### ISSUE TITLE
Refresh does not work always, even when opening the app daily. Also Contact keys that were obtained seem not to be processed correctly (no comparison of queried keys).

### ISSUE THREAD

**Issue by jangerritha** [corona-warn-app/cwa-app-ios#1001]
Referring partly to https://github.com/corona-warn-app/cwa-app-ios/issues/818 here.

The counting of days works fine. However, the risk-calculation does not seem to work correctly, even following the guidline of opening and manually refreshing the app daily. 

**Behviour:**
I opened the app almost daily since over two weeks and manually refreshed the risk-calculation. This works fine and gives me my calculated risk on ~6 of 7 days that I manually perform this procedure. The refresh never worked automatically for me. 

**But:**
On ~1 of 7 days I perform the procedure, I get the error : "Risikoermittlung nicht möglich" and I'm promted to activate the risk-calculation. I never deactivated it and the app always displayed that the risk-calculation is active since I installed it. The workaround of the bug, that works for me is the following: Deactivating and reactivating the risk-calculation 1 - 5 times will lead to a change of state in the app and i am then able to manually refresh the risk-calculation. Sometimes ,inside the risk-calculation modal, there is the button "Aktualisieren" but it won't work (This can also be seen in the attached video).

I will provide you a **video** of the behaviour and a **screenshot** of the settings of my app in the attachments

**Additionally:**
I had a look on the protocol of contact queries and something odd showed up. The app queries my contact-protocol several times (~10 times) when I manually refresh the risk-calculation. Eventhough this could be the dedicated behaviour, taking a deeper look made me wonder if something could be wrong here. If I open the contact queries, they give me a number of queried keys ("Anzahl der bereitgestellten Schlüssel" I assume this is the number of recorded keys that were near my phone.). The number of queried keys seems right for me. However, all queries say: Anzahl der abgeglichenen Schlüssel: **0**. This seems for me as if the app would not process the keys that it queried.

I will also provide a video giving some insights in the contact queries.

[information.zip](https://github.com/corona-warn-app/cwa-app-ios/files/5021835/information.zip)

**Comment by daimpi** [comment]
**Regarding the "Risikoermittlung nicht möglich" status**
Which App and iOS version are you using?

I've seen quite a few ppl with this problem and usually this post seemed to fix it for them: https://github.com/corona-warn-app/cwa-app-android/issues/637#issuecomment-655543400
This might also fix your problem with the App is not updating automatically in the background.

Otherwise this post might also help:
https://github.com/corona-warn-app/cwa-app-ios/issues/872#issuecomment-656203240


**Regarding the 14 entries per day in your contact protocol**
This is expected: Each time the app checks keys, it always compares them with the data set of the last 14 days. Each entry you see is for one day. This is described in more detail here: https://www.coronawarn.app/de/faq/#keys_matches 

The numbers you see for “Anzahl der bereitgestellten Schlüssel” is not the number of recorded keys on your phone, but rather the number of positive keys, the App downloaded from the server for one specific day within the last 14 days.

**Comment by Ein-Tim** [comment]
> However, all queries say: Anzahl der abgeglichenen Schlüssel: **0**. This seems for me as if the app would not process the keys that it queried.

I think the phrase "abgeglichene Schlüssel" is a bit misleading. 
Better to call it: "Gleiche Schlüssel" 
So when the counter there is higher than 0, f.e. 1, you've got 1 "Risiko-Begegnung".

Thats how I've understood this, correct me if I'm wrong.

**Comment by sin-azucar** [comment]
Also "Anzahl der abgeglichenen Schlüssel" is a suboptimal translation on Apple's part.
In English, it says "Matched Key Count" which is at least a little clearer: Zero matches mean that no key on your device matched the published keysets of reported infections. So "0" is actually good news. 👍 

This is also explained here: https://www.coronawarn.app/en/faq/#keys_matches

There is **no** way of getting any information (not even the count) about the keys stored on your phone.

**Comment by GPclips** [comment]
Hello @jangerritha,

thank you for sharing this issue with us and the exemplary good issue description.
Before contacting the developers, I like to ask you to share your current app version as well as the iOS version you are using.
There have been some changes and improvements regarding the ExposureNotification API in the latest iOS release. Therefore make sure your iPhone is up to date.

When you have shared the information, I would like to contact our development team.

Best Regards,
LMM

Corona-Warn-App Open Source Team

**Comment by jangerritha** [comment]
@GPclips App Version is 1.1.2, IOS Version is 13.5.1

**Comment by daimpi** [comment]
@jangerritha could you update to iOS 13.6 to see whether this fixes the problem for you?

**Comment by GPclips** [comment]
Hello @jangerritha,

please go an and do waht @daimpi suggested. Afterwards please let us know, if the error remains nor if this solved it.

Thanks,
LMM

Corona-Warn-App Open Source Team

**Comment by jangerritha** [comment]
@daimpi @GPclips I installed the update and for now the app seems to work correctly. Thank you.

**Comment by jangerritha** [comment]
@daimpi @GPclips I installed the update and for now the app seems to work correctly. Thank you.

**Comment by SonaliDK** [comment]
Hi @jangerritha ,

I see that your problem is resolved with help of @daimpi  and @GPclips , therefore I will go ahead and close this issue.

Thanks,
SD

Corona-Warn-App Open Source Team
