### ISSUE TITLE
no automated update possible

### ISSUE THREAD

**Issue by Tasmanian-Devel** [corona-warn-app/cwa-app-ios#1008]
I've three iPhones (10, 6S and SE). All these iPhones running iOS 13.6 and App version 1.1.2.
On the iPhone 10 it is only possible to sync the contact protocol manually.
The other two iPhones don't offer this update button at all and syncing every day.

I tried to reinstall the app with deleting all the app data, but this didn't solve the error.
The app got all permissions it requested.
The first time I installed the app was the release date.

**iPhone 10**

![IMG_3490](https://user-images.githubusercontent.com/17232397/89331168-982e6200-d691-11ea-8645-ed17c9b0631a.PNG)

**iPhone 6s**

![IMG_0031](https://user-images.githubusercontent.com/17232397/89331194-a0869d00-d691-11ea-8aab-70c66fbdda3b.PNG)

Thanks for your help!
Amazing job! 👍

**Comment by Ein-Tim** [comment]
> On the iPhone 10 it is only possible to sync the contact protocol manually.

The button only appears if "Hintergrundaktualisierung" is deactivated.

**Comment by Tasmanian-Devel** [comment]
Thanks for the quick response!
You're absolutely right
I only checked this setting in the app parameters and there it was set to on - but I didn't recognized that it was also greyed out.
It seems I need a theme with higher contrast 🙃

Thanks for your help!
