### ISSUE TITLE
Issue with detecting Internet Connection while phone connected with CarPlay

### ISSUE THREAD

**Issue by MacVille** [corona-warn-app/cwa-app-ios#1012]
When the iPhone is connected to an Carsterio via CarPlay the corona-warm-app can‘t detect that the iPhone still has an active Internet connection. 

Used device:
iPhone 11 Pro Max
IOS 13.6

---
Internal Tracking ID: EXPOSUREAPP-2027

**Comment by GPclips** [comment]
Hello @MacVille,

first of all, thanks for sharing your findings with the community.
This one looks like it somehow could relate to this one here: https://github.com/corona-warn-app/cwa-app-ios/issues/942.
Having said that, it still looks slightly different to me and I will get in contact with our development team.

Thank you,
LMM

Corona-Warn-App Open Source Team

**Comment by haosap** [comment]
Hi @MacVille ,
checking the internet connection constantly is a bad practice for mobile applications that don't require a constant connection. So whenever internet connection is required (e.g. when submitting yourself as infected), the app will attempt to connect and if that fails, the app will prompt that to the user. If you don't need internet connection, the app will not check it anymore. So you can be "offline", but still have active tracing displayed on the home screen. cc @inf2381 
We'll change the it in our future release.
Thanks.

**Comment by GPclips** [comment]
This issue has been marked as obsolete and will be closed now.
