### ISSUE TITLE
Configuration Loop after iPhone get restored

### ISSUE THREAD

**Issue by MacVille** [corona-warn-app/cwa-app-ios#1013]
When an iPhone get restored from an older Backup the corona-warn-app loops at the configuration and will not get to the normal App screen. 
Work-A-Round is to delete the App and loose the whole progression.

**Comment by Ein-Tim** [comment]
Please follow up in #754

**Comment by GPclips** [comment]
Hello @MacVille,

thanks for sharing the bug. There is already an ongoing discussion about that in the thread @Ein-Tim mentioned.
@Ein-Tim thanks for your support.

To run the app after your restore process has been finished, please do reinstall the app, as suggested here: https://github.com/corona-warn-app/cwa-app-ios/issues/754#issuecomment-666304765

Thanks,
LMM

Corona-Warn-App Open Source Team
