### ISSUE TITLE
App Not working on iOS 14

### ISSUE THREAD

**Issue by MderM** [corona-warn-app/cwa-app-ios#1015]
On latest beta app is not working anymore. 
Given that there are numerous devs on the planet and we have a pandemic I wonder why this does not work on preview OS?

On a fresh install one cannot get behind the notification permissions screen. 

Consecutive restarts only give a grey screen with nothing happening.

**Comment by Ein-Tim** [comment]
Take a look at the [FAQ](https://www.coronawarn.app/de/faq/#ios_14_beta)

**Comment by MderM** [comment]
Looking forward. Regarding it is vacation season...
