### ISSUE TITLE
iOS14 Beta - ENF Apps are switching automatically - Beta Test

### ISSUE THREAD

**Issue by RalphRichter** [corona-warn-app/cwa-app-ios#1029]
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is not already reported in another issue

## Expected behaviour

The new ENF Framework is now added to the settings in iOS 14 with a separate menu item in the main settings menu. When opening it it shows the active app

![IMG_71C89F4DD1D5-1](https://user-images.githubusercontent.com/67153468/89687277-3889be00-d900-11ea-84bf-c6d948f379da.jpeg)

I am using also the SwissCovid and immuni App, because I am commuting between Germany and Switzerland and immuni I have installed for my vacation (Sync should be there when the Background Sync is up and running as announced in the future)

![IMG_5AD2CF8E7A5E-1](https://user-images.githubusercontent.com/67153468/89687533-b057e880-d900-11ea-9f8c-50f35ea5f060.jpeg)

 
I have set the the CWA App as active like in the picture and after a while not observing my iPhone, the active app is switching to another one I have installed without letting me know.

![IMG_A2EA57C9AB3C-1](https://user-images.githubusercontent.com/67153468/89687827-2bb99a00-d901-11ea-8053-bbbb806eea2f.jpeg)

As a result I have to change the app back to the CWA and set it to active- The slider in CWA App to set it active I also need to reactivate.

ENFs are getting fetched from the Background Server in iOS 14. At leased on my device :-)

I would like to be part of Beta Test for CWA if there is any to help reporting back issues as tester. I know CWA is not supporting iOS14, but it will int he future and we should be prepared for it.

## Steps to reproduce the issue

1.  CWA installed
2. Install immuni https://apps.apple.com/us/app/immuni/id1513940977
3. install SwissCovid https://apps.apple.com/ch/app/swisscovid/id1509275381
4. install https://apps.apple.com/dk/app/id1516581736?l=da actually I have deleted it to see what is happening. still appearing in the list
5. upgrade your iOS Device to iOS 14 dev Beta (I am using Beta 4 build 18A5342e)
6. make sure the CWA App is set active in the settings
7. Come back after some time and you will see a different app is set active even a non installed like the danish one

I do not recall after how many hours it is switching but it does

As of now I do not know if the bug is in iOS14 dev Beta 4  but would help to test and investigate

## Technical details

- iOS Version: 14 built 18A5342e
- Device: iPhone 11 Pro Max

**Comment by Ein-Tim** [comment]
@RalphRichter 
It seems like this is a bug in the iOS 14 Beta, you could use the _Feedback Assistent_ to report it to Apple.
We will wait for the Developers how they handle it, @GPclips what do you think?

**Comment by RalphRichter** [comment]
Already shared it, but I am assuming if we would report it from there project towards Apple, would have more pressure

**Comment by Ein-Tim** [comment]
@GPclips whats your opinion to this?

**Comment by GPclips** [comment]
Hello @RalphRichter and @Ein-Tim,

the latest stable iOS version is 13.6. We recommend using stable versions, which are not in a beta state.
A region setting has been implemented recently in our Corona-Warn app, as you can check here: https://github.com/corona-warn-app/cwa-app-ios/pull/1041.
Please be patient until a region feature becomes available, to determine the Corona-Warn app by its region. The topic has been addressed.

Thanks,
LMM

Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@RalphRichter I think it would be useful to close this issue to keep the Respositorie clean. 
@GPclips said that the Topic has been addressed so...

**Comment by Ein-Tim** [comment]
@tkowark Can you close this issue?

**Comment by tkowark** [comment]
Thanks for the reminder @Ein-Tim . After consulting with the dev team, we'll close this issue for now. Apple will likely continue working on that topic and we'll have some internal tests with a later version. We'll contact you directly @RalphRichter if we need further testers.
