### ISSUE TITLE
[UX] "Risiko-Ermittlung" is non-reactive

### ISSUE THREAD

**Issue by form-follows-function** [corona-warn-app/cwa-app-ios#1033]
## Describe the bug

The activation of "Risiko-Ermittlung" doesn't trigger the Wifi or Bluetooth connectivity to be turned on or off while you have the app opened or not – system wide.

This is UX-wise a false-positive behavior which should not occur at all.

## Expected behaviour

The user expects a reactive, so to say direct, feedback when the user activates "Risiko-Ermittlung". Though the actual settings is de/activated it does not change the system-wide de/activation of Wifi and/or Bluetooth.

## Steps to reproduce the issue

- Open "Corona-Warn-App" app
- De/activate Wifi/Bluetooth
- Change settings in "Corona-Warn-App"
- Change Wifi/Bluetooth system-wide setting
- Change view inside Corona-Warn-App
- Go back to settings view: check if "Corona-Warn-App" responded to the change reactively

## Technical details

- iOS Version: Latest (13.6)
- Device: iPhone ≥ 7

## Possible Fix

- Provide a warning message at least, so the user is aware of that the in-app change does not change system wide settings immediately. Furthermore, give a hint that activation only occurs if Wifi/Bluetooth is activated – vice versa.

## Additional content
![B54286EC-BFBA-4E86-A0E0-FCE8541921FE](https://user-images.githubusercontent.com/868447/89902541-dc1bec80-dbe6-11ea-8ae8-794318192fbe.gif)

---
Internal Tracking ID: EXPOSUREAPP-2118

**Comment by GPclips** [comment]
Hello @inf2381,

thanks for reaching out. I will forward this issue to our development team for further investigation.

Thank you,
LMM

Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
Only a small note from me (just to clarify):

If you deactivate Bluetooth via the Control Centre the sending and receiving from keys from other people App's won't stop.
You have to turn off Bluetooth via Settings to stop sending&receiving.

**Comment by Ein-Tim** [comment]
See also [this](https://www.coronawarn.app/de/faq/?search=Internet#ios_logging_bt) in the FAQ.

@thomasaugsten I think we can close this now.

**Comment by form-follows-function** [comment]
@Ein-Tim Thanks for clarification. Maybe the mentioned FAQ Section can be included in the app when _deactivating_ Bluetooth via Control Center. Anyways I'll close the issue for now.
