### ISSUE TITLE
Why is version 1.2.0 not in the App Store?

### ISSUE THREAD

**Issue by mss1010** [corona-warn-app/cwa-app-ios#1035]
Version 1.2.0 is marked as latest release since 4 days. Why is it not available yet in the app store?

**Comment by GPclips** [comment]
Hello @mss1010,

thanks for reaching out. I will discuss its internally and get back to you as soon as it has been clarified.

Thank you,
LMM

Corona-Warn-App Open Source Team

**Comment by GPclips** [comment]
Hello @mss1010,

the new version will be available this week.

Thanks,
LMM

Corona-Warn-App Open Source Team

**Comment by HeiDasGri** [comment]
Just seen. It is available now!
