### ISSUE TITLE
No push notification for red risk encounter

### ISSUE THREAD

**Issue by daimpi** [corona-warn-app/cwa-app-ios#1053]
## Avoid duplicates
Checked

## Describe the bug
Two people had a "red/increased risk" encounter, but didn't receive a push notification and only noticed their status when opening their app by chance.

## Expected behaviour
A push notification should be prominently displayed as soon as such an encounter is detected.

## Steps to reproduce the issue

1. Have a red risk-encounter
2. Don’t open the app manually
3. You’ll not be notified of your risk encounter

You can find more details of the story on @jonicious ’s blog: https://jonas.re/posts/corona-warn-app/ and in this [Twitter thread](https://twitter.com/jonicious/status/1293984243111145473).

## Technical details

- iOS Version: 13.5.1  & 14 beta4 (public)
- CWA Version: 1.2.0 (both)
- Device: Iphone XS (both)

## Additional context

If you need additional Information, feel free to contact @jonicious :)

---
Internal Tracking ID: EXPOSUREAPP-2209

**Comment by thomasaugsten** [comment]
We recommend to use 13.6.1 for a stable notification. Because the notification is a local notification triggered in the background task. Only the 13.6.1 provides a stable background task.

**Comment by jonicious** [comment]
@daimpi First of all, thanks for opening the issue!

Indeed, I should have updated my phone to 13.6.1 already and of course iOS 14.0 beta is still unstable. Maybe some more useful information:

I opened the app at 11:52. It then updated and showed me the new status.

For my friend, it was already updated at 10:54 but he did not receive a notification. After I talked to him, he opened the app and saw the status. So for him the background task was already performed. Still, it could be related to an iOS 14 issue. Thought it would be useful to share though.

**Comment by thomasaugsten** [comment]
We will check this. We will test this on iOS 14 but can your friend double check that notifications for the CWA are active? Was your friend as well on iOS 14?

**Comment by jonicious** [comment]
Sure, I'll let him know and come back with an answer! Only he runs iOS 14 beta, I run 13.5.1 (but upgrading tonight to 13.6.1).

**Comment by jonicious** [comment]
Just confirming that my friend also had push notifications enabled on his iPhone running iOS 14.
![D9913DD1-5D2A-4002-81E0-63F254D5CF83](https://user-images.githubusercontent.com/2546998/90219841-3bf0de00-de07-11ea-8921-63ca5e68466b.jpeg)

**Comment by thomasaugsten** [comment]
We will add iOS14 in our test environment  and try to reproduce this. Thanks for you support here.

**Comment by jonicious** [comment]
FYI: Upgraded to iOS 13.6.1 and just received the push notification with a negative test result. This worked out pretty well. Thanks for all the work, much appreciated!
