### ISSUE TITLE
App does not work any longer if GPS is deactivated [Android]

### ISSUE THREAD

**Issue by bhintermayr** [corona-warn-app/cwa-app-ios#1055]
Error occurs on different mobile devices.

Error message 'Standortdienste deaktiviert' . If I am turning on the GPS (which usually not do) the app works and states "Risikoermittlung aktiv".

This behaviour is new.

**Comment by Ein-Tim** [comment]
Issues for Android please report [here](https://github.com/corona-warn-app/cwa-app-android)

**Comment by Ein-Tim** [comment]
@GPclips & @SebastianWolf-SAP could you transfer this to the Android Reposetorie?

**Comment by bhintermayr** [comment]
Not necessary. I did it manually. Sorry
