### ISSUE TITLE
max 100 Einträge im Begegnungsprotokoll (100entries max in Exposure log)

### ISSUE THREAD

**Issue by GisoSchroederSAP** [corona-warn-app/cwa-app-ios#1056]
Seems, this is linked to or doublette of [https://github.com/corona-warn-app/cwa-app-ios/issues/934] 
Original email: "Guten Tag,

ich glaube die Aufzeichnungstiefe der Corona-Warn-App funktioniert immer noch nicht korrekt. Nur max 19 Kontaktpersonen werden für max. 8 Tage gespeichert.  Das reicht nicht aus. Im Begegnungsprotokoll sind nur

- max. 19 IDs,
- max 100 Einträge,
- max 8 Tage,

gespeichert.

Systemvoraussetzungen:

- App Version 1.2.1 (0) (Build" : "17G80)
- IOS 13.6.1, iPhone SE (DeviceProductType" : "iPhone8,4)
- Hintergrundaktualisierung ist aktiv

Mit freundlichem Gruß
Bernd Fluhrer
 "

[ExposureChecks-2020-08-16.json.zip](https://github.com/corona-warn-app/cwa-app-ios/files/5081350/ExposureChecks-2020-08-16.json.zip)

**Comment by tkowark** [comment]
Yes, this is indeed a duplicate of #934 

And it contains some misunderstandings. The log does not store contact persons and both the 19IDs and 8 days are a consequence of the 100 entry limit. Could you please share this FAQ entry with the original reporter? https://www.coronawarn.app/de/faq/#keys_matches
