### ISSUE TITLE
Risk encounter disappeared after 4 days

### ISSUE THREAD

**Issue by eryig** [corona-warn-app/cwa-app-ios#1061]
## Avoid duplicates

* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is not already reported in another issue

## Describe the bug

A risk encounter shown up on 11.08. did not show up after 4 days. Looking at the logs, I see that the risk match of the same exposure check changed to 0 on 15.08.

## Expected behaviour

A risk encounter should disappear after 14 days, not after 4 days. If there might be circumstances where the MatchCount of an exposure check can change, this should be mentioned in the [FAQ](https://www.coronawarn.app/en/faq/).

## Steps to reproduce the issue

Looking at the exposure export, I see the same exposure check with a MatchCount of 1 from 11.08. to 14.08. From 15.08. until today (17.08.) the MatchCount is 0

Exposure Checks from 11.08.-15.08. (hash changed to "xyz")

Exposure Check on 11.08.:
~~~json
      {
        "Hash" : "xyz",
        "RandomIDCount" : 2380,
        "MatchCount" : 1,
        "DataSource" : "de.rki.coronawarnapp",
        "Timestamp" : "2020-08-11 09:08:38 +0200"
      },
~~~
Exposure Check on 12.08.:
~~~json
      {
        "Hash" : "xyz",
        "RandomIDCount" : 2380,
        "MatchCount" : 1,
        "DataSource" : "de.rki.coronawarnapp",
        "Timestamp" : "2020-08-12 09:17:17 +0200"
      },
~~~
Exposure Check on 13.08.:
~~~json
      {
        "Hash" : "xyz",
        "RandomIDCount" : 2380,
        "MatchCount" : 1,
        "DataSource" : "de.rki.coronawarnapp",
        "Timestamp" : "2020-08-13 11:32:54 +0200"
      },
~~~
Exposure Check on 14.08.:
~~~json
      {
        "Hash" : "xyz",
        "RandomIDCount" : 2380,
        "MatchCount" : 1,
        "DataSource" : "de.rki.coronawarnapp",
        "Timestamp" : "2020-08-14 12:17:56 +0200"
      },
~~~
Exposure Check on 15.08.:
~~~json
      {
        "Hash" : "xyz",
        "RandomIDCount" : 2380,
        "MatchCount" : 0,
        "DataSource" : "de.rki.coronawarnapp",
        "Timestamp" : "2020-08-15 14:12:48 +0200"
      }
  ~~~

## Technical details

- iOS Version: 13.6.1 (13.6 until 16.8.2020)
- Device: iPhone 7

## Additional context

The risk encounter mentioned above was a 'low risk' encounter

**Comment by thomasaugsten** [comment]
The matchcount disappeared because after 14 days your collected random ids will be deleted by iOS. This mean the rpi was 11 days old this the reason for a low risk and after 14 days it was deleted this mean 0 risk exposure

**Comment by daimpi** [comment]
This is expected behavior:

each package contains all the keys of all the ppl who uploaded their keys that day. The package which contained the key you matched with had 2380 keys and is therefore from the 10.08 (cf. [here](https://micb25.github.io/dka/#diagnoseschl%C3%BCssel)). It therefore contains keys for up to 14 days in the past from that date (i.e. 27.07). That your key disappeared on the 15.08 means, that you your encounter with the person who later tested positive must have been 14 days before that i.e. on the 01.08.

Keys older than 14 days are usually not relevant for determining infection risk and are therefore discarded as @thomasaugsten stated, that's the reason why your risk encounter disappeared.

**Comment by eryig** [comment]
Thank you for your quick responses and the additional information. That explains the behavior. Unfortunately, there was no information in the App about the age of the risk encounter. But it looks like this is already tracked in another issue

**Comment by daimpi** [comment]
> Unfortunately, there was no information in the App about the age of the risk encounter. But it looks like this is already tracked in another issue

Yes, this is tracked here: https://github.com/corona-warn-app/cwa-backlog/issues/23 🙂
