### ISSUE TITLE
Background checks are sometimes incomplete

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#1063]
## Avoid duplicates

* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is not already reported in another issue

## Describe the bug

As reported by me [here](https://github.com/corona-warn-app/cwa-app-ios/issues/916#issuecomment-673040325) and by [@alanrick](https://github.com/alanrick)[here](https://github.com/corona-warn-app/cwa-app-ios/issues/916#issuecomment-675098078) the App sometimes don't download the correct amount of files in the background.
 
When you open the App manually after the incomplete check, 14 (or more) checks are done.

Today I had that behaviour again. 
12 checks were performed in the background, 14 more after I opened the App.

## Expected behaviour

The App should download the correct amount of files (in my case 14).

## Steps to reproduce the issue

I couldn't find any pattern. 
My only guess is that it could have to do with the internet connection, I had an unstable connection the first time this occurred. 

## Technical details

- iOS Version: 13.6/13.6.1
- Device: iPhone XR
- CWA Version: 1.2.1

## Possible Fix

No idea.

## Additional context

For me and [@alanrick](https://github.com/alanrick) this wasn't a problem because we opened the App, but I wonder what would have happened if we wouldn't have opened the App.

It should be ensured that even with a weak internet connection (if that's the problem) all background checks are done.

## Screenshots 

![image](https://user-images.githubusercontent.com/67682506/90536784-cecda780-e17c-11ea-9167-da132a26458e.jpeg)

![image](https://user-images.githubusercontent.com/67682506/90536771-c9705d00-e17c-11ea-81fa-ac5da3cfda52.jpeg)

---

![image](https://user-images.githubusercontent.com/67682506/90536825-dab96980-e17c-11ea-9d23-cbbc7347bfb9.jpeg)

![image](https://user-images.githubusercontent.com/67682506/90536846-e1e07780-e17c-11ea-9035-82386eca665c.jpeg)

**Comment by Jens07** [comment]
I would like to observe that "alanrick" wrote that he uses iOS 13.6 - which is not the newest version - and had deactivated the background app refresh.

**Comment by Ein-Tim** [comment]
@Jens07 you're right, but I am
Using iOS 13.6.1 and it happened today again.

**Comment by thomasaugsten** [comment]
This can sometimes happen that the ENF process can be interrupted normally the next try after 2hours is successful. If this happens continuously please inform us here.

**Comment by Ein-Tim** [comment]
@thomasaugsten 
Okay, If it happens again I will wait 2 (or more) hours and report back.
Thank you.

**Comment by Ein-Tim** [comment]
Soo, update from me:
Yesterday the check included only 9 files on the first try, than 4 more at the second time and 1 more at the third time.
This is a little bit confusing but in whole this are 14 files and everything was done in the background, how @thomasaugsten said.

---

![image](https://user-images.githubusercontent.com/67682506/90986230-7bdf6000-e581-11ea-98a0-34f7ab36ef45.png)

---

Thanks for all your (fast) replies, highly appreciated 👍
Will close this soon
