### ISSUE TITLE
Shouldn’t the App show the normal card instead of „Risiko-Ermittlung gestoppt“ if the phone has no internet connection?

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#1070]
## Avoid duplicates
* [ ] Question is not already answered in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Question has not already been asked in another issue

## Your Question
If you have no Internet connection, the App shows "Risiko-Ermittlung gestoppt".
Shouldn't there just be the normal risk card (green (low risk) or red (high risk))?

## Additional Information
I remember an issue with the title "App goes into false restricted mode[...]" but I couldn't find it anymore.
So if you point me to that Issue, that would be perfect.

Thanks for all the great work guys! Keep it up!

**Comment by tkowark** [comment]
That issue was moved to the backlog (https://github.com/corona-warn-app/cwa-backlog/issues/1) and the team is already on that.
