### ISSUE TITLE
Only one test supported within the app at the same time

### ISSUE THREAD

**Issue by olafthecruel** [corona-warn-app/cwa-app-ios#1087]
For families with small children who are tested it would make a lot of sense to have the chance to monitor multiple tests in the app. At the moment it is only supported to run one test at the same time.

Scenario: 2 kids who are tested regularly in the kindergarden by the Gesundheitsamt. Of course, they do not have mobile phones yet. However, as we are a "family cluster" (i.e. if my kids are positive I am pretty sure that I am positive, too) it would make a lot of sense to bind their tests to the parents mobile devices.
But it is only possible to bind one test to the device at the same time. In addition, I did not recognize that the QR code is a one time pad. So when I deleted one test to check the result of the other test, I was not able to check the first test again (and also not the second one as i deleted that to check the first one again). So just deleting one test and creating another is not a solution here.

**Comment by Ein-Tim** [comment]
Related to [this open Issue in the Wishlist Repo](https://github.com/corona-warn-app/cwa-wishlist/issues/109)

**Comment by tkowark** [comment]
Yes, feature requests, especially for both apps, are living in the wishlist repository. Please continue the discussion there.

**Comment by daimpi** [comment]
Regarding the deletion of test results see those two issues:
https://github.com/corona-warn-app/cwa-wishlist/issues/144
and
https://github.com/corona-warn-app/cwa-app-android/issues/960
