### ISSUE TITLE
Issue: „Risiko-Ermittlung nicht möglich“

### ISSUE THREAD

**Issue by xander1401** [corona-warn-app/cwa-app-ios#1094]
## Avoid duplicates

* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is not already reported in another issue

## Describe the bug

Since yesterday the app stopped working completely. I tried to find a fix but I couldn’t. In this time there was no update neither the device or the app.
For further information please watch this video: https://drive.google.com/file/d/1D9AF0b2T1UWUuX2iGbfFhXCy1wkdgUOR/view?usp=drivesdk

## Expected behaviour

Normal operation like before and on other devices.

## Steps to reproduce the issue

That’s the question. I did nothing but it failed. Please ask if you have any guess.

## Technical details

- iOS Version: 13.6.1
- Device: iPhone 8
- App: 1.2.1(0)

**Comment by Ein-Tim** [comment]
So you said you tried to fix it, could you please descrieb how you tried it?

**Comment by xander1401** [comment]
I did the possible fix from #911 and tried switching everything on and off. I didn’t reinstalled it because I don’t want to lose the data

**Comment by Ein-Tim** [comment]
So you also restarted your phone already? 😉

**Comment by xander1401** [comment]
Yes

**Comment by Ein-Tim** [comment]
Ok good, was "Risiko-Ermittlung" deactivated for more than 24h (switching off Bluetooth, activated Flight Mode, etc.)?

**Comment by xander1401** [comment]
No, everything was normal

**Comment by Ein-Tim** [comment]
You said it stoped working yesterday, but the App says the last update (download from keys) was on the 24.08.20, so it stoped Tuesday, this is very weird. Can you go into "Einstellungen->Datenschutz->Analyse&Verbesserung->Analysedaten" and see if there are files named "ENA"?

**Comment by Ein-Tim** [comment]
Btw is "Background App Refresh" activated?

**Comment by xander1401** [comment]
There is no “ENA” file. Background App Refresh was off and is now on but I looked every day in the App since the release and it worked perfectly

**Comment by Ein-Tim** [comment]
Ok, so you now activated it, could you wait some time and see if this solves the problem, sometimes it [does](https://github.com/corona-warn-app/cwa-app-android/issues/637#issuecomment-655543400)

**Comment by xander1401** [comment]
Thx. I will post the result tomorrow

**Comment by xander1401** [comment]
Ok, that was an easy fix. Started working again a minute ago. Great job!
