### ISSUE TITLE
App obsolete with Exposure Notification Express?

### ISSUE THREAD

**Issue by mss1010** [corona-warn-app/cwa-app-ios#1107]
## Avoid duplicates
* [x] Question is not already answered in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Question has not already been asked in another issue

## Your Question
Now, that Exposure Notification Express is available with iOS 13.7 will this app be obsolete in the mid term?
Is it planned to be replaced by the iOS native contact tracing?

**Comment by Ein-Tim** [comment]
No, afaik the App is still needed to download new Keys from the Server, report you infected, etc. 
The only change is that you are now able to record your encounters without the App.

**Comment by cfritzsche** [comment]
I also doubt that Apple will take up the test result notification process.

**Comment by mss1010** [comment]
According to this documentation https://developer.apple.com/documentation/exposurenotification/supporting_exposure_notifications_express
there is NO app needed anymore.

What is still needed, is a Test verification server and a key server. Which we already have. So, in my understanding, the RKI just needs to decide to use it, and switch over to the new central framework.

**Comment by cfritzsche** [comment]
In the documentation you linked there is no mention of a test result process through the app or indeed any communication from lab or public health authority to the user through the app. They just support a verification server checking for a positive test before upload, but the test it outside this system.

**Comment by mss1010** [comment]
> 
> 
> In the documentation you linked there is no mention of a test result process through the app or indeed any communication from lab or public health authority to the user through the app. They just support a verification server checking for a positive test before upload, but the test it outside this system.

This are the steps 2 - 4 in the above link:

> 2. The test center or other health care provider determines that the user has a positive test result and reports it to the PHA.
> 3. The PHA generates a verification code using the test verification server.
> 4. The PHA sends the verification code to the user. The code may be emailed, read over the phone, or provided as a clickable deep link in a text message.

This is already now independent of the app. The test result is currently given to the user via a QR code or a TELE TAN via the hotline. In the end, it´s just some kind of code that you are receiving (outside of the app) and you currently enter it in the app.

With the new framework, you would enter this code not in an app. but in iOS directly.

**Comment by Ein-Tim** [comment]
Yeah, @mss1010, I think you are right, this is also what the Verge article says...
So the original question you asked is right, will the RKI adopt the "Exposure Notifications Express" or not?

**Comment by cfritzsche** [comment]
> 
> This are the steps 2 - 4 in the above link:
> 
> 
> 
> > 2. The test center or other health care provider determines that the user has a positive test result and reports it to the PHA.
> 
> > 3. The PHA generates a verification code using the test verification server.
> 
> > 4. The PHA sends the verification code to the user. The code may be emailed, read over the phone, or provided as a clickable deep link in a text message.
> 
> 
> 
> This is already now independent of the app. The test result is currently given to the user via a QR code or a TELE TAN via the hotline. In the end, it´s just some kind of code that you are receiving (outside of the app) and you currently enter it in the app.
> 

I disagree. CWA does not merely generate and verify a code for a positive test. It does register a QR code for a sample that has yet to be tested and talks to the backend just for the test result. That is not mentioned anywhere in that article. You could move that to another app and move the notification part directly onto the OS, but then you would still have the unnecessary indirection of receiving the test result through one app, contacting the health authority and then entering the verification code coming from them in the OS..

**Comment by mss1010** [comment]
> I disagree. CWA does not merely generate and verify a code for a positive test. It does register a QR code for a sample that has yet to be tested and talks to the backend just for the test result. That is not mentioned anywhere in that article. You could move that to another app and move the notification part directly onto the OS, but then you would still have the unnecessary indirection of receiving the test result through one app, contacting the health authority and then entering the verification code coming from them in the OS..

Ok good point. I missed, that the QR code starts already earlier in the process before the test result is available.
So, that means, the Express framework starts at the point when a test result is positive. In that case the user would not need to enter the first code, but only a code he gets, when a test result was positive.

But this raises other questions regarding the workflow. I guess that´s what you meant. Now, if a lab is connected to the test result server, the positive result is checked in theory once a day. But with the express framework, the user needs to receive the test result through another way, which is not defined, and could possible take longer.

**Comment by Marco2907** [comment]
Hi @mss1010, thanks for sharing your content. I would close this topic because this is similar with the #174 in the wishlist repo. 

Thanks,
MP

Corona-Warn-App Open Source Team
