### ISSUE TITLE
Unexpected Behaviour after Factory Reset of Iphone and Restoring an older Backup

### ISSUE THREAD

**Issue by hkreissl** [corona-warn-app/cwa-app-ios#1108]
## Avoid duplicates

* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x ] Bug is not already reported in another issue

## Describe the bug

After Factory reset of IPhone X and restoring an older backup (7 days old) a list of 14 hashcodes appears even if no device was nearby after resetting the phone at this time.

Situation: On suggest of apple support i must reset my iphone. Before resetting the IPhone i have green screen with "1 Risiko-Begegnung mit niedrigem Risiko". The Risk meeting appeared on this phone  and the iphone of my partner one day before reset with the same key.
{
      "Hash" : "E454EE196AA5AC1E135BD39DE7F1304C6E68D2ABBA6C2DF6C5D9984C3CB71F64",
      "RandomIDCount" : 3339,
      "MatchCount" : 1,
      "DataSource" : "de.rki.coronawarnapp",
      "Timestamp" : "2020-08-30 10:19:34 +0200"
 }
After resetting to factory settings and importing the backup from 22.08.2020, enabling the risk analysis it shows 14 keys including this key with matchcount 0 see:
[ExposureChecks-2020-09-01.txt](https://github.com/corona-warn-app/cwa-app-ios/files/5160389/ExposureChecks-2020-09-01.txt)
The contact with the device with that hash must be on 29.08.2020. 
After reset the app shows that risk analysis is active since 14 days and that there are "Keine Risiko-Begegnung"

## Expected behaviour

1.) Only one key in the log or all keys included in the backup from 22.8 
2.) Same matchcount on the key above or the key should not be present

## Steps to reproduce the issue

1. Have an entry with low risk in the app and on older backup not containig this key
2. Reset the device to factory settings
3. Restore older backup
4. Enable risk analysis
5. after app update explore the log 

## Technical details

- iOS Version:13.6.1
- Device: IPhone X

## Additional context

---
Internal Tracking ID: [EXPOSUREAPP-2455](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-2455)

**Comment by thomasaugsten** [comment]
Our current information are that stored RPIs/TEKs are not included in a backup. Because it is a security issue to have the same RPIs/TKEs on different devices.

**Comment by hkreissl** [comment]
I beleave the data are not from the backup. 
The data survive the factory reset so bug feature or documentation🤔

**Comment by Marco2907** [comment]
Hi @hkreissl , thanks for sharing your content. I will keep this issue to discuss this with our development team and looking forward to including this after a solution approach to the FAQ's. I will come back to you as soon as possible. 

Thank you.

Best,
MP

Corona-Warn-App Open Source Team

---
Internal Tracking ID: EXPOSUREAPP-2455

**Comment by Tho-Mat** [comment]
The key file with the match contains key from 15.08 to 28.08. 
So you "low risk" contact happend in that date interval.
So even your contact keys had been saved on 22.08. The time 23.08 to 28.08 would not be in the backup.
Also yesterday all keys 15.08-20.08 have been deleted.
So that remains in a small window 21.08-22.08 of valid keys in the backup (if there are any)

But i wonder: why the app show 14 aktive days **?**
Maybe the app does not check if the device was active **for** 14 days only **since** **?**

I read some other issues and there are some unexpected behaviors after a backup and restore.

**Comment by hkreissl** [comment]
Hi folks,  the contact was surely on the 29.8.  shown on two different devices on 30.8. first time with identical hash. So for sure it was not in the backup.
