### ISSUE TITLE
App zeigt kein Fehler an wenn keine Internetverbindung vorhanden ist

### ISSUE THREAD

**Issue by Mehaara** [corona-warn-app/cwa-app-ios#1117]
## Avoid duplicates

* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is not already reported in another issue

## Technical details

- iOS Version:
- Device:

**Comment by Ein-Tim** [comment]
Schau mal [hier](https://www.coronawarn.app/de/faq/?search=iOS+14#ios_14_beta) in die FAQ

**Comment by ndegendogo** [comment]
@Mehaara which iOS 14 version exactly?

**Comment by Ein-Tim** [comment]
@abeutel 
Take a look at my comment [here](https://github.com/corona-warn-app/cwa-backlog/issues/1#issuecomment-687175144)
The only difference is that you experience the behaviour with active Internet Connection too.

**Comment by abeutel** [comment]
@Ein-Tim OK, I see! The app does not accept/use custom SSL certificates from iOS System Profiles when SSL/TLS interception is enabled in corporate networks. In an unrestricted connection (no Wifi/VPN) it works.

**Comment by Ein-Tim** [comment]
Yes, first of all this is very confusing for the normal user and somehow also contradictory.
This should be reworked.

**Comment by Ein-Tim** [comment]
@thomasaugsten 
The problem is not only with "SSL" Certificates but when the App has no internet connection it now shows in Version 1.3.0 [this](https://github.com/corona-warn-app/cwa-backlog/issues/1#issuecomment-687175144) screen.
Are you on that?

**Comment by svengabr** [comment]
Hello everyone. I will close this issue since there isn't much new information in the original issue description here and the fact that there is already a similar issue in the backlog where the team is already working on:  https://github.com/corona-warn-app/cwa-backlog/issues/1

Best regards,
SG

Corona-Warn-App Open Source Team
