### ISSUE TITLE
Bitte die Warn App auch in anderen App Stores zur Verfügung stellen. Menschen, die zwar in Deutschland wohnen (oder als Touristen kommen), aber nicht im deutschen Store eingeloggt sind, können die Warn App gar nicht herunterladen. 

### ISSUE THREAD

**Issue by Mehaara** [corona-warn-app/cwa-app-ios#1119]
## Avoid duplicates

* [ ] This issue has not already been raised before
* [ ] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

**Comment by Ein-Tim** [comment]
Bitte schau dir [diesen](https://www.coronawarn.app/de/faq/#international) Punkt in den FAQs an.

**Comment by tkowark** [comment]
@Ein-Tim yes, that makes sense. I will close that.

Just a quick note: I am transitioning out of the project, so please notify @svengabr or @mtb77 in the future when you spot such issues.

Thanks again for all your dedication and efforts in this project! You made my (and our) life so much easier by keeping an eye on all the issues coming in and reminding us of the things that might have slipped through the cracks :)

**Comment by daimpi** [comment]
@tkowark I can only second what @Ein-Tim said: thanks for all your great work, it's a pity that you're leaving 😢. I wish you all the best for your future projects ❤️.
