### ISSUE TITLE
App on iPhone in a "endless loop"

### ISSUE THREAD

**Issue by slotosch** [corona-warn-app/cwa-app-ios#1122]
I installed the App on my iPhone 11. It worked. The iPhone was replaced by an identical one and restored from the backup.
Now my Corona App is in an endless loop with the following sequences
1: "Gemeinsam Corona bekämpfen"-page
Press default: "Los geht's"
2: "Datenschutz" page
Press default "weiter"
3: "Wie Sie die Riskio Ermittlung ermöglichen" page
Press default "weiter"
4: "Falls Sie Corona-positiv getestet wurden" page
Press default "weiter"
5: Warnungen erhalten, Risiken erkennen" page
Press default ""weiter"
back to page 1

No plan how to escape

**Comment by svengabr** [comment]
Duplicate of #754
