### ISSUE TITLE
Is it expected under iOS 13.7 that only 13 new files are downloaded?

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#1123]
## Avoid duplicates
* [x] Question is not already answered in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Question has not already been asked in another issue

## Your Question
Under iOS 13.7 the App always downloads only 13 new files for each check, now I wanted to ask if this is expected behaviour.

**Comment by mss1010** [comment]
Ok thanks for the explanation. This fits to the time pattern of my last download times.

**Comment by Ein-Tim** [comment]
Thanks for the explanation @Tho-Mat 
I knew about this bug (and yes my checks were always at 23:xxh in the last time so...) but I opened this Issue because under iOS 13.6/13.6.1 I've always got all (or more 😉) files, even between 22:00h-02:04h, so now I was a little Bit concerned.
Thanks for your help!
