### ISSUE TITLE
V 1.3.0 Zähler bei deaktivierter Hintergrundaktualisierung ist nach verlassen der App pausiert

### ISSUE THREAD

**Issue by webdesignweisshart** [corona-warn-app/cwa-app-ios#1124]
## Avoid duplicates

* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is not already reported in another issue

## Technical details

- iOS Version:
- Device:

## Additional context

Internal Tracking ID: EXPOSUREAPP-2547

**Comment by Ein-Tim** [comment]
Whats the problem with the update?

**Comment by webdesignweisshart** [comment]
In Version 1.3.0 ist die Aktualisierung schon wieder kaputt. Der Countdown zur manuellen Aktualisierung "hängt", sodass ich nie den Link zur manuellen Aktualisierung zu sehen bekomme. (Automatische Aktualisierung ist für alle Apps deaktiviert)
iOS 13.7 on iPhone 11 Pro Max

**Comment by Ein-Tim** [comment]
Okay, könntest du vielleicht einen Screenshot machen und hier _posten_?
Danke

**Comment by webdesignweisshart** [comment]
![IMG_5653](https://user-images.githubusercontent.com/59532422/92301907-da381580-ef67-11ea-9868-a3618f494446.jpg)

**Comment by Ein-Tim** [comment]
Okay, danke für den Screenshot.
Hast du schonmal dein handy neu gestartet? ￼

**Comment by webdesignweisshart** [comment]
@Ein-Tim Danke für den Hinweis. Aber ich brauche keinen Support, ich weiß mir schon zu helfen. ;-) Möglicherweise trifft dies auf die anderen 19,9 Mio User der App nicht zu. Deshalb dachte ich, ich könnte hier einen Bug melden.
NB: Hintergrundaktualisierung erlauben und dann wieder deaktivieren: Eine Methode, die bei Apple häufig funktioniert. In diesem Fall aber nicht.

**Comment by Ein-Tim** [comment]
Okay, natürlich kannst du das hier melden. 
Nur weils mich interessiert: 
Hast du den Countdown wieder zum laufen bekommen? 

Sonst kann @thomasaugsten hier vielleicht weiterhelfen.

**Comment by webdesignweisshart** [comment]
@Ein-Tim Nein. Mit deaktivierter Hintergrundaktualisierung hängt der Countdown, sobald die Warn-App einmal in den Hintergrund geht. Interessant: Wenn ich die App aus dem App-Umschalter lösche, und neu aufrufe, dann läuft der Countdown wieder. Aber nur, bis ich die App wieder schließe.
Wie schon gesagt: Ich fürchte, dass der Durchschnitts-User dieses Verhalten entweder gar nicht bemerkt, oder aber es ihm egal ist, er den Bug ignoriert, oder die App deinstalliert.

**Comment by thomasaugsten** [comment]
Das bedeutet der Counter zählt nicht runter? Auch nach dem beenden und neustarten der app bleibt er fix auf 11:30:16 ?
Können Sie bitte nochmal feedback geben wenn die 24h theoretisch abgelaufen sind ob der Counter verschwunden ist und Sie aktualisieren können.

**Comment by thomasaugsten** [comment]
Wir werden versuchen das Problem zu reproduzieren und schnell möglich zu beheben.

**Comment by webdesignweisshart** [comment]
@thomasaugsten 
Wie schon geschrieben: Wenn ich die App aus dem App-Umschalter lösche (Kaltstart), dann läuft der Countdown, mit aktualisiertem Wert. Aber nur bis die App das nächste mal geschlossen wird. Es genügt also nicht, was in allen Medien als Workaround beschrieben wird, die App einmal täglich aufzurufen.
Ok, ich melde mich dann morgen, bzw. heute nach 21:54 (siehe Screenshot). NB: Auch ein Neustart des iPhone (Kaltstart) behebt das Problem nicht.

**Comment by Ein-Tim** [comment]
Ich kann das Problem auf meinem iPhone XR mit iOS 13.7 & Version 1.3.0 der CWA reproduzieren. 
Einfach Hintergrundaktualisierung der App ausschalten, die App öffnen, (wie von @webdesignweisshart beschrieben) einmal in den Hintergrund schicken -> Countdown hängt.

**Comment by webdesignweisshart** [comment]
@thomasaugsten siehe Screenshot
![IMG_5654](https://user-images.githubusercontent.com/59532422/92313356-151f6500-efcb-11ea-9b14-cfa3a2bce78c.jpg)

**Comment by webdesignweisshart** [comment]
Nachtrag: Die CWA hat gestern doch noch im Hintergrund selbstätig aktualisiert. Um 23:26 Uhr. Keine Ahnung, weshalb gerade um diese Zeit. Und jetzt hängt der Countdown wieder. Das ist zwar besser als nichts, aber die Anzeige mit dem hängenden Countdown ist sehr irritierend.

**Comment by thomasaugsten** [comment]
Wir arbeiten dran und werden das zeitnah korrigieren

**Comment by webdesignweisshart** [comment]
Nachtrag, nur zur Info: Auch mit iOS 14 verhält sich die CWA wie oben beschrieben.

**Comment by thomasaugsten** [comment]
Wir können das auf unseren Geräte nicht nachvollziehhen. Gibt es noch eine Besonderheit außer dass du die Hintergrundaktualisierung deaktiviert hast

**Comment by webdesignweisshart** [comment]
@thomasaugsten Jetzt versteh' ich gar nichts mehr.  Vor 11 Tagen hast du geschrieben: "Wir arbeiten dran ..." Ich dachte, du könntest das von mir beschriebene Problem nachvollziehen, wie auch Ein-Tim vor 12 Tagen.
Also noch einmal:
Hintergrundaktualisierung der App ausschalten, die App öffnen,  einmal in den Hintergrund schicken -> Countdown hängt. Und zwar auch mit iOS 14 auf dem iPhone 11 Pro Max

**Comment by Ein-Tim** [comment]
Update von meiner Seite, ich kann das Problem nun auf iOS 14.0 auch nicht mehr nachvollziehen. Der Countdown scheint zu funktionieren

**Comment by webdesignweisshart** [comment]
Hm, dann bin ich wohl der einzige mit diesem Bug. Mir ist nicht bewusst, dass ich mein iPhone mit irgendwelchen besonderen Einstellungen betreibe, außer eben der deaktivierten Hintergrundaktualisierung. Da die Aktualisierung der CWA ja trotz irreführendem Countdown funktioniert, ist es ja auch nicht weiter tragisch.
Off topic: Mal schau'n, was iOS 14 sonst noch an Überraschungen bereit hält.

**Comment by thomasaugsten** [comment]
Wir denken das wir die Situation unter bestimmten Bedingungen reproduzieren können. Wir arbeiten daran das Verhalten zu verstehen und es dann zu lösen.

**Comment by webdesignweisshart** [comment]
Nur der Vollständigkeit halber: Mit dem heutigen Update hat sich keinerlei Änderung ergeben. Das Problem besteht unverändert.

**Comment by Ein-Tim** [comment]
Die PR dazu #1194 ist auch erst für Version 1.5.0 geplant... 
Wieso auch immer?

**Comment by GPclips** [comment]
This issue has been solved and will be closed now.

**Comment by GPclips** [comment]
Hello community,

since this hasn't been deployed yet, I will reopen the issue.
This will be deployed as soon as possible.

Thanks,
LMM

Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@webdesignweisshart 
Can you still reproduce this behavior with Version 1.5.0 of Corona-Warn App?

**Comment by webdesignweisshart** [comment]
Version 1.5.0 is ok. No issues.

**Comment by Ein-Tim** [comment]
So than I would consider this Issue as solved, could you close it @webdesignweisshart? 
Thank you!

**Comment by webdesignweisshart** [comment]
Well done, CWA team.
