### ISSUE TITLE
No exposure report updates 😩

### ISSUE THREAD

**Issue by richardhj** [corona-warn-app/cwa-app-ios#1125]
## Avoid duplicates

* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is not already reported in another issue

## Describe the bug

When opening the app, it complains about the exposure report already being carried out. 
When closing the alert, the status remains being ”unknown”.

![image](https://user-images.githubusercontent.com/1284725/92321167-395d5f00-f028-11ea-973c-f87a923d443f.png)
![image](https://user-images.githubusercontent.com/1284725/92321169-3cf0e600-f028-11ea-9a17-37c675cd1ef3.png)

## Expected behaviour

The App should update their data. 

## Steps to reproduce the issue

1. Open app,
2. close alert 

## Technical details

- iOS Version: 13.5.1
- Device: iPhone
- App v1.3.0

## Additional context

Maybe the app is pushing the data (the alert indicates) but not pulling and therefore shows an”unknown status”.

There is an iOS update available but the issue should not occurred nonetheless. 

The issue persists since ~3 days.

**Comment by thomasaugsten** [comment]
You have to update to iOS 13.7 to solve this issue

**Comment by richardhj** [comment]
If CWA v1.3.0 is only compatible with iOS v.13.7, it should not be installable on iOS v13.5, no?

**Comment by thomasaugsten** [comment]
No it's compatible but iOS 13.7 includes a lot of fixes from Apple side for example removing the rate Limit

**Comment by richardhj** [comment]
Issue fixed on iOS 13.7. 👍
