### ISSUE TITLE
"Active Days" go down or are stuck

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#1127]
## UPDATE 

This will be fixed with version 1.15, which will change the active days to show the days since the installation of the app.
See #2132

## Avoid duplicates

* [x] This issue has not already been raised before
* [x] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation
https://github.com/corona-warn-app/cwa-app-ios/blob/11e3821285b0ca0cc46310f0d6d2d747f907c4d7/src/xcode/ENA/ENA/Source/Workers/TracingStatusHistory.swift#L94

So out of this code and from [this](https://github.com/corona-warn-app/cwa-documentation/issues/389#issuecomment-667577152) and [this](https://github.com/corona-warn-app/cwa-documentation/issues/412#issuecomment-686388303) statement from @tkowark and @thomasaugsten, I understand the counting happens like this:

1. App counts seconds Exposure Notification was active.
2. If the counted number equals 86400sec this is shown as one day to the user. (I think the Number can be lower also, it gets rounded in some way, but I don't know how)
3. After 336 * 3600s (2 weeks) the App shows: "Risiko-Ermittlung dauerhaft aktiv"

**If this assumption is wrong/incomplete could you please explain how it works (and mainly how the rounding works)?**

## Suggested Enhancement
With the current Implementation there is the problem that when the user deactivates "Exposure Notification" during the night (activate flight mode, deactivate Bluetooth, etc.) this time is also deducted from the "active days". 
Because of this is is possible that you are stuck at one day or that the active Days go down although you had "Exposure Notification" active for the whole day, but not the night. 

I don't (yet) have a concrete proposal how this could be solved...

## Expected Benefits
It is very confusing for the user to see the Active Days go down again or stay the same. Most users won't know where the problem is and just think that the App did not work right in the last days. (Because they didn't do anything wrong, they just switched off Bluetooth during the night). 
So the expected Benefit is that the users don't get confused anymore.

---

## Related Issues
- https://github.com/corona-warn-app/cwa-documentation/issues/412
- https://github.com/corona-warn-app/cwa-wishlist/issues/102
- https://github.com/corona-warn-app/cwa-app-ios/issues/1739#issue-774547725
---
Internal Tracking ID: [EXPOSUREAPP-2556](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-2556)

**Comment by svengabr** [comment]
Hey @Ein-Tim 

Thank you for your feedback. I created a Jira Ticket EXPOSUREAPP-2556 and assigned it to the development team so they can have a look.

Best regards,
SG

Corona-Warn-App Open Source Team

**Comment by ferdinand** [comment]
I'm usually turning my phone into flight mode while I'm asleep. Therefore my active days are also never getting to 14. That's indeed confusing and annoying. But since not all people sleep at night it wouldn't make sense that the app doesn't count the active time in the night hours. My suggestion would be to check if the Sleep mode, which is newly introduced with iOS 14, is active and stop counting if so. However, I'm not sure if there's an API call for that.

**Comment by daimpi** [comment]
Given that some ppl under Android seem to have the opposite problem (they worry about their time not being deducted [while their phone is off](https://github.com/corona-warn-app/cwa-app-android/issues/929) / [while BT is disabled](https://github.com/corona-warn-app/cwa-app-android/issues/920)) and that ppl in general seem to be confused by this metric, maybe one (radical?) solution would be to [drop the display of the number of active days completely](https://github.com/corona-warn-app/cwa-wishlist/issues/102)?

I personally don't have strong opinions on this topic in either direction tbh.

**Comment by Ein-Tim** [comment]
@daimpi 
This would be one way...
I don't have any feelings in this direction but it should be ensured that the days are counted right (based on communication between humans and not technical 🙂) because this can be very confusing for the user...

**Comment by Ein-Tim** [comment]
Since @GPclips stated [here](https://github.com/corona-warn-app/cwa-wishlist/issues/102#issuecomment-698349139) that the Number of Active Days will not longer be shown to the user, I will close this Issue when this is Finally Released.

**Comment by svengabr** [comment]
@Ein-Tim could you please update your app and have a look? This should already be implemented.

Cheers!

**Comment by Ein-Tim** [comment]
@svengabr 
![image](https://user-images.githubusercontent.com/67682506/94566705-eebbb500-026a-11eb-925b-e9404b4b2bdf.png)
Newest App Version...

**Comment by Ein-Tim** [comment]
@svengabr Are there still plans to drop the number of active days or was this only a mistake back then?

**Comment by mabrin** [comment]
It indeed seems to be true users get confused about this. Take a look at this Twitter conversation I got involved to: https://twitter.com/quatschel/status/1326787201292791808?s=21

**Comment by dsarkar** [comment]
Hi @mabrin, 

Thank you for reporting. Could you please figure out the iOS version number and CWA version, thanks.
Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
@Ein-Tim, We let the developers know, that this issue is still open in favor of corona-warn-app/cwa-documentation#412.

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@dsarkar 
Thank you very much

**Comment by Ein-Tim** [comment]
Update:
Days went up to 13, stayed 13 for 7 days, today went down to 14 again...

**Comment by dsarkar** [comment]
@Ein-Tim, thanks for the new input. We will update the developers. DS

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@dsarkar 
Do the developers have a guess why the days go down and up?

**Comment by dsarkar** [comment]
@Ein-Tim, the issue was observed also by the developers and is set to high priority now. Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@dsarkar 
**Update:**
CWA now shows "Risiko-Ermittlung dauerhaft aktiv". 
Will keep monitoring for 2 weeks and report here if something changes.

**Comment by dsarkar** [comment]
Good morning @Ein-Tim, Thanks for the feedback. Do you usually deactivate exposure logging during night time? DS

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@dsarkar 
Yes I turn WiFi and Bluetooth off during the night... 
yesterday evening: 13/14 days...
Than I turned off WiFi & Bluetooth, activated Flight Mode and went to bed.
Tomorrow morning I've taken a look at CWA and it shows "Risiko-Ermittlung dauerhaft aktiv" 👍
Will keep monitoring...

**Comment by Ein-Tim** [comment]
And bad news:
Days went down to 13 again, tomorrow morning it still showed the correct phrase "Risiko-Ermittlung dauerhaft aktiv", now again 13 out of 14 days.

I start to think that this does not happen because I deactivate Exposure Notification during the night, but because of something else...

Is there any fix planed? For normal users this is really bad since they will think that they have done something wrong or that the App is not working...

**Comment by dsarkar** [comment]
@Ein-Tim, Thanks for info, we will reach out for the developers. DS

**Comment by Ein-Tim** [comment]
Now only 12 active days again...

**Comment by dsarkar** [comment]
We will forward it. DS

**Comment by Ein-Tim** [comment]
@dsarkar While I opened this as an enhancement, I would now say that this is a bug. Could you maybe change the label?

**Comment by dsarkar** [comment]
Another report https://github.com/corona-warn-app/cwa-app-ios/issues/1696#issue-768746684 from @songbird82.

## Technical details

- Device name: iPhone 12
- iOS Version: 14.3
- App Version:1.7.1


## Describe the bug

I switched to a new phone 16 days ago. Since then the risk detection was active for every single day (since November 30th). But the app says "Risiko-Ermittlung war für 11 der letzten 14 Tage aktiv". It switched to "Risiko-Ermittlung war für 12 der letzten 14 Tage aktiv" some days ago, but since then it shows "Risiko-Ermittlung war für 11 der letzten 14 Tage aktiv" every day.


## Steps to reproduce the issue

1. Open the app


## Expected behaviour

After opening the app it should show "Risiko-Ermittlung dauerhaft aktiv"

**Comment by dsarkar** [comment]
@songbird82. Your information will be forwarded to the developers. Many thanks. DS


---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
No visible improvement regarding this with 1.9.1...

**Comment by dsarkar** [comment]
Not yet fixed. I will come back with updates regarding this issue (if there are updates) Dipankar Sarkar

**Comment by cricketsamya** [comment]
@Ein-Tim I am closing the question! And commenting so I will be in the thread! Just a suggestion, cant this be done with time+gyro+accelerometer ?

**Comment by dsarkar** [comment]
Hi @Ein-Tim and community,

I see my phone stuck on 13/14 days. Phone is always on, BT on. CWA 1.12.

Your observations?

**Comment by Ein-Tim** [comment]
Morning @dsarkar 

I'm stuck on either 13 out of 14 or 12 out of 14 days. I deactivate Bluetooth during the night. 

iOS 14.4
CWA 1.12.1

**Comment by dsarkar** [comment]
@Ein-Tim I suspect that it is even independent from BT being activated or not. But lets try it, I will switch off BT a few days.

**Comment by cricketsamya** [comment]
@Ein-Tim I am also facing the same issue! I'm stuck on 12 out of 14 days. I deactivate Bluetooth during the night.

iOS 14.4
CWA 1.12.1

![image](https://user-images.githubusercontent.com/13750637/107857578-57c55300-6e2f-11eb-8a4e-cbcd71dc553b.png)

**Comment by dsarkar** [comment]
@cricketsamya Ok, thanks for the feedback. Will forward info to developers. Best, DS

---
Corona-Warn-App Open Source Team

**Comment by cricketsamya** [comment]
@dsarkar one more issue, no more background refreshes happening 😥 I must open the app to download the ids.

**Comment by dsarkar** [comment]
@cricketsamya ok.
- CWA 1.12 / iOS 14.4 / iPhone model? 
- For how long it does not download keys?
- Wifi / mobile data?
- How often does this happen, any pattern?
- Since when?


Thanks, DS

**Comment by Ein-Tim** [comment]
I've experienced this too, but only under version 1.11, do you still have this problem in 1.12? @cricketsamya 

Maybe move to #1884 for this?

**Comment by cricketsamya** [comment]
@dsarkar @Ein-Tim I am sorry! My bad lets discuss there! 👍🏼

**Comment by Ein-Tim** [comment]
@cricketsamya 

No problem 👍

**Comment by Ein-Tim** [comment]
[This](https://github.com/corona-warn-app/cwa-app-android/pull/2464) Android PR suggests that the active days will show the days since the installation (starting with version 1.15 (milestone)).

This would solve this issue. Feel free to label as `Fix 1.15` @dsarkar! 🎉

**Comment by cricketsamya** [comment]
Is there a fix planned for this? I am still stuck on day 13 and sometimes 12.

**Comment by Ein-Tim** [comment]
@cricketsamya 

Version 1.15 changes the active days to show the days since installation of the app. 
See PR: #2132

**Comment by ndegendogo** [comment]
> Version 1.15 changes the active days to show the days since installation of the app

Sounds like a good idea 😀

**Comment by Ein-Tim** [comment]
Version 1.15.1 which introduced a different counting of the days (days since installation) has been released to GitHub and will be available to all users in the next 48h.

See blog post:

DE: www.coronawarn.app/de/blog/2021-03-24-corona-warn-app-version-1-15
EN: www.coronawarn.app/en/blog/2021-03-09-corona-warn-app-version-1-15

See GitHub release:

https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v1.15.1

This issue will now be closed.

**Comment by dsarkar** [comment]
@Ein-Tim Thanks.
