### ISSUE TITLE
After resetting "Location and Privacy settings" App can't be activated again

### ISSUE THREAD

**Issue by avenius** [corona-warn-app/cwa-app-ios#1128]
When you reset the "Location and Privacy settings" to default (had to do so of a general Issue), the app can't be reactivate again.
Only way was reinstalling.

**Comment by Ein-Tim** [comment]
So the CWA worked and you resetted "Location and Privacy settings"?
What did the App show after the reset?

**Comment by svengabr** [comment]
Hello @avenius 

is it possible that you can give more information on this topic?

* Which device are you using?
* Which iOS version are you using?
* Do you have the latest 1.3.0 version of the app installed?

Thank you very much!

Best regards,
SG

Corona-Warn-App Open Source Team

**Comment by heinezen** [comment]
Closed due to missing feedback.

@avenius If the bug persists for you or you can provide the information @svengabr asked for, feel free to comment here or open anoother issue.

Regards,
CH

Corona-Warn-App Open Source Team
