### ISSUE TITLE
Are you planing to use/show „Travel Status“ (iOS 13.7 and above)?

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#1136]
## Avoid duplicates
* [x] Question is not already answered in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Question has not already been asked in another issue

## Your Question
With iOS 13.7 Apple introduced the option to "Share Travel Status" in the Settings ("Exposure Notifications").
![image](https://user-images.githubusercontent.com/67682506/92387585-17daa100-f116-11ea-9efc-39a4b692d30a.jpeg)
Are you planing to show this "Travel Status" to the User?

**Comment by svengabr** [comment]
Hey @Ein-Tim 

I will ask your question in our developer meeting tomorrow. I will not move this to the wishlist for now.

Best regards,
SG

Corona-Warn-App Open Source Team

**Comment by Marco2907** [comment]
Hi @Ein-Tim , if the consent of the user is given, the traveller flag from apple may be used without problems. It gives the information that the user has left the country in the last 14 days. 

best,
MP

Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
Okay, so not the CWA will show the Travel Status but iOS? (in a Notification or where?)

**Comment by thomasaugsten** [comment]
The CWA can access the the traveler status. The first time a consent will popup to the user. Then the CWA can access the information if the user left his home region in the past 14 days. We consider this to use this to notify the user about the  available interoperability feature in the upcoming versions if the status is true. But there is no decision yet.

**Comment by Ein-Tim** [comment]
Ok thanks.
So if the user now have this option turned on, nothing really is done with the Information?

**Comment by thomasaugsten** [comment]
Not at the moment. This switch allows the user to revoke his consent when he shared this information with the app.

**Comment by Ein-Tim** [comment]
Okay I understand. Thanks for the clarification. Will close this Issue for now

**Comment by Ein-Tim** [comment]
@thomasaugsten Did anything change about this with the release of the EFGS? 
At least for the "Travler Mode" this has to be used, or? (I refer to the 3 modes of EFGS (see here: https://github.com/corona-warn-app/cwa-website/issues/555#issuecomment-727215860))

**Comment by thomasaugsten** [comment]
There are no plan to use the travel status for interop/efgs
