### ISSUE TITLE
Risk check: Fallback strategy after bad internet connection presents 2*14 key files to ENF

### ISSUE THREAD

**Issue by ndegendogo** [corona-warn-app/cwa-app-ios#1141]
## Avoid duplicates

* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is not already reported in another issue

## Describe the bug
- App is closed, last background check was less than 24 hours ago
- disable internet connection (both WLAN and mobile data).
- wait till the check is due plus two hours, to be sure to get the fallback strategy
- enable internet again, and wait another two hours
- don't open the app, check the exposure logs of ENF

Expected: see log entries of 14 files
Observed: two iterations of log entries (2*14 files)

See attached export file of exposure logs

## Expected behaviour
only a single iteration (14 files)

## Steps to reproduce the issue
see above

## Technical details

- CWA version: 1.3.0(6)
- iOS Version: 13.6.1
- Device:iPhone 8

## Additional context

I have seen this pattern (27 or 28 files in the ENF log after delayed check > 26h) several times before, with cwa 1.2.1(0) and cwa 1.3.0(6), although I was not sure about bad internet connection. See [here](https://github.com/corona-warn-app/cwa-app-ios/issues/916#issuecomment-683390291) and [here](https://github.com/corona-warn-app/cwa-app-ios/issues/916#issuecomment-686775642) and [here](https://github.com/corona-warn-app/cwa-app-ios/issues/916#issuecomment-678691526).

Today I could reproduce it explicitely by turning internet off while the check was due.

[ExposureChecks-2020-09-07.json.zip](https://github.com/corona-warn-app/cwa-app-ios/files/5184799/ExposureChecks-2020-09-07.json.zip)

---
Internal Tracking ID: EXPOSUREAPP-2589

**Comment by Marco2907** [comment]
Hi @ndegendogo , thanks for sharing your content. I will keep this issue to discuss this with our development team and come back to you as soon as possible. 

Thanks,
MP

Corona-Warn-App Open Source Team

---
Internal Tracking ID: EXPOSUREAPP-2589

**Comment by Marco2907** [comment]
Hi @ndegendogo , this risk check issue should be fixed with 1.4.0 

Thanks,
MP

Corona-Warn-App Open Source Team

**Comment by ndegendogo** [comment]
Thanks @Marco2907 
Do you have a planning / timeline for this release?

**Comment by Marco2907** [comment]
Hi @ndegendogo, it should be fixed in 1.4 and 1.4 should be released on October 10th. 

Thanks,
MP

Corona-Warn-App Open Source Team

**Comment by ndegendogo** [comment]
Thanks again!

May I ask which commit(s) / PR / or item in the release notes relates to this issue?

**Comment by marcussc** [comment]
@ndegendogo https://github.com/corona-warn-app/cwa-app-ios/pull/1081 :)

**Comment by GPclips** [comment]
This issue has been completed and will be closed now.

**Comment by GPclips** [comment]
Hello @ndegendogo,

I will reopen the issue since the fix hasn't been deployed. Until then, we will leave the thread open.
We expecting the fix to be deployed as soon as possible.

Thanks,
LMM

Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@ndegendogo

Can you still reproduce this behavior in Version 1.5.0 or newer?

**Comment by ndegendogo** [comment]
@Ein-Tim I'll test again and report my observations.
Might have to wait for a few days (currently the check is deep in the night while I am sleeping).

**Comment by ndegendogo** [comment]
Tested scenario again today. Did behave as expected. 
Thans for fixing.

cwa 1.5.2 (1) / iOS 14.1 / iPhone 8

closing the ticket.
