### ISSUE TITLE
Dead man notification does not work

### ISSUE THREAD

**Issue by databus23** [corona-warn-app/cwa-app-ios#1144]
## Avoid duplicates

* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is not already reported in another issue

## Describe the bug

As [reported previously](https://github.com/corona-warn-app/cwa-app-ios/issues/916) background checks are ~not working on my iPhone~ only work when I connect my phone to a charger for unknown reasons.
So I was patently waiting for the new [dead man notification](https://github.com/corona-warn-app/cwa-app-ios/blob/v1.3.0/src/xcode/ENA/ENA/Source/Models/Task%20Scheduling/ENATaskScheduler.swift#L115) that was added with 1.3.0. Unfortunately I received no notification within 43 hours (at which point I opened the app to force a check).

![image](https://user-images.githubusercontent.com/439223/92457223-4020d900-f1c4-11ea-9e0c-48cfc88b27a8.png)

## Expected behaviour

After 36 hours of no check a local notification should prompt me to open the app.

## Steps to reproduce the issue
Wait for 36 hours after the last check without opening the app.

## Technical details

- iOS Version: 13.7
- Device: iPhone 8 Plus

## Possible Fix
I have no idea really but I'm wondering if the local notification is only scheduled in an actual background task, not when the check is executed while the app is in the foreground. Because in my case the checks are only happening when I'm opening the app.

---
Internal Tracking ID: EXPOSUREAPP-2994

**Comment by Marco2907** [comment]
Hi @databus23 , thanks for sharing your content. Could you wait another 30 hours for a return time and then check the time of the risk calculation?  

Thanks,
MP

Corona-Warn-App Open Source Team

**Comment by databus23** [comment]
@Marco2907 Not sure I fully understand. What do you mean be a "return time"? By "check the time of the risk calculation" you mean the last time a check was logged in Settings-> Exposure notifications?

**Comment by thomasaugsten** [comment]
This is also difficult to test the notification check at the moment only for the background task and not the risk calculation. This means if the background task was startet but canceled without a successful risk calculation the notification will be rescheduled. We plan to extend this to the risk calculation.

**Comment by databus23** [comment]
@thomasaugsten Not sure I fully understand, but this sounds like my assumption was correct that the dead man notification only works if the background task was executed previously.

**Comment by thomasaugsten** [comment]
No this means every time the background task was executed the notification is rescheduled in 36h. But an executed background task doesn't mean a successful risk calculation because iOS can stop the background task after 1sec because of memory or battery issues and this means the risk calculation is also stopped.

**Comment by databus23** [comment]
I see, so this could be the problem here.

**Comment by mss1010** [comment]
Is there any news on this? I also have the case now, that after more than 36 hours there was no background check and no notification.

iPhoneXS
newest iOS and app version

**Comment by thomasaugsten** [comment]
This will be improved in v1.5

**Comment by mss1010** [comment]
> 
> 
> This will be improved in v1.5

Thanks for the fast reply! Can you give an estimation when 1.5 will be released? I think 1.4 was planned for mid october.

**Comment by thomasaugsten** [comment]
Not yet there is already an internal planning but not yet ready to publish.

**Comment by Ein-Tim** [comment]
@databus23 
Can you please check if the Dead Man Notification now works with Version 1.5.**1** (or above) from CWA?

**Comment by Ein-Tim** [comment]
I think this Issue can be closed since Dead Man Notifications are working with 1.5.1 and above

**Comment by heinezen** [comment]
Should be fixed with https://github.com/corona-warn-app/cwa-app-android/pull/1513 and release 1.7.

----
Corona-Warn-App Open Source Team

**Comment by databus23** [comment]
I can't really reproduce the issue anymore as the background task execution started to work somewhat reliable for me.

**Comment by Ein-Tim** [comment]
@heinezen Please leave this Issue open.
With the (buggy) release of 1.6.0 and the (not optimal) hotfix 1.6.1 there are some users who complain about not working Dead Man Notifications (f.e.: https://github.com/corona-warn-app/cwa-app-ios/issues/916#issuecomment-727920973).

I can also confirm what @PalminX stated in #916:

The last check on my phone was performed at 15.11. at 22:42. Until now, no new check happened (only a failed one) and also no Dead Man Notification.

**Comment by heinezen** [comment]
@Ein-Tim We will leave it open until 1.7 has been rolled out to all users and check for feedback.

----
Corona-Warn-App Open Source Team

**Comment by PalminX** [comment]
No deadman notification showed up for me, up to 65 hrs after the laste foreground check. Then, another background check happened (see https://github.com/corona-warn-app/cwa-app-ios/issues/916#issuecomment-728935091)

**Comment by PalminX** [comment]
> @Ein-Tim We will leave it open until 1.7 has been rolled out to all users and check for feedback.
> 
> Corona-Warn-App Open Source Team

Is this fix also for iOS? Asking since the PR was for the Android repo: https://github.com/corona-warn-app/cwa-app-android/pull/1513

**Comment by heinezen** [comment]
@PalminX 

> Is this fix also for iOS?

Apologies, I have confused the fixes for the different apps. I've updated my initial post.

The Dead Man Notification Bug for iOS is currently being investigated and there are unfortunately no updates on this. 

Sorry for the confusion,
CH

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
Can anybody here report a **working** dead man notification with 1.6.0 or above?

**Comment by dsarkar** [comment]
Hi @PalminX,

FYI, I have added your report to the internal ticket for the developers. 

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by PalminX** [comment]
I received a dead-man notification yesterday, Nov 19, at 21:!5, exactly 40 hrs after the last logged background check (which was at 5:15 on Nov 18).

**Comment by ndegendogo** [comment]
Well, at least they seem not reliable.
See [here](https://github.com/corona-warn-app/cwa-app-ios/issues/916#issuecomment-729933255)

**Comment by ndegendogo** [comment]
Well - seems not reliably. I got none, see details [here](https://github.com/corona-warn-app/cwa-app-ios/issues/916#issuecomment-729933255)

**Comment by dsarkar** [comment]
Dear @ndegendogo, @PalminX,

Many thanks for feedback, we forward these observation to the developers!

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
Dear community, 

We would appreciate some feedback here. This issue was resolved in CWA version 1.7.1.

References: EXPOSUREAPP-2332, PR https://github.com/corona-warn-app/cwa-app-android/pull/1513.

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by ndegendogo** [comment]
@dsarkar I am a bit confused now - the PR you mentioned is for Android but this ticket is in the iOS repo?

**Comment by Ein-Tim** [comment]
Can anybody confrim that Dead man notificaitons are working with 1.7.1?
Or are the background checks to reliable with this version? 😉

**Comment by ndegendogo** [comment]
@dsarkar maybe the devs could confirm that there is a related PR also for iOS?

Two weeks ago [they were still investigating](https://github.com/corona-warn-app/cwa-app-ios/issues/1144#issuecomment-728955525) - but that comment might well be outdated today.

In the first week of 1.7.1 my checks were perfect. Now since two days they start to have large gaps, yesterday it was 8 hours instedad of 4, today I had a gap of 12h. **Still by far better than before 1.7.1.**

I'll continue to watch.

**Comment by dsarkar** [comment]
Dear @ndegendogo,

There is no PR that correlates directly to a fix of the deadman issue. However, this problem is understood to have resolved by fixing other issues.

Related internal tickets: EXPOSUREAPP-3880, EXPOSUREAPP-3821.

Let's monitor for the moment, any feedback will be forwarded to the developers! Many thanks, 

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
@ndegendogo, I got some feedback, which might explain some recent irregularities in the checks. In den night from Sunday to Monday and Monday to Tuesday, time 0100 - 0200, the server was prepared for ENF v2 (future CWA version 1.8). Possibly, checks in that time frame were skipped. 

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by ndegendogo** [comment]
Thanks @dsarkar.

I am just preparing to submit another ticket on some of the irregularities I saw last Thursday. (Nothing very serious, but it would be interesting if there is an explanation).

**Comment by dsarkar** [comment]
@ndegendogo, sure, see https://github.com/corona-warn-app/cwa-app-ios/issues/1631#issuecomment-739326690. Best, DS
---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
Did some additional testing, Dead Man notifications are working with 1.7.1 👍

**Comment by ndegendogo** [comment]
@Ein-Tim wow - so you saw such a notification? 🎉🎉

**Comment by dsarkar** [comment]
@Ein-Tim, thanks for letting us know. Could you let us know, how you could trigger such notifications? In any case, we will forward this information to the developers. 

We will close this issue now. However, re-open if appropriate. Thanks to everybody for contributing here.

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@ndegendogo 

> wow - so you saw such a notification?

Yes, this one:
![image](https://user-images.githubusercontent.com/67682506/101370975-7f85c100-38aa-11eb-9c4f-f8722e8fb857.jpeg)


@dsarkar 

> Could you let us know, how you could trigger such notifications?

Yeah, just make sure that your phone is not connected to the Internet for a bit more than 36h and you will revive one. 👍

But I saw that it was not exactly 36h after the last check, more like 37 1/2h. But I think this is ok 👍

**Comment by dsarkar** [comment]
@Ein-Tim, thanks for the information, very much appreciated. We will forward your observation to them and we would suggest closing this issue after monitoring a few more days. Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
Dear @Ein-Tim, @ndegendogo, @databus23, @PalminX, and community,

Thank you for your contributions.  This issue will be closed now. Please, re-open if necessary.

Best wishes,
DS

---
Corona-Warn-App Open Source Team
