### ISSUE TITLE
Getting notifications in message center for several encounters but in CWA there is no encounter mentioned

### ISSUE THREAD

**Issue by drotschmanns** [corona-warn-app/cwa-app-ios#1147]
## Avoid duplicates

* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is not already reported in another issue

## Describe the bug

I keep getting hints in the message center (iPhone) that I had several encounters, but there is nothing about it in the app. (no encounters)

## Expected behaviour

When getting notifications for encounters, I would assume this will be reflected in the app.

## Technical details

- iOS Version:
- App Version: 1.3.0
- Device:

## Additional context

More Feedback with detailed information will come later if possible. (not my issue)
Are there more experiencing this issue?

**Comment by Ein-Tim** [comment]
Which notification do you (or the person you opened this Issue for) receive?
From the App itself or from iOS?

**Comment by thomasaugsten** [comment]
Please update to iOS 13.7. Apple improved this messages in the latest iOS version.

**Comment by drotschmanns** [comment]
> Please update to iOS 13.7. Apple improved this messages in the latest iOS version.

Was an App Store Reply, hope we will get some more feedback in some days. Will keep you updated.

**Comment by svengabr** [comment]
Hey @drotschmanns 

You can find a FAQ entry explaining the issue:

https://www.coronawarn.app/en/faq/#notif_weekly_update
**[Apple/iOS]: 'COVID-19 exposure logging... - Weekly Update'**
>This is a general notification, which does not mean that risk encounters have been identified. It is not a message or function of the Corona-Warn-App. Apple's Exposure Notification Framework (ENF) sends this notification and displays the icon. Apple's ENF provides information about any encounters with app users who were tested positive - without making a statement as to whether or not it was a critical encounter according to the Robert Koch Institute's algorithm. For example, encounters are also displayed in case the distance was more than 8 meters or in case it only lasted a few minutes. This means that the 'Weekly Update' only provides information about technical procedures of the ENF that are insufficient for an actual risk calculation. A reliable risk calculation takes place exclusively in the Corona-Warn-App under the scientific framework of the Robert Koch Institute. You can view your current risk status directly in the Corona-Warn-App.

https://www.coronawarn.app/de/faq/#notif_weekly_update
**[Apple/iOS]: 'COVID-19-Begegnungsaufzeichnungen' - Wöchentliches Update**
> Das ist eine allgemeine Benachrichtigung, die nicht bedeutet, dass Risiko-Begegnungen erkannt worden sind. Es handelt sich dabei nicht um eine Meldung oder Funktion der Corona-Warn-App. Das Exposure Notification-Framework (ENF) von Apple sendet diese Benachrichtigung und zeigt das Icon an. Die ENF-Schnittstelle von Apple informiert an dieser Stelle über jegliche Begegnungen mit App-Nutzern, die positiv getestet wurden - ohne eine Aussage darüber zu treffen, ob es sich um eine nach dem Schema des Robert Koch-Instituts kritische Begegnung handelte oder nicht. Es werden beispielsweise auch Begegnungen angezeigt, bei denen der Abstand mehr als 8 Meter betrug oder die nur wenige Minuten dauerten. Das heißt: Das 'Wöchentliche Update' informiert lediglich über technische Vorgänge des ENF, die für eine tatsächliche Risiko-Ermittlung unzureichend sind. Eine zuverlässige Risiko-Ermittlung findet ausschließlich in der Corona-Warn-App unter den wissenschaftlichen Rahmenbedingungen des Robert Koch-Instituts statt. Sie können Ihren aktuellen Risikostatus direkt in der Corona-Warn-App einsehen.
