### ISSUE TITLE
Cant activate risk detection in ios 13.7

### ISSUE THREAD

**Issue by uberhusband** [corona-warn-app/cwa-app-ios#1148]
After updating my iPhone X to ios 13.7 was the risk detection off, after trying to activate it does not work. I‘m not able to activate the risk detection longer.

After activating it went automatically back to off

![2B4DADCF-006D-4B12-B5C1-BEC821719235](https://user-images.githubusercontent.com/70975024/92515917-aafa0080-f214-11ea-9773-71c942563b26.jpeg)

**Comment by thomasaugsten** [comment]
Can you check the Begegnungsüberpüfung settings in iOS and post screenshots

**Comment by uberhusband** [comment]
![28A03B02-E181-4B15-B483-C7FD5574CB70](https://user-images.githubusercontent.com/70975024/92517048-5fe0ed00-f216-11ea-958c-0adda4cb25ea.png)

**Comment by thomasaugsten** [comment]
When you click on Corona Warn App and then again Corona Warn App can you activate the Begegnungsüberprüfung ?

**Comment by uberhusband** [comment]
I‘m able to activate, after clicking back or reopen the app it is deactivated again.

**Comment by uberhusband** [comment]
![CAF59695-F68B-4520-A1EA-A3A35EC37362](https://user-images.githubusercontent.com/70975024/92517762-86535800-f217-11ea-89f4-a270a5776514.jpeg)

**Comment by thomasaugsten** [comment]
I need screenshots from all settings screen in Begegnungsüberprüfung to understand it better. Did you try to restart your phone?

**Comment by uberhusband** [comment]
Yes I already restated the phone, this has not change anything. Bluetooth and widi and mobil data is active.

Here some More Screenshots


![4DC83D80-B837-4BE7-9F23-9178BE0729B1](https://user-images.githubusercontent.com/70975024/92518252-52c4fd80-f218-11ea-8cf2-9292cc4fd946.png)
![4A73364E-8409-46ED-9323-555621FB9119](https://user-images.githubusercontent.com/70975024/92518256-53f62a80-f218-11ea-96fc-60ba04e32d60.png)
![EACD110E-6E9C-41B5-A293-DC38A103D7D6](https://user-images.githubusercontent.com/70975024/92518259-53f62a80-f218-11ea-99f7-ba6d9640ee26.png)
![69BBA4AE-C615-4DB5-A5FF-5997BD9918AD](https://user-images.githubusercontent.com/70975024/92518260-55275780-f218-11ea-9223-7eb4f73a79db.png)
![C6537347-9F9D-4163-990A-72C287B366D7](https://user-images.githubusercontent.com/70975024/92518264-55bfee00-f218-11ea-964d-9ad246f4017b.png)
![1F2A1EBE-A99C-49FA-AC82-32E98DEA8331](https://user-images.githubusercontent.com/70975024/92518244-5193d080-f218-11ea-89e2-795d9b054299.png)
![BAFAE52C-D068-4FE8-84F3-223C12BD495C](https://user-images.githubusercontent.com/70975024/92518247-522c6700-f218-11ea-9ab4-b761ae5be2e7.png)

![B1CF5932-713C-4406-A1DE-973BE79B8FAD](https://user-images.githubusercontent.com/70975024/92518242-50fb3a00-f218-11ea-926d-62881cc20b4e.jpeg)

![2C4CB8A5-4735-47B8-8BA2-94884490693B](https://user-images.githubusercontent.com/70975024/92518229-4d67b300-f218-11ea-9cb5-625effba546e.jpeg)

**Comment by thomasaugsten** [comment]
can you please add also this screen after clicking on corona-warn-app
![image](https://user-images.githubusercontent.com/6367738/92518674-00381100-f219-11ea-89bd-1f142be1cd03.png)

**Comment by uberhusband** [comment]
Sure

![9850A5C8-73D9-4991-8758-F96AAF0ECC5C](https://user-images.githubusercontent.com/70975024/92519110-bbf94080-f219-11ea-82d6-52eddd3da180.png)
![22111962-7490-4A66-855D-C5C68B096C63](https://user-images.githubusercontent.com/70975024/92519126-bf8cc780-f219-11ea-8013-cfcfc5048484.png)

**Comment by thomasaugsten** [comment]
You can switch Begenungsinforrmation teilen off and on again but I think you have to contact me directly
thomas.augsten@sap.com to provide a sysdiagnose

**Comment by uberhusband** [comment]
I alreday deactivaed this to off an on, bit this change nothing. I will send you a mail.

**Comment by Ein-Tim** [comment]
@uberhusband 
Is Background App Refresh on for the CWA?

**Comment by uberhusband** [comment]
Yes it is active

**Comment by Ein-Tim** [comment]
Okay than I have no clue... 
Sometimes it helps activating it when it was off but since it's on...
But I see, @thomasaugsten is looking into it

**Comment by ThoGei29** [comment]
I have the same problem, but it starts a few days after updating to iOS 13.7. First it was all okay after the Update, but later on, starting this morning, I have the same problem.

**Comment by thomasaugsten** [comment]
@uberhusband Könntest du bitte überprüfen ob eine Begegnungsüberprüfung gestern oder heute gelaufen ist? Bitte die App NICHT löschen und neu installieren.
@ThoGei29 Bitte lösche die App und neu installieren die App. Der Zähler wird zwar auf 1/14 Tage zurückgesetzt aber es werden trotzdem die vergangenen 14 Tage überprüft.

**Comment by ThoGei29** [comment]
@thomasaugsten Vielen Dank, es funktioniert nun wieder.

**Comment by uberhusband** [comment]
Hurray, it is working again. I did not do anything after our syslog this mornig.
The latest update this mornig was on Monday 11pm (like in the old screenshots)

After opening agin (now) it was active again.

Shall I close the Bug here? Or will you do this? Or do you need some more help from my side?

![58902309-FFD1-4C4F-BD83-F2AC67523C38](https://user-images.githubusercontent.com/70975024/92581148-9018a200-f28f-11ea-99e9-0216b5836909.jpeg)

**Comment by thomasaugsten** [comment]
You can close the ticket
