### ISSUE TITLE
Risiko-Ermittlung gestoppt

### ISSUE THREAD

**Issue by fark0** [corona-warn-app/cwa-app-ios#1153]
## Avoid duplicates

* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is not already reported in another issue

## Describe the bug

Nachdem ich die Corona App nun seit Monaten im Einsatz habe, zeigt sie mir seit gestern "Risiko-Ermittlung gestoppt", obwohl die Ermittlung lt. dem Button darüber aktiviert ist.

![IMG_7149](https://user-images.githubusercontent.com/69767274/92637582-4c4a8a80-f2d9-11ea-8dae-491155716998.PNG)

Ein Tap auf "Risiko-Ermittlung einschalten" bringt mich zu einem Screen, auf dem ich sehe, dass der Slider bereits eingeschalten ist. Deaktivieren und Aktivieren der Ermittlung, Abschießen der App, Neustart des iPhones, De-/Aktivieren der Hintergrundaktualisierung hat nichts gebracht - auch nicht in unterschiedlicher Kombination.

Ein Löschen und anschließendes Neuinstallieren hat ebenfalls nichts gebracht:

![IMG_96C2ACA1533F-1](https://user-images.githubusercontent.com/69767274/92637592-5076a800-f2d9-11ea-9e7b-a0d2ecf91000.jpeg)

## Expected behaviour

Der Mainscreen sollte konsistente Inhalte anzeigen, der Benutzer weiß nicht, ob die Ermittlung aktiv ist oder nicht.

## Technical details

- iOS Version: 14.0 (18A5369b)
- Device: iPhone Xs

## Additional context

---
Internal Tracking ID: EXPOSUREAPP-2620, EXPOSUREAPP-2472

**Comment by thomasaugsten** [comment]
Kannst du bitte mal dein wlan ausschalten und dein handy neustarten.

**Comment by fark0** [comment]
@thomasaugsten Neustart + WLAN deaktivieren hat leider nichts gebracht:
![IMG_05E7D6DC4E2E-1](https://user-images.githubusercontent.com/69767274/92638864-45bd1280-f2db-11ea-92b1-2915a5ac340c.jpeg)

**Comment by thomasaugsten** [comment]
Wir müssen uns Beta 7 mal anschauen ob wir so ein Fehler reproduzieren können. Bitte die nächste Tage schauen ob der Fehler weg ist. Eine Aktualisierung findet ja trotzdem statt

**Comment by fark0** [comment]
Dazu ergänzend: Der Fehler lag definitiv auch unter Beta 6 vor - habe gestern nachdem ich den Fehler entdeckt habe und nicht beheben konnte, auf Beta 7 aktualisiert, um zu prüfen ob er dann behoben ist.

**Comment by Ein-Tim** [comment]
Sieht so aus als wäre es praktisch [dieser](https://github.com/corona-warn-app/cwa-backlog/issues/1#issuecomment-687175144) Fehler, nur auch ohne WLan...

Hast du außerdem mal versucht die App mit Mobilen Daten/einem anderen WLan zu öffnen?

Ich frage da es scheint als würde die App bei gewissen SSL Zertifikaten Probleme haben: 
#1117

**Comment by Marco2907** [comment]
Hallo @fark0 , 
vielen Dank für deinen Input. Ich werde diesen Punkt aufnehmen und mit unserem Entwicklungsteam besprechen. 

Vielen Dank,
MP

Corona-Warn-App Open Source Team 

---
Internal Tracking ID: EXPOSUREAPP-2620

**Comment by fark0** [comment]
Dazu ein Update: Heute morgen war ich noch immer vom Problem betroffen, als ich aber vor wenigen Minuten in die App schaute, scheint wieder alles zu stimmen - obwohl der "Tagesabgleich" heute noch nicht lief:

![IMG_7156](https://user-images.githubusercontent.com/69767274/92763675-13232080-f394-11ea-8554-8c5c6c4474fa.PNG)

Nun bin ich aber vom gleichen Problem betroffen wie hier beschrieben: https://github.com/corona-warn-app/cwa-app-ios/issues/1106 Die App zeigt mir 9 Risiko-Begegnungen - das scheint stimmig, da ein Haushaltsmitglied am Montag positiv getestet wurde und dies meldete. Kurios ist aber, dass in den Exposure Notifications sämtliche Checks einen Matched Key Count von 0 aufweisen. Hier ist bei Apple irgendwo der Wurm drin.

Das in diesem Issue gemeldete Verhalten tritt seit dem "Tagesabgleich" vom Dienstag auf, der mich als risiko-gefährdet hätte einstufen müssen (nach der Positiv-Meldung vom Montag). Weiß nur nicht, ob das Zufall war oder mit dem Bug zusammenhängt...

**Comment by thomasaugsten** [comment]
Hi danke für dein Feedback. Wir hoffen das Apple den Fehler mit Log zeitnah behebt. Kannst du bitte das Verhalten auf iOS 14 bitte weiter im Auge behalten ob sich die Risikoermittlung aktualisiert.

**Comment by SabineMa** [comment]
Kann das Problem bestätigen. Bin aktuell auf Reisen und in verschiedenen Netzen unterwegs, damit scheint die App nicht klar zu kommen. Beobachte das Problem seit mehreren Tagen, jetzt kann ich die Risiko Ermittlung nicht mehr einschalten. Nachdem ich den toggle “Einstellung”-Risiko Ermittlung eingeschaltet habe und mit “zurück “ auf die Hauptseite wechsle, ist die Risiko Ermittlung wieder “aus”.

**Comment by thomasaugsten** [comment]
@SabineMa bitte in den iOS Einstellung die Region aktivieren bzw in den aktiven Region die Begegnungsübermittlung teilen deaktivieren und wieder aktivieren.

**Comment by wandoliver** [comment]
Ich kann das ebenfalls Bestätigen. Unter iOS 14 ist die Risiko-Ermittlung seit gestern auf einmal gestoppt und lässt sich nicht mehr aktivieren. Alle hier vorgeschlagenen Vorgehensweisen funktionieren nicht.

**Comment by wandoliver** [comment]
> @SabineMa bitte in den iOS Einstellung die Region aktivieren bzw in den aktiven Region die Begegnungsübermittlung teilen deaktivieren und wieder aktivieren.

Wenn ich dem Vorschlag folge und danach wieder Versuche, die Risiko-Ermittlung in der App zu aktivieren, erhalte ich folgende Fehlermeldung (die es vorher nicht gab):

![IMG_1507](https://user-images.githubusercontent.com/35329024/93765861-d964dc00-fc15-11ea-98e1-6aa849131e75.PNG)

**Comment by thomasaugsten** [comment]
Ist denn Deuschland als aktive Region gesetzt ist?

**Comment by wandoliver** [comment]
> Ist denn Deuschland als aktive Region gesetzt ist?

Das war insofern der entscheidende Hinweis, als dass in den Einstellungen unter "Aktive Region" der Text "Als aktive Region festlegen" blau und nicht grau war, also offenbar nicht aktiv. Erst nachdem ich dort geklickt hatte wurde dieser Text grau und nun funktioniert auch die Risikoermittlung der App wieder. Das ist optisch kaum zu erkennen, ganz schön tricky. Für mich hat es das jetzt soweit wohl gelöst!

**Comment by svengabr** [comment]
Some feedback from the iOS Appstore

User:
>Von einem Tag auf den anderen ist die Risikoermittlung in der App ausgeschalten. Sie lässt sich auch nicht mehr einschalten. Trotz das der Regler aktiviert wird bleibt die Ermittlung aus. Ich habe nichts geändert. iOS 14 wurde installiert am Dienstag. Schade schade um die App

User:
>Unter iOS 14 funktioniert die wichtigste Funktion der riskiobewertung nicht mehr. App gibt es als ausgeschaltet an aber wenn man es einschalten will und die app schließt und dann wieder aufmacht ist es immer noch aus.

User:
>Leider funktioniert sie seitdem iOS 14.0 Update nicht mehr, auch nicht mit dem tip der Entwickler das man für Hintergrundaktualisierung einstellt.

User:
>Leider funktioniert die App nicht mehr mit iOS 14. Ein Hard reset des iPhones hat das Problem behoben.

User:
>Bisher lief die App bei mir nahezu ohne Probleme. Seit heute bekomme ich die Meldung, die Risikoermittlung sei ausgeschaltet. Ich kann dann zwar den Button aktivieren, aber er schaltet sich immer wieder von selbst auf aus. Ist das wieder ein iOS typisches Problem???

**Comment by ThomasHornschuh** [comment]
Hatte das Problem auch, iPhone 8 und iOS14. Heute Nacht um 2:32 die letzte Aktualisierung, dann heute "Risikoermittlung gestoppt" und Versuche sie einzuschalten nicht wirksam (beim nächsten Aufruf des Dialoges steht der Schieber wieder auf aus.
iOS 14 Update war aber bei mir schon letzte Woche Mittwoch oder Donnerstag,

Der Vorschlag von @thomasaugsten  hat bei mir das Problem gelöst. Ich musste "Begegnungssinformationen teilen" deaktivren und weider aktivieren, dann war der Punkt "Als aktive Region festlegen" aktivierbar.

**Comment by Ein-Tim** [comment]
@thomasaugsten 
Könnt ihr diesen Fehler reproduzieren bzw. wisst ihr woran es liegt?

**Comment by thomasaugsten** [comment]
der fehler ist an apple weitergeleitet und in den logs sieht man das die region einfach nicht active geschaltet werden kann, wir warten auf feedback von apple ob wir auf unserer Seite etwas anders machen können

**Comment by SabineMa** [comment]
> @SabineMa bitte in den iOS Einstellung die Region aktivieren bzw in den aktiven Region die Begegnungsübermittlung teilen deaktivieren und wieder aktivieren.

Bin nur in Deutschland auf Reisen 😀. Trotzdem mal Deutschland ein gestellt. Problem bleibt.

**Comment by SabineMa** [comment]
> @SabineMa bitte in den iOS Einstellung die Region aktivieren bzw in den aktiven Region die Begegnungsübermittlung teilen deaktivieren und wieder aktivieren.

Ok nachdem ich diesen Dialog nestätigt habe geht es wieder, danke! 
![76E568F3-8A55-4C54-A1CC-22A504989C46](https://user-images.githubusercontent.com/13763544/93773239-2948a080-fc20-11ea-883f-5b52f119d7e6.png)

**Comment by Tachy** [comment]
Hatte das Problem auch seit OS14. In den Einstellungen war die Region nicht festgelegt. Aktive Region auf „Deutschland“ festlegen hat die App wieder zum Laufen gebracht. 

Hier muss die App wohl nach dem Update auf OS14 automatisch „Deutschland“ als Default einstellen. Das rafft sonst keiner.

**Comment by Tachy** [comment]
![Uploading CBBE359A-2F6D-4723-827B-6D4112265A26.png…]()

**Comment by JanKoehnlein** [comment]
Risikoermittlung war bei mir auch deaktiviert und ließ sich auch mit oben genannten Tricks über die Settings nicht wieder aktivieren. Region war ebenfalls ausgegraut, ließ sich aber nicht einstellen. Ebensowenig ein kompletter Neustart des Handys. Was half: Ich musste WLAN einmal aus- und wieder einschalten.

**Comment by dhs3000** [comment]
Ich habe (noch) iOS 13.7 und hatte auch das Problem, dass es plötzlich deaktiviert war und es sich mithilfe des Schiebereglers in der App nicht mehr aktivieren lies. 
WLAN aus-/an hat nicht geholfen. 
Was half war das Logging/die Exposure Notifications in den Settings komplett zu deaktivieren und danach die App erneut zu öffnen. Dann kam wieder der [Akzeptieren-Dialog (Kommentar oben)](https://github.com/corona-warn-app/cwa-app-ios/issues/1153#issuecomment-696119253) und es ist wieder aktiv.

**Comment by GPclips** [comment]
This issue has been marked as obsolete and will be closed.

**Comment by GPclips** [comment]
Hello community,

thins issue has been closed by mistake and will be partially tracked in EXPOSUREAPP-2472. I added this id to the description and will reopen the ticket.

Thanks,
LMM

Corona-Warn-App Open Source Team

**Comment by svengabr** [comment]
🔥 **Hot Topic Update** 🔥

We are discussing this issue on regular basis as its currently one of our high priority tasks.

**The latest feedback is:**
* An FAQ Entry was created https://www.coronawarn.app/en/faq/#no_risk_update_ios14
* This error is responsible for ~30% of all negative feedback from App Store
* The developers are working on finding a solution
* A party fix is expected with release 1.5 (EXPOSUREAPP-2742)

Best regards,
SG

Corona-Warn-App Open Source Team

**Comment by tibor** [comment]
Ich hatte das Problem ebenfalls. Bei mir half eine Deaktivierung und Aktivierung des Flugmodus.

Weiteres Feedback: Auf Twitter berichtet ein Nutzer, dass die Anzeige „Risiko-Ermittlung gestoppt“ [bei jedem Start angezeigt wird](https://twitter.com/holadiho/status/1311936250090323968)

**Comment by svengabr** [comment]
There is an FAQ entry available for a working workaround as well:

https://www.coronawarn.app/de/faq/#no_risk_update_ios14
https://www.coronawarn.app/en/faq/#no_risk_update_ios14

**Comment by sin-azucar** [comment]
> Weiteres Feedback: Auf Twitter berichtet ein Nutzer, dass die Anzeige „Risiko-Ermittlung gestoppt“ [bei jedem Start angezeigt wird](https://twitter.com/holadiho/status/1311936250090323968)

I'm seeing the same thing: For a few seconds (presumably until new data has been downloaded) the app shows "Risk calculation stopped" sometimes when I open the app. It seems to happen when the risk state is outdated because the app hasn't updated itself in the background for >24 hours.

This resolves itself after a few seconds, so it's not the exact case described here. Is it a UI glitch or should we be worried about the stopped risk calculation?

Maybe this deserves a separate ticket - or will it be solved with the following?

> A party fix is expected with release 1.5 (EXPOSUREAPP-2742)

**Comment by chrbucs2** [comment]
Ich habe das beschriebene Verhalten regelmäßig, allerdings auf einem OnePlus 6, Android Version 10, OxygenOS-Version 10.3.5. In meinen Benachrichtigungen sehe ich vorab immer eine Meldung, dass die Risiko-Ermittlung nicht aktiv sei, dann öffne ich die App und sehe den selben Zustand, den der Screenshot von fark0 im initialen Post zeigt. Neustarts hatte ich dazwischen auch schon einige.

**Comment by dsarkar** [comment]
Dear @fark0, @chrbucs2, @sin-azucar, and community,

This issue seems to be fixed in CWA version 1.7.1. I think we can close this one: any feedback is welcome before we do so?

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
Dear @fark0, @chrbucs2, @sin-azucar, and community,

This issue seems to be fixed in CWA version 1.7.1. We will close this issue now. If necessary, reopen this issue, please. Thanks for all your contributions.

Best wishes,
DS

Corona-Warn-App Open Source Team

**Comment by keugens** [comment]
Seems NOT to be fixed in CWA version 1.7.1

But restarting app seems to be a workaround

**Comment by keugens** [comment]
PS: status before was: receiving test result

**Comment by dsarkar** [comment]
Hi @keugens, Thanks for reporting. Do you still experience any issues with the current release 1.9.1? Thanks for the feedback. 

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
Does anyone still experience this Issue with the latest App version?

**Comment by keugens** [comment]
No. But I had no chance to reiterate the same situation, where I had this
error.
 
I'll trust your skill to have found out the error by fully understanding of
the code.
:-)

  _____
