### ISSUE TITLE
App nach iPhone-Wechsel und restore aus Backup in Setup-Schleife

### ISSUE THREAD

**Issue by odyvankinoby** [corona-warn-app/cwa-app-ios#1154]
## Avoid duplicates

* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is not already reported in another issue

## Describe the bug

Ich habe heute von iPhone XR zu iPhone 11 gewechselt. Nach Restore aus Backup konnte ich die App zwar starten jedoch bin ich aus den Firststart Setup nicht raus gekommen, konnte über weiter im er zum letzten Screen mit LOS GEHTs gelangen, wenn ich den Button geklickt habe ist das Setup einfach von vorne nochmal losgegangen. Dauernd.
Hab die App dann komplett deinstallieren & neu installiert, dann kamen auch die entsprechenden Screens hoch für Mitteilungen usw.

## Expected behaviour

Erwartung wäre gewesen entweder nach Setup auf den App Himebildschirm zu gelangen oder das setup garnicht machen zu müssen weil ich ja schon die Freigaben erstellt hatte.

## Steps to reproduce the issue

- Neues iPhone einrichten
- Restore aus Backup in dem die App enthalten ist und bereits eingerichtet war
- App starten, das Firststart Setup erscheint und lässt sich auch am Ende mit dem "los gehts" Button nicht beenden

## Technical details

- iOS Version: 13.7
- Device: iPhone 11 (neues Gerät), Backup von iPhone XR

**Comment by ferdinand** [comment]
Duplicate of #754

**Comment by svengabr** [comment]
Duplicate of #754
