### ISSUE TITLE
Please clarify blog post "Problems with iOS 13.7"

### ISSUE THREAD

**Issue by mss1010** [corona-warn-app/cwa-app-ios#1161]
## Avoid duplicates
* [x] Question is not already answered in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Question has not already been asked in another issue

## Your Question

In this blog post https://www.coronawarn.app/en/blog/2020-09-10-ios-13-bug/ an issue related to iOS 13.7 is described:

> In some cases, the app may show some users that they were exposed to a higher risk than was actually the case.

I did not find an issue on github, which explains this in detail. Is there an existing issue related to that blog post?
If not, can you describe it here, or create an issue?

**Comment by ir-fuel** [comment]
My guess:

The risk calculation in the code has 2 intervals. Low and High. 
Using the result of the call to the EN API of Apple and a whole bunch of downloaded configuration values a risk score is calculated. 

you can find that here:

https://github.com/corona-warn-app/cwa-app-ios/blob/develop/src/xcode/ENA/ENA/Source/Services/Risk/Calculation/RiskCalculation.swift#L146

And the explanation of how the calculation works you can find here:

https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md#risk-score-calculation

(good luck trying to understand it :D )


The resulting value is compared against the intervals:

Everything in the Low interval is considered low risk, everything in the High interval is high risk. The high risk interval begins where the low risk one ends.

For reasons unknown to me the high interval has an upper bound, namely 72. 

Now, what happens? It seems that in some cases the risk calculation done in the code results in a value a lot higher than 72. In that case the application writes `Serious error during risk calculation` to the logs and ignores the result of the risk calculation.

As you can see here: 

https://github.com/corona-warn-app/cwa-server/commit/3ef4ecfe1d892878a1861750c6b68f7173da35f3#diff-87cc707fc68022ad60f56519f0c460fe

The upper range has been changed to 9999 to mitigate this problem.

But the question remains: why should there be an upper range to the risk calculation?

**Comment by heinezen** [comment]
Hello everyone,

The bug is currently tracked in Jira ticket EXPOSUREAPP-2606. I will transfer the relevant information to a new Github issue, so that the situation becomes more clear.

Regards,
CH

Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
See: #1165

**Comment by mss1010** [comment]
Thank you @heinezen. Then we can close this issue here.
