### ISSUE TITLE
why is Spain left out???

### ISSUE THREAD

**Issue by ouboub** [corona-warn-app/cwa-app-ios#1164]
Hi

I am not sure that is the right forum, but I am an iOS user.
According to 
https://www.zeit.de/digital/2020-09/kontaktverfolgung-corona-warn-app-ausland-eu
the test phase will start soon, but only for 
Danemark, Tschechien, Italien, Lettland and Irland.
Spain is currently the country with highest increase of infections, and a considerable amount of death. 
Spain is, moreover, a country that has attracted, at least in the past, the visit of a huge amount of German Tourists.

Spain is using a decentralized app, whose source code will be published soon.

So why is Spain not included??
 Could you name me please the persons in charge, that are responsible for this decision.
kind regards

Uwe Brauer

**Comment by heinezen** [comment]
Hey @ouboub,

You question is currently already discussed in https://github.com/corona-warn-app/cwa-backlog/issues/14. If there are any new updates on the situation, you will probably find them there.

Regards,
CH

Corona-Warn-App Open Source Team

**Comment by ouboub** [comment]
> Hey @ouboub,
> 
> You question is currently already discussed in [corona-warn-app/cwa-backlog#14](https://github.com/corona-warn-app/cwa-backlog/issues/14). If there are any new updates on the situation, you will probably find them there.
> 
> Regards,
> CH
> 
> Corona-Warn-App Open Source Team

thanks very much I will have a look
regards
Uwe Brauer
