### ISSUE TITLE
Give an update about Issues with iOS 14 (Betas)

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#1179]
## Avoid duplicates
* [x] Question is not already answered in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Question has not already been asked in another issue

## Your Question
Apple will officially release iOS 14 tomorrow ([Source](https://www.apple.com/ios/ios-14/)).
In the last months, after the release of the iOS 14 Beta, many people reported they had Issues with the Betas.
With the information and research (looking in those Beta Issues) you have now, can you say if the CWA will work correctly for the most people under iOS 14.
Thanks!

**Comment by Marco2907** [comment]
Hi @Ein-Tim , thanks for your comment. I will discuss this in our internal development meeting and come back to you as soon as possible. 

Thanks.
MP 

Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@Marco2907 thanks, iOS 14 will be released today at 7:00 am, so it would be good if we get an answer before that 👍

**Comment by rafaelgaspar** [comment]
Any updates on wether it’s safe to update or not?

**Comment by PatiTati** [comment]
On iOS 14 official release the app doesn‘t work. The risk assessment cannot be activated. No update since yesterday 10 pm after the iOS Update has installed on my phone.

![1EEB646D-AE9A-4A69-B146-950C13E94841](https://user-images.githubusercontent.com/71453983/93493293-08c0d380-f90c-11ea-87f1-cae6000cbff3.jpeg)

**Comment by thomasaugsten** [comment]
Can you show the Risikobegegnung setting in the iOS settings. Did you try it to activate on this screen. Did you have installed multiple COVID-19 apps?

We didn't see any issues with iOS 14 so far

**Comment by PatiTati** [comment]
I have try to activate the risk assesment, but it shows as already activated. I have deactivate the risk assesment and reactivate it, now it works.
Maybe other people have same issues after updating to ios 14. I will report after i have other information.

**Comment by PatiTati** [comment]
Here are a Screenshot before i have deactivate the risk assesment an re-enabled it.
![6F761A04-2CE1-4225-85C2-5622DD7B4E7D](https://user-images.githubusercontent.com/71453983/93496166-30fe0180-f90f-11ea-9f67-30c163fd614f.png)

**Comment by thomasaugsten** [comment]
Ok we will also Check this but the App is only showing what the api is providing.

**Comment by PatiTati** [comment]
Thanks for answer and checking. Maybe its a Bug on iOS 14 and Apple‘s API. One of my friends has reporting that he has no problems after update.

**Comment by valentinhocher** [comment]
Same issue like described by @PatiTati on my after upgrading to iOS 14. Workaround via settings seems to fix it.

**Comment by thomasaugsten** [comment]
We will give this feedback to apple

**Comment by mss1010** [comment]
For me after iOS 14 update, the status in the app looks fine. I did not have an automatic background check yet, but so far everything looks normal.

**Comment by mtb77** [comment]
Can we close this issue now with the availability of iOS 14 final?

Cheers,
Sascha
--
Corona-Warn-App Open Source Team

**Comment by PatiTati** [comment]
> Can we close this issue now with the availability of iOS 14 final?
> 
> ## Cheers,
> Sascha
> Corona-Warn-App Open Source Team

No, the Issue still remains on Final iOS 14. Please read my posts. Maybe its bettet to open a new issue, because this bug is only on iOS 14 FINAL.

**Comment by Ein-Tim** [comment]
@PatiTati 
I think for you it would be the best to open a new Issue.

@mtb77 
My question wasn't really answered, but at least for me iOS 14 works.
So if you want to, you can close it

**Comment by rafaelgaspar** [comment]
Running iOS and it worked out-of-box for me.

Maybe a separate issue would be better to track this.

**Comment by Ein-Tim** [comment]
@rafaelgaspar 
Yes, I also think separate Issues would be better.
I will close this Issue and if somebody has problems after the Update, **open a new Isue**
