### ISSUE TITLE
1 Low Risk exposure but MatchCount is 0 

### ISSUE THREAD

**Issue by lgerhold** [corona-warn-app/cwa-app-ios#1188]
## Avoid duplicates

* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is not already reported in another issue

## Describe the bug

CWA says there was a low risk exposure "1 Risiko-Begegnung mit niedrigem Risiko", but MatchCount is in every check null (in the last 14 days). 

```
grep Match Downloads/ExposureChecks-2020-09-17\ 2.json | grep -v 0 | wc -l                                                                         
0

```
## Expected behaviour

The exposure was before the last 14 Days and the App says "no risk"

## Steps to reproduce the issue

1. Checking the risk in CWA
2. Comparing the risk with MatchCount in IOS 

## Technical details

- iOS Version: 14
- Device: iPhone 11

## Possible Fix

--

## Additional context

--

**Comment by Tho-Mat** [comment]
@igerhold
is this the same as #1106 ?

**Comment by lgerhold** [comment]
Hi @Tho-Mat, 

I am sorry, did not found that issue with the search. In my point of view, it is the same issue as described there. 

Kind Regards
