### ISSUE TITLE
Risiko-Ermittlung cannot be activated after iOS 14 update

### ISSUE THREAD

**Issue by qdoobp** [corona-warn-app/cwa-app-ios#1192]
## Avoid duplicates

* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is not already reported in another issue

## Describe the bug

After the update to iOS 14 the CWA shows the Risiko-Ermittlung as deactivated and it is impossible to reactivate it. The toggle looks like it was activated successfully but after returning to the main App screen Risiko-Ermittlung is still disabled. 
Force closing the CWA and restarting the phone did not help.
I tried activating it through the iOS settings but that was not successful either. 

## Expected behaviour

It should be possible to reactivate the Risiko-Ermittlung from the App.

## Technical details

- iOS Version: iOS 14
- Device: iPhone 7 Plus

**Comment by thomasaugsten** [comment]
Is this working for you?
https://github.com/corona-warn-app/cwa-app-ios/issues/1179#issuecomment-694328799

**Comment by qdoobp** [comment]
Does not seem to work. I toggled it multiple times but it is still shown as disabled.

**Comment by thomasaugsten** [comment]
the toggle Begegnungsinformationen teilen in the ios settings?

**Comment by qdoobp** [comment]
I meant the Risiko-Ermittlung toggle in the App. I will try the other one. There is a lot to toggle. 😉

**Comment by qdoobp** [comment]
Ok, that did it. Toggling the Begegnungsinformationen button in settings and resetting the CWA as the active region fixed it. 
Thank you for the help.

**Comment by Ein-Tim** [comment]
@qdoobp So I think we can close his Issue in favor of #1179?

**Comment by qdoobp** [comment]
Yes, I think so. Seems to be a similar issue. Thanks again for the quick help.

**Comment by Ein-Tim** [comment]
@mtb77 This Issue can (also) be closed.
