### ISSUE TITLE
Can’t enable exposure logging/Empty screen on iOS 13.7/14

### ISSUE THREAD

**Issue by The-JC** [corona-warn-app/cwa-app-ios#1193]
## Avoid duplicates

- [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
- [x] Bug is not already reported in another issue

## Describe the bug
I wanted to activate the App this morning, but I couldn’t I was greeted by a empty screen in settings/Corona Warn/Exposure Notifications.
This was with the latest version of the app and iOS 13.7. After some failed attempts I updated iOS to 14, thinking it might fix it. However the big is still present. I tried a multiple things including reboot of the phone and reinstallation of the App. Also I tried to firstly open settings or the other way around.

## Expected behaviour

Enabling exposure logging.

## Steps to reproduce the issue

1. Download the App or disable Exposure logging 
2. Go to Settings/Corona-Warn/Exposure Notifications
3. See nothing/image 
![](https://i.imgur.com/cv7tlzg.png)

## Technical details

- iOS Version: 13.7/14.0
- Device: iPhone 7

## Additional context
The problem occurred after disabling exposure notifications for a few days.

---
Internal Tracking ID: EXPOSUREAPP-2869

**Comment by Ein-Tim** [comment]
Thats very weird. And CWA is also showing an empty screen?

**Comment by thomasaugsten** [comment]
@The-JC can you contact me directly please thomas.augsten@sap.com

**Comment by budisek** [comment]
Same problem for me. No app with Covid Api works on my iPhone XS iOS 14 ane there is nothing to enable in settings.

**Comment by The-JC** [comment]
> Thats very weird. And CWA is also showing an empty screen?

No, the CWA works as expected and displays that exposure logging is stopped.

**Comment by budisek** [comment]
There were some config profile with api reset but it is outdated and unusable. 

[https://github.com/corona-warn-app/cwa-app-ios/issues/911](url)

**Comment by The-JC** [comment]
> There were some config profile with api reset but it is outdated and unusable.
> 
> [https://github.com/corona-warn-app/cwa-app-ios/issues/911](url)

I agree, I believe we must reset the exposure notifications api somehow. It might have got corrupted under some circumstances.

However I remember that I’ve seen this warning some time ago. It might be directly related to this issue.
![Warning](https://user-images.githubusercontent.com/6367738/87676388-d9a9ac80-c778-11ea-86b9-cdff9f3da5bc.png)

[https://github.com/corona-warn-app/cwa-app-ios/issues/911#issuecomment-659411203](issue)

**Comment by pablitovicente** [comment]
Similar problem for me on an iPhone 8; since today exposure logging is disabled and there's no way for me to enable it. 
I upgraded to iOS 14 on Friday but it worked Friday, Saturday and Sunday.
Let me know if there are any more details I could share.

**Comment by pablitovicente** [comment]
Ok I was able to get this back working by going to iOS "Exposure Notifications" and setting CWA as default and setting Active Region as "Deustchland" maybe this help other users so leaving both comments instead of deleting them.

**Comment by JanKoehnlein** [comment]
Had the same problem. Rebooting the device and changing the config as above didn't help. I had to disable/re-enable WLAN to make it work again. Maybe CWA failed to confirm the region without accessing the cell provider?

**Comment by budisek** [comment]
It doesn't work for me. Disabled WLAN, Bluetooth and have tried Flight mode but nothing changed.

**Comment by jonathanrd** [comment]
I had the same issue. The fix for me was to enable "Significant Locations" at the bottom of Settings > Privacy > Location Services > System Services > Significant Locations.

**Comment by heinezen** [comment]
Hey everyone,

Thank you for the reports. We have created a ticket for the internal Jira tracker (EXPOSUREAPP-2869) for this bug.

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by NilsKrumrey** [comment]
I had the same problem with the English NHS Corona app. What fixed it (through a suggestion from their support team) was Settings -> General -> Reset -> Reset Location & Privacy.
It seems like the app never requested the correct Exposure Notification and Location permissions - probably because something had gone wrong with multiple Covid apps or the iOS 14 upgrade.
I will have to give all my apps permissions again, but at least it's working now.

**Comment by budisek** [comment]
You are right. Resetting helped and exposure warning works again. Thanks a lot.

**Comment by svengabr** [comment]
This looks more like a general issue and not related to the CWA app. Maybe it makes sense to publish a new FAQ entry and close this issue.

**Comment by pavshr** [comment]
Hello, wanted to say that this is an issue we also noticed with Smitte|stop (Danmark), and for us it looks like an iOS issue. We reported it to Apple, I guess you should do the same.

**Comment by svengabr** [comment]
I have created a new issue in the cwa-website repository so this will get added to the FAQ soon:
https://github.com/corona-warn-app/cwa-website/issues/426

Thank you again for your input!

Best regards,
SG

Corona-Warn-App Open Source Team

**Comment by svengabr** [comment]
@NilsKrumrey your workaround was published on the FAQ website:
https://www.coronawarn.app/en/faq/#ios_black_screen
https://www.coronawarn.app/de/faq/#ios_black_screen

Thank you again for your input!

**Comment by roelspruit** [comment]
Hi. I just started as a developer on the Dutch "CoronaMelder" app. We launched nationwide this weekend and are encountering this issue in the wild too. We are even encountering this when a user has previously deleted the app and then re-installed it. The suggestion in your FAQ fixed that case too. It seems some state remains on the OS that prevents the framework from being initialised correctly.

Did you get any feedback from apple on this situation yet?

**Comment by hay** [comment]
@roelspruit just wanted to mention that i'm using the CoronaMelder app and i have this exact same issue. I tried re-installing several times as well. The 'reset privacy' thing didn't work for me, but after that i did a reboot and i did get the 'Enable COVID-19 exposure logging' popup again and was able to enable it.

**Comment by awbnet** [comment]
Potwierdzam. Działa od razu.

**Comment by diimaan** [comment]
This is because when exposure logging is enabled, Bluetooth gets disabled or completely greyed out. Could be an iOS issue or the issues of CWA! I am on latest iOS 14.5.1! I even got my phone replaced because the Bluetooth was greyed out and I was not able to use any accessories with my phone. After the replacement the new phone had the same issues. So when I disable exposure logging and remove CWA, this issues vanishes. I am not sure how to contact Apple to Dev support, but if it is a possibility to look from the CWA side let me know if I can run a testflight build and can provide some logs

**Comment by Ein-Tim** [comment]
@diimaan 

May I ask you to [open a new bug report](https://github.com/corona-warn-app/cwa-app-ios/issues/new?assignees=&labels=bug&template=01_bugs.md) where you explain the problem in detail?
Where exactly does something get grayed out or disabled because of Exposure Logging?
