### ISSUE TITLE
initial installation on new device after backup - stuck in loop

### ISSUE THREAD

**Issue by oliverlatka** [corona-warn-app/cwa-app-ios#1195]
Hi, 

I was setting up my new iPhone 11 Pro Plus and used a backup to restore my apps - but I was never able to use the warn app on the new device again. Every time I try to start the app, I need to do the initial config (privacy statements etc.) and somewhen get back to the first screen (stuck in a loop). Please watch the video: https://sap.sharepoint.com/:v:/s/103018/ESRhsajEPHhGpuI9MmoHu6EBZPdNuM6lCzjwM676U-d0gw?e=MoZLnx 

Best, 
Oliver

**Comment by thomasaugsten** [comment]
This problem will be fixed in next version please delete and reinstall the app

**Comment by oliverlatka** [comment]
thx for the fast reply
