### ISSUE TITLE
Main screen shows an extra exposure

### ISSUE THREAD

**Issue by kamil98** [corona-warn-app/cwa-app-ios#1217]
## Avoid duplicates

* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is not already reported in another issue

## Describe the bug

Yesterday my exposure count (in the app) was zero. Today it is 1 even though the exposure log shows zero matches.

I clicked through all exposure checks in the Settings app and all of them show "Matched Key Count: 0" 

## Expected behaviour

I'd expect that the "Matched Key Count", in the Settings app will correlate to the cwa main screen. 

## Steps to reproduce the issue

I'm not really sure how to reproduce this bug 🤷🏻‍♂️

## Technical details

- iOS Version: 14.0
- Device: iPhone XS
- app version: 1.3.0 (6)

## Additional context

Exposure check log (from the Settings app): [ExposureChecks-2020-09-22.json.txt](https://github.com/corona-warn-app/cwa-app-ios/files/5263427/ExposureChecks-2020-09-22.json.txt)
All "MatchCount" values are 0.

A screenshot from today: 
![IMG_8774](https://user-images.githubusercontent.com/15572959/93924888-a570e000-fd15-11ea-94a2-5ee753ec2a0e.png)

**Comment by Ein-Tim** [comment]
Duplicate of #1106

**Comment by kamil98** [comment]
Ups, sorry. I didn't find it when I was looking for previously created issues.
