### ISSUE TITLE
Dauerloop der Start-Hinweise bei Öffnung der App

### ISSUE THREAD

**Issue by wandoliver** [corona-warn-app/cwa-app-ios#1232]
Ich habe von Apple ein Garantie-Austausch-iPhone erhalten und ging davon aus, dass beim Übertrag der Daten des alten Gerätes auch die App mit erfasst wurde.
Offenbar nicht. Wenn ich nun die App öffne, lande ich auf folgenden Screens:

1. "Gemeinsam Corona bekämpfen" -> Los geht's
2. "Datenschutz" -> weiter
3. "Wie Sie die Risiko-Ermittlung ermöglichen" -> weiter
4. "Falls Sie Corona-positiv getestet werden..." -> weiter
5. "Warnungen erhalten, Risiken kennen" > weiter

und hier bei dem letzten "weiter" springt die App wieder zurück auf 1. Ich bin in einem Dauerloop.

- iOS 14
- Risikoermittlung aktiv, Region manuell gesetzt

**Comment by Ein-Tim** [comment]
Duplicate of: https://github.com/corona-warn-app/cwa-app-ios/issues/754

**Comment by heinezen** [comment]
Duplicate of #754

**Comment by wandoliver** [comment]
Der Titel "Can't activate exposure logging after iCloud backup restore" lässt zunächst nicht auf ein Duplikat schliessen. Aber der dortige Hinweis auf Neuinstallation der App hat geholfen. Danke.
