### ISSUE TITLE
Discussing the actual meaning of Timestamps of a Matched Key in "Exposure Checks"-Detail Screen

### ISSUE THREAD

**Issue by itinance** [corona-warn-app/cwa-app-ios#1245]
## Current Implementation

**Device:** iPhone 11 Pro with iOS 13 and 14:

### Step 1

Going to **"Settings"** -> **"Privacy"** -> **"Health"** -> **"COVID-19 Exposure Logging"** -> **"Exposure Checks"** 

will show us a ListView with Title _"Exposure Checks"_, which follow all the same model: multiple entries per day, all happening at the very same time per day (though the timestamp on the next day may be obviously some minutes later than at the day before):

![IMG_0B7C5C018C15-1](https://user-images.githubusercontent.com/1758597/94340644-c4b48980-0003-11eb-9bd2-c53f615dcb17.jpeg)

### Step 2

Tapping on a ListItem will navigate to a detail screen showing attributes like **"Matched Key Counts"** and a **Timestamp**.

![IMG_AB4F1413F452-2](https://user-images.githubusercontent.com/1758597/94341067-ce8bbc00-0006-11eb-952a-877a752bed26.jpeg)

## The Issue

What exactly does the timestamp mean? Many People are curious about this and discussing wether it will show the timestamp of the final contact when it really was happening (which makes no sense in my current case), or is it just the timestamp when the data was fetched from the server for an exposure check?

Since most of them think this was the timestamp of the real contact, it leads to a mis-interpration which could be dangerous at the end.

But in my case, every time when I found a new matched Key, I was sitting at my home-office without any other contact around. 

Also, especially today 2 hours ago, my number of exposures has increased and the related timestamp showing this Matched Key was happening 2 hours ago (when I opened the App for the first time today, without leaving the building).

Therefor I guess this timestamp means just the timestamp of latest data fetches instead of the actual timestamp when a contact was happening. But I don't know yet, could not find any information about this and thus can't tell people the truth which are asking me.

## Suggested Enhancement

Pls show the users more information and more details what these data and timestamps really means.

## Expected Benefits

- Less question marks and discussions in Forums, Social Media, Families, Offices and so on. 
- Less misleading interpretations of this timestamp.

**Comment by daimpi** [comment]
The `timestamp` is the time when your CWA downloaded keys from the server and handed them over to the Exposure Notification Framework (ENF) to check for a match ([FAQ Entry](https://www.coronawarn.app/en/faq/#keys_matches)).

For more details on the whole process see my answer here: https://github.com/corona-warn-app/cwa-app-android/issues/1217#issuecomment-697631273 🙂.

**Comment by itinance** [comment]
Thank you very much @daimpi ! This helps a lot. Nevertheless, you should provide the FAQ Entry or a hint message to it on this screen. There is still space left :)

**Comment by daimpi** [comment]
Glad I could help 🙂.

On which screen would you like to see a FAQ link? The screenshots above are all from the iOS backend which is controlled by Apple and the CWA team doesn't have any control over what is shown there.

**Comment by itinance** [comment]
> On which screen would you like to see a FAQ link? The screenshots above are all from the iOS backend which is controlled by Apple and the CWA team doesn't have any control over what is shown there.

Good to know that. Well, thats difficult now, but thanks for asking.

I have some ideas:

- to show an Info-Icon/Button next to _"`$number` encounters with low risk"_ (and only if `$number` > 0) which navigates to a screen that will explain the meaning of the Detail Screen and especially the timestamp
- generally show a button to such an info screen on the home-screen
- put this section https://www.coronawarn.app/en/faq/#keys_matches into the app as well next to "FAQ"
- integrate https://www.coronawarn.app/en/faq/#keys_matches into the official FAQ (on bundesregierung.de it is not available)
- reach out to Apple and ask for showing these information into the detail screen mentioned in my issue _(yes....)_ :)

**Comment by daimpi** [comment]
Sounds interesting. Maybe someone from the CWA UX team could take a look at this 🙂.

**Comment by Ein-Tim** [comment]
@itinance 
Since you are asking to show more (relevant) information in the App, feel free to upvote: https://github.com/corona-warn-app/cwa-wishlist/issues/165

**Comment by itinance** [comment]
Thx @Ein-Tim! Already done.

**Comment by svengabr** [comment]
Hello everyone,

there is already an internal proposal for showing more information regarding risk encounters. We will open a new wishlist entry for this soon to make it more transparent for everyone.

An overhaul of risk encounters information UI/UX was implemented with the app version 1.3.1 which is already available.

If you think you have additional ideas, please create a separate wishlist item or upvote an existing one.

Otherwise, I would like to ask you if this ticket could be closed.

Thanks!
