### ISSUE TITLE
Exposure Logging can not be activated

### ISSUE THREAD

**Issue by x34r0x** [corona-warn-app/cwa-app-ios#1246]
## Avoid duplicates

* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is not already reported in another issue

## Describe the bug

Since this morning I can’t activate my exposure logging anymore. The app only shows “exposure logging stopped” even when I switch it on. I didn’t switched it off before.

## Expected behaviour
Exposure logging to be switched on And to be active afterwards. No automatical switch off.

## Steps to reproduce the issue

![98BE8231-7F70-47E5-A11C-0CAD7F0F306B](https://user-images.githubusercontent.com/71961858/94359310-9a67d800-00a6-11eb-9b7f-23886ca88ef1.jpeg)
![5176AE86-0570-419B-AF9E-60B23A3080DB](https://user-images.githubusercontent.com/71961858/94359315-9c319b80-00a6-11eb-9627-be0da043c2ce.jpeg)

Open App and switch on Exposure Logging

## Technical details

- iOS Version: 13.7
- Device: Iphone 7
- App Version: 1.3.2(0)

## Additional context

Please fix it - I’m not able to.

**Comment by thomasaugsten** [comment]
you can find the solution in the faq
https://www.coronawarn.app/en/faq/#no_risk_update_ios14v

**Comment by x34r0x** [comment]
Thanks - I just searched for exposure logging...but there are no information in English on your link...

**Comment by Ein-Tim** [comment]
@x34r0x 
Here is the working link to the FAQ:  https://www.coronawarn.app/en/faq/#no_risk_update_ios14

But since you are not on iOS 14, lets take a closer look at this.

Are Background Tasks enabled for CWA?

**Comment by x34r0x** [comment]
Yes. Now everything works - the exposure logging is active again.

**Comment by thomasaugsten** [comment]
Did you change something or it fix self without any doing from your side

**Comment by x34r0x** [comment]
I reinstalled the app.
