### ISSUE TITLE
IOS 14 Error 11

### ISSUE THREAD

**Issue by p-doubleu** [corona-warn-app/cwa-app-ios#1284]
Problem nach wie vor bei iphone11 pro. Fehlercode 11. bekomme keine Auswertung meiner Begegnungen

## Avoid duplicates

* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is not already reported in another issue

## Technical details

- iOS Version:
- Device:

**Comment by Ein-Tim** [comment]
Und dieses Problem besteht erst nach dem Update auf iOS 14.0

**Comment by p-doubleu** [comment]
Ich hatte das Problem schon immer, konnte die App bisher nie nutzen. Entweder durch den Bug im IOS 13, dann durch IOS14 Beta und jetzt IOS14.

**Comment by Ein-Tim** [comment]
Okay und das Problem ist das die App keine neuen Daten herunterlädt? 
Ist Hinterhrundaktualisierung eingeschaltet?

**Comment by thomasaugsten** [comment]
Kannst du von dem Fehler und von den iOS Begegnungsbenachrichtiung Einstellungen Screenshots erstellen.

**Comment by p-doubleu** [comment]
![Uploading C759A6C4-337F-4488-86CB-0DA16502C8DD.png…]()

**Comment by daimpi** [comment]
@p-doubleu 
> Uploading C759A6C4-337F-4488-86CB-0DA16502C8DD.png…

Der Upload hat scheinbar nicht funktioniert, kannst du das nochmal versuchen?

**Comment by p-doubleu** [comment]
![8D0A0BD7-F86A-44AE-9722-3687FC7497EB](https://user-images.githubusercontent.com/72257875/94941981-f6cb5d00-04d5-11eb-9054-87647939e504.jpeg)
![E356E9A2-8593-4F89-8528-9FE43E635D87](https://user-images.githubusercontent.com/72257875/94941987-f92db700-04d5-11eb-94de-bd24188ed6f2.jpeg)
![1B56EE98-75BA-4122-B985-3431F3787072](https://user-images.githubusercontent.com/72257875/94941989-f9c64d80-04d5-11eb-88c2-407d57b05481.jpeg)

**Comment by Ein-Tim** [comment]
Okay, Fehler 11...
Eigentlich sollte dieser Fehler mit iOS 13.6 behoben worden sein, siehe @tkowark's statement here: 

https://github.com/corona-warn-app/cwa-app-ios/issues/972#issuecomment-665933630

**Comment by p-doubleu** [comment]
![C9EA1948-A2D1-4DFE-95CF-D754BAFC42EC](https://user-images.githubusercontent.com/72257875/94944939-401dab80-04da-11eb-8e89-f8507f0af341.png)
Scheinbar leider nicht

**Comment by Ein-Tim** [comment]
@p-doubleu 
Okaaay, du benutzt auch jetzt noch die iOS 14.2 Beta. Die sollte eigentlich funktionieren. Teilst du bitte noch einen Screenshot von dem Menü "Begegnungsmitteilungen"?

**Comment by p-doubleu** [comment]
![67DB177B-2605-4F85-AC53-A77E639F9A4A](https://user-images.githubusercontent.com/72257875/94945659-4b250b80-04db-11eb-80d6-7591d7a62c43.png)
Die Verfügbarkeitshinweise lassen sich nicht bearbeiten, schon vor Wochen alles durchgeschaut

**Comment by Ein-Tim** [comment]
Okay, sieht so aus als würde dein iPhone über Bluetooth Beacons verschicken & empfangen. Was kommt wenn du auf "Aktiv" und dann auf "Begegnungsüberprüfungen" klickst? Wann ist dort in der Liste der letzte Eintrag? 

Hast du Hintergrundaktualisierung für die Corona Warn App an?

**Comment by p-doubleu** [comment]
![5CC17664-8804-4B85-9A91-12B16FBB5D17](https://user-images.githubusercontent.com/72257875/94946141-fb930f80-04db-11eb-9a67-9a07a170694e.png)
![51627C67-7FEF-4116-A91D-0B64DDF2FCE8](https://user-images.githubusercontent.com/72257875/94946318-3a28ca00-04dc-11eb-906e-b0d5d362065d.jpeg)

**Comment by thomasaugsten** [comment]
Kannst du die Ortungsdienste kurzzeitig zum testen aktivieren bzw. auch unter Ortungsdiensten System alle aktiviere

**Comment by p-doubleu** [comment]
Ortungsdienste sind an, aber die App wird nicht aufgeführt

**Comment by thomasaugsten** [comment]
Kannst du mich bitte direkt kontaktieren dann leite ich das Problem direkt an Apple weiter.

**Comment by thomasaugsten** [comment]
Der einzige Weg ist in den iOs Einstellungen -> Begegnungsmitteilungen diese ganz unten einmal zu deaktivieren und dann zu aktivieren.

**Comment by p-doubleu** [comment]
Hallo, das habe ich schon mehrmals gemacht - jetzt geht’s plötzlich, komisch

Mit freundlichen Grüßen

Paul Wiegand

Am 06.10.2020 um 08:23 schrieb Thomas Augsten <notifications@github.com>:

﻿

Der einzige Weg ist in den iOs Einstellungen -> Begegnungsmitteilungen diese ganz unten einmal zu deaktivieren und dann zu aktivieren.

**Comment by svengabr** [comment]
Hey @p-doubleu, I am happy to hear that you were able to resolve your problem.

I think it would make sense to extend the [FAQ entry](https://www.coronawarn.app/de/faq/#ENError11) with the workaround from @thomasaugsten. I will create an issue for this on the website repository.

I will close this issue and mark it as duplicate.

Best regards,
SG

Corona-Warn-App Open Source Team

**Comment by svengabr** [comment]
Hey @p-doubleu, I am happy to hear that you were able to resolve your problem.

I think it would make sense to extend the [FAQ entry](https://www.coronawarn.app/de/faq/#ENError11) with the workaround from @thomasaugsten. I will create an issue for this on the website repository.

I will close this issue and mark it as duplicate.

Best regards,
SG

Corona-Warn-App Open Source Team

**Comment by svengabr** [comment]
Duplicate of https://github.com/corona-warn-app/cwa-app-ios/issues/972
