### ISSUE TITLE
Images streched on landscape orientation

### ISSUE THREAD

**Issue by SushiTee** [corona-warn-app/cwa-app-ios#131]
## Description

Images on _Risikoermittlung_ page are streched when in landscape orientation.

![20200602_092859000_iOS](https://user-images.githubusercontent.com/293612/83504817-3f8ded80-a4c5-11ea-90ef-e84b779694ea.png)
![20200602_092911000_iOS](https://user-images.githubusercontent.com/293612/83504828-41f04780-a4c5-11ea-8999-61ae83507ad6.png)

## Expected behaviour

Images should not be streched. I didn't find any other location where this happens.

## Steps to reproduce the issue

- Click on Risikoermittlung gestoppt
- turn Device to landcape
--> images streched
--> circle doesn't fit into elemet

## Technical details

Device:
- iPhone SE (2nd gen.)

OS:
- iOS 13.5

SW version
- ENACommunity
- _development_ branch at 98a7c119e039217e72ac6ab9fee77b5a95a0d001

**Comment by steins-code** [comment]
@SushiTee thanks for the bug report :) 
If you like just open a PR for it to be solved.

**Comment by haosap** [comment]
Hi @SushiTee @steins-code ,
I need to clarify with Ux, if the app supports landscape. 
Please don't work on it.

**Comment by SushiTee** [comment]
@haosap well then I'll wait before I report the 2nd landscape bug I found.
Then the bug would be that landscape is not disabled.

@steins-code I guess I would likely break more things than fix as I'm not usually working on iOS Software.

**Comment by haosap** [comment]
HI @SushiTee ,
We confirmed that, the first version doesn't support the landscape.
Next PR will disable it.
Thanks! I'll close this issue.

**Comment by SushiTee** [comment]
It is still there btw...

Bug should only be closed **after** it's fixed. Best with a ref to the commit which is supposed to fix the bug.
