### ISSUE TITLE
iOS 14: does the app run reliably on iOS14 

### ISSUE THREAD

**Issue by ouboub** [corona-warn-app/cwa-app-ios#1328]
Hi

given the (still remaining) problem, with background updating when running in low power mode, in 13.7
is it safe to upgrade to 14.0.1?

regards

Uwe Brauer

**Comment by Ein-Tim** [comment]
Related #1179

**Comment by ouboub** [comment]
> If you're already on iOS 14, an update on iOS 14.0.1 is surely safe (regarding ENF).
> If you're still on iOS 13.7, i can only tell that for me all went good 
> 
> Edit: I've opened an Issue about iOS 14 Issues before the release of it, see here: #1179

thanks, I will try.

**Comment by Ein-Tim** [comment]
@ouboub 
Did anything work?
If so could you close this Issue please?

**Comment by ouboub** [comment]
> @ouboub
> Did anything work?
> If so could you close this Issue please?

hi, I installed iOS14 on my iPad and run into some issues, that is why I still did not install in on my iPhone, so I will need some days more of testing before reaching to a conclusion, I hope this is ok?

**Comment by Ein-Tim** [comment]
Yes for sure, take your time 👍

**Comment by ouboub** [comment]
After three days of testing, I conclude that there is no notable difference to iOS13 concerning the app.
So I close that issue for now.
regards
