### ISSUE TITLE
testflight.

### ISSUE THREAD

**Issue by ouboub** [corona-warn-app/cwa-app-ios#1329]
I just pulled and saw in the logs that there is a testflight version for beta testers.

is it possible to become a beta tester?

**Comment by Ein-Tim** [comment]
Please follow up here: https://github.com/corona-warn-app/cwa-documentation/issues/214

**Comment by heinezen** [comment]
Duplicate of #29

**Comment by heinezen** [comment]
Hey @ouboub ,

Please look at the answer from this issue: https://github.com/corona-warn-app/cwa-app-ios/issues/29#issuecomment-636375504

CH

----
Corona-Warn-App Open Source Team

**Comment by ndegendogo** [comment]
Or, maybe duplicate of https://github.com/corona-warn-app/cwa-wishlist/issues/153

The disussion there shows that there may be good reasons for broader beta testing.

@ouboub feel free to upvote or comment on that ticket.
