### ISSUE TITLE
Update to 1.5.0 turns 7 day old high risk encounters to low risk

### ISSUE THREAD

**Issue by fabboe** [corona-warn-app/cwa-app-ios#1365]
Since Sunday (Oct 18) I had a five risk encounters shown, last one 7 days ago. High risk. This morning just before updating the app as well.

After updating now to iOS 1.5.0 (iOS 14.0.1 unchanged) there was a new sync and suddenly I have only five low risk encounters.

The high risk encounter was outside of Germany between to German CWA/phones. It was in a country that's not yet listed as participating.

No more high risk. Bug? Feature?

Or was the previous high risk a bug? 
I don't think so, since I know the person who entered a positive test and our (actual high risk) encounter matched the previous app information.

1.5.0 touched risk scoring in at least these PRs: https://github.com/corona-warn-app/cwa-app-ios/pull/1137 https://github.com/corona-warn-app/cwa-app-ios/pull/1060 https://github.com/corona-warn-app/cwa-app-ios/pull/1265  https://github.com/corona-warn-app/cwa-app-ios/pull/1162

----
ENF logs:

https://pastebin.com/f027GYK1
https://pastebin.com/9mDZiQkz

---
Internal Tracking ID: EXPOSUREAPP-3402

**Comment by heinezen** [comment]
Hey @fabboe ,

Thanks for reporting the issue. Could you provide the ENF logs for us? This would help us to better investigate your problem.

Thanks,
CH

----
Corona-Warn-App Open Source Team

**Comment by fabboe** [comment]
Sure: https://pastebin.com/f027GYK1

**Comment by daimpi** [comment]
@fabboe 
Thanks for sharing 🙂.

@heinezen unfortunately it doesn't look like we will be able to learn anything from the log as all the entries have `"MatchCount" : 0` i.e. issue https://github.com/corona-warn-app/cwa-app-ios/issues/1106 🙁.

**Comment by norbertschuler** [comment]
I also had the problem that yesterday my app warned me about a high risk encounter (red screen) about 2 days ago, but today after the update the app shows again only low risk encounters (green screen). Unfortunately I have only the export of the matching of today, where all `MatchCount` values are zero. Is it possible to trigger a match manually or do I have to wait for another test until the app triggers another match tonight?

Yesterday:
![IMG_8526](https://user-images.githubusercontent.com/1532418/96698850-caf61580-13b7-11eb-87e3-7fd400f825e2.jpg)

Today:
![IMG_8532](https://user-images.githubusercontent.com/1532418/96698864-cf223300-13b7-11eb-87fe-b780b2e13769.jpg)

(The technical hotline could not answer the question about the difference between yesterday and today.)

**Comment by Ein-Tim** [comment]
@fabboe 
Could you update to iOS 14.1, this should solve the Problem with the 0s in the EN-Log, and share your log again after the first check on iOS 14.1 was done? Thanks!

**Comment by daimpi** [comment]
@norbertschuler thanks for reporting. Great that you're now on iOS 14.1 👍. Could you also share your EN log here after your CWA sync tonight?

**Comment by fabboe** [comment]
Updated to 14.1 and it synced right afterwards: https://pastebin.com/9mDZiQkz

Match count now matches number of encounters in app. Hope that helps.

**Comment by daimpi** [comment]
@heinezen I do think there is something fishy going on here… the sudden change of risk right when updating to CWA 1.5 is a bit too unlikely especially as the number of encounters stayed exactly the same… unfortunately @fabboe number of contacts went now down by one, but right after the update it was still at five… 
Take this together with @norbertschuler's report and this just being a coincidence gets increasingly unlikely. 

For a coincidence both of them would have to phase out an old high-risk contact and replace it with a new low risk one right at the time when they updated to CWA 1.5, that sounds extremely improbable. It's imho much more likely that something in the risk calculation changed… Question would o/c be whether the new calculation or the old one was working correctly.

I think it would be good to have some devs look into this to get more clarity on this issue.
We will also not be able to deduce much more from the EN logs we can get now b/c all the entries before the update to iOS 14.1 will have 0 matches and the iOS update only happened after the CWA update.

**Comment by fabboe** [comment]
In theory I have still three more days to phase out of the previous high risk encounter. 

Also I asked the high risk encounter whether they removed the positive test result from the app - they didn't.

In the pool of high-risk encounters of the very same positive test there's at least one more such example - turned green.

In these times the risk scoring should become more conservative - not less :)

**Comment by norbertschuler** [comment]
> But there is one interesting observation: the hash for what is highly likely the same package changes between 18th and 19th i.e. the hash for the package changed with the update to CWA 1.5 even though KeyCount stayed the same.

I can confirm a change in the hash values for the files with the same amount of key counts between `"Timestamp" : "2020-10-21 01:33:30 +0200"` and `"Timestamp" : "2020-10-20 00:42:00 +0200"` and all exposure checks before in my exported file: [ExposureChecks-2020-10-21.json.zip](https://github.com/corona-warn-app/cwa-app-ios/files/5417123/ExposureChecks-2020-10-21.json.zip)

**Comment by daimpi** [comment]
@norbertschuler thanks for sharing, looking forward to your new log with iOS 14.1 🙂.

**Comment by Ein-Tim** [comment]
Hey @daimpi
 
This is the Screenshot of the EN-Log before the Update to Version 1.5.0:

<img src="https://user-images.githubusercontent.com/67682506/96775071-44592c80-13e7-11eb-9eb8-b1ae2fee670d.png" width="300">

---

And this is a Screenshot of the EN-log after the Update to Version 1.5.0:

<img src="https://user-images.githubusercontent.com/67682506/96774969-1e338c80-13e7-11eb-9685-acf370b81fc3.png" width="300">

As you can see **all** Hash Names changed and also these are not the same which are shown [here](https://ctt.pfstr.de/json/filehashes.json)...

@thomasaugsten Can you confirm that this Behaviour is planed and that there is nothing which did go wrong with the update?

**Comment by ndegendogo** [comment]
Can it be a change on the server side? E.g. different risk parameters, or the risk values associated with the keys?

**Comment by daimpi** [comment]
@ndegendogo 
> Can it be a change on the server side? E.g. different risk parameters, or the risk values associated with the keys?

At least the [config parameters](https://github.com/corona-warn-app/cwa-server/tree/master/services/distribution/src/main/resources/master-config) for CWA seem not to have changed. The most recent changes there were conducted mid of September.

**Comment by norbertschuler** [comment]
My todays matching shows 10 low risk results (one less then before) and still no more high risk in the exported exposure checks, e.g. for the timestamp `"Timestamp" : "2020-10-22 03:26:41 +0200"` the following file:
```
        {
          "Hash" : "3908E8EF3DE421C31CD585B8CBAFCEA7D54C21BF94E5E690A477AEE217E8B95A",
          "MatchCount" : 10,
          "KeyCount" : 4814,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-10-22 03:26:43 +0200"
        },
```
which by the way had no match count yesterday at `"Timestamp" : "2020-10-21 01:33:30 +0200"`:
```
        {
          "Hash" : "3908E8EF3DE421C31CD585B8CBAFCEA7D54C21BF94E5E690A477AEE217E8B95A",
          "MatchCount" : 0,
          "KeyCount" : 4814,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-10-21 01:33:32 +0200"
        },
```
and a different hash the day before at `"2020-10-20 00:42:00 +0200"`:
```
       {
          "Hash" : "668843EBFF9C6F67797D21091C025E117DB8831CD9019B66D9BC82E00F25A0D0",
          "MatchCount" : 0,
          "KeyCount" : 4814,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-10-20 00:42:03 +0200"
        },
```
Here is my exported file: [ExposureChecks-2020-10-22.json.zip](https://github.com/corona-warn-app/cwa-app-ios/files/5420308/ExposureChecks-2020-10-22.json.zip)

**Comment by fabboe** [comment]
@norbertschuler was your device in Germany during the risk encounters and during the recent matching?

Just to rule out that this is a corner case due to introduction of roaming (my risk encounters were outside of Germany, with another German device). If I recall correctly the roaming prefixes the keys/hashes with a current-country-specific part - this could explain the changed hashes.

**Comment by norbertschuler** [comment]
> @norbertschuler was your device in Germany during the risk encounters and during the recent matching?

In my case I have been in Germany in my home town all the time.

**Comment by ndegendogo** [comment]
@norbertschuler on which day did you update to iOS 14.1?
Because previous iOS versions since 13.7 had a bug and did *not* show the matches in ENF log (json). See #1106 for details

**Comment by norbertschuler** [comment]
> > which by the way had no match count yesterday
> 
> @norbertschuler on which day did you update to iOS 14.1?
> Because previous iOS versions since 13.7 had a bug and did _not_ show the matches in ENF log (json). See #1106 for details

Ok, that's an explanation as I updated yesterday (2020-10-21 after the nightly matching job) to iOS 14.1, so only the ENF log of today is showing match counts.

**Comment by daimpi** [comment]
@norbertschuler 

the package you matched with (pre 1.5 hash: `668843EBFF9C6F67797D21091C025E117DB8831CD9019B66D9BC82E00F25A0D0`) contains keys uploaded 2020-10-18 only one day after @fabboe's package. Both are right around the time when the padding multiplier on the server was dropped to 1… and also this is the timeframe when federation roaming was introduced 🤔.

@fabboe the keys from federation roaming look the same as those from the Germany at least once they are distributed by the national servers:  
> Looked at a downloaded German CWA server key file, there’s no way to distinguish the keys by country.

([via](https://covidapps.slack.com/archives/C0194ML0MLN/p1603219740217400?thread_ts=1603106882.114800&cid=C0194ML0MLN) @mh-)

@heinezen I think you can remove the "further input needed" label… We probably now have all the info we can get and need someone familiar with the changes on the server and CWA side to investigate this.

**Comment by heinezen** [comment]
@daimpi @norbertschuler @fabboe 

Yes, looks like the devolopers can take over. Thanks for all the input. It's mirrored to the internal Jira now (ticket ID: EXPOSUREAPP-3402), so the devs can pick it up.

CH

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@fabboe I think we should consider if this Issue can be closed now since I think the number of users updating from version 1.3 to 1.5 isn't very high anymore. 
But for sure it's up to you and the Open Source Team to decide (cc @dsarkar)

**Comment by fabboe** [comment]
The specific issue can be closed indeed. Up to the dev team to decide investigating the underlying problem that might reappear under different issues.
