### ISSUE TITLE
Version 1.5 where is the diary?

### ISSUE THREAD

**Issue by ouboub** [corona-warn-app/cwa-app-ios#1367]
It was announced in the news that 1.5 would come with two new features.

- some support for some European countries (this I found)

- some sort of diary, but this I cannot find, where is this supposed to be?

regards

**Comment by Ein-Tim** [comment]
I think with diary you mean the Symptoms Feature, this means that when you get tested positiv you can add the symtomps to the keys you send to the server so the Risk Evaluation gets more precisely. 
![image](https://user-images.githubusercontent.com/67682506/96465022-c9e2ae00-1228-11eb-81fc-6a61b7cab47a.png)
(Image from the new [Blog entry](https://www.coronawarn.app/de/blog/2020-10-19-version-1-5/)

**Comment by ouboub** [comment]
Ok so this is only useful, once you have a positive test?
ok.
I still think my proposal https://github.com/corona-warn-app/cwa-wishlist/issues/196
would be useful, but I can see that similar proposal have been added recently but non got implemented, yet

**Comment by Ein-Tim** [comment]
Correct, this is useful if you tested positive.
No, neither your proposal nor any other proposal have been implemented. 

If your happy with the answers could you close this Issue? Thanks!

**Comment by ouboub** [comment]
thanks, I close it.
