### ISSUE TITLE
ENA error 2

### ISSUE THREAD

**Issue by Rello** [corona-warn-app/cwa-app-ios#1368]
Hello 
Since updating to iOS14, the app does not work anymore. 
Logging was disabled at the time of the update. 

App removal and reinstall does not change anything

![701C55F8-13AC-4478-9382-5474B8C2B09F](https://user-images.githubusercontent.com/13385119/96495274-eb9f5d80-1247-11eb-8dc2-94df4eef665d.png)

Settings->Corona-Warn->Exposure Notification
Returns a blank page

![762147D9-53A5-4C50-843F-E1EDDAB6F665](https://user-images.githubusercontent.com/13385119/96495387-14bfee00-1248-11eb-9e90-eb748a227713.png)

Any advice?

**Comment by Ein-Tim** [comment]
@Rello 
Could you try to do what is proposed in: https://www.coronawarn.app/en/faq/?search=Empty#ios_black_screen and report back if this helped?

**Comment by Rello** [comment]
This one worked!
thank you for the quick advice!
