### ISSUE TITLE
Link for "More Information" isn't opened via In-App-Browser

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#1376]
## Avoid duplicates

* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is not already reported in another issue

## Describe the bug

All Links (f.e. the Frequently Asked Questions Link on the "Main Page" of the App) are opened in the In-App-Browser.
The Link "More Information" which is showed at the bottom of the Risk Card if you had a Low Risk Encounter is opened in the devices standard Browser. 

## Expected behaviour

This Link should also open in the In-App-Browser

## Steps to reproduce the issue

1. Get a Low Risk Encounter
2. Click on the Risk Card and scroll all the way down to the very bottom
3. Click the Link

## Technical details

- CWA Version: Since the Link was included (1.3.2)

## Possible Fix

Open the Link in the In-App-Browser, how it is done with all other Links 

---
Internal Tracking ID: EXPOSUREAPP-3405

**Comment by heinezen** [comment]
Hey @Ein-Tim ,

Thanks for reporting. I have mirrored your issue to Jira (ticket ID: EXPOSUREAPP-3405). The developers will have a look at this now.

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
Closing this Issue when #1625 is merged 👍

**Comment by Ein-Tim** [comment]
Closed via #1625
