### ISSUE TITLE
Während der Risiko-Ermittlung ist ein Fehler aufgetreten. EN Code: 2

### ISSUE THREAD

**Issue by marcelloceschia** [corona-warn-app/cwa-app-ios#1387]
## Avoid duplicates

* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is not already reported in another issue

## Describe the bug

Während der Risiko-Ermittlung ist ein Fehler aufgetreten. EN Code: 2

![IMG_6732](https://user-images.githubusercontent.com/203448/96783005-af0d6680-13ed-11eb-9c6e-3e744a1bba43.PNG)

Nach Aktivierung der Region Schweiz letzter Woche und dem Zurücksetzen auf Deutschland, ist keine Risiko-Ermittlungen mehr möglich. App ist bereits neu installiert.

Button "Mehr Erfahren" hat keine Wirkung

## Technical details

- iOS Version: 14.2
- Device: iPhoneX

**Comment by Ein-Tim** [comment]
@marcelloceschia 
If you upgrade to iOS 14.2 Beta 4 it will work again.

**Comment by Ein-Tim** [comment]
Duplicate of #1139
