### ISSUE TITLE
Why am I getting this reminder?

### ISSUE THREAD

**Issue by ndegendogo** [corona-warn-app/cwa-app-ios#1388]
![C93E3605-0BC4-436D-92B9-5E22A525B911](https://user-images.githubusercontent.com/6118267/96788723-3958c900-13f4-11eb-8cb6-b6d3f215371c.png)

## Avoid duplicates
* [ ] Question is not already answered in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Question has not already been asked in another issue

## Your Question

* Source File:
* Line(s):
* Question:

Today I got a notification from cwa, it reminds me to open it regularly and to check my risk status.

This is confusing, because:
1) I open it already daily to check my status (currently 3 green low-risk). So I expect cwa to know this.
2) in case of a "serious change", e.g. "red risk", I would indeed expect such a notification. But why for a green risk that is the same as yesterday?
3) the time of the message was not related to the risk checking procedure. The message popped up at 12:25. Yesterday ut checked at 16:27, today at 16:44

cwa 1.5.0(8) / iOS 13.7 / iPhone 8

**Comment by Ein-Tim** [comment]
Hey @ndegendogo 
This is a bug in CWA Version 1.5.0 and will be solved with Version 1.5.1

**Comment by miallo** [comment]
I just got this notification, despite the installation of 1.5.1 this afternoon and after I had the app opened several times afterwards.

**Comment by Ein-Tim** [comment]
@miallo 
Could you please wait for another 48h and report back if you still get this reminder?

**Comment by dsarkar** [comment]
Dear @miallo and dear community,

thank you for your posts.
My understanding is that the issue has been revolved, since no more reports on this issues have been posted here.
For the moment I will close this issue. Of course, should the issue emerge again, please open a new issue.

Best regards,
DS

Corona-Warn-App Open Source Team
