### ISSUE TITLE
Code comments link to non-public repository

### ISSUE THREAD

**Issue by ir-fuel** [corona-warn-app/cwa-app-ios#1393]
## Avoid duplicates
* [x] Question is not already answered in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Question has not already been asked in another issue

## Your Question

* Source File:
[`SymptomsOnset.swift`](https://github.com/corona-warn-app/cwa-app-ios/blob/a1b47b3e054110e68f2cf4e7ad3135fb2041c842/src/xcode/ENA/ENA/Source/Models/SymptomsOnset.swift#L62)
* Line(s):
62
* Question:
The link

https://github.com/corona-warn-app/cwa-app-tech-spec/blob/56521167b688f418127adde09a18a48f262af382/docs/spec/days-since-onset-of-symptoms.md

Points to `cwa-app-tech-spec` which is not public

---
Internal Tracking ID: EXPOSUREAPP-3428

**Comment by heinezen** [comment]
Hey @ir-fuel ,

Thanks for the feedback. I've reported this to Jira with ticket ID EXPOSUREAPP-3428. It will now be picked up by a developer and be fixed.

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment]
According to the development team, this is not something that will be changed.

----
Corona-Warn-App Open Source Team
