### ISSUE TITLE
Stop showing conflicting logging status during startup

### ISSUE THREAD

**Issue by christianMurschall** [corona-warn-app/cwa-app-ios#1400]
## Avoid duplicates
- [x] This issue has not already been raised before (could not find any: if already raised I will gladly remove this issue.)
- [x] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation

During startup the app (version 1.5.1) shows conflicting logging status information. ("Exposure Logging Active" vs "Exposure logging stopped", please see attached image)

<img src="https://user-images.githubusercontent.com/13819457/96994247-ba1ae080-152c-11eb-8f9c-729a3b506156.png" width=50% height=50%>

After the risk is calculated it turns green and the "Exposure logging stopped" message disappears. 
Kindly see recorded startup:
![image1](https://user-images.githubusercontent.com/13819457/96994306-d28afb00-152c-11eb-9b09-c7290b075b57.gif)

## Suggested Enhancement

I would suggest to show a loading screen before the app is displaying the logging status and risk level.

## Expected Benefits

The startup is always a source of wondering for me. It confuses me because it makes me think the app isn't working or configured. 
Indicating that something in the background is going on would definitely help me

**Comment by sin-azucar** [comment]
I have the same problem, it seems to appear only when the last risk calculation is more than 24 hours old.

According to this PR: #1048 actually a different card should be shown ("Risikoermittlung nicht moeglich"). 

(BTW, a little funny to see how something simple as that can be overengineered, but maybe that's just me. 😈 )

As we all know, the background job does not run reliably exactly every 24h, so "Risikoermittlung nicht moeglich" might also be suboptimal from a UX point of view. In any case, "Risikoermittlung gestoppt" is plain wrong and is a bug IMHO. 🐞

**Comment by Ein-Tim** [comment]
I can also confirm this behaviour @christianMurschall 

Only this Screen should be shown: 

![Screenshot 2020-10-23 154956](https://user-images.githubusercontent.com/67682506/97011799-6c5fa180-1547-11eb-9095-b9705968133c.jpg)

I remember an Issue which did also requested to improve this but now I can't find it anymore...

**Comment by christianMurschall** [comment]
Okay, I will close this one if favor of #770 .
But please have something done about that. The people in my environment do not appreciate this little game the app plays during startup:
`The potential lifesaving app tells my it's not working anymore - couple of seconds later: just a joke everything is in order :)`

**Comment by Ein-Tim** [comment]
@christianMurschall @sin-azucar Is this behavior still the same with 1.7.1?

**Comment by christianMurschall** [comment]
No it is fixed. 
It was fixed with 1.6.0, but unfortunately with 1.6.1 the old behavior was reintroduced. 
1.7.1 fixed it again.
