### ISSUE TITLE
contact count and matching keys doesn't match, 5 contacts

### ISSUE THREAD

**Issue by patrick-werner** [corona-warn-app/cwa-app-ios#1403]
The CWA shows  a red status and 5 contacts -> high risk.  
The logs are showing matchcount: 1. This means i had 5 contacts with a single person on one day? I'm asking because on the day in question i didn't had contact with anyone i don't know (also know their green app status). So i'm assuming receiving beacon signals from one of my neighbours through the wall/ceiling. 

Attached Screenshot and [Log](https://pastebin.com/w4c00vUa) from the CWA App (iOS 14.1 und CWA 1.5.1).

![image](https://user-images.githubusercontent.com/7199495/97088483-62b26880-1631-11eb-91b9-eb0804ee713f.png)

**Comment by daimpi** [comment]
@patrick-werner thanks for posting this… Just to mirror [some information](https://covidapps.slack.com/archives/C0194ML0MLN/p1603557900267200) from over at the [community Slack](https://github.com/corona-warn-app/cwa-documentation/issues/379): 

There is only **one** check which shows **one** match in the log entries for today:
```
 {
          "Hash" : "4CF0C497455611780A6E99FE12B16AC70DD135BB6D2769AFB0FB10A56F425722",
          "MatchCount" : 1,
          "KeyCount" : 14309,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-10-24 17:13:04 +0200"
        }
```
This usually would mean 1 encounter/exposure in CWA, but not in this case for some reason 😕.

Here are all the log entries for today in a table:

<details>
<summary>Details</summary>

Timestamp | Hash | MatchCount | KeyCount | Timestamp.1
-- | -- | -- | -- | --
24.10.2020   17:12 | 064B723E5EDD2EB8CD4C36FAA67FE839A486451748A5521B447606795867A061 | 0 | 18645 | 24.10.2020 17:13
24.10.2020   17:12 | D6C9ADEF176488BB7BCFA9F3A01EB5A9F692817441B777A630A1F74131A03CDF | 0 | 16122 | 24.10.2020 17:13
24.10.2020   17:12 | 4CF0C497455611780A6E99FE12B16AC70DD135BB6D2769AFB0FB10A56F425722 | 1 | 14309 | 24.10.2020 17:13
24.10.2020   17:12 | D63C8A25912DA34CD9A266967B854BB98BC09290BFE12B804C1FD796AE64BBD3 | 0 | 10876 | 24.10.2020 17:13
24.10.2020   17:12 | F049E50F243C7B991867B229668A44CBCA6E63846EBECA0A2B8E3C0BA8B7ACAC | 0 | 6386 | 24.10.2020 17:13
24.10.2020   17:12 | 3908E8EF3DE421C31CD585B8CBAFCEA7D54C21BF94E5E690A477AEE217E8B95A | 0 | 4814 | 24.10.2020 17:13
24.10.2020   17:12 | F9073A1268C72E6C93884F761E27066E9455BCFC0EFDB5068EA8C0BAAF1E098E | 0 | 16674 | 24.10.2020 17:12
24.10.2020   17:12 | 41444FD9FFAEFDD39A78B11E59DD58EF2146D5F65D39E7607C0E1997712B737F | 0 | 43934 | 24.10.2020 17:12
24.10.2020   17:12 | 1A7FA72A1A077EBD7EC11F0F8B3BB482A22865B133E9B45D66EA7AF11D5AAC53 | 0 | 41646 | 24.10.2020 17:12
24.10.2020   17:12 | 8F2EA05416F4175417980FFEC401506135A9591AC6A6F715CB94BF6A92723AA4 | 0 | 34105 | 24.10.2020 17:12
24.10.2020   17:12 | DB52431B890F3BC23B5C1BF902CC6EB2EDE0ABD827ABD58C207CA20E525B1008 | 0 | 28218 | 24.10.2020 17:12
24.10.2020   17:12 | 35FC7AAA7F90C04599FE355EA2AFEDC18A93F74E2AFB8E152C138EF0704E171C | 0 | 18134 | 24.10.2020 17:12
24.10.2020   17:12 | 9CCB79003AEC7BAAAA5F2733453AF4DAE414919FECF388344F8C4F7F21C47581 | 0 | 14649 | 24.10.2020 17:12
24.10.2020   17:12 | 970614A4D5AED5E567649FC508C6013847B446E03881A69647986950B497F227 | 0 | 23657 | 24.10.2020 17:12
24.10.2020   14:58 |   |   |   |  

</details>
There seemingly was an attempt to perform checks at 14:58 (but the entry is empty, so seemingly it didn't work) and then the actual checks were performed at 17:12 which is also the timestamp which shows up in CWA… but even there, only one match in one of the packages is found 😕.

**Comment by daimpi** [comment]
One question @Ein-Tim @ndegendogo: you also have encounters/exposures under iOS 14.1 and CWA 1.5.1, right? Is your EN log showing the same number of matches as your CWA?

**Comment by ndegendogo** [comment]
@daimpi yes, always. And I am verifying this daily.
I could not check during 5 weeks with iOS 13.7 because of a bug (#1106), but before and afterwards I did never see a deviation.

**Comment by ndegendogo** [comment]
@patrick-werner your ENF log file shows a match since 3 days.
Did you check cwa the days before? Are you aware if this strange mismatch was there from the beginning (all these three days)?
If you checked cwa: was it always red, or was it green (green with encounters) before?

**Comment by ndegendogo** [comment]
One crazy (?) idea on this: could it be that Apple fixed their bug (#1106) only partially in 14.1, and still suppress some of the encounters in their ENF log file??

**Comment by ndegendogo** [comment]
@patrick-werner which iOS version **exactly** do you have? Is it the "official" version, or some preliminary / special version for developers?

I noticed that the "build" number in the second line of your ENF log differs from mine.
I had always taken this number as indication of iOS version.

My number is (with iOS 14.1)
 "Build" : "18A8395",

Your ENF log shows:
  "Build" : "18A393",

@Ein-Tim could you please check your number?

**Comment by Ein-Tim** [comment]
> @daimpi yes, always. And I am verifying this daily.
I could not check during 5 weeks with iOS 13.7 because of a bug (#1106), but before and afterwards I did never see a deviation.

Can verify this, always had same amount of "matched Keys" any Encounters in CWA @daimpi

**Comment by Ein-Tim** [comment]
> @Ein-Tim could you please check your number?

Yes, my Build number is 18A8396 (like the Umber from you)

>Your ENF log shows:
"Build" : "18A393",

This is the Build Number from **iOS 14.0.1** the version which fixed this is **iOS 14.1** so I think he had 1 Red Encounter, this one got logged but the other 4 low Risk Encounters did because of #1106 not get logged...
@patrick-werner Please update to **iOS 14.1**

**Comment by patrick-werner** [comment]
oh wow. I was 100% sure beeing in iOS 14.1, which i wasn't. Thanks for the explanation, sorry for not being aware of my device s/w version.

Thanks @Ein-Tim & @daimpi  !!!

**Comment by daimpi** [comment]
@patrick-werner no worries and thanks to @ndegendogo and @Ein-Tim for solving this riddle ❤️. 

This was really very curious, as seemingly Apple went all over the place with what they showed in their log… I was under the impression that #1106 meant full suppression of all the matches, but seemingly that was only true for some versions. E.g. we had someone with red exposures on "iOS 14 public beta 8" (`"Build" : "18A5373a"`) reporting [here](https://github.com/corona-warn-app/cwa-app-ios/issues/1106#issuecomment-691471218) that they had 0 matches in their EN log with 14 (red) exposures shown in CWA. But this behavior was then seemingly changed again for iOS 14.0.1 and finally really fixed with 14.1. Fun times ^^.

**Comment by ndegendogo** [comment]
> is there some place where one can look up which build number corresponds to which iOS version?

I am not aware of any "official" list of this kind.
I have only an (incomplete) private list compiled of my own version history, plus a few from users ENF logs posted here.

**Comment by ndegendogo** [comment]
[Wikipedia](https://en.m.wikipedia.org/wiki/IOS_version_history) lists them (~semi-official)
