### ISSUE TITLE
Key count has changed from 1 to 0

### ISSUE THREAD

**Issue by sebastiancomsa** [corona-warn-app/cwa-app-ios#1404]
I think there must be something wrong here. Yesterday the app showed me I had 4 low risk encounters, after the latest update during the night it now shows I only had 1. I looked at the exposure checks (attached them here too) and it seems that yesterday one of the keys had a match count of 1 while today same key now has 0.

Is that a correct behavior? Anyone else has the same issue?

[exposure checks 20201025](https://pastebin.com/jW18YfTn)

**Comment by ndegendogo** [comment]
Yes. This happens, as soon as the match "expires", 14 days after the encounter.
Reason is that the RPI stored locally on your device have this lifetime. After this there will be no match.

For low-risk (green) encounters, unfortunately, you cannot see the date of encounter. In the ENF log you see only the matches with file granularity, corresponding to the day where a person uploaded her DEK keys.

**Comment by daimpi** [comment]
@sebastiancomsa I second what @ndegendogo said above ^
A similar question was discussed [here](https://github.com/corona-warn-app/cwa-app-android/issues/1302) in some more detail if you're interested 🙂.

**Comment by sebastiancomsa** [comment]
Thanks a lot guys, sorry if it was a duplicate post.

Happy it's not a bug and should function like this.

KR,

Seb

**Comment by daimpi** [comment]
@sebastiancomsa no worries 🙂.

If you're satisfied with the answers and don't have any other questions, feel free to close the issue 🙂.

**Comment by sebastiancomsa** [comment]
Closes: #1404
