### ISSUE TITLE
Meaning of daysSinceLastExposure in relation to increased risk score

### ISSUE THREAD

**Issue by TPei** [corona-warn-app/cwa-app-ios#1408]
## Avoid duplicates
* [x] Question is not already answered in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Question has not already been asked in another issue

## Your Question

* Source File: https://github.com/corona-warn-app/cwa-app-ios/blob/main/docs/architecture-overview.md
* Line(s): Section: Exposure Risk Level Calculation

I have a question about the meaning of the exposure timestamp in the risk summary. I read previously (https://github.com/corona-warn-app/cwa-app-ios/issues/1405) that the app basically turns all encounters into high risk exposures for the summary, if at least one is high-risk. From the documentation

> The calculated exposure risk level and the exposure risk summary (maximumRiskScore, daysSinceLastExposure and matchedKeyCount)

I gather that the timestamp also only generally concerns the last exposure not the specific identified high risk encounter. Is that correct? 

![Screenshot from 2020-10-26 10-27-59](https://user-images.githubusercontent.com/4004343/97155689-0442d280-1776-11eb-8382-33013e0bff94.png)

So in my case that wouldn't necessarily mean that my high risk encounter was 2 days ago but could lie anywhere within the last 2 weeks?

If that is so I am a bit confused by the text further down, which uses this information to display 

> You have an increased risk of infection because you were last exposed 2 days ago over a longer period of time and at close proximity [...]

which clearly implies that the high-risk exposure was two days ago. I think this could lull users into a false sense of security if they analyze said day and feel like there were no indoor, unmasked exposures on that day e.g.

**Comment by TPei** [comment]
Ah, seems to be a duplicate of https://github.com/corona-warn-app/cwa-documentation/issues/422

**Comment by Ein-Tim** [comment]
So if its a duplicate, could you close it @TPei?
