### ISSUE TITLE
Corona-Warn-App Implementation outside of Germany

### ISSUE THREAD

**Issue by CsepregiArtur** [corona-warn-app/cwa-app-ios#1434]
Hello

I want to ask if this program would be possible to implement also in different countries, with the needed modification.
and if it would be possible please send me a contact email to discuss the rest.
thank you

**Comment by thomasaugsten** [comment]
Yes:
Belgium: https://github.com/covid-be-app
Slovenia: https://github.com/si-covid-19/

**Comment by heinezen** [comment]
Hello @CsepregiArtur ,

The comment https://github.com/corona-warn-app/cwa-app-ios/issues/1434#issuecomment-719793532 from @thomasaugsten should answer your question. Therefore, I will close this issue now. If it did not answer your question please comment here with a follow-up and I will reopen the discussion.

Regards,
CH

----
Corona-Warn-App Open Source Team
