### ISSUE TITLE
Crashes after iCloud backup restore

### ISSUE THREAD

**Issue by pavll** [corona-warn-app/cwa-app-ios#1437]
## Avoid duplicates

* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is not already reported in another issue

## Describe the bug

I restored my iCloud backup on a new iPhone about 2 weeks ago. When I opened the CWA the normal setup dialog came up but no matter what I selected during the setup, in the end, the app always jumped back to the beginning of the setup screen/welcome dialog. No error message no, nothing.

## Expected behavior
Either use the old data of the app from the iCloud backup or, as after a new installation of the app, show the setup dialog and then show the default "Main Screen" of the app.

## Steps to reproduce the issue
Make a backup (maybe the problem occurs only with iCloud backups and not with local iTunes backups, i don't know) of your iPhone with CWA set up and then reset it. When you set up your iPhone again, select "Restore from iCloud backup" and wait. When all apps are restored open the CWA and voilà.

## Technical details

- iOS Version: 14.1
- Device: iPhone 8 -> iPhone SE 2

## Possible Fix

I'm not very familiar with iOS app development, but I suspect it's because certain app configs and temp files/user data were restored to "app memory" and that "confused" the app on startup.

**Comment by heinezen** [comment]
Hey @pavll 

Did you try to update the app like @Ein-Tim suggested and did this solve your problem?

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by pavll** [comment]
It's to Late to retry, Bit i think i did Not have the 1.5.0 Version on my old device. It's fixes nie
