### ISSUE TITLE
UI Tests are not compiling

### ISSUE THREAD

**Issue by chkpnt** [corona-warn-app/cwa-app-ios#1439]
## Avoid duplicates

* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is not already reported in another issue

## Describe the bug

UI Tests are not compiling

## Steps to reproduce the issue

1. Select schema ENAUITests
2. Build

## Technical details

- iOS Version:
- Device:

## Possible Fix

I'll shortly file a PR.

**Comment by marcussc** [comment]
Hey @chkpnt thanks for your work.
One thing though, with the next release (1.6) we reworked everything related to Unit/UI-Tests. You can see those changes on the branch: https://github.com/corona-warn-app/cwa-app-ios/tree/release/1.6.x On the upcoming release this should be fixed. Could you please check 1.6 for your Issue?

**Comment by ndegendogo** [comment]
@marcussc what is the planning for this 1.6? When will it be released?
In the meantime I am happy to know where to find the fix - thanks @chkpnt

**Comment by marcussc** [comment]
@ndegendogo https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v1.6.0-RC1 https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v1.6.0-RC3 
Regarding the timeline, all I can tell you is that this will be the next minor release.

**Comment by chkpnt** [comment]
Indeed, there is no compiler issue in the `release/1.6.x` branch. I've thought that `main` is the dev-branch. But okay, my fault, it seems to be the prod-branch. You might consider clarifing the branches mentioned in [CONTRIBUTING.md](https://github.com/corona-warn-app/cwa-app-ios/blob/b9b73a8ad4d8804cac67cf8afbdc7d1621222dcd/CONTRIBUTING.md).

Btw., I like the structure of your tests. The approach to use `__test__` folders for the unit tests within the production code is new for me to see in the iOS/Swift world, but it obviously makes sense if you have to use inferior tools like Xcode!

I'm orginated from the Java world, and lots of iOS projects I've seen so far were influenced by devs coming from there, too. In the Java world, where the structure is mainly stated by the Maven-src-folder-convention and the Java-package-structure, the distance between the production and test code doesn't hurt as you have IntelliJ or Eclipse (with [MoreUnit](https://moreunit.github.io/MoreUnit-Eclipse/)) which makes it easy to navigate to the tests and supports the dev during refactoring. But as Xcode and the iOS-tech-stack-tooling in general is (perceived) decades behind the Java-tech-stack, keeping that distance just hurts without any advantage. So using the `__test__`-folder approach seems reasonable, thanks for this eye-opener 👍.
