### ISSUE TITLE
Low risk contact seems like a high risk contact

### ISSUE THREAD

**Issue by Reggirella** [corona-warn-app/cwa-app-ios#1441]
Issue: If your app is warning you about a high risk contact it shows how many days it dates back. This works fine. The problem is: If you have a low risk contact during the time that your app is red it changes the number of days and the communication makes it seem like you had another high risk contact. 

Example: your app is red and tells you the last high risk contact is 6 days ago. You go to the get tested where you probably have a good chance to have a low risk contact with a corona positive person. Let's assume that you actually do have a low risk contact. As soon as this person gets the test result another risk contact shows in the app and the number of days reduces by 6 days. In the communication it makes you believe that you had another high-risk contact. Which leaves you confused and afraid that you have to get tested once again. If you wait and Don't do anything about it your CWA is getting green again 14 days after the real high risk contact. (How you find out that the second contact actually was not high risk)

Expected behavior: if you have a low risk contact during the time you're app is red it should not be given the impression that it was a high risk contact.

Solution: also in the state of a red CWA there need to be distinction of low and high risk contacts.

Thank you for looking in to this!

Cheers Reggirella

## Avoid duplicates

* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is not already reported in another issue

## Technical details

- iOS Version:
- Device:

**Comment by Ein-Tim** [comment]
Duplicate of https://github.com/corona-warn-app/cwa-documentation/issues/422

**Comment by Reggirella** [comment]
Yes it is exactly this issue. Sorry have not found it when I was searching.

**Comment by dsarkar** [comment]
Dear @Reggirella,

Thank you very much for your contribution.
As @Ein-Tim suggests, your suggestion seems to be a duplicate of https://github.com/corona-warn-app/cwa-documentation/issues/422.


There are actually several issues open on the question how low risk encounters should be notified:

- similar if not the same issue https://github.com/corona-warn-app/cwa-app-android/issues/1184
- Differentiation between low and high risk matches https://github.com/corona-warn-app/cwa-wishlist/issues/233
- Show more details about risk encounters https://github.com/corona-warn-app/cwa-wishlist/issues/100
- See also https://github.com/corona-warn-app/cwa-wishlist/issues/100#issuecomment-690279530
- show days for low risk encounters https://github.com/corona-warn-app/cwa-wishlist/issues/178
- Different colour for low risk encounters https://github.com/corona-warn-app/cwa-wishlist/issues/132
- Low Risk Exposure display optional https://github.com/corona-warn-app/cwa-wishlist/issues/181
- Display of "Tage seit letzter Risiko-Begegnung" is irritating https://github.com/corona-warn-app/cwa-documentation/issues/433

Best wishes,
DS

Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
Duplicate of https://github.com/corona-warn-app/cwa-documentation/issues/422
