### ISSUE TITLE
ENA.ExposureNotificationError-Fehler2

### ISSUE THREAD

**Issue by Aero91** [corona-warn-app/cwa-app-ios#1453]
![567E6E31-4B61-48CA-BE6C-0424EAD3F17E](https://user-images.githubusercontent.com/17228305/98026102-ebd45700-1e0a-11eb-8870-e895654ff563.png)

Seit dem Update auf iOS 14 kann ich die Risiko-Ermittlung nicht mehr aktivieren. Das Problem besteht aktuell unter iOS 14.1 auf einem iPhone 8. Ich habe die App schon mehrfach neu installiert, das Gerät neugestartet...

**Comment by Ein-Tim** [comment]
Hallo @Aero91.
Könntest du mal das versuchen: https://www.coronawarn.app/de/faq/#no_risk_update_ios14

**Comment by Aero91** [comment]
> Hallo @Aero91.
> Könntest du mal das versuchen: https://www.coronawarn.app/de/faq/#no_risk_update_ios14 und Bescheid geben ob es wieder funktioniert?

Hallo @Ein-Tim , das habe ich natürlich auch schon ausprobiert. Kein Erfolg.

**Comment by Ein-Tim** [comment]
Okay @Aero91, ich denke du hattest die App schonmal über die App eigene Zurücksetzten Funktion zurückgesetzt, oder? 
Könntest du bitte außerdem sichergehen das du 
1. die neuste App Version benutzt
2. auf iOS 14.1 bist (und nicht auf einer Beta Version o.ä.) 

Screenshots des "Begegnungsmitteilungen" Bereichs in den Einstellungen wären außerdem sehr hilfreich. 
Danke 👍

**Comment by Aero91** [comment]
@Ein-Tim 
 Korrekt, die App habe ich auch zurückgesetzt.
Die App ist eben frisch in Version 1.5.3 aus dem Store installiert.
iOS 14.1 ist installiert, keine Beta.

Nachfolgend Screenshots der einzelnen Schritte in den Einstellungen. Im letzten Schritt werde ich da nur auf die App verwiesen. In der App tritt dann das beschriebene Problem auf.

![D3B0ADBF-DCE1-4F85-BA15-D40D6FA07476](https://user-images.githubusercontent.com/17228305/98029414-bd0caf80-1e0f-11eb-8149-2622ae778198.png)
![F062EB78-1395-4829-A250-CD370D452065](https://user-images.githubusercontent.com/17228305/98029429-c3029080-1e0f-11eb-96a5-8dde47e65d24.png)
![2279242E-E817-466D-B3E7-430F1AD502E9](https://user-images.githubusercontent.com/17228305/98029436-c4cc5400-1e0f-11eb-8d04-488381262bed.png)
![B33EDA41-6C10-489E-B4A0-86DA1B29BF6B](https://user-images.githubusercontent.com/17228305/98029444-c72eae00-1e0f-11eb-889c-264411875ec7.png)

**Comment by Ein-Tim** [comment]
Ahh, ich verstehe. Also hattest du noch gar nicht die Möglichkeit Begegnungsmitteilungen wieder zu aktivieren, oder?

**Comment by Aero91** [comment]
@Ein-Tim 
Richtig. In dem Systemeinstellungen kann ich nicht mehr machen, als auf den Screenshots zu sehen. In der App gibt es zwei Fälle.

a) Wenn ich auf die Schaltfläche „Risiko-Ermittlung gestoppt >“ oder auf den Button „Risiko-Ermittlung einschalten“ tippe, komme ich nur auf diese View, die mir sagt, ich solle in die Systemeinstellungen gehen.

![349E08BB-1553-4671-93A7-AAD1A9278158](https://user-images.githubusercontent.com/17228305/98030210-fabe0800-1e10-11eb-84eb-fe3ad101dece.png)

b) Wenn ich aber auf die Überschrift „Risiko-Ermittlung gestoppt >“ tippe, komme ich auf nachfolgende Ansicht, wo dann bei Klick auf den Button die Fehlermeldung kommt.

![256D12AB-9EEF-4E81-A210-9A5C6091F412](https://user-images.githubusercontent.com/17228305/98030439-48d30b80-1e11-11eb-8a89-257c4aebfc3b.png)

**Comment by Ein-Tim** [comment]
Okay verstehe... Danke erstmal für den Input bis jetzt!
@thomasaugsten Könnte hier mal einen genaueren Blick drauf werfen 👍

**Comment by dsarkar** [comment]
Dear @Aero91,

Thank you for your contribution. 
Is Bluetooth activated?

Have you tried the following: 

1. Click on "Geräte-Einstellungen öffnen" 

![](https://user-images.githubusercontent.com/17228305/98030210-fabe0800-1e10-11eb-84eb-fe3ad101dece.png)

2. Click then "Begegnungsmitteilungen"

<img width="385" alt="image" src="https://user-images.githubusercontent.com/1409741/98095153-7a3bed80-1e8a-11eb-9e40-c1d6a10816bd.png">

3. Activate "Begegnungsinformationen teilen"

<img width="372" alt="image" src="https://user-images.githubusercontent.com/1409741/98095676-28e02e00-1e8b-11eb-80bf-7d63121d1703.png">


Best wishes,
DS

Corona-Warn-App Open Source Team

**Comment by Aero91** [comment]
Hi @dsarkar,
yes, bluetooth is activated. I can‘t follow your instructions, because there is an empty view in step 3. No text, no controls.

![5C38A2DD-EF60-4745-9FA1-1BBA893EAB4D](https://user-images.githubusercontent.com/17228305/98103292-1a970f80-1e95-11eb-8aa3-dfce720c5fbb.png)

**Comment by Ein-Tim** [comment]
@Aero91 Try this: https://www.coronawarn.app/de/faq/#ios_black_screen

**Comment by neuhausw** [comment]
Ich beobachte auf einem iPhone 6S mit iOS 14.1 und der aktuellen Corona-Warn-App exakt das gleiche Verhalten.

**Comment by Ein-Tim** [comment]
@neuhausw Did you try this: https://www.coronawarn.app/de/faq/#ios_black_screen

**Comment by neuhausw** [comment]
Seems to solve the problem. Thanks!

**Comment by Aero91** [comment]
> @Aero91 Try this: https://www.coronawarn.app/de/faq/#ios_black_screen

Das hat das Problem tatsächlich behoben, Danke! Aber das ist natürlich ein sehr unschöner Ausweg, da man dann bei allen Apps die Berechtigungen neu setzen muss.

**Comment by Ein-Tim** [comment]
@Aero91 
Ja ist nicht optimal, da das Problem hier aber auf Apples Seite liegt können wir hier nichts mehr tun...
Könntest du den Issue schließen? 
Danke!
