### ISSUE TITLE
Tapping on settings cells always open the "Transnational Exposure Logging" information 

### ISSUE THREAD

**Issue by hansemannn** [corona-warn-app/cwa-app-ios#1458]
## Avoid duplicates

* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is not already reported in another issue

## Describe the bug

When tapping on settings cells, the app always opens the "Translational Exposure Logging" info view, which irritates user when they did not request that information. See the attached video for details! 

## Expected behaviour

The "Translational Exposure Logging" info view should only be shown when tapping on the "Translational Exposure Logging" cell.

## Steps to reproduce the issue

1. Go to settings
2. Click on any of the settings cells

Video of the issue: https://www.dropbox.com/s/orllcgddcfo51qb/CWA_iOS_Settings_Bug_Repro.MP4?dl=0

## Technical details

- iOS Version: 121
- Device: iOS Simulator / iPhone 11 Pro

## Possible Fix

Guard the cell item-type before opening the view. A PR is ready for this: https://github.com/corona-warn-app/cwa-app-ios/pull/1459

Thank you for allowing OSS contributions on this project!

---
Internal Tracking ID: EXPOSUREAPP-3616

**Comment by heinezen** [comment]
Hey @hansemannn ,

Thank you for the contribution to this project. The devs have included your fix in the upcoming 1.7 release.

I have also created an internal Jira ticket so that the devs can track your the issue.

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by hansemannn** [comment]
@heinezen I think this can be closed, since the PR is already merged. Thx!
