### ISSUE TITLE
Popping multiple navigation children (iOS 14+ feature) results in broken footer state

### ISSUE THREAD

**Issue by hansemannn** [corona-warn-app/cwa-app-ios#1463]
## Avoid duplicates

* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is not already reported in another issue

## Describe the bug

When using the iOS 14+ navigation flow feature of closing multiple child views at once using force touch on the "Back" button of the navigation bar, the footer view moves to a broken state and prevent further inputs until the view is manually closed and reopened. This is only an issue for the submission view controller and can be seen in this video:

https://www.dropbox.com/s/fpqcyulaj1uhoqp/CWA_iOS_Submission_Nav_Bug_Repro.mov?dl=0 

## Expected behaviour

The submission footer view should be activated again, once a child view controller is closed.

## Steps to reproduce the issue

1. Go to "Learn More and Help"
2. Click on the "Next" button
3. Select one of the child view controllers, e.g. "TAN" or "Request TAN"
4. Long-press on the "Back" button in the navigation bar, which brings you back to the info screen
5. Notice that the "Next" button is still grayed out 

## Technical details

- iOS Version: 12.1
- Device: Simulator + iPhone 11 Pro

## Possible Fix

Clean up the footer state by using the UIViewController life cycle delegate `didMoveToParentViewController`.

## Additional context

The issue is fixed in the following PR: https://github.com/corona-warn-app/cwa-app-ios/pull/1464

<img src="https://user-images.githubusercontent.com/10667698/98129604-9905a880-1eb9-11eb-8912-c154753194d5.png" width="400" />

---
Internal Tracking ID: EXPOSUREAPP-3617

**Comment by heinezen** [comment]
Hey @hansemannn ,

Thank you again for the contributions to this project. Looks like this fix will also make it into the 1.7 release.

I have created an internal Jira ticket so that the devs can track your the issue.

Regards,
CH

----
Corona-Warn-App Open Source Team
