### ISSUE TITLE
Codespell report for "cwa-app-ios" (on fossies.org)

### ISSUE THREAD

**Issue by jschleus** [corona-warn-app/cwa-app-ios#149]
The FOSS server [fossies.org](https://fossies.org) offers among others a feature "[Source code misspelling reports](https://fossies.org/features.html#codespell)".

Although smartphone apps are not included in the portfolio of that server, due to the expected importance of the CWA app I have set up as server admin a kind of continuous source code spelling error checks for all associated CWA sub-projects (repos). This is realized by cloning the GitHub default branch ("master" resp. in case of cwa-app-ios  "development") and using the tool "[codespell](https://github.com/codespell-project/codespell)". The according reports are generated in a special restricted "test" folder that isn't fully integrated into the Fossies standard services and should also not be accessible to search engines. The cwa-app-ios report can be found here:

&nbsp;&nbsp;https://fossies.org/linux/test/cwa-app-ios-development-snap.tar.gz/codespell.html

That version independent URL hopefully always redirects to the report for the latest "development" version identified by the short commit ID and a year-month-day string (YYMMDD) representing the according git pull date (mostly = commit date). The refresh rate is currently half-hourly.

Although after a first review some obviously wrong matches ("False Positives" = FPs) are already filtered out (especially unsupported German words) please inform me if you find more of them so that I can force a new improved check if applicable (e.g. "seperator" -> "separator" may be a FP).

Just for information there are also three supplemental pages showing some used "codespell" [configuration details](https://fossies.org/linux/test/cwa-app-ios-development-snap.tar.gz/codespell_conf.html), all obvious [False Positives](https://fossies.org/linux/test/cwa-app-ios-development-snap.tar.gz/codespell_fps.html) and an [error history](https://fossies.org/linux/test/cwa-app-ios-development-snap.tar.gz/codespell_hist.html) (log).

Ok, corrections of spelling errors and typos have a low priority. Additionally some of the few found errors are "only" in comments (so not directly visible or relevant for users) and that within output strings may not all handled by the development team itself (/corona-warn-app/cwa-app-android#72).

Maybe nevertheless these reports can make a (very) small contribution to the overall code quality.

---
Internal Tracking ID: [EXPOSUREAPP-9775](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9775)

**Comment by larsaugustin** [comment]
I could take this one. It's mostly just comments, except "seperator". Since that might be an edge case, should I leave it?

**Comment by KevinMuessig** [comment]
Hi @jschleus ,

thank you for letting us know. It would be a huge help if you could let us know about your proposal in a pull request. Highly appreciate your contribution.

Best,

-KM

**Comment by jschleus** [comment]
Although your wish is understandable I cannot fulfill it.  Quoting from the [page](https://fossies.org/features.html#codespell) mentioned above:

> A note: Fossies provides as an information only the source code spelling check reports with the special option to inspect the context of the probably misspelled words in a fast and comfortable way. However Fossies doesn't create for e.g. "diff"-like files usable by the "patch" command or even GitHub pull requests (PRs) since the risk is too high that something would be wrongly corrected (but here you may find some small codespell usage hints). Whether it's worth the effort to correct the misspelling errors manually is a decision of the respective project. 

The main reason is that I don't know what is really correct. E.g. variable names don't have to be spelled correctly, but there could still be an error. A good example may be the mentioned "seperator".

By the way, the above text (page) contains also a link to [some small "codespell" usage hints](https://fossies.org/codespell_usage_hints.html).

**Comment by melloskitten** [comment]
Hi!
We appreciate your effort and think this is definitely a valuable improvement to the code base.
However, due to our current time constraints and other, more high priority items, we have to put this issue on hold.
If the time allows, at some future moment we will be able to come back to this issue.
Thank you for your understanding.

**Comment by Ein-Tim** [comment]
FYI: I created #3627 which addresses most of the typos listed on the website.

**Comment by dsarkar** [comment]
@Ein-Tim Thanks for the PR.
