### ISSUE TITLE
Handling with several smartphones

### ISSUE THREAD

**Issue by Kljcjbjj** [corona-warn-app/cwa-app-ios#1496]
I am using 2 iPhones (private / business). 

The FAQ[1] says, that there is nothing special to do, they are acting like 2 separated phones („ Was passiert, wenn ich zwei Handys habe?“ „ Die Nutzung eines zweiten Endgeräts verändert die Wirkungsweise nicht.“).

Now I realized, that this seems to be wrong, because I am not able to handle the test result on both devices. Scanning the QR Code fails:

![86119D98-0B6E-470B-919F-A287BB0AC088](https://user-images.githubusercontent.com/67545046/98801044-863b2880-2411-11eb-8980-5d0fd3ed2383.jpeg)

What does that mean?

Now I am not able to WARN other people in business context with the app running on my business phone. 

What is the solution for it and what about the FAQ? There is a very important fact missing. 

Also when scanning the QR Code - using several devices but only be able to use one QR Code means: scan it on the device that seems to have more contacts.

Is it a failure by design or maybe something in the iOS-client?

[1] https://www.bmi.bund.de/SharedDocs/downloads/DE/veroeffentlichungen/2020/corona/corona-warn-app-faq.pdf?__blob=publicationFile&v=4

**Comment by dsarkar** [comment]
Dear @Kljcjbjj,

Thank you for your post. Have a look here: https://www.coronawarn.app/en/faq/#test_multiple_devices.


Best wishes,
DS

Corona-Warn-App Open Source Team

**Comment by Kljcjbjj** [comment]
Hey!

> Thank you for your post. Have a look here: https://www.coronawarn.app/en/faq/#test_multiple_devices.

Thank you. I was really focused on the FAQ I saw on the website of the BMI. Thanks!
