### ISSUE TITLE
No "Risiko-Ermittlung" after commit a positive test

### ISSUE THREAD

**Issue by Clauswgh** [corona-warn-app/cwa-app-ios#1498]
Hello,

yesterday a friend have told, that the CWA is "Game over" on his smartphone - he don't if he have won or loss ;-)
He have commit a positive test result over two weeks ago, so he got the "Thank you" screen:
![grafik](https://user-images.githubusercontent.com/67307731/98805118-6ad31c00-2417-11eb-87f3-5dfb56a34bca.png)

**But now he have no option th close this screen to see the normal screen with "Niedriges Risiko", ...:**
![grafik](https://user-images.githubusercontent.com/67307731/98805325-b2f23e80-2417-11eb-9ab8-d8249946fcf3.png)

I think the reinstallation of the app will reset the contact history of the last 14 days too - so reinstall is not the best workaround (so my understanding of the functionallty of CWA).

Is it a bug or is it an "amazing feature"?

br,
Claus

**Comment by Ein-Tim** [comment]
@Clauswgh 
Please see: https://www.coronawarn.app/en/faq/?search=Gesund#recovered

This is "a feature"

**Comment by jucktnich** [comment]
I think it Wohls be Vetter, of in this Screen would ne a Button 'Im recovered' sich does the Same Thunfisch as the reset button.

**Comment by Clauswgh** [comment]
@jucktnich I am on your side!

But why I have to reset the complete App? In this case the contacts history will be deleted too, right?
If you reset the App 4 day after you are recoverd, you loss 4 days of your contact history - not really good implemented/specified functionallity!

**Comment by jucktnich** [comment]
Please move this to the cwa-wishlist since it's a general problem.

**Comment by Clauswgh** [comment]
Ok, issue closed - I will create a issue in cwa-wishlist asap

**Comment by Ein-Tim** [comment]
> App? In this case the contacts history will be deleted too, right?

@Clauswgh No contacts will be lost if you reset the App, but the Screen will show "Unknown Risk" for the first 24h

**Comment by Clauswgh** [comment]
Hi @Ein-Tim,

how is tile of the „Reset app“ button in german? „Anwendung zurücksetzen“ with the subtitle „Löschen sie alle ihre Daten in der App“
So only a specialist know, that not the contact history will be deleted with this action!

br

**Comment by jucktnich** [comment]
@Clauswgh I'm totally on your site but please open an enhancement suggestion on the wishlist so we can discuss this topic there.

**Comment by Ein-Tim** [comment]
@Clauswgh 

As stated before, please see my comment here: https://github.com/corona-warn-app/cwa-app-ios/issues/1339#issuecomment-709259413 and the FAQ Entry here: https://www.coronawarn.app/en/faq/?search=Deinstallieren#delete_random_ids, which states:

> We recommend that before you re-install the app, you try clearing the app data first as this will not delete the random IDs [...]

**Comment by Ein-Tim** [comment]
@jucktnich 

Please read my comments...

[Here](https://github.com/corona-warn-app/cwa-app-ios/issues/1498#issuecomment-725450516) I already told you that there is an open Issue in the Wishlist which requests adding a ["Virus Free Again"](https://github.com/corona-warn-app/cwa-wishlist/issues/115) Festure. 

If you propose something different, go ahead and open a request, if this is the same I can tell you That your Issue will get marked as a duplicate and get closed. I don't say this because I don't want you to open a new request but to saving you a lot of (unnecessary) work.

**Comment by chkpnt** [comment]
In our household we had the same issue and called the technical hotline after the Thank-You-Tile was displayed for around 4 weeks (we had suspected the tile to hide automatically after x days). The hotline told us we have to uninstall/reinstall the app.
And now I learn that there is the option to reset the app, which should be preferred over reinstalling. 😞

-> you should point this out to the hotline

**Comment by Ein-Tim** [comment]
@chkpnt 
Honestly, I personal don't know any difference between deinstalling and resetting the App. You just have to make sure that you install the App directly again after you deinstalled it, to make sure iOS does not delete the recorded contacts. 

But yes, this should definitely be pointed out to them, if you wish you could open an Issue in the github.com/corona-warn-app/cwa-hotline Repo, but to be honest, the feedback given there mostly does not make it to the people who are talking to the callers. 
Have a nice evening

**Comment by chkpnt** [comment]
> But yes, this should definitely be pointed out to them, if you wish you could open an Issue in the github.com/corona-warn-app/cwa-hotline Repo

No, I won't do that. In such a (well funded) project I expect there is a community or ux manager gathering complaints from all kind of sources. Like this GH-issue.
