### ISSUE TITLE
Bug in v. 1.6.1 on iOS14.2: Takes a long time to resolve codes

### ISSUE THREAD

**Issue by melancholyaeon** [corona-warn-app/cwa-app-ios#1513]
App version 1.6.1
IOS 14.2 
IPhone XS

Upon opening app, it gets seems to stuck resolving the codes. This can go on for 10-12 minutes. Didn't used to take more than a 1 or 2 minutes. 

I don't leave the house more than once a week now. 

![1BE90B8B-01CD-4FDE-95E5-DBED6F310E4B](https://user-images.githubusercontent.com/66167854/99144346-453b5200-2665-11eb-972c-81af71aefce5.jpeg)

---
Internal Tracking ID: EXPOSUREAPP-3840

**Comment by ndegendogo** [comment]
@melancholyaeon do you remember / are you aware of any issues with your internet connection at that time?
And: do you remember the exact date when it happened? (Just to be sure that the reason is not related to Apple's certificate server unavailable last week ... )

**Comment by heinezen** [comment]
Hey @melancholyaeon ,

Thank you for the report. Your issue has been mirrored to our internal Jira (ticket ID: EXPOSUREAPP-3840) where it will now be investigated by the devs. We will notify you here on Github when a fix is ready.

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by melancholyaeon** [comment]
Ty CH!

Right now I have a new result of what I think may be same or similar error. 

When I get the failure screen, I see the blue Restart button, but it doesn't function. Nothing happens when I click. 

I go back to the FAQ & follow those directions for restarting Exposure Checking, but it doesn't help.

Restarting the app doesn't help, nor does completely restarting the phone.

Are your servers down or overloaded? 

All my other apps work fine & I'm streaming music with no issue no its not my net connection.

Please see attached. 
![7D6AFDD4-0C0F-4800-9615-686D19A4C9CD](https://user-images.githubusercontent.com/66167854/99698654-53d49f80-2a91-11eb-9f94-e1005f38b108.jpeg)

![7DB823B3-A835-4A78-A46E-5C6D3C132FCD](https://user-images.githubusercontent.com/66167854/99698712-62bb5200-2a91-11eb-961c-62a76c55c7a8.jpeg)


Ty for looking into this; I know you guys have a lot on your plate.

**Comment by Ein-Tim** [comment]
@melancholyaeon I can't reproduce this problem on my phones, could you please close the App completely (swipe it up) and try it via your Mobile Network? (If you have one)

**Comment by ndegendogo** [comment]
@melancholyaeon could you export your ENF log file and upload it here?
It would be interesting to have a look at the timestamps.

**Comment by Ein-Tim** [comment]
@melancholyaeon 
I have a new assumption. 
If your App showed [this](https://user-images.githubusercontent.com/67682506/99188772-01784380-275e-11eb-9c4f-278f08f468f1.PNG) screen before the long _resolving codes_ screen and you clicked on the Blue Button to try it again the App will try again. But if you click the button more than one time, for example 4 times, then the App will download all codes 4 times (and it will take longer). If your device is now slow (for some reason so ever) this can take some time. But to be realistic, that it takes 10 Minutes is very weird.
Please do what @ndegendogo suggested and share your EN-Log here.


<details>
<summary>How to export Exposure Notificaiton Logs under iOS 13.7 or newer</summary>

**German:**

`Einstellungen` ➡️ `Begegnungsmitteilungen` ➡️ `Status von Begegnungsaufzeichnungen` ➡️ `Begegnungsüberprüfungen` ➡️ `Überprüfungen exportieren`

**English:**

`Settings` ➡️ `Exposure Notifications` ➡️ `Exosure Logging Status` ➡️ `Exposure Checks` ➡️ `Export Exposure Checks`
</details>

**Comment by dsarkar** [comment]
Dear @melancholyaeon,

Can you confirm that you still experience the same problem with CWA version 1.7? Thank you all very much for your contributions. 

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
Dear @melancholyaeon,

Any updates?

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by melancholyaeon** [comment]
Hi!

Sorry for the delay .... I had to try out the new version for several days
at different times before I felt it correct to respond. That's only good
QA, right? ˙ ͜ʟ˙

iPhone XS, iOS 14.2, Corona Warn 1.7.1

I keep the app open in the background all the time.

When switching to it, now I see a gray box on the screen titled Data Being
Downloaded...
Within 1 or 2 seconds that title switches to Checking...
and within about 40 seconds, the green box that says Low Risk.

I haven't left the house since the release (#besonderehelden), but my DH
has gone to the Rewe.

He has the same platform & set up. And on his phone it takes less than a
minute to process now since updating to 17.1.

So I'm calling it fixed.

Ty for your quick response & hopefully this will inspire more people to use
the app again.

Best wishes during this crazy time!

**Comment by dsarkar** [comment]
@melancholyaeon, thanks for the feedback. Stay safe! Best regards, DS

---
Corona-Warn-App Open Source Team

**Comment by melancholyaeon** [comment]
Thanks for being willing to hear that the issue was real instead of just
blaming me, Apple, my ISP or whatever.

Since some German medical officials disparage the app & still want a
Chinese-style privacy-destroying app, I really hope you guys keep up with
your fixes & improvements to increase public acceptance. I wish you all the
best.

Have a great day.
