### ISSUE TITLE
App "forgets" about checks if opened without Internet connection

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#1514]
## Avoid duplicates

* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is not already reported in another issue (see related Issues at the the bottom)

## Describe the bug

The App "forgets" old checks (which are not yet 24h old) if you open it without a connection to the internet. 

## Expected behaviour

The App should not download new data more than once in 24h.

## Steps to reproduce the issue

1. Make sure the last check was min. 10 minutes ago performed
2. Switch off Internet 
3. Open the App, you will see [this](https://user-images.githubusercontent.com/67682506/99188660-697a5a00-275d-11eb-95b7-c7329dfde87b.PNG) screen
4. Close the App (don't leave it in the background, swipe it up)
5. Open the App agian with Internet Connection, a check will be performed 

## Technical details

- iOS Version: 14.2
- Device: iPhone XR 
- CWA Version: 1.6.1

## Additional Inforamtion

<details>
<summary>How it looks</summary>

<table>
<tr>
	<td> <img src="https://user-images.githubusercontent.com/67682506/99188772-01784380-275e-11eb-9c4f-278f08f468f1.PNG" width="200">
	<td> <img src="https://user-images.githubusercontent.com/67682506/99188863-7c415e80-275e-11eb-9e75-a3af64fa2981.PNG" width="200">
	<td> <img src="https://user-images.githubusercontent.com/67682506/99188891-9e3ae100-275e-11eb-8664-8cddf715596f.PNG" width="200">
	<td> <img src="https://user-images.githubusercontent.com/67682506/99189356-1e624600-2761-11eb-949f-2c64ea171541.PNG" width="200">
	<td> <img src="https://user-images.githubusercontent.com/67682506/99189413-57021f80-2761-11eb-9bed-6fc9bfeebda0.PNG" width="200">
	<td> <img src="https://user-images.githubusercontent.com/67682506/99189438-739e5780-2761-11eb-8958-718a9ae46c27.PNG" width="200">
<tr>
	<td> App without Internet Connection at 15:05, last check was done at 10:36
	<td> Open the App with Internet, Check is instantly done
	<td> Screenshot of the EN Log in Settings 
	<td> App without Internet Connection at 15:19, last check was done at 15:06
	<td> Open the App with Internet, Check is instantly done
	<td> Screenshot of the EN Log in Settings
</table>

</details>

EN-Log: 
[ExposureChecks-2020-11-15.txt](https://github.com/corona-warn-app/cwa-app-ios/files/5542648/ExposureChecks-2020-11-15.txt) (There are 3 checks at 16:09, this was also the time I tested this again, so this behaviour is surely also linked to this Issue...)

---

## Related Issues
- #1497 
- #1505

**Comment by thomasaugsten** [comment]
This behavior is in 1.6.1 intended because we cannot load the configuration of the app. After a successful load of the configuration we do the exposure check again to ensure the result based on the latest config. But we will improve this in the future.

**Comment by ndegendogo** [comment]
> Expected behaviour
The App should not download new data more than once in 24h.

@Ein-Tim actually, we are requesting more frequent checks since long - of course as long as they don't have negative side-effects

**Comment by Ein-Tim** [comment]
@thomasaugsten 
> But we will improve this in the future.

Do you refer to this PR: #1506? 
One more question, when will we see more frequent checks? With 1.7.0 or 1.8.0? 

@ndegendogo 
> actually, we are requesting more frequent checks since long - of course as long as this does not have negative side-effects

That's true, but, correct me if I'm wrong, the server still only publishes new data once a day, or? So these checks always download the same that -> fill up more space on the users device...

**Comment by AnOtherMuenchner** [comment]
This "feature" can be used to shift the time point of comparison the an earlier point of time.

Normally, the app updates after at least 24 hours. Means: today at 12:00pm, tomorrow: 12:03pm, next day: 12:10pm and so an.

But when I open the app in the morning without connection, I get an error that the comparison has failed. When I switch on the connection, the app does the update. Also if it is before the update time of the day before.

**Comment by Ein-Tim** [comment]
@AnOtherMuenchner Yes I understand, I will close this Issue after my questions [here](https://github.com/corona-warn-app/cwa-app-ios/issues/1514#issuecomment-727606383) are answered 👍

**Comment by ndegendogo** [comment]
> That's true, but, correct me if I'm wrong, the server still only publishes new data once a day, 

as far as I know: yes. But if the client downloads more often, the strategy can change with a server update.
Of course the other order is possible as well: prepare 'hourly' endpoints at the server additionally to the 'daily' endpoints, then you can switch with a client update.

**Comment by ndegendogo** [comment]
@Ein-Tim by the way, your ENF log shows a corrupted list of files, with duplicate entries, similar to #1475 [this comment](https://github.com/corona-warn-app/cwa-app-ios/issues/1475#issuecomment-724365359)

**Comment by thomasaugsten** [comment]
@Ein-Tim Yes this PR will improve this. Every 4h exposure checks based on the hourly key files is planned for 1.7

**Comment by Ein-Tim** [comment]
Okay thanks, since now everything is clear I will close this Issue.
