### ISSUE TITLE
My app is currently updating everytime I open it, Is this intended or not?

### ISSUE THREAD

**Issue by cricketsamya** [corona-warn-app/cwa-app-ios#1517]
## Avoid duplicates

* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is not already reported in another issue

## Describe the bug

Before the app was updated every 24 hours, but now when ever I open app it downloads the keys to sync.
I am not sure if this is intended.

## Expected behaviour

App should only update itself every 24 hours

## Steps to reproduce the issue

Sync the app, close the app, wait for a minute to pass, open the app, it syncs again.

## Technical details

- iOS Version: 14.2
- Device: iPhone 11 Pro Max

**Comment by cricketsamya** [comment]
Now app is not updating everytime I open it.!

**Comment by Ein-Tim** [comment]
@cricketsamya 
This is intended with 1.6.1 (for more details see: https://github.com/corona-warn-app/cwa-app-ios/issues/1514#issuecomment-727602796)

**Comment by cricketsamya** [comment]
Cool.. Sorry for duplicate

**Comment by danielvonmitschke** [comment]
I still don't understand this behavior. Sometimes it does the update every time I open it and then suddenly it stops and does not update for 24h. (logs in #1522).

**Comment by cricketsamya** [comment]
Me neither but they say its intended! 😅

**Comment by Ein-Tim** [comment]
@danielvonmitschke The problem is that the App can't load the App config (please don't ask me why 😅) and to verify the result of the last check they do another one (@thomasaugsten stated this [here](https://github.com/corona-warn-app/cwa-app-ios/issues/1514#issuecomment-727602796):
> This behavior is in 1.6.1 intended because we cannot load the configuration of the app. After a successful load of the configuration we do the exposure check again to ensure the result based on the latest config. But we will improve this in the future.

**Comment by cricketsamya** [comment]
Hahah I eagerly wait everyday to complete 24 hours.. 😅 But from my experience it happens randomly not always. Would be amazing if you guys can support force sync.

**Comment by Ein-Tim** [comment]
@cricketsamya 

There are different approaches 
a) activated background refresh: 
The App will (try) to do a check every 24h in the background, if the App gets opened manually when 24h are over and no check has happened yet, a check will immediately happen.

b) deactivated background refresh: 
You will have to open the App every day when the last check was min. 24h ago. 

With 1.7.0, which will be released next week, the frequency of checks will be increased to 6 times a day -> all 4h.

**Comment by cricketsamya** [comment]
> @cricketsamya 
> 
> There are different approaches 
> a) activated background refresh: 
> The App will (try) to do a check every 24h in the background, if the App gets opened manually when 24h are over and no check has happened yet, a check will immediately happen.
> 
> b) deactivated background refresh: 
> You will have to open the App every day when the last check was min. 24h ago. 
> 
> With 1.7.0, which will be released next week, the frequency of checks will be increased to 6 times a day -> all 4h. 

Amazing.. frequency checks happens on the app side? Isnt that app config? 🙃

**Comment by Ein-Tim** [comment]
@cricketsamya 
Don't fully understand what you mean 😅🙂

**Comment by cricketsamya** [comment]
Why need a app release? Sever side config, can be downloaded in app right??

**Comment by Ein-Tim** [comment]
@cricketsamya 

The App's config can be found here: https://github.com/corona-warn-app/cwa-server/tree/master/services/distribution/src/main/resources/master-config. 
So how you can see there are only very few (but the most important) things saved in and no features, etc., at all.
That's why the App needs an update to do more frequent checke. (h/t @daimpi)

**Comment by cricketsamya** [comment]
![image](https://user-images.githubusercontent.com/13750637/99994837-de7f0c80-2db9-11eb-87f1-12906d9fc915.png)

Look how many times the app refreshes! 🤪

**Comment by Ein-Tim** [comment]
@cricketsamya 

The duplicate entrys are tracked here: https://github.com/corona-warn-app/cwa-app-ios/issues/1505
All this will be heavily improved (or rather completely solved).
The downloaded Data also don't take up any disk space since the files are cached based on the Hashes.

**Comment by dsarkar** [comment]
@cricketsamya and community, Thanks for contributing here. This issue is resolved in CWA version 1.7.1. 
Best wishes,
DS

---
Corona-Warn-App Open Source Team
