### ISSUE TITLE
Wrong number of encounters --> matchescount 0

### ISSUE THREAD

**Issue by montoyav** [corona-warn-app/cwa-app-ios#1525]
## Avoid duplicates
* [x ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x ] Bug is not already reported in another issue

## Describe the bug

Hey,

Yesterday I recognized "2 encounters with low risk".
Then I checked the json file and found all "matchescount" were 0
Today I checked again and it is the same. I used: https://felixlen.github.io/ena_log/

and this appears:

Bei Begegnungsüberprüfungen wurden keine Treffer mit positiv getester Person gefunden.

Has anyone the same issue?

## Expected behaviour

I would expect 0 encounters

Best regards
Vanessa

**Comment by vaubaehn** [comment]
Anyway, having a look to the iOS exposure log, there is something wrong:
For all the days there is not even one "matchCount", but there are 2 shown in CWA obviously.
For November 16, there have been 3 checks with 14 files: one in the morning hours, and two at noon (directly one after the other) - that's weird.
For November 13, there was no exposure check at all - did you close your phone on Friday the 13th? :ghost:

**Comment by montoyav** [comment]
@vaubaehn no, I did not close my phone Friday 13th :-) and I also realised about this point "November 16, there have been 3 checks with 14 files: one in the morning hours, and two at noon" --> that I found strange... so good you confirm that this is not the expected behavior.

**Comment by vaubaehn** [comment]
> so good you confirm that this is not the expected behavior.

No problem :slightly_smiling_face: However, I'll say good-bye at this point of my short joy ride to the iOS repo, as I don't have any clue of iOS so far.
But you will be in good hands here!
 :wave:

**Comment by montoyav** [comment]
@vaubaehn thanks for your help!

**Comment by dsarkar** [comment]
@montoyav, can you also upload a screen shot showing the 2 encounters in the CWA, please

**Comment by montoyav** [comment]
@dsarkar here you have. Thanks!
![screen](https://user-images.githubusercontent.com/42656444/99389931-17aa0f00-28d8-11eb-9ae3-bf0a3733faea.PNG)

**Comment by Ein-Tim** [comment]
This is a problem on Apple's side. Please update to iOS 14.1 or higher, there the problem is solved.

**Comment by montoyav** [comment]
@Ein-Tim OK, thanks! I will do so and report if the problem was solved or not

**Comment by Ein-Tim** [comment]
@montoyav Yes please, but you will have to wait until the next check is performed, the old encounters will not be shown in the log.

**Comment by montoyav** [comment]
OK! I will do as suggested

**Comment by montoyav** [comment]
I have updated my iphone to  iOS 14.2 and now I have in the CWA "no exposure up to now" in agreement with the matchCount = 0

Thanks for your help, was very useful

**Comment by Ein-Tim** [comment]
Okay good @montoyav.

If your question is answered, please close this Issue.

One more request:
The next time the App shows an Encounter, take a look at the Log to ensure that the information is consistent. (You only have to write here if it is **not** consistent) 
Thanks!

**Comment by montoyav** [comment]
@Ein-Tim Thanks a lot! I will do so
Have a nice evening
Vanessa
