### ISSUE TITLE
Replay attack starting from a testcenter for a lot of false positives?

### ISSUE THREAD

**Issue by JsBergbau** [corona-warn-app/cwa-app-ios#1543]
Moved to https://github.com/corona-warn-app/cwa-documentation/issues/463
Sorry, don't know how I landed in ios app.

**Comment by Ein-Tim** [comment]
@JsBergbau 
Just a small note:
Issues which affect both, iOS and Android, are normally posted here: https://github.com/corona-warn-app/cwa-documentation

Maybe @dsarkar?could transfer this Issue to the Documentation Repo
