### ISSUE TITLE
Question regarding #1550 ("Last at dd:mm:yy")

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#1551]
## Avoid duplicates
* [x] Question is not already answered in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Question has not already been asked in another issue (Related: https://github.com/corona-warn-app/cwa-documentation/issues/422)

## Your Question
The PR https://github.com/corona-warn-app/cwa-app-ios/pull/1550 introduces a new UI for V2 of the ENF. There the days since the last Exposure are not shown as a number anymore, but as a real Date. Thats nice! 
Is the date shown there only the date of **any** Encounter or the date of the last **High-Risk** Encounter?

**Comment by thomasaugsten** [comment]
High-Risk

**Comment by Ein-Tim** [comment]
So https://github.com/corona-warn-app/cwa-documentation/issues/422 is going to be solved by this?
