### ISSUE TITLE
The algorithm of the warning messages

### ISSUE THREAD

**Issue by ouboub** [corona-warn-app/cwa-app-ios#1552]
Hi

Just today I receive a warning message, which started like «encounters with low risk» etc. (It did not inform me about the data of the encounter, I presume because reasons concerning the data protection). Be it as it may, where can I find documentation about the algorithm

1.  low
2.  medium
3.  high

The reason I am asking concerns other European corona app, in particula the Spanish one. That informs you about the date but does not provide a sophisticated warning system as the Corona Warn app. That is why I would like to bring the subject to the attention of the Covid Radar app, but I would need details about the algorithm.

Thanks and regards

Uwe Brauer

**Comment by Ein-Tim** [comment]
@ouboub Maybe take a look at this FAQ Entry: https://www.coronawarn.app/de/faq/#encounter_but_green, which also links to https://github.com/corona-warn-app/cwa-documentation/blob/master/translations/cwa-risk-assessment.de.md. If this answeres your question please close this Issue

**Comment by ouboub** [comment]
@Ein-Tim 
Hi

Thanks, before closing it:

1.  I presume the date of the encounter is not added due to data protection?
2.  It seems that the most relevant document is this <https://github.com/corona-warn-app/cwa-documentation/blob/master/transmission_risk.pdf>

regards

**Comment by Ein-Tim** [comment]
@ouboub 

>I presume the date of the encounter is not added due to data protection? 

Yes, the RKI don't want to show the date of Low Risk Encounters unfortunately (open Wishlist Issue regarding this: https://github.com/corona-warn-app/cwa-wishlist/issues/178)

>It seems that the most relevant document is this https://github.com/corona-warn-app/cwa-documentation/blob/master/transmission_risk.pdf

Yeah, in this document you can find the very detailed information how the App is "deciding" wether it was a High or a Low Risk Encounter.

**Comment by heinezen** [comment]
Hello @ouboub ,

I assume your questions were answered by @Ein-Tim . I will close this issue now.

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by ouboub** [comment]
> Hello @ouboub ,
> 
> I assume your questions were answered by @Ein-Tim . I will close this issue now.
> 
> Regards,
> CH
> 
> Corona-Warn-App Open Source Team

right, he did and I forgot to close it sorry.
BTW, high risk encounters (which I have never received) have an indication of when they occurred?

**Comment by ndegendogo** [comment]
@ouboub yes, they do indicate it.
With current version 1.5 / 1.6 like "x days ago", in future versions they are planning to show a date to make it less ambiguous.

See [here](https://www.rki.de/SharedDocs/Bilder/InfAZ/neuartiges_Coronavirus/WarnApp/Statusanzeigen.jpg;jsessionid=5211B543F596ADC334E0087206E15E18.internet072?__blob=poster&v=2) for an example of the user screen with "red" risk warning.

**Comment by Ein-Tim** [comment]
@ouboub
Yes, at the moment the App shows the days since the encounter and with v1.8.0 the real date (dd.mm.yy) will be shown.
