### ISSUE TITLE
Why is CHANGELOG.md not updated anymore?

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#1553]
## Avoid duplicates
* [x] Question is not already answered in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Question has not already been asked in another issue

## Your Question
* Source File: https://github.com/corona-warn-app/cwa-app-ios/blob/release/1.8.x/CHANGELOG.md
* Question: The last update of this file was 3 months ago (v 1.3.0). Why is this file not updated anymore? 

---
Internal Tracking ID: EXPOSUREAPP-3899

**Comment by heinezen** [comment]
@Ein-Tim I assume the changelog link should point to https://github.com/corona-warn-app/cwa-app-ios/releases and CHANGELOG.md is no longer used. At least that is how it works in https://github.com/corona-warn-app/cwa-app-android

**Comment by Ein-Tim** [comment]
@heinezen 
Yes, should I open a PR which changes this or could you do this?

**Comment by heinezen** [comment]
@Ein-Tim I am currently not on a UNIX system that can handle the path names, so you would have to fix in PR. I've also brought it to the attention of the the developers by mirroring it to Jira, so someone shuld fix this eventually.

----
Corona-Warn-App Open Source Team
