### ISSUE TITLE
the contact diary (in which branch) or commit

### ISSUE THREAD

**Issue by ouboub** [corona-warn-app/cwa-app-ios#1587]
Hi
As I wrote yesterday  according to <https://www.spiegel.de/netzwelt/apps/corona-warn-app-update-bringt-neue-funktionen-a-24874a83-9bf7-46c8-a59d-ab3905a17832>
there will be a contact diary included in a future release.
I pulled the lastest git commit, I cannot find any branch nor a log entry referring to that functionality.
Is there any file explaining the feature which are or will be implemented

---
Related: https://github.com/corona-warn-app/cwa-app-ios/pull/1651

---
Internal Tracking ID: EXPOSUREAPP-4171 [iOS]
Internal Tracking ID: EXPOSUREAPP-4152 [Android]

**Comment by Ein-Tim** [comment]
@ouboub 
AFAIK the context diary is planed for version 1.10, for this version there is neither a branch nor a release candidate yet.

**Comment by ouboub** [comment]
> @ouboub
> AFAIK the contact diary is planed for version 1.10 (see [this](https://www.businessinsider.de/politik/deutschland/corona-warn-app-bekommt-updates-das-ist-der-geheime-plan-der-bundesregierung/) article), for this version there is neither a branch nor a release candidate yet.

and neither a document (template) with the planned features?

**Comment by Ein-Tim** [comment]
This is something I can't answer... @dsarkar, maybe you can help here

**Comment by Ein-Tim** [comment]
@ouboub 
There is now a branch for the [1.10.x](https://github.com/corona-warn-app/cwa-app-ios/tree/release/1.10.x) release. Until now I did not find a PR which would introduce the contact diary. I think the best would be if you regularly take a look at the [Changelog](https://github.com/corona-warn-app/cwa-app-ios/releases), if they release the first Release Candidate you can see it there (with a description what this version will improve/introduce/fix). 

Hope this helps, if your question is answered, please close this Issue 👍

**Comment by dsarkar** [comment]
@ouboub, @Ein-Tim, we will come back to you with some new information on this topic hopefully soon.  Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by ouboub** [comment]
@dsarkar  and @Ein-Tim 
thanks to both of you.

**Comment by Ein-Tim** [comment]
@ouboub  
Here you go: https://github.com/corona-warn-app/cwa-app-ios/pull/1651

**Comment by ouboub** [comment]
> @ouboub
> Here you go: #1651

thanks, that looks exactly what I was looking for

**Comment by Ein-Tim** [comment]
@ouboub 
Since this was just the question where you can find the diary (which was answered) I think this can be closed?

The main thread about an contact diary is: https://github.com/corona-warn-app/cwa-wishlist/issues/196

**Comment by Ein-Tim** [comment]
See also: #1670

**Comment by dsarkar** [comment]
Dear @Ein-Tim, @ouboub,


Thank you for your contributions. I agree with @Ein-Tim's suggestion to close this issue and to continue in the main thread:

> @ouboub
> Since this was just the question where you can find the diary (which was answered) I think this can be closed?
> 
> The main thread about a contact diary is: corona-warn-app/cwa-wishlist#196
> 

  
Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@ouboub Could you close this Issue please?

**Comment by ouboub** [comment]
>>> "ET" == Ein Tim <notifications@github.com> writes:

> @ouboub Could you close this Issue please?

I will.

**Comment by dsarkar** [comment]
@ouboub Thanks!
