### ISSUE TITLE
App has stopped updating 

### ISSUE THREAD

**Issue by CharlesAustralia** [corona-warn-app/cwa-app-ios#1590]
## Avoid duplicates

* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is not already reported in another issue

## Technical details

- iOS Version:
- Device:

**Comment by Ein-Tim** [comment]
Hey @CharlesAustralia 
With "has stopped updating" you mean that the App does not download new keys anymore? Could you share a screenshot of the Corona-Warn App here please?

**Comment by CharlesAustralia** [comment]
https://twitter.com/charliekreuz/status/1332478793475383296

But it has updated today. 

Charles McPhedran
Reporter and Producer
News and Current Affairs 
DW TV, Berlin

-----"Ein_Tim" <notifications@github.com> wrote: -----
To: "corona-warn-app/cwa-app-ios" <cwa-app-ios@noreply.github.com>

**Comment by Ein-Tim** [comment]
So everything is working as expected (again)? 

FYI: With the newest version 1.7.0 (and above) the App will update every 4h if your phone is connected to the Wi-Fi.

**Comment by CharlesAustralia** [comment]
Yeah it is. I have no idea why I didn't receive a key yesterday -- it simply would not update.

Thanks for that news; I will try to keep my mobile on Wifi as much as possible.

Charles McPhedran
Reporter and Producer
News and Current Affairs 
DW TV, Berlin

-----"Ein_Tim" <notifications@github.com> wrote: -----
To: "corona-warn-app/cwa-app-ios" <cwa-app-ios@noreply.github.com>

**Comment by Ein-Tim** [comment]
Okay... If you didn't revive one yesterday, this key should have been downloaded today 
Please close this Issue if you think it is solved 👍

**Comment by CharlesAustralia** [comment]
I will right now.

Charles McPhedran
Reporter and Producer
News and Current Affairs 
DW TV, Berlin

-----"Ein_Tim" <notifications@github.com> wrote: -----
To: "corona-warn-app/cwa-app-ios" <cwa-app-ios@noreply.github.com>

**Comment by CharlesAustralia** [comment]
Close #1590

Charles McPhedran
Reporter and Producer
News and Current Affairs 
DW TV, Berlin

-----"Ein_Tim" <notifications@github.com> wrote: -----
To: "corona-warn-app/cwa-app-ios" <cwa-app-ios@noreply.github.com>

**Comment by CharlesAustralia** [comment]
Resolved

Charles McPhedran
Reporter and Producer
News and Current Affairs 
DW TV, Berlin

-----"Ein_Tim" <notifications@github.com> wrote: -----
To: "corona-warn-app/cwa-app-ios" <cwa-app-ios@noreply.github.com>

**Comment by dsarkar** [comment]
Dear @CharlesAustralia , @Ein-Tim ,

Thanks for contributing and actually resolving! Stay safe!

Best wishes,
DS

---
Corona-Warn-App Open Source Team
