### ISSUE TITLE
Risc assesment stopped at pretty much every start of the app, resolves itself after brief waiting time

### ISSUE THREAD

**Issue by JMoVS** [corona-warn-app/cwa-app-ios#1592]
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is not already reported in another issue

## Describe the bug

I think I‘m encountering the same issue as this comment https://github.com/corona-warn-app/cwa-app-ios/issues/1153#issuecomment-706013278

But this behaviour is slightly different than the one explained in 1153. the end result is equally bad - my app doesn‘t refresh in the background reliably and only when I open it myself, it then tells me that refreshing did fail (send me a notification when it fails so I can open the app!), then that it‘s refreshing and it‘s fine again. My current hunch is that as I‘m a user who switches on Flightmode every night but the checking times are sometimes during the times where my flight mode is still on, it looks like CWA does not successfully use iOS background refresh to retrigger a check until someone reopens the app. 

## Expected behaviour

CWA gracefully recovering from a failed check during flight mode at night => checks working reliably

## Steps to reproduce the issue

I‘m not sure if it‘s the flight mode but with iOS 14 it has been like this eversince. Have your expected refresh time and set flight mode on before that time. Easiest to test overnight. 

## Technical details

- iOS Version: 14.2
- Device: iPhone SE 2020

## Possible Fix

- Send a notification when the check fails and asking users to open the app!
- use iOS background refresh to retrigger a check

**Comment by thomasaugsten** [comment]
Did you test the new v1.7.1 if this version updates in the background reliably on your phone?

**Comment by dsarkar** [comment]
Dear @JMoVS, 

Could you please give us some feedback regarding this issue after updating to CWA version 1.7.1? Many thanks.

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by JMoVS** [comment]
Unfortunetly, I had to get my phone replaced yesterday and it seems like for whatever reason those exposures are not part even of the password encrypted local backup, so I can only really say in a few days when I get my first info in the app

**Comment by dsarkar** [comment]
Hi @JMoVS, OK, we stand by for your feedback. Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by Mihahn** [comment]
I had the same problem and it seems to be resolved in 1.7.1.

**Comment by dsarkar** [comment]
Hi @Mihahn, @JMoVS, Thanks for all the feedback. We consider this issue as solved. We will close the ticket now. Please feel free to re-open, if necessary. DS

---
Corona-Warn-App Open Source Team
