### ISSUE TITLE
The low risk encounters and the dp3t protocol

### ISSUE THREAD

**Issue by ouboub** [corona-warn-app/cwa-app-ios#1593]
Hi 
I asked the authors of the Spanish radar covid app, to implement the feature of low risk encounters based on 
https://github.com/corona-warn-app/cwa-documentation/blob/master/transmission_risk.pdf

They answered me that 

> Sorry, that's not possible for the moment because we are using the dp3t protocol and this functionality is not supported currently.

is this true? Can anybody please comment on this.

thanks and regards

**Comment by Ein-Tim** [comment]
@ouboub 
I don't know but maybe it would be better if you ask this question here: https://github.com/DP-3T

**Comment by ouboub** [comment]
> @ouboub
> I don't know but maybe it would be better if you ask this question here: https://github.com/DP-3T/documents

Fair enough
