### ISSUE TITLE
The risk is not detemined and I live together with a positive person since days

### ISSUE THREAD

**Issue by delcorny** [corona-warn-app/cwa-app-ios#1596]
## Avoid duplicates

* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x ] Bug is not already reported in another issue

## Describe the bug

I have the corona warn app installed since months. On 24,11 my girlfriend gets tested positive (and we live in the same homeground) and she entered this in her app. . So I checked every day my risk factor but noghting changed also after 7 days living together. I did all the workarounds and also installed the app newly. I checked today again an no result ... everthing is green.

## Expected behaviour

I would expect to have a risk !

## Steps to reproduce the issue

![Corona_App](https://user-images.githubusercontent.com/75243914/100585322-aca40380-32ed-11eb-8d8e-10513cd0a563.png)

## Technical details

- iOS Version: 14.2
- Device: iPhone 11 Pro

**Comment by Ein-Tim** [comment]
Hey @delcorny 

This is very strange, would you mind to share your EN-Log here? The Log does not contain any private data, but the number of encounters you had. 

Thanks!

BTW: You wrote you reinstalled the App, how long was the App deinstalled? And why is the App again showing "Risiko-Ermittlung dauerhaft aktiv"?

<details>
<summary>How to export Exposure Notificaiton Logs under iOS 13.7 or newer</summary>

**German:**

`Einstellungen` ➡️ `Begegnungsmitteilungen` ➡️ `Status von Begegnungsaufzeichnungen` ➡️ `Begegnungsüberprüfungen` ➡️ `Überprüfungen exportieren`

**English:**

`Settings` ➡️ `Exposure Notifications` ➡️ `Exosure Logging Status` ➡️ `Exposure Checks` ➡️ `Export Exposure Checks`
</details>

**Comment by dsarkar** [comment]
Dear @delcorny,

Thanks for reporting. Please, as @Ein-Tim already proposed, provide the additional information requested.

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by delcorny** [comment]
It is working now ... no idea why
