### ISSUE TITLE
Was tun bei neuem Gerät?

### ISSUE THREAD

**Issue by renehamburg** [corona-warn-app/cwa-app-ios#1613]
Ich habe gerade ein neues iPhone 11 bekommen und habe mein Restore des iCloud- Backups vom alten 7er durchgeführt. 
Die CWA sagt mir, dass ich wieder von vorne beginne. Das ist schlecht.

Ich würde gerne meine ID auf ein neues Gerät "mitnehmen" können.

iOS 14.3 (public beta 2) auf iPhone 11

**Comment by Ein-Tim** [comment]
Hey @renehamburg, zuerst musst du wissen das es normal ist das du auf deinem neuen Gerät "von vorne" beginnen musst (siehe: https://www.coronawarn.app/de/faq/#backup).

Ich würde empfehlen das du dein neues iPhone 11 nun aktiv benutzt (nach draußen mitnehmen, etc.) und auf deinem alten iPhone noch 2 Wochen lang guckst ob es dir Begegnungen anzeigt.
Solltest du positiv getestet werden, müsstest du dir zu dem QR-Code noch eine TeleTAN von der Hotline geben lassen (siehe hier: https://www.coronawarn.app/de/faq/#test_multiple_devices).
Problematisch wird es wenn du keinen QR-Code hast, dann müsstest du 2 TeleTANs anfragen... 

Alternativ könntest du auch für 14 Tage beide iPhones immer aktiv benutzen (beide mit nach draußen nehmen, etc.).

**Comment by renehamburg** [comment]
Schon klar 😎
Und was machen die, die eben das alte Gerät nicht mehr haben? 
Die verlieren 14 Tage tracking. 
Das ist nicht optimal.

**Comment by Ein-Tim** [comment]
@renehamburg 
Ja ich weiß (und auch die Developer) wissen das das nicht optimal ist, da das allerdings von Apple bzw. Google so entschieden wurde, können die Devs hier nicht viel tun.
Trotzdem hier der Link zum offenen Issue im Wishlist Repo: https://github.com/corona-warn-app/cwa-wishlist/issues/8

Falls deine Frage geklärt ist, könntest du den Issue schließen 👍

Danke und einen schönen Abend!

**Comment by renehamburg** [comment]
Danke, Tim!
