### ISSUE TITLE
[Fix 1.8] Crash report: Unbalanced call to dispatch_group_leave()

### ISSUE THREAD

**Issue by ndegendogo** [corona-warn-app/cwa-app-ios#1649]
## Avoid duplicates

* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is not already reported in another issue

## Describe the bug

Today I saw an entry related to ENA / cwa in my crash logs.

Application Specific Information:
BUG IN CLIENT OF LIBDISPATCH: Unbalanced call to dispatch_group_leave()

Please give instructions how I can share this log file with you.

## Expected behaviour

Correct and balanced usage of the dispatch framework.

## Technical details

- cwa 1.7.1
- iOS Version: 14.2
- Device: iPhone 8

## Additional context

---
Possibly related: https://github.com/corona-warn-app/cwa-app-ios/issues/1631#issue-757691351

---
Internal Tracking ID: [EXPOSUREAPP-4289](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4289).

**Comment by dsarkar** [comment]
Good morning @ndegendogo! We will come back to you with instructions. Thanks, DS

---
Corona-Warn-App Open Source Team

**Comment by ndegendogo** [comment]
Another observation.
Crash log entry timestamp is
2020-12-03 18:14:35.6757 +0100
This was the first check after an exceptional pattern (14:10 checked only 5 hourly files).
See more details [here](https://github.com/corona-warn-app/cwa-app-ios/issues/1631#issue-757691351)

**Comment by dsarkar** [comment]
FYI: Internal Tracking ID: [EXPOSUREAPP-4289](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4289). Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
Fixed with 1.8
https://github.com/corona-warn-app/cwa-app-ios/pull/1575

Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by thomasaugsten** [comment]
v1.9.1 is released with a fixed please retest

**Comment by ndegendogo** [comment]
Thanks a lot! 👍
