### ISSUE TITLE
sometimes 10% battery capacity usage per hour 

### ISSUE THREAD

**Issue by mss1010** [corona-warn-app/cwa-app-ios#1664]
## Avoid duplicates

* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is not already reported in another issue

## Describe the bug

In some situations, the battery usage of the exposure framework is extremely high. In these screenshots you see the behavior. The curve is very steep here, while the device was mainly in standby and not used.
In some hours, the battery was drained by approx. 10% overall by exclusively the the exposure framework.

So, far this happened twice, but only on my iPhone 7. But I don´t know, which special conditions were related. Connectivity is always available either via WiFi or cellular LTE.

![IMG_0737](https://user-images.githubusercontent.com/36116339/101792300-d555a580-3b04-11eb-8faf-bf651fcabfdc.PNG)
![IMG_0738](https://user-images.githubusercontent.com/36116339/101792517-13eb6000-3b05-11eb-93b1-3c372a49391b.PNG)
![IMG_0739](https://user-images.githubusercontent.com/36116339/101792513-12ba3300-3b05-11eb-9001-82a809f77dbf.PNG)

## Technical details

- iOS Version: 14.2
- Device: iPhone 7
- app version: 1.7.1

## Additional context

---
Internal Tracking ID:   [EXPOSUREAPP-1882](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-1882)

**Comment by Ein-Tim** [comment]
See also: #671 and #912 

Just a small remark:
If you do not use your phone, than it makes sence that "Begegnungsmittelungen" is the only "App" (=100%) which is shown in these screens...

**Comment by jucktnich** [comment]
Just a small reminder:
The cwa can NOT influence the battery usage of "Begegnungsmtteilungen".

**Comment by mss1010** [comment]
> See also: #671 and #912
> 
> Just a small remark:
> If you do not use your phone, than it makes sence that "Begegnungsmittelungen" is the only "App" (=100%) which is shown in these screens...

That’s basically true, but if the battery consumption is 10% in one hour.
A „normal“ consumption chart has a much flatter curve like this:

![9240594B-119C-4738-A977-60B6816B072D](https://user-images.githubusercontent.com/36116339/101808523-ba8c2c80-3b16-11eb-9b23-03a9401aa85a.jpeg)

**Comment by mss1010** [comment]
> See also: #671 and #912
> 
> Just a small remark:
> If you do not use your phone, than it makes sence that "Begegnungsmittelungen" is the only "App" (=100%) which is shown in these screens...
> 
> Edit: I think this can, just like #912 back then, be closed as a duplicate of #671.
> Also the [reminder ](https://github.com/corona-warn-app/cwa-app-ios/issues/1664#issuecomment-742669575)from @jucktnich is a good one.
> 
> I don't think it will make any sense to further investigate this, but if you like to (@mss1010) you can share
> 
> * the battery healt
> * is this the original battery
> * is there any phone you know of near your phone which constantly shares RPIs?

Im aware of the other issues, but it‘s not a duplicate because the behavior is very different. Im not complaining about relative, but about absolute consumption of 10% battery capacity per hour.

I know that its not directly influenced by the app, but I was hoping that the developers can use their contacts to apple to address this.

**Comment by jucktnich** [comment]
I think apple knows this issue. You can eventually help them by open a ticket under feedbackassistent.apple.com and attache the iOS Systemlog.

**Comment by Ein-Tim** [comment]
@mss1010 

Yes you are right...
I just checkd an iPhone 6s which is mainly laying around and not used, the ENF does not drain the battery at all on this phone. So maybe it is worth to take a look at your case, even though it might be a edge case.

You can do what was proposed by @jucktnich, but it's also the task from the devs to talk with Apple about this. (Discussion about this back then: https://github.com/corona-warn-app/cwa-app-ios/issues/671#issuecomment-696099259)

Sorry for my not so nice reaction 😅 

Have a nice evening

**Comment by ndegendogo** [comment]
See also [here](https://github.com/corona-warn-app/cwa-app-android/issues/1814#) for related observation on Android.

**Comment by ndegendogo** [comment]
> The cwa can NOT influence the battery usage of "Begegnungsmtteilungen".

([via](https://github.com/corona-warn-app/cwa-app-ios/issues/1664#issuecomment-742669575) @jucktnich 

*Well - we don't know how this number is measured.* 

One part of ENF functionality is sending and receiving RPI - this is definitely out of control of cwa.
The other part is the calculation of matches.
We don't know if this counts towards cwa or towards ENF. [My own numbers](https://github.com/corona-warn-app/cwa-app-android/issues/1814#issuecomment-741006885) suggest it might be the latter, at least if it is triggered from background. But of course we don't know, **to be answered by Apple**.

**Comment by ndegendogo** [comment]
And if we assume that risk checks from background count towards cwa, then the change from 1 daily check to 5-6 checks per day since cwa 1.7 could maybe explain higher consumption now.

**Comment by mss1010** [comment]
> If you like to (@mss1010) you can share
> 
>     * the battery health
> 
>     * is this the original battery
> 
>     * is there any phone you know of near your phone which constantly shares RPIs?

- battery health is 95%
- it´s the original battery
- yes, but this is the case all the time. But only on some days the high consumption happens

**Comment by jucktnich** [comment]
@ndegendogo cwa also can't influence matching numbers...

**Comment by ndegendogo** [comment]
> I just checkd an iPhone 6s which is mainly laying around and not used, the ENF does not drain the battery at all on this phone. 

@Ein-Tim interesting.
Could you please give a few more details? (Just for comparison): cwa version? iOS version?
Is background check working on this device?
How regularly? Is it connected to WLAN? (So with current cwa 1.7.1 we would assume 5-6 checks per day - yes?)

**Comment by ndegendogo** [comment]
> cwa also can't influence matching numbers...

@jucktnich correct. But one check per day (pre-cwa 1.7) or 5-6 checks could make a difference

**Comment by jucktnich** [comment]
Yes, but what's the clue for the developers? Should they offer a setting to disable multiple checkings per day? That would be, i think, the only way to decrease battery usage.

**Comment by Ein-Tim** [comment]
For sure @ndegendogo 

- CWA Version: 1.7.1
- iOS Version: 14.3 Public Beta RC 2Build: 18C66)
- Background checks working reliable (4-5 checks per day)
- Connected to the internet via WiFi
- Not used at all

I definetly think that the Battery is drained faster because of the ENF. But I never expierienced spikes like @mss1010 reported...

**Comment by Ein-Tim** [comment]
@jucktnich 

The clue for the developers is that the user will not make a difference between ENF and CWA and if the phone gets empty to fast, because of "the App", the user will deinstall it. 
See also this discussion: https://github.com/corona-warn-app/cwa-app-ios/issues/671#issuecomment-696109490

**Comment by Ein-Tim** [comment]
@mss1010 (and everybody else), maybe you could monitior if something has changed with v 1.9.1 and v2 of the ENF.

**Comment by itinance** [comment]
I face a similiar issue. A new iPhone 11 Pro is discharging 100% over night, while my 2 years old iPhone 10 remains fully charged. The only difference is that the new iPhone 11 has CWA installed. I spot this issue since some days now.

All PNS are disabled, across all apps. Almost all background services are disabled as well (it is enabled for CWA, though). But overnight it gets discharged since some days.

iOS 14.2
CWA: 1.10.1

![File](https://user-images.githubusercontent.com/1758597/104304374-95029200-54cb-11eb-8c39-e633b43bbd3a.jpg)

**Comment by jucktnich** [comment]
What's the "Batteriezustand" on the iPhone 11?

**Comment by Ein-Tim** [comment]
@itinance 

Is there any other device with an installed Corona-Warn-App near the iPhone 11?

**Comment by itinance** [comment]
@jucktnich 

> What's the "Batteriezustand" on the iPhone 11?

Battery Health -> Maximum Capacity: 99%

@Ein-Tim 

no. I just see almost every night a constant drop in battery capacity from 100 to 0.

**Comment by jucktnich** [comment]
Did you tried to reboot the device?

**Comment by Ein-Tim** [comment]
Interesting. Is "Exposure Notification " responsible for 100% of it?

**Comment by itinance** [comment]
Exposure Notifications: 36%. 

While alle other services are single figures.

**Comment by Ein-Tim** [comment]
Okay thanks. 
Could you update to iOS 14.3 and report back after monitoring for some time?

**Comment by itinance** [comment]
@jucktnich i will reboot todays evening and see what is happening then during night (now at day time it makes no sense due to heavy usage including personal hotspot)

**Comment by itinance** [comment]
> Okay thanks.
> Could you update to iOS 14.3 and report back after monitoring for some time?

Alright!

**Comment by dsarkar** [comment]
Internal Tracking ID:   [EXPOSUREAPP-1882](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-1882)

**Comment by thomasaugsten** [comment]
@itinance is your iPhone 11 Pro still discharging 100% over night?

**Comment by itinance** [comment]
> @itinance is your iPhone 11 Pro still discharging 100% over night?

Unfortunately Exposure Logging has disabled during Wednesday Night for unknown reasons.  I just noticed it todays morning and re-enabled it.
However, iOS 14.3 is installed since 2 days and todays night I will check again and tell here the results tomorrow.

**Comment by Ein-Tim** [comment]
Any update @itinance or do you want to monitor a bit longer?

**Comment by itinance** [comment]
> Any update @itinance or do you want to monitor a bit longer?

Yes! No significant battery drop last night. 4% energy consumption over last 24 hours)

**Comment by Ein-Tim** [comment]
What about you @mss1010?

**Comment by mss1010** [comment]
I did not see the issue anymore. We could close the issue if you like

**Comment by Ein-Tim** [comment]
For sure. 👍
As the author of this Issue you can go ahead and close it.
