### ISSUE TITLE
Weird variations/spikes in match count on iPhone 12 Pro

### ISSUE THREAD

**Issue by holicodes** [corona-warn-app/cwa-app-ios#1672]
## Technical details

- Device name: iPhone 12 Pro 
- iOS Version: 14.2.1
- App Version: 1.7.1 (0)

## Describe the bug

First of all, thank y'all for contributing to this software – the code and the discussions here are a beautiful balance to the madness outside.

To my point: I see strange spikes in my green encounters and I feel like it could be related to switching from an iPhone 8 Plus to the new iPhone 12 Pro.

Today, I have 10 low-risk matches whereas my girlfriend only has 5 on her iPhone Xs. I don't use public transport, work from home and only go out for groceries, almost always together with her. We live in a big city in Germany.

I started taking notes on November 19, exactly 2 weeks after setting up the new iPhone, to have more than the 14-day view of the iOS logs. Earlier than Nov 19 (also on the old phone of course), I never exceeded 3 matches but I know that we had infection numbers rising a lot during that timeframe. Here's what my notes look like:

Date | Match count
------------ | -------------
Before | never more than 3 
Nov 19 | 5
Nov 20 | 8
Nov 21 | 11
Nov 22 | 3
Nov 23-25 | 2
Nov 26 | 1
Nov 27-30 | 0
Dec 1-2 | 0
Dec 3-7 | 1
Dec 8 | 1 at 16:01, 9 at 20:02 CET
Dec 9 | 9 at 08:05, 10 at 12:06 CET
Dec 10-11 | 10

During this time, my girlfriend never had more than half of my matches and she even used public transport a couple times whereas I didn't.

Do you think this could be in any kind related to the new device and its Bluetooth performance or is it likely to be pure coincidence that my phone simply cast more (later positive) IDs?

## Expected behaviour

With infections being at a fairly consistent level, I can't explain why my matches are not. Besides, it irritates me that I have so many more matches than 

## Additional context

As a control device, my work phone (iPhone Xs) shows zero matches so I can exclude any impact from the surroundings/neighbours of our flat. Exposure log is attached.

[ExposureChecks-2020-12-11.txt](https://github.com/corona-warn-app/cwa-app-ios/files/5678896/ExposureChecks-2020-12-11.txt)

**Comment by Ein-Tim** [comment]
See also #1513

**Comment by holicodes** [comment]
Thank you @Ein-Tim for the quick reply! And shame on me for not finding this one earlier, looks like a duplicate indeed.

**Comment by Ein-Tim** [comment]
@holicodes 
No problem. As the author of this Issue you can go ahead and close it 👍

I think it would be helpful to have your information in #1531.
So if you like to, you can follow up there. 

Have a nice weekend and stay safe!

**Comment by wolfgang35435** [comment]
Yes, after upgrading, my green count went from 3 to zero. Apparently there was a calibration problem with the new devices.
Have a nice and safe Christmas.
