### ISSUE TITLE
CWA for older iPhones - Support iOS12.5

### ISSUE THREAD

**Issue by roxola** [corona-warn-app/cwa-app-ios#1682]
Update the app for using it under iOS 12.5 which allows exposure notifications on older iPhones such as iPhone 6 and iPhone 5s. 

Apple dropped iOS 12.5 recently with the exposure notification. This renders older devices such as iPhone 6 and 5s compatible with Corona-Warn-App, would be great if those devices i.e. their owners would be able to download and use corona-warn-app.

Regards. 

---

Related issues:
---
PR https://github.com/corona-warn-app/cwa-website/pull/670
Blog post https://www.coronawarn.app/en/blog/2020-12-15-ios-12-5/
See the related feature branch: https://github.com/corona-warn-app/cwa-app-ios/commits/feature/iOS12.5-Support
Source: https://developer.apple.com/documentation/exposurenotification/supporting_exposure_notifications_in_ios_12_5
CWA 1.12 will bring compatibility with iOS 12.5: https://www.coronawarn.app/en/blog/2021-02-04-cwa-1-12-announcement/

---
Internal Tracking ID: [EXPOSUREAPP-4179](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4179)

**Comment by Ein-Tim** [comment]
Source: https://developer.apple.com/documentation/exposurenotification/supporting_exposure_notifications_in_ios_12_5

**Comment by dsarkar** [comment]
Dear @roxola, and community

Thank you for your contributions.

This issue is internally tracked: 
Internal Tracking ID: [EXPOSUREAPP-4179](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4179)

Any further developments will be notified here in this Github issue.
  
Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
This PR hints that we will see CWA on iOS 12.5 soon:

https://github.com/corona-warn-app/cwa-website/pull/670

**Comment by dsarkar** [comment]
See https://www.coronawarn.app/en/blog/2020-12-15-ios-12-5

**Comment by mss1010** [comment]
See the related feature branch: https://github.com/corona-warn-app/cwa-app-ios/commits/feature/iOS12.5-Support

**Comment by SoftwareRat** [comment]
Is there any ETA for iOS 12.5 support?

**Comment by yorickreum** [comment]
What are you still waiting for?

**Comment by Ein-Tim** [comment]
@yorickreum 
I don't think they are waiting for something, the devs are simply still working on it (see the branch: https://github.com/corona-warn-app/cwa-app-ios/commits/feature/iOS12.5-Support).

**Comment by mss1010** [comment]
I was about to say the same as @Ein-Tim. In the branch you can see that it’s very active.

**Comment by ndegendogo** [comment]
Yes. Backporting an application to an older version of iOS is real work.
Although Apple has made the Exposure Notification Framework available for iOS 12.5, several other APIs that are currently used in the implementation are not available, and must somehow be replaced.

**Comment by whiskey** [comment]
Backpoting is one (big) piece of the work. The other issue is testing that port. Apple never released and most likely will release an iOS 12.5 SDK so we had to rely on a few devices to test the backports.

**Comment by ndegendogo** [comment]
> Apple never released and most likely will release an iOS 12.5 SDK

Wow ... I was not aware of this! 😱

**Comment by Ein-Tim** [comment]
FYI: PR #1752

**Comment by ndegendogo** [comment]
One of several APIs they need to backport.
I don't think that all is finished till 1.11, especially the testing ...

**Comment by ndegendogo** [comment]
@dsarkar could you try to bring up the discussion again of extending beta testing to the community? 
As @whiskey mentioned [here](https://github.com/corona-warn-app/cwa-app-ios/issues/1682#issuecomment-753870063), testing will be (is already!) especially challenging for this version

**Comment by thomasaugsten** [comment]
The public beta is already addressed and will be decided soon

**Comment by Ein-Tim** [comment]
CWA 1.12 will bring compatibility with iOS 12.5:
https://www.coronawarn.app/en/blog/2021-02-04-cwa-1-12-announcement/

**Comment by Ein-Tim** [comment]
Version 1.12.1, which comes with support for iOS 12.5, has been released today: https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v1.12.1

Blog post: https://www.coronawarn.app/en/blog/2021-02-10-corona-warn-app-version-1-12/

**Comment by dsarkar** [comment]
Dear @roxola and community.

Thanks again for all the contributions. This issue has been addressed and solved. @roxola, please close this issue! many thanks. Best wishes, DS

---
Corona-Warn-App Open Source Team
