### ISSUE TITLE
iOS 12.5 support

### ISSUE THREAD

**Issue by MapeRiptide** [corona-warn-app/cwa-app-ios#1683]
iOS 12.5 now officially supports the contact tracing engine. Is it planned to support iOS 12.5 in a future version?
I think it would be great if a lot of older devices benefit from it.

**Comment by Ein-Tim** [comment]
@MapeRiptide 
See #1683. 

Please close this Issue.

**Comment by MapeRiptide** [comment]
> @MapeRiptide 
> 
> See #1683. 
> 
> 
> 
> Please close this Issue.
> 
> 
> 
> 

2 minutes too late. Issue closed.

**Comment by dsarkar** [comment]
Hi @MapeRiptide,

Thanks for contributing. As @Ein-Tim suggests, please contribute to this topic in the issue https://github.com/corona-warn-app/cwa-app-ios/issues/1682 opened slightly earlier.

Best wishes,
DS

---
Corona-Warn-App Open Source Team
