### ISSUE TITLE
CWA 1.9.1 does not show Risk Contact but iOS Exposure Framework does show matching keys / Lost encounters after the latest update

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#1703]
CWA 1.9.1 does not show Risk Contact but iOS Exposure Framework does show matching keys
Lost encounters after the latest update
---

This behavior has been raised several times recently and has caused some confusion (e.g. in these duplicates: #1705, #1706, #1713, #1723, #1755).  
However, this is not a bug. For an explanation, see the following references, please:

**Blog post:**

_German_:

https://www.coronawarn.app/de/blog/2020-12-17-risk-calculation-exposure-notification-framework-2-0/

_English_:

https://www.coronawarn.app/en/blog/2020-12-17-risk-calculation-exposure-notification-framework-2-0/

**FAQ-Entries:**

_German_:

https://www.coronawarn.app/de/faq/#encounter_count_19

https://www.coronawarn.app/de/faq/#encounter_19_calc

_English_:

https://www.coronawarn.app/en/faq/#encounter_count_19

https://www.coronawarn.app/en/faq/#encounter_19_calc

---
ORIGINAL POST 
---

## Avoid duplicates

* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: iPhone XR
- iOS Version: 14.3
- App Version: 1.9.1

## Describe the bug

With version 1.7.1 the App showed "Eine Risiko-Begegnung mit niedriegem Risiko". The EN-Log also showed "1 Übereinstimmender Schlüssel"
Here is the EN-Log before the update: 
[ExposureChecks-2020-12-16.txt](https://github.com/corona-warn-app/cwa-app-ios/files/5704062/ExposureChecks-2020-12-16.txt)

---

Now, I installed 1.9.1, the App did another check and now it shows this:

<img src="https://user-images.githubusercontent.com/67682506/102377826-6a551480-3fc5-11eb-811a-4c06292ef62f.PNG" width="300">

But the log shows this:

<img src="https://user-images.githubusercontent.com/67682506/102377886-7d67e480-3fc5-11eb-9b47-1511b1c40af7.PNG" width="300">

Here is the Log after the update: 
[ExposureChecks-2020-12-16.txt](https://github.com/corona-warn-app/cwa-app-ios/files/5704088/ExposureChecks-2020-12-16.txt)
Somehow (I assume because of the update to v2 of ENF) the Log does not show "MatchCount" anymore...

**What is correct? The App or the Log? Or is this just a change in v2 of the ENF that the Log can show a Matched Key but the App does not show an encounter?**

## Steps to reproduce the issue

1. Get a Risk Contact
2. Update to 1.9.1 (0)
3. See no Risk Contact

**Comment by wowbagger089** [comment]
Confirm same behaviour iPhone 12 Pro, ios 14, app 1.9.1(0) (Should be 4 low risk (was before update and 4 in the key details), is 0 on the UI)

**Comment by Delta1977** [comment]
Same here. Device name: iPhone 8 , iOS Version: 14.3 App Version: 1.9.1.  One risk is shown before update, after update 0 risk. in ENF is 1 shown.

**Comment by max-ae** [comment]
Same here, 4 encounters before update in app and settings log, 0 in app after update, 4 matches in the settings log still remaining. 
Device: iPhone 12 Pro Max, iOS 14.3, CWA v1.9.1

**Comment by Ein-Tim** [comment]
Could be that this has something to do with: 

>With the change to ENF 2.0, it is no longer a single encounter that is decisive for the risk assessment, but the sum of the risk minutes per day. Thus, even several short encounters can lead to an increased risk.

(Source: https://www.coronawarn.app/en/blog/2020-12-16-corona-warn-app-version-1-9/)

Would be nice to have a clarification about this.

**Comment by Ein-Tim** [comment]
[This](https://github.com/corona-warn-app/cwa-website/pull/685) closed PR in the Website Repo from @thomasaugsten seems to confirm that it is possible to have matches in the Log but no encounters in App.

>Unter dem Exposure Notification Framework in Version 2 werden vom Betriebssystem außerdem Begegnungen erfasst, die ein geringeres Risiko als „niedriges Risiko“ (grün) aufweisen. Diese sind aus virologischer Sicht aber nicht relevant und werden von der Corona-Warn-App herausgefiltert.

**Comment by thomasaugsten** [comment]
With ENF v2 there are matched keys on OS level with a low risk. This matched are from RKI model not relevant and filtered out by the App. This means since ENF v2 there could be a mismatch between the OS matched Keys and the CWA risk encounters.

We will create soon an FAQ entry with a detailed explanation.

**Comment by Ein-Tim** [comment]
Okay thanks @thomasaugsten 

One last question:
Is it normal that there are now "MatchedKeys" in the Log with v2 of ENF?

**Comment by thomasaugsten** [comment]
I can confirm at the moment there is the matched key count visible in the UI, but not in the log. We will address this.

**Comment by thomasaugsten** [comment]
In the updated documentation you can see TRL 1 and 2 are filtered out on App level

https://github.com/corona-warn-app/cwa-documentation/blob/master/images/risk_calculation/risk_calculation_enf_v2_overview.pdf

**Comment by Ein-Tim** [comment]
This was also reported in #1706 and #1705

**Comment by Ein-Tim** [comment]
@thomasaugsten 

> I can confirm at the moment there is the matched key count visible in the UI, but not in the log. We will address this.

Yes, but but only for the whole check and not for every individual hash...

**Comment by Ein-Tim** [comment]
I will close this PR as soon as there is a FAQ Entry explaining this.

**Comment by Ein-Tim** [comment]
Blog post reg. this: https://www.coronawarn.app/de/blog/2020-12-17-risk-calculation-exposure-notification-framework-2-0/

**Comment by Ein-Tim** [comment]
I will close this Issue now, still it would be good to get figured out why there is no Match Keys neither in the EN-Log nor in UI for the individual hashes.

**Comment by dsarkar** [comment]
@Ein-Tim, ok! let's keep that one open as a reference. I think we will get many more questions regarding this behavior. I suggest writing in the first post the links to the FAQ and a short statement that this is not a bug. DS

**Comment by Ein-Tim** [comment]
@dsarkar I think we can close this now with v1.10.1 released 👍

**Comment by dsarkar** [comment]
@Ein-Tim, sure, go ahead! Thanks! DS

**Comment by dsarkar** [comment]
@Ein-Tim, re-opened for visibility and avoiding duplicates.

**Comment by fsbaraglia** [comment]
Hi @dsarkar Hi @Ein-Tim ,

Same here. Device name: iPhone 11 , iOS Version: 14.3 **App Version: 1.10.1**. 
0 exposure in the App, but IOS "Begegnungsmitteilungen" shows "Übereinstimmend Schlüssel".

I downloaded the ExposureChecks.json file, this is what I see (it is just an extract of the first :
.... 
{
          "Hash" : "xxxxxxxxx",
          "KeyCount" : 26879,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2021-01-05 20:44:29 +0100"
        }
...
I installed , activated the Italian version "Immuni" and selected that I am leaving in Germany, 
I downloaded again the Exposure.json and I see this:
{
          "Hash" : "xxxxx",
          "MatchCount" : 1,
          "KeyCount" : 15991,
          "AppBundleIdentifier" : "it.ministerodellasalute.immuni",
          "Timestamp" : "2021-01-05 23:17:20 +0100"
        },

I think that what @Ein-Tim sees in "Begegnungsmitteilungen" -> "Übereinstimmend Schlüssel", is coming from another corona tracking App and not from the matching from the Coronawarnapp.

Maybe it is a fake positive matching ? What do you think ?

I can provide the full Exposure files.

**Comment by Ein-Tim** [comment]
Hey @fsbaraglia 

First of all I don't have any other tracing App installed on my phone and as you can see all entries in the EN-Log are coming from Corona-Warn-App. The drop of encounters after the update to 1.9.1 is ok, please see my comment [here](https://github.com/corona-warn-app/cwa-app-ios/issues/1703#issuecomment-747494860) for more information. 


You are using two Apps, Immuni & Corona-Warn App. 
I think Immuni is selected as "active region" in your phones settings, right? 

It seems like Immuni is still using v1 of ENF (Match Count in Log) while CWA is using v2 of it (no Match Count in the Log). 


Does Immuni show you an encounter while CWA doesn't?

**Comment by fsbaraglia** [comment]
Hey @Ein-Tim,

nice, thank you for the quick answer.
I placed as active region Immuni -> yes
and inside the app you can select that you are in another country that it is not Italy at the moment, here I selected Germany. 

For the MatchCount, I commented you with screenshots in the other issue https://github.com/corona-warn-app/cwa-app-ios/issues/1731

**Comment by Ein-Tim** [comment]
Okay thanks @fsbaraglia.
So both Apps are reporting one Encounter at the moment, right?

**Comment by fsbaraglia** [comment]
yes. unfortunately the Immuni app is not showing the num of Exposures but just if you are in high RISK.

**Comment by Ein-Tim** [comment]
I will close this issue now. If there are still any duplicates, we can reopen it.
