### ISSUE TITLE
Update 1.9.1 => Reduzierung der Begegnungen auf 0?

### ISSUE THREAD

**Issue by theMoe** [corona-warn-app/cwa-app-ios#1706]
Mit dem Update auf 1.9.1 sind meine Begegnungen mit niedrigem Risiko von 24 auf 0 gesunken. In den Begegnungsüberprüfungen in den iOS Einstellungen steht weiterhin die 24 für den aktuellsten Datensatz.

Hat sich etwas am Algorithmus geändert? Wenn ja, was?

**Comment by Ein-Tim** [comment]
Duplicate of #1705

**Comment by dsarkar** [comment]
Dear @theMoe,

Thank you for your report. This issue was close since it is a duplicate and is not a bug. Please monitor and if necessary contribute here: #1703.  

Best wishes, DS

---
Corona-Warn-App Open Source Team
