### ISSUE TITLE
Availability Alerts Activation?

### ISSUE THREAD

**Issue by 2x-pr0** [corona-warn-app/cwa-app-ios#1722]
Hey!

how do i activate this availability Alerts down on thr screen?

![E5AF3EE1-ACEA-4154-B82C-1B1A73C9A495](https://user-images.githubusercontent.com/74964739/102695295-a0450380-4226-11eb-80ef-713bdd463c2d.png)

**Comment by Ein-Tim** [comment]
As you can read in the text below the switch, you can't activate this "because Location Services are turned off in Settings".


How to turn it on: https://support.apple.com/en-us/HT207092

**Comment by 2x-pr0** [comment]
My location services are turned on.

**Comment by Ein-Tim** [comment]
@2x-pr0 
Could you provide a screenshot from the "Location Services" Menu?

**Comment by 2x-pr0** [comment]
Ive got it fixed with https://discussions.apple.com/thread/251753922
