### ISSUE TITLE
[BSI][20201223] Best-Practice Violation: Prevent SQL Injections

### ISSUE THREAD

**Issue by BSI-TF-CWA** [corona-warn-app/cwa-app-ios#1734]
Rating: Informational

Description:
The application contains multiple string concatenations for SQL queries.
None of the strings are controlled by the user or the server. However, if that changes (e.g. if the retention policy becomes a server-controlled value) it instantly implies an SQL injection.
SQL injection vulnerabilities arise when user-controllable data is incorporated into database SQL queries in an unsafe manner (e.g. string concatenation). An attacker can supply crafted input to break out of the data context in which their input appears and interfere with the structure of the surrounding query.
Various attacks can be delivered via SQL injection, including reading or modifying critical application data, interfering with application logic, escalating privileges within the database and executing operating system commands.
Most of the other queries are parameterized, the same should be applied to the following occurrences found in 
https://github.com/corona-warn-app/cwa-app-ios/blob/4e3f737af869e0786e202358da39a3755184b552/src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/ContactDiaryStoreV1.swift#L86
https://github.com/corona-warn-app/cwa-app-ios/blob/4e3f737af869e0786e202358da39a3755184b552/src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/ContactDiaryStoreV1.swift#L92
https://github.com/corona-warn-app/cwa-app-ios/blob/4e3f737af869e0786e202358da39a3755184b552/src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/ContactDiaryStoreV1.swift#L145
https://github.com/corona-warn-app/cwa-app-ios/blob/4e3f737af869e0786e202358da39a3755184b552/src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/ContactDiaryStoreV1.swift#L150
https://github.com/corona-warn-app/cwa-app-ios/blob/4e3f737af869e0786e202358da39a3755184b552/src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/ContactDiaryStoreV1.swift#L825

Recommended Controls:
All user-supplied data must be checked and validated, so that no SQL code is included into database commands. Proper input validation via Regular Expressions can help to mitigate this attack vector. Therefore, a list of allowed characters should be defined. This list should not include any characters that are handled in a special way by the database.
Additionally, prepared statements can be used to create SQL queries that are not vulnerable to SQL Injection. Any kind of string concatenation must be avoided, instead parameterized queries must be constructed.

**Comment by mlenkeit** [comment]
Thanks for pointing that out, we'll keep an eye on it. 

As you already mentioned, the SQL statements that you referenced do _not_ process user-supplied, server-supplied, or any other external data, so there is **no attach surface for SQL injections** in the 1.10 release.

The queries that _do_ process user-supplied data are properly protected against SQL injections, e.g.:

https://github.com/corona-warn-app/cwa-app-ios/blob/4e3f737af869e0786e202358da39a3755184b552/src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/ContactDiaryStoreV1.swift#L207-L222

or 

https://github.com/corona-warn-app/cwa-app-ios/blob/4e3f737af869e0786e202358da39a3755184b552/src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/ContactDiaryStoreV1.swift#L288-L307

I'll close the issue then.
