### ISSUE TITLE
Risk exposure Notification date is wrong 

### ISSUE THREAD

**Issue by szuecs** [corona-warn-app/cwa-app-ios#1735]
## Technical details

- Device name: iPhone
- iOS Version: 14.3
- App Version: 1.9.1

## Describe the bug

2 iOS devices from 2 different persons living in the same flat, both with newest Corona-Warn app installed.
One reported positive at date X and the warn app reports only an exposure at date X and not every day since day X.

## Steps to reproduce the issue

1. report corona positive at device A
2. next days you can observe on device B next to device A no date changes in the notification 

## Expected behaviour

all days next to a positive marked phone should be reported

**Comment by Ein-Tim** [comment]
Hey @szuecs 

If you get tested positive and enter the test result in the app, the app will upload all recorded encounters to the server. 
Now every device running Corona-Warn App downloads the encounters from positive tested people from the server. The app now checks if it encountered any positive tested person in the last 14 days. 
(This is very simplified, for more information see: https://www.coronawarn.app/en/ and scroll down to the section "How does the App work?")

After you entered the positive test into the App other users will be warned. But they will only be warned once because hopefully a positive tested person will go into quarantine and doesn't encounter any more people.

**Comment by Ein-Tim** [comment]
Your question is also answered in the [Corona-Warn App Update Podcast](https://www.telekom.com/de/medien/podcasts/corona-warn-app). Listen to episode #10 at 07:11. The podcast is only available in German.

**Comment by thomasaugsten** [comment]
There are several reason why this not possible. To access the diagnosis keys the user has to accept a OS prompt in the App. This means the user has to start the app every day. We also don't want to encourage to break the quarantine.

**Comment by szuecs** [comment]
> From this part in the documentation, you can also see that Corona-Warn App will warn others about encounters that they had **before** you entered your positive result in the App.
> After you entered it, your phone will still continue to exchange keys with other phones, but these phones are not warned anymore.
> The simple reason for that is that people who tested positive hopefully don't encounter any other people but go into quarantine.

That’s just lol, no?
I mean we exchange keys and make sure that we could get correct information, but we don’t because we hope that everyone who is in quarantine won’t get in contact by anyone else?
What if you share a flat and the other person wouldn’t know?

> 
> So the bug here would not be about the exposures since day X but the exposures before day X.

There’s nothing shown in the app that you have constantly, every day contact, but this is fine?

**Comment by szuecs** [comment]
> There are several reason why this not possible. To access the diagnosis keys the user has to accept a OS prompt in the App. This means the user has to start the app every day. We also don't want to encourage to break the quarantine.

Both phones with apps running every day.
Not sure if I understand your point.

**Comment by Ein-Tim** [comment]
@szuecs 

> That’s just lol, no?
I mean we exchange keys and make sure that we could get correct information, but we don’t because we hope that everyone who is in quarantine won’t get in contact by anyone else?
What if you share a flat and the other person wouldn’t know?

I understand your concerns. You could [open a Feature/Enhancement Request](https://github.com/corona-warn-app/cwa-wishlist/issues/new/choose) in the Wishlist Repo.


> There’s nothing shown in the app that you have constantly, every day contact, but this is fine?

I don't fully understand what you mean, sorry.

**Comment by szuecs** [comment]
> > There’s nothing shown in the app that you have constantly, every day contact, but this is fine?
> 
> I don't fully understand what you mean, sorry.

Day X is the day of exposure of phone A. Phone B is every day for hours in the same room. It’s reported in phone B only day X.
You’re right that it should be reported day X-2 but also until day X+14 (14 or at least 10 but not only 0). This sounds not like a feature to me.

**Comment by Ein-Tim** [comment]
> Both phones with apps running every day.
Not sure if I understand your point.

To share the Keys (=encounters) from your phone, you have to open the App and accept a prompt which comes from iOS. So it is not possible to share keys in the background --> a positive tested user would have to open the App every day to share his Keys again and again.

**Comment by szuecs** [comment]
Ok that makes sense, because then you would need to get the secret again to do the write from phone A to the system to tell positive tested.

**Comment by Ein-Tim** [comment]
> Day X is the day of a positive test sent by phone A. Phone B is every day for hours in the same room. It’s reported in phone B only day X.
You’re right that it should be reported day X-2 but also until day X+14 (14 or at least 10 but not only 0). This sounds not like a feature to me.

But it is the current implementation and I think it makes sense;

The health authority does also only inform people you encountered before you were tested positive and not them who you meet if you are in quarantine (whoever you should meet in quarantine who doesn't know that you are positive).

**Comment by Ein-Tim** [comment]
If your question here is answered, please close this Issue. 
As said before, feel free to [open a Issue in the Wishlist Repo](https://github.com/corona-warn-app/cwa-wishlist/issues/new/choose).


Stay safe and healthy!

**Comment by Ein-Tim** [comment]
@thomasaugsten could you close this?
