### ISSUE TITLE
Why exposure logging always show 13/14 days even though exposure logging is always active?

### ISSUE THREAD

**Issue by cricketsamya** [corona-warn-app/cwa-app-ios#1739]
## Avoid duplicates
* [ ] Question is not already answered in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Question has not already been asked in another issue

## Your Question

Why exposure logging always show 13/14 days even though exposure logging is always active?
I every day check the app. But I have never seen 14/14 or always active. Am I expecting something wrong?
* Source File:
* Line(s):
* Question:

**Comment by Ein-Tim** [comment]
Please see #1127.
According to @dsarkar:
> the issue was observed also by the developers and is set to high priority now

(see: https://github.com/corona-warn-app/cwa-app-ios/issues/1127#issuecomment-740461168).

**Comment by cricketsamya** [comment]
Yes Wifi and Bluetooth is off! As I  dont want to drain off battery of my wearables!

**Comment by Ein-Tim** [comment]
@cricketsamya 

Yes, and that's the "Problem". Since it is turned off during the night it wasn't activate for the whole day (technically). 
See @thomasaugsten's comment [here](https://github.com/corona-warn-app/cwa-documentation/issues/412#issuecomment-686388303)

**Comment by cricketsamya** [comment]
Closing as asked! 💪🏼

**Comment by dsarkar** [comment]
@Ein-Tim, @cricketsamya Thanks, will forward this issue to developers.
