### ISSUE TITLE
License is hard to find

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#1740]
## Avoid duplicates

* [x] This issue has not already been raised before
* [x] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation
iOS Repository does not have a license.

## Suggested Enhancement
Add a license, i.e. the Apache License Version 2.0, how it's already done in the [Android Repository](https://github.com/corona-warn-app/cwa-app-android/blob/main/LICENSE).

I would open a PR which adds the license, you only have to check if this Repository is also licensed under the Apache License Version 2.0.

---
Internal Tracking ID: EXPOSUREAPP-4470

**Comment by dsarkar** [comment]
Morning @Ein-Tim, 

Have a look here: https://github.com/corona-warn-app/cwa-app-ios/blob/release/1.9.x/LICENSES/Apache-2.0.txt.

Best, DS

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
Okay thanks @dsarkar, I did not see this 😅 
Maybe you would like to add [this](https://github.com/corona-warn-app/cwa-app-android#licensing) text to the README.md here to? Because as of now the license is quite hard to find and GitHub is also showing:
![image](https://user-images.githubusercontent.com/67682506/103205836-c5a6d100-48fa-11eb-8604-4ba8685b3007.jpeg)

**Comment by Ein-Tim** [comment]
Solved by #1754

**Comment by dsarkar** [comment]
@Ein-Tim Thanks.

**Comment by jucktnich** [comment]
Here isn't the license still
![image](https://user-images.githubusercontent.com/73582096/104422783-7eb50e80-557d-11eb-84de-6c90d5fcffea.jpeg)

**Comment by Ein-Tim** [comment]
@jucktnich yes this is not possible because GitHub searches for a file named "LICENSE" and grabs this but the iOS Repo has the licenses in a folder (GitHub is not aware of this).

**Comment by jucktnich** [comment]
Why is it not possible to create a license file?

**Comment by Ein-Tim** [comment]
@jucktnich 

As you can see in the [LICENSES](https://github.com/corona-warn-app/cwa-app-ios/tree/release/1.12.x/LICENSES) folder, the Repo is licensed under 2 Licenses, I think GitHub can only show one license, so you would have to pick one.

**Comment by jucktnich** [comment]
Or write to in one file.

**Comment by Ein-Tim** [comment]
Yes would be possible, maybe @kaddaSz could just quickly give her opinion to this? 🙂

**Comment by kaddaSz** [comment]
@jucktnich, @Ein-Tim:
The [LICENSES](https://github.com/corona-warn-app/cwa-app-ios/tree/release/1.12.x/LICENSES) folder is needed for the [REUSE Tool](https://reuse.software/), to which we migrated for the iOS repo already. Unfortunately this is not recognized by GitHub. 
We will check if we just add the LICENSE file with the Apache 2.0 License again (and additionally) to the root folder, so that the license information can be shown by GitHub.

**Comment by Ein-Tim** [comment]
@jucktnich see #1791

**Comment by Ein-Tim** [comment]
@dsarkar 
Can be moved to done
