### ISSUE TITLE
Add Home Screen Quick Actions

### ISSUE THREAD

**Issue by jajoho** [corona-warn-app/cwa-app-ios#1744]
## Avoid duplicates

* [x] This issue has not already been raised before
* [ ] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation
Currently I do not have any quick actions, when I touch and hold the app icon (see screenshot)
![IMG_63E7D35D980E-1](https://user-images.githubusercontent.com/15175599/103221492-17fbe800-4923-11eb-8e57-7084089a57c5.jpeg)

## Suggested Enhancement
It would be nice, if I could get directly to the most important functions of the app (e.g. Kontakt-Tagebuch).

## Expected Benefits
More usability of the app -> It is more likely, that the functions are frequently used 

> Since this is a request for a new feature (what I would support), please move this Issue to the [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist/issues/new?labels=feature+request&template=01_feature_request.md)

**Comment by Ein-Tim** [comment]
Since this is a request for a new feature (what I would support), please move this Issue to the [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist/issues/new?labels=feature+request&template=01_feature_request.md)

**Comment by jajoho** [comment]
@Ein-Tim Since this is an iOS feature, I assume it doesn't make that much sense to add this suggestion to the general list

**Comment by Ein-Tim** [comment]
@jajoho Since Android does support quick actions too ("dynamic shortcuts" see i.e.: [this article](https://medium.com/@alla.dubovska/android-how-to-add-dynamic-shortcuts-to-your-app-55d774af23fd)) I think a implementation fot both iOS and Android should be considered.

**Comment by jajoho** [comment]
Created new issue: https://github.com/corona-warn-app/cwa-wishlist/issues/295

**Comment by dsarkar** [comment]
@jajoho Thanks for contributing. We will have a look at your wishlist issue.

Best wishes,
DS

---
Corona-Warn-App Open Source Team
