### ISSUE TITLE
[CWA Appstore] App Store Screenshot showing old version

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#1747]
## Avoid duplicates

* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is not already reported in another issue

## Describe the bug

In the [App Store](https://apps.apple.com/de/app/corona-warn-app/id1512595757) the first screenshot was definitely not taken on version 1.10.
Screenshot in the App Store: 

<img src="https://user-images.githubusercontent.com/67682506/103233958-b6e20d80-493e-11eb-99fa-f11e980dbd3f.jpeg" width="300">

Screenshot from the app:

<img src="https://user-images.githubusercontent.com/67682506/103233983-cbbea100-493e-11eb-9ba3-a7cecc473d61.jpeg" width="300">

---
Internal Tracking ID: [EXPOSUREAPP-4672](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4672)

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-4672](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4672)

**Comment by Ein-Tim** [comment]
Solved with 1.11 release.
Will be closed now.

**Comment by dsarkar** [comment]
@Ein-Tim Thanks!
