### ISSUE TITLE
Missing encounters in App

### ISSUE THREAD

**Issue by flightsearch** [corona-warn-app/cwa-app-ios#1755]
After last app update to 1.10.1 number of exposures dropped from 3 to zero. 

Im Begegnungsüberprüfung there are 3 matching IDs 
![1DEBF318-A316-4979-BFA8-569D19EC059A](https://user-images.githubusercontent.com/4244558/103501763-7a874380-4e4f-11eb-8ecf-989337cc678d.png)

![27C25442-FD43-45EA-A947-8631310C8C3F](https://user-images.githubusercontent.com/4244558/103501786-8bd05000-4e4f-11eb-9153-5972dd2d113e.png)

**Comment by dsarkar** [comment]
@flightsearch, see https://github.com/corona-warn-app/cwa-app-ios/issues/1703

**Comment by dsarkar** [comment]
@flightsearch, thanks for closing,
