### ISSUE TITLE
Add 'ENA Community' build to your CI pipeline

### ISSUE THREAD

**Issue by ndegendogo** [corona-warn-app/cwa-app-ios#1764]
## Avoid duplicates

* [x] This issue has not already been raised before
* [ ] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation

The true ENF framework is available only for the cwa development team, but not for the public. To mitigate this fact, a 'mock' has been developed and included in the repo, and a build target was setup to link with this mock.
This mock needs to be maintained with evolution of the code base. Unfortunately, it has happened in the past several times that this was forgotten. See #1585 for example. It seems that such a broken build during development is detected only per accident / or when reported from the community. 

## Suggested Enhancement

Extend your CI pipeline, add a build of the 'ENA Community' target.

## Expected Benefits

Breaking this build will be noticed timely.
Especially such a broken build can be fixed in time **before** a release.

Please note that code browsing tools (like the XCode IDE) need a successfull build to work properly. With a broken ENA Community build at a release label it is very hard for a community member to even read your released code.

---
Internal Tracking ID: EXPOSUREAPP-4522

**Comment by heinezen** [comment]
Hey @ndegendogo ,

Thank you for the proposal. We have mirrored this request to our internal Jira. The dev team will look into this and we will notify you here if we get any news about this.

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@ndegendogo 

Solved with #1978?

**Comment by ndegendogo** [comment]
@Ein-Tim wow, yes, seems so! Thanks for watching the PRs and keeping us updated!

And many thanks to the developers for addressing this!

**Comment by dsarkar** [comment]
@ndegendogo Thanks for contributing here!
