### ISSUE TITLE
App shows two encounters, json file doesn't ?

### ISSUE THREAD

**Issue by somebabe** [corona-warn-app/cwa-app-ios#1775]
I’ve downloaded this app nearly two weeks ago when I went shopping a day before New Years Eve. I remember there was large crowds in-front of each shop and I spent quite some time there.

Anyways the question is: It says that I have **2 encounters with low risk**. The color of the app is still green but when I check json file I can’t seem to find the date of it or any information about those 2 encounters. Is that a bug or am I just having trouble reading the code ? 

The reason I'm asking this is because I do feel slightly unwell and scared of potentially getting infected. 

Thanks in advance! 

![image0](https://user-images.githubusercontent.com/77331958/104313177-efa1eb00-54d7-11eb-8303-2f819c26be1e.png)

[ExposureChecks-2021-01-12.zip](https://github.com/corona-warn-app/cwa-app-ios/files/5801941/ExposureChecks-2021-01-12.zip)

**Comment by dsarkar** [comment]
Hi @somebabe,

Thanks for reporting. Can you provide some more information, please?

- iOS version
- iPhone model
- Version 1.10.1 ?
- I understand you are using the Slovenian App. Version ?

Note: Officially only the German CWA is supported/maintained from the developers side here. However, having this said, keep this issue open here, and somebody might find the time to have a look into it.

Best wishes,
DS

---

**Comment by Ein-Tim** [comment]
I am looking into this right now

**Comment by Ein-Tim** [comment]
You are using iOS 14.0.1, with this version there is a bug that the json file does not contain any matches. Please update to iOS 14.1 or higher.

**Comment by somebabe** [comment]
> You are using iOS 14.0.1, with this version there is a bug that the json file does not contain any matches. Please update to iOS 14.1 or higher.

If I update my iOS to higher will it show the matches of this “2 encounters” or will it only show for the future matches? 

Thank you so much for taking your time!  You truly are a nice person!

**Comment by dsarkar** [comment]
@Ein-Tim Great stuff!

**Comment by Ein-Tim** [comment]
@somebabe 
If the matches are not already older than 14 days it will also show these encounters

**Comment by somebabe** [comment]
> @somebabe
> If the matches are not already older than 14 days it will also show these encounters

Thank you. The reason I haven’t updated it yet is cause I want to keep my phone jailbroken but I guess health is more important. 😊

**Comment by Ein-Tim** [comment]
But please note that you won't be able to see the time of the encounter or something like this, you will just see when the hash was downloaded from the server.

**Comment by somebabe** [comment]
> But please note that you won't be able to see the time of the encounter or something like this, you will just see when the hash was downloaded from the server.

Oh so at least the day I might know. Well thank you so much. Stay safe. ❤️😊

**Comment by Ein-Tim** [comment]
Thank you! 
If you are happy with the answerer you could close this Issue.


Stay safe and healthy!

**Comment by Ein-Tim** [comment]
@thomasaugsten could you close this
