### ISSUE TITLE
"Exposure check" notification after confirmed positive

### ISSUE THREAD

**Issue by moburkhardt** [corona-warn-app/cwa-app-ios#1815]
## Avoid duplicates

* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 12 Pro
- iOS Version: 14.3
- App Version: 1.10.1 (0)

## Describe the bug

The push notifications to regularly check the app in order for the "exposure check" to update continue to be pushed even when the app has been elevated into the state of "confirmed positive" and the quarantine time is not yet up.

At this stage there is no need to refresh the other ids from the server as the user is in quarantine and  

## Steps to reproduce the issue

1. Enter Confirmation code from lab, via QR Code or Tan, 
2. wait, 
3. after 7 days the alert to open the app In order to do the exposure checking will be displayed

## Expected behaviour

Notifications will be disabled once confirmed positive for at least 10 days (duration of quarantine )

## Possible Fix

Allow for user set timeframe in which no notifications will be pushed after the app receives a confirmation code of a postive test.

## Additional context

---
Internal Tracking ID: [EXPOSUREAPP-4805](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4805)
Internal Tracking ID: [EXPOSUREAPP-4781](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4781)
FYI solved with PR #1960

**Comment by Ein-Tim** [comment]
> Allow for user set timeframe in which no notifications will be pushed after the app receives a confirmation code of a postive test.


Since the App will not show any result of the risk calculation when a positive test was entered this is not necessary. It would be enough to deactivate the Dead-Man notification if there was a positive test result entered in the App. 

To devs: Please check under Android too.

**Comment by dsarkar** [comment]
@moburkhardt Thanks for reporting. Could you provide us with the following information, please:
- Date of your PCR test
- Date when you scanned the QR code
- Date when you received the positive test result
- Date of the push notification to check the CWA

Many thanks. Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by moburkhardt** [comment]
PCR test date 13.01.2021
Phone Tan input 15.01.2021
Postive Test result 15.01.2021
Date of Push notification to check CWA 19.01.2021

**Comment by Ein-Tim** [comment]
@dsarkar I think the Dead Man Notification should be deactivated in case that the user has entered a positive test result. 
Yes the risk checks will still work in the background, but since this is not shown to the user it is also not necessary to remind the user to open the App.

**Comment by dsarkar** [comment]
@Ein-Tim OK.

@moburkhardt: 
Was the notification one of these ('Deadman notifications.')
- DE "Bitte öffnen Sie die Corona-Warn-App, um die Risiko-Überprüfung anzustoßen." or
- EN "Please remember to open the Corona-Warn-App regularly to check your risk status."

Thanks for the feedback.

**Comment by moburkhardt** [comment]
@dsarkar Yes the notification was the EN localised 'Deadman notification'
Screenshot attached
![IMG_3120](https://user-images.githubusercontent.com/169051/105985507-d4200e00-609b-11eb-9dae-a2ccf6e6d74b.PNG)

**Comment by dsarkar** [comment]
@moburkhardt Thanks.

**Comment by dsarkar** [comment]
Hi  @moburkhardt, Thanks again for reporting. We have created an internal ticket for this issue. Any further development will be published here. Best wishes, DS

---
Corona-Warn-App Open Source Team

Internal Tracking ID: [EXPOSUREAPP-4805](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4805)

**Comment by ndegendogo** [comment]
> Yes, the risk checks will still work in the background 

@Ein-Tim why? My understanding was that after the positive test the risk checking stops. Has this changed, or is there a misunderstanding on my side?

**Comment by Ein-Tim** [comment]
@ndegendogo 

I also asked me why they do this but I didn't find an answer. 

But yeah, they do it, @thomasaugsten stated this somewhere (if I find it I will link it here)...
@moburkhardt Could also provide his EN-Log, then we could see that the checks still happen after a positive test was entered.

**Comment by moburkhardt** [comment]
@Ein-Tim unsure how to grab that log, could you point me to some more Infos? I’d be happy to provide further Infos.

**Comment by Ein-Tim** [comment]
@moburkhardt 


<details>
<summary>How to export Exposure Notificaiton Logs under iOS 13.7 or newer</summary>


_This log does not conatin any private information._

**German:**

`Einstellungen` ➡️ `Begegnungsmitteilungen` ➡️ `Status von Begegnungsaufzeichnungen` ➡️ `Begegnungsüberprüfungen` ➡️ `Überprüfungen exportieren`

**English:**

`Settings` ➡️ `Exposure Notifications` ➡️ `Exosure Logging Status` ➡️ `Exposure Checks` ➡️ `Export Exposure Checks`

**To upload the file here, rename it from .json to .txt**
</details>

**Comment by moburkhardt** [comment]
@Ein-Tim thanks for that, here is the export:
[ExposureChecks-2021-02-01.json.zip](https://github.com/corona-warn-app/cwa-app-ios/files/5902631/ExposureChecks-2021-02-01.json.zip)

**Comment by Ein-Tim** [comment]
@moburkhardt 

Did you reset the App or is it still showing the thank you screen?
If you resettend it, do you remember when?

**Comment by moburkhardt** [comment]
@Ein-Tim I reset the CWA between the 25th and the 26th.

**Comment by Ein-Tim** [comment]
@moburkhardt 
Okay thanks.

@ndegendogo 
As you can see, the checks continued in the background even after the 15.01.21 (Input of positive test).

But when looking at your log I don't see a gap in the check which would trigger a dead man notification (<36h)...
@dsarkar please transfer this to the devs, it makes no sense to me that the dead man notification was fired on the 19.01.21

**Comment by thomasaugsten** [comment]
We aware of this Bug. After submitting the test result the risk calculation is stopped (not the submission to the ENF)  without disabling the deadman notification we will improve this in the next version also with the possibility to reset the app more easy

**Comment by Ein-Tim** [comment]
Thanks @thomasaugsten 
So the fix for this will be in 1.12? 

Btw what do you mean with:
> After submitting the test result the risk calculation is stopped (not the submission to the ENF)

Do you mean that CWA continues to download files from the server and submits them to the ENF but then the final step of the risk calculation (done by CWA) is not carried out?

**Comment by Ein-Tim** [comment]
O/T @dsarkar What does the `Sprint 14` label mean?

**Comment by ndegendogo** [comment]
> O/T @dsarkar What does the Sprint 14 label mean?

@Ein-Tim very good point!
@dsarkar I think what we are missing here is the mapping of sprint numbers to calender time.

**Comment by dsarkar** [comment]
> And btw the Fix 1.13 label has the description Fix is planned for 1.12...

Fixed.

> What does the Sprint 14 label mean?

see for example https://www.atlassian.com/agile/scrum/sprints

> I think what we are missing here is the mapping of sprint numbers to calender time.

Sprint 14 tasks are intended to be resolved and fixes/features included for release 1.12 or 1.13
When I put the sprint-14 label it was not clear if the fix can be included in release 1.12 already.
Now I can forward you the info that it is planned for 1.13, so I remove the sprint label and replaced it with Fix-1.13 label. I hope that makes it a bit more transparent what's going on.

**Comment by Ein-Tim** [comment]
Thanks for explaining @dsarkar! ❤️

**Comment by Ein-Tim** [comment]
FYI: Fix is in https://github.com/corona-warn-app/cwa-app-ios/commit/1e48962ba4ae9e793ab46595922b73d7a94062bc.
	 Branch: https://github.com/corona-warn-app/cwa-app-ios/tree/feature/4781-end-of-life-behaviour

**Comment by dsarkar** [comment]
FYI solved with PR https://github.com/corona-warn-app/cwa-app-ios/pull/1960

**Comment by Ein-Tim** [comment]
@dsarkar 

According to the title of #2033, dead man notifications are scheduled and sent in End-of-Life state.
Could you plese clarify if they will fix this issue or not?

**Comment by dsarkar** [comment]
@Ein-Tim ok, I will check with the developers.

**Comment by Ein-Tim** [comment]
@dsarkar What did the devs say?

**Comment by dsarkar** [comment]
@Ein-Tim I am sorry, this question snowed under. Will bring it up again next week. Stand by, please.

**Comment by heinezen** [comment]
Hello everyone,

Tis issue should be fixed by now. Please report back if you are still experiencing the problem with the recent CWA version.

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@heinezen 

Sure about that, see PR #2033?

@dsarkar wanted to clarify this.

**Comment by dsarkar** [comment]
@heinezen @dsarkar We will try to get some info (Thursday).

**Comment by dsarkar** [comment]
@Ein-Tim Just got feedback from dev: dead man notifications are **NOT** scheduled and sent in End-of-Life state. This was a bug for a long time, but has been fixed.

**Comment by Ein-Tim** [comment]
@dsarkar 

Okay, this is really something I can't test, so I will trust the devs. I was confused by #2033, the title seems to be really inappropriate then.

Feel free to close this issue.

**Comment by dsarkar** [comment]
@Ein-Tim I agree, the title is confusing. 

Thanks to everybody for contributing. Closing this issue.
