### ISSUE TITLE
Number of active days is wrong if time is set to a past date

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#1847]
## Avoid duplicates

* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 6s
- iOS Version: iOS 14.4 Public Beta RC 1 / iOS 14.3
- App Version: 1.10.1

## Describe the bug

If you set the system time of your iPhone back (f.e. a month - but one day is also enough), CWA will show an unrealistic high number of active days.

<img src="https://user-images.githubusercontent.com/67682506/105634065-95504500-5e5c-11eb-884a-8369581430bb.PNG" width="300">

## Steps to reproduce the issue

1. Close CWA completetly 
2. Open the iOS-Settings: General -> Date & Time -> Set  Automatically OFF -> Change to any date in the past 
3. Open CWA 
4. See unexpected long number of days 

## Expected behaviour

The quote "Exposure logging was active for 0 of the past 14 days." should be shown 
or 
(how it is done if the user's time is in the future) the "[Exposure check failed](https://user-images.githubusercontent.com/67682506/105634703-bebea000-5e5f-11eb-844f-07db316960e0.PNG)" card and [this](https://user-images.githubusercontent.com/67682506/105634711-ca11cb80-5e5f-11eb-98ee-ad03081c09ab.PNG) pop up should be shown.

## Additional context

@MikeMcC399 could you maybe check the behavior under Android?

---
Internal Tracking ID: [EXPOSUREAPP-4755](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4755)

**Comment by MikeMcC399** [comment]
@Ein-Tim 
This is similar to https://github.com/corona-warn-app/cwa-app-android/issues/1786 where a negative number was being displayed as a large positive number.

4.294.967.268 = 0xFFFF FFE4 or -28 in DWORD

I couldn't reproduce it with CWA Android 1.10.1.

For Android there is a related PR https://github.com/corona-warn-app/cwa-app-android/pull/2019 related to "time travel" however it hasn't been merged into a released version yet.

**Comment by Ein-Tim** [comment]
Okay thanks @MikeMcC399.

I know about the Android Issue, and since this was a bug in Googles ENS, I fear that this is the same bug but for Apples ENF. 

I will leave this Issue here since you could not reproduce it and according to @dsarkar in https://github.com/corona-warn-app/cwa-app-android/issues/1786 this should be fixed in version 1.8.

**Comment by dsarkar** [comment]
@Ein-Tim I can reproduce this on iOS 14.3.

**Comment by dsarkar** [comment]
Any updates will be reported here.
Internal Tracking ID: [EXPOSUREAPP-4755](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4755)

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for your comments, which have been added to the ticket as additional remarks.

**Comment by Ein-Tim** [comment]
I actually can't reproduce this anymore on CWA 1.11 and iOS 14.4.

I've uninstalled the App and downloaded version 1.11 from the App Store. I did the onboarding and afterwards I set the time back (1 month back). Everything looked correct, "Risiko-Ermittlung war für 0 der letzten 14 Tage aktiv".

So the problem with the large number seems to be solved, still I think the behavior for a shifted back time should be the same as for a time in the future.

**Comment by dsarkar** [comment]
@Ein-Tim 

CWA 1.11 / iOS 14.4 / iPhone6s -  I set date to 1.12.2020 and I get this:

![IMG_487910DED7A8-1](https://user-images.githubusercontent.com/1409741/106248019-ac05eb80-6210-11eb-89a6-70db95feb768.jpeg)

**Comment by Ein-Tim** [comment]
Yes, looks definitely better than before.
I have different behaviors, either the screen that you have is shown or the quote "Exposure logging was active for 0 of the past 14 days."

will close this now

**Comment by dsarkar** [comment]
@Ein-Tim Thanks!
