### ISSUE TITLE
Corona Warn App bringt iPhone XS mit IOS 14.3 dauernd zum Absturz

### ISSUE THREAD

**Issue by miracee** [corona-warn-app/cwa-app-ios#1854]
Nach Installation und Einrichtung der APP sowie hochladen der Tests (auf Annordnung des Arztes im Abstand von 48 Stunden) stürzte das iPhone innerhalb einer Woche im Schnitt alle zwei Stunden ab. Es ging aus und musste manuell wieder eingeschaltet werden. Das Handy hat während der Zeit das Haus nicht verlassen sondern lediglich hin und wieder das Stockwerk gewechselt.

Darüber hinaus wurde immer wieder automatisch das WLAN deaktiviert. Andere Apple-Geräte, wie Uhr, MacBooks usw. hatten keine Probleme mit dem WLAN. Wenn das WLAN manuell wieder angeschaltete wurde, wechselte es nach kurzer Zeit zurück auf LTE und das WLAN in den Einstellungen war deaktiviert.

Die Deinstallation der App und das deaktivieren der Begegnungsmitteilungen änderte am Problem nicht. Dem Apple-Support war das Problem bereits bekannt. Sie bestätigten mündlich, dass es an der App liegt.

Für die Behebung des Problems musste das iPhone komplett zurückgesetzt werden. Ohne App und mit ausgeschalteten Begegnungsmitteilungen funktioniert das Handy wieder normal und auch die Kommunikation mit der Uhr klappt wieder problemlos.

**Comment by Ein-Tim** [comment]
Hi @miracee 

Ich benutze die Corona-Warn-App auf meinem iPhone XR (iOS 14.3) und auf meinem iPhone 6s (iOS 14.4 Public Beta RC 1) ohne Probleme, habe aber auch kein Testergebnis geteilt.


Ich denke es ist davon auszugehen das das Problem, welches du hast, nicht von der Corona-Warn-App (bzw. nur indirekt) verursacht wird, sondern von der API auf welche die App zurückgreift. 
Diese ist auf Betriebssytemlevel integriert und Aktionen wie WLAN ausschalten, etc. sollten im Normalfall nur vom Betriebssystem durchgeführt werden können, die Corona-Warn-App kann das auf jeden Fall nicht.

>Dem Apple-Support war das Problem bereits bekannt. Sie bestätigten mündlich, dass es an der App liegt.

Das ist interessant, @thomasaugsten hat Apple euch irgendwelche Informationen bezüglich dieses Bugs im ENF mitgeteilt?

Du meintest das eine Deinstallation der Corona-Warn-App und das deaktivieren von Begegnungsmitteilungen nichts geholfen hat. 

>Die Deinstallation der App und das deaktivieren der Begegnungsmitteilungen änderte am Problem nicht.

Nur zum Verständnis, auch nachdem du die App deinstalliert hast stürzte dein iPhone **mehrere** male ab und du hattest Probleme mit dem WLAN?

Bevor das Handy ausging, gab es da irgendeine Fehlermeldung oder so etwas? Ist es eingefroren oder ist es aus dem nichts abgestürzt?
Gab es ein Problem während du den Test in der App geteilt hast?

Sind in deinem iPhone in den Einstellungen unter "Datenschutz" -> "Analyse & Verbesserungen"-> "Analysedaten" irgendwelche Einträge welche mit "ENA" beginnen zu sehen (wenn ja bitte **nicht hier teilen**, da diese unter Umständen sensible Daten enthalten könnten). 

>Für die Behebung des Problems musste das iPhone komplett zurückgesetzt werden. Ohne App und mit ausgeschalteten Begegnungsmitteilungen funktioniert das Handy wieder normal und auch die Kommunikation mit der Uhr klappt wieder problemlos.

Interessant wäre ob das nochmal passiert, wenn du die App nun wieder installierst. Wenn du willst kannst du das ja mal ausprobieren, könnte aber auch verstehen, wenn dir das zu "gefährlich" ist.

Eine letzte Frage noch: Hast du dein Handy komplett zurückgesetzt und danach nicht von einem Backup wiederhergestellt?

**Comment by thomasaugsten** [comment]
Ich gehe auch nicht davon aus das die CWA ein Crash im Betriebssystem erzeugen kann, wenn doch wäre das ein Bug der ein hohen Verkaufswert hätte und sofort von Apple geschlossen werden würde.
In unseren Tests und auf allen Supportkanäle für die CWA und auch bei allen Apps in Europa ist kein solches Verhalten bekannt.

Also kann sich die Aussage vom Apple-Support sich nicht auf die App beziehen. Ich denke sie bezieht sich eher auf die Aussage Wifi lässt sich nicht aktivieren das ist ein bekanntes iOS 14 wifi daemon Problem. Bei dem nur ein Settings Reset hilft.

Da das ausschalten der Begegnungsüberprüfung auch keine Änderung gebracht hat ist es als Ursache auszuschließen, da jegliche iOS und Bluetoothinteraktion beendet wird.

**Comment by miracee** [comment]
Moin,

Wow! Mit so schneller Reaktion hatte ich nicht gerechnet.
Und wie ich sehe, war es auch ok, Euch in Deutsch zu schreiben.

Danke für den Tipp mit den Analysedaten. Ich wusste gar nicht, dass Apple das macht.
Ich sag es mal so: Die Meldungen beim Absturz waren IOS "Kernel Panic"

Das sieht mir dann doch stark nach ... tja ... Kernel Panic ... Betriebssystem aus.

Den Trace erspare ich Euch. 

Es seid eindeutig nicht Ihr; sondern, wenn dann die Schnittstelle.

Wir haben natürlich auch mit mehreren ITlern gerätselt, woran es liegen kann.

Meinetwegen dürft Ihr den Bug schliessen.

Beste Grüße,

miracee

**Comment by Ein-Tim** [comment]
@thomasaugsten Could you close this?

**Comment by dsarkar** [comment]
@miracee, 

Vielen Dank für Deinen Feedback! Wir schliessen dieses Issue. Sollten weitere, andere, neue Probleme auftauchen, bitte gerne ein neues Issue anlegen. 

Alles Gute, DS

---
Corona-Warn-App Open Source Team


@Ein-Tim, @thomasaugsten Dank auch an Euch.
