### ISSUE TITLE
Contact journal (diary) entries disappear

### ISSUE THREAD

**Issue by dsarkar** [corona-warn-app/cwa-app-ios#1880]
---

## Technical details

**CASE 1**
- iPhone SE
- CWA 1.10.1
- iOS  14.3

**CASE 2**
- iPhone 6s
- CWA 1.10.1
- iOS 14.4 

## Describe the bug

- Contacts disappear from the contact journal

## Steps to reproduce the issue

**CASE 1**
1. Go to Contact journal
2. Add persons
3. Go back, see entries
4. close CWA (swipe)
5. open CWA, check contacts

- NOT reproduced on: CWA 1.11 / iPhone 6s / iOS 14.4 @Ein-Tim 
- NOT reproduced on: CWA 1.11 / iPhone 6s / iOS 14.4 @dsarkar 
- NOT reproduced on: CWA 1.11 / iPhone XS / iOS 14.4 @Ein-Tim 

**CASE 2**
- Create contact jounal entries using the same person
  - last day 
  - and other days
  - after one day, with the last day being deleted, all other entries of the same person have disappeared

## Expected behavior

- Contacts shouldn't disappear, only after 14 days

---

Fig from left to right
1. contact entries have been created and are shown correctly. CWA is then closed
2. reopen CWA, contacts are not shown anymore
3. tap on a day, you see the persons you have created previously, but specific entries of the day(s) have disappeared

![image](https://user-images.githubusercontent.com/1409741/106262501-6999da00-6223-11eb-92cc-3bc7b72c365e.png)

---
Internal tracking ID: [EXPOSUREAPP-4952](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4952)

**Comment by dsarkar** [comment]
@Ein-Tim Can you reproduce this? Thanks for the feedback.

**Comment by Ein-Tim** [comment]
Case 1 not reproducible, will test Case 2. Will report back here tomorrow.
Testing on both, iPhone 6s & XR

**Comment by Ein-Tim** [comment]
IMHO somebody should test the behavior with an iOS update. Somebody here who is on iOS 14.3 and wants to update to 14.4?
If yes, please create some entries in the contact journal and close the App completely. Then, open the app back up after you updated (maybe even without WiFI).
Thanks!

**Comment by Ein-Tim** [comment]
Tested this:

1. Add entries to contact diary
2. Close App completely
3. Update from version 1.10.1 to 1.11.0
4. All entries still there

**Comment by Ein-Tim** [comment]
Tested Case 2 too, not reproducible on my devices. 🤷‍♂️

**Comment by dsarkar** [comment]
Same here, I cannot reproduce either.

**Comment by dsarkar** [comment]
Internal tracking ID: [EXPOSUREAPP-4952](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4952)

**Comment by dsarkar** [comment]
we have some indication that this issue is resolved by updating from iOS 14.3 to 14.4.

**Comment by Ein-Tim** [comment]
@dsarkar 

If this is _fixed_, will you close this now?

**Comment by dsarkar** [comment]
@Ein-Tim yep, can't be reproduced in 1.11 and 14.4. closing it. Thanks for feedback !
