### ISSUE TITLE
App is incompatible with iPod touch although listed as a compatible device on the App Store page

### ISSUE THREAD

**Issue by docs-eng** [corona-warn-app/cwa-app-ios#1887]
## Avoid duplicates

[X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
[X] Bug is not already reported in another issue

## Technical details

- Device name: iPod touch 7th generation
- iOS Version: 14.4
- App Version: 1.11.0

## Describe the bug

The App Store page lists as compatible devices “iPhone and iPod touch running iOS 13.7 or later“. But the app cannot be installed on an iPod touch running iOS 14.4.

## Steps to reproduce the issue

1. On an iPod touch with iOS 14.4, open the App Store.
2. In the App Store, go to the Corona-Warn-App.
3. At the top of the App Store page, a notice is displayed that the iPod touch is not a compatible device. ![image](https://user-images.githubusercontent.com/70102960/106305163-a209da00-625c-11eb-8a06-8b9b026738b1.jpeg)
4. At the bottom of the page, ”iPod touch running iOS 14.4 or later“ is listed as a compatible device. ![image](https://user-images.githubusercontent.com/70102960/106305143-9c13f900-625c-11eb-8588-ecb505415cf5.jpeg)

Screenshots taken on an iPod touch 7th generation ![image](https://user-images.githubusercontent.com/70102960/106305183-a930e800-625c-11eb-806d-8c4c3c9e8d49.jpeg)

## Expected behaviour

iOS 14.4 on iPod touch does support Apple’s Exposure Notification framework. ![image](https://user-images.githubusercontent.com/70102960/106305673-42f89500-625d-11eb-9d4b-1fbe2b8a1b1b.jpeg)

The Corona-Warn-App should be possible to install on an iPod touch running the latest iOS.

**Comment by Ein-Tim** [comment]
Hi @docs-eng 👋🏻

Could you please provide a screenshot of the "Begegnungsmitteilungen" menu?

Thanks

**Comment by docs-eng** [comment]
Hi @Ein-Tim

![image](https://user-images.githubusercontent.com/70102960/106306805-d4b4d200-625e-11eb-8bd7-f99d26863665.jpeg)

**Comment by Ein-Tim** [comment]
@docs-eng 

Could you please try: https://www.coronawarn.app/en/faq/#ios_black_screen?

**Comment by docs-eng** [comment]
@Ein-Tim 

[https://www.coronawarn.app/en/faq/#ios_black_screen](https://www.coronawarn.app/en/faq/#ios_black_screen) did not help.

I have a 2nd iPod touch of the same model. I have fully reset that one to factory settings. I have just now set it up as a new device, no backup restored, only logged into iCloud.

The “Begegnungsmitteilungen” menu is the same, all black.
![image](https://user-images.githubusercontent.com/70102960/106312287-b652d480-6266-11eb-98ef-50d81aa9cb85.jpeg)

**Comment by Ein-Tim** [comment]
Okay thanks @docs-eng 

As you probably know, this menu in the settings is provided by Apple.
I am quite sure that you can't download the App because of the shown black screen in the settings.

Sadly, I don't know what you could do to see the correct screen in the settings: 

![image](https://user-images.githubusercontent.com/67682506/106313683-df746480-6268-11eb-8330-3a332b56bc4b.png)

Did you restart the device after doing the steps described in the FAQ?

**Comment by thomasaugsten** [comment]
The app is not unlocked for iPod because our information are the framework is only working for iPhones. Can you install a different COVID-19 app?
https://www.xda-developers.com/google-apple-covid-19-contact-tracing-exposure-notifications-api-app-list-countries/

**Comment by Ein-Tim** [comment]
@thomasaugsten 
If the App is not unlocked for iPhone you should consider to change the requirements in the App Store. Should I open a new Issue for this?

**Comment by thomasaugsten** [comment]
We have already a ticket for this 3451
@docs-eng Can you please test this apps
https://apps.apple.com/ch/app/swisscovid/id1509275381
https://apps.apple.com/us/app/coronalert-belgium/id1526431891

**Comment by docs-eng** [comment]
@Ein-Tim 

Yes, I have restarted my first iPod touch after resetting the privacy data (according to [https://www.coronawarn.app/en/faq/%23ios_black_screen&source=gmail-imap&ust=1612549194000000&usg=AOvVaw2psEC9s4V9pJrjJJVbRiDc](https://www.coronawarn.app/en/faq/%23ios_black_screen&source=gmail-imap&ust=1612549194000000&usg=AOvVaw2psEC9s4V9pJrjJJVbRiDc)). Also, I have fully reset my second iPod touch using Apple Configurator 2 on a Mac. (Restoring from a Mac is the most thorough way to reset any iOS device.)

According to Apple’s Dev Docs, all iOS devices running iOS 13.5 supported exposure notifications. [https://developer.apple.com/documentation/exposurenotification/building_an_app_to_notify_users_of_covid-19_exposure](https://developer.apple.com/documentation/exposurenotification/building_an_app_to_notify_users_of_covid-19_exposure)
![image](https://user-images.githubusercontent.com/70102960/106316754-8529d280-626d-11eb-8d48-d377bc8d6e91.jpeg)
However, the Danish and the Latvian exposure tracking apps, for example, have the same problem (not able to install, but listing iPod touch as a compatible device).
![image](https://user-images.githubusercontent.com/70102960/106316820-a5599180-626d-11eb-8d80-43e7433f4349.jpeg)
![image](https://user-images.githubusercontent.com/70102960/106316839-a985af00-626d-11eb-9049-6834caea9f04.jpeg)
![image](https://user-images.githubusercontent.com/70102960/106316846-ad193600-626d-11eb-8989-c9717baccc32.jpeg)
![image](https://user-images.githubusercontent.com/70102960/106316868-b1ddea00-626d-11eb-96a2-5bc84c3f0a5d.jpeg)
Also, my iPad running iOS 14.4 does not even have the “Exposure Notification” menu in Settings.

I have submitted this issue to Apple via [https://www.apple.com/feedback](https://www.apple.com/feedback)

Thank you for taking the time!
Thorsten

**Comment by docs-eng** [comment]
Hi @thomasaugsten 

Same
![image](https://user-images.githubusercontent.com/70102960/106317806-1fd6e100-626f-11eb-8db3-bb885d59d5d8.jpeg)
![image](https://user-images.githubusercontent.com/70102960/106317877-3b41ec00-626f-11eb-8820-712f1467c159.jpeg)
![image](https://user-images.githubusercontent.com/70102960/106317888-3e3cdc80-626f-11eb-8061-e4cca88d3e80.jpeg)
![image](https://user-images.githubusercontent.com/70102960/106317897-4137cd00-626f-11eb-988d-60c45c0558b5.jpeg)

See also my comment above regarding the Danish and Latvian apps.

**Comment by Ein-Tim** [comment]
> Also, my iPad running iOS 14.4 does not even have the “Exposure Notification” menu in Settings.

iPads don't support Exposure Notification. 

If you consider this as solved here (and it @thomasaugsten does not want to investigate this further) you could close this.

**Comment by Ein-Tim** [comment]
@thomasaugsten could you close this?

**Comment by thomasaugsten** [comment]
@dsarkar please transfer the tested App to 3451
