### ISSUE TITLE
„Begegnungs-Aufzeichnungen“ instead of „Begegnungsaufzeichnungen“ in reset view

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#1934]
## Avoid duplicates

* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: -
- iOS Version: 14.4
- App Version: 1.11.0

## Describe the bug

The [info screen](https://user-images.githubusercontent.com/67682506/107131796-09b5ca00-68da-11eb-9ecc-ffcb87b34b64.jpeg) which is shown to the user before resetting the app talks about deleting "Begegnungs-Aufzeichnungen".
However in the [iOS settings](https://user-images.githubusercontent.com/67682506/107131811-2baf4c80-68da-11eb-9b37-a80f25f0ee69.jpeg) it's called "Begegnungsaufzeichnungen". 

## Steps to reproduce the issue

1. Open CWA
2. Navigate to the very bottom
3. Click on "Einstellungen"
4. Click on "Anwendung zurücksetzten"

## Expected behaviour

Be consistent with iOS settings.

## Possible Fix

Change 

https://github.com/corona-warn-app/cwa-app-ios/blob/e16f6f078d3012ce65c71712b9e5f340d4ec2b89/src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings#L1164 

from 
`Begegnungs-Aufzeichnungen löschen` 
to 
`Begegnungsaufzeichnungen löschen`

and 

https://github.com/corona-warn-app/cwa-app-ios/blob/e16f6f078d3012ce65c71712b9e5f340d4ec2b89/src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings#L1166

from 
`Die Begegnungs-Aufzeichnung muss separat in den Geräte-Einstellungen gelöscht werden`
to
`Die Begegnungsaufzeichnung muss separat in den Geräte-Einstellungen gelöscht werden`.

## Additional context

I could open a PR which fixes this, but please first make sure that this won't get changed back with the next translation delivery.

---
Internal Tracking ID:  [EXPOSUREAPP-5017](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5017)

**Comment by dsarkar** [comment]
@Ein-Tim Thanks. I think you can do a PR if you like to. In the internal ticket, I will directly ping the translation people, so they can change it in the translation system as well.

**Comment by Ein-Tim** [comment]
Thanks @dsarkar 

I will create a PR soon.

**Comment by dsarkar** [comment]
OK, thanks !



---
Internal Tracking ID:  [EXPOSUREAPP-5017](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5017)

**Comment by Ein-Tim** [comment]
@dsarkar 

@janetback stated in #1937: https://github.com/corona-warn-app/cwa-app-ios/pull/1937#pullrequestreview-585291298

Could you please let me know if this is the final desicion or if they are maybe willing to change this.

If they want to leave it like this, I will close this Issue.

**Comment by dsarkar** [comment]
@Ein-Tim stand by. Will check.

**Comment by dsarkar** [comment]
@Ein-Tim Feedback: Quote:

> ... this should be written with a hyphen (einfaches Deutsch) - this is an official term in the glossary, and should not be changed 

Anyway thanks for the suggestion, they looked into it and took a decision.

**Comment by Ein-Tim** [comment]
If somebody is interested, I now found this glossar: https://www.bundesregierung.de/resource/blob/975226/1760836/fffa3f10830fe90d6d26453d6634af43/2020-06-16-glossar-data.pdf?download=1
