### ISSUE TITLE
Deletion of unused people/locations in the contact diary

### ISSUE THREAD

**Issue by felixbohnacker** [corona-warn-app/cwa-app-ios#1936]
## Avoid duplicates

* [X] This issue has not already been raised before
* [ ] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation
Currently, people and locations can‘t be deleted once they have been entered. If there is a typo, this is quite annoying.

## Suggested Enhancement
Allow deletion of entries that have not been added to the contact diary

## Expected Benefits
A less cluttered list of people/locations to select from

**Comment by Ein-Tim** [comment]
Hey @felixbohnacker 👋🏻

Indeed it is possible to delete locations/people, used or unused. 
Please follow [these](https://github.com/corona-warn-app/cwa-wishlist/issues/316#issuecomment-753401958) instructions. 

There is a open wishlist issue which requests a better usability for the contact diary: 

If you are happy with the answer, please close this Issue.

Thanks and stay safe!

**Comment by dsarkar** [comment]
@felixbohnacker Thanks for the question. I think @Ein-Tim has answered it adequately. As he suggests, please close this issue. Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
@Ein-Tim Actually not the first time this question was posed. What do you think about creating a FAQ on contact diary usage?

**Comment by Ein-Tim** [comment]
@dsarkar 
Sounds good, will you create a PR? 
Maybe it would be possible to link this from inside the App?

**Comment by felixbohnacker** [comment]
Thank you, I really missed this option. However, I agree that the usability could be better.

**Comment by dsarkar** [comment]
@felixbohnacker Thanks, any feedback and suggestions welcome!

**Comment by dsarkar** [comment]
@Ein-Tim 

> Sounds good, will you create a PR?

Can do, although having second thoughts... we have this large blog
https://www.coronawarn.app/en/blog/2020-12-28-corona-warn-app-version-1-10/ 

> Maybe it would be possible to link this from inside the App?

That must be discussed with devs and product owners. Let's start with a small FAQ, if necessary.

**Comment by Ein-Tim** [comment]
@dsarkar 

Right, I forgot this blog post, sorry.

I think a small FAQ entry would be still good to have this important information in the FAQs too, but not a high priority item.
