### ISSUE TITLE
Deadman notification is reset too early

### ISSUE THREAD

**Issue by ndegendogo** [corona-warn-app/cwa-app-ios#1964]
## Avoid duplicates

* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is not already reported in another issue

## Technical details

- Device name:
- iOS Version:
- App Version:

File RiskProvider.swift, line 290 and 322 (on branch release/1.14.x at 1bc728)

## Describe the bug

The deadman notification reset is called two times:
a) first from executeExposureDetection, **before** calling the completion handler (line 290)
b) second from calculateRiskLevel after the completion handler (line 322)

(a) seems too early, because the completion handler might fail.

Note: I have seen this only at a code review. It looks wrong, but I have not verified it with any test.
Of course there might be a misunderstanding on my side.

## Expected behaviour

Deadman notification is reset not before the risk calculation is really done and nothing can fail after this.

## Possible Fix

Just delete line 289 - 290?

## Additional context

---
Internal tracking ID: [EXPOSUREAPP-5100](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5100)

**Comment by dsarkar** [comment]
@ndegendogo Thanks. We will forward this to the developers. Best regards, DS


---
Internal tracking ID: [EXPOSUREAPP-5100](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5100)
Corona-Warn-App Open Source Team

**Comment by ndegendogo** [comment]
As far as I see, this is meanwhile fixed on branch release/1.13.x 😀

**Comment by dsarkar** [comment]
@ndegendogo, 
Your info has been forwarded to the developers´s ticket. Thanks!
