### ISSUE TITLE
FYI Release 1.13

### ISSUE THREAD

**Issue by dsarkar** [corona-warn-app/cwa-app-ios#1984]
See 
https://github.com/corona-warn-app/cwa-app-ios/releases

https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v1.13.0-RC1
https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v1.13.0-RC2
https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v1.13.0-RC3
https://www.coronawarn.app/en/blog/2021-02-26-corona-warn-app-1-13-announcement/

---

[EXPOSUREAPP-4879](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4879)

**Comment by Ein-Tim** [comment]
Thanks @dsarkar.
Any ETA that you can share? 🙂

**Comment by dsarkar** [comment]
@Ein-Tim No ETA, however, maybe extrapolating the dates of the last releases to the future gives you a hint, not more than that. ;-) Having said that, there are several variables (e.g. many parties involved) that might speed up or delay a release.

**Comment by Ein-Tim** [comment]
O/T @dsarkar 

Could you maybe close the issues labeled as `ready to close` (seems like the ppl who opened the issues are not going to close them)?
I think this would help to keep a better overview and also, it's better to distinguish between active and resolved issues (especially if we maybe get new issues related to the 1.13 release soon).

Thank you and sorry for the comment here (:

**Comment by dsarkar** [comment]
@Ein-Tim Sure! FYI https://www.coronawarn.app/en/blog/2021-02-26-corona-warn-app-1-13-announcement/

**Comment by Ein-Tim** [comment]
@dsarkar 

Since version 1.13 has been released now I think it would make sense to close this, or?

**Comment by dsarkar** [comment]
@Ein-Tim Sure.

**Comment by Ein-Tim** [comment]
@dsarkar Maybe you could also unpin it 😁

Thanks and have a nice evening.

**Comment by dsarkar** [comment]
@Ein-Tim Right!
