### ISSUE TITLE
FYI Release 2.0

### ISSUE THREAD

**Issue by dsarkar** [corona-warn-app/cwa-app-ios#1992]
see https://github.com/corona-warn-app/cwa-documentation/issues/544#issue-827350993

**Comment by dsarkar** [comment]
Release 1.13
---

See
https://github.com/corona-warn-app/cwa-app-ios/releases

https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v1.13.0-RC1
https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v1.13.0-RC2
https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v1.13.0-RC3
https://www.coronawarn.app/en/blog/2021-02-26-corona-warn-app-1-13-announcement/

EXPOSUREAPP-4879

**Comment by Ein-Tim** [comment]
Good morning @dsarkar 

You could update the title here since 1.14 has been released yesterday. You could also remove the links to 1.14, if you want (-:

**Comment by dsarkar** [comment]
@Ein-Tim Done!

**Comment by Ein-Tim** [comment]
@dsarkar 

Feel free to update this here too. (:

**Comment by Ein-Tim** [comment]
Version 2.0 has been released. I'd suggest to update this issue accordingly (either close it or inform about version 2.1 & 2.2)
