### ISSUE TITLE
Reactivation of Risk Determination

### ISSUE THREAD

**Issue by BlancoDeMallloca** [corona-warn-app/cwa-app-ios#1997]
## Avoid duplicates

* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is not already reported in another issue

## Technical details

- Device name:  iPhone XS
- iOS Version: 14.4
- App Version: 1.12.1

## Describe the bug

After iOS reinstallation the App gets stuck in a vicious circle when trying to reactivate Risk Determination (please see steps below)

## Steps to reproduce the issue

- press button "Risiko-Ermittlung aktivieren" (after App start)
![IMG_1837](https://user-images.githubusercontent.com/63304769/108073752-b0cbfb80-7068-11eb-9b30-9517dd22ab8b.jpg)
- press button "Geräte-Einstellungen öffnen"
![IMG_1838](https://user-images.githubusercontent.com/63304769/108073796-be818100-7068-11eb-880a-184386e840c4.jpg)

-> this sends you to the setting of the app, No possibility to activate "Risiko-Ermittlung"

other way:
- open iPhone settings
- go to "Begegnungsmitteilungen
![IMG_1839](https://user-images.githubusercontent.com/63304769/108073982-f688c400-7068-11eb-8ead-4cfdfb397fb0.jpg)
- press button "Begegnungsmitteilungen aktivieren"
![IMG_1840](https://user-images.githubusercontent.com/63304769/108074098-1d46fa80-7069-11eb-91d2-2d470ff7f66a.jpg)
- Choose country "Deutschland" in step 2
![IMG_1841](https://user-images.githubusercontent.com/63304769/108074156-2afc8000-7069-11eb-8568-1953eac9e641.jpg)
-> this sends you to the AppStore, because there is a App for your region, No possibility to activate "Risiko-Ermittlung"

## Expected behaviour

Reactivation of Risk Determination should be possible either via app or via iPhone settings

---
Internal Tracking ID: [EXPOSUREAPP-5224](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5224)

**Comment by Ein-Tim** [comment]
@BlancoDeMallloca 

Did you delete the App and reinstalled it? Seems like the ENF does not notice that the app was installed.

**Comment by BlancoDeMallloca** [comment]
Thank you very much for the fast response.

Yes I needed to restore my iPhone from backup due to other iPhone issues. 

Tried to delete/reinstall the app with and without restart of the iPhone in several steps of the delete/installation process. Unfortunately none of it solved issue

**Comment by Ein-Tim** [comment]
Okay thank you for the information. 

@thomasaugsten any idea how to quickly fix this?

**Comment by Ein-Tim** [comment]
@BlancoDeMallloca 

I don't expect this to fix it but give it a try: 

Reset the app inside of the App:

"Einstellungen" -> "Anwendung zurücksetzten"

**Comment by dsarkar** [comment]
@BlancoDeMallloca Not as a solution, but as part of the fault analysis: Are you able to install and get running another COVID-App, i.e. the Spanish CovidRadar or the Italian Immuni app?

**Comment by BlancoDeMallloca** [comment]
> Reset the app inside of the App:
> 
> "Einstellungen" -> "Anwendung zurücksetzten"

As you expected, this did not solve the problem. This only prompted again the initial setup of the app.

**Comment by BlancoDeMallloca** [comment]
> @BlancoDeMallloca Thanks for reporting. Not as a solution, but as part of the fault analysis: Are you able to install and get running another COVID-App, i.e. the Spanish CovidRadar or the Italian Immuni app?

I installed the Spanish, the Italian and also the US NY app. 
Unfortunately I can not enable exposure notifications in any app. So may this seems to be an issue related to iOS. I tried to find a solution to reset Exposure Notification API but did not find anything

**Comment by Ein-Tim** [comment]
I will try to reproduce this on an iPhone 6s.

**Comment by Ein-Tim** [comment]
@BlancoDeMallloca Did you back your phone up vie iTunes or did you do a iCloud backup?

**Comment by BlancoDeMallloca** [comment]
via the iCloud backup after a factory reset to delete all data and settings

**Comment by Ein-Tim** [comment]
Okay thanks, I'll try to reproduce this now.

**Comment by Ein-Tim** [comment]
Not at all reproducible on my iPhone 6s running a beta version of iOS 14.5 (18E5140k).

**Comment by BlancoDeMallloca** [comment]
Mmh. May iOS 15.5 will fix this issue. 

May I ask you to turn of "Begegnungsmitteilungen" and reactivate it after few minutes? May this will reproduce the issue

**Comment by Ein-Tim** [comment]
Done. Still no issue. @dsarkar Somebody should try to reproduce this on a device running iOS 14.4.

**Comment by Ein-Tim** [comment]
@BlancoDeMallloca Could you please try this: https://www.coronawarn.app/de/faq/#ios_black_screen

**Comment by jucktnich** [comment]
I know someone with the same issue. He transferred his data from an iPhone 6s to an iPhone 12 mini. The Apple support couldn't help, there where no hardware errors. The iOS log was transferred to apple, hopefully apple found the problem.

**Comment by Ein-Tim** [comment]
@jucktnich Thanks for this report. Let's hope iOS 14.5 fixes this. @thomasaugsten do you want to further investigate this?

**Comment by dsarkar** [comment]
@BlancoDeMallloca @Ein-Tim @jucktnich 
I will create an internal ticket.

**Comment by BlancoDeMallloca** [comment]
> @BlancoDeMallloca Could you please try this: https://www.coronawarn.app/de/faq/#ios_black_screen

To be honest. I do not want to perform this reset. This would cause that I need to set all settings for all apps again. Sorry this is to much effort to be spent just to solve the Warnapp issue.

**Comment by BlancoDeMallloca** [comment]
Thanks for your support @all

**Comment by dsarkar** [comment]
@BlancoDeMallloca @Ein-Tim 
Thanks for reporting and analyzing. Internal Tracking ID: [EXPOSUREAPP-5224](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5224). Any news on this issue will be published here. Thanks, best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@BlancoDeMallloca 

Did you update to iOS 14.4.1 and CWA version 1.14.4?

**Comment by BlancoDeMallloca** [comment]
> @BlancoDeMallloca
> 
> Did you update to iOS 14.4.1 and CWA version 1.14.4?

Already updated iOS 14.4.1 and now downloaded the CWA again. 

Still CWA sends me to iPhone settings and the settings App states that there is a app for my region. Issue is not solved for yet.

**Comment by Ein-Tim** [comment]
@BlancoDeMallloca 

Sad... Let's wait for iOS 14.5, hopefully it'll fix this issue.

**Comment by Ein-Tim** [comment]
For another report from @UlliKu, please see #2550.

Are there any news on this issue?

**Comment by Ein-Tim** [comment]
@BlancoDeMallloca (and @UlliKu)

Could you please update to iOS 14.5?

**Comment by BlancoDeMallloca** [comment]
Hi @Ein-Tim,
Thanks for the reminder. 
Updated iOS to 14.5 yesterday but forgot to download and test the CWA. Sorry my fault 🤦‍♂️ 
CWA still sends me to iOS settings. And iOS settings still says there is an app for your region. Sorry no progress yet.

**Comment by Ein-Tim** [comment]
@BlancoDeMallloca 

Okay, @thomasaugsten was this reported to Apple already?

**Comment by jucktnich** [comment]
@Ein-Tim Apple should know that issue due to the chat with the support by my relative... But maybe it got lost on the way to the apple developers... He didn't got any answers.

**Comment by UlliKu** [comment]
Ich kann das „Grün“ der Kontaktermittlung kurz sehen (wenn man keinen Coronakontskt hat ist es grün). Dann springt das Bild um und es heißt die Kontaktermittlung ist deaktiviert.

**Comment by Ein-Tim** [comment]
@UlliKu 

Okay danke. Wann hat das Problem bei dir eigentlich begonnen? Bei @BlancoDeMallloca war es nach einem Backup, war das bei dir auch so?

**Comment by jucktnich** [comment]
@Ein-Tim In my relatives case it was after changing the phone with quick start. Ps.: He had deactivated Exposure Notification on his old phone due to the bad battery healthy of the phone.

**Comment by UlliKu** [comment]
KP, ist praktisch 8-12 Wochen  nach WarnApp Veröffentlichung entstanden.  Bestimmt schon 6-8 Monate. Besonders ärgerlich: ich bin beruflich sehr viel unterwegs, jeden Tag woanders. Ich bin ein Superspreader wenn es mich erwischt, und ich könnte keinen warnen🤔

**Comment by Ein-Tim** [comment]
@UlliKu 

So lange hast du das Problem schon?!
Das ist wirklich sehr doof, Apple müsste sich das mal anschauen...

**Comment by BlancoDeMallloca** [comment]
> KP, ist praktisch 8-12 Wochen nach WarnApp Veröffentlichung entstanden. Bestimmt schon 6-8 Monate. Besonders ärgerlich: ich bin beruflich sehr viel unterwegs, jeden Tag woanders. Ich bin ein Superspreader wenn es mich erwischt, und ich könnte keinen warnen🤔

Bei mir ist es leider auch schon seit September 2020

**Comment by Ein-Tim** [comment]
@dsarkar 

Could you let us know if this has been reported to Apple? And if yes what is the current status of the report/request?

**Comment by UlliKu** [comment]
Ich weiß nicht wie man das an Apple meldet. Bin User.😬

**Comment by Ein-Tim** [comment]
@UlliKu 

This definitely has to be done by the developers, we will keep you up to date. 👍

**Comment by Ein-Tim** [comment]
@BlancoDeMallloca Maybe you would like to try what @thomasaugsten added to the OP of this issue: https://github.com/corona-warn-app/cwa-app-ios/issues/911#issue-657567065

Download the profile and follow the steps described there.
Maybe this'll fix it.

@thomasaugsten Is it still safe to use the profile you shared back there?

**Comment by thomasaugsten** [comment]
Im not sure maybe this profile is expired. 
What happens after deleteing the app. Restart the phone and reinstall the app?

**Comment by jucktnich** [comment]
I tried to activate exposure notification on the iPhone, and it worked. I dunno why it worked, I just tried to activate it, when I got the iPhone in my hands. It was approx a bimonthly rhythm. Maybe it was caused by the update to iOS 14.6 or even 14.5, hopefully this update fixed it for all.

**Comment by Ein-Tim** [comment]
@BlancoDeMallloca Could you try if it works for you too with the latest iOS version (14.6)?

**Comment by BlancoDeMallloca** [comment]
Wow. Seems to work right now. Well done folks. 

I will test it the upcoming days.

**Comment by BlancoDeMallloca** [comment]
Still working. 

Thank you 🙏

**Comment by Ein-Tim** [comment]
Nice @BlancoDeMallloca!

I'd consider this as fixed now, so feel free to close this issue. 

Have a nice Sunday evening.

**Comment by BlancoDeMallloca** [comment]
Thanks again

**Comment by dsarkar** [comment]
@BlancoDeMallloca Thanks for contributing here! Best, DS 

---
Corona-Warn-App Open Source Team
