### ISSUE TITLE
Make sure all EN-Erros link to the FAQ page correctly

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#1998]
## Avoid duplicates

* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: -
- iOS Version: 14.4
- App Version: 1.12.1

## Describe the bug

I have some [indication](https://twitter.com/padeluun/status/1361696623638831108?s=20) that ENError-Pop ups do **not** correctly link to the `General_moreInfo_URL` defined in https://github.com/corona-warn-app/cwa-app-ios/blob/11e3e101ba3e52f3ad8321ce5d3ded642960f4ca/src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.links.strings#L13

Instead, if the user clicks "Mehr Erfahren", nothing happens but the pop-up closes. I can't confirm this myself, since it is not easy to reproduce such errors.
I think that this does not affect, the separately defined, ENErrors 5, 11 and 13.

## Steps to reproduce the issue

1. Get a ENError (but 5, 11 and 13)
2. Click on "Mehr Erfahren"
3. Pop-Up closes
4. Nothing happens

## Expected behaviour

The FAQ website should be opened.

---

## Related Issue

- #1353 

---
Internal Tracking ID: [EXPOSUREAPP-5223](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5223)

**Comment by ndegendogo** [comment]
@Ein-Tim did you actually see this popup? If yes: do you know if the corresponding risk check was triggered from background or foreground?

**Comment by Ein-Tim** [comment]
@ndegendogo 

I don't experience this issue, I just talked with somebody on Twitter who encountered ENError 14.

But I also [noticed](https://github.com/corona-warn-app/cwa-app-ios/issues/1353#issuecomment-764671747)
back in #1353 that I think that it is (still) not working.

**Comment by ndegendogo** [comment]
Thanks @Ein-Tim.
*I cannot promise for sure, but if I find time I am going to play with this scenario in my simulator ...*

**Comment by dsarkar** [comment]
@ndegendogo @Ein-Tim 
Do you have any idea how to trigger one of the ENErrors?

**Comment by Ein-Tim** [comment]
@dsarkar ENError 14 is triggered if a MDM is preventing CWA to use the ENF/the ENF is deactivated by a MDM.

But it's all a bit tricky because some ENErorrs are also hidden from the user, others aren't but the most common (13, 11 and 5) seem to work correctly (but not sure about that).

**Comment by dsarkar** [comment]
@Ein-Tim  Ok. ENError13 ( API was called too often ), I think one could trigger it: At the end of the day, after 4-6 checks, reset app several times (or re-install). So we could check at least that one.

**Comment by Ein-Tim** [comment]
@dsarkar Yes, I triggered this yesterday and it seemed to work. It's only about the Erros which don't have a own FAQ entry. This should best be tried out by the devs.

**Comment by dsarkar** [comment]
@Ein-Tim ok

**Comment by ndegendogo** [comment]
@dsarkar I plan to use the simulator / community build, then cherry-pick my recent PR for #1918, and do a local modification so that the mock returns error 14
😎😎

**Comment by ndegendogo** [comment]
I can reproduce it with 1.12.1. 
ENError 13 forwards to the FAQ, ENError 14 shows no action on "more info".

Root cause is [here](https://github.com/corona-warn-app/cwa-app-ios/blob/e9f999303c5d74499e04defabf04ff426416aa6c/src/xcode/ENA/ENA/Source/Extensions/Error%2BFAQUrl.swift#L35). Three specific error codes are extended with an URL to the FAQ, but the default gets no URL.

I guess it should use [one of the other URLs here](https://github.com/corona-warn-app/cwa-app-ios/blob/e9f999303c5d74499e04defabf04ff426416aa6c/src/xcode/ENA/ENA/Source/View%20Helpers/AppStrings.swift#L38), else the list of URLs to be extended.

@dsarkar

**Comment by dsarkar** [comment]
@ndegendogo @Ein-Tim Thanks for reporting and analyzing!


Internal Tracking ID: [EXPOSUREAPP-5223](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5223)

**Comment by ndegendogo** [comment]
@dsarkar please ask the devs what is the fastest way to get this fix in.
If they have time to work on it I guess this would be fastest.
Else I could volunteer for a PR; but of course I don't want to spend duplicate effort.

**Comment by dsarkar** [comment]
@ndegendogo  They are working already on it as far as I can see in the ticket. However, I will forward your generous offer and suggest the developer contacting you here on this issue if this is applicable and/or practical for the devs.

**Comment by dsarkar** [comment]
@ndegendogo @Ein-Tim FYI PR https://github.com/corona-warn-app/cwa-app-ios/pull/2024/files

**Comment by Ein-Tim** [comment]
@dsarkar Thanks! 

@ndegendogo I will leave this issue open until Version 1.13 is released, maybe you would like to test this via the emulator again then? Thank you so much for you help here! 👍

**Comment by ndegendogo** [comment]
Wow - this is fast 🚀 amazing 😀

@dsarkar **Please tell the devs!**

*But then ... I have another question - not sure if I should open a new ticket or can just append here?*

Actually, in the same file there is another, very similar extension `ExposureSubmissionError` and I am wondering if that should be also extended with a default URL.
However, so far I have not analysed its usage (from the name it could be related to submission of DEK keys)

@dsarkar could you please give the developers the hint to double-check that?

*(sorry - I should have mentioned it in the first place ... but it was already a bit late yesterday ...)*

**Comment by heinezen** [comment]
@ndegendogo

From the perspective of the FAQ it's not necessary to make an FAQ entry for every error type. In general, these errors should be caught and handled internally (e.g. try again in case of submission). Most of them are not meant to be shown to the user. And if they are, the app should show it's own user-friendly error message.

If the error is still shown to a lot of users, we will make an FAQ entry of course. However, chances are we are mirroring the Apple FAQ's if we do this preemptively for every error.

----
Corona-Warn-App Open Source Team

**Comment by ndegendogo** [comment]
@heinezen no problem. I have meanwhile analysed the source myself, and as far as I see all is fine.

ExposureSubmissionCoordinator.showErrorAlert adds the 'More Info' button [only if the error has an URL](https://github.com/corona-warn-app/cwa-app-ios/blob/cdce0e8e8625b4b4b6bd83cd4b961a25c4a74a7c/src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift#L684), so the user gets the popup with just one button in the 'default' case, which is fine.

This is different with AppDelegate.makeAlertController, which **always** adds [a second button](https://github.com/corona-warn-app/cwa-app-ios/blob/cdce0e8e8625b4b4b6bd83cd4b961a25c4a74a7c/src/xcode/ENA/ENA/Source/AppDelegate%20%26%20Globals/AppDelegate.swift#L411). 

*(And a button which promises 'More info' but does not fulfill this promise is at least surprising.)*

**Comment by dsarkar** [comment]
@ndegendogo regarding your comment https://github.com/corona-warn-app/cwa-app-ios/issues/1998#issuecomment-781633712, I forwarded both, your question and your amazement to the developer.

**Comment by freshking** [comment]
> @heinezen no problem. I have meanwhile analysed the source myself, and as far as I see all is fine.
> 
> ExposureSubmissionCoordinator.showErrorAlert adds the 'More Info' button [only if the error has an URL](https://github.com/corona-warn-app/cwa-app-ios/blob/cdce0e8e8625b4b4b6bd83cd4b961a25c4a74a7c/src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift#L684), so the user gets the popup with just one button in the 'default' case, which is fine.
> 
> This is different with AppDelegate.makeAlertController, which **always** adds [a second button](https://github.com/corona-warn-app/cwa-app-ios/blob/cdce0e8e8625b4b4b6bd83cd4b961a25c4a74a7c/src/xcode/ENA/ENA/Source/AppDelegate%20%26%20Globals/AppDelegate.swift#L411).
> 
> _(And a button which promises 'More info' but does not fulfill this promise is at least surprising.)_

@ndegendogo This is the correct answer to your question about the `ExposureSubmissionError`.

**Comment by Ein-Tim** [comment]
Version 1.13 which fixed this has been released to GitHub and will be available to all users in the next 48h.

See blog post:

DE: https://www.coronawarn.app/de/blog/2021-03-04-corona-warn-app-version-1-13/
EN: https://www.coronawarn.app/en/blog/2021-03-04-corona-warn-app-version-1-13/

See GitHub release:

iOS: https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v1.13.0
Android: https://github.com/corona-warn-app/cwa-app-android/releases/tag/v1.13.2

This issue will now be closed.

**Comment by dsarkar** [comment]
@Ein-Tim  Thanks!
