### ISSUE TITLE
Version 1.12.1 (0)

### ISSUE THREAD

**Issue by stefan-123456** [corona-warn-app/cwa-app-ios#2030]
## Avoid duplicates

* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 11
- iOS Version:14.4
- App Version: 1.12.1(0)

## Describe the bug

hello. This is similar as 1715 that you closed a week ago. 

I have the following error messsge on 1.12.1(0) 

see screenshot 

## Steps to reproduce the issue

I just start the app 
-->

## Additional context

hello. This is similar as 1715 that you closed a week ago. 

I have the following error messsge on 1.12.1(0) 

see screenshot 

![1A6E5E8A-8C8F-45AD-895F-CBF9C4B74FF2](https://user-images.githubusercontent.com/79279110/108405723-bc165700-7221-11eb-86f2-85ad65702695.png)

**Comment by Ein-Tim** [comment]
Hey @stefan-123456 

As you can see in #1715 and also if you click on "Mehr Erfahren" in the pop-up, you can ignore this message. It will be gone after 24h.

**Comment by stefan-123456** [comment]
Thanks Tim. This is not a normal behavior (error-13) though and if known since exactly 2 months (anything special since to happen on the 18th) it should be fixed

**Comment by Ein-Tim** [comment]
@stefan-123456 

This is a rare case that can happen in the version 2 of the Exposure Notification Framework, the API used by Corona-Warn-App. 
There is sadly nothing the developers can do about it...

**Comment by Ein-Tim** [comment]
@stefan-123456 

Did you update from a version below 1.9 (like 1.5/1.6/etc.) to 1.12?

**Comment by stefan-123456** [comment]
Hello Tim. No, updates on my iPhone are automatic so I believe it updated from the previous version.

**Comment by stefan-123456** [comment]
Hi Tim. I fixed it. I pressed the “diagnose in corona warn app Teilen and it now works 🤔

![FD1285D4-EBD4-4B04-8E09-F1E2C157C671](https://user-images.githubusercontent.com/79279110/108417099-d9522200-722f-11eb-8ff9-8864aad8f0ec.png)
![A1E270C7-2D30-4DA6-8CC0-EE764CA6BDB8](https://user-images.githubusercontent.com/79279110/108417108-dbb47c00-722f-11eb-8a1c-9120083dd86a.png)

**Comment by Ein-Tim** [comment]
@stefan-123456 

Okay, as Said before this is a rare case this can happen sometimes. AFAIK the devs can't do anything about it. 

If you're happy with the answer please close this issue. Thanks!

**Comment by dsarkar** [comment]
@stefan-123456 Thanks for reporting.
@Ein-Tim Thanks for assisting.

Most probably, as stated by @Ein-Tim, this happened in the context of a CWA update. It is not critical and should go back to normal after 24 h on its own.
