### ISSUE TITLE
Explain the `update os` screen more 

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#2045]
## Avoid duplicates

* [x] This issue has not already been raised before
* [x] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation
Version 1.12.1 introduced an `update os` screen, which is shown to users on iOS 13 versions below 13.7.

At the moment, this screen only says: 

>Please update your iOS.
You need the current iOS version to install the Corona-Warn-App. To do so, open the settings in your iPhone and select General -> Software Update.

## Suggested Enhancement

Add a link to a FAQ entry (for example: https://www.coronawarn.app/en/faq/#ios135) to give the user an explanation why this is needed. 

## Expected Benefits
More user really updating their iOS version and not just uninstalling CWA (when reading the comments on the App Store, it seems like the most users will just delete the app). 

---

## Related Issues

- #2032
- https://github.com/corona-warn-app/cwa-website/issues/905

 
---
Internal Tracking ID: [EXPOSUREAPP-5275](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5275)

**Comment by heinezen** [comment]
@Ein-Tim 

Thank you! I've forwarded the suggestion to the devs. We'll see what we can do about it.

----
Corona-Warn-App Open Source Team

**Comment by ndegendogo** [comment]
There are more suggestions what should be shown on this screen to mitigate the fact / decision that cwa has dropped support for ENF v1 and for the affected iOS versions:
* a link to list of other European corona warning apps, which could be an alternative for a user who does not want to upgrade iOS
* a hint that not all these apps exchange keys with every other country, and most don't accept infection reported from another country.

See the discussion at https://github.com/corona-warn-app/cwa-app-ios/issues/2032 , especially [this comment](https://github.com/corona-warn-app/cwa-app-ios/issues/2032#issuecomment-787415627) and [this.](https://github.com/corona-warn-app/cwa-app-ios/issues/2032#issuecomment-787414454)

**Comment by dsarkar** [comment]
@ndegendogo ok, ticket updated.

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-5275](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5275)

**Comment by Ein-Tim** [comment]
There's now a FAQ entry which could be linked to from this screen:

https://www.coronawarn.app/de/faq/#update_iOS
or
https://www.coronawarn.app/en/faq/#update_iOS

**Comment by Ein-Tim** [comment]
I consider this issue as obsolete since the most people who were seeing the `update os` screen most likely uninstalled the app or updated to a supported iOS version.

Therefore I'm closing this issue now.
