### ISSUE TITLE
[BSI][20210225] Contact Diary Store Key Not Regenerated After Reset

### ISSUE THREAD

**Issue by BSI-TF-CWA** [corona-warn-app/cwa-app-ios#2084]
Rating: Low

Description:
When resetting the iOS app the Contact Diary database is cleaned up by removing all items in the database. The en- cryption key that is used to encrypt the Contact Diary database is not removed from the keychain.
When the app restarts following a reset, it checks whether a ContactDiaryStoreEncryptionKey exists within the device’s keychain. If it does exist, the app takes this key to encrypt the Contact Diary store.
This results in every Contact Diary created on a particular device to be encrypted with the same encryption key.
A user passing on a device to another person could, for example, insert a crafted encryption key in the keychain. Even if the CWA app is not installed on the device, the keychain entry can still exist. If the receiving person then installs the app, without resetting the whole phone, the CWA app will then use an encryption key that is known to the initial owner of the device.

The code snippet below, taken from src/.../ContactDiaryStore.swift shows that on creation of the Contact Diary database, the keychain is queried to check whether it already contains a ContactDiaryStoreEncryptionKey.

<img width="702" alt="PoC_ContactDiary" src="https://user-images.githubusercontent.com/65443025/109140053-7f37ec00-775c-11eb-8dc2-ba26dfc5baed.png">

Recommended controls:
When resetting the app, not only the content of the Contact Diary, but also the encryption key should be deleted. The app already does that for the secureStore database. The removal of the Contact Diary could be implemented similar to how it is implemented in the case of the secureStore database.

---
Internal Tracking ID: [EXPOSUREAPP-5384](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5384)

**Comment by jjc-mueller** [comment]
Planned for Version 2.0 (16.04.2021)

**Comment by Ein-Tim** [comment]
PR #2330

**Comment by Ein-Tim** [comment]
Version 2.0 which fixed this has been released to GitHub and is available to all users in the next 48h. 

See blog post: 

DE: https://www.coronawarn.app/de/blog/2021-04-21-corona-warn-app-version-2-0/
EN: https://www.coronawarn.app/en/blog/2021-04-21-corona-warn-app-version-2-0/

See GitHub release:

iOS: https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v2.0.3

This issue should now be closed if the fix is working.

**Comment by dsarkar** [comment]
@Ein-Tim @BSI-TF-CWA  Thanks. Fixed with Release 2.0, see PR above.


---
Corona-Warn-App Open Source Team
