### ISSUE TITLE
Positive Test stays in App

### ISSUE THREAD

**Issue by blockiyt** [corona-warn-app/cwa-app-ios#2125]
## Avoid duplicates

* [ yes, I think] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ yes, I think also] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 8
- iOS Version: 14.4
- App Version: 1.12.1

## Describe the bug

I have an Positive test in my App, and my Quarantine is now over and I am testet negative. I can't remove the test to put In my new test because it stays on Thanks for Your Help!

## Steps to reproduce the issue

Be Corona positive and scan your test and share the warning with others.

## Expected behaviour

There should be a Button where you can remove the test if your quarantine is over.
It could also be a Timer for 14 Days but idk if this is a function or so.

## Possible Fix

Put a Button to remove the test or out a 14 Days timer in to show then a Button to remove the test

## Additional context

https://user-images.githubusercontent.com/65811753/109712232-13acaf00-7ba0-11eb-97fa-69b4d9b810c8.mov

**Comment by Ein-Tim** [comment]
Hey @blockiyt 👋

This is currently the intended behavior, the app does not automatically delete the test result after 14 days. 
You can find out how to continue in this FAQ entry: https://www.coronawarn.app/en/faq/#recovered

The behavior after reporting an infection will be heavily improved in the next release (version 1.13): 
https://github.com/corona-warn-app/cwa-app-ios/pull/1960

If you're happy with the answer, please close this issue. 

Thanks, have a good night and stay safe!

**Comment by blockiyt** [comment]
Thank you @Ein-Tim!
 
Now I resetted the App and everything works fine!

Have also a good night and stay safe!

**Comment by dsarkar** [comment]
@Ein-Tim Thanks!
