### ISSUE TITLE
[Discussion] Not enough space for an iOS update

### ISSUE THREAD

**Issue by dsarkar** [corona-warn-app/cwa-app-ios#2126]
I need more space for an iOS update
---

Some iPhone users have reported that they can't update to the latest iOS version since there is not enough space on their iPhone. In particular, older iPhone models might be affected.

The device manufacturer provides some advice, e.g., see these links:

- [If you need more space for an update](https://support.apple.com/en-gb/HT203097)
- [Wenn Sie für ein Update mehr Speicherplatz benötigen](https://support.apple.com/de-de/HT203097)
- [Apple community: Not enough memory to update](https://discussions.apple.com/thread/7841473)

[iOS 14.4](https://support.apple.com/en-gb/guide/iphone/iphe3fa5df43/14.0/ios/14.0) is supported on the following  models:
---

- iPhone SE (1st generation)
- iPhone SE (2nd generation)
- iPhone 6s
- iPhone 6s Plus
- iPhone 7
- iPhone 7 Plus
- iPhone 8
- iPhone 8 Plus
- and newer models X, 11, and 12 and their variants

[iOS 12.5](https://support.apple.com/en-gb/guide/iphone/iphe3fa5df43/12.0/ios/12.0) is supported on the following models:
---
- iPhone SE
- iPhone 5s
- iPhone 6
- iPhone 6 Plus
- and newer models 6, 7, 8, X and their variants.

**Comment by Ein-Tim** [comment]
@dsarkar 

I think in the Apple support article, the second point (updating via iTunes) is from a high value. 
AFAIK iTunes downloads all files on the disk from the PC/Mac and thus this method doesn't need any free space on the phone. 
The only negative thing here is that probably not so many normal users have iTunes installed on their Windows machine. 
Macs are different since iTunes is better integrated into the OS there.

**Comment by jucktnich** [comment]
You can also auslagern (what's the name in English?) some apps, update the os and download the app again. The user data won't be lost. You'll also get a message from the os to do so, if you don't have enough free space.

**Comment by Ein-Tim** [comment]
@jucktnich 

It's called "Offload". More infos here: https://support.apple.com/en-us/HT203097

**Comment by Ein-Tim** [comment]
@dsarkar Do you need this issue open or can it be closed?

**Comment by dsarkar** [comment]
@Ein-Tim I think at this stage we can close this. If necessary we could create a FAQ article, however, for the moment it does not seem necessary.
