### ISSUE TITLE
Icon of „Share Data“ menu in settings looks strange in dark mode

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#2142]
## Avoid duplicates

* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: /
- iOS Version: /
- App Version: 1.13.0

## Describe the bug

The icon from the "Share Data" menu in the settings is darker than the other icons. This only affects dark mode.

<img src="https://user-images.githubusercontent.com/67682506/110075625-62666e80-7d83-11eb-84bd-207d6f1b57ee.jpeg" width="300">

## Steps to reproduce the issue

1. Activate dark mode 
2. Open CWA
3. Scroll down to "Settings"
4. Click on "Settings" 
5. See strange icon from "Share Data"

## Expected behaviour

Icon should match the brightness of the other icons.

## Additional context

Please check the behavior under Android and move to the documentation repo if necessary.

#### Fix in PR: #2066

---
Internal Tracking ID: [EXPOSUREAPP-5553](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5553)

**Comment by dsarkar** [comment]
@Ein-Tim Thanks. EXPOSUREAPP-5553.

**Comment by dsarkar** [comment]
EXPOSUREAPP-5179

**Comment by dsarkar** [comment]
@Ein-Tim FYI https://github.com/corona-warn-app/cwa-app-ios/pull/2066

**Comment by Ein-Tim** [comment]
Thanks @dsarkar 
I forgot this PR 😅

Do you want this issue to stay open? Because I don't need it open, so feel free to close it.

**Comment by dsarkar** [comment]
@Ein-Tim I suggest keeping it open until 1.14 is released.

**Comment by Ein-Tim** [comment]
Version 1.14 which fixed this has been released to GitHub and is available to all users in the next 48h.

See blog post:

DE: www.coronawarn.app/de/blog/2021-03-09-corona-warn-app-version-1-14
EN: www.coronawarn.app/en/blog/2021-03-04-corona-warn-app-version-1-14

See GitHub release:

https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v1.14.3

This issue will now be closed.

**Comment by dsarkar** [comment]
@Ein-Tim Thanks.
