### ISSUE TITLE
Clicking on icon on the tab bar should bring to the top

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#2156]
## Avoid duplicates
* [X] This issue has not already been raised before
* [ ] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation
Clicking on for example the "Start Screen" icon on the tab bar does nothing if the start screen is already opened. Even if the user is on the very bottom of the start screen, nothing happens.

## Suggested Enhancement
Scroll to the top of the screen.
Native iOS Apps (try i.e. the App Store or Photos) are scrolling back to the top if the user is clicking on the icon from the currently opened menu on the tab bar.

## Expected Benefits
Consistency with other and mainly the native iOS Apps.

---

## Related Issue

- #2159 

---
Internal Tracking ID: [EXPOSUREAPP-5572](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5572)

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-5572](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5572)

**Comment by Ein-Tim** [comment]
Just to follow up here:

Although I didn't consider this as a bug, some users might think it's a bug. I really hope that one of the devs is on this, since iOS wide I didn't found **a single** application which doesn't support this.
Is this a story in JIRA @dsarkar?

**Comment by dsarkar** [comment]
@Ein-Tim It is indeed, Internal Tracking ID: EXPOSUREAPP-5572 as a wishlist item. Considered to be a great addition, but right now, not in development. Currently prio high on wishlist (be aware, this might change.).

**Comment by tens0rfl0w** [comment]
@Ein-Tim @dsarkar Hey there! I checked the mentioned behavior on multiple views and can't reproduce it right now, seems fixed👍🏼

**Comment by fynngodau** [comment]
In Android, touching the Start Screen icon reloads the Start Screen, thereby jumping (not smooth scrolling) to the top. I can't tell to what extend this is intentional, but this is indeed the behavior I'd expect from a tab bar on Android.

**Comment by Ein-Tim** [comment]
@fynngodau 

Touching the icon on a tab bar should scroll to the top of the view. Additionally the view can be reloaded. 
This is the behavior of every single iOS app on my phone, native and third party ones. 
CWA is really an exception there.

**Comment by ndegendogo** [comment]
@Ein-Tim which behaviour do you suggest if it is inside a submenu?

Examples:
- App informations, or Settings from home tab (or even second level submenu)
- diary page for a single day from diary tab

Current behaviour as of cwa 2.7.2(0):
- if you tap the **current** tab bar icon while inside a submenu then it jumps to top level
- if you tap the **current** tab bar icon while on top level then nothing happens
- if you tap a **different** tab bar icon then it switches tab, but remembers the submenu

**Comment by Ein-Tim** [comment]
@ndegendogo 

If it's in a submenu, I think this would be the best behavior:
First Tab -> Close submenu
Second Tab -> Scroll to top

**Comment by ndegendogo** [comment]
> Second Tab -> Scroll to top

@Ein-Tim its still ambiguous 😅

Do you mean the **fourth** (not he second!) tab icon? => corresponding to the contact diary
Or do you mean a single-tap vs a double-tap gesture on the tab bar icon?

**Comment by Ein-Tim** [comment]
@ndegendogo 

Sorry for the confusion, I meant to write "tap" and not "tab" as in tab bar...

So if you, e.g. are in the submenu to create an event qr code and **tap** on the first **tab** once, the submenu closes. Then you're on the start screen again, but not on the top. When you now **tap** again on the first **tab** the view scrolls to the top.

Now a bit clearer?

**Comment by ndegendogo** [comment]
> Sorry for the confusion, I meant to write "tap" and not "tab" as in tab bar...

😅😅 no problem @Ein-Tim. I just want to be sure that I understand it correctly.

Try again with the contact diary, cwa as of 2.7.2 (0).

**Scenario-1:**
- I enter the submenu = page for today
- I scroll down through my loooong list to pick "Walter" 
- then I tap on the icon, and it closes the page and is back on top level. 
=> this is ok as desired.

**Scenario-2:**
- I scroll down to the entry of last week. Each day has many entries, so I am scrolling a lot.
- I add a person
- I press 'back' and am back on the top level, **but still down at last week**, and there is no short-cut, so I have to scroll up all the many entries of last week
=> this is what you are missing, right?

*I started to play with it and sent you a PM on Slack - please create a branch for a PR*

**Comment by Ein-Tim** [comment]
> his is what you are missing, right?

Yes, exactly!

> I started to play with it and sent you a PM on Slack - please create a branch for a PR

I've done this! See my message.

Thanks for your help!

**Comment by ndegendogo** [comment]
> So if you, e.g. are in the submenu to create an event qr code and tap on the first tab once, the submenu closes. Then you're on the start screen again, but not on the top. When you now tap again on the first tab the view scrolls to the top.

Yes, this makes sense.
I just checked the native HealthApp, they do it exactly that way.

**Comment by Ein-Tim** [comment]
FYI @ndegendogo has started to work on this and we (@ndegendogo and me) would offer to provide a PR for this. 
@dsarkar could you ask a dev if a PR from the community would be reviewed & accepted?

Thank you!

**Comment by Ein-Tim** [comment]
**Update:** PR #3411 was submitted to implement this.

**Comment by Ein-Tim** [comment]
#3411 was merged and the feature will be shipped with version 2.10. 🎉

**Comment by ndegendogo** [comment]
Our solution of PR #3411 has still a few issues:
1) it scrolls to the top, but does not reveal the large title
2) it would crash if it is used with an empty table or with an empty first section of such a table
3) it works only with embedded table views, but not with other scroll views

I have now found a better solution that addresses all three issues.
I will prepare another PR for that

**Comment by Ein-Tim** [comment]
@dsarkar / @heinezen 

Although @ndegendogo will further improve the behavior, the `Fix 2.10` label can already be applied here.

**Comment by ndegendogo** [comment]
PR #3475 submitted with the improvements and with unit tests.

@dsarkar @heinezen could you please apply the labels to this PR? - Thanks!

**Comment by Ein-Tim** [comment]
This has finally been **implemented** in version 2.10 by @ndegendogo! Thank you so much!

There is still one improvement to come in 2.11 (https://github.com/corona-warn-app/cwa-app-ios/pull/3475), still, this has basically been implemented.

Closing as implemented.

**Comment by dsarkar** [comment]
@ndegendogo @Ein-Tim and community: Many thanks for contributing.
