### ISSUE TITLE
Inconsistent & wrong behaviour of the button to reactivate exposure logging on the risk card in different scenarios

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#2157]
## Avoid duplicates

* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone XR / iPhone 6s 
- iOS Version: iOS 14.5 (Public Beta 2) / iOS 14.5 (Public Beta 3)
- App Version: 1.13.0 / 1.13.0

## Describe the bug

The button to reactivate exposure logging on the main risk card behaves inconsistently & wrong in different scenarios:

### Scenario 1 - Bluetooth deactivated:

a) Risk card on main screen:

https://user-images.githubusercontent.com/67682506/110162351-e6097500-7dee-11eb-817a-eab9f2551b74.mp4

Click on "Activate Exposure Logging" brings the user to the "Exposure Logging" screen.

b) After clicking on the risk card:

https://user-images.githubusercontent.com/67682506/110162566-31bc1e80-7def-11eb-9ddc-758216f27e33.mp4

Click on "Activate Exposure Logging" does **nothing**.

---

### Scenario 2 - "Exposure Logging" deactivated in app:

a) Risk card on main screen:

https://user-images.githubusercontent.com/67682506/110162977-ba3abf00-7def-11eb-9a22-93ee89d7e988.mp4

Click on "Activate Exposure Logging" brings the user to the "Exposure Logging" screen.

b) After clicking on the risk card:

https://user-images.githubusercontent.com/67682506/110163663-9d52bb80-7df0-11eb-8ddf-4d51e62c1291.mp4

Click on "Activate Exposure Logging" instantly activates Exposure Logging.

## Expected behaviour

Scenario 1: The buttons should do the same, regardless where they are pressed **and** the button on the risk detail screen (after clicking on the risk card) should do something.
Scenario 2: The buttons should do the same, regardless where they are pressed.

---

Scenario 1 fix: -

Scenario 2 fix: #2239 (version 2.0)

---
Internal Tracking ID: [EXPOSUREAPP-5579](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5579)
Internal Tracking ID: [EXPOSUREAPP-4954](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4954) related

**Comment by dsarkar** [comment]
@Ein-Tim Thanks. Internal Tracking ID: [EXPOSUREAPP-5579](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5579)

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-4954](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4954) related

**Comment by dsarkar** [comment]
PR https://github.com/corona-warn-app/cwa-app-ios/pull/2219

**Comment by Ein-Tim** [comment]
**Update**

The fix was **reverted** in #2236. 
@dsarkar Will they try to fix it again?

**Comment by dsarkar** [comment]
@Ein-Tim Thanks. Will check.

**Comment by Ein-Tim** [comment]
New fix seems to be in #2237.

**Comment by dsarkar** [comment]
Indeed.

**Comment by Ein-Tim** [comment]
#2237 was closed too. Let's wait and see 😃

**Comment by dsarkar** [comment]
PR https://github.com/corona-warn-app/cwa-app-ios/pull/2239

**Comment by Ein-Tim** [comment]
Version 2.0 which fixed this has been released to GitHub and is available to all users in the next 48h. 

See blog post: 

DE: https://www.coronawarn.app/de/blog/2021-04-21-corona-warn-app-version-2-0/
EN: https://www.coronawarn.app/en/blog/2021-04-21-corona-warn-app-version-2-0/

See GitHub release:

iOS: https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v2.0.3

This issue will now be closed.

**Comment by dsarkar** [comment]
@Ein-Tim Thanks.

---
Corona-Warn-App Open Source Team
