### ISSUE TITLE
Make tab bar translucent

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#2159]
## Avoid duplicates

* [x] This issue has not already been raised before
* [ ] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation
CWA tab bar is opaque (see @ndegendogo's findings [here](https://github.com/corona-warn-app/cwa-app-ios/issues/2159#issuecomment-792372404)).

## Suggested Enhancement
Make the tab bar translucent, like the tab bar from native Apple apps is (see f.e. Photos or App Store).

## Expected Benefits
Consistency with other and mainly the native iOS Apps. 
IMHO, this will also look more modern.

---

## Related Issue

- #2156

---
Internal Tracking ID: [EXPOSUREAPP-5612](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5612)

**Comment by ndegendogo** [comment]
@Ein-Tim what exactly do you mean with 'acrylic'?
*Just guessing:* Do you mean the color effect that iOS calls 'translucent'? ('translucent glas' = Milchglas). Not fully transparent, but a blurred image of the background, shining through a semi-transparent foreground?

iOS has many options to configure the appearance of the tab bar, [translucency](https://developer.apple.com/documentation/uikit/uitabbar/1623458-translucent) is one of them.

But: there might be a need to adapt your layout slightly when you switch your app from non-translucent bars to translucent bars; because the content that is very close to the edge of the screen can be hidden behind the bar and cannot be scrolled out.

**Comment by Ein-Tim** [comment]
@ndegendogo 

I was searching for this word (do you say this in English 😂)!
Yes, I mean translucent. 

> there might be a need to adapt your layout slightly when you switch your app from non-translucent bars to translucent bars; because the content that is very close to the edge of the screen can be hidden behind the bar and cannot be scrolled out.

Okay, thanks for this information. Do you have any guess how the Tabbar from CWA is configured?

**Comment by ndegendogo** [comment]
> I was searching for this word (do you say this in English 😂)!

@Ein-Tim I am not a native English speaker - I only [ask leo](https://dict.leo.org/englisch-deutsch/milchglas) 🙃

> any guess how the Tabbar from CWA is configured

I'll try to find out 😎

**Comment by Ein-Tim** [comment]
@ndegendogo 

> I'll try to find out 😎

Thanks! 😃

**Comment by ndegendogo** [comment]
@Ein-Tim you are right. The tab bar is opaque. Whereas the navigation bar at the top is translucent (you can see this if you scroll the green risk card up).
I add two screenshots how it would look like with a translucent tab bar.
![Simulator Screen Shot - iPhone 8 Plus - 2021-03-08 at 00 07 46](https://user-images.githubusercontent.com/6118267/110258526-52c57080-7fa3-11eb-88bd-fd5b37d0348f.png)
![Simulator Screen Shot - iPhone 8 Plus - 2021-03-08 at 00 08 56](https://user-images.githubusercontent.com/6118267/110258531-5e189c00-7fa3-11eb-963f-6cc25efd10dd.png)

**Comment by Ein-Tim** [comment]
@ndegendogo 

Thank you so much (and also for the screenshots)! 
I will rewrite this ticket so that it get's an enhancement request, since my question has been answered by you! 

Thanks again!

**Comment by Ein-Tim** [comment]
@dsarkar Changed to enhancement request, could you relabel it? Thanks!

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-5612](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5612)

**Comment by dsarkar** [comment]
@Ein-Tim Your link in your OP to related issue is the very same issue. I guess that is not your intention.

**Comment by Ein-Tim** [comment]
@dsarkar 

Thank's for the hint! Changed it. 
Have a good night.

**Comment by dsarkar** [comment]
@Ein-Tim Thanks for proposal.

@ndegendogo Thanks for contributions here. I understand that you have figured out already how to implement this story. Can I forward to the developers that you would provide information or even a PR in case this story is accepted?

Good night everybody!

**Comment by dsarkar** [comment]
@ndegendogo ok, got it, thanks. Will forward your comments on this issue to the developer's ticket.

**Comment by ndegendogo** [comment]
Just another thought on this ... you will also have to cover integration with the layout of your many parallel branches.
I have never worked with UI Tests; I have no idea how good they are to catch this type of integration issues (or how fragile they are for this kind of layout change). If you are lucky they can mitigate a lot. And of course this depends also on your test coverage of corner cases, like the last line in a table view.

**Comment by Ein-Tim** [comment]
I opened #2887 for this. Thank you for your help @ndegendogo!

**Comment by ndegendogo** [comment]
@Ein-Tim looks nice - I had just a look at your screenshots - and you even managed to keep the color of the icons! 👍😁

**Comment by Ein-Tim** [comment]
The change in my PR #2887 sadly didn't make it into 2.5, the change is not live. 

The definition for the tab bar color is still in the code:
https://github.com/corona-warn-app/cwa-app-ios/blob/8c14cecc01b682510a4f57b837f6d374d9411836/src/xcode/ENA/ENA/Source/RootCoordinator.swift#L137

@dsarkar Could you let me know if it was intended to revert my change (because there were issues with it) or if this was a mistake and I should try again?

Thank you!

**Comment by Ein-Tim** [comment]
New PR for `release/2.6.x`: #3144

**Comment by Ein-Tim** [comment]
This has been **implemented** in version 2.6.

Closing as implemented.
