### ISSUE TITLE
Illustration missing in "Share Data" settings

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#2160]
## Avoid duplicates

* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone XR
- iOS Version: iOS 14.5 Public Beta 3
- App Version: 1.13.0

## Describe the bug

The Android app shows this illustration in the data donation settings:

<img src="https://user-images.githubusercontent.com/67682506/110218022-b6726f80-7eb7-11eb-9222-fd23aaa1af05.png" width="300">

The iOS app is missing this illustration, it shows this in the data donation settings:

<img src="https://user-images.githubusercontent.com/67682506/110218076-ecafef00-7eb7-11eb-8382-b658f5c7de92.png" width="300">

## Steps to reproduce the issue

1. Open CWA
2. Open "Settings"
3. Click on "Share Data"
4. See no illustration

## Expected behaviour

Same illustration as under Android should be shown.

## Related Issue

https://github.com/corona-warn-app/cwa-wishlist/issues/382

## Additional Information:

Thanks to @MikeMcC399 who provided the screenshot from Android in https://github.com/corona-warn-app/cwa-wishlist/issues/382#issuecomment-792014395!

---
Internal Tracking ID: [EXPOSUREAPP-5577](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5577) obsolete
Internal Tracking ID: [EXPOSUREAPP-5328](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5328)

**Comment by dsarkar** [comment]
@Ein-Tim @MikeMcC399  Thanks. Internal Tracking ID: EXPOSUREAPP-5577

**Comment by dsarkar** [comment]
New Internal Tracking ID: [EXPOSUREAPP-5328](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5328)

**Comment by Ein-Tim** [comment]
In version 1.15.1 I still don't see an illustration in the "Share Data" settings. 
This is also not mentioned in the [1.15.1 release](https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v1.15.1) here on GitHub.

**Comment by dsarkar** [comment]
@Ein-Tim ok, thanks for checking. Ticket is still open.

**Comment by Ein-Tim** [comment]
Fix for this is in PR: #4027

**Comment by Ein-Tim** [comment]
This was fixed with https://github.com/corona-warn-app/cwa-app-ios/pull/4027. Please apply the https://github.com/corona-warn-app/cwa-app-ios/labels/Fix%202.16 label here.
