### ISSUE TITLE
[cwa 1.13] Do I need to setup a local server?

### ISSUE THREAD

**Issue by ndegendogo** [corona-warn-app/cwa-app-ios#2161]
## Avoid duplicates
* [ ] Question is not already answered in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Question has not already been asked in another issue

## Your Question

* Source File:
* Line(s):
* Question:

Your [Setup documentation](https://github.com/corona-warn-app/cwa-app-ios#setup) describes how I can build the cwa application with the ENACommunity scheme, and then run it e.g. on a simulator.
With cwa v 1.12 release, and even with early branch 1.13.x this works out of the box for me. The server environment is created successfully; keys are downloaded from the true production server (no authentication required). For download of the statistics I get an error message; but after this message I can test all the rest of the application.

However, with cwa v1.13.0 (release) this has changed. Now I can still compile it successfully with the XCode IDE, but on start of the application it tries to [construct the ServerEnvironment](https://github.com/corona-warn-app/cwa-app-ios/blob/77fb1f828047eff5f2534f6e5db80361c1c6771c/src/xcode/ENA/ENA/Source/AppDelegate%20%26%20Globals/AppDelegate.swift#L35) and [this fails](https://github.com/corona-warn-app/cwa-app-ios/blob/77fb1f828047eff5f2534f6e5db80361c1c6771c/src/xcode/ENA/ENA/Source/ServerEnvironment/ServerEnvironment.swift#L32).
This change in behaviour seems to be related to the data donation feature and the new server url for that feature.
I also noticed that the [definition for the dataDonationURL](https://github.com/corona-warn-app/cwa-app-ios/blob/8fdb3c4b2c6338da2e47ef74a22329c22acba169/src/xcode/ENA/ENA/Resources/ServerEnvironment/ServerEnvironments.default.json#L8) is missing in the v1.13.0 release version of the default configuration.

* Am I missing something in my setup?
* Am I supposed to build differently?
* Do I need to setup a local server?

**Comment by dsarkar** [comment]
@ndegendogo I will bring this to a developer to get an answer. Thanks.

**Comment by ndegendogo** [comment]
Thanks @dsarkar

**Comment by thomasaugsten** [comment]
Hi

you can use your own server from https://github.com/corona-warn-app/cwa-ppa-server
or you enter in the dataDonationURL the public server https://data.coronawarn.app

**Comment by ndegendogo** [comment]
Thanks @thomasaugsten I'll try it
