### ISSUE TITLE
Question regarding #1902

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#2176]
## Avoid duplicates
* [X] Question is not already answered in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Question has not already been asked in another issue

## Your Question
The PR #1902, which has been merged into the _release 1.13.x_ branch adapted the consent flow to the new Apple API ("Automatically notify others") which has been introduced with iOS 14.4 (IIRC). 
I'm on version 1.14.3 and I still only see this grayed out button, no option to enable it:

<img src="https://user-images.githubusercontent.com/67682506/110536490-d1e0b300-8121-11eb-8475-2b2c95da807e.png" width="300">

Is this the intended behavior? When can this button be switched to the ON position?

**Comment by Ein-Tim** [comment]
Thanks @xNeoPilot 

Did you already report an infection thorough the app? 
I'll check with some other devices here too.

**Comment by xNeoPilot** [comment]
@Ein-Tim

So far, I have not reported or registered any infection via the app.

However, I noticed something else.

After disabling the "Andere automatisch informieren" feature,
I have no option to re-enable it, just like you @Ein-Tim.

**Comment by dsarkar** [comment]
@Ein-Tim @xNeoPilot Thanks for your comments. We will raise the question internally.

---
Corona-Warn-App Open Source Team

**Comment by thomasaugsten** [comment]
This options is enable when you register a test via qr code scanning. We will ask you for you pre-consent to warn others automatically if you have a positive test result. You can only disable this in the OS settings but not activate it.

**Comment by dsarkar** [comment]
@Ein-Tim @xNeoPilot see https://github.com/corona-warn-app/cwa-app-ios/issues/2176#issuecomment-795195445

**Comment by Ein-Tim** [comment]
Thanks @thomasaugsten.
