### ISSUE TITLE
Support link preview pop-up

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#2179]
## Current Implementation
Currently (v. 1.12.1, v. 1.13, v 1.14.3), when [holding](https://user-images.githubusercontent.com/67682506/107942410-7c364200-6f8b-11eb-9c52-afdee3b2ad28.mov) links, nothing happens, except for the "New Features" screen which is showing after an app update, there the preview [works](https://user-images.githubusercontent.com/67682506/110522429-2d567500-8111-11eb-86a5-8d1738e98d48.png).

## Suggested Enhancement
Support link previews everywhere in the app, like Safari or GitHub does ([Screen recording](https://user-images.githubusercontent.com/67682506/107942163-2792c700-6f8b-11eb-8a0b-cf61e0c0836d.MP4)).

## Expected Benefits
Consistency with the "New Features" screen, the "Terms of Use" screen, the "Data Privacy" screen, the "Imprint" screen and most other iOS apps. Also, the user has quick(er) access to content. 

---
Internal Tracking ID: [EXPOSUREAPP-5624](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5624)

**Comment by dsarkar** [comment]
@Ein-Tim I am planning to do an issue [Overview] UX/UI with this issue in the wishlist repo, the translucent tab bar, etc. If you are happy to create such an issue go ahead, please. These overviews help quite a lot to get organized and direct the attention of the team to certain topics.

**Comment by Ein-Tim** [comment]
@dsarkar 

I can't create it right now but today afternoon.

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-5624](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5624)

**Comment by Ein-Tim** [comment]
@dsarkar Please see https://github.com/corona-warn-app/cwa-wishlist/issues/386 for the overview.
I will extend it with Android issues soon, but feel free to already add some.

**Comment by ndegendogo** [comment]
@Ein-Tim could you please test this again? I think it is at least partly resolved.
I see the current behaviour:
(cwa 2.13.1(0) / iOS 14.4.1 / iPhone 8, tested with a few links)

- I press long on the link and get a menu together with a small window that shows the link in full length, and an option to preview.
- if I opt for the preview, next time I get the menu and the small window shows the preview, and an option to not preview

![4BE44D04-E7D3-4F2F-9745-DAFFBBF6A3C4](https://user-images.githubusercontent.com/6118267/140650276-d5714684-499b-4209-9159-b1a5038d1f80.png)

**Comment by Ein-Tim** [comment]
@ndegendogo 

This is very inconsistently implemented across the app. Try the Statistics info screen:

First link "FAQ zu Statistiken": Hold -> Nothing happens
Second link (very bottom) "Mehr inhaltliche Details zu einzelnen Kannzahlen finden Sie im Blog.": Hold -> Preview opens.

And this on the same screen.

Same goes for the link to the FAQ if you have a low risk encounter. Hold on the link -> nothing happens.
Now the "Notifications" settings: Hold on the FAQ link > Preview opens.

This really needs to be aligned all across the app.

**Comment by ndegendogo** [comment]
oh yes - I agree

**Comment by ndegendogo** [comment]
Initial analysis: linking the examples given above to source code lines:

1) [First link "FAQ zu Statistiken":](https://github.com/corona-warn-app/cwa-app-ios/blob/438c4f5549bf38dc84b661b3dc244fcbcab1aad0/src/xcode/ENA/ENA/Source/Scenes/StatisticsInfo/StatisticsInfoViewController.swift#L202)
Hold -> Nothing happens
2) [Second link (very bottom) "Mehr inhaltliche Details zu einzelnen Kannzahlen finden Sie im Blog.":](https://github.com/corona-warn-app/cwa-app-ios/blob/438c4f5549bf38dc84b661b3dc244fcbcab1aad0/src/xcode/ENA/ENA/Source/Scenes/StatisticsInfo/StatisticsInfoViewController.swift#L280)
Hold -> Preview opens.
3) [link to the FAQ if you have a low risk encounter.](https://github.com/corona-warn-app/cwa-app-ios/blob/438c4f5549bf38dc84b661b3dc244fcbcab1aad0/src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewModel.swift#L623)
Hold on the link -> nothing happens.
4) [Now the "Notifications" settings:](https://github.com/corona-warn-app/cwa-app-ios/blob/438c4f5549bf38dc84b661b3dc244fcbcab1aad0/src/xcode/ENA/ENA/Source/Scenes/Settings/NotificationSettings/NotificationSettingsViewModel.swift#L85)
Hold on the FAQ link > Preview opens.

**Comment by ndegendogo** [comment]
The funny thing is: There are several cells formatted as .link, they differ in the number of parameters, and some of them are implemented to support preview, some of them not.

Examples
1) [the link at the bottom of the "About the App" page:](https://github.com/corona-warn-app/cwa-app-ios/blob/438c4f5549bf38dc84b661b3dc244fcbcab1aad0/src/xcode/ENA/ENA/Source/Scenes/AppInformation/AppInformationModel.swift#L31) has many parameters, it is implemented [here](https://github.com/corona-warn-app/cwa-app-ios/blob/438c4f5549bf38dc84b661b3dc244fcbcab1aad0/src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/DynamicTableViewCell.swift#L288) and it **does support the preview**
2) [the link to the FAQ for error reports](https://github.com/corona-warn-app/cwa-app-ios/blob/438c4f5549bf38dc84b661b3dc244fcbcab1aad0/src/xcode/ENA/ENA/Source/Scenes/ErrorReporting/MainErrorReportViewControllers/TopErrorReportViewModel.swift#L30) has 3 parameters, it is implemented [here](https://github.com/corona-warn-app/cwa-app-ios/blob/438c4f5549bf38dc84b661b3dc244fcbcab1aad0/src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/Extensions/DynamicCell%2BExposureDetection.swift#L165) and does **not** support preview
3) [link in explanation of low risk cell](https://github.com/corona-warn-app/cwa-app-ios/blob/438c4f5549bf38dc84b661b3dc244fcbcab1aad0/src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewModel.swift#L623) has 2 parameters, same implementation as (2), does **not** support preview.
Same [here](https://github.com/corona-warn-app/cwa-app-ios/blob/438c4f5549bf38dc84b661b3dc244fcbcab1aad0/src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewModel.swift#L653)
4) [link in info for statistics tiles](https://github.com/corona-warn-app/cwa-app-ios/blob/438c4f5549bf38dc84b661b3dc244fcbcab1aad0/src/xcode/ENA/ENA/Source/Scenes/StatisticsInfo/StatisticsInfoViewController.swift#L202) has 2 parameters, same as (2) does **not** support preview.

**Comment by ndegendogo** [comment]
[This](https://github.com/corona-warn-app/cwa-app-ios/blob/438c4f5549bf38dc84b661b3dc244fcbcab1aad0/src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/Extensions/DynamicCell%2BExposureDetection.swift#L141) could also be a candidate worth for further investigation

**Comment by ndegendogo** [comment]
In iOS 12 the links don't show the preview. If I press the link long, only a popup window opens and shows the full link and a menu, see screenshot.
Tested on a true device with iPhone 6 / iOS 12.5.5 / cwa 2.13.1 (0) 
and the links (5 - bottom of About page) and (4 - Notification Settings) and (2 - Statistics Info at the bottom).

**Comment by ndegendogo** [comment]
Essentially, it boils down to two different APIs used for opening links.

(A) the link examples (1), (3), (6), (7) that do **not** support previews, are DynamicCells configured with a DynamicAction, and they all delegate to [LinkHelper.open(url: url)](https://github.com/corona-warn-app/cwa-app-ios/blob/e323c253776cbc1340c70a49c7691f03d5b06f49/src/xcode/ENA/ENA/Source/Workers/LinkHelper.swift#L23), and finally it calls `UIApplication.shared.open()`.
Note: `LinkHelper.open()` is also called from a lot of other places in the cwa source code.

(B) the link examples (2), (4), (5) that **do** support previews, are implemented as [extension](https://github.com/corona-warn-app/cwa-app-ios/blob/e323c253776cbc1340c70a49c7691f03d5b06f49/src/xcode/ENA/ENA/Source/Extensions/NSMutableAttributedString%2BLink.swift#L18) of `NSMutableAttributedString`, they add a `.link` attribute to the string.

**Comment by ndegendogo** [comment]
Especially weird is the link to the "App informations in Easy Language and Sign Language".
It is linked from the About screen as well as from the first page of the Onboarding flow.
And, guess what: the preview works from the About screen but not from the Onboarding.

**Comment by Ein-Tim** [comment]
@ndegendogo Something is strange is going on with this. I don't understand it...

**Comment by ndegendogo** [comment]
You are right, it is a mess 👹 
But actually I am understanding by far more detail than in the beginning. Although I don't have yet a good idea **how** this best be cleaned up.

I think I will attack one link after the other. And discuss the pros and cons of each solution with the developers.

**Comment by ndegendogo** [comment]
I have submitted PR #3843 - only for the Onboarding flow.
@dsarkar - could you please apply the labels? - Thanks!

**Comment by dsarkar** [comment]
Good morning @ndegendogo  done, thanks.

**Comment by ndegendogo** [comment]
@dsarkar 
I have submitted PR #3898. Please ally the labels - thanks!

**Comment by dsarkar** [comment]
Good morning @ndegendogo! Thanks for the PR, will apply the labels and add info to Internal Tracking ID: [EXPOSUREAPP-5624](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5624). Enjoy the weekend!

**Comment by Ein-Tim** [comment]
I've tested multiple links all around the app (increased risk card, statistics info screen, etc.), they all had a preview.

Thanks to @ndegendogo for implementing this!

Closing this issue as implemented.

**Comment by ndegendogo** [comment]
@Ein-Tim thank you.
As I [wrote here](https://github.com/corona-warn-app/cwa-app-ios/issues/2179#issuecomment-980538375) I am aware of two links that are not covered. But, yes, **most links** are indeed covered now. So: "good enough" 🙃
