### ISSUE TITLE
iPhone SE, Contact Journal, cannot add email address in contacts

### ISSUE THREAD

**Issue by ouboub** [corona-warn-app/cwa-app-ios#2185]
Hi
either when editing an old contact or adding a new one, it is impossible on my iPhone SE (1 gen) to add an email address, since the screen is too small. That however cannot be the reason, since I can do use in my  iOS contact list, the reason is that there is no scrolling possible.
BTW why should places posses a email address instead of a ZIP code.
see the attached screenshot

regards

UB
![Screenshot 2021-03-10 at 22 44 17](https://user-images.githubusercontent.com/5957203/110703043-91ea0080-81f3-11eb-9151-c99479ea4b35.png)

---
Internal Tracking ID: [EXPOSUREAPP-5575](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5575)

**Comment by Ein-Tim** [comment]
@ouboub 

Could you maybe let us know your iOS and CWA Version?

**Comment by jucktnich** [comment]
Same by me
- iOS 14.4.1
- cwa 1.14.3

**Comment by ouboub** [comment]
>>> "T" == Tim  ***@***.***> writes:

> @ouboub 
> Could you maybe let us know your iOS and CWA Version? 

Ios 14.4.1
CW 1.14.3 (0)

**Comment by dsarkar** [comment]
@ouboub 
@jucktnich 
Thanks for reporting.  We will report the issue to the developers.

---
Internal Tracking ID: [EXPOSUREAPP-5575](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5575)

**Comment by Ein-Tim** [comment]
Can confirm this bug on an emulator with iOS 14.4 running CWA 1.14.4. 
The safe button always pops up above the `e-mail` field, so that it isn't possible to add one. The only device affected seems to be the iPhone SE 1. Gen, since it has the smallest screen.

Problem is that there is no scrollbar on this view, which is needed for the iPhone SE 1.

**Comment by Ein-Tim** [comment]
#2198 is the PR fixing this, labeled for the next release, version 1.15

**Comment by dsarkar** [comment]
@Ein-Tim Thanks for the link tot the PR.

**Comment by ndegendogo** [comment]
> Can confirm this bug on an emulator with iOS 14.4 running CWA 1.14.4.

@Ein-Tim so you have a debugging environment up and running? 
**Congratulations!** 👍

**Comment by Ein-Tim** [comment]
@ouboub 

[Version 1.15.1](https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v1.15.1), which should fix this, has just been released, can you confirm the fix?

**Comment by dsarkar** [comment]
Indeed, as mentioned above 1.5.1 has been released, see also:

https://www.coronawarn.app/de/blog/2021-03-24-corona-warn-app-version-1-15/
https://www.coronawarn.app/en/blog/2021-03-24-corona-warn-app-version-1-15/

**Comment by dsarkar** [comment]
@jucktnich see https://github.com/corona-warn-app/cwa-app-ios/issues/2185#issuecomment-805657864, please. Feedback appreciated. Thanks.

**Comment by jucktnich** [comment]
Works now, thx

**Comment by dsarkar** [comment]
@jucktnich Thanks for the feedback. 
@ouboub The issue was fixed with 1.15. Could you close this issue, please. 

Many thanks for contributing here to everybody. Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by ouboub** [comment]
The Fix works. Thanks

**Comment by Ein-Tim** [comment]
@ouboub 

Nice to hear, feel free to close this (since you can close it as the author of this issue) 🙂

**Comment by dsarkar** [comment]
@ouboub Thanks for the feedback and participating here!
