### ISSUE TITLE
Question reg. #2132 („Days since installation“)

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#2204]
## Avoid duplicates
* [X] Question is not already answered in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Question has not already been asked in another issue

## Your Question
* PR: #2132
* Question:
What will users who update the app see for a number? 
The days that passed since the update or the actual time how long they have the app installed?

**Comment by dsarkar** [comment]
@Ein-Tim Since installation. Updates should not reset the count.

**Comment by Ein-Tim** [comment]
@dsarkar 

So even when I update from version 1.14.4 (which doesn't show how long the app was installed) to version 1.15, the correct time will be shown?

**Comment by ndegendogo** [comment]
@Ein-Tim very good question! 👍

I guess the answer depends on how they designed their solution.
And asking this question **before** the release of such a feature gives the devs the chance to design it from the beginning in a way that meets user expectations; instead of  getting many questions and confused users **after** a release.

**Comment by Ein-Tim** [comment]
@ndegendogo 

Yes, I wanted to ask this before the release. 
If the app will show 0 days since installation after update to 1.15 then this **needs** a **in app** explanation (Pop-Up, etc.).

**Comment by heinezen** [comment]
@Ein-Tim 

From the code in the PR you can see that the installation date is inferred from the creation time of the app's folders. Upgrading the app does not affect this parameter.

For Android, there is an [API call](https://developer.android.com/reference/android/content/pm/PackageInfo#firstInstallTime) that returns the first install date.

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
Thanks @heinezen!
