### ISSUE TITLE
Highlight effect is shown on areas it shouldn't be shown

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#2245]
## Avoid duplicates

* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: -
- iOS Version: -
- App Version: 1.14.4

## Describe the bug

This highlight effect is shown on 
a) some empty areas
b) areas that don't do anything if clicked on

<details>
<summary>Screen recording from a)</summary>

https://user-images.githubusercontent.com/67682506/111690871-01807100-882e-11eb-986d-ec5db1a1e2c0.mp4

</details>

and

<details>
<summary>Screen recording from b) - Case 1</summary>

https://user-images.githubusercontent.com/67682506/111690884-03e2cb00-882e-11eb-9ff9-569a881a79a0.mp4

</details>

<details>
<summary>Screen recording from b) - Case 2</summary>

https://user-images.githubusercontent.com/67682506/112021738-e36a8780-8b31-11eb-9e99-870c801dd7b6.mp4

</details>

It should only be shown on fields that will do something (like the "[Share the Corona-Warn-App](https://user-images.githubusercontent.com/67682506/111690853-fd545380-882d-11eb-95f5-f8a6e6fca131.mp4)" section).

## Steps to reproduce the issue

a)

1. Open the contact diary
2. Click on the 3 dots in the top right corner
3. Click on information
4. Click on the empty space between the points
5. See highlight effect

and

b)

Case 1: 

1. Open the "Have you been tested?" box
2. Click on "No TAN yet" 
3. Tap on the text in the section "How this works"
4. See highlight effect

Case 2: 

1. Open the "Overview"
2. Tap on "Increased Risk", "Low Risk" 
3. See highlight effect. 

## Expected behaviour

Highlight effect only shown on areas that do something (like open a menu, etc.).

## Additional context

Affected screens (that I found) are:

- Contact Diary Info Screen (Open the contact diary and click on the 3 dots in the top right corner, in the menu click on "Information")
- "Request a Tan" screen inside of the "Have you been tested?" (click on "No TAN yet")
- "Overview" screen (tap on the "i" in the top right corner) and click on "Increased Risk" or "Low Risk"

## Related Issue

- #2246 (Highlight effect missing on "Transnational Exposure Logging" field)

---
Internal Tracking ID: [EXPOSUREAPP-5896](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5896)

**Comment by dsarkar** [comment]
---
Internal Tracking ID: [EXPOSUREAPP-5896](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5896)

**Comment by Ein-Tim** [comment]
FYI @dsarkar I updated the op with one more place I found this bug

**Comment by dsarkar** [comment]
@Ein-Tim OK, Thanks. Will add the additional information to the internal ticket.

**Comment by Ein-Tim** [comment]
And one more case:

<img src="https://user-images.githubusercontent.com/67682506/112811337-3f766400-907c-11eb-913a-5b519c692c20.png" width="300">

**Comment by dsarkar** [comment]
@Ein-Tim ok, added to ticket.

**Comment by Ein-Tim** [comment]
All cases mentioned in the OP have been fixed, but

Case 2:

1. Open the "Overview"
2. Tap on "Increased Risk", "Low Risk"
3. See highlight effect.

@hansemann I assume this is a quick fix. Would you like to quickly fix this too? This would be marvelous!

**Comment by ndegendogo** [comment]
@Ein-Tim what exactly is missing here?

**Comment by Ein-Tim** [comment]
@ndegendogo 

There should be no highlight effect when clicking in the Overview on "Increased Risk" or "Low Risk".

See https://github.com/corona-warn-app/cwa-app-ios/issues/2245#issuecomment-857088356

**Comment by ndegendogo** [comment]
ah - found it 😅

**Comment by ndegendogo** [comment]
@dsarkar @heinezen I have submitted PR #3790 with the fix for the missing part. Please apply the labels - thanks.

**Comment by Ein-Tim** [comment]
@ndegendogo 

Thank you for this PR!

**Comment by ndegendogo** [comment]
@Ein-Tim could you please test it and confirm if it is fixed now? Thanks!

**Comment by Ein-Tim** [comment]
@ndegendogo 

Thanks for reminding me! Yes, this was fixed in version 2.14!

Closing.

**Comment by dsarkar** [comment]
@ndegendogo @Ein-Tim Thanks for CONFIRM. internal ticket set accordingly.
