### ISSUE TITLE
Highlight effect missing on "Transnational Exposure Logging" field

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#2246]
## Avoid duplicates

* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: -
- iOS Version: -
- App Version: 1.14.4

## Describe the bug

The highlight effect isn't shown on the transnational exposure logging field: 

https://user-images.githubusercontent.com/67682506/111695563-8752eb00-8833-11eb-9980-489d87aa7d72.mp4

## Steps to reproduce the issue

1. Click on "Exposure Logging Active/Stopped"
2. Click on "Transnational Exposure Logging"
3. Notice that there's no highlight effect when clicking on the field

## Expected behaviour

Highlight effect shown, as on all other clickable fields.

## Related Issue

- #2245 (Highlight effect is shown on areas it shouldn't be shown)

---
Internal Tracking ID: [EXPOSUREAPP-5897](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5897)

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-5897](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5897)

**Comment by ndegendogo** [comment]
@dsarkar @heinezen I have submitted PR #3789 with a fix. Please apply the labels - thanks.

**Comment by Ein-Tim** [comment]
Thank you for the PR @ndegendogo!

**Comment by ndegendogo** [comment]
@Ein-Tim could you please test it? Thanks!

**Comment by Ein-Tim** [comment]
I can confirm that this issue was fixed in version 2.14.1.

Thank you for providing a PR with the fix @ndegendogo!

Closing.

**Comment by dsarkar** [comment]
@ndegendogo @Ein-Tim Thanks for CONFIRM, internal ticket set accordingly.
