### ISSUE TITLE
[Apple iOS 14.5] Unlocalized string „PRE_AUTHORIZATION_TITLE“ is shown (and the screen isn‘t localized)

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#2250]
## Avoid duplicates

* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone XR
- iOS Version: 14.5 Public Beta 4/5
- App Version: 1.14.4

## Describe the bug

The screen which is shown inside of the "Have you been tested?" box -> "Test with QR Code" -> "Accept" 

a) has an unlocalized title
~b) is only shown in German.~

<img src="https://user-images.githubusercontent.com/67682506/111762329-34b01800-88a1-11eb-8d78-a4487cb05703.png" width="300">

## Steps to reproduce the issue

1. Open the "Have you been tested?" box
2. Select "Test with QR Code"
3. Tap on "Agree"
4. See unlocalized string "PRE_AUTHORIZATION_TITLE" ~and see that the screen is always shown in German, even if the app language is set to English.~

## Expected behaviour

Localized string ~and screen shown in the language of the app.~

## Additional information

Seems like this screen comes directly from iOS, if the language from the whole phone, and not only the language from the app is set to English, the screen is shown in English (but it still shows "PRE_AUTHORIZATION_TITLE").

So that it's shown in German although the app's language is English seems to be intended.

**Comment by thomasaugsten** [comment]
This is already addressed to Apple

**Comment by jucktnich** [comment]
On iOS 14.4.1 is the localised text.

**Comment by Ein-Tim** [comment]
Thanks for the feedback @thomasaugsten & @jucktnich.

Let's hope that this doesn't make it into the final release of iOS 14.5.

**Comment by Ein-Tim** [comment]
This has been fixed. The screen now shows "Begegnungsinformationen automatisch teilen" or "Automatically Share Exposure Information".

**Comment by dsarkar** [comment]
@Ein-Tim Thanks.
