### ISSUE TITLE
Risk encounter shown in ENF log but not in cwa

### ISSUE THREAD

**Issue by ndegendogo** [corona-warn-app/cwa-app-ios#2272]
## Avoid duplicates

* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is not already reported in another issue

## Technical details
1) Primary device, this works as expected
- Device name: iPhone 8
- iOS Version: iOS 14.4.1
- App Version: 1.14.4(0)

2) secondary device, this one is unexpected:
- Device name: iPhone 6
- iOS Version: 12.5.1
- App Version: 1.14.4(0)

## Describe the bug

Today I got a green warning (low risk) on my primary phone. I see it in the ENF log, and it is shown in the contact journal. Everything as expected so far.
But then I checked my secondary phone. Here I see also 1 contact in the ENF log, but cwa shows just nothing.

## Steps to reproduce the issue

Compare encounters shown in ENF log with cwa risk warning

## Expected behaviour
Encounters should match between ENF log and cwa - *(or am I missing something?)*

## Additional context
I will add screenshots of both devices later.

**Comment by Ein-Tim** [comment]
@ndegendogo 

This is possible since version 1.9, see https://www.coronawarn.app/en/faq/#encounter_count_19:

> With the interface's new version, it is now possible to control more precisely which encounters should be counted. However, in the operating system's contact log, a count is performed. However, this is not an error.

And my issue back then: https://github.com/corona-warn-app/cwa-app-ios/issues/1703

**Comment by ndegendogo** [comment]
Thanks @Ein-Tim for your fast response! Yes, you are right. And now I even remember that I had seen this pattern before. Exactly as you describe in your linked ticket. Before version 1.9 I had one (low-risk) contacts, and after the update to 1.9 it was no longer shown in cwa, but still in the ENF log.

Closing this ticket.

**Comment by ndegendogo** [comment]
Just wanted to mention before I forget it.

**I appreciate the new warning screen with the date of the contact very much.**

Thanks a lot 👍👍
