### ISSUE TITLE
App crashes if user clicks on link on the bottom of the "Exposure check failed" detail screen

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#2287]
## Avoid duplicates

* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 6s
- iOS Version: 14.5 Beta 5 
- App Version: 1.15.1 (0)

## Describe the bug

The app crashes if the user clicks on the link on the bottom of the "Exposure check failed" screen:

https://user-images.githubusercontent.com/67682506/112733386-0f29ab00-8f40-11eb-94e4-e0f0b9dfab1a.mov

## Steps to reproduce the issue

1. Get the app to show the "Exposure check failed" screen (trigger an ENError like 13)
2. Tap on the "Exposure check failed" card
3. Scroll to the ver bottom
4. Click on the link "For further information, please see our FAQ page"

## Expected behaviour

No crash & open the FAQ page

## Additional context

- This link is not shown on the normal risk screen. Maybe it should be removed?
- The crash happens with all languages except of German
- Locale set to German, the link is set to  Links to entry https://www.coronawarn.app/de/faq/#encounter_but_green, which is not the correct context.

---
Internal Tracking ID: [EXPOSUREAPP-5999](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5999)

**Comment by dsarkar** [comment]
@Ein-Tim Can't reproduce actually. Link seems to work, no crash.

**Comment by Ein-Tim** [comment]
@dsarkar 

Mh, okay. Will try to reproduce with iOS 14.4.2. 
Will report back here ASAP.

**Comment by dsarkar** [comment]
ahh got it. In DE it works, crash is in EN only, can you confirm this? @Ein-Tim

**Comment by Ein-Tim** [comment]
@dsarkar 

Confirm. German is not affected. All other languages are affected.

The link should be removed. Links to entry https://www.coronawarn.app/de/faq/#encounter_but_green, which should only be shown if there was an encounter with low-risk.

**Comment by dsarkar** [comment]
@Ein-Tim Thanks for analysing this ...

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-5999](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5999)

**Comment by dsarkar** [comment]
PR https://github.com/corona-warn-app/cwa-app-ios/pull/2328

**Comment by Ein-Tim** [comment]
Version 2.0 which fixed this has been released to GitHub and is available to all users in the next 48h. 

See blog post: 

DE: https://www.coronawarn.app/de/blog/2021-04-21-corona-warn-app-version-2-0/
EN: https://www.coronawarn.app/en/blog/2021-04-21-corona-warn-app-version-2-0/

See GitHub release:

iOS: https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v2.0.3

This issue will now be closed.

**Comment by dsarkar** [comment]
@Ein-Tim Thanks!

---
Corona-Warn-App Open Source Team
