### ISSUE TITLE
Is it intended that not all links open in the in-app browser?

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#2289]
## Avoid duplicates
* [X] Question is not already answered in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Question has not already been asked in another issue

## Your Question
* Question: The FAQ link (`safari_corona_website` - [link to code](https://github.com/corona-warn-app/cwa-app-ios/blob/557661423a2869b98e4affdcc40c6f50b469a205/src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.links.strings#L11)) on the main page opens in the in-app browser. 
Links in f.e. the "Terms of Use" are all opened in the devices standard browser. 

Is this the intended behavior, if yes, why?

**Comment by dsarkar** [comment]
@Ein-Tim We will try to get an answer.

**Comment by Ein-Tim** [comment]
@dsarkar 

Thanks, although it's a bit weird that some links open via in-app and others don't, I'll close this issue now.
