### ISSUE TITLE
Write Tests for DynamicTable*-Classes

### ISSUE THREAD

**Issue by ChristianKienle** [corona-warn-app/cwa-app-ios#23]
There are a lot of classes that deal with dynamic tables. Those classes start with `DynamicTable`. Most of them are pure model classes and can easily be tested. Tests for those classes a very valuable since we use them a lot.

**Comment by dasdom** [comment]
I did some work on this one. But there is still much work left.

Note: The tests are in a section called __tests__ next to the code that is being tested (as it's done in the rests of the project).

**Comment by dasdom** [comment]
Right now I'm doing the tests for header and footer in DynamicTableViewController.

**Comment by ChristianKienle** [comment]
I will close this issue since there are already a lot of nice tests in our development branch - done by @dasdom (thanks again).
