### ISSUE TITLE
Wiederholte Fehler 13 Meldung

### ISSUE THREAD

**Issue by malinax0605** [corona-warn-app/cwa-app-ios#2327]
iPhone SE
IOS 14.4.1
 1.15.2 (2)

Seid drei Tagen zeigt meine Corona- App folgendes an: 

![0C32C350-97B6-4DDD-9825-364A1C509CA4](https://user-images.githubusercontent.com/81713414/113205011-11f10c80-926e-11eb-95b0-55ab21789dd4.png)

---
Related Issues:

#2220
#2316

Internal Tracking ID: [EXPOSUREAPP-5836](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5836)

**Comment by Ein-Tim** [comment]
Hey @malinax0605 

Could you please provide your EN-Log here? This would be perfect! 


<details>
<summary>How to export Exposure Notificaiton Logs under iOS 13.7 or newer</summary>


**German:**

`Einstellungen` ➡️ `Begegnungsmitteilungen` ➡️ `Status von Begegnungsaufzeichnungen` ➡️ `Begegnungsüberprüfungen` ➡️ `Überprüfungen exportieren`

**English:**

`Settings` ➡️ `Exposure Notifications` ➡️ `Exosure Logging Status` ➡️ `Exposure Checks` ➡️ `Export Exposure Checks`

**To upload the file here, rename it from .json to .txt**
</details>

Please also provide:

- iPhone model
- iOS Version
- CWA version

Thank you! 

---

Related Issues:

#2220 
#2316

**Comment by Ein-Tim** [comment]
Aaaand:

Any special action done before this error appeared?

**Comment by malinax0605** [comment]
iPhone SE 
IOS 14.4.1 

where can I find out about CWA version? 

![420A1944-6395-40F4-8BAF-88A6C48DAC6E](https://user-images.githubusercontent.com/81713414/113208843-93e33480-9272-11eb-9716-5aaa6c927105.png)

Attached: EN- log 

I did update my iPhone on the 19th March. This had never occurred before so maybe the update and the error are in fact related?!

**Comment by Ein-Tim** [comment]
@malinax0605 

The CWA version can be found in CWA:

Scroll to the bottom and click on "App-Informationen", there you can see the Version (little text under "Impressum").

Although I can't see your EN-Log (could you please try to upload it again?), I can tell from the screenshot that yesterday and today, the limit of 6 checks has been reached, but all of them were not normal.

> I did update my iPhone on the 19th March. This had never occurred before so maybe the update and the error are in fact related?!

I don't think that it's really related to the iOS update on 19th march, rather it comes from CWA updates.

---

@thomasaugsten I am lost here, something weird is going on. This is the third case where Error 13 is showing up either because of checks that happen to often (distance from 1-2 minutes, see also https://github.com/corona-warn-app/cwa-app-ios/issues/2220#issuecomment-800150325)) or that Error 13 is showing up with no real reason (#2316).
Are you looking into this internally?

**Comment by malinax0605** [comment]
Okay thanks! So I checked the Version, it is 1.15.2 (2) 

And where can I find the requested EN- Log?

**Comment by Ein-Tim** [comment]
Okay thanks for the app version.

>And where can I find the requested EN- Log?

Here:

`iOS Einstellungen` ➡️ `Begegnungsmitteilungen` ➡️ `Status von Begegnungsaufzeichnungen` ➡️ `Begegnungsüberprüfungen` ➡️ `Überprüfungen exportieren`

**Comment by dsarkar** [comment]
@malinax0605 Thanks for reporting. We have two more similar cases #2220 and #2316. In both cases the issue started with a positive test result. On the phone with the issue, was there a QR code scanned and did the problem start with receiving the test result? Thanks for the feedback.

**Comment by malinax0605** [comment]
#

> problem
That might be the case. A QR was scanned on Monday. The result was negative. However, the issue had appeared before. I think I noticed the error report on Sunday afternoon or Monday morning. How shall I proceed now? 

Thank you for your help!

**Comment by Ein-Tim** [comment]
@malinax0605 

Please do as follow: Open the iOS Settings -> search for "Corona-Warn" -> "Hintergrundaktualisierung" and turn it off. 

Wait 24h, don't open the app! Tomorrow open the app and trigger a risk check manually. 

Could you please share your EN-Log with us? This would be very helpful. Thank you so much! 😀

**Comment by malinax0605** [comment]
I have tried to share the EN- log a couple of times but it seems that I’m unable to share the document... 
![22E71D49-D440-4FB2-8A33-9EDDA17CF323](https://user-images.githubusercontent.com/81713414/113292382-b87ff080-92f4-11eb-824e-b05add381beb.jpeg)
![99109C05-4219-443A-AF17-456179FA2C17](https://user-images.githubusercontent.com/81713414/113292385-b9b11d80-92f4-11eb-8318-dc597af411e1.png)


And also my „Hintergrundaktualisierung“ appear to be turned off already. What am I supposed to do now? Any other suggestions?

**Comment by Ein-Tim** [comment]
@malinax0605 

To share the log, you can compress it into an zip folder. 
Long press on the document and then tap "Komprimieren". This folder can be uploaded to GitHub. 

> And also my „Hintergrundaktualisierung“ appear to be turned off already. What am I supposed to do now? Any other suggestions?

Could you please share a screenshot of your Corona-Warn-App without the Error pop up? Thanks!

**Comment by dsarkar** [comment]
@malinax0605 Developers are looking into this issue currently. 
„Hintergrundaktualisierung“ is turned off. i.e. you trigger manually the "Aktualisierung" ?
Do you get the error 13 in both cases, i.e. with „Hintergrundaktualisierung“ on or off?
Also see this, please: https://github.com/corona-warn-app/cwa-app-ios/issues/2327#issuecomment-811873335

**Comment by TinyToon13** [comment]
Ich habe den gleichen Fehler. Habe einen positiven Test eingegeben, dann war die Risiko Ermittlung aus. Nach einschalten diesem Fehler.

**Comment by Ein-Tim** [comment]
Danke fürs Melden @TinyToon13.

Könntest du vielleicht deinen EN-Log hier mit uns teilen? Anleitung siehe unten. Entweder die Datei von .json zu .txt umbenennen oder, wie [hier](https://github.com/corona-warn-app/cwa-app-ios/issues/2327#issuecomment-811873335) erklärt als ZIP-Ordner.

Bitte außerdem noch dein iPhone Modell, deine iOS-Version und deine App Version. Das wäre super! Danke!

<details>
<summary>How to export Exposure Notificaiton Logs under iOS 13.7 or newer</summary>


**German:**

`Einstellungen` ➡️ `Begegnungsmitteilungen` ➡️ `Status von Begegnungsaufzeichnungen` ➡️ `Begegnungsüberprüfungen` ➡️ `Überprüfungen exportieren`

**English:**

`Settings` ➡️ `Exposure Notifications` ➡️ `Exosure Logging Status` ➡️ `Exposure Checks` ➡️ `Export Exposure Checks`

**To upload the file here, rename it from .json to .txt**
</details>

**Comment by TinyToon13** [comment]
EN-Log ist leer. Habe App gelöscht und Bewegungen gelöscht da ich eh gerade in Quarantäne bin. IOS Version ist 14.4.2 mit einem iPhone X und die App hat Version 1.15.2 (2)
reicht das?

**Comment by Ein-Tim** [comment]
Danke. Wenn der Log leer ist dann reicht das. Die App zeigt auch noch nachdem der Log gelöscht wurde den Error 13 an? Oder jetzt nicht mehr?

**Comment by TinyToon13** [comment]
Doch deswegen hab ich geschrieben. Ich dachte ich kann mir selbst helfen weil es nicht so wichtig ist die Begegnungen aufzuzeichnen weil ich gerade nur zu Hause sitze. App zeigt immer noch den Fehler .

**Comment by Ein-Tim** [comment]
@TinyToon13

Wenn du den Log gerade erst gelöscht hast dann kann es bis zu 24h dauern bis der Error wieder verschwindet. 
Hast du Hintergrundaktualisierung für die Corona-Warn-App aktiv (siehe [dieser](https://github.com/corona-warn-app/cwa-app-ios/issues/2327#issuecomment-811851153) Kommentar)?

**Comment by TinyToon13** [comment]
Ich kann sie gern mal aus machen und prüfe das in 24 Stunden. Melde mich dann

**Comment by Ein-Tim** [comment]
Das wäre super. Danke!

**Comment by dsarkar** [comment]
@TinyToon13 Danke für deinen Bericht. Wir hoffen später Dein Feedback zu bekommen. Best Grüße, DS

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
@malinax0605 Any updates? Also see this, please: #2327 (comment). Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by TinyToon13** [comment]
Jetzt scheint es wieder alles zu klappen. Der Aktualisierungs Countdown ist neu 

![92666239-70FD-4483-A5E9-385D34E3CE93](https://user-images.githubusercontent.com/73381220/113436021-3c64d600-93e4-11eb-8e66-513d0b8d9d5f.jpeg)

**Comment by dsarkar** [comment]
@TinyToon13 Danke für das Feedback. Wenn Du  „Hintergrundaktualisierung“ wieder einschaltest, ist der Count-down wieder weg, und die Aktualisierung sollte im Hintergrund von alleine von statten gehen. Ich schlage vor das auch so einzustellen, und bitte, wir würden auch dann gerne Feedback haben, ob die App ordnungsgemäß funktioniert. Frohe Ostern, DS

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@malinax0605 

Is the app working again for you? Or still error 13? 

Nice easter days!

**Comment by TinyToon13** [comment]
Alles wieder gut. Hintergrund Aktualisierung eingeschaltet. Funktioniert wie vorher. Jetzt will ich aber lange kein Rot mehr sehen 😜 euch auch schöne Ostern und passt auf dass ihr euch nicht ansteckt.

**Comment by malinax0605** [comment]
> @malinax0605
> 
> Is the app working again for you? Or still error 13?
> 
> Nice easter days!

Nope, still not working.... shall I delete the app and all activity linked to the app?

**Comment by Ein-Tim** [comment]
Before you delete it do this:

1. Open iOS Settings
2. Open "Begungsmitteilungen" 
3. Click on "Aktive Region" / "Corona-Warn-App"
4. Click on "Corona-Warn-App"
5. Scroll down
6. Deactivate "Begegnungsinformationen teilen"

Now the app doesn't have any access to the Apple API anymore, so it can't make anymore faulty API calls. 

Reaktive this setting after ca. 25h (to be sure).

**Comment by dsarkar** [comment]
Good morning @malinax0605,

Is the error 13 notification gone or do you still get the notification every day?
If that is the case, did you try this: #2316 (comment)?

Thanks for the feedback, best wishes, DS

Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
Version 2.1 which fixed the unintended occurrence of Error 13 has been released!

It will reach all users in the next 48 hours.

See GitHub Release: https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v2.1.1 

The PR that fixed this was #2492.

Please update your App, confirm the fix and then close this issue.

Thank you!

**Comment by dsarkar** [comment]
Hi @malinax0605,

Siehe den Kommentar oben von @Ein-Tim. Wir würden uns über Feedback von Dir freuen: Kannst Du bestätigen, dass der Fehler bei Dir nicht mehr auftaucht? Vielen Dank, Beste Gruesse, DS

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
Hi @malinax0605,

Siehe den Kommentar oben von @Ein-Tim. Wir würden uns über Feedback von Dir freuen: Kannst Du bestätigen, dass der Fehler bei Dir nicht mehr auftaucht? Vielen Dank, Beste Gruesse, DS

Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@dsarkar And one more issue to close (-;

**Comment by heinezen** [comment]
Hello everyone,

Occurences of Error 13/Fehler 13 should be fixed with the recent CWA release 2.5. Please update your app and report back if the error still persists for you when using the newest version. We will close the issue for now.

----
Corona-Warn-App Open Source Team
