### ISSUE TITLE
Change from green to red risk with update to cwa 1.15?

### ISSUE THREAD

**Issue by ndegendogo** [corona-warn-app/cwa-app-ios#2341]
## Avoid duplicates
* [x] Question is not already answered in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Question has not already been asked in another issue

## Your Question

* Source File:
* Line(s):
* Question:
I am asking the following on behalf of my sister. She updated today to cwa 1.15.2(0).
Before the update her risk card showed 2 days with encounters, but her score was still green. And today / shortly after the update she got the red warning. Still the same two days as before.

cwa 1.15.2(2) / iOS 14.4.2 / iPhone 8

Questions:
1) Did the risk formula or its parametrization change with cwa 1.15, or today (02 April)?
2) What else can explain this change from green to red?

**Comment by jucktnich** [comment]
Maybe it's the change to ENF v2

**Comment by ndegendogo** [comment]
@jucktnich thanks for the suggestion - but I don't think so.
ENF v2 was introduced something like Nov last year

**Comment by jucktnich** [comment]
@ndegendogo I don't know your sister, but I know people who didn't update their apps for years...

**Comment by Ein-Tim** [comment]
I don't think that it's something about ENF v2, this update was done in version 1.9. If your sister already had the contact diary then she already was on a CWA version using ENF v2.

This PR updated the risk calculation: #2111

There were two changes to the risk formula, one on 23.02.2021 ([blog post](https://www.coronawarn.app/de/blog/2021-02-23-corona-warn-app-risk-calculation-optimization/)) and one on 19.03.2021 ([blog post](https://www.coronawarn.app/de/blog/2021-03-19-risk-calculation-improvement/)).
But the older app version should already have used the new config from the server, so probably this change is related to #2111.

**Comment by Ein-Tim** [comment]
@ndegendogo I'm sure you checked the EN-Log & what's shown in the contact diary to make sure that this isn't a new encounter and the old one just dropped out of the 14 days window, correct? 😉

**Comment by ndegendogo** [comment]
As far as I remember, back in Nov the announcement was that they reduce the number of "false positives" and don't show "negligible green risks". There were several users who reported accordingly that their green warning vanished with the update.
But meanwhile the philosophy seems to filter less / accept more warnings, even at the expense of more false positives.
https://www.coronawarn.app/de/blog/2021-03-19-risk-calculation-improvement/

**Comment by Ein-Tim** [comment]
@ndegendogo Yes, this changed with the rising number of mutations/virus variants we have, since they're (the most) more contagious.

**Comment by ndegendogo** [comment]
> This PR updated the risk calculation: #2111

@Ein-Tim this is the hottest candidate imo.
Do you have more details on the background / purpose of this PR?

**Comment by Ein-Tim** [comment]
> Do you have more details on the background / purpose of this PR?

No, sadly I don't... I can't really tell if it is possible that this change transforms a green risk into a red risk. 

One of the community managers should ask one of the devs (i.e. @nickguendling, the author of the PR #2111) if such a change is possible.

**Comment by ndegendogo** [comment]
Well - I can ask as well 😀

**Comment by thomasaugsten** [comment]
In 1.15 we introduce v2 of the config file to allow more precise risk calculation. Which is need because of this adoption
https://www.coronawarn.app/de/blog/2021-03-19-risk-calculation-improvement/

**Comment by ndegendogo** [comment]
> I'm sure you checked the EN-Log & what's shown in the contact diary to make sure that this isn't a new encounter and the old one just dropped out of the 14 days window, correct?

@Ein-Tim of course I forgot the ENF log 😅

> You can also see if your sister was on ENF v2 if the format of the EN-log changed with the update (encounters are only shown on top level and not for each key anymore).

Well - as far as I remember, since ENF v 2 the encounters are shown locally, but suppressed in the exported version.

But you are right, I'll ask her right now what the ENF log shows to her.

**Comment by ndegendogo** [comment]
Thanks @thomasaugsten

**Comment by ndegendogo** [comment]
@Ein-Tim I did not see many warnings since ENF v2, this was about the same time as the "lockdown light" which indeed reduced my number of contacts. (Only recently I got 1 green warning again).
But it seems that the information in the ENF log complements the information that cwa shows: ENF shows number of matches (but no days), whereas cwa shows which days (but no further details on the days).

**Comment by ndegendogo** [comment]
Question is answered , thanks again.
Closing the ticket.
