### ISSUE TITLE
[App-Store] CWA story in the App Store

### ISSUE THREAD

**Issue by jucktnich** [corona-warn-app/cwa-app-ios#2346]
## Avoid duplicates

* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is not already reported in another issue

## Technical details

- Device name:
- iOS Version:
- App Version:

## Describe the bug
In the App Store story about the cwa, in the section about the minimum requirements, there's the iPhone 7 the oldest device with iOS 13.7, but it should be iPhone 6s (and iPhone SE 1.gen).

![image](https://user-images.githubusercontent.com/73582096/113883875-d6e75f80-97be-11eb-834d-05c6e73b62e7.jpeg)

## Fixed issue
In the App Store, when you go to CWA and than to the bottom, there's a story. This story is not up to date anymore. F.e. there is the info, that the minimum iOS version is 13.5.

**Steps**

Search for corona-warn-app ➜ click on the app ➜ scroll down to bottom (or a little bit less on small devices) ➜ click on the picture with the woman walking and man riding bike

or go to https://apps.apple.com/de/story/id1517388949 (german)

![AppStore-1](https://user-images.githubusercontent.com/1409741/113712775-d2e80e80-96e6-11eb-806a-023ead7d0c35.png)

![AppStore-2](https://user-images.githubusercontent.com/1409741/113712793-da0f1c80-96e6-11eb-8576-20d497511778.png)

---
Internal Tracking ID: [EXPOSUREAPP-6191](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6191)

**Comment by Ein-Tim** [comment]
Related issue: #1395

**Comment by jucktnich** [comment]
Sorry, didn't searched in closed issues. But I think it has to be changed to 13.7 or newer, right?

**Comment by Ein-Tim** [comment]
@jucktnich 

No problem, please leave this issue open. The situation has changed. It's not iOS 13.5 anymore, it's either iOS 12.5 or iOS 13.7. So this has to be addressed to Apple. 

Thanks for bringing it up again!

**Comment by dsarkar** [comment]
@Ein-Tim @jucktnich I can't find the story. Any trick or hint for me?

**Comment by jucktnich** [comment]
Search for corona-warn-app ➜ click on the app ➜ scroll down to bottom (or a little bit less on small devices) ➜ click on the picture with the woman walking and man riding bike

**Comment by Ein-Tim** [comment]
@dsarkar 

Go to the app store and search for CWA. When you see this screen: ! <img src="https://user-images.githubusercontent.com/67682506/113694646-4e8a9100-96d0-11eb-843b-113407f7257e.png" width="300">

Scroll all the way down and you'll see this: 
<img src="https://user-images.githubusercontent.com/67682506/113694685-5b0ee980-96d0-11eb-9925-cb6c9bec2590.png" width="300">

**Comment by jucktnich** [comment]
https://apps.apple.com/de/story/id1517388949 (german)

**Comment by dsarkar** [comment]
@jucktnich @Ein-Tim ok!! thanks!

**Comment by dsarkar** [comment]
Thanks!
---
Internal Tracking ID: [EXPOSUREAPP-6191](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6191)

**Comment by dsarkar** [comment]
Issue was forwarded to Apple.

**Comment by thomasaugsten** [comment]
Fixed

**Comment by jucktnich** [comment]
I think there's now another problem, iOS 13.7 is needed on iPhone 6s (and iPhone SE 1) or newer, not iPhone 7.

**Comment by thomasaugsten** [comment]
Already reported

**Comment by Ein-Tim** [comment]
Also fixed, they removed the sentence.

**Comment by dsarkar** [comment]
@jucktnich Thanks for reporting. We suggest to close this issue!

**Comment by jucktnich** [comment]
Close #2346
