### ISSUE TITLE
UX: Same info icon triggers two different behaviours 

### ISSUE THREAD

**Issue by benekuehn** [corona-warn-app/cwa-app-ios#236]
## Current Implementation
![info-icon](https://user-images.githubusercontent.com/41262108/83852006-6fcacb80-a713-11ea-90f3-166a869ff611.png)
Currently, the info icon triggers two different behaviours. Number 1 opens another view, number 2 opens a website in Safari.
## Suggested Enhancement
Use the same behaviour for the same UI elements.
## Expected Benefits
To ease the use of the app, behavioural patterns should be established and the same elements trigger the same action.

**Comment by EisvogelSAP** [comment]
Hey @benekuehn, thanks for pointing this out. The second icon was already removed from the current development branch a few days ago (or was it yesterday?).

**Comment by benekuehn** [comment]
@EisvogelSAP sorry for this one, my pull didnt work and I didnt noticed
