### ISSUE TITLE
Wiederholter F13 Fehler - case 4

### ISSUE THREAD

**Issue by jane1973** [corona-warn-app/cwa-app-ios#2387]
Meine App zeigt seit 2 Tagen wiederholt der Fehler F13 an und lässt sich nicht mehr aktualisieren.
iPhone 7 
![95944134-4F5D-4271-9F85-A5A172251FDF](https://user-images.githubusercontent.com/82117959/113922101-2b063a00-97e7-11eb-8fdc-7a93c4d9a9df.png)

Thanks for reporting a bug 🙌 ❤️

Before opening a new issue, please make sure that we do not have any duplicates already open. You can ensure this by searching the issue list for this repository. If there is a duplicate, please close your issue and add a comment to the existing issue instead.

Also, be sure to check our documentation first: https://github.com/corona-warn-app/cwa-documentation
-->

## Avoid duplicates
* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue

## Technical details

- Device name:
- iOS version:
- App version:

## Additional context

---
Internal Tracking ID: [EXPOSUREAPP-5836](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5836)

**Comment by Ein-Tim** [comment]
Hey @jane1973 👋

Danke das du diesen Bug gemeldet hast! Wir haben schon ähnliche Berichte in #2327, #2220 and #2316.

Um dieses Problem zu beheben, gehe bitte wie folgt vor:

1. Öffne die iOS Einstellungen
2. Scrolle hinunter bis zu "Begegnugnsmitteilugen"
3. Klicke auf "Corona-Warn-App"
4. Klicke nochmal auf "Corona-Warn-App"
5. Scrolle runter und deaktiviere "Begegnungsinformationen teilen"

Nach 24 Stunden kannst du die Option wieder aktivieren, danach sollte die App wieder funktionieren.

In der Zeit in der du "Begegnungsinformationen teilen" ausgeschaltet hast werden deine Kontakte nicht aufgezeichnet und dein Risiko wird nicht berechnet. 
Wenn du das nicht willst gib bescheid, es gibt noch andere Optionen, die aber manchmal nicht funktionieren.

---

Damit wir den Fehler analysieren können, wäre es perfekt wenn du den sog. EN-Log hier auf GitHub hochladen könntest (Anleitung  siehe unten). 

Teile uns bitte außerdem mit 
- deine iOS Version
- deine App Version
- dein iPhone Modell
- ob du einen Test registriert hast
- ob dir irgendwelche anderen Fehler aufgefallen sind bevor der Fehler auftrat


<details>
<summary>Anleitung zum exportieren von EN-Logs under iOS 13.7 or newer</summary>


`Einstellungen` ➡️ `Begegnungsmitteilungen` ➡️ `Status von Begegnungsaufzeichnungen` ➡️ `Begegnungsüberprüfungen` ➡️ `Überprüfungen exportieren`


**Um die Datei hier hochzuladen, benenne sie von .json zu .txt um oder komprimiere die Datei (.zip)**
</details>

**Comment by dsarkar** [comment]
Hi @jane1973,

vielen Dank fuer den Bericht. Wurde auf dem Telefon mit dem Problem kurz zuvor ein positives Testergebnis übermittelt? 

---

**Comment by jane1973** [comment]
Ja, wurde es

Von meinem iPhone gesendet

**Comment by dsarkar** [comment]
@jane1973 Danke fuer die Info. Und damit fing das Fehler-13 Problem an?

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-5836](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5836)

**Comment by jane1973** [comment]
Ja, genauso ist es

Von meinem iPhone gesendet

**Comment by jane1973** [comment]
Ja, genauso ist es

Von meinem iPhone gesendet

**Comment by Ein-Tim** [comment]
Hi @jane1973 

Danke für die Info mit dem positiven Test. 

Welche iOS Version und welche CWA-Version nutzt du?

**Comment by jane1973** [comment]
Hallo,

ich nutze iOS 14.4.2 und die CWA Version 1.15.2.(2).
Der Fehler liegt leider immer noch vor.


Von meinem iPhone gesendet

**Comment by Ein-Tim** [comment]
Danke @jane1973 für die Info! 

> Der Fehler liegt leider immer noch vor. 

Hast du das gemacht?:

1. Öffne die iOS Einstellungen
2. Scrolle hinunter bis zu "Begegnungsmitteilungen"
3. Klicke auf "Corona-Warn-App"
4. Klicke nochmal auf "Corona-Warn-App"
5. Scrolle runter und deaktiviere "Begegnungsinformationen teilen"

Nach 24 Stunden kannst du die Option wieder aktivieren, danach sollte die App wieder funktionieren.

In der Zeit in der du "Begegnungsinformationen teilen" ausgeschaltet hast werden deine Kontakte nicht aufgezeichnet und dein Risiko wird nicht berechnet. 
Wenn du das nicht willst gib bescheid, es gibt noch andere Optionen, die aber manchmal nicht funktionieren.

**Comment by jane1973** [comment]
Ja, genauso bin ich vorgegangen, aber der Fehler ist immer noch da. Letzte Aktualisierung ist 3 Tage her.

Von meinem iPhone gesendet

**Comment by Ein-Tim** [comment]
@jane1973 

Das ist natürlich sehr blöd. Und die Option war wirklich für 24 Stunden ausgeschaltet?

Hast du irgendwelche anderen Apps auf deinem Handy die auf Begegnungsmitteilungen zugreifen (wie RadarCovid aus Spanien)?

**Comment by jane1973** [comment]
Nein, ich habe keine andere Apo, die auf Begegnungsmitteilungen zugreift.
Ich habe mir keinen Wecker gestellt, als ich die App ausgeschaltet habe
Das kann ich natürlich noch machen.

Von meinem iPhone gesendet

**Comment by Ein-Tim** [comment]
@jane1973 

Bevor du es nochmal versuchst, könntest du bitte einen Screenshot hier hochladen? Dazu müsstest du aber auf die GitHub Website/App gehen, über Mail geht das nicht.

Der Screenshot wäre von: 

`Einstellungen` ➡️ `Begegnungsmitteilungen` ➡️ `Status von Begegnungsaufzeichnungen` ➡️ `Begegnungsüberprüfungen`

Wenn du mir dann noch sagst wann du Begegnungsmitteilungen aus hattest kann ich sehen ob auch in dieser Zeit falsche Anfragen and die Schnittstelle gemacht wurden.

**Comment by jane1973** [comment]
Ich habe die Begegnungsmitteilungen vor 10 Minuten ausgeschaltet und mir einen Wecker für morgen Abend gestellt.
Dann versuche ich es nochmal. Wenn es nicht klappt, sage ich Bescheid und lade den entsprechenden Screenshot hoch.

Von meinem iPhone gesendet

**Comment by Ein-Tim** [comment]
@jane1973 

Super, so machen wirs! 👍

**Comment by jane1973** [comment]
Hallo,
leider lässt die CWA sich nicht aktualisieren. Der Fehler ist zwar verschwunden, aber die Risikoprüfung und Aktualisierung funktioniert nicht.

Von meinem iPhone gesendet

**Comment by Ein-Tim** [comment]
Hi @jane1973

Diesmal wäre ein Screenshot der App sehr hilfreich! 
Sieht es in deinen Einstellungen von iOS jetzt wieder so aus:
<img src="https://user-images.githubusercontent.com/67682506/114231981-77827e80-997b-11eb-933b-9eab53c92a42.jpeg" width="300">

**Comment by jane1973** [comment]
Ja, so sieht es bei mir aus 


Von meinem iPhone gesendet

**Comment by Ein-Tim** [comment]
Ist "Als aktive Region festlegen" auch ausgegraut?

Könntest du bitte einen Screenshot der App hochladen? Das müsstest du aber über GitHub selber machen, das geht leider nicht per Mail.

**Comment by jane1973** [comment]
Und so sieht die App aus


Von meinem iPhone gesendet

**Comment by Ein-Tim** [comment]
@jane1973 

Leider können Screenshots nur mit der Website (www.github.com) oder mit der App hochgeladen werden.

**Comment by jane1973** [comment]
Ich weiß nicht genau, was du mit ausgegraut meinst. Ich hab nochmal nen neuen Screenshot gemacht.


Von meinem iPhone gesendet

**Comment by jane1973** [comment]
Ok, dann mache ich das

Von meinem iPhone gesendet

**Comment by Ein-Tim** [comment]
Vielen Dank für deine Hilfe @jane1973, und Entschuldigung für die Unannehmlichkeiten.

**Comment by jane1973** [comment]
![Uploading DFE96C5F-5BFF-4585-8105-6704E5919ECC.png…]()

**Comment by jane1973** [comment]
Danke für deine Hilfe!
![9DA4B4AB-76E7-4426-8C65-617A3E5DC928](https://user-images.githubusercontent.com/82117959/114233886-49eb0480-997e-11eb-8a2c-f74c1dca889d.png)

**Comment by jane1973** [comment]
![155510F1-793B-4FEB-A8A1-C3E18B89C336](https://user-images.githubusercontent.com/82117959/114233946-5b341100-997e-11eb-9591-7e78c1c00ead.png)

**Comment by Ein-Tim** [comment]
@jane1973 

Okay, danke für die Screenshots! 
Einen Moment bitte

**Comment by jane1973** [comment]
Die Hintergrundaktualisierung für die CWA habe ich eh ausgeschaltet. Leider funktioniert die manuelle Aktualisierung nicht.

Von meinem iPhone gesendet

**Comment by Ein-Tim** [comment]
@jane1973 

Okay das ist jetzt wirklich komisch. 
Hast du mal dein iPhone neugestartet?
Wenn nicht dann probiere das bitte.

**Comment by jane1973** [comment]
Ok, den Neustart probiere ich aus

Von meinem iPhone gesendet

**Comment by jane1973** [comment]
So, das Handy ist neu gestartet, die Aktualisierung funktioniert trotzdem nicht. Erst läuft eine zeit lang die Prüfung, dann schließt sich die App automatisch ohne Aktualisierung 

Von meinem iPhone gesendet

**Comment by Ein-Tim** [comment]
@jane1973 

Okay, so soll das definitiv nicht. Schließe bitte die App ganz (2x auf den Home Button drücken und dann die App nach oben swipen).

Dann bitte Hintergrundaktualisierung wieder anschalten und nochmal die App öffnen. 

Hoffe das hilft, sonst bin ich mit meinem Latein am Ende.

**Comment by thomasaugsten** [comment]
@jane1973 Kannst du bitte schauen ob unter
„Einstellungen“ > „Datenschutz“ > „Analyse & Verbesserungen“ > Analysedaten
Eine Date mit dem Namen ENA-2021......ips existiert.
Wenn ja kannst du sie mir bitte via E-Mail zukommen lassen
thomas.augsten@sap.com

**Comment by jane1973** [comment]
Jetzt hab ich wieder den F13 Fehler😔
Soll ich die App vielleicht komplett löschen und neu installieren?

Von meinem iPhone gesendet

**Comment by jane1973** [comment]
Da sind mehrere solcher Dates

Von meinem iPhone gesendet

**Comment by jane1973** [comment]
Soll ich dir alle schicken?

Von meinem iPhone gesendet

**Comment by thomasaugsten** [comment]
Die erste und die letze reichen

**Comment by jane1973** [comment]
Erledigt 

Von meinem iPhone gesendet

**Comment by thomasaugsten** [comment]
Dann kannst du die App jetzt löschen und morgen Abend wieder neuinstallieren

**Comment by jane1973** [comment]
Ok. Mache ich. Müssen wieder 24 Stunden dazwischen liegen?

Von meinem iPhone gesendet

**Comment by thomasaugsten** [comment]
Korrekt.

**Comment by Ein-Tim** [comment]
@thomasaugsten 

Lemme know if there's anything I can do to help to find the root cause of this. 🙂👍

**Comment by jane1973** [comment]
Ok. Wecker ist gestellt😉. Hoffe, es klappt morgen wieder. Vielen Dank!

Von meinem iPhone gesendet

**Comment by jane1973** [comment]
Die App funktioniert wieder! Vielen Dank!

Von meinem iPhone gesendet

**Comment by Ein-Tim** [comment]
Super @jane1973!

@thomasaugsten Do you need this issue open to give feedback on the root cause or can we close it?

**Comment by jane1973** [comment]
Ich muss leider sagen, dass der F13 Fehler wieder da ist.

Von meinem iPhone gesendet

**Comment by Ein-Tim** [comment]
@jane1973 

Könntest du nochmal einen Screenshot von dieser Liste hier hochladen (übe die GitHub Website).

Ich meine das was du siehst unter 
`Einstellungen` ➡️ `Begegnungsmitteilungen` ➡️ `Status von Begegnungsaufzeichnungen` ➡️ `Begegnungsüberprüfungen` ➡️.

Dann können wir sehen wie oft die App versucht eine Risiko-Überprüfung durchzuführen.

**Comment by jane1973** [comment]
![357C1655-7E35-4390-8B70-50BAD6EE7285](https://user-images.githubusercontent.com/82117959/114297792-07771400-9ab3-11eb-8c50-d8c1a9918df3.png)

**Comment by Ein-Tim** [comment]
Die App macht bei dir, genauso wie bei #2200 sehr viele falsche Risiko-Überprüfung kurz nacheinander (07:16 Uhr, 07:19 Uhr & 07:35 Uhr).

Bitte warte nun einfach 24 Std. ohne die App zu öffnen, eigentlich sollte sich das wieder Normalisieren.

**Comment by jane1973** [comment]
Ok. Probiere ich aus.

Von meinem iPhone gesendet

**Comment by Ein-Tim** [comment]
@dsarkar 

This was closed by mistake, could you reopen please?

**Comment by jane1973** [comment]
Ich habe die App jetzt 24 Stunden lang nicht geöffnet und auch die Hintergrundaktualisierung ausgeschaltet.
Leider lässt sich die App nicht manuell aktualisieren

**Comment by dsarkar** [comment]
Hi @jane1973, könntest du einen Screenshot hier hochladen? Danke! 


---
Corona-Warn-App Open Source Team

**Comment by jane1973** [comment]
![Uploading 7407E32B-F44E-4804-95B7-8B0D91340EE5.png…]()

**Comment by jane1973** [comment]
![15FB9B87-D350-4697-A972-EB7DB406EA72](https://user-images.githubusercontent.com/82117959/114371444-c816f900-9b80-11eb-90f4-488249f166ca.png)

**Comment by Ein-Tim** [comment]
@jane1973 

Das ist ein Bug, ich glaube @thomasaugsten guckt sich das näher an. 
Was passiert wenn du die Hintergrundaktualisierung einschaltest und die App öffnest?

**Comment by jane1973** [comment]
Dann versucht die App zu aktualisieren, das klappt nicht. Dann schaltet sie sich ab und wenn ich sie danach wieder öffne ist der F13 Fehler da.

Von meinem iPhone gesendet

**Comment by Ein-Tim** [comment]
Okay @jane1973 

Ich denke das du einen Bug hast den nur die App Entwickler lösen können, mir fällt nichts mehr ein (außer vielleicht die Daten der Begegnungsmitteilungen zu löschen, dadurch verlierst du aber alle aufgezeichneten Kontakte). 
Irgendwelche Ideen @thomasaugsten @dsarkar

**Comment by dsarkar** [comment]
@jane1973 Danke für die Infos. Mit 

> Dann schaltet sie sich ab ...

meinst du damit, dass die sich komplett selbst schliesst? 

2. Frage: Zwischenzeitlich hattest du die App gelöscht und neu installiert?

**Comment by jane1973** [comment]
Ja, sie schließt sich dann komplett selbst.
2. Ja, ich hatte die App 24 Stunden gelöscht und habe sie dann neu installiert 

Von meinem iPhone gesendet

**Comment by dsarkar** [comment]
@jane1973 Ok, danke erst mal. Wir leiten das weiter.


---
Corona-Warn-App Open Source Team

**Comment by jane1973** [comment]
Gibt es schon irgendwelche Neuigkeiten zu meiner CWA?

Von meinem iPhone gesendet

**Comment by dsarkar** [comment]
@jane1973 Es gibt noch keine Neuigkeiten. Wir haben einige Fehlerlogs von Nutzern der App bekommen, offenbar crashed die App bei einigen wenigen Benutzern beim Zugriff auf die Schnittstelle zu den Begegnungsmitteilungen. Auch wenn das Problem offenbar (bisher) nur sehr wenige Einzelfälle betrifft wird es ernst genommen, und die Entwickler schauen sich das Problem zur Zeit an. Danke für den Bericht und wir werden uns hier wieder melden, wenn noch mehr Information gebraucht wird, oder es Neuigkeiten zu berichten gibt. 

---
Corona-Warn-App Open Source Team

**Comment by jane1973** [comment]
Danke für die Information!

Von meinem iPhone gesendet

**Comment by Ein-Tim** [comment]
@jane1973 

Zeigt 

`Einstellungen` ➡️ `Begegnungsmitteilungen` ➡️ `Status von Begegnungsaufzeichnungen` ➡️ `Begegnungsüberprüfungen` ➡️ 

noch die Einträge der letzten 14 Tage?

**Comment by jane1973** [comment]
Ja, die Einträge gehen bis zum 30.3. zurück 

Von meinem iPhone gesendet

**Comment by Ein-Tim** [comment]
@jane1973 

Wenn es dir wichtig ist das die App wieder funktioniert hätte ich noch eine Idee. Allerdings würdest du alle aufgezeichneten Kontakte (und Tagebuch-Einträge sowie Testergebnis die in der App sind) verlieren. 

Wenn das OK für dich ist, mache folgendes:

1. Öffne die Einstellungen
2. Scrolle zu "Begegnungsmitteilungen" 
3. Klicke auf "Begegnungsmitteilungen deaktivieren"
4. Bestätige mit "Deaktivieren und Daten löschen"
5. Lösche die Corona-Warn-App
6. Installiere die Corona-Warn-App nach 24 Stunden neu

Ich kann dir nicht garantieren das das hilft, sollte es wirklich ein schwierigeres Problem sein kann es auch sein das das nichts hilft. 

Wie gesagt, nur wenn du möchtest, alternativ halt warten (:

**Comment by jane1973** [comment]
Ok. Ich überlege mal. Danke für den Tip!

Von meinem iPhone gesendet

**Comment by thomasaugsten** [comment]
@jane1973 Hi Jane könntest du mich bitte via E-Mail kontaktieren, ich würde gerne noch näheres darüber erfahren wie vielen anderen Corona Warn App Nutzer du im Durchschnitt begegnest.
thomas.augsten@sap.com

**Comment by Ein-Tim** [comment]
Version 2.1 which fixed the unintended occurrence of Error 13 has been released!

It will reach all users in the next 48 hours.

See GitHub Release: https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v2.1.1 

The PR that fixed this was #2492.

Please update your App, confirm the fix and then close this issue.

Thank you!

---

Die Version 2.1, die das unbeabsichtigte Auftreten des Fehlers 13 behebt, wurde veröffentlicht!

Sie wird in den nächsten 48 Stunden alle Nutzenden der CWA erreichen.

Siehe GitHub Release: https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v2.1.1 

Der PR, der den Fehler behoben hat, war #2492.

Bitte aktualisieren Sie Ihre App, bestätigen Sie den Fix und schließen Sie dann diesen Issue.

Danke!

**Comment by dsarkar** [comment]
Hi @jane1973,

Siehe den Kommentar oben von @Ein-Tim. Wir würden uns über Feedback von Dir freuen: Kannst Du bestätigen, dass der Fehler bei Dir nicht mehr auftaucht? Vielen Dank, Beste Gruesse, DS

---
Corona-Warn-App Open Source Team

**Comment by jane1973** [comment]
Der Fehler ist behoben. Vielen Dank!

**Comment by dsarkar** [comment]
@jane1973 Vielen Dank für das Feedback. Viele Grüsse, DS 


---
Corona-Warn-App Open Source Team
