### ISSUE TITLE
Fehler 13 verschwindet nicht nach 24 Stunden | Error 13 not disappearing after 24h

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#2395]
| No. | Issue | CWA | iOS | Test result | EN-Log | Fixed through workaround? |
| --- | --- | --- | --- | ----| --- | --- |
| 1. | #2220 | 1.14.4 | 14.4 | [Positive](https://github.com/corona-warn-app/cwa-app-ios/issues/2220#issuecomment-811025882) | [Yes](https://github.com/corona-warn-app/cwa-app-ios/issues/2220#issuecomment-800125110) | No, fixed itself |
| 2. | #2316 | 1.15.2 | 14.5 Beta 5 | [Positive](https://github.com/corona-warn-app/cwa-app-ios/issues/2316#issue-844977428) | No | Unknown whether fixed |
| 3. | #2327 | 1.15.2 | 14.4.1 | [Negative](https://github.com/corona-warn-app/cwa-app-ios/issues/2327#issuecomment-811848238) | No | Unknown whether fixed |
| 4. | https://github.com/corona-warn-app/cwa-app-ios/issues/2327#issuecomment-811984681 | 1.15.2 | 14.4.2 | [Positive](https://github.com/corona-warn-app/cwa-app-ios/issues/2327#issuecomment-811984681) | No | [Yes](https://github.com/corona-warn-app/cwa-app-ios/issues/2327#issuecomment-812612382) - 1 |
| 5. | #2387 | 1.15.2 | 14.4.2 | [Positive](https://github.com/corona-warn-app/cwa-app-ios/issues/2387#issuecomment-815491391) | No | fixed -closed |
| 6. | #2389 | 1.15.2 | 14.4 | No | No | [Yes](https://github.com/corona-warn-app/cwa-app-ios/issues/2389#issuecomment-816459870) - 2 |
| 7. | #2415 | Unknown | Unknown | Unknown | No | Not yet fixed |
| 8. | #2450 | Unknown | Unknown | Unknown | No | Not yet fixed |
| 9. | #2474 | Unknown | 14.4.2 | [Negative](https://github.com/corona-warn-app/cwa-app-ios/issues/2474#issuecomment-821869721) | [Yes](https://github.com/corona-warn-app/cwa-app-ios/issues/2474#issuecomment-821835797) | [Yes](https://github.com/corona-warn-app/cwa-app-ios/issues/2474#issuecomment-821881477) - 2  Fix 2.1 confirmed|
| 10. | #2485 | Unknown | Unknown | Unknown | No | Not yet fixed |
| 11. | #2519 | Unknown | Unknown | Unknown | No | fixed - closed|
| 12. | #2521 | Unknown | 14.4.2 | Unknown | No | Not yet fixed |
| 13. | #2545 | Unknown | Unknown | Unknown | No | Fixed after 2.1 - Closed |
| 14. | #2556 | Unknown | Unknown | Unknown | No | fixed - closed |
| 15. | #2758 | 2.2.1 | 14.5.1 | No | No | Not yet fixed |
| 16. | #2870 | 2.3.2 | 14.6 | Unknown | No | Not yet fixed |

Workarounds:

1. Hintergrundaktualisierung ausschalten | Deactivate Background app refresh
2. Begegnungsmitteilungen ausschalten | Deactivate Exposure Notifications
3. App löschen und erneut installieren | Delete app and install it again

---

Developers

- [X] Analyzing issue
- [x] Found root cause - See https://github.com/corona-warn-app/cwa-app-ios/issues/2387#issuecomment-818936478
- [X] Finished investigating - See https://github.com/corona-warn-app/cwa-app-ios/pull/2492#issue-619392650
- [X] Fix issue - See #2492 
- [X] Fix live - 2.1 [released](https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v2.1.1) on 02.05.2021

---

Internal Tracking ID: [EXPOSUREAPP-5836](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5836)

**Comment by dsarkar** [comment]
@Ein-Tim Many thanks !

**Comment by Ein-Tim** [comment]
Is #2492 how they want to fix the faulty Error-13 notifications?

**Comment by dsarkar** [comment]
@Ein-Tim Yes, indeed.

**Comment by ndegendogo** [comment]
Do I [understand correctly](https://github.com/corona-warn-app/cwa-app-ios/issues/2395#issuecomment-823338903) that the developers have already implemented a solution?
What is the planned timeline for release?

**Comment by jucktnich** [comment]
There's a or which priories the check, so if the background scheduler stops the tasks of the CWA the check should be done.

**Comment by ndegendogo** [comment]
Thanks @Ein-Tim and @jucktnich 

The bugfix was available just a bit too late to make it into the 2.0, yes? So now I hope very much that the release 2.1 with this bugfix will not be delayed again ... else the devs could consider to add a 2.0.4 to speed this up ...

**Comment by Ein-Tim** [comment]
@ndegendogo 

https://github.com/corona-warn-app/cwa-quicktest-onboarding/wiki/FAQ#ab-wann-k%C3%B6nnen-ergebnisse-aus-den-schnelltestzentren-in-die-corona-warn-app-%C3%BCbertragen-werden 
says the plan is to release the version with quick-test integration at the end of April. 
This is version 2.1, so yes, I'd also say at the end of April 😁

**Comment by ndegendogo** [comment]
Thanks @Ein-Tim 

End of April - this is pretty soon 😀😀

**Comment by Ein-Tim** [comment]
Version 2.1 which fixed the unintended occurrence of Error 13 has been released!

It will reach all users in the next 48 hours.

See GitHub Release: https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v2.1.1 

The PR that fixed this was #2492.

I'll leave this issue open until the fix has been confirmed.

**Comment by Ein-Tim** [comment]
I suggest to close the issue where we did not get any feedback. We have a new case on version 2.2 now already: https://github.com/corona-warn-app/cwa-app-ios/issues/2758

**Comment by Ein-Tim** [comment]
@dsarkar Please see https://github.com/corona-warn-app/cwa-app-ios/issues/2395#issuecomment-851064717 with the suggestion to close the issue where we did not get any feedback (but #2758).

This will be helpful since the first iOS 15 beta will be released today, and I'm expecting that it will introduce some issues. To keep the issue tracker clean, I think we should close some of the non relevant issues.
If you or anyone else have a different opinion on this, just let me know.

**Comment by Ein-Tim** [comment]
I'll now close this issue, since the only two active issues are #2758 & #2870. 
We don't need an overview for them.

**Comment by dsarkar** [comment]
@Ein-Tim Thanks for managing this overview issue!
