### ISSUE TITLE
[CWA-Docu] MIT License is not customised

### ISSUE THREAD

**Issue by jucktnich** [corona-warn-app/cwa-app-ios#2413]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name:
- iOS version:
- App version:

## Describe the bug

The mit license is not customised. (Year and contributors are only placeholders)

## Additional context

---
Internal Tracking ID: [EXPOSUREAPP-6343](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6343)

**Comment by Ein-Tim** [comment]
Link to file: https://github.com/corona-warn-app/cwa-app-ios/blob/release/2.1.x/LICENSES/MIT.txt

**Comment by dsarkar** [comment]
@jucktnich @Ein-Tim Thanks. Internal Tracking ID: [EXPOSUREAPP-6343](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6343)

**Comment by dsarkar** [comment]
@Ein-Tim, @jucktnich regarding this issue: "... Adding RKI or SAP as copyright holder would be wrong as the MIT license is only for the external copyright holders of copied and integrated source code." 

This file is a template being used by another tool.

**Comment by Ein-Tim** [comment]
@dsarkar @jucktnich

I suggest to close this issue now.

**Comment by dsarkar** [comment]
@jucktnich Thanks for all the contributions in general. We will close this issue now. Thanks again.

---
Corona-Warn-App Open Source Team
