### ISSUE TITLE
Fehler 13 verschwindet nach 24h nicht 

### ISSUE THREAD

**Issue by xthommy81x** [corona-warn-app/cwa-app-ios#2415]
## Avoid duplicates
* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue

## Technical details

- Device name:
- iOS version:
- App version:

## Additional context

---
Internal Tracking ID: [EXPOSUREAPP-5836](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5836)

**Comment by Ein-Tim** [comment]
Hey @jane1973 👋

Danke das du diesen Bug gemeldet hast! Wir haben schon ähnliche Berichte in #2327, #2220, #2316 & #2387.

Um dieses Problem zu beheben, gehe bitte wie folgt vor:

1. Öffne die iOS Einstellungen
2. Scrolle hinunter bis zu "Begegnungsmitteilungen"
3. Klicke auf "Corona-Warn-App"
4. Klicke nochmal auf "Corona-Warn-App"
5. Scrolle runter und deaktiviere "Begegnungsinformationen teilen"

Nach 24 Stunden kannst du die Option wieder aktivieren, danach sollte die App wieder funktionieren.

In der Zeit in der du "Begegnungsinformationen teilen" ausgeschaltet hast werden deine Kontakte nicht aufgezeichnet und dein Risiko wird nicht berechnet. 
Wenn du das nicht willst gib bescheid, es gibt noch andere Optionen, die aber manchmal nicht funktionieren.

---

Damit wir den Fehler analysieren können, wäre es perfekt wenn du den sog. EN-Log hier auf GitHub hochladen könntest (Anleitung  siehe unten). 

Teile uns bitte außerdem mit 
- deine iOS Version
- deine App Version
- ob du einen Test registriert hast
- ob dir irgendwelche anderen Fehler aufgefallen sind bevor der Fehler auftrat


<details>
<summary>Anleitung zum exportieren von EN-Logs unter iOS 13.7 oder neuer</summary>


`Einstellungen` ➡️ `Begegnungsmitteilungen` ➡️ `Status von Begegnungsaufzeichnungen` ➡️ `Begegnungsüberprüfungen` ➡️ `Überprüfungen exportieren`


**Um die Datei hier hochzuladen, benenne sie von .json zu .txt um oder komprimiere die Datei (.zip)**
</details>

**Comment by dsarkar** [comment]
Hi @xthommy81x,

 Thanks again for reporting. Could you please give us more information as @Ein-Tim requested? Feedback very much appreciated. Best, DS

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-5836](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5836)

**Comment by Ein-Tim** [comment]
Version 2.1 which fixed the unintended occurrence of Error 13 has been released!

It will reach all users in the next 48 hours.

See GitHub Release: https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v2.1.1 

The PR that fixed this was #2492.

Please update your App, confirm the fix and then close this issue.

Thank you!

---

Die Version 2.1, die das unbeabsichtigte Auftreten des Fehlers 13 behebt, wurde veröffentlicht!

Sie wird in den nächsten 48 Stunden alle Nutzenden der CWA erreichen.

Siehe GitHub Release: https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v2.1.1 

Der PR, der den Fehler behoben hat, war #2492.

Bitte aktualisieren Sie Ihre App, bestätigen Sie den Fix und schließen Sie dann diesen Issue.

Danke!

**Comment by dsarkar** [comment]
Hi @xthommy81x,

Siehe den Kommentar oben von @Ein-Tim. Wir würden uns über Feedback von Dir freuen: Kannst Du bestätigen, dass der Fehler bei Dir nicht mehr auftaucht? Vielen Dank, Beste Gruesse, DS

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
Same here, please close these issues.

**Comment by heinezen** [comment]
Hello everyone,

Occurences of Error 13/Fehler 13 should be fixed with the recent CWA release 2.5. Please update your app and report back if the error still persists for you when using the newest version. We will close the issue for now.

----
Corona-Warn-App Open Source Team
