### ISSUE TITLE
White Overlay at statistics card in darkmode

### ISSUE THREAD

**Issue by jucktnich** [corona-warn-app/cwa-app-ios#2417]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: iPhone SE 1
- iOS version: 14.4.2
- App version: 1.15.2

## Describe the bug

When you click on the info button on a statistics card in darkmode, there's a white overlay (like on white mode I think).

## Steps to reproduce the issue

1. activate darkmode

2. go to the statistics card

3. touch and hold the info button

## Expected behaviour

Black overlay for darkmode.

## Possible Fix

Change the overlay for darkmode to (0, 0, 0, 0.5).

---
Internal Tracking ID: [EXPOSUREAPP-6371](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6371)

**Comment by Ein-Tim** [comment]
Good point, you can see how it should look like when pressing the "i" in the top right corner.

Adding a screen recoding here:


https://user-images.githubusercontent.com/67682506/114318881-420e9a00-9b0f-11eb-9ec3-35dee0d634cd.mov

**Comment by dsarkar** [comment]
@jucktnich @Ein-Tim Thanks. Internal Tracking ID: [EXPOSUREAPP-6371](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6371)

---
Corona-Warn-App Open Source Team

**Comment by bgeisb** [comment]
I have implemented a solution to the issue (see #4390).

**Comment by Ein-Tim** [comment]
@marcussc or @dsarkar 

Could you please apply a `Fix 2.21` label here?

**Comment by Ein-Tim** [comment]
Confirm fixed with version 2.21.

**Comment by dsarkar** [comment]
@Ein-Tim Thanks for the feedback, forwarded the CONFIRM to internal ticket.
