### ISSUE TITLE
[Bug] Notification settings broken if authorization skipped during onboarding

### ISSUE THREAD

**Issue by sebastianpicklum** [corona-warn-app/cwa-app-ios#242]
## Describe the bug

When skipping notification authorization during onboard, the notification settings are broken
* When accessing the notification settings, an authorization popup occurs unexpectedly
* If this popup occurence is fixed, then the settingsOff becomes pointless as a user won't be able to activate the notifications in the iOS settings app as they new will be registered

## Expected behaviour

* Skipping the notification authorization will let the user enable the notifications later through the settings menu
* No unexpected popups should occour

## Steps to reproduce the issue
General:
1. Perform Onboarding, but skip notification authorization
2. Open settings 
3. Tap on notifications -> Popup occurs

iOS Settings issue:
Remove the authorization requests in the settings controllers
1. Perform Onboarding, but skip notification authorization
2. Open settings 
3. Tap on notifications
4. Tap to open iOS Settings -> No notifications settings availabile

## Technical details

- iPhone 8 Simulator w/ iOS 13.5

## Possible Fix

To my best knowledge, there is no way to register notifications in the iOS settings without an pop-up appearing.

I've already created a pull request #201 that would fix this issue by tracking if a user skipped notification authorization during onboard and provide a nicer way to enable them later.
#201 was intended to get rid of the unexpected popup, but I've just realized that the underlying issue is more severe than I've initially thought.

**Comment by sebastianpicklum** [comment]
@inf2381 Just to be sure: You are already working on this?

Otherwise I'd modify this PR to have the checks for authorisation directly on the toggle switches which shouldn't change the UX at all.

**Comment by inf2381** [comment]
@sebastianpicklum Sorry for the late response. Does #674 provide the fixes you intended?

**Comment by sebastianpicklum** [comment]
Thanks for the info. I've added a comment to #674 since there is still a case where a popup appears when it shouldn't
