### ISSUE TITLE
Scrolling Issues in Contact Journal Details 

### ISSUE THREAD

**Issue by riconeitzel** [corona-warn-app/cwa-app-ios#2436]
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: iPhone Xs
- iOS version: 14.4.2
- App version: 1.15.2 (2)

## Describe the bug

When you open up the contact journal details for one day the places (and sometimes the people) tab have a small scroll indicator (looks like there are hundreds of entries). If you start to scroll it sometimes lacks scrolling performance and jumps weirdly to the end and back to the top or vice versa. 

## Steps to reproduce the issue

1. Open the journal tab
2. Open details for one day
3. switch to places tab (make sure it has about 30 entries)
4. select one place
5. try to scroll up or down

## Expected behaviour

Expected: if you open the places tab, the scroll indicator should be correct
Actual: the indicator is too small and changes size once you start to scroll

Expected: smooth scrolling after selecting one item
Actual: poor scrolling performance, jumping weirdly to the end or somewhere else

A screen recording can be provided! Please contact me directly (personal data shown in screen recording)

---
Internal Tracking ID: [EXPOSUREAPP-6368](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6368)

**Comment by Ein-Tim** [comment]
Can confirm this bug. Didn't report it because I think it's fixed in the upcoming version 2.0 release.

Adding here that this is not only about the places but also about the people tab.

**Comment by Jakre73** [comment]
I have 41 contacts in my list and can reproduce this behavior with App version 1.15.2 (iOS 14.5) on an iPhone 12 Pro Max (A2411). There is another issue with the choppy scroll animation: As soon as you´re selecting a contact for a day and the details (e.g. longer 15 minutes/without mask/inside) are shown up it starts to get jerky and sometimes the list even jumps down to the last entity.

**Comment by Ein-Tim** [comment]
Adding a video here:

https://user-images.githubusercontent.com/67682506/114542333-15b26500-9c58-11eb-8858-bb68a2469af2.MP4

**Comment by Ein-Tim** [comment]
This should be fixed in version 2.0, can you confirm @riconeitzel & @Jakre73?

**Comment by riconeitzel** [comment]
Hi @Ein-Tim … 

yes! fixed 👏🏻👏🏻👏🏻 🚀

Thanks!

**Comment by dsarkar** [comment]
@riconeitzel Thanks for the feedback!
