### ISSUE TITLE
F13 bleibt seit 7 Tagen bestehen - case 8

### ISSUE THREAD

**Issue by faVo1994** [corona-warn-app/cwa-app-ios#2450]
Fehler 13 bleibt seit 7 Tagen in der App stehen..

## Avoid duplicates
* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue

## Technical details

- Device name:
- iOS version:
- App version:

## Additional context

---
Internal Tracking ID: [EXPOSUREAPP-5836](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5836)

**Comment by dsarkar** [comment]
Hi @faVo1994 Danke für en Report. Wir haben mehrere ähnliche Bereiche bekommen. Könnest Du bitte weitere Information liefern, siehe dazu: https://github.com/corona-warn-app/cwa-app-ios/issues/2387#issuecomment-815173737

Viele Grüsse, DS

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-5836](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5836)

**Comment by Ein-Tim** [comment]
Version 2.1 which fixed the unintended occurrence of Error 13 has been released!

It will reach all users in the next 48 hours.

See GitHub Release: https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v2.1.1 

The PR that fixed this was #2492.

Please update your App, confirm the fix and then close this issue.

Thank you!

---

Die Version 2.1, die das unbeabsichtigte Auftreten des Fehlers 13 behebt, wurde veröffentlicht!

Sie wird in den nächsten 48 Stunden alle Nutzenden der CWA erreichen.

Siehe GitHub Release: https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v2.1.1 

Der PR, der den Fehler behoben hat, war #2492.

Bitte aktualisieren Sie Ihre App, bestätigen Sie den Fix und schließen Sie dann diesen Issue.

Danke!

**Comment by dsarkar** [comment]
Hi @faVo1994,

Siehe den Kommentar oben von @Ein-Tim. Wir würden uns über Feedback von Dir freuen: Kannst Du bestätigen, dass der Fehler bei Dir nicht mehr auftaucht? Vielen Dank, Beste Gruesse, DS

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
Can this issue please be closed due to missing feedback?

**Comment by heinezen** [comment]
Hello everyone,

Occurences of Error 13/Fehler 13 should be fixed with the recent CWA release 2.5. Please update your app and report back if the error still persists for you when using the newest version. We will close the issue for now.

----
Corona-Warn-App Open Source Team
