### ISSUE TITLE
Fehler13 nach 5 Tagen

### ISSUE THREAD

**Issue by manuel1960elmama** [corona-warn-app/cwa-app-ios#2474]
## Avoid duplicates
* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue

## Technical details

- Device name:
- iOS version:
- App version:

**Comment by Ein-Tim** [comment]
Hey @manuel1960elmama 👋

Danke das du diesen Bug gemeldet hast! Wir haben schon ähnliche Berichte, siehe #2395.

Um dieses Problem zu beheben, gehe bitte wie folgt vor:

1. Öffne die iOS Einstellungen
2. Scrolle hinunter bis zu "Begegnungsmitteilungen"
3. Klicke auf "Corona-Warn-App"
4. Klicke nochmal auf "Corona-Warn-App"
5. Scrolle runter und deaktiviere "Begegnungsinformationen teilen"

Nach 24 Stunden kannst du die Option wieder aktivieren, danach sollte die App wieder funktionieren.

In der Zeit in der du "Begegnungsinformationen teilen" ausgeschaltet hast werden deine Kontakte nicht aufgezeichnet und dein Risiko wird nicht berechnet. 
Wenn du das nicht willst gib bescheid, es gibt noch andere Optionen, die aber manchmal nicht funktionieren.

---

Damit wir den Fehler analysieren können, wäre es perfekt wenn du den sog. EN-Log hier auf GitHub hochladen könntest (Anleitung  siehe unten). 

Teile uns bitte außerdem mit 
- deine iOS Version
- deine App Version
- ob du einen Test registriert hast
- ob dir irgendwelche anderen Fehler aufgefallen sind bevor der Fehler auftrat


<details>
<summary>Anleitung zum exportieren von EN-Logs unter iOS 13.7 oder neuer</summary>


`Einstellungen` ➡️ `Begegnungsmitteilungen` ➡️ `Status von Begegnungsaufzeichnungen` ➡️ `Begegnungsüberprüfungen` ➡️ `Überprüfungen exportieren`


**Um die Datei hier hochzuladen, benenne sie von .json zu .txt um oder komprimiere die Datei (.zip)**
</details>

**Comment by manuel1960elmama** [comment]
Hi Tim,
Anbei mein EN-Log als .txt
iOS Version 14.4.2
App Version iPhone 11
Ja, ich hatte am Di 6.04. einen PCR-Test hochgeladen und vor ich glaube zwei Tage wieder gelöscht.
Viele Grüße
Manuel
[ExposureChecks-2021-04-17.txt](https://github.com/corona-warn-app/cwa-app-ios/files/6329445/ExposureChecks-2021-04-17.txt)

**Comment by dsarkar** [comment]
@Ein-Tim Thanks.
@manuel1960elmama 

- Danke fuer den Bericht und vor allen Dingen das EN-LOG file. 
- Wir haben inzwischen mehrere Berichte über diesen Fehler, die im Zusammenhang eines positiven Test-Ergebnisses wohl auftauchen. 
- Der Fall, über den Du hier berichtest, ging dem Fehler 13 ein positives Test-Ergebnis voraus?
- Wurde der Test / Ergebnis automatisch oder manuell gelöscht?

Danke für das Feedback. Die Entwickler schauen sich das Problem an, aber jede weitere Information kann sehr hilfreich sein und ist sehr willkommen. 

Viele Grüsse, DS

---
Corona-Warn-App Open Source Team

**Comment by manuel1960elmama** [comment]
Hi DS,
Mein Test war negativ und ich habe ihn manuell gelöscht.
Viele Grüße, Manuel


Sent from my iPhone
+49 175 936 97 64

**Comment by Ein-Tim** [comment]
@dsarkar 

Please edit @manuel1960elmama last comment, there‘s a phone number which I assume is unintended.

@manuel1960elmama 

Probierst du meinen Workaround den ich in der ersten Nachricht geschrieben habe aus? 
Das wäre super!

**Comment by manuel1960elmama** [comment]
HI Tim,
Ja, hatte die Überprüfung deaktiviert und gerade wieder aktiviert, läuft alles sauber.

Herzliche Grüße, Manuel


Sent from my iPhone
+49 175 936 97 64

**Comment by Ein-Tim** [comment]
@manuel1960elmama 

Du meinst, es geht schon wieder? Das wäre ja super!

**Comment by manuel1960elmama** [comment]
Yes :-)


Von meinem iPad gesendet

**Comment by Ein-Tim** [comment]
@dsarkar Do you need this open if it's already fixed? I'd suggest to focus on the other cases that aren't fixed yet & close this issue.

**Comment by Ein-Tim** [comment]
In the EN-Log provided by @manuel1960elmama I see some faulty ENF calls that aren't 4 hours apart (for example on the 16.04., there was one at 23:48h and the next one wasn't 4 hours later but only 40 minutes (00:20h))

**Comment by dsarkar** [comment]
@Ein-Tim @manuel1960elmama Let's keep open some days. We would appreciate some feedback in a couple of days, if the error hasn't occurred again. Thanks.

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
Version 2.1 which fixed the unintended occurrence of Error 13 has been released!

It will reach all users in the next 48 hours.

See GitHub Release: https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v2.1.1 

The PR that fixed this was #2492.

Please update your App, confirm the fix and then close this issue.

Thank you!

---

Die Version 2.1, die das unbeabsichtigte Auftreten des Fehlers 13 behebt, wurde veröffentlicht!

Sie wird in den nächsten 48 Stunden alle Nutzenden der CWA erreichen.

Siehe GitHub Release: https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v2.1.1 

Der PR, der den Fehler behoben hat, war #2492.

Bitte aktualisieren Sie Ihre App, bestätigen Sie den Fix und schließen Sie dann diesen Issue.

Danke!

**Comment by dsarkar** [comment]
Hi @manuel1960elmama,

Siehe den Kommentar oben von @Ein-Tim. Wir würden uns über Feedback von Dir freuen: Kannst Du bestätigen, dass der Fehler bei Dir nicht mehr auftaucht? Vielen Dank, Beste Gruesse, DS

---
Corona-Warn-App Open Source Team

**Comment by manuel1960elmama** [comment]
Hi zusammen,

yep, der Fehler ist nicht mehr aufgetreten, lieben Dank für euren Support.

Viele Grüße
Manuel

**Comment by dsarkar** [comment]
@manuel1960elmama Vielen Dank für das Feedback! Wir überlassen gerne dem Autor eines Issues den Thread selbst zu schliessen. Viele Grüße, DS 

--> ![image](https://user-images.githubusercontent.com/1409741/116881866-140b0a00-ac24-11eb-86ef-640d8ecc5c1a.png)

---
Corona-Warn-App Open Source Team
