### ISSUE TITLE
3 Dot Menu Symbol is in false thickness

### ISSUE THREAD

**Issue by jucktnich** [corona-warn-app/cwa-app-ios#2495]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: iPhone SE 1
- iOS version: 14.4.2
- App version: 2.0.3 (1)

## Describe the bug

- The 3 Dot Menu in the check-in and contact journal tab is not in normal thickness. I don't know, if this is intended, but it neither matches other symbols nor looks nice imho.
- the 3 dot symbol is a little bit smaller then the i icon. Also the the i icon is resizable if you change your os font size, but the 3 dot menu isn't. Maybe the 3 dot icon is SF symbols, while the 3 dot menu isn't...

## Steps to reproduce the issue

Go to the checkin or contact journal tab and there's in the top right corner this menu-item.

## Expected behaviour

Normal thickness of the icon.

## Additional context

---
Internal Tracking ID: [EXPOSUREAPP-6627](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6627)

**Comment by riconeitzel** [comment]
Can you post a screenshot? I can see it in the same style as the (i) on the Start Screen … latest app version, iPhone Xs, latest iOS

**Comment by jucktnich** [comment]
![image](https://user-images.githubusercontent.com/73582096/115536084-ae209900-a299-11eb-8f3f-ce89858fa506.png)
Every 3 dot menus I found are same.

**Comment by riconeitzel** [comment]
![IMG_3414](https://user-images.githubusercontent.com/930706/115540311-402aa080-a29e-11eb-945f-d012e71363ac.jpeg)
![IMG_3415](https://user-images.githubusercontent.com/930706/115540314-415bcd80-a29e-11eb-9f77-6fb578e0d08c.jpeg)

**Comment by jucktnich** [comment]
I think there's also a difference in thickness, but not that much like on smaller devices.

**Comment by jucktnich** [comment]
I just found out, that the 3 dot symbol is a little bit smaller then the i icon. Also the the i icon is resizable if you change your os font size, but the 3 dot menu isn't. Maybe the 3 dot icon is SF symbols, while the 3 dot menu isn't...

**Comment by riconeitzel** [comment]
now here in that LARGE scale … I would say: correct … line width is different.

**Comment by dsarkar** [comment]
@riconeitzel @jucktnich Thanks. Internal Tracking ID: [EXPOSUREAPP-6627](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6627)


---
Corona-Warn-App Open Source Team

**Comment by 30mar** [comment]
will set to obsolete as described in the attached jira ticket.
