### ISSUE TITLE
Missing illustration in „My Check-Ins“ screen

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#2497]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
**Not sure, please check**
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone XR
- iOS version: 14.5 RC
- App version: 2.0.3

## Describe the bug

The "My Check-Ins" screen is [completely empty](https://user-images.githubusercontent.com/67682506/115528991-cfca5200-a292-11eb-87ed-6f35f34a1218.png) if the user hasn't checked-in somewhere. 
This is not the intended behavior, there should be an illustration like in the "My QR-Codes" screen.

## Steps to reproduce the issue

1. Open CWA
2. Click on "Check In" on the tab bar
3. See empty "My Check-Ins" screen
 

## Expected behaviour

There should be an illustration like in the "My QR-Codes" screen.

## Possible Fix

Add the illustration.

---
Internal Tracking ID: [EXPOSUREAPP-6508](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6508)

**Comment by jucktnich** [comment]
I also didn't saw the illustration, but then, i don't know what I did, the illustration appeared.

**Comment by Ein-Tim** [comment]
@jucktnich 

There are some situations where the illustration is shown, but the most of the time it isn't.

**Comment by riconeitzel** [comment]
You can click "remove all" then the illustration is shown. Still it's fine as it shows My Check-Ins + Button to scan … so I didn't scan anything and would ne expect any further info on the screen 😄

**Comment by jucktnich** [comment]
I also would suggest to make the illustration scrollable or add a background to the overlay.

**Comment by dsarkar** [comment]
@jucktnich I suggest to create a separate issue in the wishlist repo for new features or enhancements.

**Comment by dsarkar** [comment]
@Ein-Tim So, the bug is basically that no image shown initially and then after removing all QR codes the image appears. Is that correct?

**Comment by jucktnich** [comment]
This can also be triggered by discarding the qr code scanner, so I think, every time there's the possibility to change if it should appear, the app checks if there's are 0 qr codes, but forgets about it at startup.

**Comment by jucktnich** [comment]
On src/xcode/ENA/ENA/Source/Scenes/Checkin/Overview/CheckinsOverviewViewModel.swift there's a var called isEmptyStateVisible wich is used, if I got it right, by src/xcode/ENA/ENA/Source/Scenes/Checkin/Overview/CheckinsOverviewViewController.swift to decide whether or not to show a background.

**Comment by Ein-Tim** [comment]
Sorry, was a busy day, answering now:

1. The correct screen is shown after removing check ins once you checked in somewhere. After a restart of the app the empty screen is shown again. This is definitely a bug.
2. @riconeitzel Please refer to the empty contact journal or the empty "Create QR Code". There you can see that the app shows such an illustration if there's nothing to show.
3. @jucktnich Thank you for investigating!

@dsarkar FYI, I'm currently updating the overviews, there were many issues with the release of version 2.0. Please mirror the overviews back into JIRA tomorrow. Thank you!

**Comment by marcussc** [comment]
Was already solved for 2.1: https://github.com/corona-warn-app/cwa-app-ios/pull/2468

**Comment by Ein-Tim** [comment]
Thank you @marcussc!

**Comment by Ein-Tim** [comment]
Version 2.1 which fixed this has been released to GitHub and is available to all users in the next 48h. 

See GitHub release:

iOS: https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v2.1.1

This issue will now be closed.

**Comment by dsarkar** [comment]
@Ein-Tim Thanks.
