### ISSUE TITLE
Error 13 - case 11

### ISSUE THREAD

**Issue by annakristinak** [corona-warn-app/cwa-app-ios#2519]
## Avoid duplicates
* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue

## Technical details

- Device name:
- iOS version:
- App version:

**Comment by Ein-Tim** [comment]
Hi @annakristinak 👋

Do you have a question reg. the Corona-Warn-App or experience any problems? 
If yes, please comment on this issue and let us know. 🙂
Thank you and stay safe! 

Regards Tim

**Comment by annakristinak** [comment]
Hey,
The app stopped functioning on Monday and no longer tracks my risk-contacts. Ist says Error 13: which seems to be common on iOS.

**Comment by Ein-Tim** [comment]
Hi, we've already got some similar reports, see #2495
A fix has already bern merged (#2492) and will be included in the next version, 2.1. 

Until this version is published, you can try these steps (German only - currently):

1. Öffne die iOS Einstellungen
2. Scrolle hinunter bis zu "Begegnungsmitteilungen"
3. Klicke auf "Corona-Warn-App"
4. Klicke nochmal auf "Corona-Warn-App"
5. Scrolle runter und deaktiviere "Begegnungsinformationen teilen"

Nach 24 Stunden kannst du die Option wieder aktivieren, danach sollte die App wieder funktionieren.

In der Zeit in der du "Begegnungsinformationen teilen" ausgeschaltet hast werden deine Kontakte nicht aufgezeichnet und dein Risiko wird nicht berechnet. 
Wenn du das nicht willst gib bescheid, es gibt noch andere Optionen, die aber manchmal nicht funktionieren.

**Comment by Ein-Tim** [comment]
Version 2.1 which fixed the unintended occurrence of Error 13 has been released!

It will reach all users in the next 48 hours.

See GitHub Release: https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v2.1.1 

The PR that fixed this was #2492.

Please update your App, confirm the fix and then close this issue.

Thank you!

---

Die Version 2.1, die das unbeabsichtigte Auftreten des Fehlers 13 behebt, wurde veröffentlicht!

Sie wird in den nächsten 48 Stunden alle Nutzenden der CWA erreichen.

Siehe GitHub Release: https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v2.1.1 

Der PR, der den Fehler behoben hat, war #2492.

Bitte aktualisieren Sie Ihre App, bestätigen Sie den Fix und schließen Sie dann diesen Issue.

Danke!

**Comment by dsarkar** [comment]
Hi @annakristinak,

Siehe den Kommentar oben von @Ein-Tim. Wir würden uns über Feedback von Dir freuen: Kannst Du bestätigen, dass der Fehler bei Dir nicht mehr auftaucht? Vielen Dank, Beste Gruesse, DS

---
Corona-Warn-App Open Source Team

**Comment by annakristinak** [comment]
Hi, der Fehler taucht nicht mehr auf. Vielen Dank für die Hilfe! 


Gesendet von Yahoo Mail für iPhone


Am Montag, Mai 3, 2021, 3:07 PM schrieb dsarkar ***@***.***>:




Hi @annakristinak,

Siehe den Kommentar oben von @Ein-Tim. Wir würden uns über Feedback von Dir freuen: Kannst Du bestätigen, dass der Fehler bei Dir nicht mehr auftaucht? Vielen Dank, Beste Gruesse, DS

Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
@annakristinak  Vielen Dank für das Feedback. Viele Grüsse, DS 


---
Corona-Warn-App Open Source Team
