### ISSUE TITLE
Rename the Infos Button in Check-in Page

### ISSUE THREAD

**Issue by DerVogel2020** [corona-warn-app/cwa-app-ios#2543]
## Current Implementation

Press the 3 dot button, it says Infos instead of Informationen, as it is in the Tagebuch page.

## Suggested Enhancement

Rename to "Informationen"

## Expected Benefits

---
Internal Tracking ID: [EXPOSUREAPP-6853](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6853)

**Comment by DerVogel2020** [comment]
See #2549 in cwa-app-android.

**Comment by Ein-Tim** [comment]
PR #2544

**Comment by Ein-Tim** [comment]
#2544 has been merged into the `Release/2.2.x` branch.

**Comment by DerVogel2020** [comment]
Fixed in Version 2.2.

**Comment by dsarkar** [comment]
@DerVogel2020 Thanks.
