### ISSUE TITLE
Fehler 13

### ISSUE THREAD

**Issue by Anette841** [corona-warn-app/cwa-app-ios#2545]
Kein Zugriff auf Corona-Warn App seit 4 Tagen wegen Fehler 13. Auch 24 Stunden warten ändert nichts. 

---
Internal Tracking ID: EXPOSUREAPP-5836

**Comment by Ein-Tim** [comment]
Hey @Anette841 👋

Wir haben schon ähnliche Berichte, siehe #2395.
Ein Fix wurde bereits gemerged (#2492) und wird mit der nächsten Version, 2.1, ausgespielt. 

Bis dahin kannst du folgendes versuchen: 

1. Öffne die iOS Einstellungen
2. Scrolle hinunter bis zu "Begegnungsmitteilungen"
3. Klicke auf "Corona-Warn-App"
4. Klicke nochmal auf "Corona-Warn-App"
5. Scrolle runter und deaktiviere "Begegnungsinformationen teilen"

Nach 24 Stunden kannst du die Option wieder aktivieren, danach sollte die App wieder funktionieren.

In der Zeit in der du "Begegnungsinformationen teilen" ausgeschaltet hast werden deine Kontakte nicht aufgezeichnet und dein Risiko wird nicht berechnet. 
Wenn du das nicht willst gib bescheid, es gibt noch andere Optionen, die aber manchmal nicht funktionieren.

**Comment by Anette841** [comment]
Hey Tim,

danke für die Info. Bin der Anleitung gefolgt und habe jetzt die Begegnungsinfos wieder aktiviert.

Nun fliege ich aber bei der Überprüfung der Daten raus... was tun?

Nächtliche Grüße von Anette 

Von meinem iPhone gesendet

**Comment by Ein-Tim** [comment]
Hey @Anette841 

Das ist leider auch nicht das erste mal das wir davon hören das die App abstürzt. 

Versuch mal das Folgende: 

1. iOS-Einstellungen öffnen
2. Nach "Corona-Warn" suchen
3. Deaktiviere "Hintergrundaktualisierung"

Nun gibt es in der App einen Button "Aktualisieren". 
Diesen bitte **nicht** klicken, erst nochmal 24 Stunden warten, die App nicht öffnen! 
Morgen dann die App öffnen und die App geöffnet lassen während die App (hoffentlich) eine Risiko-Überprüfung durchführt, ohne Abzustürzen. 
Danach kannst du dich hier nochmal melden.

Sollte das nicht helfen musst du wohl leider auf Version 2.1 warten.

**Comment by dsarkar** [comment]
Internal Tracking ID: EXPOSUREAPP-5836

**Comment by Anette841** [comment]
Hey Tim,

hat kurz funktioniert... jetzt bin ich wieder bei Fehler 13 🙈... vermutlich war ich wieder zu oft drin 🤔

Jetzt nochmal 24 Stunden... 

Melde mich bei Bedarf und danke Dir 😃

Liebe Grüße von Anette 

Von meinem iPhone gesendet

**Comment by Ein-Tim** [comment]
@Anette841 

Okay 😄

Die App am besten gar nicht öffnen während die 24 Stunden laufen 😅

**Comment by Ein-Tim** [comment]
Version 2.1 which fixed the unintended occurrence of Error 13 has been released!

It will reach all users in the next 48 hours.

See GitHub Release: https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v2.1.1 

The PR that fixed this was #2492.

Please update your App, confirm the fix and then close this issue.

Thank you!

---

Die Version 2.1, die das unbeabsichtigte Auftreten des Fehlers 13 behebt, wurde veröffentlicht!

Sie wird in den nächsten 48 Stunden alle Nutzenden der CWA erreichen.

Siehe GitHub Release: https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v2.1.1 

Der PR, der den Fehler behoben hat, war #2492.

Bitte aktualisieren Sie Ihre App, bestätigen Sie den Fix und schließen Sie dann diesen Issue.

Danke!

**Comment by Anette841** [comment]
Hey Tim,
    ich wollte mich ja
        nochmal melden... funktioniert alles wieder :-)
    Vielen. Dank für Deine
        Hilfe und ich wünsche Dir eine sonnige Zeit,
    Anette
    
    
      
    Am 26.04.21 um 06:36 schrieb Tim:
    
    
      
      Hey @Anette841
      Das ist leider auch nicht das erste mal das wir davon hören das
        die App abstürzt.
      Versuch mal das Folgende:
      
        iOS-Einstellungen öffnen
        Nach "Corona-Warn" suchen
        Deaktiviere "Hintergrundaktualisierung"
      
      Nun gibt es in der App einen Button "Aktualisieren".
        Diesen bitte nicht klicken, erst nochmal 24
        Stunden warten, die App nicht öffnen!
        Morgen dann die App öffnen und die App geöffnet lassen während
        die App (hoffentlich) eine Risiko-Überprüfung durchführt, ohne
        Abzustürzen.
        Danach kannst du dich hier nochmal melden.
      Sollte das nicht helfen musst du wohl leider auf Version 2.1
        warten.
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/corona-warn-app/cwa-app-ios/issues/2545#issuecomment-826494203",
"url": "https://github.com/corona-warn-app/cwa-app-ios/issues/2545#issuecomment-826494203",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Ein-Tim** [comment]
Hallo @Anette841 

Schön zu hören das alles wieder funktioniert. Dir auch eine schöne Zeit und bleib sicher & gesund! 

Danke für deine Hilfe!

**Comment by Ein-Tim** [comment]
@thomasaugsten Could you close this issue? 

Thank you!

**Comment by dsarkar** [comment]
@Anette841 Danke fuer das Feedback. Stay safe, DS

---
Corona-Warn-App Open Source Team
