### ISSUE TITLE
Unnecessary free space between paragraphs [check-in info menu]

### ISSUE THREAD

**Issue by midorrr** [corona-warn-app/cwa-app-ios#2546]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: iPhone SE (iPhone8,4)
- iOS version: 14.4
- App version: 2.0.3 (1)

## Describe the bug

Large areas of free space within the information text After update on newest version or later review of same text via check-in menu (3 dot)￼.

## Steps to reproduce the issue

1. Go to 'Check-In'
2. Click on 'Menue'/ 3DotIcon > 'Infos'
3. Scroll down to 'Ihr Einverständnis' (text with darker background)

## Expected behaviour

Much less free space, so you don't have to scroll down so much.

## Possible Fix

Adapt text layout for smaller screens.
￼
## Additional context

It's only an issue with first iPhone SE's small screen resolution (maybe smaller android smartphones too)￼. No free space with iPhone 6S.

## Screenshots
![image](https://user-images.githubusercontent.com/83180186/116005188-1d81ea00-a606-11eb-8349-7ac66dcbae57.jpeg)

![image](https://user-images.githubusercontent.com/83180186/116005196-22df3480-a606-11eb-8acb-6fd8309b2627.jpeg)

[First GitHub contribution -- hope I did well enough.]

---
Internal Tracking ID: [EXPOSUREAPP-6774](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6774)

**Comment by midorrr** [comment]
![image](https://user-images.githubusercontent.com/83180186/116005088-c1b76100-a605-11eb-8768-b2b1720f5232.jpeg)

**Comment by Ein-Tim** [comment]
Hey @midorrr 👋

I can't reproduce this on an Emulator at the first try (which means nothing at first 😉). 
Could you post a screenshot of "Einstellungen" -> "Bedienungshilfen" -> "Anzeige & Textgröße", so that I can try to reproduce this in your font size.

Thank you, and a very good first issue!

**Comment by jucktnich** [comment]
I tried it on the same device, the error didn't showed up, but I think that the bullet points between are missing.

**Comment by midorrr** [comment]
1. Requested Screenshot
![image](https://user-images.githubusercontent.com/83180186/116006638-62a91a80-a60c-11eb-9e8b-770f3245a00a.png)

2. Initial setting:
![image](https://user-images.githubusercontent.com/83180186/116006668-84a29d00-a60c-11eb-9cf1-783abc356878.png)

3a. Adjusted setting (second step  = first one with no empty space):
![image](https://user-images.githubusercontent.com/83180186/116006725-c59ab180-a60c-11eb-9c41-7849752a25bb.png)

3b. Text without empty space
![image](https://user-images.githubusercontent.com/83180186/116006858-51144280-a60d-11eb-87f7-9c099eb2adf5.png)

**Comment by Ein-Tim** [comment]
@midorrr 

Thank you. I can confirm that with the font size set to minimum there's this layout issue. 

@jucktnich I can't reproduce this, would you like to open another issue reg. this.

**Comment by midorrr** [comment]
> I tried it on the same device, the error didn't showed up (there were 3 bullet points in between), but I think that the bullet points between are missing.

I tried it on two devices (same Apple ID) with presumable same basic setting over all.

**Comment by jucktnich** [comment]
@Ein-Tim sorry my post maybe was a bit concussing... I don't have any problems.

**Comment by midorrr** [comment]
> @Ein-Tim sorry my post maybe was a bit concussing... I don't have any problems.

Fixed my title because it was misleading; the text contains 5 paragraphs (but only 3 bullet points).

**Comment by dsarkar** [comment]
Hi @midorrr,

Thanks for reporting. Internal Tracking ID: [EXPOSUREAPP-6774](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6774)

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
FYI PR https://github.com/corona-warn-app/cwa-app-ios/pull/2729

**Comment by Ein-Tim** [comment]
Version 2.3 has been released to the App Store yesterday. Can you confirm that this has been fixed @midorrr?

**Comment by heinezen** [comment]
Closed because it is very likely fixed.

----
Corona-Warn-App Open Source Team
