### ISSUE TITLE
Risiko Ermittlung funktioniert nicht

### ISSUE THREAD

**Issue by UlliKu** [corona-warn-app/cwa-app-ios#2550]
Hallo,
Auf meinem iPhone xr läuft die Risikoermittlung nicht. Ich habe die App mehrfach deinstalliert neu installiert ein Update durchgeführt. iOS ist neuste Version. 
so sieht es bei mir aus:
![51465ECF-C1D3-4585-8185-B50B43A0275E](https://user-images.githubusercontent.com/83214151/116063479-51502480-a685-11eb-8434-bfa695618228.png)
![77865F20-38A7-45B7-9DFD-716B2DB3357F](https://user-images.githubusercontent.com/83214151/116063498-54e3ab80-a685-11eb-9ca3-7aa38bf44114.png)
![194D2B17-6F0C-4005-8F20-21E8C0D85556](https://user-images.githubusercontent.com/83214151/116063503-557c4200-a685-11eb-85bc-f742fae08399.png)
Mit Bitte um Hilfe 27.04. 2021

**Comment by jucktnich** [comment]
See #1997

**Comment by Ein-Tim** [comment]
We hope that iOS 14.5 will fix this.

**Comment by Ein-Tim** [comment]
Could you add a screenshot of "Einstellungen" -> Begegnungsmitteilungen"?

**Comment by UlliKu** [comment]
![4DC1B6F8-E206-4805-B2AA-4767FA23639B](https://user-images.githubusercontent.com/83214151/116069116-5617d700-a68b-11eb-8b3f-73af99217700.png)

**Comment by UlliKu** [comment]
![F13C3346-7BF9-4833-BDBC-01CEC142BA95](https://user-images.githubusercontent.com/83214151/116069282-7f386780-a68b-11eb-8d93-a408bbb48336.png)

**Comment by UlliKu** [comment]
![DF0EF6E8-EEEE-4072-B715-AC21A7A645D6](https://user-images.githubusercontent.com/83214151/116069501-bc9cf500-a68b-11eb-9060-87dcfc3819f5.png)

**Comment by UlliKu** [comment]
![F4598A4B-38D5-4E22-89EE-38A52F2CEB09](https://user-images.githubusercontent.com/83214151/116069530-c4f53000-a68b-11eb-94fb-cdd87ca7a055.png)

**Comment by Ein-Tim** [comment]
@UlliKu 

Okay, you are unfortunately experiencing the exact same as already reported in #1997. 

Could you add your screenshots there and close this issue here? 

Thank you!

**Comment by UlliKu** [comment]
KP wie diese Plattform funktioniert, bin froh, dass ich sie bei Google wiedergefunden habe und bedanke mich für die Hilfen schon jetzt.

**Comment by Ein-Tim** [comment]
@UlliKu 

Okay, kein Problem, ich werde deine Screenshots nachher zu dem anderen Issue hinzufügen. 
Vielen Dank fürs Melden und eine Entschuldigung dafür das wir dir hier nicht helfen können 😅

**Comment by Ein-Tim** [comment]
iOS 14.5 has been released yesterday, could you please update to it and try if this fixes the issue? @UlliKu
