### ISSUE TITLE
Error 13 - Risiko-Überprüfung läuft bei jedem Aufruf der App automatisch

### ISSUE THREAD

**Issue by drlludwig** [corona-warn-app/cwa-app-ios#2556]
Die Risiko-Ermittlung sollte nur einmal pro Tag zu einem vom User eingestellten Zeitpunkt, und zwar auch im Hintergrund, laufen und nicht automatisch bei jedem Aufruf der App. Ansonsten sollte die Risiko-Ermittlung zusätzlich manuell gestartet werden können. 
Nach automatischer Risiko-Ermittlung sollte wenn vom Benutzer gewünscht, eine Push-Mitteilung gesendet werden, die das Ergebnis anzeigt.

**Comment by Ein-Tim** [comment]
@drlludwig 

Kannst du mir einen Gefallen tun und deinen EN-Log hier hochladen (wie siehe unten)?
Seit Version 1.7 aktualisiert die App im WLAN alle 4 Stunden, mit Mobilen Daten alle 24 (siehe https://www.coronawarn.app/de/blog/2020-11-25-corona-warn-app-version-1-7).

> Ansonsten sollte die Risiko-Ermittlung zusätzlich manuell gestartet werden können.

Das ist gar nicht so einfach da die App auf eine Schnittstelle im Betriebssystem zugreift, diese erlaubt maximal 6 Zugriffe in 24 Stunden. 

> Nach automatischer Risiko-Ermittlung sollte wenn vom Benutzer gewünscht, eine Push-Mitteilung gesendet werden, die das Ergebnis anzeigt.

Die App meldet sich wenn du eine Begegnung mit hohem Risiko hattest, d.h. wenn sie sich nicht meldet ist alles okay.
Wenn du möchtest kannst du aber gerne [hier](https://github.com/corona-warn-app/cwa-wishlist/issues/new/choose)[](https://github.com/corona-warn-app/cwa-wishlist/issues/new/choose) ein Feature-Request dazu auf machen.

<summary>How to export Exposure Notificaiton Logs under iOS 13.7 or newer</summary>


**German:**

`Einstellungen` ➡️ `Begegnungsmitteilungen` ➡️ `Status von Begegnungsaufzeichnungen` ➡️ `Begegnungsüberprüfungen` ➡️ `Überprüfungen exportieren`

**English:**

`Settings` ➡️ `Exposure Notifications` ➡️ `Exosure Logging Status` ➡️ `Exposure Checks` ➡️ `Export Exposure Checks`

**To upload the file here, rename it from .json to .txt**
</details>

**Comment by drlludwig** [comment]
Hallo Tim,

danke für die schnelle Antwort!

Bei mir läuft die Überprüfung bei jedem Aufruf der App automatisch immer wieder ab, bis schließlich der Fehler 13 kommt. Allerdings kommt die Überprüfung nie zum Ende. Nach einigen Minuten beendet sich die App einfach. Wenn man wieder startet beginnt sie wieder automatisch mit der Risiko-Ermittlung. 

Eine Push-Nachricht nach einer Risiko-Begegnung kommt auch nicht. 

Anbei auch der gewünschte Report:


 Grüße 

Lothar

Am 27.04.2021 um 14:37 schrieb Tim ***@***.***>:

﻿
@drlludwig

Kannst du mir einen Gefallen tun und deinen EN-Log hier hochladen (wie siehe unten)?
Seit Version 1.7 aktualisiert die App im WLAN alle 4 Stunden, mit Mobilen Daten alle 24 (siehe https://www.coronawarn.app/de/blog/2020-11-25-corona-warn-app-version-1-7).

Ansonsten sollte die Risiko-Ermittlung zusätzlich manuell gestartet werden können.

Das ist gar nicht so einfach da die App auf eine Schnittstelle im Betriebssystem zugreift, diese erlaubt maximal 6 Zugriffe in 24 Stunden.

Nach automatischer Risiko-Ermittlung sollte wenn vom Benutzer gewünscht, eine Push-Mitteilung gesendet werden, die das Ergebnis anzeigt.

Die App meldet sich wenn du eine Begegnung mit hohem Risiko hattest, d.h. wenn sie sich nicht meldet ist alles okay.
Wenn du möchtest kannst du aber gerne hier ein Feature-Request dazu auf machen.

How to export Exposure Notificaiton Logs under iOS 13.7 or newer
German:

Einstellungen ➡️ Begegnungsmitteilungen ➡️ Status von Begegnungsaufzeichnungen ➡️ Begegnungsüberprüfungen ➡️ Überprüfungen exportieren

English:

Settings ➡️ Exposure Notifications ➡️ Exosure Logging Status ➡️ Exposure Checks ➡️ Export Exposure Checks

To upload the file here, rename it from .json to .txt

**Comment by Ein-Tim** [comment]
Okay @drlludwig.

Zu dem Fehler 13 (das ist ein Bug) haben wir schon mehrere Berichte, siehe #2395.
Ein Fix wurde bereits gemerged (#2492) und wird mit der nächsten Version, 2.1, ausgespielt. 

Bis dahin kannst du folgendes versuchen: 

1. Öffne die iOS Einstellungen
2. Scrolle hinunter bis zu "Begegnungsmitteilungen"
3. Klicke auf "Corona-Warn-App"
4. Klicke nochmal auf "Corona-Warn-App"
5. Scrolle runter und deaktiviere "Begegnungsinformationen teilen"

Nach 24 Stunden kannst du die Option wieder aktivieren, danach sollte die App wieder funktionieren.

In der Zeit in der du "Begegnungsinformationen teilen" ausgeschaltet hast werden deine Kontakte nicht aufgezeichnet und dein Risiko wird nicht berechnet. 
Wenn du das nicht willst gib bescheid, es gibt noch andere Optionen, die aber manchmal nicht funktionieren.

**Comment by drlludwig** [comment]
ok, habe ich jetzt mal ausgeschaltet. 

Danke

Lothar

 

Am 27.04.2021 um 15:06 schrieb Tim ***@***.***>:

﻿
Okay @drlludwig.

Zu dem Fehler 13 (das ist ein Bug) haben wir schon mehrere Berichte, siehe #2395.
Ein Fix wurde bereits gemerged (#2492) und wird mit der nächsten Version, 2.1, ausgespielt.

Bis dahin kannst du folgendes versuchen:

Öffne die iOS Einstellungen
Scrolle hinunter bis zu "Begegnungsmitteilungen"
Klicke auf "Corona-Warn-App"
Klicke nochmal auf "Corona-Warn-App"
Scrolle runter und deaktiviere "Begegnungsinformationen teilen"
Nach 24 Stunden kannst du die Option wieder aktivieren, danach sollte die App wieder funktionieren.

In der Zeit in der du "Begegnungsinformationen teilen" ausgeschaltet hast werden deine Kontakte nicht aufgezeichnet und dein Risiko wird nicht berechnet.
Wenn du das nicht willst gib bescheid, es gibt noch andere Optionen, die aber manchmal nicht funktionieren.

**Comment by Ein-Tim** [comment]
Version 2.1 which fixed the unintended occurrence of Error 13 has been released!

It will reach all users in the next 48 hours.

See GitHub Release: https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v2.1.1 

The PR that fixed this was #2492.

Please update your App, confirm the fix and then close this issue.

Thank you!

---

Die Version 2.1, die das unbeabsichtigte Auftreten des Fehlers 13 behebt, wurde veröffentlicht!

Sie wird in den nächsten 48 Stunden alle Nutzenden der CWA erreichen.

Siehe GitHub Release: https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v2.1.1 

Der PR, der den Fehler behoben hat, war #2492.

Bitte aktualisieren Sie Ihre App, bestätigen Sie den Fix und schließen Sie dann diesen Issue.

Danke!

**Comment by dsarkar** [comment]
Hi @drlludwig,

Siehe den Kommentar oben von @Ein-Tim. Wir würden uns über Feedback von Dir freuen: Kannst Du bestätigen, dass der Fehler bei Dir nicht mehr auftaucht? Vielen Dank, Beste Gruesse, DS

---
Corona-Warn-App Open Source Team

**Comment by drlludwig** [comment]
Der Fehler ist bei mir mit dem letzten Update behoben. Besten Dank!

**Comment by dsarkar** [comment]
@drlludwig Danke fuer das Feedback. Sollte der Fehler wieder auftauchen, bitte hier melden. Vielen Dank. Beste Grüß, DS

---
Corona-Warn-App Open Source Team
