### ISSUE TITLE
High risk encounter still shown after 15 days

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#2587]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 8
- iOS version: 14.4.2
- App version: 2.0.3

## Describe the bug

The Corona-Warn-App on an iPhone 8 continues to show a high risk encounter from the 14.04.2021, although this encounter is already older than 14 days. This encounter is also not visible anymore in the contact journal, since it's already older than 14 days and the contact journal only shows the encounters of the last 14 days.

## Steps to reproduce the issue

1. Get a high risk encounter
2. Wait till the 14 days window is over
3. See that the encounter is still shown

## Screenshot

<img src="https://user-images.githubusercontent.com/67682506/116594322-5bdb1a00-a922-11eb-9608-c514a13a771d.jpg" width="300">

(Taken on 1.15, the update to 2.0 didn't change anything)

## Expected behaviour

Encounter should not be shown anymore after 14 days.

## Additional context

This issue was reported to me via [Twitter](https://twitter.com/tweetymelay/status/1387716975464521728?s=21).
I didn't attach the EN-Log here since it does not contain any MatchedKeyCount anymore, see #1731.

**Comment by dsarkar** [comment]
@Ein-Tim Thanks. Can you figure out if it still shows the risk encounter?

BTW: Today + 14 past days = 15  => could be interpreted as the time span 14-29. April. Therefore, more interesting if this problem still persists today.

**Comment by Ein-Tim** [comment]
@dsarkar 

He [told](https://twitter.com/tweetymelay/status/1388015360025284611?s=21) me that the app went back to green today. 
He said that he got the notification reg. the risk encounter on the 16.04. 

Still the EN-Log as well as the contact journal yesterday didn't show the 14.04. anymore, so the 14 days passed on the 28.04....

**Comment by dsarkar** [comment]
ok. I will bring this up internally. At this stage I understand there is no bug. There seems always to be the problem of how do you count:

- Start with 0, start with one?
- Today counts?
- When is the next day? After 24 h or at 0000? If at 0000, is it UTC time or local time?
- In detail: When is next day for an encounter vs  how do you define next day for a contact journal entry?
- And so forth.

It might look slightly inconsistent that the Contact journal did not show 14.04. anymore, but the risk encounter was still there, but then again it might be related to one of the mentioned points above.

**Comment by Ein-Tim** [comment]
> Start with 0, start with one?
> Today counts?

The [FAQ](https://www.coronawarn.app/de/faq/#days_last_risk_encounter) says: 
"The number of days is counted as normal - '1 day since the last encounter' means 'yesterday', '2' the day before yesterday."

But seems like this FAQ article is outdated since version 1.9 (ENF v2) since the linked Apple docu says "Note
This value is only available when ENAPIVersion is set to 1 in the app’s Info.plist file."

In general I agree with you that this is most likely only an understanding issue, still it would be good to get a confirmation. 
Also, normal users will be confused since everywhere the value 14 is mentioned but now the encounter is olde than 14 days already... 

Thank you! Have a nice Friday!

**Comment by Ein-Tim** [comment]
I assume https://github.com/corona-warn-app/cwa-app-ios/pull/3565 fixes this.

**Comment by Ein-Tim** [comment]
https://github.com/corona-warn-app/cwa-app-ios/pull/3565 has been merged into `release/2.10.x` and is included in the hot fix version 2.10.2.

**Comment by dsarkar** [comment]
@Ein-Tim Thanks for reporting and following up!
