### ISSUE TITLE
Capitalize German locations

### ISSUE THREAD

**Issue by DerVogel2020** [corona-warn-app/cwa-app-ios#2600]
## Technical details

- App version: 2.0.5

## Describe the bug

First letters are not writen as majuscile.

## Steps to reproduce the issue

1. Go to 'Startseite'
2. Click on 'QR-Code erstellen'
3. Click on '+ QR-Code'
4. Look at "öffentliches Gebäude", "anderer Ort", "private Feier" and "anderes Event"

## Expected behaviour

Capitalize the items from point 4.
corona-warn-app/cwa-wishlist#491

**Comment by Ein-Tim** [comment]
@DerVogel2020 
Do you plan to submit a PR here too? 
If not, I can do it and I'll also provide some screenshots from my emulator.

**Comment by DerVogel2020** [comment]
Yes, I'm still cloning the repo.

**Comment by Ein-Tim** [comment]
@DerVogel2020 Okay, I'll provide a PR then. 

AFAIK, it should be possible to check the iOS repo out on Windows, are you using GitHub Desktop?

**Comment by DerVogel2020** [comment]
No, Git Bash:
`error: invalid path 'Icon?'`
`fatal: Could not reset index file to revision 'HEAD'.`

**Comment by Ein-Tim** [comment]
@DerVogel2020 Please take a look at #2601

**Comment by DerVogel2020** [comment]
Closed, because #2601 won't be merged for convention reasons.

**Comment by dsarkar** [comment]
@DerVogel2020 Same here, thanks again for contributing.

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
Seems like this will be implemented in version 2.3, see #2682.

**Comment by DerVogel2020** [comment]
Reopen, so this issue can get the "Fix 2.3"-label. I will close it as soon as CWA 2.3 is available.
