### ISSUE TITLE
Fehlercode: NoExposureWindows - iPhone 6S, iOS 14.5, CWA 2.0.3 (1)

### ISSUE THREAD

**Issue by Vktrg** [corona-warn-app/cwa-app-ios#2602]
## Avoid duplicates
* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 6S
- iOS version: iOS 14.5
- App version: CWA 2.0.3

## Describe the bug

Fehlercode: NoExposureWindows

## Additional context

---
Internal Tracking ID: [EXPOSUREAPP-7419](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7419)

**Comment by Ein-Tim** [comment]
Hey @Vktrg 👋

Could you please share a screenshot of the error here? Also, it would be nice if you could let us know your iOS version, your CWA version & your iPhone model.  

Thank you!

**Comment by Vktrg** [comment]
![Uploading 912F4AB8-D2A3-4B51-8301-2510A07A45F7.png…]()

**Comment by Vktrg** [comment]
Ist der Screenshot sichtbar?

**Comment by Ein-Tim** [comment]
Leider nicht. Beim hochladen musst du warten bis dort nicht mehr [Uploading…] steht, sondern !IMAGE[…].

**Comment by Vktrg** [comment]
![C007CA31-BB2C-44E9-8DC9-5A73EA5B85AD](https://user-images.githubusercontent.com/83012474/116780841-4af3eb00-aa7f-11eb-92b7-3577877b5b56.png)

**Comment by thomasaugsten** [comment]
Hallo welche iOS Version verwendest du? Was passiert wenn du die App löscht und neu installierst?

**Comment by Ein-Tim** [comment]
@thomasaugsten Siehe Titel, es ist iOS 14.5.

Danke für den Screenshot @Vktrg!

**Comment by Ein-Tim** [comment]
Ich denke das das mit dem Fehler 13 zusammenhängt, den hast du ja schon in #2521 gemeldet.

**Comment by Ein-Tim** [comment]
@Vktrg 

Kannst du bitte auf Version 2.1 aktualisieren und es nochmal versuchen?

**Comment by Vktrg** [comment]
Fehler besteht nach Update auf 2.1.2 leider immer noch. 
![BFCB4701-DEB6-4D26-B47A-2BB50D0E28B0](https://user-images.githubusercontent.com/83012474/117035789-08434480-ad05-11eb-8010-1e284b755d28.png)
![44FAD7F0-36A0-4896-B7EA-A15957F44CFC](https://user-images.githubusercontent.com/83012474/117035795-0aa59e80-ad05-11eb-8a6c-d8094bbd4ac1.png)

**Comment by Ein-Tim** [comment]
@Vktrg Hast du 24 Stunden gewartet?

**Comment by Vktrg** [comment]
Nach dem Update? Bin mir nicht ganz sicher. Habe nochmal alles deaktiviert und schaue morgen

**Comment by Vktrg** [comment]
![58566579-2201-4CC0-A76E-850928CB92EA](https://user-images.githubusercontent.com/83012474/117186446-1ebbcf80-addb-11eb-80af-1ce5001d1b39.png)

**Comment by Vktrg** [comment]
Fehler besteht nach 24 stunden noch

**Comment by Ein-Tim** [comment]
Okay danke @Vktrg 

- Hast du dein Handy mal neugestartet?
- Hast du die App mal zurückgesetzt (Kontakte die via Bluetooth aufgezeichnet wurden bleiben erhalten, Test-Ergebnisse, Kontakttagebuch-Einträge & Check-Ins gehen aber verloren!) via "Einstellungen" (in der App) -> "Anwendung zurücksetzten" -> "Anwendung zurücksetzten" "Zurücksetzten"?
- Bist du auf Version 2.1.3?

**Comment by Vktrg** [comment]
Handy habe ich mal neu gestartet. App habe ich gerade zurückgesetzt, jetzt erscheint wieder Fehler 13. 
App ist jetzt auf 2.1.3 
Soll ich wieder alles deaktivieren und 24 Stunden warten?

**Comment by thomasaugsten** [comment]
Einfach nur 24h warten reicht

**Comment by Vktrg** [comment]
Fehler 13 besteht leider immer noch

**Comment by Vktrg** [comment]
Okay, danke für den Support!

**Comment by Ein-Tim** [comment]
@Vktrg Könntest du bitte einen Screenshot von "Begegnungsmitteilungen" aus den iOS-Einstellungen hier hochladen? Ich würde gerne wissen wie das aussieht.

**Comment by Vktrg** [comment]
![EDB8F8D1-F6EE-4EC5-AC30-DDA3D802B736](https://user-images.githubusercontent.com/83012474/117551024-d6531a80-b043-11eb-89fc-f14a7ae81723.png)

**Comment by Ein-Tim** [comment]
@Vktrg 

Mh, danke, da sieht alles normal aus... 
Mal sehen was die Devs sagen, schönen Abend noch!

**Comment by dsarkar** [comment]
Hi @Vktrg Treten beide Fehler noch auf? Fehler 13 **und** NoExposureWindows?
 Danke.

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@Vktrg Ich würde empfehlen nicht immer alles auszuschalten?

@thomasaugsten Was bedeutet "NoExposureWindows"? Ich würde raten das das ENF keine Kontakte aufgezeichnet hat?

**Comment by ndegendogo** [comment]
@Ein-Tim NoExposureWindows is defined [by cwa](https://github.com/corona-warn-app/cwa-app-ios/blob/c6f6b67e3756eccbed98f8752de56ced59c3e261/src/xcode/ENA/ENA/Source/Services/Exposure%20Transaction/ExposureDetectionTransaction%2BDidEndPrematurelyReason.swift#L13), not by Apple

**Comment by thomasaugsten** [comment]
Der Fehler bedeutet das ENF keine Exposure Windows berechnen kann. Es ist hier wahrscheinlich der Fall das die Signature der Pakete nicht überprüft werden kann. Wir sind dran mehr details über den Fehler anzeigen zu lassen. Bitte noch ein paar Tage Geduld

**Comment by Vktrg** [comment]
![C08BE13B-8B35-4E1E-9AC4-8F9F9A2929A6](https://user-images.githubusercontent.com/83012474/119177919-48c4f100-ba6d-11eb-9994-3396b93d4a9d.png)

**Comment by dsarkar** [comment]
@Vktrg Thank you very much!


---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
@Vktrg I guess all tree error reports were sent within the same minute, since there was no confirmation of successful submission and have therefore the same content. Do you know more or less at what time the error NoExposureWindows occurred during error logging?
Many thanks, enjoy the weekend. 

---
Internal Tracking ID: [EXPOSUREAPP-7419](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7419)
Corona-Warn-App Open Source Team

**Comment by Vktrg** [comment]
I started the analysis again, maybe it will work now. 
The error appears immediately after opening the app.

**Comment by Vktrg** [comment]
![C1CF2DCA-ED5B-42B3-B9A2-C6ED6EFDA8D4](https://user-images.githubusercontent.com/83012474/119321368-daef1400-bc7c-11eb-87db-5c9c3152c5a3.png)

**Comment by dsarkar** [comment]
@Vktrg Thank you very much. Why are there 5 error reports? Did you send it 5 times, or is this another bug?

**Comment by Ein-Tim** [comment]
@dsarkar See #2715

**Comment by dsarkar** [comment]
@Ein-Tim Thanks!

**Comment by Vktrg** [comment]
No, I only sent it once. I think it's another bug

**Comment by Vktrg** [comment]
Bin auf das 11pro umgestiegen, jetzt besteht der Fehler nicht mehr. Vielen Dank für die Unterstützung!

**Comment by dsarkar** [comment]
@Vktrg Thanks for contributing. Viel Spass mit dem neuen Telefon. 


---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@thomasaugsten 

Hey Thomas, sorry to bother you again, I have a [Twitter user](https://twitter.com/maxgarnier/status/1516160986096488457?s=21&t=-PkPqLyeMHsLDVIA4sStNg) experiencing the NoExposureWindows error, could you let me know what you recommend the user does? 
Do you want an error report?

**Comment by thomasaugsten** [comment]
Most likely a network or certificate issue.
But a error report would be helpful

**Comment by Ein-Tim** [comment]
@thomasaugsten 

Ok, I'll open a new issue for this.
