### ISSUE TITLE
Add the flag of Norway next to EU and Switzerland for Transnational Exposure Logging

### ISSUE THREAD

**Issue by phibo23** [corona-warn-app/cwa-app-ios#2606]
## Avoid duplicates
* [x] This enhancement request has not already been raised before
* [ ] Enhancement request is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)
* [ ] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation

In one of the recent updates, Switzerland was added to the list of countries supported by transnational exposure logging and the flag was added next to the EU flag where the latter is displayed. However, the list of countries also contains Norway, which, like Switzerland, is not part of the EU.

![Simulator Screen Shot - iPhone SE (2nd generation) - 2021-05-02 at 16 44 50](https://user-images.githubusercontent.com/1328782/116817491-e7dd8380-ab66-11eb-9852-d3a164aa1705.png)
![Simulator Screen Shot - iPhone SE (2nd generation) - 2021-05-02 at 16 44 53](https://user-images.githubusercontent.com/1328782/116817492-e8761a00-ab66-11eb-9cd3-a2d70e681de8.png)
![Simulator Screen Shot - iPhone SE (2nd generation) - 2021-05-02 at 16 45 03](https://user-images.githubusercontent.com/1328782/116817493-e90eb080-ab66-11eb-88d9-656542fb85d9.png)

## Suggested Enhancement

Add the flag of Norway next to those of the EU and Switzerland

## Expected Benefits

This is not a technical improvement, just a more accurate representation of the facts.

Also, I didn't check if this also affects the Android app. If that is the case, please transfer this issue to a more appropriate place like the wishlist.

**Comment by Ein-Tim** [comment]
This has already been declined once, please see https://github.com/corona-warn-app/cwa-documentation/issues/566

**Comment by phibo23** [comment]
Thanks for the link, I didn't search the documentation repo
