### ISSUE TITLE
UI: Empty space on some screens

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#2631]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone XR, iPhone 6s, iPhone SE 1, iOS 14.5.1. (So probably affects all screen sizes)
- iOS version: 14.5.1, 14.6 Beta 2
- App version: 2.1.3 (0)

## Describe the bug

There are some screens where there are unnecessary free spaces.

## Steps to reproduce the issue

Depending on screens, see screenshots below, should be clear. On the Home Screen the bug is only visible below the "Create QR Code" screen.

## Expected behaviour

No free/empty space

## Screenshots
<img src="https://user-images.githubusercontent.com/67682506/117199726-d60c1280-adea-11eb-925c-6227e8fdae10.PNG" width="300">
<img src="https://user-images.githubusercontent.com/67682506/117199742-da383000-adea-11eb-88e3-e1dda73b6cd3.PNG" width="300">
<img src="https://user-images.githubusercontent.com/67682506/117199750-dc9a8a00-adea-11eb-81a8-38c43958bcb3.PNG" width="300">
<img src="https://user-images.githubusercontent.com/67682506/117199752-ddcbb700-adea-11eb-8008-bf902ddc11c9.PNG" width="300">

---
Internal Tracking ID: [EXPOSUREAPP-7098](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7098)

**Comment by dsarkar** [comment]
@Ein-Tim Good morning! Thanks.
- Affect only main screen apparently?
- I can reproduce.

**Comment by jucktnich** [comment]
Can reproduce it with iPhone SE 1, iOS 14.5.1. (So probably affects all screen sizes)

**Comment by dsarkar** [comment]
@jucktnich thanks, will add this to OP.

**Comment by dsarkar** [comment]
@jucktnich I could find this bug only on the main screen. You? Thanks for the feedback.

**Comment by jucktnich** [comment]
I too only on the homescreen, sorry forgot to add this to my comment

**Comment by jucktnich** [comment]
https://user-images.githubusercontent.com/73582096/117279025-946a7e80-ae61-11eb-9fd7-472ea56476f8.MP4

As you can see here, the blank space only appears at the uikit buttons.

**Comment by dsarkar** [comment]
@Ein-Tim @jucktnich Thanks. Internal Tracking ID: [EXPOSUREAPP-7098](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7098)

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@dsarkar So you can't reproduce this on the QR-Code screen?

Thanks for mirroring to JIRA!

**Comment by dsarkar** [comment]
@Ein-Tim You might be right, but I can't see it on the QR-Code screen. Could you mark/circle it?

**Comment by dsarkar** [comment]
![image](https://user-images.githubusercontent.com/1409741/117304889-86772680-ae7e-11eb-88c5-720af75a687e.png)

**Comment by Ein-Tim** [comment]
<img src="https://user-images.githubusercontent.com/67682506/117306321-e02c2080-ae7f-11eb-9ab4-f2f08e496469.PNG" width="300">
<img src="https://user-images.githubusercontent.com/67682506/117306343-e4f0d480-ae7f-11eb-9f18-6867fb1246a9.PNG" width="300">

**Comment by dsarkar** [comment]
![image](https://user-images.githubusercontent.com/1409741/117307201-a576b800-ae80-11eb-8915-6d34056a5eed.png)


iPhone 6s - you think there is an extra space?

**Comment by dsarkar** [comment]
If so, then also on the right screenshot...

**Comment by dsarkar** [comment]
@Ein-Tim  BTW, I am surprised you did not report that one ;-) (no need to create a ticket, we got it tracked already internally):
![image](https://user-images.githubusercontent.com/1409741/117307642-069e8b80-ae81-11eb-9961-c6e447ce77e0.png)

**Comment by jucktnich** [comment]
It's probably only on iPhones with notch, since the safe space isn't there...

**Comment by Ein-Tim** [comment]
@dsarkar I was about to report this, but I saw the PRs so I thought no need to report it (;

I can't confirm wether this issue is also there on the "Request TAN" screen since my iPhone XR just broke (again)... I'll test later on an Emulator.

**Comment by Ein-Tim** [comment]
@dsarkar No visible free space on "Request TAN" screen, maybe it's there but it's not visible.

**Comment by dsarkar** [comment]
FYI PR https://github.com/corona-warn-app/cwa-app-ios/pull/2650

**Comment by Ein-Tim** [comment]
@dsarkar I can confirm that the glitch on the whole screen is fixed, but on the QR-Code screen I can see the free space. Maybe you could ask wether this will also be fixed in version 2.3?

**Comment by dsarkar** [comment]
@Ein-Tim I forwarded your question. Thanks.

**Comment by dsarkar** [comment]
FYI PR https://github.com/corona-warn-app/cwa-app-ios/pull/2658

**Comment by Ein-Tim** [comment]
Closing as fixed in version 2.3.2 which was released to the App Store today.

**Comment by dsarkar** [comment]
@Ein-Tim Can you confirm the fix? Thanks.

**Comment by Ein-Tim** [comment]
@dsarkar Yes I can. Has been fixed.

**Comment by dsarkar** [comment]
@Ein-Tim OK, thanks I will forward this as confirmed by community then. Cheers.

**Comment by Ein-Tim** [comment]
@dsarkar Just so that you forward the right info, I can confirm that there is no empty space on the Home Screen anymore. I cannot say anything about the case on the QR-code screen since I don't have an iPhone with a notch currently. I could cross check with an Emulator or the devs confirm this. 

Thank you and have a nice evening. Sorry if I my tone was "rude" in the website repo 😅

**Comment by dsarkar** [comment]
Hi @Ein-Tim ok, I will specify the confirmation of the fix as you wrote it. Didn't notice any "rude" tone in the website repo... all chilled! Thanks to you and everybody else in the community for great support and contributions! 

Same to you, and all, enjoy the evening!
