### ISSUE TITLE
Becoming a beta tester

### ISSUE THREAD

**Issue by kevin-kraus** [corona-warn-app/cwa-app-ios#2647]
## Avoid duplicates
* [X] Question is not already answered in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Question is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Question has not already been asked in another issue

## Your Question

* Question:
Is there a publicly (or invite-only) beta test available via TestFlight?

If yes, how can you participate?

**Comment by Ein-Tim** [comment]
Hey @kevin-kraus 👋

Thanks for your question!

No, there is no public beta currently, see https://github.com/corona-warn-app/cwa-wishlist/issues/153.

This issue is a duplicate of #29.

Please close it and monitor https://github.com/corona-warn-app/cwa-wishlist/issues/153.

**Comment by dsarkar** [comment]
Hi @kevin-kraus @Ein-Tim, Thanks for asking, and commenting on it, respectively. 

---
Corona-Warn-App Open Source Team
