### ISSUE TITLE
UX: Misleading counting of installed days

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#2648]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation) - **Please check**
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 6s
- iOS version: 14.5.1
- App version: 2.1.3

## Describe the bug
I've installed CWA yesterday and it showed "Installed today". 
This morning I opened the Corona-Warn-App and it still shows "Installed today". 
Probably, the app counts 24h as one day. This is misleading since a human would expect that as soon as one day passes (00:00h) the app shows one more day.

## Steps to reproduce the issue
1. Install the app at 15:00h
2. See that the app shows "Installed today"
3. Open the app at 08:00h on the next day
4. See that the app still shows "Installed today"

## Expected behaviour
As explained above, as soon as one day passes the app should show "Installed 1 day ago".

## Additional context

Please check the behavior under Android and move this issue to the documentation repository if necessary.

##  Possible Fix:
Increase day count since installation at 0000 LT instead of every 24 h.

---
Internal Tracking ID: [EXPOSUREAPP-7201](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7201)

duplicate of

Internal Tracking ID: [EXPOSUREAPP-7145](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7145) 
Internal Tracking ID: [EXPOSUREAPP-7279](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7279) 

PR https://github.com/corona-warn-app/cwa-app-ios/pull/2705

**Comment by dsarkar** [comment]
@Ein-Tim I will check these days with Android. I add to you OP, if that is fine with you:

Possible Fix:
Increase day count since installation at 0000 LT instead of every 24 h.

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-7201](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7201)

**Comment by dsarkar** [comment]
FYI PR https://github.com/corona-warn-app/cwa-app-ios/pull/2705 
Internal Tracking ID: [EXPOSUREAPP-7145](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7145)

**Comment by Ein-Tim** [comment]
@dsarkar Could you or somebody else confirm the fix? Reset the app and see if the next day starts at midnight and not after 24h. Thank you!

**Comment by dsarkar** [comment]
@Ein-Tim Wilco!

**Comment by Ein-Tim** [comment]
@dsarkar

Any update on this? What's the status of the internal ticket? Has the fix been confirmed?

**Comment by dsarkar** [comment]
Hi @Ein-Tim, will be tested next weekend. Thanks.

**Comment by Ein-Tim** [comment]
@dsarkar 

Thank you! I was just able to confirm the fix myself.

Closing as fixed.

**Comment by dsarkar** [comment]
@Ein-Tim 

![image](https://user-images.githubusercontent.com/1409741/135827322-220935c7-fa54-4090-8d33-62cdb6d8a59c.png)

Android: 2.10.1
iOS: 2.10.2

Slight difference between Android and iOS.

**Comment by Ein-Tim** [comment]
@dsarkar 

Will create a new enhancement issue asking to show "Gestern installiert" instead of "Seit 1 Tag installiert".
The issue, however, I reported in the OP has been fixed & I was able to confirm the fix.

**Comment by dsarkar** [comment]
@Ein-Tim Alright, thanks.

**Comment by Ein-Tim** [comment]
@dsarkar

I opened #3648.
