### ISSUE TITLE
[Register Test] (Lightmode) Back button gets white

### ISSUE THREAD

**Issue by jucktnich** [corona-warn-app/cwa-app-ios#2686]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [?] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: iPhone SE 1
- iOS version: iOS 14.5.1
- App version: 2.2.1 (0)

## Describe the bug

Back button gets white in Lightmode (really hard to spot)

## Steps to reproduce the issue

https://user-images.githubusercontent.com/73582096/117953539-64662400-b316-11eb-8d36-dffc343b3f1c.MOV

## Expected behaviour

Blue button
## Additional context

---
Internal Tracking ID: [EXPOSUREAPP-7121](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7121)

**Comment by jucktnich** [comment]
FYI: https://github.com/corona-warn-app/cwa-app-ios/pull/2687

**Comment by Ein-Tim** [comment]
This has been fixed somehow strange:

https://user-images.githubusercontent.com/67682506/121299017-16ccdf00-c8f5-11eb-8095-9765a7e4cded.MOV

You are always thrown back to the rapid test profile screen even if you only swipe over a bit. This is not the normal behavior under iOS.

Probably a separate ticket would be good for this?

**Comment by jucktnich** [comment]
Would you open an issue for this?

**Comment by Ein-Tim** [comment]
Done in #2881
