### ISSUE TITLE
Colors in dark mode do not match

### ISSUE THREAD

**Issue by jucktnich** [corona-warn-app/cwa-app-ios#2690]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [?] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name:
- iOS version:
- App version:

## Describe the bug

![image](https://user-images.githubusercontent.com/73582096/117975731-46f18400-b32f-11eb-8f4f-818e32172185.png)

## Steps to reproduce the issue

1. Activate darkmode
2. Go to the your consent screen

## Expected behaviour

Matching colors

## Possible Fix

Match the color

----
Internal Tracking-ID: [EXPOSUREAPP-7267](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7267)

**Comment by Ein-Tim** [comment]
This affects more screens, like this one too:

<img src="https://user-images.githubusercontent.com/67682506/117990716-b3737f80-b33d-11eb-9f9b-7174d6d957b1.PNG" width="300">

It's hard to see but the section "Ermittlungszeitraum" has a different color than the elements above.

**Comment by heinezen** [comment]
@jucktnich @Ein-Tim 

Thank you both for the screenshots. I've forwarded the problem to the developers ([EXPOSUREAPP-7267](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7267)). Feel free to report other places where this happens iin this issue.

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
In this case, the color of the illustration does not match the background color.

<img src="https://user-images.githubusercontent.com/67682506/118324090-dd759f00-b501-11eb-806c-1dcc2c5de9fb.PNG" width="300">

**Comment by dsarkar** [comment]
@Ein-Tim will include this into internal ticket! Thanks!

**Comment by Ein-Tim** [comment]
@jucktnich 

The case you mention in the OP has been fixed, https://github.com/corona-warn-app/cwa-app-ios/issues/2690#issuecomment-841478685 will be fixed in one of the next releases. 

Only https://github.com/corona-warn-app/cwa-app-ios/issues/2690#issuecomment-839812566 isn't fixed yet. 

@heinezen / @dsarkar Could you maybe update the internal ticket so that only https://github.com/corona-warn-app/cwa-app-ios/issues/2690#issuecomment-839812566 has to be fixed now.

**Comment by Ein-Tim** [comment]
Please apply the "Fix 2.28" label to this issue, as it was fixed with https://github.com/corona-warn-app/cwa-app-ios/pull/4831.

**Comment by Ein-Tim** [comment]
@dsarkar Could you please ask the team if this is the intended look for that screen (background color of headline "Risiko-Ermittlung" differs from the rest of the background):
<img src="https://user-images.githubusercontent.com/67682506/200122421-253ab6b5-5f6b-4d2e-80ff-f58d183180b8.jpeg" width="300">

**Comment by Ein-Tim** [comment]
@dsarkar All issues in this thread have been fixed. It can be closed now.

**Comment by larswmh** [comment]
Thanks for the information @Ein-Tim. As all issues in this thread have been fixed, I will now close this issue.
