### ISSUE TITLE
2.2.1 release?

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#2693]
## Avoid duplicates
* [X] Question is not already answered in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Question is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Question has not already been asked in another issue

## Your Question
The App Store offers version 2.2.1 for download. It can be installed by all users manually and will go into automatic update mode on 15.05.2021.

Will you follow up with a version 2.2.1 Release shown on https://github.com/corona-warn-app/cwa-app-ios/releases?

The latest shown there is currently https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v2.2.1-RC1.

## Acknowledgements 

The text of this issue was adapted from https://github.com/corona-warn-app/cwa-app-android/issues/2725 by @MikeMcC399.

**Comment by Ein-Tim** [comment]
@marcussc @kaddaSz 

Would you like to release this version here on GitHub, please?

**Comment by heinezen** [comment]
@Ein-Tim Sorry, should be released now.

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
No problem, yes I can see the release now: https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v2.2.1

Closing as fixed.
