### ISSUE TITLE
App shows "Your test result cannot be loaded. The response has no content"

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#2694]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 6s
- iOS version: 14.5.1
- App version: 2.2.1

## Describe the bug

My app showed this message to me today, after I registered a Rapid Test yesterday:
<img src="https://user-images.githubusercontent.com/67682506/118002743-36013c80-b348-11eb-8cae-3f876520cf7b.PNG" width="300">
After clicking on "OK", I was able to continue to use the app as normal, my test result was also still registered. 

## Steps to reproduce the issue

1. Open the Corona-Warn-App
2. Register a Test via the "Register your Test" box
3. Wait for some time - if you don't get a result the app shows this message after some time

## Expected behaviour

This message should either 
a) be suppressed - it does not have any useful information and only concerns the user or
b) has a link to an FAQ entry with further details.

## Possible Fix

See above, either
a) surpress
b) Add "More Information" button which links to more information

## Additional context

1. I registered a test which will be performed on the 15.05.2021.
2. This message is also shown for PCR-Test results, I saw this in earlier versions.

----
Internal Tracking-ID: [EXPOSUREAPP-7265](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7265)

**Comment by Ein-Tim** [comment]
It should be easy to reproduce this issue, if not, I can try to reproduce it and upload an error log.

**Comment by heinezen** [comment]
@Ein-Tim 

We have created a Jira ticket for your bug ([EXPOSUREAPP-7265](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7265)). Creating an error report could be useful, so why not? We can also test the new reporting feature this way :)

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@heinezen 

I'll try to create an error report but this could be difficult here because the error pops up instantly when opening the app, but not if I'm already in the app. 

Thanks for mirroring to Jira!

**Comment by calle2010** [comment]
I have the same error (in German). I registered my test with QR code on Friday. On Saturday morning I saw the message the first time. On Sunday morning the second time. I removed the test registration and tried to scan the QR code again, but now even registration fails with the same message. 

Btw: Gesundheitsamt called me yesterday to tell me the result, so the old fashioned way works...

**Comment by Ein-Tim** [comment]
@calle2010 

And I think exactly that is the problem with the message, the user thinks that the transfer does not work or so and will maybe remove the test (not knowing that he/she can't scan the Code again). 
I did not remove the test and just ignored the message. The test result of my quick test was shown to me as expected, although I saw the error message at least 4 times before.

So, to summarise, the error message does not mean that the test result is broken, but only that it isn't there yet. This message does not contain any information useful for a normal user and will only lead to confusion, that's why it should be removed ASAP.

**Comment by dsarkar** [comment]
@calle2010 Thanks for letting us know. @Ein-Tim  Thanks for analysing.

---
Corona-Warn-App Open Source Team

**Comment by calle2010** [comment]
If that makes a difference: in my case it was a PCR test.

**Comment by Ein-Tim** [comment]
I've sent an error report today at 15:09h. It's very long but it contains the pop up.
The pop up showed at:
14:06h & 14:58h

**Error Report ID: B43D8B36747DC526D64E**

**Comment by dsarkar** [comment]
Hi @Ein-Tim Thank you very much! Forwarded to internal ticket!

**Comment by heinezen** [comment]
We cannot reproduce this anymore, so I would suggest closing this issue.

In general the error message is correct, so there might be an issue wth the RAT provider. We'll have to check if it happens again.

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@heinezen I have no way to confirm this, but since the error seems to be fixed, I'll close this now.

**Comment by Ein-Tim** [comment]
Just experienced this yesterday with a PCR test again, I'd suggest to log this message but not show it to the user, as it has 0 information value for them. I'll open a new issue for this.

**Comment by heinezen** [comment]
Reopened because the error happened again (https://github.com/corona-warn-app/cwa-app-ios/issues/2694#issuecomment-887373613).

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
This is still an issue under version 2.8. @heinezen is this intended? If not, I wonder why the pop-up was not removed?

**Comment by Ein-Tim** [comment]
@dsarkar 

What exactly is the status here? The problem persists, even in 2.15.1.

<img src="https://user-images.githubusercontent.com/67682506/146784138-4c4122e2-f1f1-4452-9a8d-e436b662995e.png" width="300">

**Comment by dsarkar** [comment]
@Ein-Tim In the previous reports, did the user eventually receive the result?

**Comment by Ein-Tim** [comment]
@dsarkar 

Yes, the result was always received, the only unexpected thing is this pop-up.

**Comment by dsarkar** [comment]
@Ein-Tim ok, thanks for the info.

**Comment by Ein-Tim** [comment]
@dsarkar 

For sure! I'm still voting for just removing this pop up, as it does not help the user in any way. The message should be logged if error logging is active, though.

**Comment by dsarkar** [comment]
@Ein-Tim ok, I forward this the ticket.

**Comment by larswmh** [comment]
@Ein-Tim @calle2010 FYI: PR #4050

**Comment by Ein-Tim** [comment]
I will try to reproduce the error on version 2.17, when I'm not able to, I'll close the issue.

**Comment by Ein-Tim** [comment]
I wasn't able to reproduce this issue anymore, but a new issue appeared: https://github.com/corona-warn-app/cwa-app-ios/issues/4180

Closing this issue as fixed.
