### ISSUE TITLE
Date of birth is always one day in the past

### ISSUE THREAD

**Issue by Jens07** [corona-warn-app/cwa-app-ios#2696]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 11
- iOS version: 14.4.2
- App version: 2.2.1

## Describe the bug

After the creation of a rapid test profile the date of birth is always one day in the past compared to the value in the previous input field.

## Steps to reproduce the issue

1. Go to 'register your test'
2. Click on 'next steps'
3. Click on 'create rapid test profile'
4. See that the date of birth is always one day before the selected date. I tried it with a plurality of dates. It seems always the same problem.

## Expected behaviour

The date of birth should be correct.

**Comment by Ein-Tim** [comment]
Hey @Jens07 

I tried the following:
1. Click on "Next Steps" in the "Register your Test" box
2. "Create Rapid Test Profile"
3. Enter "01.01.2000" into the field via the picker
4. Click on "Save" 
5. The date of birth is shown correctly as "1. Jan 2000".

Could you maybe upload a screen recoding? Are you using a keyboard from the App Store? 

Thank you!

**Comment by Ein-Tim** [comment]
@Jens07 Please also see #2695, where the same was reported before. I think it would be good if you could follow up there and close this issue here to be able to better keep track.

**Comment by dsarkar** [comment]
@Jens07 Thanks for reporting. Internal Tracking ID: [EXPOSUREAPP-7263](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7263)


---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
FYI PR https://github.com/corona-warn-app/cwa-app-ios/pull/2707

**Comment by dsarkar** [comment]
FYI new PR https://github.com/corona-warn-app/cwa-app-ios/pull/2741

**Comment by dsarkar** [comment]
Fixed in 2.3

**Comment by dsarkar** [comment]
@Jens07 Thanks for reporting. Best, DS


---
Corona-Warn-App Open Source Team
