### ISSUE TITLE
Test Concept

### ISSUE THREAD

**Issue by HolgerMayer** [corona-warn-app/cwa-app-ios#27]
## Your Question
Could you please explain your QA concept. I am especially interested how much you plan to unit test and when.

**Comment by SebastianWolf-SAP** [comment]
Dear @HolgerMayer,

thank you for your question. However, please understand that such a QA concept is currently not planned. Please see our https://github.com/corona-warn-app/cwa-documentation repository for details on the already shipped and planned deliverables. 

However, contributions to missing tests are - of course - always appreciated.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by HolgerMayer** [comment]
_"However, contributions to missing tests are - of course - always appreciated."_

First - It is useless to write the same thing twice. So if you plan to write test which ones?#
Second - I don't see many tests

Or - and I currently fear it is true : you follow a path that is well known since the beginning of programming - scrubbing QA because of a nearing release date.

**Comment by SebastianWolf-SAP** [comment]
First, apologies for the - probably premature - closing of this issue. Yesterday evening, the text sounded to me as you ask us to provide a big document - which is definitely not planned.

However, the development team will certainly provide more details about how to test and the way forward. A first version of a small MD file is already in the development branch: https://github.com/corona-warn-app/cwa-app-ios/blob/development/TESTING.md

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by inf2381** [comment]
Hi @HolgerMayer. To ensure quality and a stable application we are doing the following:
- There is a dedicated team for testing at SAP Switzerland. Their main focus is to set up an automated test environment using real devices. They will upload everything in a (fork)[https://github.com/RHasemann/cwa-app-ios] and merge it into our repo once it's ready.
- Tomorrow, we are releasing a testable version of the app on TestFlight (SAP + T-Systems internal only, see #29)
- After tomorrow, one of our focusses is to refactor our code to enable more tests (We also consider not testable code as a bug)
- Once the refactoring is done, we try to archive as much test coverage as possible already when implementing new features but we also are hoping for the community to help us there. So we will continue to create issues here on GitHub to tell the community where help is needed.
