### ISSUE TITLE
[UX] Step cells should not be selectable 

### ISSUE THREAD

**Issue by hansemannn** [corona-warn-app/cwa-app-ios#2700]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 11 Pro
- iOS version: 14.6
- App version: 2.2.1

## Describe the bug

There is a commonly used item template for displaying "steps", e.g. in the submission test result view, submission hotline and submission success view. Currently, when tapping on one of the cells, a selection indicator is displayed, which looks odd to non-technical users knowing that a `UITableView` is behind it:

<img src="https://user-images.githubusercontent.com/10667698/118355321-a4741380-b56f-11eb-92fe-e9ffeae2676c.jpeg" width="320" />

## Steps to reproduce the issue

1. Add a sample antigen test
2. Tap on the test
3. Scroll down to the "Info" section+
4. Tap on one of the steps

## Expected behaviour

No selection is displayed.

## Possible Fix

Disable cell selection for step cells (fixed in https://github.com/corona-warn-app/cwa-app-ios/pull/2701)

---
Internal Tracking ID: [EXPOSUREAPP-7296](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7296)

**Comment by Ein-Tim** [comment]
Will this fix #2245 too?

**Comment by dsarkar** [comment]
@hansemannn Thanks. Internal Tracking ID: [EXPOSUREAPP-7296](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7296)

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
Version 2.3 has been released to the App Store yesterday, can you confirm the fix @hansemannn?

**Comment by hansemannn** [comment]
Looks good, we can close this one!

**Comment by Ein-Tim** [comment]
@hansemannn As the author of this issue you can close it yourself.
