### ISSUE TITLE
App Store reports: Crashes after update on version 2.2.1

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#2703]
## Avoid duplicates
* [X] Question is not already answered in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Question is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Question has not already been asked in another issue

## Your Question
There are many [reports on the App Store](https://apps.apple.com/de/app/corona-warn-app/id1512595757#see-all/reviews) which talk about crashes after the update to version 2.2.1.
Did you investigate this? When do these crashes happen? 

---
Internal Tracking ID: [EXPOSUREAPP-7280](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7280)

**Comment by dsarkar** [comment]
@Ein-Tim Yes, we are aware of these crashes: Internal Tracking ID: EXPOSUREAPP-7280. Its something being looked at. At this stage there is no more detailed information.

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@dsarkar Okay, thank you for the quick answer! Could you please keep us posted here if there are any new informations available? 

Thank you and have a nice Sunday!

**Comment by Ein-Tim** [comment]
Obsolete with 2.3 release.
