### ISSUE TITLE
Wrong dates & times  in "ID History" screen

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#2715]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 6s
- iOS version: iOS 14.5.1
- App version: 2.2.1

## Describe the bug

The "ID History" screen of the error logging feature does not show the date and time when the error log was sent to the server but the current date and current time.

## Steps to reproduce the issue

1. Open CWA
2. Scroll down till "App Information"
3. Click on "Error Reports"
4. If you haven't sent an error log to the server yet, do this 
5. Scroll down to "ID History"
6. See that the current time and date is shown

## Expected behaviour

The date and time when the error report was sent to the server should be shown.

## Possible Fix

Already fixed in #2633.

## Additional context

I created this issue for transparency and to make everyone aware of this issue.
This issue will be closed after the fix in version 2.3 has been confirmed on a real device.

---

Internal Tracking ID: [EXPOSUREAPP-7094](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7094)

**Comment by dsarkar** [comment]
FYI PR https://github.com/corona-warn-app/cwa-app-ios/pull/2633

**Comment by dsarkar** [comment]
@Ein-Tim Haha... got it! It is already in your OP!

**Comment by Ein-Tim** [comment]
Closing as fixed in version 2.3.2 which was released to the App Store today.

**Comment by dsarkar** [comment]
@Ein-Tim Thanks.
