### ISSUE TITLE
[Exposure logging active screen] headline changes appearance

### ISSUE THREAD

**Issue by jucktnich** [corona-warn-app/cwa-app-ios#2743]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: iPhone SE 1
- iOS version: iOS 14.5.1
- App version: 2.2.1 (0)

## Describe the bug

The headline changes appearance
## Steps to reproduce the issue

Watch the video:
![Image](https://user-images.githubusercontent.com/73582096/118995613-949d6a80-b987-11eb-933b-4241b8ac6815.MOV)

## Expected behaviour

No changes
---
Internal Tracking ID: [EXPOSUREAPP-7385](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7385)

**Comment by dsarkar** [comment]
@jucktnich Thanks. Internal Tracking ID: [EXPOSUREAPP-7385](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7385)

Cannot reproduce on iPhone 6s / iOS 14.4 / CWA 2.2.1


---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
Tested on:

- iPhone SE 1. Gen (Emulator)
- iPhone SE 2. Gen (Emulator)
- iPhone 6s (real device)
- iPhone 12 Pro (Emulator)

Reproducible on all these devices.
