### ISSUE TITLE
Bluetooth option gets greyed out when Exposure logging is enabled

### ISSUE THREAD

**Issue by diimaan** [corona-warn-app/cwa-app-ios#2745]
## Technical details

- Device name: iPhone 11 Pro Max
- iOS version: 14.5.1
- App version: 2.1.3

## Describe the bug

Bluetooth gets disabled or completely greyed out, the Bluetooth module goes into auto on off mode and it keeps on refreshing and the phone becomes slow because of the background refresh. 
I even got my phone replaced because the Bluetooth was greyed out and I was not able to use any accessories with my phone. After the replacement the new phone had the same issues. I did some digging, by reset the network, reset the phone completely, disable the bluetooth devices one by one. Finally, when I disable exposure logging and remove CWA, this issue vanishes. I am not sure how to contact Apple Dev support, but if it is a possibility to look from the CWA side let me know if I can run a testflight build and can provide some logs

## Steps to reproduce the issue
Enable exposure logging in the settings. Use any app CWA/CoronaMelder. After sometime the Bluetooth toggle gets greyed out. If we go into settings and the Bluetooth option is greyed out and we will not be able to see the connected devices.

## Expected behaviour

Exposure logging should not interfere with the bluetooth functionality of the phone.

## Possible Fix
Reboot the device fixes it. But I cannot reboot 4-5 times in a day so that my Bluetooth would work as expected.
Possible workaround is to disable exposure logging and remove the app. It has been a week since I disabled the logging and removed the app and I have not seen a single instance of this issue.

---

EDIT Corona-Warn-App Open Source Team

Related  to
https://github.com/corona-warn-app/cwa-app-ios/issues/1193 ? 
Internal Tracking ID: EXPOSUREAPP-2869 ?

**Comment by Ein-Tim** [comment]
Hey @diimaan 

Thank you for opening this issue here (:

Do you have CWA installed currently? If yes, could you share a screenshot of how the Bluetooth Settings looks once it gets grayed out? What does CWA show? What do you see in "Begegnungsmitteilungen"?

If you have CWA installed, please also update to version 2.2 and see if anything has changed? Do you experience any other issues with the app?

We also have a FAQ-Entry regarding such problems, but since you said you even got your phone replaced I assume that there are no new/helpful informations in for you: https://www.coronawarn.app/en/faq/#various_device_problems

**Comment by dsarkar** [comment]
Hi @diimaan,

Thanks for your report here. Please, follow the suggestions  made by @Ein-Tim. Should the problem persist, we have the option in CWA version 2.2 to create an error report. 
Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
Also, did you try this?
https://www.coronawarn.app/en/faq/#ios_black_screen
https://www.coronawarn.app/de/faq/#ios_black_screen

**Comment by diimaan** [comment]
Yes I did a complete reset. And at Apple Genius Bar, they replaced my phone as they were not able to get it fixed. 
But after getting the new phone, I had the same problem. I tried the reset routine and it was the same!
To dig more and isolate the issue I did the following, 

After a complete reset and restore of apps. I tried disabling the apps and devices I frequently use or connect:
1, I disabled my VPN (Mullvad), run it for a day and still the problem was persisting! (This was my primary suspect)
2, Removed all my paired devices, run it for a day and still was the same. (Including my Apple Watch)
3, Then I saw that Exposure Logging was enabled. I disabled that and removed all associated apps(CWA), run it for a day I did not had the issue. Now it has been a week since that and it is working without the glitch!

Just wanted to get to the root of this so I posted here as I was not aware about the community before. Else would have shared screenshots and logs at that time itself.
I have installed the latest version of CWA(2.2.x) and enabled Exposure Logging. I will run it for a week and post updates and logs if necessary.

**Comment by Ein-Tim** [comment]
@diimaan Thank you very much! Have a nice Friday & a great weekend!

**Comment by Ein-Tim** [comment]
@diimaan 

If you want to you could give this another try under iOS 15 & CWA 2.10.2.

If not I suggest to close this issue as this seems to be an edge case and this can't really be fixed by the CWA devs but has to be fixed by Apple.

**Comment by Ein-Tim** [comment]
The "in review" label is applied here since 21.05.2021, so over a year. 

@diimaan Is this still occurring under iOS 15.4.1 and with the latests CWA? 

@dsarkar Is this really still "in review"?

**Comment by 30mar** [comment]
This should be fixed already please re open if you face an issue with it @diimaan , thanks!
