### ISSUE TITLE
Deleted persons and locations reappear after reopening the app

### ISSUE THREAD

**Issue by FlightMS** [corona-warn-app/cwa-app-ios#2759]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 11
- iOS version: 14.5.1
- App version: 2.2.1

## Describe the bug

When working with the person and location editor of the contact journal, there is a confusing behaviour. When you delete a person or location in the editor, it disappear from the list. After closing the editor, it‘s still in the day overview of the contact journal and when you reopen the person or location editor, the person or location reappeared in the list.

## Steps to reproduce the issue

1. Open contact journal
2. Add persons and locations to days
3. Open location and person editor and delete something
4. Close editor and open again

## Expected behaviour

A message appear that the location or person is still „in use“ and can‘t be deleted. Or the person and location will be also deleted from the contact journal.

## Additional context

----
Internal Tracking-ID: [EXPOSUREAPP-7588](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7588) duplicate of
Internal Tracking ID: [EXPOSUREAPP-7568](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7568)

**Comment by Ein-Tim** [comment]
Not reproducible with these steps: 
1. Open the contact journal
2. Click on the current day
3. Click on "Person hinzufügen" 
4. Enter "Test" into the name field
5. Click on "Speichern" 
6. Navigate back from today to the main screen of the contact journal
7. Click on the 3 dots in the right corner
8. Click on "Personen bearbeiten" 
9. Scroll to "Test"
10. Press on the - and then on "Löschen"
11. Click "Ja" on the pop-up
12. Close the editor via the x in the right corner
13. The entry "Test" is gone

**Comment by FlightMS** [comment]
Hi @Ein-Tim

can you check it with locations added via QR Code?

**Comment by Ein-Tim** [comment]
@FlightMS 

Checked with location that was added by an event QR-Code. 
Works the same way as above and works as expected.
If there is no sensible information in your contact journal you could provide us with a screen recording here.

Thank you.

**Comment by FlightMS** [comment]
As I tried to reproduce it, the error does not occur anymore.

Issue is solved for this moment.

**Comment by FlightMS** [comment]
I was able to reproduce the error. Below you will find a short screen recording.

https://user-images.githubusercontent.com/82420268/120123576-e75cfa80-c1af-11eb-9ba3-d1fe86aa6195.MP4

**Comment by heinezen** [comment]
@FlightMS 

Thank you for reproducing the issue. That helps us a lot! I've notified the developers about the issue by creating a Jira ticket. We'll report back when the issue gets resolved.

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
FYI: PR #2839, fix planned for version 2.4.

**Comment by Ein-Tim** [comment]
@FlightMS Version 2.4 is in the App Store and can be installed manually. Could you try to reproduce the bug and confirm that it has been fixed in version 2.4?

**Comment by FlightMS** [comment]
The error no longer occurs in version 2.4.1.

Fixed!
