### ISSUE TITLE
Some ASCII control characters allowed in check-in QR-code address and description

### ISSUE THREAD

**Issue by RickP** [corona-warn-app/cwa-app-ios#2784]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: All iOS devices
- iOS version: 14.5
- App version: 2.2.1

## Describe the bug

In the address and description field of the check-in QR-Code newlines and linefeeds are filtered - so I assume there should not be any empty lines in these fields. 

All other control characters are allowed. Especially the NULL character (0x00) in combination with a TAB (0x09) or FormFeed (0x0C) can lead to some undesired behaviour.

Lots of FormFeed characters after the address can be used to make the box with the checkin-time disappear from the screen area.

When the address or the description starts with a NULL character it is not displayed on the "Checkin for" screen and the "My checkins" screen. This way check-in codes with empty addresses and descriptions can be made. 

For some reason strings starting with a NULL character ARE displayed on the "Checkin for" screen if the string contains another control character after the NULL character but not on the "My checkins" screen. This seems to be due to incoherent string handling within different iOS UI components. So check-ins that change their label after being accepted can be created.

## Steps to reproduce the issue

Here's a checkin QR code that shows both described problems
![control_codes](https://user-images.githubusercontent.com/835371/119685334-8fd42d00-be45-11eb-94c8-da31b8a6a059.png)

Make a checkin with this code. On the info screen it adds lots of empty lines after the address and puts the description out of the screen area. If you accept the checkin it will show only the description on the "My checkins" screen.

## Expected behaviour

Control characters (especially NULL and FormFeed) should be removed from the address and description strings.

----
Internal Tracking-ID: [EXPOSUREAPP-7591](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7591)

**Comment by heinezen** [comment]
Hey @RickP ,

Thanks for the report.

> Make a checkin with this code. On the info screen it adds lots of empty lines after the address and puts the description out of the screen area. If you accept the checkin it will show only the description on the "My checkins" screen.

Could you make a screenshot of that so we can compare how it looks on Android? Thank you.

----
Corona-Warn-App Open Source Team

**Comment by RickP** [comment]
> Could you make a screenshot of that so we can compare how it looks on Android? Thank you.

I don‘t have an Android device. It‘s trivial and takes seconds to try it with the QR code above if you have an iOS and an Android device with the CWA installed - so I don‘t see the need for screenshots.

**Comment by heinezen** [comment]
@RickP 

I meant on your iOS device. The screenshot would help us to replicate the issue better.

----
Corona-Warn-App Open Source Team

**Comment by RickP** [comment]
Info screen after scanning the QR code:

![2530C1BA-F94D-4AC7-996E-5F102B46B809](https://user-images.githubusercontent.com/835371/119879424-858c5e80-bf2b-11eb-8ede-998cdcbbd4d0.png)


„My checkins“ screen after pressing „Einchecken“:

![3B8F37BD-BB95-4651-8E4E-1E920BE9499F](https://user-images.githubusercontent.com/835371/119879565-a81e7780-bf2b-11eb-8ddf-a030ba18503b.png)

**Comment by heinezen** [comment]
@RickP 

Thanks a lot for reproducing the issue. The screenshots will definitely help.

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
FYI: PR: #3064

**Comment by Ein-Tim** [comment]
@RickP Could you confirm that the fix is in version 2.5?

**Comment by Ein-Tim** [comment]
Could you close this issue @dsarkar?
