### ISSUE TITLE
cwa-ios-sdk

### ISSUE THREAD

**Issue by SvenTiigi** [corona-warn-app/cwa-app-ios#28]
Are there are any plans to introduce a dedicated cwa SDK/Framework for the Apple platform?

A cwa-sdk-ios would be beneficial in points of separation of concerns, code consistency and coherency.

The following parts of the cwa-app-ios project could be moved into a dedicated framework:

* Model-Layer (including Google Protobuf files)
* Network-Layer (HTTPS Communication)
* REST-API Layer when performing a specific request to the cwa-server/cwa-verification-server
* Cryptography-Layer
* BackgroundTask-Management
* Persistence-Layer
* ExposureNotification-Tracing-Layer

Additionally, a cwa-ios-sdk would enable a clear API-Specification in terms of what kind of functionality is publicly available for the consumer (the cwa-ios-app) and which is framework internal or private.

A comparable approach can be found within the SwissCovid-App project on GitHub.
https://github.com/DP-3T/dp3t-sdk-ios
https://github.com/DP-3T/dp3t-app-ios-ch

**Comment by ChristianKienle** [comment]
We definitely want to go there. At the moment the code base is still changing a lot. I think this should at least to be considered when thinking about the introduction of frameworks. An additional thing is how to actually split it up? By feature? By *layer*? Both? :)

What are your thoughts on the last point?

**Comment by SvenTiigi** [comment]
The proposal has been discussed with @ChristianKienle via Skype and will be reviewed by the core development team.

**Comment by ChristianKienle** [comment]
On hold for now. But a prototype has already been launched. We will report back in 1-2 weeks or so.

**Comment by Ein-Tim** [comment]
Is there any update on this available? If not, I suggest to close this issue.

**Comment by dsarkar** [comment]
@SvenTiigi Thanks to everybody for contributing here. This issue became stale, therefore we are closing it. Feel free to open a new issue for any further suggestions, discussions, bug reports, etc. Many thanks again! Best wishes, DS

---
Corona-Warn-App Open Source Team
