### ISSUE TITLE
VCARD-Display different for iOS and Android

### ISSUE THREAD

**Issue by lafidi** [corona-warn-app/cwa-app-ios#2800]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: IPhone 7
- iOS version: iOS 14.5
- App version: 2.2.0 (Testflight)

## Describe the bug

The handling/displaying of VCards differs between iOS and Android. The Content (plain text) of the defined Attributes is usually in capital letters. CWA complies to that with one exception on the address field: `ADR;TYPE=home` (Android; capital `TYPE`) and `ADR;type=home` (iOS). This can be a problem for some standardized VCard libraries when they trigger on capital letters.

## Steps to reproduce the issue

1. open App
2. create quick test profile with Address (if not already done)
3. display QR-Code with address
4. read plain text from QR-Code

## Expected behaviour

Having the capital letters in both versions equally.

## Possible Fix

capitalize TYPE

----
Internal Tracking-ID: [EXPOSUREAPP-7590](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7590)

**Comment by heinezen** [comment]
@lafidi 

Thank you for reporting. I have notified the development team about this by creating an internal Jira ticket (ticket ID: [EXPOSUREAPP-7590](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7590)). They will have a look at this.

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
FYI: PR #2863

**Comment by Ein-Tim** [comment]
Hey @lafidi, Version 2.4 is in the App Store now and should have fixed this. Can you confirm?

**Comment by lafidi** [comment]
Hello,
On a quick look it ses to be correct now. 

Thank

**Comment by heinezen** [comment]
@lafidi Thanks for checking!

We'll close here then because it seems to be fixed.

----
Corona-Warn-App Open Source Team
