### ISSUE TITLE
High storage comsumption for personal data

### ISSUE THREAD

**Issue by FlightMS** [corona-warn-app/cwa-app-ios#2806]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 11
- iOS version: 14.6
- App version: 2.2.1

## Describe the bug

The app seems to be have a high storage comsumption. As you can see in the screenshot, it needs ~131 MB for personal data.

Is that a normal amount for the app?

## Steps to reproduce the issue

1. Open Settings app
2. Check storage management for the Corona-Warn-App

![IMG_6560](https://user-images.githubusercontent.com/82420268/120111623-ef4a7980-c172-11eb-8ef1-894faba241d2.PNG)

## Expected behaviour

Less more storage used for personal data by the app.

## Additional context

----
Internal Tracking-ID: [EXPOSUREAPP-7589](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7589)

**Comment by Ein-Tim** [comment]
Hey @FlightMS 

Thank you for reporting this issue. Do you see this behavior since a special CWA/iOS version? 
We had a similar issue before, #1549, this was fixed back in version 1.9.

On my iPhone CWA's "Dokumente & Daten" are ca. 70 MB, you have nearly twice of this, so I don't think this is normal.
Do you have a test registered, many check-ins or contact diary entries?

**Comment by FlightMS** [comment]
I saw this the first time when I created the screenshot yesterday. Before I've never checked the storage consumption before.
So I can't say if the problem occurs since a specific version.

I have one registered Rapid Test (the first ever), some contact diary entries (not very much - only a few days), some QR Code check-ins and 12 places and 4 persons.

**Comment by heinezen** [comment]
@FlightMS 

Interesting. Thanks for reporting this to us. The dev team will have a look at this.

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@FlightMS One more question, did you activate the new error logging feature in the app?

**Comment by FlightMS** [comment]
@Ein-Tim No that's not activated

**Comment by FlightMS** [comment]
„Dokumente & Daten“ are still increasing on my iPhone. Now it‘s about 212,2 MB.

**Comment by Ein-Tim** [comment]
I'll now start logging my numbers here:

iPhone XR:

App Größe: 32,1 MB
Dokumente & Daten: 129,9 MB -> Contact diary entries, COVID certificates

---

iPhone 6s:

App Größe: 31,6 MB
Dokumente & Daten: 23,9 MB -> No contact diary entries, only one COVID certificate

**Comment by Ein-Tim** [comment]
@thomasaugsten 

You said back in https://github.com/corona-warn-app/cwa-app-ios/issues/1549#issuecomment-737714790 that iOS doesn't automatically "clean up temporary system files of the app" and that you "add a feature to trigger this system clean up manually", is this still in place and works?

**Comment by dsarkar** [comment]
@FlightMS @Ein-Tim Thanks for the update. Forwarded into the internal ticket.

**Comment by Ein-Tim** [comment]
11 days have passed since [my last comment](https://github.com/corona-warn-app/cwa-app-ios/issues/2806#issuecomment-883719952) and here are my new numbers:

iPhone XR:

- CWA-Version: 2.6.2
- iOS-Version: 14.7.1
- App Größe: 37,3 MB
- Dokumente & Daten: 172,4 MB -> Increase of ca. 50 MB? Why?
---

iPhone 6s:

- CWA-Version: 2.6.2
- iOS-Version: 15.0 Public Beta 4
- App Größe: 36,3 MB
- Dokumente & Daten: 36,6 MB -> Seems ok

**Comment by FlightMS** [comment]
I can also share my new numbers here:

On my iPhone 11 „Dokumente & Daten“ is now about 221,2 MB with version 2.6.2.
I‘ve entered one rapid test result and scanned one check-in QR code within the last 14 days.

**Comment by Ein-Tim** [comment]
@FlightMS 

Please update to the latest CWA version & iOS 15 and let us know if anything changed.

**Comment by FlightMS** [comment]
@Ein-Tim 

No change here. I‘ve stopped scanning codes and entering data in the contact journal some time ago.

![BCEF0851-7D1D-4E03-8B6D-A9ACBD6397A1](https://user-images.githubusercontent.com/82420268/135043360-47bafe42-c5a4-46f3-bf3f-1ea849f7f9be.jpeg)

**Comment by dsarkar** [comment]
@FlightMS Thanks for the feedback. The information was forwarded to the internal ticket. CC @Ein-Tim Thanks.

**Comment by FlightMS** [comment]
Time for some updates. Just right now this is my space used with my iPhone 11 and iOS 15.2

![9887B5C4-DF0B-44EF-BB56-8D7648AE2541](https://user-images.githubusercontent.com/82420268/146419055-cb3f22a4-e434-416e-a060-259fa09a6c78.jpeg)

**Comment by dsarkar** [comment]
@FlightMS Thanks for update, forwarded to internal ticket.

**Comment by moabits** [comment]
I'll link my comment, since it seems to be also relevant to this issue... https://github.com/corona-warn-app/cwa-app-ios/issues/3854#issuecomment-981837315

**Comment by FlightMS** [comment]
Seems something happened here

![A927248C-5AAB-4B8D-84EF-6BCD91C33886](https://user-images.githubusercontent.com/82420268/147282061-1a3c9e3a-d117-4cb1-9d0a-050dca14a33a.jpeg)

**Comment by Ein-Tim** [comment]
This issue is fixed for me:
 ![image](https://user-images.githubusercontent.com/67682506/147470787-3b75906e-9f74-4fcb-92a3-2f177645cf38.jpeg)

**Comment by FlightMS** [comment]
@Ein-Tim thanks for the confirmation.

Issue closed

**Comment by dsarkar** [comment]
@Ein-Tim @FlightMS Thanks for the feedback, which I forwarded to the internal ticket.
