### ISSUE TITLE
UI: Text on "7-Day Incidence" card too small (Version 2.3)

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#2813]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 12 Pro Emulator
- iOS version: iOS 14.5
- App version: 2.3.0 (10)

## Describe the bug

The text on the "7-Days Incidence" statistics card is too small and does not match the text size of the other texts on the statistic cards.
<img src="https://user-images.githubusercontent.com/67682506/120233855-fa76d580-c256-11eb-813a-d617441b5a20.jpg" width="300">

## Steps to reproduce the issue

1. Open the Corona-Warn-App
2. Scroll down to the statistic cards
3. Swipe right to the card "7-Day Incidence" 
4. See that the text is too small

## Expected behaviour

The text should match the size of the texts on the other cards (like "7-Day R Value").

## Additional context

This issue is not there in the latest released version 2.2.1.

----
Internal Tracking-ID: [EXPOSUREAPP-7587](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7587) duplicate of
Internal Tracking-ID: [EXPOSUREAPP-7577](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7577)

**Comment by heinezen** [comment]
@Ein-Tim 

Thanks for the report. I have reported the issue to the devs ([EXPOSUREAPP-7587](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7587)).

----
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment]
Fix is planned for release 2.4

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
PR: #2858

**Comment by Ein-Tim** [comment]
Confirm fixed in version 2.4.

Closing as fixed.
