### ISSUE TITLE
Import Rapid Test via URL not working

### ISSUE THREAD

**Issue by FlightMS** [corona-warn-app/cwa-app-ios#2819]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 11
- iOS version: 14.6
- App version: 2.2.1

## Describe the bug

I've made a Rapid Test and get the response via mail. I've got a QR Code and a Link to import the result in CWA. When I opened the link I just got redirected to a Corona-Warn-App Website which redirects me to the App Store to install the app instead open the app and import the result.

So the installation status of CWA was not detected correctly.

After this, I've tried with the QR Code which works without any further problems.

The link was https://apo-schnelltest.de/cwa/?v=1#eyJmbiI6Ik1hbHRlIiwib...... (shortend for usability and data security)

![1](https://user-images.githubusercontent.com/82420268/120300545-53cd1c00-c2cc-11eb-9879-859b0f75d556.jpg)

![2](https://user-images.githubusercontent.com/82420268/120300532-4fa0fe80-c2cc-11eb-8b49-9090b91a4c33.jpg)

## Steps to reproduce the issue

1. Open Mail with Link
2. Click on Link
3. Check if the CWA will open

## Expected behaviour

CWA will open and import the result of the test.

**Comment by Ein-Tim** [comment]
Related too https://github.com/corona-warn-app/cwa-event-landingpage/issues/22

**Comment by Ein-Tim** [comment]
@FlightMS 

Can you long klick the link and then tap "Open with Corona-Warn"?

**Comment by FlightMS** [comment]
@Ein-Tim

It directly tries to open the website with Safari.

![CB1A9504-1A2A-4DC5-8C87-04900F58776B](https://user-images.githubusercontent.com/82420268/120364475-9400be80-c30d-11eb-8025-7b76d170bd36.png)

**Comment by Ein-Tim** [comment]
@FlightMS 

Okay thanks, I'll cross check this.
If I visit s.coronawarn.app I see this: 
<img src="https://user-images.githubusercontent.com/67682506/120365574-e68eaa80-c30e-11eb-8b0e-6fb2f1998f15.png" width="300">
I wonder why your page is different. 

@thomasaugsten made some change to the page lately (in https://github.com/corona-warn-app/cwa-event-landingpage/pull/27), so maybe he would like to take a look at this.

**Comment by thomasaugsten** [comment]
I think he has an old cached version.

**Comment by Ein-Tim** [comment]
@FlightMS Could you manually refresh the page and try again?

**Comment by FlightMS** [comment]
@thomasaugsten @Ein-Tim 
I've tried to refresh it, however with no luck.

In Safari I will directly redirected to the App Store where I can open CWA like any other installed app. On the website is no information about "Schnelltest Link". But when I open the Link with Google Chrome, I see the "Schnelltest Link", but I'm unable to open it with CWA and when I click on it, it just opens a new tab with the same content.

Safari
![IMG_6583](https://user-images.githubusercontent.com/82420268/120398994-7c402f00-c33b-11eb-9404-b0e898fe143a.png)

https://user-images.githubusercontent.com/82420268/120400440-2b7e0580-c33e-11eb-826d-822241c346fa.mp4


Chrome
![IMG_6584](https://user-images.githubusercontent.com/82420268/120399008-83ffd380-c33b-11eb-9f97-e9ae81d767be.png)

![IMG_6585](https://user-images.githubusercontent.com/82420268/120399020-88c48780-c33b-11eb-9ac0-7c7c23ecbd08.png)

https://user-images.githubusercontent.com/82420268/120399777-fae99c00-c33c-11eb-8c41-3bb8e56a0c00.mp4

**Comment by thomasaugsten** [comment]
Thanks for the information regarding Google Chrome. We will add Chrome on iOS to the not supported browser list. Please use Safari.

**Comment by FlightMS** [comment]
I've made a new Rapid Test today and now it's working with Safari. I was able to import the result via link.

Thanks!
