### ISSUE TITLE
[ENF] Is the Apple Watch used by ENF?

### ISSUE THREAD

**Issue by jucktnich** [corona-warn-app/cwa-app-ios#2822]
## Avoid duplicates
* [?] Question is not already answered in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Question is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Question has not already been asked in another issue

## Your Question

* Source File:
* Line(s):
* Question:
Does the ENF use the Apple Watch? Or in another way asked, do I need to take my iPhone with me every time, or does my Watch the same thing and send the codes to my iPhone?

**Comment by Ein-Tim** [comment]
Related to: https://github.com/corona-warn-app/cwa-wishlist/issues/12

**Comment by jucktnich** [comment]
Not directly, the issue you've linked is about a whole app for wearables, mine is just about, if the Apple Watch uses collects and sends IDs and then transmitting the data to the iPhone for further use.

**Comment by Ein-Tim** [comment]
@jucktnich 

I know, I understood and I think the answer is no, see https://www.apple.com/de/watchos/feature-availability/ which does not mention ENF in any form. But this should probably be clarified with Apple.

If I link to related issues, I just want to keep track of all issues which are about the same topic and thus help others finding related topics.

**Comment by jucktnich** [comment]
Ok, thx for clarifying it.

**Comment by heinezen** [comment]
I think we can close here because answer https://github.com/corona-warn-app/cwa-app-ios/issues/2822#issuecomment-852297004 by @Ein-Tim is correct.

----
Corona-Warn-App Open Source Team
