### ISSUE TITLE
"Warn Others" Consent does not always reflect real situation

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#2840]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 6s
- iOS version: 14.6
- App version: 2.2.1

## Describe the bug

The text on the bottom of the "Your Test Result" screen as well as the toggle on the "Your Consent" screen is wrong if you denied access to DKs in the pop up from iOS. 
See: 

https://user-images.githubusercontent.com/67682506/120560169-909b2f00-c402-11eb-81c1-edd865158af1.mov

## Steps to reproduce the issue

1. Open the Corona-Warn-App
2. Scroll down to the "Register your Test" box
3. Click on "Next Steps"
4. Click on "Scan QR code"
5. Click on "Accept"
6. Click on "Don't Share"
7. Scan the QR code
8. Scroll down to the bottom
9. See the text "Consent "Warn others" granted" 
10. Click on the text
11. See that the toggle is active
12. Open the iOS Settings
13. Scroll down to "Exposure Notifications" and click on it
14. Click on "Active Region"
15. Click on "Corona-Warn-App"
16. See that the option "Automatically Notify Others" is deactivated and greyed out because you denied to automatically warn others in the pop up before.

## Expected behaviour

The text and the toggle should reflect the actual situation (which is shown in the iOS Settings), which is that you did not consent to warn others automatically, because you denied this in the iOS pop up. 
So, the text should be "Consent "Warn others" not granted" and the toggle should be inactive.

## Possible Fix

"Ask" the ENF for the status of the consent before showing the user that he/she has consent to automatically share his/her test result although the he/she hasn't.

## Additional Information

If you now turn off the toggle and turn it on again it seems like you granted consent to warn others automatically, but you did not because the CWA does not have access to your DKs. So if I turn the toggle on again the iOS pop up come up again and afterwards the "real" consent (on or off, depending on wether you selected "Share" or "Don't Share" in the iOS pop up) should be shown.

----
Internal Tracking-ID: [EXPOSUREAPP-7773](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7773)

**Comment by heinezen** [comment]
@Ein-Tim 

Thank you. The devs are notified and will take a look at this. 

----
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment]
@Ein-Tim

I was informed that we cannot implement a fix for this because the app does not have sufficient access to the requested information. Therefore, a fix is not possible.

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@heinezen 

Thanks for the update. That's a pitty.

Closing as not possible to fix.
