### ISSUE TITLE
Excessive battery drain on iPhone 6s w/ iOS 14.6 

### ISSUE THREAD

**Issue by webdesignweisshart** [corona-warn-app/cwa-app-ios#2849]
## Avoid duplicates
* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue

## Technical details

- Device name:
- iOS version:
- App version:

**Comment by webdesignweisshart** [comment]
Excessive battery drain on iPhone 6s since update to iOS 14.6 CWA 2.2.1

**Comment by jucktnich** [comment]
What's your battery health?

**Comment by webdesignweisshart** [comment]
100%

**Comment by thomasaugsten** [comment]
Battery drain is a known issue of iOS 14.6 not related to CWA. Try 14.7b2 or wait for final 14.7.

**Comment by webdesignweisshart** [comment]
Hm? If I deactivate CWA, battery drain is back to normal level.

**Comment by jucktnich** [comment]
How much battery is used by CWA directly and how much by Exposure Notification?

**Comment by webdesignweisshart** [comment]
It's seems to be all Exposure Notification.

**Comment by jucktnich** [comment]
How much battery does it use (loss of battery / hour * percentage used by Exposure Notification)

**Comment by webdesignweisshart** [comment]
I'm going to monitor that next night, when the iPhone is not used else.

**Comment by jucktnich** [comment]
You can see this data under settings ➜ battery ➜ last 10 days if you click on one day you'll see the percentage used by Exposure notification and you can see on the graph how much batter you was used on the whole day.

**Comment by jucktnich** [comment]
If you want you can do both, cause maybe theres significant difference between real life situations and being idle.

**Comment by webdesignweisshart** [comment]
Ah ok. Exposure notification is always top of the list. From 35% to 80%.

**Comment by Ein-Tim** [comment]
Do you use your phone much?

**Comment by jucktnich** [comment]
![image](https://user-images.githubusercontent.com/73582096/120920476-47c3ce80-c6bf-11eb-86c8-a703fb4a9dbf.jpeg) What does this bar graph show by you?

**Comment by Ein-Tim** [comment]
I suggest you do the following test this night:

1. Charge the phone to 100%
2. Activate the flight mode and turn on WLAN and Bluetooth
3. Make sure CWA is running & background app refresh is like it always is (on/off)
4. Wait for the night

On the morning, see how much of the battery has been drained. 
If it's over 15%, this is odd. If not thats probably normal.

You can then do the same test the next night with flight mode on, WLAN off, Bluetooth off (and CWA deactivated).
This test will show how much of the battery is drained without CWA running.

**Comment by webdesignweisshart** [comment]
I use it about 2 hours a day. The problem is: even if I don't use it at all, e.g. at night, the battery is discharged about 10% per hour. But I will test this again exactly.
Btw. The problem exists only on the iPhone 6s, not on the 11th generation. Both run iOS 14.6 and CWA 2.2.1

**Comment by webdesignweisshart** [comment]
@Ein-Tim 
With CWA running: About 30% in 9 hours.
Without CWA: almost no battery discharge 
See screenshots.
![IMG_0283](https://user-images.githubusercontent.com/59532422/121179885-7b8a2a00-c860-11eb-9f51-ab6cbd62b8b2.PNG)
![IMG_0286](https://user-images.githubusercontent.com/59532422/121179934-8b097300-c860-11eb-9d37-54e5d910701d.PNG)

**Comment by Ein-Tim** [comment]
@webdesignweisshart 

Okay, this seems a bit much to me. I'll test this tonight on my iPhone 6s and let you know how it's on my device.

**Comment by dsarkar** [comment]
Searching in the internet, battery draining seems to be an issue of iOS 14.6, but no related to ENF or CWA.

**Comment by Ein-Tim** [comment]
iOS 14.7 has been released, please retest with iOS 14.7.

**Comment by webdesignweisshart** [comment]
Sorry, apparently no improvement at all with iOS 14.7

**Comment by Ein-Tim** [comment]
Please update to iOS 15 and let us know if the situation has changed.

**Comment by webdesignweisshart** [comment]
Things are looking good now after the update to iOS 15. Thank you.

**Comment by dsarkar** [comment]
Hi @webdesignweisshart Thanks for your feedback! Good to know!

Best, DS 

---
Corona-Warn-App Open Source Team
