### ISSUE TITLE
2.3.2 release?

### ISSUE THREAD

**Issue by xNeoPilot** [corona-warn-app/cwa-app-ios#2869]
## Avoid duplicates
* [x] Question is not already answered in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Question is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Question has not already been asked in another issue

## Your Question
The App Store offers version 2.3.2 for download, it can be installed by all users manually.

Will you follow up with a version 2.3.2 Release shown on https://github.com/corona-warn-app/cwa-app-ios/releases?

The latest shown there (version 2.4.x excluded) is currently https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v2.3.0-RC11

## Acknowledgements

The text of this issue was adapted from https://github.com/corona-warn-app/cwa-app-ios/issues/2693 by @Ein-Tim.

**Comment by xNeoPilot** [comment]
Oh okay, I see @Ein-Tim  was faster, I will close the issue. :D

**Comment by Ein-Tim** [comment]
Thank you anyways @xNeoPilot!
