### ISSUE TITLE
when scanning QR-Code to add vaccination receiving error VC_PREFIX_INVALID

### ISSUE THREAD

**Issue by foss-** [corona-warn-app/cwa-app-ios#2871]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: iPhone
- iOS version: 14.6
- App version: 2.3.2

## Describe the bug

When scanning QR-Code to add vaccination to CWA by scanning vaccination confirmation QR-Code receiving:

```
Fehler
Dieser QR-Code ist kein gültiges Impfzertifikat. (VC_PREFIX_INVALID).
```

## Steps to reproduce the issue

Followed in-app steps to add vaccination and scan QR-Code.

## Expected behaviour

Expected for vaccination to be added to app.

## Additional context

Standard vaccination in vaccination center. Identical QR-Code on all documentation. BioNTech was used.

![error](https://user-images.githubusercontent.com/5708172/121261720-5d99e500-c8b3-11eb-937a-3d4c9c94d9ec.jpg)

---
Internal Tracking ID: [EXPOSUREAPP-7703](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7703)

**Comment by thomasaugsten** [comment]
This is not a valid EU certificate you can receive this next week in pharmacy. Can you please share the structure of your code and from which center you receive this.

**Comment by foss-** [comment]
Will have to followup later as my contact running into this is sleeping at this very moment. What do you mean by "structure of your code"? What exact info do you want me to provide?

**Comment by thomasaugsten** [comment]
You can scan the qr code with a qr code scanner app and post the structure in an anonymized way.

**Comment by bockchristian** [comment]
I have scanned the one from my wife, I replaced the name with XXX and the name of the doctor with YYYYYYYY and the birthdate with 000.

This is the barcode she got at the Impfzentrum München after her second shot.

v6c780418797{"state":3,"v3":"000000000000000","v4":true,"v5":true,"v6":true,"v7":true,"v8":true,"v9":false,"va":true,"vb":false,"vg":2,"vk":"YYYYYYY YYYYYY","vl":"","vo":false,"vp":"XXXXXXXXXX XXXXXXX.XXXXXXX.0000-00-00.81735","vc":"8.6.2021","vd":"002","ve":"FA5833","vf":20210702,"vh":false,"vi":"1","vj":"30"}

**Comment by MichaelDzsida** [comment]
Same problem here, iOS 14.6 and “Impfbescheinigung gemäß Paragraf 22 Impfschutzgesetz” from Kreisimpfzentrum produces VC_PREFIX_INVALID

**Comment by Ein-Tim** [comment]
These are not valid EU digital vaccination certificates they were not yet handed out you have to go to a pharmacy next week and they'll give you the right QR-Code. 
See https://www.aponet.de/artikel/corona-digitaler-impfnachweis-ab-14-juni-in-apotheken-24262

**Comment by foss-** [comment]
@Ein-Tim thanks for elaborating. It is what Thomas also said. Maybe an improved error message will help to convey this to users as the current error message is not very helpful.

**Comment by Ein-Tim** [comment]
@foss- 

Since the error message under Android is the same, I suggest to open an issue in the [wishlist repository](https://github.com/corona-warn-app/cwa-wishlist).

Besides of improving the error message there's nothing we can do here, so I suggest to close this.

**Comment by melancholyaeon** [comment]
Hi!

I'm here with a group at TU Darmstadt. We got our first Astras last week because the university got us all into Prio 3.

But we have only our first shot. The Impfzentrum gave us QR codes on a piece of paper. 

Can we scan this? And then the second code from the second dose? Or are we supposed to wait for another document? 

Many of us are not EU citizens so we don't have a "yellow passport," just this xeroxed QR code. The German citizens all have a yellow passport with a numbered sticker AND a QR code. 

Please give us a FAQ on what the workflow for the user is supposed to be & which of the several QR codes we all now have are supposed to scanned. 

Thanks for all your great work! 

Your favorite confused American, 
MelancholyAeon

**Comment by bleft** [comment]
I am having the same issue. 
Impfort: Impfzentrum Kitzingen
Adresse: Marshall-Heights-Ring 15, 97318 Kitzingen

**Comment by thomasaugsten** [comment]
A detailed FAQ entry will follow soon. But this QR Code is not valid EU certificate. If you get your second vaccination next week the vaccination center should print out a EU vaccination certificate:
Example: 
![pdfExample](https://user-images.githubusercontent.com/6367738/121354638-59aba880-c92f-11eb-98bb-9dcbc42d6742.jpg)

**Comment by melancholyaeon** [comment]
Ty!

This more than the hotline knew. Both Spiegel & Tagesshau stories are vague
on what we're supposed to do.

Have a great day.

**Comment by Ein-Tim** [comment]
Hey all, we will se an improvement reg. the error message: #2886

**Comment by dsarkar** [comment]
@foss- @melancholyaeon see:
- **EN** https://www.coronawarn.app/en/faq/#vac_cert_invalid
- **DE** https://www.coronawarn.app/de/faq/#vac_cert_invalid

**Comment by GisoSchroederSAP** [comment]
@All: The FAQ entries exist and will be updated continuously - next update today. We are trying to stay ahead with the dynamics of the events, valid information is given only infrequently, sorry.
So, I recommend to check the above-mentioned FAQ daily until you find the expected guidance.

First news: Beginning next week, a network of pharmacies will be capable to issue digital vaccination statements that can be scanned by the CWA to convert them into the digital European vaccination certificate.

**Comment by mbw83** [comment]
Would it be reasonable to change the text which is written in the app respectively make in more precise? At the moment the app it is clearly says, that I should scan the QR code I received after getting vaccined ("Um ein Impfzertifikat in die App hinzuzufügen, scannen Sie den QR-Code, den Sie bei der Impfung erhalten haben.").
But as @thomasaugsten already mentioned, the QR codes aren't yet handed out when receiving the vaccination, the pharmacies will start with this on monday.

For me it was quite clear what would happen when I scanned the QR code which I got from the Impfzentrum in Munich, because I followed the media. But there might also be other persons which don't know what to do, even if there is now an entry in the FAQ.

**Comment by melancholyaeon** [comment]
@GisoSchroederSAP

TY! Very grateful.

 Once again you all here give more precise info than the hotline staff can
or the not-so-helpful Tagesschau stories that simply say "on Monday some
pharmacies can issue EU QR codes," but give no useful details on the
process.

Thanks for all your work.

**Comment by Ein-Tim** [comment]
@mbw83 

Yes, it is reasonable! We will see a hot fix for this: https://github.com/corona-warn-app/cwa-app-ios/pull/2886

**Comment by Ein-Tim** [comment]
Version 2.3.3 has been released to the App Store and is available for download now:  https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v2.3.3

This has improved the error message and this is all what we can do about this...

**Comment by Ein-Tim** [comment]
I guess this can be closed now @dsarkar?

**Comment by dsarkar** [comment]
@Ein-Tim Thanks, right. As @Ein-Tim mentioned message has improved and also FAQ had been updated some time ago:

- **EN** https://www.coronawarn.app/en/faq/#vac_cert_invalid
- **DE** https://www.coronawarn.app/de/faq/#vac_cert_invalid

Dear @foss-, @melancholyaeon , @mbw83   @bleft, @MichaelDzsida @bockchristian  and all others in the community: Thanks for contributing here. Closing this issue now. Best wishes, DS 

---
Corona-Warn-App Open Source Team
