### ISSUE TITLE
Support wallet for the vaccination 

### ISSUE THREAD

**Issue by iMonZ** [corona-warn-app/cwa-app-ios#2873]
Adding support for the iOS Wallet.
It would be very convenient and would work on the Apple Watch too (so you don’t need just the phone)
And you don’t need to open the Corona warn app every time you want to show your vaccination.
Especially with FaceID enabled this approach now is very inconvenient.
Here is the developers documentation:
https://developer.apple.com/wallet/get-started/

**Comment by Ein-Tim** [comment]
Hey @iMonZ 

We have an issue for this already in the wishlist repo. 

https://github.com/corona-warn-app/cwa-wishlist/issues/503

I'd like to ask you to close this issue here and monitor the other one. 

Thanks and stay safe!

**Comment by iMonZ** [comment]
> Hey @iMonZ
> 
> We have an issue for this already in the wishlist repo.
> 
> [corona-warn-app/cwa-wishlist#503](https://github.com/corona-warn-app/cwa-wishlist/issues/503)
> 
> I'd like to ask you to close this issue here and monitor the other one.
> 
> Thanks and stay safe!

Thanks. I missed that one
