### ISSUE TITLE
GitHub shows 2.2.1 as latest release but 2.3.2 is on my iphone

### ISSUE THREAD

**Issue by alanrick** [corona-warn-app/cwa-app-ios#2875]
![28559D6A-F5C0-4775-B1B8-6A62165FFAB6](https://user-images.githubusercontent.com/7034358/121327496-cadd6280-c913-11eb-9b30-d3d2e4170447.jpeg)
![056CC1CD-9B24-4AF3-8641-C95CFB4CF30E](https://user-images.githubusercontent.com/7034358/121327504-cca72600-c913-11eb-85b4-d1506f8ec25a.jpeg)

This is true in my safari browser despite refresh, and also the iOS GitHub App.

**Comment by Ein-Tim** [comment]
Please see #2868. [According to](https://github.com/corona-warn-app/cwa-website/issues/1343#issuecomment-857480623)@thomasaugsten they will release the version on GitHub tomorrow. 

I suggest to close this issue here in favor of #2868.

**Comment by alanrick** [comment]
Ok. Guess I just don't understand the Release process as I couldn't figure how a release makes it to the Apple App Store when it hasn't been released from GitHub.

**Comment by Ein-Tim** [comment]
@alanrick The uploading to the stores is independent of the GitHub releases. 
See also the FAQ entry: https://www.coronawarn.app/en/faq/#dev_status
