### ISSUE TITLE
Swiping back from the "register your test" screen to the rapid test profile is not animated

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#2881]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 6s
- iOS version: 14.6
- App version: 2.3.2

## Describe the bug

Swiping back from the register your test screen to the rapid test profile is not animated.

https://user-images.githubusercontent.com/67682506/121363340-29680800-c937-11eb-8324-d1841eeaa808.mp4

## Steps to reproduce the issue

1. Open the Corona-Warn-App
2. Click on "Register your Test"
3. Click on "Rapid Test Profile" (if you haven't created one yet create one)
4. Click on "Continue"
5. Only swipe back a bit
6. See that you are thrown back to the rapid antigen test profile screen

## Expected behaviour

The swipe back should be animated and should work as the other swipe backs, if you only swipe back a bit the view does not change.

----
Internal Tracking-ID: [EXPOSUREAPP-7770](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7770)

**Comment by jucktnich** [comment]
Thx

**Comment by jucktnich** [comment]
This qr codes does include your personal data!!!

**Comment by jucktnich** [comment]
@Ein-Tim

**Comment by Ein-Tim** [comment]
Thank you!

**Comment by Ein-Tim** [comment]
Changed to another, non personal data QR-Code. 😅

**Comment by jucktnich** [comment]
For luck does the camera app on the iPhone detect qr codes that fast, if you want to take a picture of something else 😅

**Comment by Ein-Tim** [comment]
Yeah, I just did not thought about this... That was dumb wow! 😂 Thanks again!

**Comment by heinezen** [comment]
@Ein-Tim 

Thank you for the hint. I've mirrored the information to a Jira ticket.

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
PR: #3020

**Comment by ndegendogo** [comment]
According to the PR it was merged with 2.5
@Ein-Tim could you please verify? - Thanks!

**Comment by Ein-Tim** [comment]
@ndegendogo 

Thanks for the ping, I can confirm that this has been fixed in the meantime. 

Closing as fixed.
