### ISSUE TITLE
Typo „übe“ instead of „über“ in German localization

### ISSUE THREAD

**Issue by gruselhaus** [corona-warn-app/cwa-app-ios#2899]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 12 Pro
- iOS version: iOS15 - should not make impact
- App version: 2.3.2 (0)

## Steps to reproduce the issue

![image](https://user-images.githubusercontent.com/33380107/121563853-1af31c80-ca1b-11eb-9402-6276190d7bcd.jpeg)

**Comment by Ein-Tim** [comment]
Strange, the "r" is there on my iPhone 6s, running iOS 14.6 and CWA 2.3.2.

<img src="https://user-images.githubusercontent.com/67682506/121564671-019ea000-ca1c-11eb-80c6-882c8cdd4f0c.jpeg" width="300">

Are you sure about version 2.3.0? This version was never released?

**Comment by gruselhaus** [comment]
Yes, 2.3.2. Sorry for that.

**Comment by gruselhaus** [comment]
Alright. Closing this issue for now. Could come up when you are preparing for iOS 15 compatibility again.
