### ISSUE TITLE
Testflight?

### ISSUE THREAD

**Issue by capsload2** [corona-warn-app/cwa-app-ios#29]
A testflight now would be very nice. Or at least before the public launch

**Comment by tkowark** [comment]
As stated in https://github.com/corona-warn-app/cwa-documentation/issues/92 and https://www.coronawarn.app/en/faq/ , testflight builds will only be available to the Corona-Warn-App project team and our partners (German Federal Government, Robert Koch-Institute, BSI, BfDI etc.).
