### ISSUE TITLE
Certificates don't store on iPhone Simulator

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#2907]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 12 Pro Simulator
- iOS version: 14.5
- App version: 2.3.3 (0) & 2.4.8 (0)

## Describe the bug

The vaccination certificate does not store correctly in the Simulator:

https://user-images.githubusercontent.com/67682506/121705991-7d105800-cad5-11eb-89b1-931122668b7f.mp4

## Steps to reproduce the issue (Instructions for the `release/2.4.x` branch)

1. Open the Corona-Warn-App on a Simulator
2. Click on "Certificates" in the tab bar
3. Click on the card "Add Digital Proof of Vaccination"
4. See the pop-up saying "Digital Proof of Vaccination"
5. Close the pop-up via the x in the right corner
6. See that the vaccination certificate was not added to the app

## Expected behaviour

The certificate should have been added.

## Possible Fix

Store the certificate in the db.

## Additional context

Could be that this is intended on a Simulator - if it's please clarify why.

----
Internal Tracking-ID: [EXPOSUREAPP-7969](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7969)

**Comment by heinezen** [comment]
@Ein-Tim 

Thanks for reporting. The dev team has been informed. Tracked under  [EXPOSUREAPP-7969](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7969)

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
Problem persists on `release/2.5.x` branch.

**Comment by Ein-Tim** [comment]
Sadly, this is also a problem on the `release/2.6.x` branch. I would have liked to take a look at the new DCC rules feature and also include it in my Tweet about the next version from Corona-Warn-App... 😕

**Comment by dsarkar** [comment]
@Ein-Tim We updated the internal ticket accordingly. Thanks.

**Comment by ndegendogo** [comment]
@Ein-Tim [try this](https://github.com/corona-warn-app/cwa-app-ios/issues/3567#issuecomment-932827610) and consider to close the ticket

**Comment by Ein-Tim** [comment]
This issue was solved by the Universal QR code scanner too, it's now possible to import real certificates into the Simulator and they will store there.

Thanks @ndegendogo for pointing this out in https://github.com/corona-warn-app/cwa-app-ios/issues/3567#issuecomment-932827610.

Closing as fixed.

**Comment by ndegendogo** [comment]
😁😁😁😁😁
