### ISSUE TITLE
❓ Digitaler Impfnachweis auch ohne Entsperren des Telefons möglich?

### ISSUE THREAD

**Issue by riconeitzel** [corona-warn-app/cwa-app-ios#2919]
Wie ist aktuell die Impfstatus-Anzeige implementiert? Geht das ausschließlich in der App bei entsperrtem Telefon oder gibt es eine Wallet-Integration?

Ich möchte gerne verhindern, dass ich bei Kontrollen mein entsperrtes Telefon präsentieren muss (Diebstahlschutz, Schutz der Privatsphäre). Daher ist eine Integration in die Wallet durchaus interessant, für die ein Entsperren des Telefons nicht erforderlich ist.

Vielen Dank für eine kurze Rückmeldung :-)
Rico

**Comment by Ein-Tim** [comment]
Hey @riconeitzel 

Nein, es gibt momentan keine Wallte integration. Allerdings wird darüber diskutiert: https://github.com/eu-digital-green-certificates/dgca-wallet-app-ios/issues/69, https://github.com/corona-warn-app/cwa-wishlist/issues/503 & https://github.com/Digitaler-Impfnachweis/certification-apis/discussions/37.

Du kannst allerdings einfach den QR-Code ausdrucken und diesen vorzeigen, das geht genau so.

**Comment by kevin-kraus** [comment]
> Hey @riconeitzel 
> 
> Nein, es gibt momentan keine Wallte integration. Allerdings wird darüber diskutiert: https://github.com/eu-digital-green-certificates/dgca-wallet-app-ios/issues/69, https://github.com/corona-warn-app/cwa-wishlist/issues/503 & https://github.com/Digitaler-Impfnachweis/certification-apis/discussions/37.
> 
> Du kannst allerdings einfach den QR-Code ausdrucken und diesen vorzeigen, das geht genau so. 

Aber ist ausdrucken nicht voll so garnicht 2021? 😉

**Comment by Ein-Tim** [comment]
@kevin-kraus 

Nein, eher nicht. Aber es sieht nicht so aus als würden wir schnell eine Apple Wallet integration bekommen. 😅

Außerdem scheint es so das man auf dem Sperrbidlschirm nur Apple Pay Karten sehen kann, und keine anderen Sachen (QR-Codes, Tickets, etc.) sehen, also müsstest du dein Handy auch dafür entsperren... 

(Siehe https://github.com/eu-digital-green-certificates/dgca-wallet-app-ios/issues/69#issuecomment-860042008)

**Comment by kevin-kraus** [comment]
@Ein-Tim 

Das mit den Apple Pay Karten scheint eine Fehlinformation gewesen zu sein. Ich sehe bei mir auch bei gesperrten Gerät sämtliche andere Pässe im Wallet. 

Ich dachte auch der Verfasser hatte sein Kommentar korrigiert. Soweit ich weiß ist das Einstellungssache (siehe Screenshot). 

![image](https://user-images.githubusercontent.com/36297312/121892679-580e2600-cd1d-11eb-8781-18e6893ff8e5.png)

**Comment by Ein-Tim** [comment]
@kevin-kraus Okay thanks, @jucktnich, is the setting "Wallet" active on your phone?

**Comment by kevin-kraus** [comment]
> @kevin-kraus Okay thanks, @jucktnich, is the setting "Wallet" active on your phone?

I think he didn't try it by himself but rather got that information out of the official documentation. 

(See this comment.)[https://github.com/eu-digital-green-certificates/dgca-wallet-app-ios/issues/69#issuecomment-860042008]

**Comment by riconeitzel** [comment]
Should I close this ticket? 😄 *insert not sure if gif here*

**Comment by Ein-Tim** [comment]
@riconeitzel Yes, I think your request is covered by the issues I linked to, isn't it?

**Comment by kevin-kraus** [comment]
I think we've answered all your questions here. If not you can always reopen 😄

**Comment by riconeitzel** [comment]
I was unsure whether that request might be submitted by others as well 😄 so perhaps this could be a resident for a while. Anyway … I'll close it. make it sticky or reopen it, if you feel it could prevent duplicate requests.

Take care and thanks for your help!
Rico

**Comment by jucktnich** [comment]
@Ein-Tim yep

**Comment by jucktnich** [comment]
@kevin-kraus which cards can you access from lockscreen, since there more cards out there with Apple Pay integration than you might think

**Comment by riconeitzel** [comment]
you can access cards without unlocking your phone. I verified it today. subway customer card, mediamarkt customer card, IKEA Family Card …

**Comment by jucktnich** [comment]
@riconeitzel sure they don't fit these categories?

**Comment by kevin-kraus** [comment]
> @riconeitzel sure they don't fit these categories? "If you have a credit, debit, prepaid, store card, or a rewards card in Wallet that works with Apple Pay, double-click the Home Button from the Lock Screen to open Wallet. On iPhone X or later, double-click the Side button."

@jucktnich 

According to their documentation [here](https://developer.apple.com/wallet/) you can also add generic passes that don't fit apples example passes.

**Comment by jucktnich** [comment]
@kevin-kraus the requirements I put there where to access them without authentication

**Comment by kevin-kraus** [comment]
@jucktnich as far as I can try and see there is no Limitation to these types of passes to access without authentication.

**Comment by jucktnich** [comment]
@kevin-kraus [This](https://support.apple.com/en-us/HT204003) is the Support article

**Comment by jucktnich** [comment]
At @kevin-kraus 
`I think he didn't try it by himself but rather got that information out of the official documentation. `
i tried it on my own device and it behaved like in the documentary 😉

**Comment by kevin-kraus** [comment]
> @kevin-kraus [This](https://support.apple.com/en-us/HT204003) is the Support article

@jucktnich 

I can see what you mean. As far as I can tell, based on the passes on my phone, I can access tickets and any other Typ of pass in Wallet while the phone is locked. 

I've tried following Types of passes:

- Boarding Pass
- Ticket
- Gift Card
- Other 

and I can access all of these in the locked state.

**Comment by Ein-Tim** [comment]
Which iOS versions are you using?

**Comment by kevin-kraus** [comment]
> Neither the iTunes pass nor the tickets of the Deutsche Bahn work on the homescreen on my device

@jucktnich have you made sure you have checked the option as shown [here](https://github.com/corona-warn-app/cwa-wishlist/issues/503#issuecomment-860671362)?

**Comment by jucktnich** [comment]
@Ein-Tim iOS 14.6 (and see correction above)

**Comment by jucktnich** [comment]
@kevin-kraus yeah, for sure
