### ISSUE TITLE
CovPassCheck app cannot verify vaccination certificate stored in CWA (verifying the same certificate works from CovPass)

### ISSUE THREAD

**Issue by Ondolin** [corona-warn-app/cwa-app-ios#2927]
## Technical details

- Device name: iPhone 11 Pro Max
- iOS version: 14.6
- App version: 2.3.3

## Describe the bug

When trying to verify the vaccination certificate using the official CovPass Check app the code is not recognized at all. (No error, no verification) The exact same certificates were recognised when using the android equivalent of this app. We've tried with the Biontech and the Johnson and Johnson vaccine. In all tested cases the certificate was not yet valid (5-9 days left).

## Steps to reproduce the issue

1. Register a "Digital Proof of Vaccine"
2. Open the CovPass Check app
3. Scan the code
4. Nothing happens

## Expected behaviour

The same information message about the invalid vaccination status we saw on android.

## Additional information

When using the CovPass App on iOS with the same vaccination certificates everything works as expected. So we can isolate the error to the "corona warn app" for iOS.

----
Internal Tracking-ID: [EXPOSUREAPP-7970](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7970)

**Comment by thomasaugsten** [comment]
Please report issue with the COVPass Apps to the COVPass team
Github:
https://github.com/Digitaler-Impfnachweis/documentation/issues
Hotline numbers:
https://digitaler-impfnachweis-app.de/faq/
Email:
impfnachweis@rki.de

**Comment by Ondolin** [comment]
This error is not related to CovPass. The error only occurs when the certificate is from the iOS version of the "corona warn app". When using the android app or an alternative app like the "CovPass" app the certificate works as intended.

**Comment by thomasaugsten** [comment]
Hi
can you please write exactly if the certificates are valid or not and what you expect so see on the covpass check app.
Please provide an exampe code to
thomas.augsten@sap.com

**Comment by krisrdvc** [comment]
I just tried to reproduce the issue, but it wasn't present. Tested on 11 Pro, 14.6 and iPhone 7 on 15.0.

**Comment by Ondolin** [comment]
We just did some more testing and discovered that the error only occurs when checking an iOS Code with an Android CovPass Check app.

**Comment by Ondolin** [comment]
Updates regarding this bug:

The "CovPass Check" app on Android is not capable of checking QR-codes from the Corona warn app. Checking codes from the "CovPass" works fine though.

**Comment by heinezen** [comment]
@Ondolin 

Thank you for reporting the issue. We have now created an internal ticket for tracking the issue  [EXPOSUREAPP-7970](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7970). The dev team will look for a solution.

----
Corona-Warn-App Open Source Team

**Comment by thomasaugsten** [comment]
The problem here is the camera of the android device. The scanner is not reacting on the QR-Code to solve the problem you need a distance of 30-50cm to the qr-code. This can also happens with printed qr-codes

**Comment by EricHier** [comment]
No matter how far we move the scanning device away from the qr code - it does not work. The lighting conditions were perfect and the qr code was in focus all the time.

**Comment by thomasaugsten** [comment]
What kind of devices you are using?

**Comment by dsarkar** [comment]
@EricHier See question from T Augsten, please. Thanks.

**Comment by EricHier** [comment]
> What kind of devices you are using?

We already send emails with all details to @thomasaugsten. But here are the details again: 

Scan App: OnePlus 7 Pro with Android 11
CWA: iPhone 11 Pro Max with iOS 14.6

**Comment by thomasaugsten** [comment]
But via email was the response with enough distance the scanning was working

**Comment by EricHier** [comment]
> But via email was the response with enough distance the scanning was working

No that is not correct. The response was that we were able to scan the screenshot on the pc but not on the iPhone itself.

**Comment by thomasaugsten** [comment]
But I saw in the video succesfull scanning. But I will contact you directly

**Comment by dsarkar** [comment]
related: https://github.com/corona-warn-app/cwa-app-ios/pull/2992

**Comment by Ondolin** [comment]
Bug was resolved with version 2.4.2
