### ISSUE TITLE
Could not add vaccination certificate after adding and removing test certificate

### ISSUE THREAD

**Issue by Tmkrth** [corona-warn-app/cwa-app-ios#2933]
Hello! I have CWA installed since it is available on an iPhone SE (2016) with latest iOS.

Last week I tested adding the test certificate https://github.com/Digitaler-Impfnachweis/certification-apis/tree/master/examples. It worked and I removed it again.

Yesterday I went to the pharmacy and got the QR code for my vaccination. Adding it to CWA did not work, the message was in the sense of: "You cannot add another person's certificate".

Removing CWA from the phone and reinstalling it solved it.

Sincerely,

**Comment by Ein-Tim** [comment]
Are you sure that you removed the old certificate?

**Comment by Tmkrth** [comment]
Yes, it was removed beforehand.

**Comment by Ein-Tim** [comment]
Not reproducible for me:

1. Scan the QR code from https://github.com/Digitaler-Impfnachweis/certification-apis/tree/master/examples
2. Remove it
3. Scan the QR code from https://github.com/eu-digital-green-certificates/dgc-testdata/tree/main/DE
4. See that it works without any issues.

Are you sure you did the following: 

https://user-images.githubusercontent.com/67682506/122054768-480f4880-cde8-11eb-93b2-a9d7da05a1c1.mp4

And not just clicked on "Weitere Impfung hinzufügen"?

**Comment by Tmkrth** [comment]
I also cannot reproduce it now.

I removed/added the app and added/removed the test certificate. Could add real certificate this time without any error.

Maybe I didn't operate the app correctly last time, sorry. Thanks for taking time.
