### ISSUE TITLE
White screen - app not starting

### ISSUE THREAD

**Issue by vwdss** [corona-warn-app/cwa-app-ios#2955]
## Technical details

- Device name: iPhone 11 Pro Max
- iOS version: iOS 14.6
- App version: 2.3.3

## Describe the bug

1. Cannot click 'Activate Exposure Logging' without going back.
2. Cannot enable exposure logging
3. App shows white screen after first use

## Steps to reproduce the issue

https://user-images.githubusercontent.com/3357905/122245931-6e0b1a80-cec6-11eb-8542-ab40e02d6711.mp4

--- 

Internal Tracking-ID: [EXPOSUREAPP-7862](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7862)

**Comment by Ein-Tim** [comment]
Hey @vwdss 

#2951 is the fix for this, it has been merged into `release/2.4.x`, so this should be fixed in the next version. 

Please leave this issue open until you can confirm that the fix in version 2.4 (which is still in development) is working. 

--- 

Internal Tracking-ID: [EXPOSUREAPP-7862](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7862)

**Comment by Ein-Tim** [comment]
@dsarkar 

I assume the `fix 2.0` label was added here by mistake. Please remove it and add the `fix 2.4` label here. 

Thank you!

**Comment by thomasaugsten** [comment]
@vwdss can you please retest after manually update on v2.4?

**Comment by vwdss** [comment]
@thomasaugsten unfortunately it did not help. I removed the app and reinstalled - also did not help.

**Comment by heinezen** [comment]
@vwdss Thanks for checking. We'll take another look

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
PR fo 2.5: #3037

**Comment by dsarkar** [comment]
@vwdss have you tried this?

- DE https://www.coronawarn.app/de/faq/#ios_black_screen
- EN https://www.coronawarn.app/en/faq/#ios_black_screen

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@dsarkar 

I don't think this is related here since the white or black screen back then was shown in the iOS settings and not in CWA. But give it a try @vwdss.

**Comment by dsarkar** [comment]
@Ein-Tim OK, your are probably right, I might have mixed that up here. Thanks for pointing it out!

**Comment by vwdss** [comment]
> @vwdss have you tried this?
> 
> * DE https://www.coronawarn.app/de/faq/#ios_black_screen
> * EN https://www.coronawarn.app/en/faq/#ios_black_screen
> 
> Corona-Warn-App Open Source Team

Just tried. Did not help. After reset step, app still opens with white screen.

**Comment by dsarkar** [comment]
@vwdss Thanks for the feedback. Hopefully the fix in 2.5 resolves your issue.


---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@vwdss Could you try it again with version 2.5?

**Comment by vwdss** [comment]
> @vwdss Could you try it again with version 2.5?

It works 🎉

**Comment by Ein-Tim** [comment]
@vwdss 

Nice! 🎉

Can you confirm that the exposure logging is also working correctly?

**Comment by vwdss** [comment]
@Ein-Tim I managed to enable it, and it seems it works.

**Comment by dsarkar** [comment]
@vwdss Thanks for the feedback.

**Comment by dsarkar** [comment]
Re-opened since there are more reports on this issue and related PRs.

**Comment by Ein-Tim** [comment]
@dsarkar Has the internal ticket been set to "Fix in 2.7 confirmed"? OR is this still not finally fixed with 2.7?

**Comment by heinezen** [comment]
@Ein-Tim We are sure that it's fixed by now.

----
Corona-Warn-App Open Source Team
