### ISSUE TITLE
Why has the App Store Age rating been changed to 17?

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#2984]
## Avoid duplicates
* [X] Question is not already answered in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Question is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Question has not already been asked in another issue

## Your Question
The App Store showed CWA as rated for age 12 until recently. Now it has changed to 17 again, although the terms of use still say that if you're 16 or older, you're allowed to use the app. 
Why has the rating been changed? Because of the vaccination certificates?

**Comment by dsarkar** [comment]
@Ein-Tim Apple updated age rating settings in App Store Connect, which led to the rating changed to 17. See https://developer.apple.com/news/?id=fwpxy9kw. The option 12+ does not exist anymore.

**Comment by Ein-Tim** [comment]
@dsarkar 

Thanks! I even read the news from Apple but did not think it would affect CWA in any way.

> The option 12+ does not exist anymore.

Are you sure about this? 

CovPass is still listed as 12+:

<img src="https://user-images.githubusercontent.com/67682506/122923124-a1d1be80-d364-11eb-9c40-9e1d9cab8ccd.png" width="300">

**Comment by heinezen** [comment]
@Ein-Tim

The age rating was increased because medical treatment information is part of the app. We don't know why CovPass is rated 12+.

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@heinezen 

Okay thanks. I'll open a wishlist issue regarding this which asks for an enhancement regarding this.
