### ISSUE TITLE
Change system date will skip the waiting time

### ISSUE THREAD

**Issue by b3nsen** [corona-warn-app/cwa-app-ios#2996]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 11 Pro
- iOS version: 15 (Dev Beta 1)
- App version: 2.3.3

## Describe the bug

Hey :) 

In case you got your vaccination certificate inside the app, you need to wait 14 days until the vaccination is completed. 
But if you turn the date of your phone to a future date (+14 days e.g.) the state changed to “complete” 

## Steps to reproduce the issue

See above 

## Possible Fix

The waiting time should not be based on the system time. Maybe a counter will solve the problem

**Comment by Ein-Tim** [comment]
Hey @b3nsen 

We are aware of this and this is not a problem. You can find more information in: https://github.com/corona-warn-app/cwa-documentation/issues/642

I would suggest to close this issue.

Thank you anyways for reporting! Have a nice evening and stay safe!

**Comment by b3nsen** [comment]
Didn't see the other report. 
Thank you! 

But an internal timer / counter could still solve the problem of manipulation :)
