### ISSUE TITLE
Vollständiger Impfschutz wird einen Tag zu früh angezeigt 

### ISSUE THREAD

**Issue by ulibestfleisch** [corona-warn-app/cwa-app-ios#2997]
Wenn man exakt 14 Tage nach der letzten Impfung den Impfstatus in der Corona Warn App überprüft wird dieser blau hinterlegt und mit einem Haken für vollständigen Impfschutz hinterlegt. Bei der CovPass App und CovPass Check App wird das Zertifikat aber zu dem Zeitpunkt noch als ungültig gewertet. Dort wird der Impfschutz erst einen Tag später als vollständig gewertet. Das ist laut [Verordnung](https://www.bmjv.de/SharedDocs/Gesetzgebungsverfahren/Dokumente/Verordnungsentwurf_Corona-Impfung.pdf?__blob=publicationFile&v=7) aus meiner Sicht auch richtig.

Die Berechnung in der Corona Warn sollte entsprechend korrigiert werden, um Irritationen zu vermeiden.

**Comment by Ein-Tim** [comment]
Hallo @ulibestfleisch 

Dieser Fehler ist bereits bekannt und wurde in https://github.com/corona-warn-app/cwa-documentation/issues/638 gemeldet. 
Das nächste Update wird diesen Fehler beheben.

Schließe gerne deinen Issue, damit sich Kommentare auf https://github.com/corona-warn-app/cwa-documentation/issues/638 konzentrieren. 

Danke trotzdem und einen schönen Abend!
