### ISSUE TITLE
Type-safe access to resources

### ISSUE THREAD

**Issue by SvenTiigi** [corona-warn-app/cwa-app-ios#30]
## Current Implementation
Currently resources like localizable string files, xcassets and Storyboard identifiers/segues are not checked by the compiler which opens up various scenarios for bugs.

- If a localized key has been added, changed or removed the `AppStrings.swift` and `AppInformationDetailModelData.swift` files needs to be updated manually. If this gets forgotten a wrong or no localized string will be shown to the user.
- If an asset for example an icon has been added, changed or removed the corresponding usage must be updated manually. If this gets forgotten a wrong or no asset will be displayed.
- If a color has been added, changed or removed the `UIColor+ColorStyle.swift` file needs to be updated manually. If this gets forgotten the wrong color will be displayed.
- If a Storyboard identifier has been added, changed or removed the `AppStoryboard.swift` file needs to be updated manually. If this gets forgotten the app could potentially crash.
- If a Storyboard segue name has been added, changed or removed the corresponding usage must be found within the project and updated manually. If this gets forgotten the app could potentially crash or a wrong ViewController gets displayed.

## Suggested Enhancement
Implementing [SwiftGen](https://github.com/SwiftGen/SwiftGen) via a build script phase to auto-generate the Swift code for localized strings, xcassets, Storyboard identifiers and segues.

## Expected Benefits
- Auto-completion for any kind of resources
- Compiler checked resources which eliminates all kind of bugs where the usage of a specific resource has not been updated alongside to its modification.

---
Internal Tracking ID: EXPOSUREAPP-3006

**Comment by flashspys** [comment]
Alternative to SwiftGen would be [R.swift](https://github.com/mac-cain13/R.swift)

**Comment by ChristianKienle** [comment]
On hold for now due to critical project phase. We will come back to this in 1-2 weeks.

**Comment by Ein-Tim** [comment]
@ChristianKienle Said he would come back in 1-2 weeks, however, nearly 2 years now passed without feedback from him.

If there is no development on this issue and nothing is planned, I suggest to close this issue.

**Comment by dsarkar** [comment]
@SvenTiigi @flashspys  Thanks to everybody for contributing here. This issue became stale, therefore we are closing it. Feel free to open a new issue for any further suggestions, discussions, bug reports, etc. Many thanks again! Best wishes, DS

---
Corona-Warn-App Open Source Team
