### ISSUE TITLE
Changing date to the future makes vacination certificate visualy valid during 14 day waiting period

### ISSUE THREAD

**Issue by reptil1990** [corona-warn-app/cwa-app-ios#3005]
## Technical details

- Device name: iPhone 11 pro
- iOS version: 16.4
- App version: 2.3.3

## Describe the bug

If you set the date manually on the iphone to the future you will get an error message that the date is not correct.
Nerver the less the certificate will be visually shown as completed.
If someone is not scanning the barcode and just paying attention to the visual it will be dangerous, since a person can get access to areas he is not yet supposed to access

## Steps to reproduce the issue

Set the date in the settings a few days to the future and click ok on the error message.

## Expected behaviour

If the Date check fails the certificate should not be shown as completed.

## Possible Fix

Render the certificate as red or not valid if the Date check fails. So it is visually clear!

**Comment by reptil1990** [comment]
Already fixed in 2.4

**Comment by reptil1990** [comment]
I saw there is already a discussion on this issue.
BUT we are all lazy humans and i don´t think a barkeeper will scan 10 barcodes to check. He will just check visually.

**Comment by Ein-Tim** [comment]
@reptil1990 

I see you're point, but I would still like to ask you to follow up in https://github.com/corona-warn-app/cwa-documentation/issues/642 instead of opening a new issue for this.

So please, add your comment to https://github.com/corona-warn-app/cwa-documentation/issues/642 and close this issue.

Thanks!

**Comment by reptil1990** [comment]
MOVED! [#642](https://github.com/corona-warn-app/cwa-documentation/issues/642)
