### ISSUE TITLE
Date of full vaccination incorrect?

### ISSUE THREAD

**Issue by krausf** [corona-warn-app/cwa-app-ios#3008]
According to federal regulations, one is fully vaccinated on the 15th day after vaccination.
This rule is implemented in the CovPass App, but not the CWA App.

Background:
My CWA App shows that I am already fully vaccinated on the 14th day, whereas the CovPass App shows, that I am fully vaccinated on the 15th day. (of course using the same QR code)

**Comment by Ein-Tim** [comment]
@krausf 

This has been fixed in version 2.4. Please update your app and confirm the fix. Thanks.

**Comment by krausf** [comment]
That fixed it. Thanks!
