### ISSUE TITLE
Tests card disappeared from start page after 2.4.2 update

### ISSUE THREAD

**Issue by Pe-te** [corona-warn-app/cwa-app-ios#3015]
Hi, I had two test certificates scanned in the app and now both are gone after I upgraded the app to v2.4.2 in the app store.

iPhone SE (1st gen), iOS 14.6, app v2.4.2 now, probably v2.4.1 before

**Comment by Ein-Tim** [comment]
@Pe-te 

Did you scan test or vaccination certificates?

Did you take a look in the "Cerrificates" tab which is on the bottom of the screen?

**Comment by Pe-te** [comment]
Oh okay, that explains it, thanks!

They are now in the certificate tab on the bottom. But I'm pretty sure it was on the start page right below the Risiko-Card? Did you move them? Can I get them back somehow? Now I only see a Tests-Card below the Risiko-Card.

**Comment by Ein-Tim** [comment]
@Pe-te 

No, all certificates were permanently moved to the certificates tap with version 2.4, so there is no way of bringing them back to the home screen, sorry. 

If you consider your question as answered, feel free to close this issue.

**Comment by Pe-te** [comment]
Oh no, i just want to show people my fancy Impfnachweis! 😄 
Please add some option to start on the second tab then ...

Thx for the explanation until then!

**Comment by Ein-Tim** [comment]
> Please add some option to start on the second tab then ...

Feel free to open a new feature request for this here: https://github.com/corona-warn-app/cwa-wishlist. 🙂

**Comment by Pe-te** [comment]
aye aye!

https://github.com/corona-warn-app/cwa-wishlist/issues/566
