### ISSUE TITLE
Cell selection doesn't disappear on FAQ card

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#3039]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 6s 
- iOS version: iOS 14.6
- App version: 2.4.2

## Describe the bug

The cell selection doesn't disappear on the FAQ card after it has been clicked or isn't selected anymore: 

https://user-images.githubusercontent.com/67682506/123840668-e7672c00-d90e-11eb-8cb7-35dce5071871.mp4

## Steps to reproduce the issue

1. Open the Corona-Warn-App
2. Scroll down to the "Frequently Asked Questions" card
3. Click on the card
4. Return to the app 
5. See that the selection effect is still shown

## Expected behaviour

The cell selection effect should only be shown when the cell is really selected.

----
Internal Tracking-ID: [EXPOSUREAPP-8290](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8290)

**Comment by heinezen** [comment]
Thanks, I've reported the issue to the devs.

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
PR #3146

**Comment by Ein-Tim** [comment]
This has been fixed in version 2.6.

Closing as fixed.
