### ISSUE TITLE
Receiving VC_JSON_SCHEMA_INVALID error when scanning a Hungarian EU vaccination certificate

### ISSUE THREAD

**Issue by RolandSzep** [corona-warn-app/cwa-app-ios#3057]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 11 Pro Max
- iOS version: 14.6
- App version: 2.4.2

## Describe the bug

I get the following error message when scanning a valid EU vaccination certificate:

<img src="https://user-images.githubusercontent.com/19844622/124113100-56f22e00-da6b-11eb-8edb-fec52bb96074.PNG" width=50% height=50%>

## Steps to reproduce the issue

1. Go to 'Certificates'
2. Click on 'Add **Digital Proof of Vaccination**'
3. Scan the QR code on the 'EU Digital COVID Certificate'

## Expected behaviour

Expected the certificate to be added to the app.

## Additional context

I get the error message for both of my vaccination certificates (1st and 2nd dose). The issue is iOS specific, I had no problem on Android. My certificate was issued in Hungary and is valid.

---
Internal Tracking ID: [EXPOSUREAPP-8222](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8222)

**Comment by dsarkar** [comment]
@RolandSzep Thank you very much for your report. Did you try to scan the certificate with the 
- CovPass-App
- CovPassCheck-App

Feedback very much appreciated.
Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by RolandSzep** [comment]
@dsarkar Unfortunately those apps are not available in the Hungarian App Store/Google Play. I would love to use them though, our local vaccine certificate app is a mess, hard to use and requires network connection...

<img src="https://user-images.githubusercontent.com/19844622/124256411-8cf6e700-db2b-11eb-9ce7-734c18424f0c.PNG" width=30% height=30%>

**Comment by dsarkar** [comment]
@RolandSzep Thanks for your feedback. Did you check if Hungarian EU DCCs are not scannable in general? E.g. tried to scan a DCC from another person.

**Comment by thomasaugsten** [comment]
@RolandSzep  Can you please provide me the qr code via email and we will check this
thomas.augsten@sap.com

**Comment by RolandSzep** [comment]
@dsarkar I can successfully scan my certificates with the Danish "Coronapas" or the Dutch "Scanner" apps for example.

<img src="https://user-images.githubusercontent.com/19844622/124258394-a1d47a00-db2d-11eb-9569-8652a72f7f9f.PNG" width=30% height=30%>

@thomasaugsten Sure, one moment.

**Comment by thomasaugsten** [comment]
The issue here is the version of the QR-Code it is higher than we use in 2.4. We will update the scanner for new Qr-Code versions in v2.5. This will be released in the next 14days

**Comment by RolandSzep** [comment]
Great, thank you, have a nice day!

**Comment by dsarkar** [comment]
@RolandSzep Thanks for contributing. Can you confirm that you could scan successfully your certificate? Thanks.

---
Corona-Warn-App Open Source Team

**Comment by RolandSzep** [comment]
@dsarkar Yes, it's working in v2.5.1.

**Comment by dsarkar** [comment]
@RolandSzep Thanks for the feedback! Best regards, DS

---
Corona-Warn-App Open Source Team

**Comment by schurig** [comment]
Same error happens to me since this morning (release 2.7.1). I have a valid certificate issued by Servei Català de la Salut:
![screenshot](https://user-images.githubusercontent.com/2672413/129556589-6c93b575-a5c1-485a-b02d-85f87f93e5dc.jpeg)

**Comment by thomasaugsten** [comment]
I assume you have a space in your first or last name. Spain did a mistake when they create the ICAO format of the name we will accept this with the next version 2.8 in 14 days

**Comment by schurig** [comment]
@thomasaugsten yes, that's indeed the case. Thanks!
