### ISSUE TITLE
Error 13, after 4 checks today

### ISSUE THREAD

**Issue by ndegendogo** [corona-warn-app/cwa-app-ios#3087]
## Avoid duplicates
* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue
(several similar reports: #2316, #2327, #2395, #2415, #2450, #2485, #2521, #2758, #2879)

## Technical details

- Device name: iPhone 8
- iOS version: iOS 14.4.1
- App version: 2.4.2 (0)

## Describe the bug
I open cwa and get error 13. See screenshot.
The button 'mehr erfahren' tells me that ENF only allows 6 checks per day; but according to 'Begegnungsmitteilungen' I had only 4 checks today, see screenshot.

## Expected behaviour

No error message

## Additional context

If it helps, I can try to create an error log.

**Comment by ndegendogo** [comment]
![IMG_1131](https://user-images.githubusercontent.com/6118267/124367058-68e2f500-dc54-11eb-8a75-f97b9de8a34d.png)

![IMG_1132](https://user-images.githubusercontent.com/6118267/124367063-74362080-dc54-11eb-8dc2-17088068850d.png)

**Comment by Ein-Tim** [comment]
@ndegendogo 

What does the risk card show? Exposure Check failed?
Did a restart change something?

**Comment by ndegendogo** [comment]
@Ein-Tim Exactly, risk card tells me that the test failed. When I press the button 'Erneut starten' I get the error message again (error 13).

**Comment by ndegendogo** [comment]
> Did a restart change something?

What do you mean with "restart"? Reboot the phone? Or just press the home button and launch cwa again?
I get the error message each time when I start cwa.

**Comment by Ein-Tim** [comment]
@ndegendogo 

Okay thanks, that's indeed strange. 
If you want to share your EN-Log here, feel free to, maybe there's something in it that's not shown in the UI.

Yes, with restart I mean reboot, sorry for not being clear here. 


<details>
<summary>How to export Exposure Notificaiton Logs under iOS 13.7 or newer</summary>


**German:**

`Einstellungen` ➡️ `Begegnungsmitteilungen` ➡️ `Status von Begegnungsaufzeichnungen` ➡️ `Begegnungsüberprüfungen` ➡️ `Überprüfungen exportieren`

**English:**

`Settings` ➡️ `Exposure Notifications` ➡️ `Exosure Logging Status` ➡️ `Exposure Checks` ➡️ `Export Exposure Checks`

**To upload the file here, rename it from .json to .txt**
</details>

**Comment by ndegendogo** [comment]
Update: Now it is after midnight (local time), and the **error 13 is gone, I got a successfull risk check** after opening cwa again.

*(strange... I will keep the ticket open and watch it for a few days ...)*

**Comment by ndegendogo** [comment]
> If you want to share your EN-Log here, feel free to, maybe there's something in it that's not shown in the UI.

@Ein-Tim you are right 👍 - there is indeed an irregularity in the ENF log, preceding the failed risk check.
I'll export the file and upload it here.
Did you have successful checks yesterday late night? If yes: could you please also export your ENF log, so we can compare? 😁

**Comment by Ein-Tim** [comment]
@ndegendogo 

Last check was at 21:09h yesterday, here's my EN-Log:

[ExposureChecks-2021-07-04.txt](https://github.com/corona-warn-app/cwa-app-ios/files/6759910/ExposureChecks-2021-07-04.txt)

**Comment by ndegendogo** [comment]
Uploaded my log - see [here](https://github.com/corona-warn-app/cwa-app-ios/issues/3087#issuecomment-873585015)

To read and interprete an ENF log file, the following helps:
- the entries are in *inverted chronological* order (youngest first); so to read it chronologically you start from the bottom
- the hourly files of current day are presented first to ENF, followed by the daily files of the past two weeks
- hourly files are presented in inverted chronological order (youngest first)
- daily files are presented in chronological order (oldest first)
- wrap-up of a day is done at 00:00 UTC (corresponding to 02:00 MESZ); 
   so the number of hourly files should be `current hour - 2`

The entry of "2021-07-03 14:20:47 +0200" is as expected:
- "Hash" : "4D680525..." => youngest daily file (02 July)
- "Hash" : "AB6CFF7F..." => oldest daily file (19 June)
- "Hash" : "D6DACA69..." => oldest hourly file (03:00)
- "Hash" : "D82F3458..." => youngest hourly file (14:00)

But the next entry of "Timestamp" : "2021-07-03 18:21:18 +0200" misses two entries:
- "Hash" : "4D680525..." => youngest daily file (02 July)
- "Hash" : "AB6CFF7F..." => oldest daily file (19 June)
- "Hash" : "D6DACA69..." => oldest hourly file (03:00)
- "Hash" : "D82F3458..." => hourly file (14:00)
- "Hash" : "CAB94E48..." => hourly file (15:00)
- "Hash" : "792C6CE..." => hourly file (16:00)
- **no new hourly files for 17:00 and 18:00**

**Comment by ndegendogo** [comment]
@Ein-Tim And your file looks pretty normal / as expected.
The only difference I see between our files is thatmine checks faster ( ~ 1 sec, whereas yours needs 2 - 3 seconds).

**Comment by ndegendogo** [comment]
... and yesterday evening I went shopping ... 
I don't remember the exact time, but **it could well be that I was without WLAN at 18:21** (which would be consistent with a check with two hourly files missing, because it downloads the files every two hours, but checks them every four hours).

**Comment by heinezen** [comment]
Hello everyone,

Occurences of Error 13/Fehler 13 should be fixed with the recent CWA release 2.5. Please update your app and report back if the error still persists for you when using the newest version. We will close the issue for now.

----
Corona-Warn-App Open Source Team

**Comment by ndegendogo** [comment]
Thanks @heinezen
