### ISSUE TITLE
How to use the error report? (cwa since 2.2)

### ISSUE THREAD

**Issue by ndegendogo** [corona-warn-app/cwa-app-ios#3088]
## Avoid duplicates
* [ ] Question is not already answered in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Question is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Question has not already been asked in another issue

## Your Question

* Source File:
* Line(s):
* Question:

Since version 2.2, cwa provides a feature to upload an error report.
However, I am not sure if I fully understand how to use it.

On the main screen (Startseite), I scroll down and press 'App-Informationen', then 'Fehlerberichte'.
I scroll down again and read "Datenschutz und Datensicherheit":
`Auf den Fehlerbericht haben zunächst nur Sie Zugriff. Sie können im Anschluss entscheiden, ob Sie den Fehlerbericht an den technischen Support senden, ob Sie den Fehlerbericht zunächst auf Ihrem Smartphone speichern oder die Aufzeichnung stoppen und löschen wollen. Wenn Sie den Fehlerbericht zunächst lokal speichern, haben Sie die Möglichkeit, sich den Fehlerbericht selbst anzuschauen, bevor Sie diesen an den Support übermitteln.`

Question:
After I start the reporting function, I have the buttons "Fehlerbericht senden", "Teilen und fortsetzen", "Stoppen und löschen". How do I save the report locally, and how do I read it before I submit it to the tech support?

**Comment by ndegendogo** [comment]
I think I found out meanwhile some of the answers: With "Teilen und fortsetzen" I can send it per email to myself. Nice! 

Still open question: can I send this error report later in such a case? How?

**Comment by Ein-Tim** [comment]
@ndegendogo 

You cannot view the exact error report before sending it, see https://github.com/corona-warn-app/cwa-documentation/issues/614.

Does this answer your question?

**Comment by ndegendogo** [comment]
@Ein-Tim thanks - I guess my question is answered.
Still the fact that I cannot review my report before I send it is **very** disappointing. Actually, it is common practice for such a function to give me the opportunity to review before I decide to send it. I don't like to be forced to trust blindly ...

Is there already a wishlist ticket on that? (so I can upvote it)

**Comment by Ein-Tim** [comment]
@ndegendogo 

There is no wishlist issue reg. this, but since 
https://github.com/corona-warn-app/cwa-documentation/issues/614 is handled as a bug, I guess a wishlist item is not necessary.

**Comment by ndegendogo** [comment]
@Ein-Tim Thanks again.
Closing this ticket, as the question was answered.
