### ISSUE TITLE
Make Date and Time of the Test Result bigger.

### ISSUE THREAD

**Issue by moritzdorn** [corona-warn-app/cwa-app-ios#3089]
## Current Implementation

In the newest version (2.4.2 (0)) on iOS of the CWA the letters of Date and Time are so small. Every time my Test is controlled the Employees need to search for a long time for Date and Time, because here in Berlin it isn't allowed to have a Test who is older then 24 hours. 

![cwa negativ test result](https://user-images.githubusercontent.com/67069171/124351170-11fc0200-dbf9-11eb-8a6e-feb142e44e6f.png)

## Suggested Enhancement

Make the letters bigger, like in the versions before. 

## Expected Benefits

It make it faster and easier to see if the Test is ok and corresponds with the state regulation and if I'm allowed to enter the gym, library, store or restaurant. 

----
Internal Tracking-ID: [EXPOSUREAPP-8276](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8276)

**Comment by heinezen** [comment]
@moritzdorn 

Thanks for spotting the problem! I've informed the dev team. They'll see what they can do.

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@moritzdorn ￼

Did you close this by accident? Or do you consider this as fixed?

**Comment by moritzdorn** [comment]
> @moritzdorn ￼
> 
> Did you close this by accident? Or do you consider this as fixed?

I closed it because its fixed
