### ISSUE TITLE
No valid certificate: VC_JSON_SCHEMA_INVALID

### ISSUE THREAD

**Issue by jonroca91** [corona-warn-app/cwa-app-ios#3095]
![image0](https://user-images.githubusercontent.com/86960124/124462211-c335a000-dd91-11eb-9e39-091c335834c1.png)
## Technical details

- Device name: iPhone 12
- iOS version: 14.6
- App version: 2.4.2 

## Describe the bug

After a Antige-Rapidtest was performed, which also is been confirmed as a EU digital Covid Certificate Member, my negative test certificate can not be certificed but the QR-Code is been identified as an vaccination code? 
But I am getting the error: VC_JSON_SCHEMA_INVALID
Not sure if it is now a bug or problem of the test center.

QR-Code also doesnt work on the CovPass-App

**Comment by Ein-Tim** [comment]
@jonroca91 

You cannot scan a QR-Code from a test certificate in the app currently. 

You can only request one in the app, if you've received your test result through the app.

**Comment by thomasaugsten** [comment]
@jonroca91  can you please provide the qr code via email and the rapid test provider
thomas.augsten@sap.com

**Comment by Ein-Tim** [comment]
@thomasaugsten 

Am I wrong or isn't it possible to scan a test certificate in the app at the moment?

**Comment by heinezen** [comment]
@jonroca91 Is your QR code from another country? Might be the a similar problem as https://github.com/corona-warn-app/cwa-app-ios/issues/3057 then

----
Corona-Warn-App Open Source Team

**Comment by jonroca91** [comment]
@thomasaugsten it would be strange to get a QR code from another country when being testen in germany (Hessen).
The company who did the test was by Safemeditec GmbH

**Comment by thomasaugsten** [comment]
Yes this test is not a valid CWA test qr code. testverify.io stated this but this is not correct. We try to contact testverify.io to remove this false information

**Comment by jonroca91** [comment]
@thomasaugsten okay, good to know and thank you very much!

**Comment by jonroca91** [comment]
@thomasaugsten does it mean the website https://map.schnelltestportal.de/  in which i found that test center is not correct either?

**Comment by thomasaugsten** [comment]
We will contact the provider and either correct the qr code or fix the map.

**Comment by Ein-Tim** [comment]
Can this issue be closed @thomasaugsten?
