### ISSUE TITLE
Align height of the pictures

### ISSUE THREAD

**Issue by jucktnich** [corona-warn-app/cwa-app-ios#3138]
## Avoid duplicates
* [x] This enhancement request has not already been raised before
* [?] Enhancement request is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)
* [x] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation

The pictures are not aligned on the same height
<table>
<th>

![image](https://user-images.githubusercontent.com/73582096/125322339-f18d1f80-e33d-11eb-80b7-dfac7ebb71fe.png)
</th>
<th>

![image](https://user-images.githubusercontent.com/73582096/125322353-f8b42d80-e33d-11eb-85b1-3871b170d45e.png)
</th>
</table>

## Suggested Enhancement

Align them on the same height.
## Expected Benefits

----
Internal Tracking-ID: [EXPOSUREAPP-8478)](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8478)

**Comment by Ein-Tim** [comment]
Android (?) PR: https://github.com/corona-warn-app/cwa-app-android/pull/3740

**Comment by ndegendogo** [comment]
**Analysis:** On both screens, the image and the two text elements are laid out in a vertical stack view, with an additional padding added to the top to prevent the image from slipping under the button or the navigation bar.
**But:** the Certificates screen is a table view controller on top level, whereas in the Check-Ins screen the table view controller is embedded in a TopBottomViewController. This results in a **different height** of the table view for the both screens.
Furthermore, the second text element is of variable length (especially in its localized variants), and has multiple lines. This results in a **different height** of the whole block.
Finally, the stack view is vertically **centered** on the table view. All this results in a crooked layout.

The layout should be top-aligned instead.

**Comment by dsarkar** [comment]
@ndegendogo Thanks. Your comment was mirrored into the internal ticket.

**Comment by ndegendogo** [comment]
Analysing and documenting the layout as of current version for three screen sizes (iPhone 8, iPhone 13 mini, iPhone 13 Pro Max), all with simulator for iOS 15.0.

The EmptyStateView is used in the following table view controllers as background view for empty table:
* DiaryDayViewController (contact diary single day view, both for People selection and for Places selection)
* HealthCertificateOverviewViewController (tab Certificates, top level)
* CheckinsOverviewViewController (tab Check In, top level)
* TraceLocationsOverviewViewController (tab Status (Home) / plan event) 
* OnBehalfTraceLocationSelectionViewController (tab Status (Home) / plan event / menu Warn For Others)

Results see in below comments and videos

**Comment by ndegendogo** [comment]
1) **DiaryDayViewController:**
* the People selection layout is well aligned with the Places selection layout.
* this layout differs significantly from the other mentioned layouts. 
 
***I see no need for alignment here.***

**iPhone 8:**

https://user-images.githubusercontent.com/6118267/136658211-5b196ca3-4201-410c-94df-8ffc072e52e1.mp4

**iPhone 13 mini:**

https://user-images.githubusercontent.com/6118267/136658234-f74ed634-0cd8-4ed2-a9f7-97f851408355.mp4

**iPhone 13 Pro Max:**

https://user-images.githubusercontent.com/6118267/136658264-845c34f1-de65-4c25-bfb3-e080df9d40de.mp4

**Comment by ndegendogo** [comment]
**2) CheckinsOverviewViewController, TraceLocationsOverviewViewController and HealthCertificateOverviewViewController:**
* I can switch directly between those three with the tab buttons.
* their layout is structured very similar.

***These three should be aligned better.***

**Comment by ndegendogo** [comment]
**3) OnBehalfTraceLocationSelectionViewController:**
This screen is presented modally. The tab bar is not available. 

***No need for alignment with the other screens.***

**Comment by Ein-Tim** [comment]
Same here @jucktnich, was this fixed with version 2.13?

**Comment by jucktnich** [comment]
Closing as fixed
