### ISSUE TITLE
Whitespace padding for keyboard does not disappear

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#3149]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone XR
- iOS version: iOS 14.6
- App version: 2.5.1 - version 2.4 was not affected

## Describe the bug

https://user-images.githubusercontent.com/67682506/125450131-3c618ebf-72bd-4514-96e2-f3fbe5b2dc2b.mov

## Steps to reproduce the issue

1. Open the Corona-Warn-App
2. Scroll down to "Planning an event?"
3. Click on "Create QR Code"
4. Click on "Create QR Code" on the top
5. Click on "Cultural Event"
6. Click in the "Description" field & enter something there
7. Click in the "Place" filed & enter something there
8. Click on "Start"
9. See that there is a large white space where the keyboard was before

## Expected behaviour

No free space

## Additional information

1. This only happens on the first time - so if you have clicked on "Start" once and afterwards navigate back into the "Description" or "Place" field and then click on "Start" again, everything works.
2. I remember a PR for this, but I can't find it anymore...

----
Internal Tracking-ID: [EXPOSUREAPP-8388](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8388)

**Comment by heinezen** [comment]
@Ein-Tim 

Thanks for finding this one. I've informed the dev team about it.

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
Same somehow happens here (personalized negative RAT result):
<img src="https://user-images.githubusercontent.com/67682506/127051596-11f1d570-052c-4ead-98d9-bdd618e55afe.jpeg" width="300">

**Comment by dsarkar** [comment]
PR: https://github.com/corona-warn-app/cwa-app-ios/pull/3152

**Comment by Ein-Tim** [comment]
@dsarkar 

Sure about that? This was a negative test result and the case I reported in the OP has still not been fixed.

**Comment by dsarkar** [comment]
@Ein-Tim According to the internal ticket this issue should have been fixed. We are now shortly before the roll out of the next release 2.6, so I am afraid, at this stage it will be re-testing with R 2.6.

**Comment by Ein-Tim** [comment]
This has been fixed in version 2.6. 

Closing as fixed.
