### ISSUE TITLE
Suggestions on Rapid Test Profile (`textContentType` fields) don't work 

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#3159]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone XR
- iOS version: 14.6
- App version: 2.5.1 - version 2.4 was not affected

## Describe the bug

The suggestions, which iOS makes during the creation of a Rapid Test Profile (because of the `textContentType` attribute) don't work anymore in version 2.5. This is a regression from version 2.4.

Here's a comparison between version 2.4 (on the left) and version 2.5 (on the right). 

| Version 2.4 | Version 2.5 |
|---|---|
| <img src="https://user-images.githubusercontent.com/67682506/125691827-d9ec740b-d86b-47a8-a2c2-d2b51018fd39.mov" width="300"> | <img src="https://user-images.githubusercontent.com/67682506/125691963-ce4d9182-f01b-447d-a3c4-54c594600272.mov" width="300"> |

## Steps to reproduce the issue

**If you don't see any suggestions, make sure that you have entered a contact which could be used. To check whether this is the case, go to the iOS settings, scroll down to "Contacts" and then click on "My Info".**

1. Open the Corona-Warn-App
2. Scroll down to the "Register your Test" box
3. Click on "Next Steps"
4. Click on "Rapid Test Profile"
5. Click into the "First Name" field
6. Click on the suggestion which is made above the keyboard (see the videos above)
7. See that nothing happens

## Expected behaviour

The suggestions should be used and the text fields should be filled with them. If you don't want that there are suggestions, remove  the `textContentType` attribute from these fields.

## Possible Fix

I'm quite sure that this is related to the fix of https://github.com/corona-warn-app/cwa-documentation/issues/605, which was done by @freshking in #3018.

## Additional context

The `textContentType` attribute was added to the fields in version 2.3 by the community contributor @toto through #2702.

----
Internal Tracking-ID: [EXPOSUREAPP-8484](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8484)

**Comment by freshking** [comment]
@Ein-Tim Please check out PR #3285. This will allow selection of toolbar suggestions.

**Comment by Ein-Tim** [comment]
I can confirm that this has been fixed in version 2.7.

Closing as fixed.

**Comment by dsarkar** [comment]
@Ein-Tim Thanks for reporting this issue and confirming the fix. Forwarded to the internal ticket.
