### ISSUE TITLE
Name of a Check-in location not shown properly

### ISSUE THREAD

**Issue by Jakre73** [corona-warn-app/cwa-app-ios#3161]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 12 Pro Max
- iOS version: 15.0 (19A5297e)
- App version: 2.5.1 (1)

## Describe the bug

When scanning a QR code for check-in the app does not show the name of the location right. It looks like the upper and lower part of the text gets cut off and only the middle part of the text is shown (experienced in Dark Mode). After scrolling through the location history (down and up again) the text refreshes and is shown right.

## Steps to reproduce the issue

1. Activate the dark mode on the iPhone
2. Scan a CWA location QR code (no matter if its via the CWA pp or with the camera app)
3. Hit the check-in button
4. See the error at the top of the Check-ins list

## Expected behaviour

The name of the location should be readable after the check-in.

## Additional context
See screenshot here: https://ibb.co/1zJcZLx

**Comment by dsarkar** [comment]
@Jakre73 Thanks for your report. Internal Tracking ID: [EXPOSUREAPP-](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-)

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
I cannot reproduce on iPhone 6s / iOS 14.4 / CWA 2.5.1

**Comment by Ein-Tim** [comment]
I will try to reproduce with iOS 14.6 vs. iOS 15.0

**Comment by dsarkar** [comment]
@Jakre73 This issue can be observed only in dark mode, not white mode?

**Comment by Ein-Tim** [comment]
Not reproducible:

iPhone XR - iOS 14.6 - CWA 2.5.1 - Darkmode active
iPhone 6s - iOS 15.0 (19A5281j) - CWA 2.5.1 - Darkmode active

I assume you're on the Developer Beta, I'm on the Public Beta. Thus you're on iOS 15 Developer Beta 3 and I'm on iOS 15 Pubic Beta 2. So there is a chance that this issue was introduced with iOS 15 Beta 3. I will check again when I got the update.

**Comment by dsarkar** [comment]
@Jakre73 @Ein-Tim Alright, thanks. So far it looks more like an iOS issue.

**Comment by Jakre73** [comment]
Hi @Ein-Tim  & @dsarkar ,
yes, it is only reproducible in dark mode, white mode works fine. And yes it is Dev Beta 3 (introduced yesterday I think). 

Just tried it with an iPhone XR & iPhone 11 on iOS 15.0 public Beta 2 and on the same iPhones with iOS 14.6 and there the bug is also not reproducable. So it is only related to the newest developer build of iOS 15.

**Comment by Jakre73** [comment]
I'll submit a feedback to apple regarding the bug (y)

**Comment by Ein-Tim** [comment]
@dsarkar Do we still want to track this here even if it's a iOS 15 Beta 3 only issue is? I assume it would make more sense to close it for now and come back to it once we're close to the final release of iOS 15, to check whether this was fixed.

**Comment by dsarkar** [comment]
@Ein-Tim I leave it to @Jakre73 to close (or not) this issue. No problem to keep it open and track this issue. I added the apple label, indicating that this is not a CWA issue but an Apple/iOS related issue.

**Comment by Jakre73** [comment]
I'd suggest that I'll close the request and I'll re-open it (or maybe someone else will notice the bug again) if we're coming closer to the final release (shouldn't take that long).

**Comment by dsarkar** [comment]
@Jakre73 Thanks for contributing here.

**Comment by Jakre73** [comment]
Hi all, the issue is again occurring in the latest dev beta of iOS 15.4 (19E5209h) inc combination with CWA v2.17.1. I've tried it with an iPhone 12 Pro Max and an iPhone XR. It occurs in dark and bright mode. It only happens when first launching the app, after I've once checked in it does not occur until I've once completely closed the app and restarted the app. I've re-opened the Apple feedback report under FB9332820.
![IMG_2708](https://user-images.githubusercontent.com/36055573/152955826-d6712b1a-a411-4ef7-bd77-64968833bce9.jpeg)
![IMG_2707](https://user-images.githubusercontent.com/36055573/152955843-6ab3eac5-15af-443d-bde6-a78ce5f11edf.jpeg)

**Comment by Ein-Tim** [comment]
@Jakre73 Thanks for informing us about this bug in the beta version. I can't reproduce it on my iPhone 6s on the iOS 15.4 Beta. Can you continue to monitor this and let us know should the bug still exist when the version is closer to release?

**Comment by Jakre73** [comment]
Another issue that I've experienced but also was just able to reproduce in the beta (same device, iOS version, and app version like in the comment before) was that the navigation icons at the bottom of the app are getting transparent if you're doing the following:

1. Go to the "Journal"
2. Select a specific day
3. Navigate to the locations page for that day
4. Then click on the "Check-In" navigation icon
5. Then click again on the "Journal" navigation icon

It will then look like this:
![IMG_2712](https://user-images.githubusercontent.com/36055573/153057309-bd1e967b-f8f0-4ecd-9320-a060c8846c8d.jpeg)

The navigation icons will go back into their normal look as soon as you press on one of them, close and restart the app or navigate into any submenu.

**Comment by Jakre73** [comment]
Short update: iOS 15.4 dev beta 2 (19E5219e) is just out now and both issues are still occurring in that beta reproducible on an iPhone 12 Pro Max and an iPhone XR.

**Comment by Jakre73** [comment]
Short update: iOS 15.4 dev beta 3 (19E5225g) is just out now and both issues are still occurring in that beta reproducible on an iPhone 12 Pro Max and an iPhone XR.

**Comment by dsarkar** [comment]
@Jakre73 Thanks for the feedback.

**Comment by Jakre73** [comment]
Short update:  iOS 15.4 dev beta 4 (19E5235a) is just out now and both issues are still occurring in that beta reproducible on an iPhone 12 Pro Max and an iPhone XR.

**Comment by Ein-Tim** [comment]
@Jakre73 Please report the issue with the transparent tab bar on the journal tab in a separate issue, as I can report it on the production iOS version 15.3.1, not only on the beta. 

Regarding the other issues with the check in: I still can't reproduce this on my iPhone 6s running the latests public beta.

**Comment by Ein-Tim** [comment]
Update no need to open a new issue just comment on: https://github.com/corona-warn-app/cwa-app-ios/issues/3728

**Comment by Ein-Tim** [comment]
@Jakre73 Are you seeing this on iOS 15.4.1 released to the public? I don't.
