### ISSUE TITLE
Time of vaccination certificate until turns blue - different with IOS and Android

### ISSUE THREAD

**Issue by rupprechtt** [corona-warn-app/cwa-app-ios#3174]
Me and my friend got vaccinated the same day. My android phone turned blue one day earlier than his iPhone.
Data on digitial certificates (print outs) are correct.

**Comment by rupprechtt** [comment]
With the iPhone it took 17 days (including day of vaccination and the day the certificate turned blue) - with android one day less.

**Comment by Ein-Tim** [comment]
@rupprechtt 

Please let us know if both, your friend and you, use the latests app version (2.5.1).

**Comment by rupprechtt** [comment]
The error occured with version 2.4.2.

**Comment by Ein-Tim** [comment]
@rupprechtt There were some issues with the calculation when the vaccination certificate is valid (under Android there was version [2.4.3](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.4.3), which further improved this).
I would therefor suggest to retest on version 2.5.

**Comment by rupprechtt** [comment]
@Ein-Tim The erroneous caculation is present in this iOS app only. (At least according to official data)

**Comment by Ein-Tim** [comment]
@rupprechtt 

But please cross check with version 2.5 there were some issues with the calculation in version 2.3 & 2.4 but AFAIK everything has been fixed in version 2.5.

**Comment by dsarkar** [comment]
@rupprechtt Thanks for your report. 

Full immunity should be shown **after** 14 days. The day of vaccination is not counted, since, for example, a person could have been vaccinated at 23:59. 

As @Ein-Tim already asked, please let us know the following:

- Corona-Warn-App iOS version number
- date of vaccination
- date when Corona-Warn-App iOS showed full immunity
- date when Corona-Warn-App Android showed full immunity

**Comment by dsarkar** [comment]
|count||day after vaccination|
|--|--|--|
|1|Day of vaccination||
|2|||
|3||1|
|4||2|
|5||3|
|6||4|
|7||5|
|8||6|
|9||7|
|10||8|
|11||9|
|12||10|
|13||11|
|14||12|
|15||13|
|16||14|
|17|CWA shows immunity|15|

**Comment by rupprechtt** [comment]
@dsarkar  

iOS Version 2.4.2
Day of vaccination 30.06.21 (Wednesday)
iOS CWA showed full immunity today (16.07.21) (Friday)
Android CWA showed full immunity yesterday (15.07.21) (Thursday)

I double checked this, since we both scanned the certificates on the day of vaccination and the andoird app said "14 days until full immunity", whereas the iOS app said "15 days ..." 

Following your table, full immunity is shown after 15 days. (The day after vaccination is still a day, independet weather its day 0 or 1). However, as you said, full immunity should be shown after 14 days. This does mean, vaccination on wednesday should lead to full immunity on thursday two weeks later, not on friday)

Your table shows the logics of the iOS app.

To clarify: I define the day of vaccination as day 0. Then 14 complete days should pass. Then, on the next day (day 15) the CWA should certificate full immunity. Thereby it is ensured, that 14 complete days are between vaccination and CWA showing immunity.
However, this is the behavior of the Andoird app only.

**Comment by dsarkar** [comment]
|Count||Day (multiples of 24 h) after vaccination|Date|
|--|--|--|--|
|1|Day of vaccination||30.6.|
|2|||1.7.|
|3||1|2.7.|
|4||2|3.7.|
|5||3|4.7.|
|6||4|5.7.|
|7||5|6.7.|
|8||6|7.7.|
|9||7|8.7.|
|10||8|9.7.|
|11||9|10.7.|
|12||10|11.7.|
|13||11|12.7.|
|14||12|13.7.|
|15||13|14.7.|
|16|Android CWA 2.??? showed full immunity |14|15.7.|
|17|iOS  CWA  2.4.2 showed full immunity |15|16.7.|

@rupprechtt Actually, you are right about the counting (I think), as you say, an easy way to express it: There are 14 full days between day of vaccination and day when CWA should show immunity.

Which Android CWA version is your friend using? Do you have screenshots of the yesterday and today of your iPhone and your vaccination certificate with the date of vaccination. Please, black out any personal data and the QR code, should you post it here.

**Comment by rupprechtt** [comment]
@dsarkar That's right.

Android CWA version is 2.5.1 today. However, it was version 2.4.2 or 2.4.3 when I scanned the qr code (30.6.21). The countdown of both apps, andoird and ios, were consitent over time (Every day one day less, iOS always one additional day). At least for the Android CWA, the version update had no effect on the time until full immunity.

Unfortunatley I dont have any screenshots with time stamp. And I made no screenshots before the certificate turned blue.

**Comment by Ein-Tim** [comment]
I think the thing was that Android showed "1 Tag bis zum Vollständigen Impfschutz" and then "Voller Impfschutz morgen" while iOS only showed "1 Tag bis zum Vollständigen Impfschutz" and the the full vaccination protection.

I urge you, again, to re-test with CWA 2.5.1 on both, iOS & Android.

**Comment by rupprechtt** [comment]
@Ein-Tim 

As said.
Second dose on the same day (Wednesday)
Andoird: full immunity (Thrusday 2 weeks later)
iOS: full immunity (Friday 2 weeks later)

I reported just today, to be sure that the certificates are issued on diffrent days and not only (for whatever reason) diffrent strings in the GUI are used.

Since both certificates should have been issued yesterday, updating to CWA 2.5.1. should not make any diffrence for me. The iOS certificate that was issued today (one day too late) will stay blue.

**Comment by Ein-Tim** [comment]
@rupprechtt 

You could test if iOS & Android behave the same way now by changing the system time.  

Alternatively, I'd like to ask @dsarkar to talk to the devs who can cross check whether iOS & Android behave the same now.

**Comment by dsarkar** [comment]
@rupprechtt @Ein-Tim I tested. It seems correct. Stand by for screenshots.

**Comment by rupprechtt** [comment]
@Ein-Tim 
Unfortunatley the iPhone user is on vaccation since today, thus testing is hardley possible. 
Nevertheless, I don't think that changing the system time affects the certificate appearance, does it? What happens if I change the system date to last year after my vaccination?

**Comment by Ein-Tim** [comment]
@rupprechtt 

You can change whats shown (the data in the QR-Code is not affected) by changing the system time, more infos: https://github.com/corona-warn-app/cwa-documentation/issues/642

@dsarkar Thank you!

**Comment by rupprechtt** [comment]
@Ein-Tim All right. I try catching him ;)

**Comment by Ein-Tim** [comment]
@rupprechtt Thanks for your efforts, but since @dsarkar said he can confirm that everything works now, so I think you can let your friend enjoy his vacation (; 

Have a nice Friday!

**Comment by dsarkar** [comment]
@rupprechtt @Ein-Tim See the right column of the table https://github.com/corona-warn-app/cwa-app-ios/issues/3174#issuecomment-881498434

29.5. Date of vaccination 
... 
12.06. iOS CWA 2.5.1 shows: vaccination protection is complete tomorrow. See right screenshot.
13.06. iOS CWA 2.5.1 shows: no specific message! See left screenshot.

So, at least with 2.5.1 the behaviour is correct!

![image](https://user-images.githubusercontent.com/1409741/125974239-05b300d6-266c-48f3-99fb-92fa7042c28c.png)

**Comment by rupprechtt** [comment]
@dsarkar That's what its all about! ;) (y)

**Comment by dsarkar** [comment]
@rupprechtt Thanks for reporting and contributing here! Best wishes, DS 

---
Corona-Warn-App Open Source Team
