### ISSUE TITLE
Build on branch release/2.5.x fails (community build) - HealthCertificateToolkit package is missing

### ISSUE THREAD

**Issue by ndegendogo** [corona-warn-app/cwa-app-ios#3185]
## Avoid duplicates
* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue

## Technical details

- Device name: XCode Simulator, ENACommunity build
- iOS version: Simulator for iPhone 8 plus / iOS 14.4
- App version: 2.5.1

## Describe the bug

The ENACommunity build at release 2.5 fails.
The 'HealthCertificateToolkit' package is missing.

## Steps to reproduce the issue

* Checkout cwa source for iOS at branch release/2.5.x / tag v2.5.1 / commit 8c14cecc
* Configure XCode for ENACommunity build / iPhone 8 plus (14.4)
* Clean build folder and package dependencies
* Build

The build fails. I get the error message "Missing package product 'HealthCertificateToolkit'"

## Expected behaviour

Build successfull

## Additional context

A similar error was reported with version 2.4, see #2862 and especially [this comment](https://github.com/corona-warn-app/cwa-app-ios/issues/2862#issuecomment-856460565). 
The issue had been fixed on a branch fix/community-build-june-edition .

----
Internal Tracking-ID: [EXPOSUREAPP-8480](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8480)

**Comment by Ein-Tim** [comment]
I am **not** able to reproduce this, I can build as described above without any problems. The only difference is that I have a iOS 14.5 simulator. Build folder was cleaned before the build.

**Comment by ndegendogo** [comment]
it seems that the branch fix/community-build-june-edition was never merged (and maybe for reasons, so the fix possibly conflict with some other changes ....)

@Ein-Tim do you build a **clean** release/2.5.x or did you merge it with the abovementioned branch?
Did you ever checkout that branch, or was #2862 already fixed for you with the deletion of the json file?

**Comment by Ein-Tim** [comment]
@ndegendogo I did build a clean `release/2.5.x` branch. I did not merge anything. I checked out the branch back when we had the issue before (#2862). I could remove the repo and clone it again, but tbh, I'm happy that it works for me 😅

**Comment by ndegendogo** [comment]
@Ein-Tim Please do not risk to "kill" your working environment!! 😱😱

**Comment by ndegendogo** [comment]
@heinezen @dsarkar any news on this?
Or any hints or workarounds for me?

**Comment by ndegendogo** [comment]
Yesterday I tried with the newest branch release/2.8.x
it is still broken

Maybe it is related to the integration of the HealthCertificateToolkit,
especially with the discussion at 
https://github.com/corona-warn-app/cwa-app-ios/pull/2880

*just guessing*

**Comment by marcussc** [comment]
@ndegendogo I just freshly checkout out the codebase with the 2.8.x branch. I see no build error. Also we have a our CI-Pipeline setup to check the community target, this seems to work fine as well. 
Could you try a fresh `git clone` and see if the Issue still persist?

**Comment by ndegendogo** [comment]
@marcussc Thanks for reaching out.
I tried this yesterday also with a fresh clone, and on a new machine where I had never built cwa before; but I will try this evening again.
I forgot maybe to mention that I was using the XCode GUI to build.
Do you build with the GUI, or do you perform a command-line build?

**Comment by ndegendogo** [comment]
@marcussc also yesterday I had played a bit with the XCode project file. I think I found a change that at least the package dependencies were resolved and the compiler seemed to have started (not sure if it finished successfully), but I got then another error message, related to lint and the vendor folder ...
I am considering to open a PR for this change, although I don't know much about your workflows; so just in the hope that it does not break anything for you ....

**Comment by ndegendogo** [comment]
ok, so more details now.
I am building from the Xcode IDE (Xcode version 12.4).
Build was first broken with cwa v2.4 (release/2.4.x branch), see #2862, and this was fixed on branch fix/community-build-june-edition.
Unfortunately, my build is still broken on all other branches since then (release/2.5.x, release/2.6.x, release/2.7.x, and now release/2.8.x).
The build does not even resolve the packages, error message is "Missing package product HealthCertificateToolkit".

I tried to add the HealthCertificateToolkit to the Xcode project file, and **this improved it a lot.**
Now it resolves the packages successfully and starts the build.

I am going to create a PR with this improvement.

Unfortunately, I still cannot build. I get now the error message "size: can't open file: 27813542 (No such file or directory)", see screenshot. 

<img width="1137" alt="Screenshot 2021-08-04 at 22 11 27" src="https://user-images.githubusercontent.com/6118267/128250662-051849ac-5473-43df-a44e-ccfc7a4fa305.png">

**Comment by marcussc** [comment]
@ndegendogo One of our devs might had the Idea what is going wrong: https://github.com/corona-warn-app/cwa-app-ios/pull/3318#pullrequestreview-723001982 could you check this on your side? :)

**Comment by jucktnich** [comment]
I just wanted to add, that I'm not able to build the app too. (macOS 11.5.1 / Xcode 12.? / M1)

**Comment by marcussc** [comment]
We just update the Readme to make it more clear which project file to use: https://github.com/corona-warn-app/cwa-app-ios/pull/3323

@jucktnich could you please go into more detail why you are not able to build the app?

**Comment by jucktnich** [comment]
I don't know. It's a week since then and I just tryed to build the app, cause I had some little ideas I wanted to try, but the error message from ndegendogo looks familiar to me. I don't have Access to the Mac now, so I can't try it.

**Comment by ndegendogo** [comment]
@marcussc @ArturFriesen 

YES! The xcworkspace was the right question / hint, now it resolves all packages nicely out of the box 🎉🎉🎉🎉🎉

> We just update the Readme to make it more clear which project file to use

**Thanks also for this!**

*The error message with the missing file with the mysterious name persists - but now I have the strong suspicion that its because my git client is too old ... I have only 1.8.4 and especially no support for lfs* 😱🙈

**Comment by marcussc** [comment]
@ndegendogo nice to hear! 
Yeah the `size: can't open file: 27813542 (No such file or directory)` seems to be an Issue due to git-lfs. Our internal and easiest fixed seemed to be to just delete the repo locally and clone it again.

**Comment by ndegendogo** [comment]
@marcussc my current git is too old, it does not support lfs
I guess I have to upgrade my git ...

> Our internal and easiest fixed seemed to be to just delete the repo locally and clone it again.

Thanks for the hint... so this might be needed in case the "new" git istallation is reluctant to take over ...

**Comment by ndegendogo** [comment]
I am back 🎉🎉🎉
Everything is working again 🎉🎉🎉
Thanks for all your support 🎉🎉🎉

Summarizing the two key points:
1) *cannot resolve packages, HealthCertificateToolkit missing*
**=> use the ENA.xcworkspace** (not the project file)
2) *vendor/swiftlint ... oid: command not found ... size: can't open file: 27813542 (No such file or directory)*
**=> install git-lfs**

closing the ticket
