### ISSUE TITLE
Certificate sorting sequence (Test prior to Vaccination)

### ISSUE THREAD

**Issue by bondskin** [corona-warn-app/cwa-app-ios#3203]
## Avoid duplicates
* [ X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue

## Technical details

- Device name: iPhone
- iOS version: 14.6
- App version: 2.5.1

## Describe the bug
A newer Test Certificate is shown on the Certificate tab, although a vaccinated certificate has been added before.
Does this sorting make sense?
![IMG_0961](https://user-images.githubusercontent.com/55050117/126193794-65436ba9-a770-4892-9bb8-9932ddb0c17c.jpg)

## Steps to reproduce the issue
n.a

## Expected behaviour

I would expect that a vaccination certificate is always listed at the top, before any test certificate is being listed/shown.

**Comment by rgrenz** [comment]
Hi @bondskin, there is a specific sorting order that determines which certificate is seen as most relevant (see [here](https://github.com/corona-warn-app/cwa-app-ios/blob/536c9c09b2e76544322aa818892f6414263f4275/src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/HealthCertificateArray%2BMostRelevant.swift#L40)). In that way, a recent PCR / Rapid Antigen Test certificate "outweighs" an older vaccination (by definition). So from my perspective I would say this works as designed.

**Comment by bondskin** [comment]
Excellent, that does make sense indeed. I was not sure if the sorting is by random or by relevance. 
Thanks for the explanation

**Comment by dsarkar** [comment]
@bondskin @rgrenz Indeed, this works as designed. It's not random, but there are rules in which order certificates are shown.


---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@bondskin 

Do you consider this as solved? If you want to open an enhancement request regarding this, please do so [here](https://github.com/corona-warn-app/cwa-wishlist/issues/new/choose). 

Otherwise you could close this issue. Thanks!
