### ISSUE TITLE
Spelling / Grammar mistake (?)

### ISSUE THREAD

**Issue by hija** [corona-warn-app/cwa-app-ios#3243]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)  --> Felt wrong to post in the documentation because the grammar / spelling error is not written down there and I don't really think it is related to the documentation. If you feel like I should post there anyways, please just close this issue and I will do so :)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: iPhone SE 2
- iOS version: iOS 14.7
- App version: 2.5.1 (1)

## Describe the bug

When clicking on the information button for the fully vaccinated people the explanation for the statistics appear.  For fully vaccinated people there is written (in German) "Anzahl der an das RKI übermittelten Personen, die die alle notwendigen Impfdosen erhalten haben." 

I think, there is one "die" (German article) too much. "Anzahl der an das RKI übermittelten Personen, die alle notwendigen Impfdosen erhalten haben." is better to understand.

## Steps to reproduce the issue

1. The app has to use the German localization
2. Go to main page
3. Scroll down to statistics area
4. Click on the information icon (i) in the upper right corner of any statistic tile
5. Scroll down until you can read "Vollständig geimpfte Personen"

## Expected behaviour

Text should be "Anzahl der an das RKI übermittelten Personen, die alle notwendigen Impfdosen erhalten haben."

## Possible Fix

Change Localizable Strings:

iOS: https://github.com/corona-warn-app/cwa-app-ios/blob/5dc34e76d49d1430c840a8afcd5b6272b82fc1e5/src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings#L2075

Android: https://github.com/corona-warn-app/cwa-app-android/blob/63df24be9d2bc1bfb324325d79b1c8b0f8606f4d/Corona-Warn-App/src/main/res/values-de/strings.xml#L1637

**Comment by Ein-Tim** [comment]
@hija 

Just for your information: We use the documentation repository not only for issues with the documents there but also for issues which affect the apps on both operating systems, iOS & Android. 
So yes, I'd suggest to post the issue there and close this one here. Alternatively, one of the community managers will transfer it there. 

Thanks and have a nice evening.

**Comment by hija** [comment]
Alright, going to do so :)
Thanks 👍
