### ISSUE TITLE
Don't show the "Your test result cannot be loaded. The response has no content" error to the user

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#3254]
## Avoid duplicates
* [X] This enhancement request has not already been raised before
* [X] Enhancement request is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)
* [X] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation
When the user has registered a test in the app, there are some cases where the app shows this error:

<img src="https://user-images.githubusercontent.com/67682506/118002743-36013c80-b348-11eb-8cae-3f876520cf7b.PNG" width="300">

## Suggested Enhancement
As this error has no information value for the end user at all (since there is only one button "OK", but no more information what to do, etc.), I suggest to log this error but not show it to the user. 

## Expected Benefits
Less confused users, some might think that they will never receive their test result via CWA, although they just have to wait until the test result is available. 

## Additional Information
As this does not happen under Android (= Android users don't see this error), it should be fine to just hide this error under iOS too.

**Comment by heinezen** [comment]
@Ein-Tim Did the error in https://github.com/corona-warn-app/cwa-app-ios/issues/2694 occur again?

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@heinezen 

Yes, yesterday after I registered a PCR-test, see https://github.com/corona-warn-app/cwa-app-ios/issues/2694#issuecomment-887373613.

**Comment by heinezen** [comment]
@Ein-Tim Ah I see. I think it's better to reopen https://github.com/corona-warn-app/cwa-app-ios/issues/2694 and check if we can get a proper solution instead of just suppressing the error message.

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@heinezen I agree with you, let's continue in #2694.
