### ISSUE TITLE
What does the DCC_COMP_202 error mean? 

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#3261]
## Your Question

This question is related to https://github.com/corona-warn-app/cwa-app-ios/issues/3256.

What does the DCC_COMP_202 error mean?

**Comment by ascheibal** [comment]
I faced this DCC_COMP_202 shown in modal dialog, while 'in the same moment' receiving the dcc certificate in the background, so it may be related to more than one pending requests at a time.

**Comment by Ein-Tim** [comment]
@ascheibal 

That is actually possible, see the log I posted in https://github.com/corona-warn-app/cwa-app-ios/issues/3256. There is one background task trying to receive the certificate and then the user (in this case me) also tries to receive it.
