### ISSUE TITLE
Notification Settings Screen becomes unresponsive when scrolling on iPhone SE

### ISSUE THREAD

**Issue by EisvogelSAP** [corona-warn-app/cwa-app-ios#327]
When using the app on the iPhone SE the notification settings screen becomes unresponsive when scrolling.

![IMG_CA6445A1738A-1](https://user-images.githubusercontent.com/64848654/83977656-79665600-a902-11ea-92c6-431894c62f2f.jpeg)

**Comment by Bohne9** [comment]
It's not only on the SE. I'm gonna have look at it.
