### ISSUE TITLE
Check Validity Screen: Top isn’t blurred after clicking on validate for another country

### ISSUE THREAD

**Issue by jucktnich** [corona-warn-app/cwa-app-ios#3274]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: iPhone SE 1
- iOS version: iOS 14.7.1
- App version: 2.6.1

## Describe the bug

The top of the Validate for Country screen isn't blurred after accessing it thru the check for another country button. See video:
![image](https://user-images.githubusercontent.com/73582096/127518475-4561363b-2383-42d3-87b9-fdfe1b6f6676.MOV)

## Steps to reproduce the issue

1. Go to the certificate tab
2. Click on a certificate
3. Click on Check validity
4. Scroll down - everything normal
5. Click on check
6. Click on check for another country
7. Scroll down - background of headline isn't blurred

## Expected behaviour

Blurre background

----
Internal Tracking-ID: [EXPOSUREAPP-9085](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9085) duplicate of
Internal Tracking-ID: [EXPOSUREAPP-8932](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8932)

**Comment by Ein-Tim** [comment]
Fix for this: #3398

**Comment by Ein-Tim** [comment]
Confirm fixed in version 2.9. 👍
