### ISSUE TITLE
Spelling mistakes in Privacy Policy

### ISSUE THREAD

**Issue by EisvogelSAP** [corona-warn-app/cwa-app-ios#328]
The Privacy Policy (German) may still have some spelling mistakes. Proof reading required.

**Comment by haosap** [comment]
Any PR regarding this issue is welcomed. Thanks.

**Comment by ferdinand** [comment]
I did not notice any spelling mistakes but only minor punctuation errors. Please see my pull request #433 for details.

**Comment by mh-** [comment]
Please also integrate the result of https://github.com/corona-warn-app/cwa-documentation/issues/207 when it's available.
