### ISSUE TITLE
Implement a MockENManager for the community build

### ISSUE THREAD

**Issue by ndegendogo** [corona-warn-app/cwa-app-ios#3283]
## Avoid duplicates
* [x] This enhancement request has not already been raised before
* [x] Enhancement request is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)
* [ ] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation

The true Exposure Notification Framework (ENF) provided by Apple needs a special entitlement and is not available for the community build. As a work-around, we community members currently link the MockExposureManager. This is a mock that was originally implemented for user interface tests, but it allows us to execute and test nearly 100% of the functionality of cwa.
However, the code in ENAExposureManager (which serves as a 'bridge' between the cwa classes and the ENF) is **unreachable** with such a build. And this code is meanwhile not just a "very thin adapter"; it contains also logic, and the related execution pathes are also unreachable in a community build. [See e.g. here](https://github.com/corona-warn-app/cwa-app-ios/blob/02961b600f7b2e5d68cef2b9974deaa02203937d/src/xcode/ENA/ENA/Source/Models/Exposure/ExposureManager.swift#L304).

## Suggested Enhancement

Implement a mock for ENManager (on the 'Apple side' of the bridge instead on the 'cwa side'), and use this MockENManager in the community build instead of the true ENManager.
Note: The user interface tests need not change, they can stay with the current MockExposureManager.

## Expected Benefits

Better code coverage for the community build, allowing a more realistic testing and debugging also for community members.

Note: I would volunteer for a PR on this enhancement proposal.

----
Internal Tracking-ID: [EXPOSUREAPP-8990](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8990)

**Comment by ndegendogo** [comment]
Any feedback on this proposal?
Shall I prepare a PR?

**Comment by dsarkar** [comment]
@ndegendogo I will ping a couple of developers. Thanks for the offering a PR.

**Comment by dsarkar** [comment]
@ndegendogo quote dev: 

> "yeah sure, I would love to see something like this coming from the Community."

**Comment by ndegendogo** [comment]
Closing as implemened

**Comment by dsarkar** [comment]
@ndegendogo Thanks again!
