### ISSUE TITLE
Glitch in scrolling the main screen 2.0

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#3289]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone XR
- iOS version: 14.7.1
- App version: 2.6.2

## Describe the bug

When using the scrollbar to scroll the main screen of CWA, there are visible offsets:

https://user-images.githubusercontent.com/67682506/127714549-a82fa613-0985-4ba2-9e19-ba4cb96f0758.mp4

## Steps to reproduce the issue

1. Open the Corona-Warn-App
2. Use the scrollbar on the right to scroll
3. Scroll down slowly
4. See that the view jumps around

## Expected behaviour

No jumps or offsets.

## Additional context

Hello again #991 from @ndegendogo 😉😄

----
Internal Tracking-ID: [EXPOSUREAPP-9084](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9084)

**Comment by jucktnich** [comment]
There are Hangers etc all over the app (iPhone SE 1). I thought, that this is just my old device, but maybe not, as this glitch also appears on a iPhone XR.

**Comment by Ein-Tim** [comment]
This seems to be fixed in version 2.13.2.

I guess the redesigned home screen ("More" box at the bottom was the thing that fixed this).

Closing as fixed.
