### ISSUE TITLE
Local statistics card(s) disappears

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#3290]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 11 Pro
- iOS version: 14.7.1
- App version: 2.6.2

## Describe the bug

The local statistic card(s) sometimes disappears. 

<img src="https://user-images.githubusercontent.com/67682506/127768125-446d6e0a-3590-495d-96ef-9b0990036da9.png" width="300">

## Steps to reproduce the issue

Not really clear in which circumstances this problem happens.

## Expected behaviour

The local statistics card(s) should not disappear without the user having deleted them.

## Additional context

This bug report is based on feedback I received from a Twitter user: https://twitter.com/tejaytwit/status/1421722380511109123?s=20

---
Internal Tracking ID: [EXPOSUREAPP-8753](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8753)
Internal Tracking ID: [EXPOSUREAPP-8762](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8762)
PR https://github.com/corona-warn-app/cwa-app-ios/pull/3287

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-8753](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8753)
Internal Tracking ID: [EXPOSUREAPP-8762](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8762)
PR https://github.com/corona-warn-app/cwa-app-ios/pull/3287

**Comment by Ein-Tim** [comment]
@dsarkar 

Has this been fixed in version 2.6.3?

**Comment by heinezen** [comment]
@Ein-Tim It should be fixed.

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@heinezen 

Thank you! 

Closing as fixed.
