### ISSUE TITLE
Contact diary empty and all persons and places deleted

### ISSUE THREAD

**Issue by jajoho** [corona-warn-app/cwa-app-ios#3317]
CWA closed itself. After that all entries from my contact diary and all persons/places are deleted.
I haven’t done anything special. Just opened the app, it seems it crashed and after that I opened it again and everything was empty/deleted. My vaccination certificate is still available and also locals statistics.

CWA 2.6.3
iOS 14.7.1

**Comment by dsarkar** [comment]
@jajoho Thanks for the report. Is this the first and only time this happens? Can you reproduce this issue? 

---
Corona-Warn-App Open Source Team

**Comment by jajoho** [comment]
@dsarkar yes, this happened for the first time. Unfortunately I'm unable to reproduce this. My storage is scarce. That's the only reason I can think of.

**Comment by Ein-Tim** [comment]
@jajoho 

What were you doing when the app crashed?

**Comment by jajoho** [comment]
@Ein-Tim 
Just opening it. It crashes immediately after

**Comment by Ein-Tim** [comment]
Strange, which device are you using @jajoho?

**Comment by jajoho** [comment]
iPhone 11 Pro

**Comment by Ein-Tim** [comment]
@jajoho Okay (one more, hopefully) the last question from my side; How much free space is still available?

**Comment by jajoho** [comment]
@Ein-Tim 
No worries :)
A little bit less than 1 GB

**Comment by Ein-Tim** [comment]
Mh, okay, I could only imagine that CWA tried to clean up the old contact journal entries (AFAIK it always does this at app start) and then the task for this crashed somehow (which then leaded to a crash of the whole application). This could be related to the very few free MBs on the device, but maybe also something completely different...

**Comment by jucktnich** [comment]
May the free Storage was under 500 MB?

**Comment by jajoho** [comment]
@jucktnich 

Yes, it is definitely possible that I had less than 500 MB of free storage at the time.

**Comment by jucktnich** [comment]
Ok, this means, that the app maybe couldn't write something.

**Comment by dsarkar** [comment]
@jajoho If at some point you can reproduce this issue, let us know, please. In such a case an error report would help the developers to analyse this issue.

**Comment by jajoho** [comment]
@dsarkar @jucktnich 

I've tried to reproduce this by reducing my free storage to less than 500 MB, but CWA did not crash and my contact journals entries were not deleted. It seems I'm unable to reproduce. I will open this ticket again if anything changes.

**Comment by jucktnich** [comment]
@jajoho you can, if you want to, go to "Datenschutz" ➜ "Analyse & Verbesserungen" ➜ "Analysedaten" and then search for the date and time and maybe you'll find something there, since such bugs can be also produced by the OS

**Comment by jajoho** [comment]
@jucktnich I've already searched there and couldn't find anything related to a crash of iOS or CWA or anything else

**Comment by Ein-Tim** [comment]
@jajoho The CWA log would be called something with ENA. Is there an entry called ENA...?

**Comment by jajoho** [comment]
@Ein-Tim Unfortunately not :(

**Comment by Ein-Tim** [comment]
FYI, more recent bug report on this: #3680

**Comment by jajoho** [comment]
Not fixed but error message added with #4389
