### ISSUE TITLE
[Statistics Card] Incidences cards different position of the incidences

### ISSUE THREAD

**Issue by jucktnich** [corona-warn-app/cwa-app-ios#3331]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: iPhone SE 1
- iOS version: iOS 14.7.1
- App version: 2.6.3 (0)

## Describe the bug

![image](https://user-images.githubusercontent.com/73582096/128605675-6d997f52-7864-4f00-96f7-c1fae4227f87.MOV)

## Steps to reproduce the issue

Go to the statistics cards an watch the cards

## Expected behaviour

Same height

**Comment by Ein-Tim** [comment]
Could be that this has already been fixed for version 2.7 with: #3325

**Comment by Ein-Tim** [comment]
I don't see this behavior under 2.7, so I assume this has been fixed.

**Comment by jucktnich** [comment]
For me too, closing this as fixed.

**Comment by dsarkar** [comment]
@jucktnich @Ein-Tim Thanks for confirming the fix.
