### ISSUE TITLE
Release on Canadian/American App Store?

### ISSUE THREAD

**Issue by omearaco** [corona-warn-app/cwa-app-ios#3346]
I have a Canadian Apple store account and unfortunately the iOS app can’t be installed on my iPhone. Is it possible to release it on that App Store ? I live permanently in Munich.

**Comment by Ein-Tim** [comment]
Hi @omearaco 

Thank you for your question. I'd suggest you read through the FAQ entry: https://www.coronawarn.app/en/faq/#international which answers the question why the Corona-Warn-App is not available in the App Stores of all countries worldwide. 

In our wishlist repository https://github.com/corona-warn-app/cwa-wishlist you can suggest the release of the CWA in new countries. 

For Canada, there's this issue: https://github.com/corona-warn-app/cwa-wishlist/issues/38
For the USA, there's this issue: https://github.com/corona-warn-app/cwa-wishlist/issues/41

If I've answered your question, I'd like to ask you to close this issue. 

Thanks and have a nice day! Stay safe!

**Comment by omearaco** [comment]
Thanks @Ein-Tim ! Apologies for not seeing that documentation. I’ll bring it up in the other thread. Thanks!
