### ISSUE TITLE
No exposure check for 36 hours

### ISSUE THREAD

**Issue by ndegendogo** [corona-warn-app/cwa-app-ios#3352]
## Avoid duplicates
* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 8
- iOS version: 14.4.1
- App version: cwa 2.6.3

## Describe the bug

Yesterday morning I played a bit with switching WLAN on and off from the "Exposure Check Active" dialog - I tried if I can reproduce #3188 . First I could not reproduce it, but later at 10:17 I suddenly saw the error message when I opened cwa to add entries to my contact diary. See [this comment](https://github.com/corona-warn-app/cwa-app-ios/issues/3188#issuecomment-896198866) and related screenshot.
And then today evening I got the "dead man notification" - and, indeed, my ENF log confirms this; it shows no risk check in the last 36 hours, since my experiments.

The ENF settings indicate contact tracing active and linked to cwa Germany.

## Expected behaviour
Regular and robust risk checks from background as well as during app usage, and from WLAN as well as from mobile connection.

## Additional context

At least we have evidence that the dead man notification is working well ... 🙈

![IMG_1192](https://user-images.githubusercontent.com/6118267/129093774-670eb31b-e0ac-4271-98fe-f5042c010cd5.png)

![IMG_1194](https://user-images.githubusercontent.com/6118267/129093864-c787b517-c0b9-4103-a7eb-5afc5146ecfb.png)

![IMG_1193](https://user-images.githubusercontent.com/6118267/129093906-c7840f5d-54c2-4c03-8dbd-15ef09c26cd6.png)

----
Internal Tracking-ID: [EXPOSUREAPP-9086](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9086)

**Comment by ndegendogo** [comment]
More screenshots: when I open the app now, I get again / still the error message.
The in-app settings show everything is active.

![IMG_1195](https://user-images.githubusercontent.com/6118267/129095212-011f660f-1cb4-46ec-9456-f68cf85e2128.png)

![IMG_1196](https://user-images.githubusercontent.com/6118267/129095248-d358e50e-57ae-43a5-acb9-6064a88ca8de.png)

**Comment by ndegendogo** [comment]
**A few lines from my log file:** 
*has a risk check started but never finished, and this blocks now more risk checks?*

Info 2021-08-11T20:02:52Z
[ENA/RiskProvider.swift:98] [requestRisk(userInitiated:timeoutInterval:)]
RiskProvider: Request risk was called. UserInitiated: false

Info 2021-08-11T20:02:52Z
[ENA/RiskProvider.swift:101] [requestRisk(userInitiated:timeoutInterval:)]
RiskProvider: Risk detection is already running. Don't start new risk detection.

Info 2021-08-11T20:02:52Z
[ENA/RiskProvider.swift:479] [failOnTargetQueue(error:updateState:)]
RiskProvider: Failed with error: riskProviderIsRunning

Info 2021-08-11T20:02:52Z
[ENA/RiskProvider.swift:98] [requestRisk(userInitiated:timeoutInterval:)]
RiskProvider: Request risk was called. UserInitiated: false

Info 2021-08-11T20:02:52Z
[ENA/RiskProvider.swift:101] [requestRisk(userInitiated:timeoutInterval:)]
RiskProvider: Risk detection is already running. Don't start new risk detection.

Info 2021-08-11T20:02:52Z
[ENA/RiskProvider.swift:479] [failOnTargetQueue(error:updateState:)]
RiskProvider: Failed with error: riskProviderIsRunning

**Comment by ndegendogo** [comment]
***it looks as if the HTTP session was crashed and is now blocking everything...?***

Info 2021-08-11T20:02:52Z
[ENA/PPAnalyticsSubmitter.swift:61] [triggerSubmitData(ppacToken:completion:)]
Analytics submission was triggered. Checking now if we can submit...

Warning 2021-08-11T20:02:52Z
[ENA/PPAnalyticsSubmitter.swift:65] [triggerSubmitData(ppacToken:completion:)]
Analytics submission abord due to submission is already in progress

Debug 2021-08-11T20:02:52Z
[ENA/CachedAppConfiguration.swift:223] [shouldFetch()]
timestamp >= 300s? 132255.60344099998 >= 300)

Debug 2021-08-11T20:02:52Z
[ENA/CachedAppConfiguration.swift:189] [appConfiguration(forceFetch:)]
fetching fresh app configuration. forceFetch: false, force: true

Debug 2021-08-11T20:02:52Z
[ENA/CachedAppConfiguration.swift:76] [getAppConfig(with:)]
Return immediately because request allready running.

Debug 2021-08-11T20:02:52Z
[ENA/CachedAppConfiguration.swift:77] [getAppConfig(with:)]
Append promise.

**Comment by ndegendogo** [comment]
I try to press the button but nothing happens 
(*note: in the log file I see that it refused to start the risk check because it thinks the check is already running*)

**Comment by ndegendogo** [comment]
**I exit the app and kick it out of memory (swipe), then I reboot the phone.**
*This seems to do the trick - risk check is now working again*

**Comment by Ein-Tim** [comment]
Okay, let me summarize to make sure I understood everything correctly.

You tried to reproduce #3188 but failed. Afterwards you opened the CWA and saw this error message on the risk card. At this time, did you have an active internet connection? 
After you added the entry to the contact journal you left the app. Did you hard close the app or just press on the home button?
Then you did not open the app anymore until you received the dead man notification today - after 36h without a successful risk check. 
When you opened the app today, did you have an active internet connection? If yes, did the app showed the typical "Downloading" card? Or did it just stick to the message "Exposure check failed"?
Pressing on "Erneut starten" did not have any influence. Have you tried going to a submenu in the app and returning back to the Home Screen (as I did in the video in the OP of #3188). 
Does the ENF log show any new check for this time before the reboot?

---

I interpret the log that way that the data donation submission failed and this blocked everything? Do you agree with me here? Interesting would be if you can reproduce this if you turn off data donation. Then nothing should be submitted anymore. 

---

Lemme know in case I have mixed something up or misunderstood something. Thanks and have a good night!

**Comment by ndegendogo** [comment]
@Ein-Tim thanks for your interest to dig into this ...

> You tried to reproduce #3188 but failed. 

Yes. Let me add that I was on public transport during my experiments. So no WLAN coverage all the time, and possibly bad or instable network coverage.

> Afterwards you opened the CWA and saw this error message on the risk card. 
At this time, did you have an active internet connection?

Yes, I opened cwa after arriving at work. **No WLAN** (I did not yet enter their new password since they changed it). My screenshot confirms this, and shows also a bit of mobile coverage (one bar LTE, usually this is enough for surfing through the internet).

> After you added the entry to the contact journal you left the app. Did you hard close the app or just press on the home button?

Yes. I just pressed the home button. I never hard-close it, except in emergencies (like yesterday evening).

> Then you did not open the app anymore until you received the dead man notification today - after 36h without a successful risk check.

No. I opened it **several times** over the day and added more collegues to the diary as I met them. In the evening I opened it again and checked the statistics. And the following day again several times for the diary. So, definitely, the app was up and running. Only I did not notice that the risk check was outdated. **So I am very thankful for the notification.**

> When you opened the app today, did you have an active internet connection? 

"Today" means before or after the deadman notification?
Opened for diary: no WLAN, but mobile coverage.
Opened for statistics in the evening: WLAN yes; mobile coverage: don't remember, possibly weak.
*My understanding of intended behaviour is: daily risk check, even without WLAN, and additionally checks with a 4-hour period in case of WLAN. And this is the pattern I see for the other days.*

> If yes, did the app showed the typical "Downloading" card? Or did it just stick to the message "Exposure check failed"?

Tbh, I don't remember. I was focussed on the diary resp the statistics numbers, and did not look at the risk. (I didn't expext anything interesting there, luckily our local incidence is still low 😁)

> Pressing on "Erneut starten" did not have any influence. 

Well - not any *visible* influence. In the log file I see very clearly that it indeed reacted to my pressing the button - only it stopped very fast.

> Have you tried going to a submenu in the app and returning back to the Home Screen (as I did in the video in the OP of #3188).

*Any submenu*: yes, I activated logging 😎
*This specific submenu*: I don't remember, so I guess: No.

> Does the ENF log show any new check for this time before the reboot?

No. After reboot I got a check, but before the ENF log shows no check since 36 hours. And cwa log confirms that every attempt for risk check is aborted early because it thinks there is already a risk check running.

**Comment by ndegendogo** [comment]
Before I close this ticket (because for me the risk check works again), I would like two action items:

1) a Jira ticket to make the devs aware that there is still a path that can lead to inconsistent state in the risk provider and this can block the risk check
@dsarkar @heinezen

2) a discussion / assessment if the suggestions how to act in case of dead man notification could/should be extended. In my case the suggestion on the notification was to open the app; and I didn't find any related FAQ entry (but maybe I just didn't search hard enough).
The suggestion could be (a) to open cwa, and (b) in case this does not help, to close and hard-kill it.
@Ein-Tim @dsarkar @heinezen

**Comment by Ein-Tim** [comment]
@ndegendogo 

Thanks for your long and detailed comments, I will try to reproduce this (together with #3188) on my second device as soon as I have time. (:

**Comment by Ein-Tim** [comment]
I tried hard to reproduce this but wasn't able to, sorry 😕

**Comment by ndegendogo** [comment]
@Ein-Tim 

> I tried hard to reproduce this

I don't think this is easy / straightforward to reproduce. Else I would expect more tickets. 🤭

**Comment by ndegendogo** [comment]
I reproduced "something similar" on the simulator.
I am uploading my log file.

Details:
* local build of cwa for community, from branch release/2.6.x
* **execution _on simulator_**
* I had setup a few breakpoints, possibly they distorted the timing of execution
* I captured the logging via "copy&paste" from the Xcode console window

**Comment by ndegendogo** [comment]
[simu_log2.txt](https://github.com/corona-warn-app/cwa-app-ios/files/7012227/simu_log2.txt)

**Comment by heinezen** [comment]
@Ein-Tim @ndegendogo 

Sorry for coming back to this so late. The developers are trying to find the cause and a solution for this problem. I've forwarded the log file. Let's see what they can find out.

----
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
@ndegendogo FYI: Dev team became aware of a bug, exposure checks was heavily tested and successfully verified that it is working (now).

Some changes were introduced, see https://github.com/corona-warn-app/cwa-app-ios/pull/3362

**Comment by heinezen** [comment]
We are still looking into this issue, but there might be multiple problems that influence the surfacing of this bug.

----
Corona-Warn-App Open Source Team

**Comment by thomasaugsten** [comment]
Out investigation at the moment show that this white card is correct.

If you are checked into an event the app the app needs to check if the event was infectious or not.
For this check the app needs to fetch the latest published event ids from the CDN. If this fetch is not possible no exposure check for this event is possible. 
The white card informs the user that the risk check was not successful

**Comment by Ein-Tim** [comment]
@thomasaugsten 

Did you want to comment on #3188?

**Comment by ndegendogo** [comment]
> Because here the issue was that the app doesn't carry out risk checks in the background. 

Exactly. I didn't have any event checkin codes. I played with the ENF activation/ deactivation button while I was in unstable network coverage

**Comment by Ein-Tim** [comment]
Is this still reproducible on your device with version 2.16 and the latest iOS version @ndegendogo?

**Comment by ndegendogo** [comment]
What a coincidence!
Today I come home, open cwa and expect a risk check like every day - and nothing happens! Just a green card, and the last check was in the morning. And, yes, during the day I had no WLAN coverage, but now I definitely have WLAN.
So I waited another hour and tried again ... and now I have the white card with the error message. See screenshot.
And the button has no effect.

Note: I am currently still on
cwa 2.15.1 (2) / iOS 15.1 / iPhone 13 Pro

Next action will be to upgrade cwa to newest and try again.

**Comment by ndegendogo** [comment]
Looks good ...

![CBFC1CAA-33E9-4B90-8CC4-8379B4F85971](https://user-images.githubusercontent.com/6118267/150019096-1003752a-8e53-41b4-9b71-fb9565b30a4a.png)

**Comment by Ein-Tim** [comment]
@ndegendogo Do you still need this issue open?

**Comment by ndegendogo** [comment]
@Ein-Tim thanks for the reminder.
In last time my risk checks are absolutely reliably, and very fast; especially since the optimization (show only the new key files to ENF).

Closing as resolved.
