### ISSUE TITLE
UI: Headline disappears

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#3372]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone XR
- iOS version: 14.7.1
- App version: 2.7.1

## Describe the bug

When swiping back from the "My QR Codes" screen, the headline disappears: 

https://user-images.githubusercontent.com/67682506/129716156-14b20983-b9e7-4c51-ac15-b90754d8e427.mov

## Steps to reproduce the issue

1. Open the Corona-Warn-App
2. Scroll down to the "Planning an event?" box
3. Click on "Create QR Code"
4. Swipe back as shown in the video

## Expected behaviour

The headline should not disappear

---
Internal Tracking ID: [EXPOSUREAPP-9029](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9029)

**Comment by dsarkar** [comment]
@Ein-Tim Thanks. Internal Tracking ID: [EXPOSUREAPP-9029](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9029)

**Comment by ndegendogo** [comment]
UIKit provides the following elements for handling of large titles:
- the navigation bar can be configured to support large titles (UINavigationBar.prefersLargeTitles). 
Note that the **navigation bar is shared** between the sibling view controllers (these siblings are pushed in from the side).
- each of these view controller **has its own navigation item** which it configures with its title and layout preferences (UINavigationItem.largeTitleDisplayMode).
- in the current implementation the view controllers permanently re-configure the shared navigation bar to their own preferences in their viewWillAppear method.

*A better solution seems to setup the navigation bar only from its owner (the navigation controller), and the view controllers don't fiddle with it and only setup their navigation item. 
BUT: it seems that the UIKit API has a bug (or hard-to-understand usage) if this view controller is a UITableViewController 
(if you google you find tons of Voodoo recipes and all seem to help in specific circumstances only)...*

I continue to investigate this...

**Comment by dsarkar** [comment]
@ndegendogo forwarded all to internal ticket. Thanks.

**Comment by ndegendogo** [comment]
@dsarkar I have played a bit with both tickets on the weekend. Currently I have no good solution, but I'll continue to investigate.

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode & this is only a minor issue, I don't expect it to be addressed anymore. I'm therefore closing this issue.
