### ISSUE TITLE
Contact Journal: Do not show the "Remove All" button if no People or Places exist

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#3382]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: not important
- iOS version: not important
- App version: 2.7.2

## Describe the bug

The big red "Remove All" button is shown, even if there are no People or Places to remove:

<img src="https://user-images.githubusercontent.com/67682506/129938758-cd7f465b-2261-436c-ab77-1e8a6a26063d.PNG" width="300">

After clicking on it, the "Do you really want to remove all people/places?" warning is shown: 

<img src="https://user-images.githubusercontent.com/67682506/129939043-7a2e7aa1-a780-477a-bd75-15a12a5b1d63.PNG" width="300">

This does not make sense and is confusing for the user.

## Steps to reproduce the issue

1. Open the Corona-Warn-App
2. Click on the "Journal" tab
3. Remove all people from the journal by clicking the 3 dots in the right corner and selecting "Edit People"
4. Click on "Remove All"
5. Click "Yes"
6. See that neither the "Remove All" button disappears, nor the view closes
7. Click on "Remove All"
8. See the warning
9. Click "Yes"
10. See that nothing happens (because nothing can happen)

## Expected behaviour

The button should only be shown if there are people or places which can be deleted.

## Possible Fix

The best way would be to gray out the "Edit People/Places" option in the 3 dot menu if there are not people/places. If all people/places are deleted via the button, the view should close after the people/places were deleted.

## Additional context

Please check the behavior under Android. 

----
Internal Tracking-ID: [EXPOSUREAPP-9081](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9081)

**Comment by jucktnich** [comment]
Not graying out but making a little graphic and text imo

**Comment by Ein-Tim** [comment]
I can confirm that this bug has been fixed with version 2.13.

| Contact Journal | My QR codes | My Check-Ins | 
|---|---|---| 
| <img src="https://user-images.githubusercontent.com/67682506/140170062-894f944d-a2b3-48f1-a72a-e1a8d351f849.PNG" width="300">  | <img src="https://user-images.githubusercontent.com/67682506/140170135-d6e3cd13-f5e0-48fd-8a97-ff5a0dbc6872.PNG" width="300"> | <img src="https://user-images.githubusercontent.com/67682506/140170189-2a3d5226-1e43-46c6-8393-041802ac4346.PNG" width="300"> | 

It is no longer possible to access the screen where you can press the "Remove All" button, thus this issue is solved.

Closing as fixed.
