### ISSUE TITLE
Vaccination certificate validation country list: there is country called "UP" in the list

### ISSUE THREAD

**Issue by ahsanemon** [corona-warn-app/cwa-app-ios#3383]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 6s
- iOS version: 14.4.2
- App version: 2.7.2 (0)

## Describe the bug
While validating the vaccination certificate I see there is country called UP in the country list. Just a heads-up whether this is intentional or not. 

![image](https://user-images.githubusercontent.com/1409741/130058161-c6d36c85-53b3-48b8-8c8d-16597f808684.png)

## Steps to reproduce the issue

1. Go to 'Certificate'
2. Click on the already added 'vaccination certificate QR code'
2. Click on 'Check Validity'
3. Scroll down throw the list of 'country' under 'Check for'
4. See error - A country called 'UP'

## Expected behaviour
I am not sure if such a country exists.

## Additional context

---
Internal Tracking ID: [EXPOSUREAPP-9054](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9054)

**Comment by Ein-Tim** [comment]
"UP" is a country code, that's shown if there is no localized name for the country available. However, I'm also unsere for which country "UP" stands.

**Comment by jucktnich** [comment]
UP Stands for Ukraine

**Comment by thomasaugsten** [comment]
The issue is fixed

**Comment by dsarkar** [comment]
@ahsanemon Thanks for reporting, see comment https://github.com/corona-warn-app/cwa-app-ios/issues/3383#issuecomment-901971903.

Please, close this issue.

![image](https://user-images.githubusercontent.com/1409741/130224878-9d22c038-297c-4a31-863a-91bb8c44ffb3.png)

---
Corona-Warn-App Open Source Team

**Comment by ahsanemon** [comment]
You people are doing a great job. Thanks a lot. :clap:
