### ISSUE TITLE
Vaccination certificates get valid at 02:00h and not at 00:00h (UTC translation issue)

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#3385]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 12 Pro
- iOS version: 14.7.1
- App version: 2.6.3

## Describe the bug

A Twitter user who was vaccinated on the 04.08.2021 saw this screen today at 00:48h:
<img src="https://user-images.githubusercontent.com/67682506/130060222-a1b5ac81-7436-4baa-a447-c294fcf6aa6e.png" width="300">

Although 15 days have passed, CWA still says that the certificate is invalid.

When he tried again later today, everything worked and his certificate was shown as valid.

This clearly seems like a UTC timezone issue. 

## Steps to reproduce the issue

1. Open the Corona-Warn-App
2. Import a vaccination certifcate
3. Wait till 15 days since your vaccination have passed and check the certificate between 00:00h and 01:59h
4. See that CWA shows that the certificate is invalid

## Expected behaviour

The certificate should become valid at exactly 00:00h at the 15. day after the vaccination

## Additional context

This bug report is based on the information a Twitter user shared with me: https://twitter.com/blackXXseven/status/1428127261178355713?s=20

----
Internal Tracking-ID: [EXPOSUREAPP-9080](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9080)

**Comment by jucktnich** [comment]
It's not the first UTC translation bug, maybe you should find a way internally, how time is handled 🤷‍♂️

**Comment by vaubaehn** [comment]
Hi @Ein-Tim and @jucktnich , I do not consider this to be a bug in CWA. Please see https://github.com/corona-warn-app/cwa-app-android/issues/3990#issuecomment-907110796 for an explanation.

**Comment by Ein-Tim** [comment]
@vaubaehn Thank you! As you are really **the** EU DCC expert here in the community, I trust you and your explanation makes sense. Maybe we could still get feedback from the developers? 

Have a good night!

**Comment by Ein-Tim** [comment]
Any feedback from the developers that this is intended? @thomasaugsten / @dsarkar

**Comment by dsarkar** [comment]
@Ein-Tim UTC times are used, this is intended in this case.

**Comment by Ein-Tim** [comment]
@dsarkar Okay, thanks for the confirmation.

Closing.
