### ISSUE TITLE
Add a warning message when trying to add a local 7-day-incidence without internet connection

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#3393]
## Avoid duplicates
* [X] This enhancement request has not already been raised before
* [X] Enhancement request is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)
* [X] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation
As described in https://github.com/corona-warn-app/cwa-documentation/issues/672#issuecomment-899384824:

Adding a local 7-day incidence without internet connection now no longer just does nothing while offline but already adds the card to the Home Screen. However, the card is empty (because CWA couldn't download the incidence from the internet - makes sense)
Here's a screenshot:
<img src="https://user-images.githubusercontent.com/67682506/129546599-9c0cda04-ad51-4375-a2f4-a15666b21d85.PNG" width="300">

After connecting to the internet, closing and reopening the app, the value is shown:
<img src="https://user-images.githubusercontent.com/67682506/129546774-cfc71136-5b40-45a1-b23e-8ccc794fe9a0.PNG" width="300">

## Suggested Enhancement
Align the behavior under iOS to the [behavior under Android](https://github.com/corona-warn-app/cwa-documentation/issues/672#issuecomment-903102086), where a warning message is shown: "Your Internet connection was lost. It was not possible to add a 7-day incidence figure. Please check the connection and try again."

## Expected Benefits
I think that the Android implementation is more user friendly, since the user is informed what's the problem. Currently, the user just sees a empty tile and wonders what went wrong...

---
Internal Tracking ID: [EXPOSUREAPP-13528](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13528)

**Comment by Ein-Tim** [comment]
I opened this issue nearly a year ago, it is still valid. It was never mirrored to JIRA. Please mirror it to JIRA now.

**Comment by Ein-Tim** [comment]
Why is this issue not mirrored to JIRA @larswmh & @dsarkar?

**Comment by larswmh** [comment]
Thanks for your enhancement request @Ein-Tim. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-13528](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13528)

As described in another issue already, the issues unfortunately snowed under, but we're now getting back to all the issues you're mentioning us in.

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
@Ein-Tim FYI PR https://github.com/corona-warn-app/cwa-app-ios/pull/4960

**Comment by dsarkar** [comment]
PR https://github.com/corona-warn-app/cwa-app-ios/pull/5018

**Comment by Ein-Tim** [comment]
I can confirm that this has been **fixed** with version 3.1, and I'm therefore closing this issue as completed.
