### ISSUE TITLE
UI: Empty space at the bottom of the "My QR Codes" screen

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#3408]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 12 mini Emulator
- iOS version: 14.5
- App version: 2.7.1

## Describe the bug

There's this unnecessary free space on the bottom of the "My QR Codes" screen, if you've got more than 3 QR Codes (in my case). The free space cuts off the 3rd QR-Code box.
<img src="https://user-images.githubusercontent.com/67682506/130646753-13d8ebb8-2582-4a3f-aeaf-1fd59324e2b8.png" width="300">

## Steps to reproduce the issue

1. Open the Corona-Warn-App
2. Scroll down to the "Planning an event?" box
3. Click on "Create QR Code"
4. Click on "Create QR Code" to create some QR codes
5. See the free space

## Expected behaviour

No empty space.

---

## Related issue

- #3332

---
Internal Tracking ID: [EXPOSUREAPP-9750](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9750)

**Comment by ndegendogo** [comment]
Same root cause as #3332

**Comment by dsarkar** [comment]
@ndegendogo Thanks, forwarded!

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-9750](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9750)

**Comment by ndegendogo** [comment]
@dsarkar please ask the devs if they are planning to work on this.
Else I would volunteer to try ... 😎

**Comment by heinezen** [comment]
@ndegendogo There is nobody assigned yet, so you can try :)

----
Corona-Warn-App Open Source Team

**Comment by ndegendogo** [comment]
I have submitted PR #3628 with a fix.

@dsarkar @heinezen please apply the labels. Thanks!
