### ISSUE TITLE
Digital COVID certificates validity check: List of countries is always in the language which was active during the onboarding

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#3409]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details
- Device name: iPhone 6
- iOS version: 15 Beta 6
- App version: 2.8.1

## Describe the bug
The names of the countries which can be selected in the "Validity of Certificate" screen does not adapt its translation correctly. They always stay in the language which was active during the onboarding.

## Steps to reproduce the issue
1. Open the iOS Settings
2. Scroll down to "Corona-Warn"
3. Select "Sprache" 
4. Select "English"
5. Open the Corona-Warn-App
6. Click on "Certificates"
7. Click on "Add Certificate" and scan the QR code of a certificate if you don't have any certificates registered in the app
8. Click on a certificate
9. Click on "Check Validity"
10. Click on "Country"
11. See that the names of the countries appear in German instead of in English

## Expected behaviour
The names of the countries should be localized correctly.

## Additional context
1. There is no way for me (currently) to get the app back to show the English names...
2. Please let me know if you need an error log. 

## Credits
This issue was discovered by @dsarkar!

---
Internal Tracking ID: [EXPOSUREAPP-10180](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10180)

**Comment by Ein-Tim** [comment]
With version 2.8 the issue is exactly the other way around. English always shows the German names...
Will adapt the OP later.

**Comment by ndegendogo** [comment]
Analysis: the list of countries is stored persistently including the localised names of the countries. As long as the list does not change (e.g. additional countries participate), it uses this stored list and does not recalculate the localisation.

**Comment by dsarkar** [comment]
@ndegendogo Thanks for analysing, I forward your info to the internal ticket.

**Comment by ndegendogo** [comment]
I found three variables in the Store related to Countries:
- [validationOnboardedCountriesCache](https://github.com/corona-warn-app/cwa-app-ios/blob/438c4f5549bf38dc84b661b3dc244fcbcab1aad0/src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift#L260) - this is used to populate the picker for the certificate validity check
- [lastSelectedValidationCountry](https://github.com/corona-warn-app/cwa-app-ios/blob/438c4f5549bf38dc84b661b3dc244fcbcab1aad0/src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift#L241) - this is the initial value of the picker for the certificate validity check
- [submissionCountries](https://github.com/corona-warn-app/cwa-app-ios/blob/438c4f5549bf38dc84b661b3dc244fcbcab1aad0/src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift#L181) - this is not used during certificate validation; it seems to be related to the ExposureSubmissionService, but I didn't analyse this in more detail

**Comment by ndegendogo** [comment]
@dsarkar @heinezen I have submitted PR #3802 with a fix for this - please apply the labels. Thanks!

**Comment by Ein-Tim** [comment]
Thanks for the PR @ndegendogo!

**Comment by Ein-Tim** [comment]
Confirm fixed in version 2.15.

Thank you, again, for the PR fixing this @ndegendogo.

Closing as fixed.

**Comment by dsarkar** [comment]
@ein Thanks for following up. I will remark in the internal ticket, that the fix was confirmed by the community.
