### ISSUE TITLE
Why checks for countries with no rules?

### ISSUE THREAD

**Issue by jwildeboer** [corona-warn-app/cwa-app-ios#3415]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 11
- iOS version: 14.7.1
- App version: 2.8.0(4)

## Describe the bug

When you check validity of certificate for entry in a country, the selector offers countries that have no rules, so the check always fails.

In previous version of the App, the check would show a succesful check.  

This change in behaviour is confusing.

It would be better to only offer countries in the selector that actually have rules. Because when no rules exist, the check will always fail.

**Comment by Ein-Tim** [comment]
Please check for the behavior under Android.

**Comment by thomasaugsten** [comment]
A country can have no rules for the specific date or for the specific certification type.

Offer only countries with rules will  raise the questions why is the country not in the list.

Is traveling not allowed for this country or is my certificate not accepted in this country.
For every country in the list you are allowed to travel with your certificate and you can find the detailed rules on the reopen europe page

**Comment by jwildeboer** [comment]
There currently seem to be active rules only for:

- Germany
- Ireland
- Lithuania
- Luxembourg
- Netherlands
- Romania
- Slovenia
- Spain
- Ukraine

**Comment by jwildeboer** [comment]
So why check at all? ;) The CWA now checks validity when adding a certificate anyway and any valid certificate allows entry in all listed countries, as you say, so what purpose does the check fulfil at the moment? It gives a confusing message (cannot check validity) for most countries.

**Comment by Ein-Tim** [comment]
@jwildeboer 

To answer your question, yes, CWA checks for a valid signature, but it doesn't check for the rules a country has set.

If you want to know more I suggest to read through here: https://github.com/corona-warn-app/cwa-app-android/issues/4053

Would you like to close this issue?

**Comment by dsarkar** [comment]
@Ein-Tim @jwildeboer The country list is not hard-coded into the CWA, but can be updated dynamically. We can most probably expect that these countries shown, might upload business rules at some point.

**Comment by Ein-Tim** [comment]
@jwildeboer Could you please close this issue? Your question has been answered and it seems like the behavior won't be changed.
