### ISSUE TITLE
EU country check is valid before test time

### ISSUE THREAD

**Issue by arnebr** [corona-warn-app/cwa-app-ios#3420]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
**Not sure, if only on iOS **
* [x] Bug is not already reported in another issue

## Technical details

- Device name: iPhone
- iOS version:14.7.1
- App version: 2.8.1

## Describe the bug

When I checked a valid EU test certificate against country rules before the test time it is shown as valid.

![image](https://user-images.githubusercontent.com/1068416/130829681-c08312b5-e2b8-442e-b9d0-038ef42730cd.jpeg)
![image](https://user-images.githubusercontent.com/1068416/130829722-49c65db4-c3a7-4827-8a4d-c4efdd2d1f5d.png)

## Steps to reproduce the issue

- Generate a valid EU test certificate 
- Check against country rules to a date in the past 
- It is shown as valid 

## Expected behaviour

The certificate should be invalid due to test time before certificate check time 

## Possible Fix

If test time before certificate check time then show error

**Comment by vaubaehn** [comment]
This can only be fixed by the member countries that uploaded their business rules to an interoperability gateway, frome where CWA downloads the rules to check them in the app.
In case of Spain, it could be @carballAcc who could take care of it, but to my best knowledge, all or nearly all member countries (including Germany?) are affected by this. AFAIR, when debugging business rules with a self-created test cert with sample collection date-time in the future, it was valid everywhere. Maybe something that could be brought up in the next IOP subgroup meeting, @thomasaugsten ?

On the other hand, a business rule check should not be possible for the past. It's not possible in CWA Android, and should probably be aligned for iOS.

**Comment by Ein-Tim** [comment]
@vaubaehn 

Yes, I guess the real issue here is that you can choose a date in the past. This should be fixed (make it impossible to select a date in the past).

**Comment by vaubaehn** [comment]
@Ein-Tim 
But for all other wallet apps existing in the wild in all countries, it would also be good to take care of the business rules themselves :)

**Comment by Ein-Tim** [comment]
This issue is nearly 9 months old and

a) it was not mirrored to JIRA
b) there was no feedback at all from any of the maintainers

If this is out of scope for the CWA, please close it. If not, please mirror it to JIRA or let us know that someone is aware of this issue. 

cc @thomasaugsten

**Comment by Ein-Tim** [comment]
@arnebr Maybe it makes sense to close this issue in favour of https://github.com/corona-warn-app/cwa-app-ios/issues/3839?

**Comment by arnebr** [comment]
When a maintainer decides they will close the issue. But it seems this ticket older then the other  to have a better timeline of the issue occurence, this should be the reference.

**Comment by Ein-Tim** [comment]
@arnebr Agreed. It would be great if @thomasaugsten could confirm what @vaubaehn shared with us above.

**Comment by Ein-Tim** [comment]
With version 2.23.1 it's not possible to check certificates against a time in the past. This issue is therefore also fixed.

Please close this issue @arnebr.

@dsarkar Would you like to apply the `Fix 2.23` label here?

**Comment by dsarkar** [comment]
@arnebr Thanks for reporting. @Ein-Tim Thanks for the ping here.

Best wishes, DS

---
Corona-Warn-App Open Source Team
