### ISSUE TITLE
Inconsistencies in the license/third-party-notices documentation

### ISSUE THREAD

**Issue by serenity182** [corona-warn-app/cwa-app-ios#343]
Hi,

I'm refering to this file /corona-warn-app/cwa-app-ios/blob/development/THIRD-PARTY-NOTICES

There are some inconsistencies in this document.

- The copyright information seems to be missing in the swift-protobuf/Apple Inc. license section (starting LOC44) 

- Ashley Mills is mentioned with his/her license, but the referering component is missing in the beginning. (starting LOC267)

- Deusty, LLC is mentioned with its license, but the referering component is missing in the beginning. (starting LOC341)

**Comment by tkowark** [comment]
Dear @serenity182 , thanks for spotting these issues. We're currently working on automating the creation of both the app screen and the third party notices file (#204 ) and will try to fix your points in that process
