### ISSUE TITLE
Exposure check failed / no exposure check for more than 24 hours

### ISSUE THREAD

**Issue by ndegendogo** [corona-warn-app/cwa-app-ios#3432]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 6
- iOS version: 12.5.3
- App version: 2.7.2 (0)

## Describe the bug
Today I opened cwa on my iPhone 6 and instead of the (hopefully green) risk card, I see an error message, see screenshot.
Risk check failed. The "Start again" button shows no effect.
The ENF log confirms there was no check since yesterday evening 19:41. Now it is 21:45. Usually I get several test per day. The device had WLAN coverage all the time.

## Expected behaviour
Regular risk checks from background and foreground.

## Additional context

![IMG_0006](https://user-images.githubusercontent.com/6118267/131027378-68eb7f39-f90a-418e-9d66-9607d7b434ce.png)
![IMG_0007](https://user-images.githubusercontent.com/6118267/131027425-f225087b-e1b2-4c61-b185-0440d9b65f13.png)

**Comment by Ein-Tim** [comment]
@ndegendogo 

Are you able to reproduce this on the latest CWA version?

**Comment by ndegendogo** [comment]
Meanwhile I am on version 2.10.2 (0).
I have not seen this error message again, and got regular risk checks since then.

I am not aware of any special circumstances or action that had caused the checks to stop back then in the 2.7. So, either it is indeed **fixed** 👍😁, or it is a very special (and unknown) combination of circumstances, and we can regard it as **not reproducible** 🤷

In any case, I am closing the ticket now.
