### ISSUE TITLE
Twitter Report: „2/3“ vaccination does not show up as valid

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#3436]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation) - not sure
* [x] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 6s
- iOS version: 14.7.1
- App version: 2.8.1

## Describe the bug

A user on Twitter received his second shot of Comirnaty today. 
On his vaccination certificate, however, it says "2/3" (two out of three shots received).
This leads to the issue that CWA does not recognize the vaccination as full yet, it says "Sie haben derzeit noch nicht alle geplanten Impfungen erhalten. Daher ist Ihr Impfschutz noch nicht vollständig."

## Steps to reproduce the issue

1. Get your second shot and make sure that you get a EU digital COVID vaccination certificate where the vaccination is issued as "2/3"
2. Add the certificate to the Corona-Warn-App
3. See the text I wrote above

## Expected behaviour

"2/3" vaccinations should already show as valid (after min. 14 days of the vaccination)

**Comment by Ein-Tim** [comment]
Can we get this mirrored to JIRA? Version 2.9 did not fix this.

**Comment by jucktnich** [comment]
Isn't this a problem of the specific certificate? It should say 2/2.

**Comment by Ein-Tim** [comment]
@jucktnich I don't know, this would be the first question that have to be answered, is it intended that a certificate shows "2 out of 3 doses".

**Comment by Ein-Tim** [comment]
As a "2/3" certificate would not be validated in the CovPassCheck-App, it makes no sense to show it as valid in the CWA.
These certificate should not exist, as the 3rd shot is optional. 

Closing this as not fixable.
