### ISSUE TITLE
Is it intended that the "HealthCertifiedPerson_partiallyVaccinated" text is shown even if a test certificate is the currently used certificate?

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#3455]
## Avoid duplicates
* [X] Question is not already answered in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Question is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Question has not already been asked in another issue

## Your Question
If a user has registered one vaccination certificate "1/2" and one test certificate from a test which was taken less than 24h ago than the test certificate is the currently used certificate. But still, the text "You have not yet received all the currently planned vaccinations. As such, your vaccination protection is not complete yet." is shown.
I would expect that this text is only shown if the vaccination certificate "1/2" is the currently used certificate.

## Screenshot
<img src="https://user-images.githubusercontent.com/67682506/131675278-e602fa05-ed14-4f0c-b38f-9e081d4284cd.jpg" width="300">

---
Internal Tracking ID: EXPOSUREAPP-13336

**Comment by Ein-Tim** [comment]
@dsarkar Could you or the team check if this still applies? I currently don't have a test certificate so I can't check. Thanks.

**Comment by Ein-Tim** [comment]
Please mirror this item to JIRA.

**Comment by svengabr** [comment]
I have opened a Jira ticket:

Internal Tracking ID: EXPOSUREAPP-13336

**Comment by mlenkeit** [comment]
@Ein-Tim although this ticket is quite a few months old and the corresponding logic in CWA was changed many times, this is currently the expected behavior.

Even if there is only a Test Certificate and no Vaccination Certificate, the text would be displayed.

The message is not wrong: the user does not have recommended vaccinations.

**Comment by Ein-Tim** [comment]
@mlenkeit Thanks for the feedback! Yep, seems right, I was just unsure as the vaccination certificate is not the currently used certificate, but OK. Thank you!
