### ISSUE TITLE
Onboarding flow is broken in community build / cannot enable EN Manager (Development version / pre-release)

### ISSUE THREAD

**Issue by ndegendogo** [corona-warn-app/cwa-app-ios#3460]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue

## Technical details

- Device name: simulator, all devices
- iOS version: simulator, independent of iOS version
- App version: *Development branch*: release/2.10.x as of 28aedac81cf81a66bec30ac7814c31f240d0edcf (01 Sept, development version / pre-release).

## Steps to reproduce the issue

1) from Home screen / Settings / reset App
2) follow the Onboarding
3) get several error messages, see screenshots
4) ENManager cannot be activated

## Expected behaviour

Reset app and the following Onboarding flow should succeed

## Additional context
Most likely reason is the integration of the MockENManager for the Community build. It seems that a few switches for Community build are still missing.
Also the state machine for activation of the ENManager assumes initial state = enabled. This is not true for the Onboarding flow.

**Work-around**: ignore all error messages during onboarding, and restart application after onboarding is finished. 

![Simulator Screen Shot - iPhone SE (2nd generation) - 2021-09-01 at 23 34 38](https://user-images.githubusercontent.com/6118267/131749788-3fc12ef9-1cdb-4c28-8f9a-5807a2d102da.png)

![Simulator Screen Shot - iPhone SE (2nd generation) - 2021-09-01 at 23 35 33](https://user-images.githubusercontent.com/6118267/131749831-a4714dd4-7f7f-4830-929f-9db0c0089013.png)

![Simulator Screen Shot - iPhone SE (2nd generation) - 2021-09-01 at 23 36 01](https://user-images.githubusercontent.com/6118267/131749869-8df297cb-8d29-4946-a641-0ef89d8bef77.png)

![Simulator Screen Shot - iPhone SE (2nd generation) - 2021-09-01 at 23 36 55](https://user-images.githubusercontent.com/6118267/131749915-0c3ec566-6167-4571-83c4-cc89b5afc036.png)

![Simulator Screen Shot - iPhone SE (2nd generation) - 2021-09-01 at 23 37 12](https://user-images.githubusercontent.com/6118267/131749942-a770b937-509e-402a-bca1-ee184bc14f49.png)

---
Internal Tracking ID: [EXPOSUREAPP-9280](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9280)

**Comment by ndegendogo** [comment]
Volunteering for a fix ....

**Comment by ndegendogo** [comment]
... it seems indeed related to the integration of the MockENManager 
(commit 7ed7a60965dc0f1b33e15a7423ee070c6815e1bf).
If I revert that commit, everything works again.

Maybe the reason is that the state machine for enable/disable the MockENManager does not work as expected.
The property observer for the ENState is not triggered as expected.

Maybe it was some other dependency that was introduced via ENAManager.

***@dsarkar @heinezen please tell the devs: before they are blocked from working they shall revert this commit so it can be investigated in more detail.***

**Comment by ndegendogo** [comment]
Also I see a long error message related to SSL in the log file.
Not sure if that is a local problem on my side, or related to the issue, or if I can just ignore it?
Am I missing a certificate?

2021-09-02 01:54:06.837516+0200 ENA[22125:717527] Task <BC052FF2-C2CC-44F7-9EFD-D6454932FA35>.<1> finished with error [-1200] Error Domain=NSURLErrorDomain Code=-1200 "Es ist ein SSL-Fehler aufgetreten. Eine sichere Verbindung zum Server kann nicht hergestellt werden." UserInfo={NSErrorFailingURLStringKey=https://svc90.main.px.t-online.de/version/v1/ehn-dgc/dscs, NSLocalizedRecoverySuggestion=Soll die Verbindung zum Server trotzdem hergestellt werden?, _kCFStreamErrorDomainKey=3, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <BC052FF2-C2CC-44F7-9EFD-D6454932FA35>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <BC052FF2-C2CC-44F7-9EFD-D6454932FA35>.<1>"
), NSLocalizedDescription=Es ist ein SSL-Fehler aufgetreten. Eine sichere Verbindung zum Server kann nicht hergestellt werden., NSErrorFailingURLKey=https://svc90.main.px.t-online.de/version/v1/ehn-dgc/dscs, NSUnderlyingError=0x600003018ab0 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, _kCFNetworkCFStreamSSLErrorOriginalValue=-9816, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9816}}, _kCFStreamErrorCodeKey=-9816}
2021-09-02 01:54:06.839870+0200 ENA[22125:716860] Task <412973CF-8797-4E54-B3D4-2C0F67E3622E>.<1> HTTP load failed, 0/0 bytes (error code: -1200 [3:-9816])
2021-09-02 01:54:14.802738+0200 ENA[22125:717527] [api] [ENA/URLSession+Convenience.swift:68] [response(for:isFake:extraHeaders:completion:)] No server request response
2021-09-02 01:54:14.803321+0200 ENA[22125:717529] Task <412973CF-8797-4E54-B3D4-2C0F67E3622E>.<1> finished with error [-1200] Error Domain=NSURLErrorDomain Code=-1200 "Es ist ein SSL-Fehler aufgetreten. Eine sichere Verbindung zum Server kann nicht hergestellt werden." UserInfo={NSLocalizedRecoverySuggestion=Soll die Verbindung zum Server trotzdem hergestellt werden?, _kCFStreamErrorDomainKey=3, NSErrorPeerCertificateChainKey=(
    "<cert(0x7fb541829600) s: svc90.main.px.t-online.de i: TeleSec ServerPass Class 2 CA>",
    "<cert(0x7fb54182a400) s: TeleSec ServerPass Class 2 CA i: T-TeleSec GlobalRoot Class 2>"
), NSErrorClientCertificateStateKey=0, NSErrorFailingURLKey=https://svc90.main.px.t-online.de/version/v2/app_config_ios, NSErrorFailingURLStringKey=https://svc90.main.px.t-online.de/version/v2/app_config_ios, NSUnderlyingError=0x60000306d020 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, kCFStreamPropertySSLPeerTrust=<SecTrustRef: 0x600000c7ed00>, _kCFNetworkCFStreamSSLErrorOriginalValue=-9816, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9816, kCFStreamPropertySSLPeerCertificates=(
    "<cert(0x7fb541829600) s: svc90.main.px.t-online.de i: TeleSec ServerPass Class 2 CA>",
    "<cert(0x7fb54182a400) s: TeleSec ServerPass Class 2 CA i: T-TeleSec GlobalRoot Class 2>"
)}}, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <412973CF-8797-4E54-B3D4-2C0F67E3622E>.<1>"
), _kCFStreamErrorCodeKey=-9816, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <412973CF-8797-4E54-B3D4-2C0F67E3622E>.<1>, NSURLErrorFailingURLPeerTrustErrorKey=<SecTrustRef: 0x600000c7ed00>, NSLocalizedDescription=Es ist ein SSL-Fehler aufgetreten. Eine sichere Verbindung zum Server kann nicht hergestellt werden.}
2021-09-02 01:54:14.804194+0200 ENA[22125:717527] [ENA/DSCListProvider.swift:82] [updateListIfNeeded()] Failed to updated DSCList noResponse
2021-09-02 01:54:14.872412+0200 ENA[22125:717529] [api] [ENA/URLSession+Convenience.swift:68] [response(for:isFake:extraHeaders:completion:)] No server request response

**Comment by dsarkar** [comment]
@ndegendogo Thanks for the report. I have forwarded this issue and in particular your comment https://github.com/corona-warn-app/cwa-app-ios/issues/3460#issuecomment-910969761


---
Internal Tracking ID: [EXPOSUREAPP-9280](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9280)

**Comment by ndegendogo** [comment]
@dsarkar I have a solution and am just preparing a PR.
Mainly there was a switch missing.

**Comment by dsarkar** [comment]
@ndegendogo OK, thanks.

**Comment by ndegendogo** [comment]
I have submitted PR #3463 with a fix.

@dsarkar @heinezen could you please add labels? Thanks.

**Comment by ndegendogo** [comment]
The PR with the fix is merged and available in the latest developer build.
Closing the ticket.

**Comment by dsarkar** [comment]
@ndegendogo Thanks for reporting the issue and providing a PR.
