### ISSUE TITLE
Large titles for the Data donation screen

### ISSUE THREAD

**Issue by ndegendogo** [corona-warn-app/cwa-app-ios#3467]
## Avoid duplicates
* [X] This enhancement request has not already been raised before
* [X] Enhancement request is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)
* [ ] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation

Currently, the data donation screen is implemented with a normal title.
See screenshot.

## Suggested Enhancement

According to [this discussion](https://github.com/corona-warn-app/cwa-app-ios/pull/3430#discussion_r700185826), the designer would rather like a large title, but not in the onboarding flow.

> ... chat with a responsible designer. Its a little more complicated. This view controller is used in the onboarding and also in the settings. The ideal solution would be: a small title in the onboarding and a large title in the settings.

## Expected Benefits

Make the designer happy

![Simulator Screen Shot - iPhone SE (2nd generation) - 2021-09-01 at 21 03 05](https://user-images.githubusercontent.com/6118267/131838681-f28a4792-6da8-46cd-98f9-c3916b18e6dc.png)

---
Internal Tracking ID: [EXPOSUREAPP-9292](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9292)

**Comment by ndegendogo** [comment]
@dsarkar I volunteer for this one

**Comment by ndegendogo** [comment]
@dsarkar @heinezen I have submitted PR #3473.
Could you please apply the labels?
Thanks!

**Comment by ndegendogo** [comment]
Closing as implemented

**Comment by dsarkar** [comment]
@ndegendogo Thanks for contributing!
