### ISSUE TITLE
FriendsInvite has no scrolling behaviour on bigger iPhones. On purpose?

### ISSUE THREAD

**Issue by Bohne9** [corona-warn-app/cwa-app-ios#347]
The FriendsInvite scene has no scrolling behaviour. Since there is not a lot of content in this scene, I am asking myself if that behaviour is on purpose.

For me it feels more natural if that scene bounces.

<img src="https://user-images.githubusercontent.com/24317813/84043057-1fb76780-a9a6-11ea-8167-d3a76cdbdfb5.png" width=300x></img>

**Comment by EisvogelSAP** [comment]
Hey @Bohne9, thanks for raising this. Will align with our design team.
