### ISSUE TITLE
Use standartized name from the EU Digital Covid Certificate to support other languages

### ISSUE THREAD

**Issue by yoanad** [corona-warn-app/cwa-app-ios#3471]
I noticed that the app doesn't display the standartized name, when displaying the EU Digital Covid Certificate. 
In my case, the vaccination certificate was issued by Bulgaria and the "default" name is in Cyrillic letters, which is of course, not very useful outside of Bulgaria. I can imagine that it could be an issue for other EU-issued certificates (e.g. Greek?).

**Comment by Ein-Tim** [comment]
@yoanad 

Version 2.8 implemented that the standardized name is shown too. 
More information can be found in this blog post: [Corona-Warn-App version 2.8 displays names in certificates in standardized characters](https://www.coronawarn.app/en/blog/2021-08-25-cwa-version-2-8)
Please make sure you are on version 2.8.

**Comment by yoanad** [comment]
@Ein-Tim Thanks! I see that it's shown only in the detailed preview, but not on the first page. Maybe it makes sense to use it as a default? 
![IMG_0023](https://user-images.githubusercontent.com/11481046/131879166-a06fbe35-4503-432d-900d-56878776811c.jpg)

**Comment by Ein-Tim** [comment]
@yoanad 

Ah okay, yes, it's only shown in the detail view. 
If you think it would be a good idea to also show it on the overview, I suggest to open a new issue here https://github.com/corona-warn-app/cwa-wishlist, as this affects iOS & Android.

Thanks!

**Comment by dsarkar** [comment]
Dear @yoanad and community.

Thanks for contributing here. As @Ein-Tim mentioned this enhancement has been implemented. We will therefore close this issue now. 

Of course, feel free to create another wihslist item, as @Ein-Tim has suggested.

Thanks again, best wishes, DS

---
Corona-Warn-App Open Source Team
