### ISSUE TITLE
"Exposure Submission QR Code Info" screen is shown twice when registering test

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#3478]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone XR
- iOS version: 14.7.1
- App version: 2.8.1

## Describe the bug

When a rapid antigen test is registered via a link or when the user scans the QR code with the native iOS camera, the `Exposure Submission QR Code Info` screen is pushed twice.

## Steps to reproduce the issue

1. Make an appointment for a rapid antigen test
2. Scan the QR code with the native iOS camera or click on the link to register the test in the Corona-Warn-App
3. See that the `Exposure Submission QR Code Info` screen is pushed twice

## Expected behaviour

`Exposure Submission QR Code Info` screen should only be pushed once.

## Screenrecordings

Click on link:

https://user-images.githubusercontent.com/67682506/132257322-adb57984-112e-4347-8649-4ef6e0003c1c.MP4

Scan QR code via iOS camera app:

https://user-images.githubusercontent.com/67682506/132257329-e6ef77fa-4d95-4351-bf0b-6d3da72d22d2.MP4

----
Internal Tracking-ID: [EXPOSUREAPP-9770](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9770)

**Comment by Ein-Tim** [comment]
It seems like this was fixed in the meantime. I can't reproduce it anymore.

**Comment by dsarkar** [comment]
@Ein-Tim Thanks for your feedback, forwarded to internal ticket.
