### ISSUE TITLE
A bit confusing information in the news, concerning the release of today. 8th september

### ISSUE THREAD

**Issue by ouboub** [corona-warn-app/cwa-app-ios#3485]
Hi

the latest release states:

The Corona-Warn-App now displays full vaccination protection for recovered persons directly after the first vaccination. The two-week waiting time is waived for all vaccines except Johnson&Johnson.

A couple of remarks
1. I am not sure it is a got idea to use the verb waived here, since non native speaker might not know it.

2. More importantly, the information is a bit confusing. So I understand it like this. You obtain a first stab of a non Johnson Johnson vaccination  (normally you would need two), now since you recovered from a infection: recovered infection + only one shot = you don't need to wait two weeks to obtain the status of fully vaccinated. The confusing part concerns Johnson Johnson (which I received). For that you only need 1 shot. So does the information really mean, that  it is *not* sufficient to have recovered, you still have to wait for 2 weeks? Is this really true? Or is this just not correctly stated. If true can somebody please provide me a pointer?

Thanks 

Uwe Brauer

**Comment by Ein-Tim** [comment]
@ouboub 

Reg. 1: Please provide a link to a article where this term is used.

Reg. 2: Yes, see the blog post: https://www.coronawarn.app/en/blog/2021-09-08-cwa-version-2-9/

**Comment by ouboub** [comment]
>>> "T" == Tim  ***@***.***> writes:

> @ouboub 
> Reg. 1: Please p
rovide a link to a article where this term is used.
It is in the news (either calling the app, your using the info in the app shop). Here is a screenshot


> Reg. 2: Yes, see the blog post: https://www.coronawarn.app/en/blog/2021-09-08-cwa-version-2-9/

That information is a bit clearer than the screenshot I attach.

Still this is a serious lack of features.
To get that straight.
A recovered user with one stab of Moderna/Astra/Biontech gets full
vaccinated status, meanwhile a recovered user with one stab
Johnston/Johnston, does *not*. Call it nitpicking but this is a serious
lack of a feature.

**Comment by Ein-Tim** [comment]
@ouboub 

If you want to upload a screenshot, please use GitHub Mobile or the GitHub website. You can't upload anything via E-Mail replay.

> Call it nitpicking but this is a serious
lack of a feature.

There is no technical way to implement this, see the description in the blog post. Or do you have an idea how to implement this?

**Comment by jucktnich** [comment]
@Ein-Tim the App knows you've got the recovery certificate and you got the shot, so what's the problem?

**Comment by Ein-Tim** [comment]
@jucktnich What if there is no recovery certificate in the app? The app currently detects that you received a vaccination certificate "1/1" for a vaccine that normally requires two doses, so it "notices" that this must be a vaccination after a recovery. 
Johnson & Johnson vaccinated people always receive a "1/1" certificate, so there is no way for the app to tell whether this is a normal vaccination or a vaccination after a recovery.

**Comment by jucktnich** [comment]
Ah ok if you have a recovery certificate This constraint doesn't apply?

**Comment by Ein-Tim** [comment]
@jucktnich No this has nothing to do with recovery certificates. Is completely independent.

**Comment by jucktnich** [comment]
If the same person has a recovery certificate and a 1/1 JJ shot, why can't the CWA then show the fully vaccinated status directly. If it's a normal vaccination you won't have a recovery certificate.

**Comment by Ein-Tim** [comment]
@jucktnich 

Feel free to open an issue in the wishlist for this.

**Comment by Ein-Tim** [comment]
@jucktnich 

FYI: @dsarkar describes [here](https://github.com/corona-warn-app/cwa-website/issues/1674#issuecomment-915334299) pretty well why this would not help, CWA could maybe show the certificate as valid even though 14 days aren't up yet, but a verifier app will still show the certificate as invalid.

**Comment by jucktnich** [comment]
https://github.com/corona-warn-app/cwa-website/issues/1674#issuecomment-915334299 says that it wouldn't work cause of the business rules, so I won't open a new issue.

**Comment by ouboub** [comment]
> @ouboub
> 
> If you want to upload a screenshot, please use GitHub Mobile or the GitHub website. You can't upload anything via E-Mail replay.
> 
> > Call it nitpicking but this is a serious
> > lack of a feature.
> 
> There is no technical way to implement this, see the description in the blog post. Or do you have an idea how to implement this?

First the screenshot
![corona](https://user-images.githubusercontent.com/5957203/132578583-e2413550-57a3-43ca-85d6-c1cfd9ac80b3.png)

**Comment by ouboub** [comment]
>>> "T" == Tim  ***@***.***> writes:

> @ouboub 

> If you want to upload a screenshot, please use GitHub Mobile or the
> GitHub website. You can't upload anything via E-Mail replay.

Done, but frankly Github s... Not only does it use git instead of a
decent VC system, it does not allow a normal email flow (ok this is off
topic)


>> Call it nitpicking but this is a serious
> lack of a feature.

> There is no technical way to implement this, see the description in
> the blog post. Or do you have an idea how to implement this?

Right now, I am just talking about the information provided in the News,
of the release of today, I sent a screenshot.

Then I want to comment on the blog.
I quote 

,----
| Normally, vaccines do not have full protection until 14 days after the
| last required vaccination. However, the two-week waiting period is not
| applicable to those who recovered from COVID and then got their first
| shot. In these cases, the Corona-Warn-App now recognizes this as a
| post-recovery vaccination and displays the full vaccination protection
| immediately.
`----

Conclusion: 

1. the Corona-Warn-App has a way to know if someone has recovered.

2. The Corona-Warn-App has a way to know that the vaccination is a
   two-stab vaccination

3. The app display the full vaccination protection *before* the 14 week
   period has finished.

Then this blog states:

,----
| Users who get vaccinated with Johnson & Johnson’s vaccine after recovery
| are an exception. Since only one shot is required for this vaccine, the
| Corona-Warn-App cannot distinguish between those who have recovered and
| got vaccinated and those who have been vaccinated normally. In these
| cases, it always displays full vaccination status after 14 days.
`----

This does not make sense. If the App can do 1. And 2 above then it can
do the same for Johnson-Johnson.

You say that is impossible, then this information is misleading and it
should be explained better. The same holds for the News (which is the
issue I raised).

Regards

**Comment by Ein-Tim** [comment]
@ouboub 

Thanks for the screenshot, indeed, the word waived is also new for me. Strange that they used it in this screen... 

Now to your comment on Johnson & Johnson: 
Yes, the coverage in the media reg. this is confusing, I hope somebody from SAP/a PR agency contacted the news sites about this, but in the end, it's their decision what and how they write...

> Conclusion: 1. the Corona-Warn-App has a way to know if someone has recovered. 

Yes, but only because it notices that a vaccine which normally requires 2 doses is finished with just one dose. 

> 2. The Corona-Warn-App has a way to know that the vaccination is a two-stab vaccination 3. The app display the full vaccination protection *before* the 14 week period has finished.

Yes & Yes. 

> This does not make sense. If the App can do 1. And 2 above then it can do the same for Johnson-Johnson. You say that is impossible, then this information is misleading and it should be explained better.

No, because the app does only read from the number of doses, with e.g. Biontech it's clear, if you only receive one shot and that's it, you must be recovered. If you receive only one shot of Johnson & Johnson, that's totally normal, the app can't tell whether you recovered or not. 

Maybe [this](https://github.com/corona-warn-app/cwa-website/issues/1674#issuecomment-915334299) comment from @dsarkar helps:
> It is a technical problem: The actual JSON scheme makes it impossible to differentiate the case "Recovered and 1/1 &J vaccinated" not only for a the CWA but also for the verifier apps. Scanning both certificates would not help in the current implementation, since the vaccination certificate will be shown as invalid in the first 14 days due to the business rules. The current scheme simply cannot map the case properly.

**Comment by ouboub** [comment]
>>> "T" == Tim  ***@***.***> writes:

> @ouboub 
> Thanks for the screenshot, indeed, the word waived is also new for me. Strange that they used it in this screen... 

> Now to your comment on Johnson & Johnson: 
> Yes, the coverage in the media reg. this is confusing, I hope somebody
> from SAP/a PR agency contacted the news sites about this, but in the
> end, it's their decision what and how they write...

>> Conclusion: 1. the Corona-Warn-App has a way to know if someone has recovered. 

> Yes, but only because it notices that a vaccine which normally requires 2 doses is finished with just one dose. 

I am not sure I understand that. 

    1. The app knows it is Biontech, Moderna, Astra-Z

    2. the app noticed no second stab,

    3. The app concludes that was a case of a recovered person??


What's about the szenario the person just forgot to take the second stab or had a too strong reaction or whatever the reason is.

Surely there must be something else, say upload a certificate that you had recovered.

That is a crucial information that is missing

>> 2. The Corona-Warn-App has a way to know that the vaccination is a
>> two-stab vaccination 3. The app display the full vaccination
>> protection *before* the 14 week period has finished.

> Yes & Yes. 

>> This does not make sense. If the App can do 1. And 2 above then it
>> can do the same for Johnson-Johnson. You say that is impossible,
>> then this information is misleading and it should be explained
>> better.

> No, because the app does only read from the number of doses, with e.g.
> Biontech it's clear, if you only receive one shot and that's it, you
> must be recovered. If you receive only one shot of Johnson & Johnson,
> that's totally normal, the app can't tell whether you recovered or
> not.

See my objection above, the person simply does want (or cannot take a second stab).

> Maybe [this](https://github.com/corona-warn-app/cwa-website/issues/1674#issuecomment-915334299) comment from @dsarkar helps:
>> It is a technical problem: The actual JSON scheme makes it
>> impossible to differentiate the case "Recovered and 1/1 &J
>> vaccinated" not only for a the CWA but also for the verifier apps.
>> Scanning both certificates would not help in the current
>> implementation, since the vaccination certificate will be shown as
>> invalid in the first 14 days due to the business rules. The current
>> scheme simply cannot map the case properly.

This does not explain, on what reasons the app after one shot declares fully vaccinated, without any further confirmation.

regards

**Comment by Ein-Tim** [comment]
@ouboub 


> I am not sure I understand that. 1. The app knows it is Biontech, Moderna, Astra-Z 2. the app noticed no second stab, 3. The app concludes that was a case of a recovered person?? What's about the szenario the person just forgot to take the second stab or had a too strong reaction or whatever the reason is. Surely there must be something else, say upload a certificate that you had recovered. That is a crucial information that is missing

Okay, I will explain it the best way I can.
Normally, when you receive your first shot of Biontech, Moderna or AstraZeneca, you get a certificate which says "1/2" (one dose out of two planned doses).
If a recovered person gets vaccinated with Biontech, Moderna or AstraZeneca, they get a certificate "1/1" (one dose out of one planned doses). Now the app notices: "Oh, this vaccine normally requires two doses at the end, but here we have certificate which only requires one dose at the end. This person must be recovered"). Do you understand?

Now to the problem: If a non recovered person receives the Johnson & Johnson vaccine, they get a certificate "1/1" (one dose out of one planned doses). 
And if a recovered person gets the Johnson & Johnson vaccine, they also get a certificate "1/1" (one dose out of one planned doses). 
So now the app has no way to tell whether this person was just vaccinated as planned or if the person was recovered before. So, everybody sees the 14 day countdown. 

To your concern that maybe a person who just didn't receive the second dose may be shown as fully vaccinated then, no, because they will receive a "1/2" (one dose out of two planned doses) certificate, so the app sees: "Ah, everything is normal here, the person has not recovered and their vaccination protection is not yet full since the person did not yet get the second dose". 
A not recovered person will **never** receive a "1/1" (one dose out of one planned doses), only the people who recovered. 

Now clearer?

**Comment by ouboub** [comment]
>>> "T" == Tim  ***@***.***> writes:

> @ouboub 
>> I am not sure I understand that. 1. The app knows it is Biontech,
> Moderna, Astra-Z 2. the app noticed no second stab, 3. The app
> concludes that was a case of a recovered person?? What's about the
> szenario the person just forgot to take the second stab or had a too
> strong reaction or whatever the reason is. Surely there must be
> something else, say upload a certificate that you had recovered. That
> is a crucial information that is missing

> Okay, I will explain it the best way I can.
> Normally, when you receive your first shot of Biontech, Moderna or
> AstraZeneca, you get a certificate which says "1/2" (one dose out of
> two planned doses).
> If a recovered person gets vaccinated with Biontech, Moderna or
> AstraZeneca, they get a certificate "1/1" (one dose out of one planned
> doses). Now the app notices: "Oh, this vaccine normally requires two
> doses at the end, but here we have certificate which only requires one
> dose at the end. This person must be recovered"). Do you understand?

I see, now I understand! This was the crucial information I was missing. Thanks very much

> Now to the problem: If a non recovered person receives the Johnson &
> Johnson vaccine, they get a certificate "1/1" (one dose out of one
> planned doses).
> And if a recovered person gets the Johnson & Johnson vaccine, they also get a certificate "1/1" (one dose out of one planned doses). 
> So now the app has no way to tell whether this person was just
> vaccinated as planned or if the person was recovered before. So,
> everybody sees the 14 day countdown.


> Now clearer? 

Very much so. But don't you think, coming back to the original issue, that this information (or better said a link) should be made available in the News? Maybe there are more users like me, having received Johnson, and then  being confused

Regards

**Comment by Ein-Tim** [comment]
@ouboub 

> But don't you think, coming back to the original issue, that this information (or better said a link) should be made available in the News? Maybe there are more users like me, having received Johnson, and then being confused 

Yes I think so, however, this was clearly stated in the blog post and as we have freedom of press here in Germany, there is no way for us to influence the news in any way. I wish we could make it clearer in the media anyhow, but I fear that's not possible (despite from getting in touch with dpa, etc.)

**Comment by ouboub** [comment]
>>> "T" == Tim  ***@***.***> writes:

> @ouboub 
>> But don't you think, coming back to the original issue, that this
> information (or better said a link) should be made available in the
> News? Maybe there are more users like me, having received Johnson, and
> then being confused

> Yes I think so, however, this was clearly stated in the blog post and
> as we have freedom of press here in Germany, there is no way for us to
> influence the news in any way. I wish we could make it clearer in the
> media anyhow, but I fear that's not possible (despite from getting in
> touch with dpa, etc.)

I think we have a misunderstanding here: by News I did not mean the press (sorry in free software projects there is always a NEWS file of sorts). I meant the section 

New Features in the App.

The information there is not clear.

The blog you quoted is a bit better but still some background information is missing and that is why I was confused.

My suggestion is to add a link to website that explains the problem, as you just did.

**Comment by Ein-Tim** [comment]
@ouboub 

Ah, okay, yes, I understood you wrong, sorry 😅
I think in general it would make sense to add a link to the blog post which announces the new version to the "New Features" screen in the app. 
I've already opened a wishlist issue for this: https://github.com/corona-warn-app/cwa-wishlist/issues/513

**Comment by Ein-Tim** [comment]
@ouboub 

Meanwhile version 2.10 of the CWA has been released, so can this issue be closed?

**Comment by ouboub** [comment]
>>> "T" == Tim  ***@***.***> writes:

> @ouboub 
> Meanwhile version 2.10 of the CWA has been released, so can this issue be closed? 

But has the issue been resolved? I mean has the information a bit updates and it is now clearer than before?

**Comment by Ein-Tim** [comment]
@ouboub I'm not sure whether I understand you correctly, it doesn't make sense to change something reg. version 2.9 anymore, the current version is 2.10.

**Comment by ouboub** [comment]
>>> "T" == Tim  ***@***.***> writes:

> @ouboub I'm not sure whether I understand you correctly, it doesn't
> make sense to change something reg. version 2.9 anymore, the current
> version is 2.10.

Ah, ok, I am acquainted with News files (information that accumulate
information), so I understand that version 2.10 does not contain anymore
that information.  If that is the case the issue can be closed, of course.

**Comment by Ein-Tim** [comment]
@ouboub 

Yes, version 2.10 doesn't contain this information anymore. 

You can either close it yourself or @dsarkar can do it.

**Comment by ouboub** [comment]
Not any longer relevant since the actual version is 2.10
