### ISSUE TITLE
Different blue tone as background of certificates

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#3493]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone XR
- iOS version: 14.7.1
- App version: 2.9.0

## Describe the bug

The app shows different tones of blue in the background of certificates, independently of the validation status of the certificate or the type of certificate. 

| Blue tone one | Blue tone two | Blue tone three |
|---|---|---|
| <img src="https://user-images.githubusercontent.com/67682506/132536367-9107c7eb-3b3a-4085-934d-ded40f96e4b4.PNG" width="300"> | <img src="https://user-images.githubusercontent.com/67682506/132536676-af2e0f8f-da24-42f5-9ed6-0840ade22779.PNG" width="300"> | <img src="https://user-images.githubusercontent.com/67682506/132536888-daa7e36d-266b-49d2-b106-ca9d4e2b4f37.PNG" width="300"> |
| <img src="https://user-images.githubusercontent.com/67682506/132536390-602b3e2f-1fbe-4d9b-b093-0ae8a82b716c.jpg" width="300"> | <img src="https://user-images.githubusercontent.com/67682506/132536699-36cf8901-dc8c-4664-8dbd-d86313cc7c12.PNG" width="300"> | <img src="https://user-images.githubusercontent.com/67682506/132536897-3c724a29-2466-4b9b-83e5-b22d76d96fa3.PNG" width="300"> |
| <img src="https://user-images.githubusercontent.com/67682506/132536406-e8ca12e5-ce4e-4cd0-8ff7-cc81d8de5918.PNG" width="300"> | | |

## Steps to reproduce the issue

Add multiple certificate to the Corona-Warn-App.

## Expected behaviour

All certificates should have the same tone of blue in the background.

**Comment by mlenkeit** [comment]
@Ein-Tim that's a feature 😉  The idea is to help visually distinguishing certificates if you have certificates of multiple people in the app. There are three different shades of blue. The colors start repeating with the fourth certificate.

**Comment by Ein-Tim** [comment]
@mlenkeit 

Ah thanks! Interesting Feature & nice to know! 

Closing as answered (a fix is not necessary as this is intended).
