### ISSUE TITLE
Merge `release/2.9.x` branch into `main`

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#3494]
## Avoid duplicates
* [X] This enhancement request has not already been raised before
* [X] Enhancement request is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)
* [X] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation
https://github.com/corona-warn-app/cwa-app-ios/tree/main is multiple versions out of date.

## Suggested Enhancement
Merge the latest changes (https://github.com/corona-warn-app/cwa-app-ios/tree/release/2.9.x) into https://github.com/corona-warn-app/cwa-app-ios/tree/main.

## Expected Benefits
https://github.com/corona-warn-app/cwa-app-ios/tree/main is up to date with the latest release branch. This was how it was handled before. 

Ping @marcussc, would you quickly like to do this? There shouldn't be any merge conflicts so it's really just pressing a button 🙂

**Comment by marcussc** [comment]
Done 🥳

**Comment by Ein-Tim** [comment]
Thanks!
