### ISSUE TITLE
Enable third party developers

### ISSUE THREAD

**Issue by holtwick** [corona-warn-app/cwa-app-ios#35]
Congratulations on the great work done so far!

As an interested third party contributor I ran into difficulties getting the app to run out of the box. Two issues were the reason:

1. The required entitlements `com.apple.developer.exposure-notification` are not easily accessible for common developers without an official background, see https://developer.apple.com/documentation/exposurenotification
2. After the "onboarding" the activation check for the exposure manager is mandatory

I was able to workaround both:

1. I ran the app in the simulator, which does not require the entitlement
2. For the actual device I removed the entitlements
3. I commented out the check

In order to allow more participation it would be great to have some of these settings for DEBUG builds already in place.

I'll provide a PR for allowing to skip the exposure check when running in the simulator.

Good luck for your work! And stay healthy.

**Comment by ChristianKienle** [comment]
Your PR has already been approved by myself. I like the idea to make it easier for other developers to join the development efforts.

**Comment by holtwick** [comment]
Awesome, thanks! I really appreciate that the work is going on weekends as well ;)

Regarding the entitlements I'd suggest to add another **Configuration** and leave out the entitlements for it. It should have a clear name like "DebugWithoutExposureAPI". Of course a preset **Schema** for this configuration would be nice as well. What do you think?

![CleanShot 2020-05-31 at 09 43 22@2x](https://user-images.githubusercontent.com/49557/83347228-e5095b80-a323-11ea-9791-85ae000b8edf.png)

**Comment by ChristianKienle** [comment]
> Awesome, thanks! I really appreciate that the work is going on weekends as well ;)
> 
> Regarding the entitlements I'd suggest to add another **Configuration** and leave out the entitlements for it. It should have a clear name like "DebugWithoutExposureAPI". Of course a preset **Schema** for this configuration would be nice as well. What do you think?
> 
> ![CleanShot 2020-05-31 at 09 43 22@2x](https://user-images.githubusercontent.com/49557/83347228-e5095b80-a323-11ea-9791-85ae000b8edf.png)

Thanks for this great idea. @inf2381 is already on it. 😋

**Comment by inf2381** [comment]
Please have a look at #43 😁
