### ISSUE TITLE
Where did the iOS app go?

### ISSUE THREAD

**Issue by justin-varner** [corona-warn-app/cwa-app-ios#3506]
## Issue

The Corona-Warn app is nowhere to be found on the US Apple iOS App Store and the link from https://www.coronawarn.app/en/ just displays a blank white page. 

How does one install this app on an iPhone...

**Comment by Ein-Tim** [comment]
@justin-varner 

The app is not in the US App Store, where you ever able to download it from there?

**Comment by justin-varner** [comment]
I have not been able to download the app at all. It is missing from the app store completely. 

I wasn't sure if Apple temporarily yanked it or if I needed to have a German IP to access (I can use a VPN for this but that's besides the point). 

We'll be traveling to Germany in a few weeks and wanted to get out ahead of this but if that's not the intent then we'll just have to wait until we arrive.

**Comment by Ein-Tim** [comment]
@justin-varner 

You can't download the app with an US AppleID, either you change your region in the current AppleID you have, or you create a new one with region set to Germany.

Related issue: https://github.com/corona-warn-app/cwa-wishlist/issues/41

**Comment by jucktnich** [comment]
You can use an app from some other EU countries, some are available in the US App Store. This wouldn't be an optimal solution, but better than nothing.

**Comment by justin-varner** [comment]
Thanks for the information and apologies for the duplicate issue. Closing this one out.
