### ISSUE TITLE
CWA QR-Code certificates not scalable with check-apps

### ISSUE THREAD

**Issue by merlinseeling** [corona-warn-app/cwa-app-ios#3513]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 12 and others
- iOS version: iOS 14.7 - iOS 15
- App version: 2.8 - 2.9.X

## Describe the bug

In the Zertifikat

**Comment by Ein-Tim** [comment]
Hi @merlinseeling 

Did you close this by accident? If yes, either reopen this issue or just create a new one.

**Comment by merlinseeling** [comment]
I just started writing the issue and accidentally pressed ENTER... I'm writing a new one...

**Comment by Ein-Tim** [comment]
@merlinseeling 

Okay 👍

Thank you!
