### ISSUE TITLE
Statusbar is not visible while requesting a test certificate

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#3520]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone XR
- iOS version: 14.7.1
- App version: 2.9.0

## Describe the bug

The status bar (time, signal strength, battery) is not visible while requesting an EU digital COVID test certificate.

The red line shows where the status bar should be. 

<img src="https://user-images.githubusercontent.com/67682506/133219267-c7947961-b93b-4298-ae8f-0dc8395bd1d9.jpeg" width="300">

## Steps to reproduce the issue

1. Open the Corona-Warn-App
2. Register a rapid antigen test in the app
3. Request a test certificate 
4. See the missing status bar

## Expected behaviour

Status bat should be visible.

## Possible Fix

I guess the color of the status bar stays black although the background is black too.

---
Internal Tracking ID: [EXPOSUREAPP-9453](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9453)

**Comment by dsarkar** [comment]
@Ein-Tim Thank you: Internal Tracking ID: [EXPOSUREAPP-9453](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9453).

**Comment by Ein-Tim** [comment]
This issue still exists. I imagine this to be an easy fix, @dsarkar could you maybe ask the developers to include a fix in version 2.24?

**Comment by dsarkar** [comment]
@Ein-Tim FYI, still reproducible, however, following behaviour observed: I tested twice on an iPhone SE, CWA 3.1.0 (1). First time status bar visible, second time not visible, see left and right screenshots, respectively. 
![image](https://user-images.githubusercontent.com/1409741/216373414-561ca267-65c3-4e85-8a9d-fd23d045334e.png)

The difference was that on the first try the app was not active, i.e. could not access ENF, which led to an ENerrorDOmain 14 notification  before the "Request Test certificate"-Screen (above) was shown: 
![image](https://user-images.githubusercontent.com/1409741/216373494-50c50f2f-c531-41ef-9084-cea14b0f3166.png)

Dev team is looking at it.

**Comment by Ein-Tim** [comment]
This would have been an issue that I'd close now, but as @dsarkar wrote that the development team is looking into it, I'll leave it open for the time being.

**Comment by 30mar** [comment]
will set to obsolete as the effect is only until  31.4.2023
