### ISSUE TITLE
iOS Setting text says „Corona-Warn-App-App öffnen“

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#3533]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone XR
- iOS version: 14.8
- App version: 2.9.0

## Describe the bug

The iOS settings do not use the short form „Corona-Warn“ but „Corona-Warn-App“. 
This leads to the problem that the settings show a button „Corona-Warn-App-App öffnen“.

## Steps to reproduce the issue

(language set to German)

1. Open „Einstellungen“
2. Navigate to „Begegnungsmitteilungen“
3. Click on „Aktive Region“
4. Click on „Corona-Warn-App“
5. See the button with the text „Corona-Warn-App-App öffnen“.

## Expected behaviour

The button should say „Corona-Warn-App öffnen“.

## Possible Fix

This probably has to be fixed by Apple?

**Comment by jucktnich** [comment]
You could try to name the app only Corona-Warn, this would fix it.

**Comment by Ein-Tim** [comment]
@jucktnich 

The app itself is called Corona-Warn (name on the home screen, in the settings, etc.). Only the app in the Store is called Corona-Warn-App. The settings seem to use the name from the App Store.

**Comment by jucktnich** [comment]
@Ein-Tim i think you can alter the name for different places. If the Exposure Notification has its own name (I think so) it would be possible.

**Comment by ndegendogo** [comment]
I see this on my iPhone 8 (cwa 2.9.0 / iOS 14.4.1 / German language settings).
I don't see this on my iPhone 6 (cwa 2.9.0 / iOS 12.5.3 / English language settings).

**Comment by ndegendogo** [comment]
@Ein-Tim I assume you cannot reproduce this on the simulator, as the true ENF is missing there?

A good place to investigate if cwa can do anything would be the app configuration files (plist and their like).
I am afraid this is to be done by SAP development team, as only they see the effect with the true ENF and/or true devices; so they are the only ones that are able to test this ...

**Comment by ndegendogo** [comment]
> I don't see this on my iPhone 6 (cwa 2.9.0 / iOS 12.5.3 / English language settings).
And I see this on the same iPhone 6 with cwa 2.9.0 / iOS 12.5.3 as soon as I switch to German language.

*This is a strong indication that the root cause is an inconsistency somewhere in the localized texts / strings and under control of cwa*

**Comment by dsarkar** [comment]
@Ein-Tim @ndegendogo @jucktnich Thanks. Internal Tracking ID: [EXPOSUREAPP-9467](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9467)

**Comment by ndegendogo** [comment]
Today I checked again. It now shows consistently "Corona-Warn-App App" on both my devices, in both languages (German and English).

cwa 2.13.1 / iOS 14.4.1 / iPhone 8
cwa 2.12.1 / iOS 12.5.5 / iPhone 6

**Comment by ndegendogo** [comment]
![8B9AE239-4DD8-4053-942C-2FBEB09C6F72](https://user-images.githubusercontent.com/6118267/140623954-8cf88720-3ed7-4d69-9132-16ecf37ffa61.png)

**Comment by Ein-Tim** [comment]
This issue still persists. @dsarkar If this is nothing that you can fix, just let me know and I will close this issue.

**Comment by dsarkar** [comment]
@Ein-Tim I got feedback: It seems there is nothing dev team can do about, since the screen is owned by Apple. The internla ticket was set to obsolete. Thanks. Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@dsarkar 

Thanks for the feedback. Closing this issue as not fixable by the CWA team.
