### ISSUE TITLE
Cleanup navigation items in the top bottom view controllers

### ISSUE THREAD

**Issue by ndegendogo** [corona-warn-app/cwa-app-ios#3547]
## Avoid duplicates
* [X] This enhancement request has not already been raised before
* [X] Enhancement request is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)
* [X] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation

View controllers that are used as top controller in a TopBottomViewController often use their parent's navigation item instead of their own, like `parent?.navigationItem.title = ...` This forces them to be aware of the context in which they are used (embedded in a top-bottom view controller or direct children of a navigation controller).
Since #3474 is resolved, this is no longer necessary. This code can now cleaned up, which improves encapsulation. 

## Suggested Enhancement

Replace patterns like `parent?.navigationItem.title = ...` with the more simple and better `navigationItem.title = ...` for all controllers embedded as the top view controller of a top-bottom view controller.

## Expected Benefits

Improve quality of the code. Cleaner usage of the navigation items. Better encapsulation.

Note: I would volunteer to support you with this, at least for those which I can test (I am using the simulator).

---
Internal Tracking ID: [EXPOSUREAPP-9599](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9599)

**Comment by ndegendogo** [comment]
I have submitted a first PR #3548 for the DataDonationViewController as an example.

@dsarkar @heinezen could you please label it? - Thanks!

**Comment by ndegendogo** [comment]
@dsarkar @heinezen please label also PR #3580 - thanks!

**Comment by dsarkar** [comment]
Thanks @ndegendogo for another PR!

**Comment by ndegendogo** [comment]
@dsarkar @heinezen I have submitted another PR #3630 - please apply the labels. Thanks!

**Comment by ndegendogo** [comment]
I have submitted still another PR #3644 on this ticket
@dsarkar @heinezen would you please be so kind and apply the labels? Thanks!

**Comment by ndegendogo** [comment]
All PR are merged and available in the latest dev branch (release/2.13.x).
Closing as implemented.

**Comment by dsarkar** [comment]
@ndegendogo Many thanks for all the PRs!
