### ISSUE TITLE
Are notifications from CWA flagged as "Time Sensitive" (iOS 15 feature "Focus")?

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#3559]
## Avoid duplicates
* [X] Question is not already answered in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Question is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Question has not already been asked in another issue

## Your Question
iOS 15, which has been released yesterday, added a new feature called "Focus" (More infos what it does, etc. [here](https://www.macrumors.com/search/?s=How+To+Focus)).
There is the possibility to silent all notifications until the focus mode is turned off again.
However, one can either allow apps individually **and** there is the option to also allow all notifications from "Time Sensitive" apps. 

1. Are notifications from Corona-Warn-App "Time Sensitive"? 
	I'd argue yes, if the user had a high risk contact the user should be informed as fast as possible.
	- If they are **not** considered as "Time Sensitive": Why not? Is there some regulation from Apple what is "Time Sensitive"? Is there even an option for developers to flag their notifications as "Time Sensitive" or is this something which iOS does?
2. Are notifications from Corona-Warn-App already flagged as "Time Sensitive"?
	- If **yes**: Which notifications? All or only the ones which inform the user about a high risk contact?
	- If **no**: Do you plan to do so in a future release?

**Update:** No, notifications from CWA aren't currently consider as "Time Sensitive", see https://github.com/corona-warn-app/cwa-app-ios/issues/3559#issuecomment-924346685.

---
Internal Tracking ID: [EXPOSUREAPP-9690](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9690)

**Comment by jucktnich** [comment]
A notification about a high risk should maybe even get flagged as critical. (Cause its health related)

**Comment by Ein-Tim** [comment]
@jucktnich 

Thanks for answering! 

Now the question whether CWA already flags its notifications as "Time Sensitive" or if it's planned to implement this.

**Comment by Ein-Tim** [comment]
I found the answer (very well hidden) in the iOS settings: 

<img src="https://user-images.githubusercontent.com/67682506/134240431-211a91e5-2c77-45d6-b49f-e5eac711256e.jpeg" width="300">

So notifications from CWA are not considered as Time Sensitive at the moment.

Now the last remaining question is:

**Is it planned to change this?** Do you plan to flag the high risk notifications from CWA as Time Sensitive?

**Comment by Ein-Tim** [comment]
@thomasaugsten Maybe you could give us a little hint? Is it planned to mark the increased risk notifications as time sensitive?

**Comment by thomasaugsten** [comment]
This is in discussion at the moment

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-9690](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9690)

**Comment by Ein-Tim** [comment]
@thomasaugsten 

What was the result of the discussion?

**Comment by thomasaugsten** [comment]
This is at the moment postponed because other more important features

**Comment by Ein-Tim** [comment]
@thomasaugsten 

Okay, that's understandable.

Anyone knows how much work it is to set notifications from an app as time sensitive? 
Because if it's not too complicated the community could maybe provide a PR for this?

**Comment by thomasaugsten** [comment]
It is not complicated at all it is only one line

**Comment by jucktnich** [comment]
@Ein-Tim just watch the following video: https://developer.apple.com/wwdc21/10091

**Comment by Ein-Tim** [comment]
Thanks @jucktnich

**Comment by Kloenk** [comment]
I think the discussion if it is `time-sensitiv` or `critical` should be considered before implementing it. Critical would need an extra entitlement which has to manually be assigned to the app by apple.

**Comment by Ein-Tim** [comment]
@Kloenk 

I, personally, would not suggest to mark notifications as `critical`, as I don't think anyone would be too happy being woken up by the CWA in the middle of the night.

**Comment by Kloenk** [comment]
Okay, Working on it. Time sensitiv compiles, but I'm currently trying to figure out how to test it if it works.

**Comment by Ein-Tim** [comment]
<img src="https://user-images.githubusercontent.com/67682506/146814971-15f49659-15ae-4b11-9efb-ffae28642c43.jpeg" width="300">

This has been implemented in version 2.15, thanks to @Kloenk for providing the PR! 

Closing as implemented & answered.

**Comment by dsarkar** [comment]
@ein Thanks for following up.
