### ISSUE TITLE
UI glitch after certificate check

### ISSUE THREAD

**Issue by ndegendogo** [corona-warn-app/cwa-app-ios#3560]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 8
- iOS version: iOS 14.4.1
- App version: cwa 2.9.1 (1)

## Describe the bug

After a certificate check, the large title of the view is corrupted for a short time.

## Steps to reproduce the issue
Precondition: Have a certificate scanned.

Steps: 
- from the 'Certificates' tab select your certificate
- press button "check validity" and get the screen with the country selection dialog
- select a country, press button 'check' and watch the title closely
- the result screen slides in from the right side. Its title overlays with the title of the previous screen.

## Expected behaviour
Smooth animation between the screens with uncorrupted title

## Additional context

It is not easy to obtain a screenshot, but I succeeded 😎 

Note: I have a suspicion on the root cause and volunteer for the initial analysis (and, hopefully, a PR)
Edit: added screenshot

![IMG_1257](https://user-images.githubusercontent.com/6118267/134407228-e4854a44-70af-491f-a733-b0b1d2c01fe0.PNG)

----
Internal Tracking-ID: [EXPOSUREAPP-9768](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9768)

**Comment by ndegendogo** [comment]
https://user-images.githubusercontent.com/6118267/134417995-c172d77d-afbe-496d-8c42-41ff8e01d83a.mp4

**Comment by dsarkar** [comment]
FYI PR https://github.com/corona-warn-app/cwa-app-ios/pull/4661

**Comment by Ein-Tim** [comment]
@ndegendogo 

Could you please check if this issue has been fixed in version 2.25?

**Comment by ndegendogo** [comment]
closing as fixed
