### ISSUE TITLE
How to test the screens of certificates tab with simulator?

### ISSUE THREAD

**Issue by ndegendogo** [corona-warn-app/cwa-app-ios#3567]
## Avoid duplicates
* [x] Question is not already answered in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Question is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Question has not already been asked in another issue

## Your Question

* Source File:
* Line(s):
* Question:

I am testing and debugging with the community build on the simulator.
Till recently I was able to obtain a short-time fake certificate by pressing the "Add certificate" button, and this allowed me to access many (all?) screens of the Certificates tab.
However, on the newest development branch (release/2.12.x) this trick does no longer work. I have yet to debug this, but my current suspect is a side effect of the refactoring and harmonizing of QR code scanning.

Questions:
1) Is there currently a way to test the mentioned screens on the simulator? How do the developers do this? I am very interested to learn more about their tricks.
2) Assuming this was indeed a side effect of the refactoring: Was this intentional, or by accident? Would it harm to bring back this trick again? Are the developers even aware of this? Are they maybe already working on a solution to bring it back again? *(because in that case I could just stop to analyse this and wait for their solution)*

**Comment by dsarkar** [comment]
@marcussc @pascal-brause Maybe you can help out here? Thanks.

**Comment by Ein-Tim** [comment]
Related to #2907.

**Comment by ndegendogo** [comment]
Maybe I could try to extend the developer menu, and bring back the "fake certificate" that was formerly the result of the "fake scanning" on the simulator?

@Ein-Tim what do you think?

**Comment by Ein-Tim** [comment]
@ndegendogo This would be a great addition! But this sounds like a lot of work to me, so if you don't want to do this or don't have the time to do this, this would also be ok.

If you decide to give it a try, let me know when I could support you somehow (Slack DM)!

**Comment by ndegendogo** [comment]
🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉
***YES - the new universal scanner can scan the QR code from a photo 🎉🎉🎉 and that is the solution 🎉🎉🎉***

How to get a (valid) certificate into the simulator:
* make a photo of the QR code (e.g. a screenshot of cwa with your original health certificate) 😁 then export this photo to your MAC, and drag&drop it to your simulator.
* start simulator with cwa on newest development branch (release/2.12.x)
* select the new universal QR code scanner tab, cancel the selection menu and press the button 'open file'
* import your code from photos

**Comment by ndegendogo** [comment]
closing as answered - and even fixed 👍😁

**Comment by dsarkar** [comment]
@ndegendogo Many thanks for the feedback.
