### ISSUE TITLE
Prio: App crashes when "Check Validity" button is clicked without active internet connection

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#3573]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone XR
- iOS version: 15.0
- App version: 2.10.1

## Describe the bug

The app crashes instantly when the "Check Validity" button on a certificate is clicked and the device is not connected to the internet.

## Steps to reproduce the issue

1. Open the Corona-Warn-App
2. Turn off WLAN and Mobile Data
3. Click on "Certificates"
4. Select a certificate
5. Press "Check Validity"
6. See the app crash

## Expected behaviour

An error message should be shown, like in the previous releases.

---
Internal Tracking ID: [EXPOSUREAPP-9638](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9638)

**Comment by Ein-Tim** [comment]
@dsarkar I consider this as a high priority item. Could you mirror it to JIRA asap? Maybe a fix can be included in the upcoming 2.10.2 hot fix? 

Thank you!

**Comment by thomasaugsten** [comment]
Will be included

**Comment by Ein-Tim** [comment]
PR #3576 fixes this issue. It's merging into `release/2.10.x` which confirms that this will be included in a hot fix version.

**Comment by Ein-Tim** [comment]
@dsarkar 

Feel free to add a `Fix 2.10.2` label here.

**Comment by Ein-Tim** [comment]
Confirm fixed in version 2.10.2. 

Closing as fixed.
