### ISSUE TITLE
Can‘t select country for validity check

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#3577]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone XR
- iOS version: 15.0
- App version: 2.10.1

## Describe the bug

After I yesterday reported the issue that the app crashes when it's offline and the "Check validity" button is clicked, I now can't select any countries for the validity check anymore:

<img src="https://user-images.githubusercontent.com/67682506/134667657-19099a5c-e383-4033-963f-dd5a7a377daf.png" width="300">

## Steps to reproduce the issue

1. Open the Corona-Warn-App without active internet connection
2. Click on "Certificates"
3. Select a certificate 
4. Click "Check Validity" 
5. See the app crash
6. Connect to the internet
7. Perform steps 2 - 4
8. Click on the name of the country which is currently selected
9. See the empty menu appear

## Expected behaviour

It should be possible to select other countries.

**Comment by Ein-Tim** [comment]
@thomasaugsten I'd argue this is also worth to be included in the hot fix (if that's reproducible).

**Comment by thomasaugsten** [comment]
Can you recheck please

**Comment by Ein-Tim** [comment]
@thomasaugsten 

Works again! Thank you! 

Closing as fixed.
