### ISSUE TITLE
Unit tests: NavigationControllerViewScrollingTest is reported as flaky

### ISSUE THREAD

**Issue by ndegendogo** [corona-warn-app/cwa-app-ios#3583]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Simulator
- iOS version:
- App version:

## Describe the bug

Circle CI reports the test cases of NavigationControllerViewScrollingTest as 'flaky', meaning they are not robust, and are failing sometimes randomly. See screenshots. 

## Expected behaviour

Unit tests should be robust.

## Possible Fix

The timing of the implementation is a bit guesswork, and seems too tight, especially on the simulator, where the unit tests are executed. 

## Additional context

<img width="1010" alt="Screenshot 2021-09-26 at 22 43 36" src="https://user-images.githubusercontent.com/6118267/134823800-a99e4adf-aec7-48e7-99b6-6486d28e3150.png">

<img width="977" alt="Screenshot 2021-09-26 at 22 45 47" src="https://user-images.githubusercontent.com/6118267/134823816-84ab162a-4664-42db-9874-6df36428d9ac.png">

---
Internal Tracking ID: [EXPOSUREAPP-9661](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9661)

**Comment by ndegendogo** [comment]
I did a series of test executions of the 7 test cases of NavigationControllerViewScrollingTest on a simulator (Xcode 13) for iPhone 13 Pro Max with iOS 15.0. About 10 percent of the runs had one failing test. This confirms that the tests are indeed unrobust.

**Comment by ndegendogo** [comment]
I have submitted a PR #3584 with an improved timing.

@dsarkar @heinezen please apply the labels - thanks!

**Comment by dsarkar** [comment]
Good morging @ndegendogo, Thanks: Internal Tracking ID: [EXPOSUREAPP-9661](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9661)

**Comment by ndegendogo** [comment]
PR is merged, the fix is available in branch release/2.12.x
Closing the ticket.

**Comment by dsarkar** [comment]
Thank you @ndegendogo!
