### ISSUE TITLE
Community build: Developer Menu "Test keys" is broken

### ISSUE THREAD

**Issue by ndegendogo** [corona-warn-app/cwa-app-ios#3599]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Simulator for iPhone 8
- iOS version: Simulator for iOS 14.3
- App version: development / Community build at commit b58c1637b751c256a7e16bbba618adfd30b57b94 (Sept 15)

## Describe the bug

In the Community build, the developer menu "Test keys" is broken. The MockENManager does not return such keys, but reports an error code instead. And the error message lacks a button to confirm it, so everything is stuck. 

## Steps to reproduce the issue

* start cwa community build on the simulator
* from the Home tab, tap 3 times to start the developer menu
* select the first entry "Keys"
* press button "Test Keys"
* get an error message (see screenshot)

## Expected behaviour

no error message
~2) even in case of error message, there should be a button so I can continue operation without restart~

*Edit: As @thomasaugsten correctly pointed out, it is a fatal error, this menu is only working if you have the entitlement for ENF, the alert was intentionally setup as "error", and the expectation to continue operation after such an error message is wrong.*

## Additional context

![Simulator Screen Shot - iPhone 8 - 2021-09-28 at 22 47 27](https://user-images.githubusercontent.com/6118267/135163644-58f9a4f4-1595-4a8a-b13a-4954aed3e305.png)

---
Internal Tracking ID: [EXPOSUREAPP-9711](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9711)

**Comment by ndegendogo** [comment]
I volunteer to analyse this in more detail

**Comment by thomasaugsten** [comment]
You need the developer entitlement to access this method

**Comment by ndegendogo** [comment]
The guard clause in MockENManager.getDiagnosisKeysImpl is wrong.
The result is preconfigured for success, so error is nil.

**Comment by ndegendogo** [comment]
> You need the developer entitlement to access this method

@thomasaugsten thanks, of course you are right.
Still I expect that the mock at least not crashes in this case.
Let me try to fix / improve this (and you can still reject my PR if it is nonsense altogether)

**Comment by ndegendogo** [comment]
@dsarkar @heinezen I have submitted a PR #3600 to improve this - please apply the labels.
Thanks!

**Comment by ndegendogo** [comment]
Closing the ticket. The fix is merged and available on the current development branch. No need to wait for the release, as this is related to a development-only feature.

**Comment by dsarkar** [comment]
@ndegendogo Thanks for reporting and providing a fix!
