### ISSUE TITLE
"Warn On Behalf" screen has lost its title (regression)

### ISSUE THREAD

**Issue by ndegendogo** [corona-warn-app/cwa-app-ios#3649]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 8
- iOS version: 14.4.1
- App version: 2.10.2 (0)

## Describe the bug

The screen "Warn on behalf" has no title.
This is a regression.

## Steps to reproduce the issue

- select "event planning" from the home tab
- select "warn on behalf" from the 3-dot menu
- see the screen without a title

## Expected behaviour

a title should be shown

## Possible Fix

Root cause is the order of setting up the title and creating the navigation items. *This is indeed tricky...*

## Additional context

Screenshot see below.
Again, a side effect of the refactoring #3474 👹
I have yet to confirm if this issue is still present with the latest source.

**Suspecting that also ExposureSubmissionCheckinsViewController is affected.**

---
Internal Tracking ID: [EXPOSUREAPP-9826](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9826)

**Comment by dsarkar** [comment]
Good morning @ndegendogo, thanks for reporting. Internal Tracking ID: [EXPOSUREAPP-9826](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9826)

**Comment by ndegendogo** [comment]
@dsarkar please ask the devs.
I can offer a PR, but not before this evening (I am going to work now 😅)
Maybe the devs are faster; maybe they even manage to get a fix into the 2.12; but maybe they are busy with higher-priority tasks.

**Comment by ndegendogo** [comment]
![1BE8A904-D85F-4132-A346-5AA56CDE08C9](https://user-images.githubusercontent.com/6118267/136160872-4a07b033-5f31-4687-a116-bb9eeeabb15a.png)

**Comment by dsarkar** [comment]
@ndegendogo ok, stand by, I informed dev team.
