### ISSUE TITLE
Onboarding: "If you are diagnosed with coronavirus" screen appears twice

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#3663]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 6s
- iOS version: 15.0.1
- App version: 2.11.1

## Describe the bug

The "If you are diagnosed with coronavirus" screen is pushed twice in the onboarding:

https://user-images.githubusercontent.com/67682506/136430368-91281e22-49dd-47a0-b1de-ab5fca53127f.mov

## Steps to reproduce the issue

**This is also reproducible on my Emulator!**

1. Delete the Corona-Warn-App (you have to delete it, an in-app reset is not sufficent)
2. Open the Corona-Warn-App
3. Click on "Let's get started"
4. Click on "Next
5. Click on "Activate Exposure Logging"
6. In the pop up click on "Enable"
7. See that the screen "If you are diagnosed with coronavirus" is pushed twice

## Expected behaviour

Each screen of the onboarding should only appear once.

---
Internal Tracking ID: [EXPOSUREAPP-9926](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9926) duplicate of
Internal Tracking ID: [EXPOSUREAPP-8882](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8882)

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-9926](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9926) duplicate of
Internal Tracking ID: [EXPOSUREAPP-8882](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8882)

**Comment by Ein-Tim** [comment]
Can't reproduce anymore, seems fixed. Closing.

**Comment by dsarkar** [comment]
FYI PR https://github.com/corona-warn-app/cwa-app-ios/pull/4967
