### ISSUE TITLE
Why does the app show "There is news about your certificates" when the certificates are added via a QR code scanner other than the QR code scanner on the certificates tab?

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#3664]
## Avoid duplicates
* [X] Question is not already answered in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Question is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Question has not already been asked in another issue

## Your Question
Why does the app shows the note that there is news about your certificates when the certificate was added with e.g. the QR code scanner on the "Check In" tab? There aren't any news, the certificates were added, and not more. The red badge on the "Certificates" tab is fine, it informs the user that the certificates were added, but the text "There is news about your certificates" is wrong, as there aren't any news. Or am I overlooking something?

---
Internal Tracking ID: [EXPOSUREAPP-9925](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9925)

**Comment by dsarkar** [comment]
@Ein-Tim Stand by for an answer, please.
