### ISSUE TITLE
Number in red badge on certificate is not centered, red circle in the background is very small

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#3665]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 6s
- iOS version: 15.0.1
- App version: 2.11.1

## Describe the bug

The number in the red badge on a certificate is very small and it is nearly cut off, also the number is not really centered

Here's a screenshot:

![IMG_0010](https://user-images.githubusercontent.com/67682506/136439846-d267fb68-3583-4a9e-9b2f-1a5020b91d46.jpeg)

Here's a screenshot: 

## Steps to reproduce the issue

1. Add a certificate to the app but **not** through the QR code scanner on the "Certificates" tab but through the QR code scanner on the "Check In" tab
2. Click on the "Certificates" tab
3. See the text with the red badge "There is news about your certificates"

## Expected behaviour

The red circle shouldn't be that small, rather match the size of the badge on the "Certificates" tab. The number should be centered and not cut off. 

---
Internal Tracking ID: [EXPOSUREAPP-9914](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9914)

**Comment by Ein-Tim** [comment]
@ndegendogo 

> can you confirm that the 'crippled' appearance is related to the language setting?

Yes, confirm that.

**Comment by ndegendogo** [comment]
@Ein-Tim could you test this? - Thanks!

**Comment by Ein-Tim** [comment]
Thanks for the ping @ndegendogo!

I can confirm that the issue has been fixed in version 2.14.1.

Thanks for fixing! 

Closing.

**Comment by dsarkar** [comment]
@ndegendogo @Ein-Tim Thanks for report/fix/Feedback. Internal ticket set to CONFIRMED.
