### ISSUE TITLE
iPhone 13 mini: Animation for switch (People / Places) broken in contact diary day view

### ISSUE THREAD

**Issue by ndegendogo** [corona-warn-app/cwa-app-ios#3669]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 13 mini (simulator)
- iOS version: 15.0
- App version: latest on developer branch (branch release/13.x as of Oct 09)

## Describe the bug

For iPhone 13 mini: in the contact diary, the animation for the switch between People selection and Places selection is broken.
It does not animate the full height of the switch.

## Steps to reproduce the issue

- select tab "Journal"
- select a day
- see the People selection view
- switch to the Places selection view
- see the switch slide to the right; but the top of the switch does not slide

## Expected behaviour
The switch slides as a whole.

## Possible Fix

I noticed that DiaryDayViewController.segmentedControl is not created programmatically, but from a xib file.
Maybe this xib file needs an update for the screen size of iPhone 13 mini.

## Additional context

I am testing on the simulator, not on a true device. 
See screenshot and video.

![Simulator Screen Shot - iPhone 13 mini - 2021-10-09 at 11 45 48](https://user-images.githubusercontent.com/6118267/136653976-731701bf-ef45-4e0e-b987-4df1ca466f29.png)

**Comment by Schlaubischlump** [comment]
I'm unable to reproduce the error on my iPhone 13 mini running iOS 15, CWA 2.11.1(0). 

I noticed that the iOS 15 iPhone 13 mini Simulator has quite a few graphic issues. Maybe this only affects the simulator.
