### ISSUE TITLE
Notification missing after red risk check from foreground

### ISSUE THREAD

**Issue by ndegendogo** [corona-warn-app/cwa-app-ios#3675]
## Avoid duplicates
* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 8
- iOS version: 14.4.1
- App version: 2.11.1 (0)

## Describe the bug

Yesterday I opened cwa after returning home. It performed the risk check as usual - and the result was red!
However, I didn't see any notification with any warning.

## Steps to reproduce the issue

- open cwa
- see the risk check with red result
- get no notification

## Expected behaviour
A notification on a changed risk result, regardless if the risk check was performed from the background thread or performed while cwa was open.

## Additional context

---
Internal Tracking ID: [EXPOSUREAPP-9970](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9970)

**Comment by thomasaugsten** [comment]
It will not block the notification.

We had exposure check at
   "Timestamp" : "2021-10-11 09:15:38 +0200",
   "Timestamp" : "2021-10-11 05:12:52 +0200",
   "Timestamp" : "2021-10-10 21:38:01 +0200",
   "Timestamp" : "2021-10-10 10:42:08 +0200",
   "Timestamp" : "2021-10-10 10:31:57 +0200",
   "Timestamp" : "2021-10-10 05:19:44 +0200",

And you say first check with "Übereinstimmende Schlüssel" >0 was at 21:38:01 

When was you manual check/manual open of the app?

**Comment by ndegendogo** [comment]
> When was you manual check/manual open of the app?

I think it was about **2021-10-10 21:38** when I opened the app. The check was the first thing it did.

*Sorry for the misleading answer and the resulting confusion*

**Comment by ndegendogo** [comment]
@thomasaugsten So I will get the notification only if the app performs the first red check from background?
Maybe there is a misunderstanding / wrong expectation on my side?

Will I get a notification in the following scenarios:
(A) red check is performed while the app is closed ( = from the background)
(B) last time I was using the Journal tab before I closed the app; now I start the app and it performs the red check, triggered from startup, but I see only the Journal tab, and I have no clue that I should check also the Home tab.
(C) I keep the app open at the Journal tab for several hours, and it performs the red check triggered by the timer

**Comment by Ein-Tim** [comment]
@ndegendogo 

First when I read this issue I asked myself when you would want a push notification to be send, if the app's in foreground anyways.
But I think you bring up a valid point here:
If the app is opened on the contact journal tab (or on any other tab, besides from the start screen) and the app performs a risk check which finds an encounter with increased risk, the user has absolutely no clue that this happened.
AFAIK there is not push notification send if the app's open. 

So, this is definitely a flaw and should be fixed.
There are two solutions I could imagine for this:
1. Show a push notification to the user
2. Show a red badge on the "Start Screen" tab if the exposure check finds an encounter with increased risk

@thomasaugsten Any opinion on this? Do you see the problem here too (user potentially unaware of infection risk as app does not inform about increased risk encounter when opened on another tab than start screen)?

**Comment by Ein-Tim** [comment]
This was an actual problem for this user: https://twitter.com/neuesausdemnest/status/1462503966328201221?s=21

**Comment by thomasaugsten** [comment]
Ok the user is missing a notification when they manually opens the app and not in the Home Screen of the app. The app will switch to red but if you stay in Zertifikate Screen you will not see this.

**Comment by Ein-Tim** [comment]
@thomasaugsten 

Yes exactly. Will you bring this up so that this get's improved?

**Comment by ndegendogo** [comment]
> Ok the user is missing a notification when they manually opens the app and not in the Home Screen of the app.

- In the very early days this could not happen, because there was **only** the home screen, and the first thing a user saw was **always** their current risk status
- then the app was extended with many more functions, and the user interface restructured into several tabs (meanwhile 5 tabs). Still this was no issue, because the app opened always on the home tab.
- but then the UI was improved, so now the app **remembers** the state of the app, especially the tab, and even the scrolling position. **Since then it is very likely that you can miss the red status if you don't check actively.**

**Comment by ndegendogo** [comment]
I would appreciate very much a notification **in any case** as soon as the risk check turns red. Regardless if it was triggered from background, from opening the app regularly or by a "fast route", by a timer while the app was open, or even explicitely by the user pressing a button.

**Comment by thomasaugsten** [comment]
We created a story for this and will add this as soon as possible
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10683

**Comment by Ein-Tim** [comment]
#3956 is the fix for this.

**Comment by Ein-Tim** [comment]
@ndegendogo 

Would you like close this issue? The feature was implemented in the latest release.

**Comment by ndegendogo** [comment]
Closing as feature request is implemented.

**Many thanks to the developers for picking this up and for the implementation. I am very sure that the users of cwa will appreciate this very much and that it meets their expectations.**

*I did't test it - luckily I am green currently, and hope this will stay green for the next time* 🍀🍀

**Comment by dsarkar** [comment]
@ndegendogo Thanks for the proposal and your feedback!

**Comment by ndegendogo** [comment]
Just tested it ...... works exactly as expected!
Thanks again!

![BAAA2F12-79F0-41C5-AD03-4FB2EEFFFCB4](https://user-images.githubusercontent.com/6118267/151598060-56d563bb-c9cc-4879-a077-fc7d70a8f1f3.png)

**Comment by dsarkar** [comment]
@ndegendogo Thanks for your feedback! Forwarded to internal ticket.
