### ISSUE TITLE
Twitter Report: App deleted all contact journal entries

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#3680]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone SE (2020)
- iOS version: 15.0
- App version: 2.10.2

## Describe the bug

The app deleted all contact journal entries automatically.
All People & Places were deleted. 

There were two "special" happenings on the day this happened:

- When the CWA was opened, the phone was sometimes not connected to the internet at all or was connected to the internet through Danish cellular network (this doesn't seem like it's the reason for the behavior of the app).
- The phones disk space was nearly full, only ca. 500 MB were left (this could very well be the reason for the behavior of the app). 

 
## Steps to reproduce the issue

1. Close the Corona-Warn-App
2. Start to fill up your disk space until no more than 500 MB are available
3. Open the Corona-Warn-App
4. See that all contact journal entries are gone

## Expected behaviour

In case of low storage, the app shouldn't delete the contact journal store. 

## Additional context
Thanks to the Twitter user who reported this bug! 
Link to Twitter: https://twitter.com/martintaetzner/status/1447493086322610177?s=21

---
Internal Tracking ID: [EXPOSUREAPP-4952](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4952)

**Comment by Ein-Tim** [comment]
@dsarkar 

This happened independently of any updates.

**Comment by Ein-Tim** [comment]
Closing this issue in favor of https://github.com/corona-warn-app/cwa-app-ios/issues/3896.

**Comment by dsarkar** [comment]
FYI PR: https://github.com/corona-warn-app/cwa-app-ios/pull/4389
