### ISSUE TITLE
iPhone SE: first generation, option open file cannot be seen

### ISSUE THREAD

**Issue by ouboub** [corona-warn-app/cwa-app-ios#3703]
Hi

according to https://www.coronawarn.app/en/blog/2021-10-06-cwa-version-2-11/
the 2.11 version should have a open file option, as the screeshot shows, that is not the case for my 
iPhone SE first generation (Apple still provides iOS 15 for this device!
![SE](https://user-images.githubusercontent.com/5957203/137458324-56cfada5-75b6-45f1-8d24-d26109808354.png)

---
Internal Tracking ID: [EXPOSUREAPP-10037](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10037)

**Comment by Ein-Tim** [comment]
@ouboub 


Version 2.11 only includes the feature to scan QR codes from files under Android, version 2.12 will add this feature under iOS.
