### ISSUE TITLE
[a11y] Layout of 'warn on behalf' page is broken for extreme font sizes

### ISSUE THREAD

**Issue by ndegendogo** [corona-warn-app/cwa-app-ios#3709]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

Screenshots were created with:
- Device name: iPhone 12 / simulator (but all screen sizes are affected)
- iOS version: iOS 15 / simulator (but all iOS versions are affected)
- App version: current developer branch (branch = release/2.13.x as of Oct 17, commit = 584727) (but latest release 2.11. is affected as well)

## Describe the bug

With extreme a11y settings the layout of the page "Warn on behalf of others" is broken.
The descriptive text at the top can grow so much that it pushes the table of QR codes below the visible screen. Even the 'scan' button can be hidden. Of course you can scroll both in again, but you have to know.
The only visible button on this page is disabled, which is especially confusing.

## Steps to reproduce the issue

* close cwa, open the Settings / Accessibility / Display & Text Size / Larger Text
* enable Larger Accessibility Sizes
* select the largest font size (note: on smaller screens the same happens earlier)
* open cwa, select 'Event Planning' / three-dot-button / Warn for Others, and press the Continue button
* the explanation text fills the whole visible screen. The list of QR codes and the scanning button are not visible without scrolling. The button 'Continue' is visible but disabled. 

## Expected behaviour
Below the explanation on top of the screen, see a scrollable and selectable list of QR codes, and a button to scan another QR code.

## Possible Fix

* consider to shorten the very long explanation, and/or limit its size
* consider to hide the 'Continue' button as long as it is disabled

## Additional context

See example screenshots for iPhone 12 below.

![Simulator Screen Shot - iPhone 12 - 2021-10-17 at 16 59 40](https://user-images.githubusercontent.com/6118267/137633449-40108fa0-fd08-4d92-9ff3-b6e68b6a62c8.png)

![Simulator Screen Shot - iPhone 12 - 2021-10-17 at 17 00 02](https://user-images.githubusercontent.com/6118267/137633467-c45bad84-89ef-4f07-bdd0-da521d9ce744.png)

![Simulator Screen Shot - iPhone 12 - 2021-10-17 at 17 21 35](https://user-images.githubusercontent.com/6118267/137633813-6c6ceefd-8af7-4677-af5b-5df2baaa181f.png)

---
Internal Tracking ID: [EXPOSUREAPP-10243](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10243)

**Comment by ndegendogo** [comment]
Note: I found this issue while working on PR #3685. However, that PR will not fix it.

**Comment by Ein-Tim** [comment]
FYI: PR https://github.com/corona-warn-app/cwa-app-ios/pull/4591 will improve the situation here.

**Comment by 30mar** [comment]
Fixed in #4591
