### ISSUE TITLE
[CircleCI] ...doesn't run because of "unauthorised" error.

### ISSUE THREAD

**Issue by sebastianpicklum** [corona-warn-app/cwa-app-ios#372]
CircleCI doesn't run for #358 because it gives an "unauthorised" error:
https://app.circleci.com/pipelines/github/corona-warn-app/cwa-app-ios?branch=pull%2F367

Previous PRs from me passed CircleCI without any problem, like 
https://app.circleci.com/pipelines/github/corona-warn-app/cwa-app-ios?branch=pull%2F352

Can you manually start CircleCI for #358 and maybe have a look into the unauthorised-issue?

**Comment by inf2381** [comment]
I disabled SonarCloud until we come up with a solution.
