### ISSUE TITLE
Overlapping icons in PDF viewer (print certificates)

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#3731]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone XR
- iOS version: 15.0.2
- App version: 2.12.1

## Describe the bug

In the screen where the user can view the PDF before printing it, the buttons are overlapping:
![image](https://user-images.githubusercontent.com/67682506/138213289-fa85f081-7b0c-4e0c-a284-81425e3b9e28.jpeg)

## Steps to reproduce the issue

1. Open the CWA
2. Click on the "Certificates" tab
3. Click on a certificate or add one
4. Click on "More"
5. Click on "Display Print Version"
6. Click on "Continue"
7. See the broken layout on the top

## Expected behaviour

No overlapping icons.

## Additional information

It seems like the background of the icons on the PDF viewer screen is translucent, thus one sees the icons of the PDF viewer and the icons of the certificates detail view. 

---
 Internal Tracking ID: [EXPOSUREAPP-10179](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10179)

**Comment by Ein-Tim** [comment]
PR: #3904

**Comment by Ein-Tim** [comment]
Confirm fixed in version 2.15:
![IMG_D8D7277A797C-1](https://user-images.githubusercontent.com/67682506/146814582-ef76291e-a05e-4532-acd1-a13edcaadb3d.jpeg)

Closing this issue as fixed.

**Comment by dsarkar** [comment]
I will remark in the internal ticket, that the fix was confirmed by the community.
