### ISSUE TITLE
"QR Code" instead of "QR code" in multiple places in the English language version of the app

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#3792]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Not relevant
- iOS version: Not relevant
- App version: 2.13.1

## Describe the bug

In different places the app writes "QR Code" with an uppercase "C" instead of "QR code" with a lowercase "c".
Some places are:
- Warn for Others screen
- Universal QR code scanner (title)
- Check in screen
- Manage Your Tests screen ("Scan QR Code")

## Steps to reproduce the issue

Different

## Expected behaviour

"QR code" should be written with a lowercase "c" throughout the whole app. 

## Possible Fix

Change the text.

## Additional context

Let me know if a PR is welcome on this or if you would rather like to change this yourself so that the internal translation system does not get out of touch with "reality" 😅

CC @CV113

---
Internal Tracking ID: [EXPOSUREAPP-11165](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11165)

**Comment by larswmh** [comment]
Thanks for your report @Ein-Tim.
Internal Tracking ID: [EXPOSUREAPP-11165](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11165)

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
@Ein-Tim Do you know if Android is affected as well? Thanks.

**Comment by Ein-Tim** [comment]
@dsarkar 

Yes, seems like.

**Comment by Ein-Tim** [comment]
🙋🏻‍♂️ I'm working on a fix for this under iOS.

**Comment by Ein-Tim** [comment]
PR https://github.com/corona-warn-app/cwa-app-ios/pull/4451 provided.

**Comment by Ein-Tim** [comment]
PR #4551 closed, as this change should be done through a translation update provided by @service-tip-git

**Comment by larswmh** [comment]
@Ein-Tim 

This was internally set to obsolete. This is due to the capitalization guidelines. 

> Use sentence style for messages and all other sentence-like text on the user interface.
> Sentence style is your normal, everyday capitalization style. It is equivalent to using lowercase for all words, except for proper nouns and the first letter in a new sentence.
> 
> Use title case for all types of titles and labels on the user interface.
> Title case applies to: field labels, checkboxes, radio buttons; buttons, menu items; predefined entries in a dropdown list; titles of screens, tabs, and dialog boxes; table titles and their column and row headings; and so on
