### ISSUE TITLE
[UI] [Minor] Graphics glitch in certificate detail screen

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#3801]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 6s
- iOS version: 15.1
- App version: 2.13.1

## Describe the bug

There's a little graphics glitch in the certificate detail screen. Here are two screenshots, I put red circles around the glitch, so that everyone understands what I mean.

<img src="https://user-images.githubusercontent.com/67682506/140613293-72ba67d0-548a-4289-9856-c7d15dc16c14.jpeg" width="300" align= "center">
<img src="https://user-images.githubusercontent.com/67682506/140613308-2a1c40ae-92ef-4c39-bc78-9378b531e0dc.jpeg" width="300“ align: "center" >

## Steps to reproduce the issue

1. Open the app
2. Click on "Certificates"
3. Select a person
4. Scroll down to the very bottom
5. Select a certificate
6. See the glitch 

## Expected behaviour

No offset.

---
Internal Tracking ID: [EXPOSUREAPP-10827](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10827)

**Comment by larswmh** [comment]
Hi @Ein-Tim, thanks for your report. We have created an internal ticket and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-10827](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10827)

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode & this is only a minor issue, I don't expect it to be addressed anymore. I'm therefore closing this issue.
