### ISSUE TITLE
Align to Android: Deactivate possibility to check certificates against a date in the past

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#3839]
## Avoid duplicates
* [X] This enhancement request has not already been raised before
* [X] Enhancement request is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)
* [X] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation
In version 2.13.1 it is possible to check certificates against a date in the past under iOS.
Android does not allow to select a date in the past.

## Suggested Enhancement
Do not allow users to select a date in the past for checking their certificates against.

## Expected Benefits
1. Wrong results are shown less frequently (e.g. checking a certificate against a date before the issuance date of the certificate leads to the "Signature not valid" screen shown.
2. The user does not always have to select the current time but the app already sets this time as the default. 

---
Internal Tracking ID: [EXPOSUREAPP-10830](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10830) duplicate of
Internal Tracking ID: [EXPOSUREAPP-11633](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11633)

**Comment by larswmh** [comment]
Hi @Ein-Tim, thanks for your report. We have created an internal ticket and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-10830](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10830)

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
@Ein-Tim Internal ticket is a status "Analyzing", stand by , please.

**Comment by Ein-Tim** [comment]
PR: https://github.com/corona-warn-app/cwa-app-ios/pull/4559

**Comment by Ein-Tim** [comment]
This has been implemented in version 2.23.1.

Closing as implemented. Thanks!

**Comment by dsarkar** [comment]
@Ein-Tim Thanks for the feedback.

**Comment by Ein-Tim** [comment]
@dsarkar

Please reopen this issue, as it occurs again.

**Comment by dsarkar** [comment]
Good morning @Ein-Tim,

I cannot reproduce on iPhone 6s. Could you send a screenshot and technical details of your device? Thanks for your feedback.

**Comment by Ein-Tim** [comment]
@dsarkar I guess it's better to follow up in #4825, see my comment there.
