### ISSUE TITLE
Risk check from background not reliable

### ISSUE THREAD

**Issue by ndegendogo** [corona-warn-app/cwa-app-ios#3860]
## Avoid duplicates
* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 6
- iOS version: 12.5.5
- App version: 2.13.2

## Describe the bug

Today I checked my ENF logs and saw that the last risk check was more than 24 h ago.
I then opened the cwa and this triggered the risk check.
Note: I don't have a SIM card in that device (it is my secondary device), and through the day I don't have WLAN.
But at night I have WLAN coverage, and expect that the background process will trigger the risk check regularly while I have WLAN coverage, even if I don't open the app actively.

## Expected behaviour
Regular risk checks, triggered from background, even if I don't open the app.

## Additional context

---
Internal Tracking ID: [EXPOSUREAPP-10776](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10776)

**Comment by ndegendogo** [comment]
I attach a screenshot that shows the gap > 24 h in the ENF logs, although I had WLAN coverage.

![image1](https://user-images.githubusercontent.com/6118267/142300003-133f6a2a-7705-4738-a59f-9516ce37e2c8.png)

**Comment by ndegendogo** [comment]
And here is my ENF log

at 00:13 I opened the app

[ExposureChecks-2021-11-18.json.txt](https://github.com/corona-warn-app/cwa-app-ios/files/7558693/ExposureChecks-2021-11-18.json.txt)

**Comment by larswmh** [comment]
Hi @ndegendogo , thanks for your report. We have created an internal ticket and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-10776](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10776)

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
I currently have a GAP of ~16h without any risk checks in the background:
- The phone was connected to the internet the whole night
- The phone is running iOS 15.3

<img src="https://user-images.githubusercontent.com/67682506/151306557-efbb3439-4c10-4b39-ab3b-2af68b0013a2.png" width="300">

I won't open the app to see when it will start doing checks again or push me a dead man notification.

**Comment by ndegendogo** [comment]
@Ein-Tim wow 😬

Which model? Which cwa version?
Did you enable error logging?
Yesterday (after the 16:38 check) - did you have internet all the time? Do you know if your internet coverage was always good and stable?
Do you know if the 16:38 check was triggered from background or foreground? Do you remember your last active usage of cwa? When, and what did you do?

**Comment by ndegendogo** [comment]
@Ein-Tim do you have open workflows that are related to network traffic?
Like: waiting for test results, waiting for a certificate, event registration, data donation

Did you "play" with activation / deactivation of contact tracing?

**Comment by Ein-Tim** [comment]
@ndegendogo 

> Which model?

iPhone XR

> Which cwa version?

CWA 2.16.2

> Did you enable error logging?

No, as I didn't think this would happen.

> Yesterday (after the 16:38 check) - did you have internet all the time? Do you know if your internet coverage was always good and stable?

I went for a PCR test yesterday evening, so my phone was not connected between 17:40 and 18:30h.
Afterwards it was connected the whole evening & the whole night & also today.

> Do you know if the 16:38 check was triggered from background or foreground? 

This was from foreground.

> Do you remember your last active usage of cwa? When, and what did you do?

Yes at around 18:10 I registered a PCR test in the app using mobile data.

> do you have open workflows that are related to network traffic?
Like: waiting for test results, waiting for a certificate, event registration, data donation

Yes, I have a PCR test registered in the app.

> Did you "play" with activation / deactivation of contact tracing?

No.

**Comment by ndegendogo** [comment]
@Ein-Tim uh - a PCR test ... 
**I wish you all the best for your results** 🍀🍀🍀

Do you remember if you **closed** cwa after your test registration? Home button, or did you even swipe it out of memory? Or did you just switch off the display?

**Comment by Ein-Tim** [comment]
@ndegendogo 

> I wish you all the best for your results 🍀🍀🍀

Thank you!

> Do you remember if you closed cwa after your test registration? Home button, or did you even swipe it out of memory? Or did you just switch off the display?

I closed it only via the "home button", but meanwhile it was also swiped out of memory, I think I swiped all apps out of memory yesterday evening before going to bed.

**Comment by ndegendogo** [comment]
@Ein-Tim So let's wait if / how / and when it recovers ...

I my experience:
- iOS 15 has very aggressive power-saving, so at night I often have gaps (or is it only my iPhone 13?)
- background check "feeled" always more reliably than foreground / with open app
- bad internet connection had often kicked me out *(although I have not yet seen this with cwa 2.16)*

**Comment by ndegendogo** [comment]
@Ein-Tim I suggest the following:
- wait if it recovers or you get the deadman notification
- in latter case: open cwa and see if that triggers a check
- if not: enable error logging

**Comment by Ein-Tim** [comment]
I see an entry in the ENF log for 13:10 but the check failed...

**Comment by Ein-Tim** [comment]
And another failed attempt at 13:34:

![image](https://user-images.githubusercontent.com/67682506/151359983-ffec0a9d-f967-494f-8a44-08c5fa960133.png)

**Comment by Ein-Tim** [comment]
@thomasaugsten Are these failed attempts resetting the dead man notification?

**Comment by thomasaugsten** [comment]
Should not reset the notification especially when retries in this short time

**Comment by Ein-Tim** [comment]
Okay I will for some more time until today's evening ~ 20:00h but I can't wait any longer as I need to see my test result.

Any clue why this happens @thomasaugsten?

**Comment by Ein-Tim** [comment]
As I was able to receive my (negative) test result via another way, I won't open the app now. Let's do this experiment! 🙂

**Comment by Ein-Tim** [comment]
**A risk check was carried out and CWA pushed me 2 notifications!** 🎉🎉

After connecting my phone to the charging cable it took around 5 minutes, then the push notifications came:
<img src="https://user-images.githubusercontent.com/67682506/151425037-f47a6184-785b-4d2c-bc6d-4e288ccc8cdf.PNG" width="300">

Here a screenshot from the settings:
<img src="https://user-images.githubusercontent.com/67682506/151424955-5af206cf-5f97-4bb6-af55-833280fd2e50.PNG" width="300">

Seems like the charing cable triggered iOS to do the background job. I wonder why this didn't happen last night, where my phone was also connected to the charing cable.

**Comment by ndegendogo** [comment]
@Ein-Tim **good that it works again!**
*Still what a pity that you didn't catch it with an error log... But either it will happen again, or it is so rare that it is not worth investigating 😅*

**Comment by Ein-Tim** [comment]
Here is a Twitter user reporting that background checks never worked reliable: https://twitter.com/connor_larkin/status/1489595545563942920?s=20&t=ex97vxfGdt8xT4TmzNodeg
Should I ask for an error log or so?

**Comment by Ein-Tim** [comment]
@ndegendogo Can you still reproduce this issue? On my device risk checks are very reliable with the latest versions of CWA & iOS.

**Comment by ndegendogo** [comment]
> On my device risk checks are very reliable with the latest versions of CWA & iOS.

Same here. Very reliable.
Closing as fixed.
