### ISSUE TITLE
Auto Fill Bug

### ISSUE THREAD

**Issue by luisoos** [corona-warn-app/cwa-app-ios#3871]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 11 64GB
- iOS version: 15.1
- App version: 2.13.2 (0)

## Describe the bug

🇬🇧 Hey, I've had this bug many times before and thought I'd report it now. If you use the auto-fill function with your contacts during keyboard / autocorrection, this simply does not work. In this example video, when creating a quick test profile, some auto-fills just don't want to go into the input, so you have to type it in manually. Is a relatively unimportant bug, but would increase the user-friendliness / accessibility. 

🇩🇪 Hey, ich habe diesen Bug bereits öfters zuvor gehabt und dachte mir dass ich jenen jetzt Reporte. Wenn man beim Keyboard / Autokorrektur die Auto-Fill Funktion mit seinen Kontakten benutzt, funktioniert dies einfach nicht. In diesem Beispielvideo ist es bei der Anlegung eines Schnelltest-Profils, manche Auto-Fills wollen einfach nicht in den Input reingehen, sodass man ihn manuell eintippen muss. Ist ein relativ unwichtiger Bug, würde aber die Benutzerfreundlichkeit heben.

## Steps to reproduce the issue

https://user-images.githubusercontent.com/81855420/142756332-f98adc72-f79a-403c-af5b-96521a1f130b.MOV

Example:
1. Go to 'Ihre Testverwaltung'
2. Click on 'Schnelltest-Profil'
3. Create a new profile 
4. Some auto fills may not be working

## Expected behaviour

Some auto-fill options may not be working.

---
Internal Tracking ID: [EXPOSUREAPP-10750](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10750)

**Comment by Ein-Tim** [comment]
Related to the closed issue #3159.
CC @freshking

**Comment by larswmh** [comment]
Hi @luis, thanks for your reports. We have created an internal ticket and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-10750](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10750)

---
Corona-Warn-App Open Source Team

**Comment by moabits** [comment]
+1 can confirm

**Comment by Ein-Tim** [comment]
@luisoos / @moabits 

Can you still reproduce this issue? I can't.

**Comment by luisoos** [comment]
> @luisoos / @moabits 
> 
> 
> 
> Can you still reproduce this issue? I can't.

Tested it, I cannot.

**Comment by Ein-Tim** [comment]
@luisoos Then I suggest to close this issue.

**Comment by dsarkar** [comment]
Hi @luisoos Thanks for contributing here and your feedback. Best wishes, DS

---
Corona-Warn-App Open Source Team
