### ISSUE TITLE
Display Issue Statistics Card "Hospitalisierungen"

### ISSUE THREAD

**Issue by jajoho** [corona-warn-app/cwa-app-ios#3872]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 11 Pro
- iOS version: 15.1
- App version: 3.13.2

## Describe the bug

The word "Hospitalisierungen" has a strange line-brake for the nationwide card. This is not happening for the local statistics.
It seems to me that this is because the image is arranged differently for the two cards types (see screenshots). 

![IMG_0449](https://user-images.githubusercontent.com/15175599/142760161-eee9edaa-199c-48d0-87b3-ff3ca9959943.PNG)
![image](https://user-images.githubusercontent.com/15175599/142760179-73a9b2e3-bd68-4dff-9e40-08930d28b7e4.png)

## Steps to reproduce the issue

Add local statistics and observe the difference

## Expected behaviour

The word should not have a line-break at all.

## Possible Fix

Arrange the image differently or allow overlay of text and image

---
Internal Tracking ID: [EXPOSUREAPP-10744](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10744)

**Comment by Ein-Tim** [comment]
Can't confirm this. I assume it very much depends on your font size & device model.


<img src="https://user-images.githubusercontent.com/67682506/142761367-aba297fb-bb79-424d-963d-874aee0134a3.png" width="300">

**Comment by jajoho** [comment]
@Ein-Tim 

When changing the font size in system preferences to a smaller size the line-brake no longer occurs. 
But for me, at a text size with the slider in the middle, the word is already wrapped (moreover, also without a hyphen, which does not look good from my point of view).
This occurs with the local statistics only at an almost maximum text size.

From my point of view, it is therefore easy to solve the problem by arranging the image in the same way for the nationwide statistics as for the local statistics.

**Comment by Ein-Tim** [comment]
@jajoho 

> But for me, at a text size with the slider in the middle, the word is already wrapped (moreover, also without a hyphen, which does not look good from my point of view).

I also have the slider in the middle:

<img src="https://user-images.githubusercontent.com/67682506/142762060-614dd205-fe37-4107-9d3a-4bc5be2cb553.png" width="300">

**Comment by larswmh** [comment]
Hi @jajoho, thanks for reporting. We have created an internal ticket and will raise this topic internally. Internal Tracking ID: [EXPOSUREAPP-10744](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10744)

--- 
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
FYI: PR: #3906

**Comment by jajoho** [comment]
Problem solved with release 2.15.1

Thank you l!
