### ISSUE TITLE
Display Errors in View (Header / Navbar) for Certificate printing

### ISSUE THREAD

**Issue by JNSOFF** [corona-warn-app/cwa-app-ios#3874]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation) Can't say, I don't have an Android Device.
* [x] Bug is not already reported in another issue

## Technical details

- Device name: iPhone SE 2. Generation
- iOS version: 15.0.1
- App version: 2.14.1

## Describe the bug

The Header / Navbar in the View for printing the current Vaccination-Certificate has some Bugs. You can see two Label for `Zurück` and also some Elements of the Certificate-View itself.

## Steps to reproduce the issue

1. Go to your Vaccination-Certificate
2. Click on `Mehr`
3. Click on `Druckversion anzeigen`
4. See error, like in Screenshot

![IMG-4553](https://user-images.githubusercontent.com/16521123/142846601-ecea9a01-166b-4fec-b759-0f92fc277135.jpg)

## Expected behaviour
The Header / Navbar shouldn't have duplicate Labels or Content from other Views.

**Comment by Ein-Tim** [comment]
Hey @JNSOFF, this seems like a duplicate of #3731. Can you confirm?

**Comment by JNSOFF** [comment]
Hey @Ein-Tim, correct, overlooked it 🤦‍♂️.
I will close this Issue.
