### ISSUE TITLE
Risk check failed - retry button does not work

### ISSUE THREAD

**Issue by ndegendogo** [corona-warn-app/cwa-app-ios#3876]
## Avoid duplicates
* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 8
- iOS version: 14.4.1
- App version: cwa 2.13.2

## Describe the bug
Today evening I returned home and opened cwa. But the risk check shows that it has failed. I press the "retry" button, but nothing happens. See screenshot.
My last check was in the morning 08:00 before I left. During the day I had no WLAN, therefore no risk checks.

## Steps to reproduce the issue
- Open cwa
- get a failing risk check
- press the retry button
Expected: the risk check repeats
Observed: nothing (or: still the same error message?)

## Expected behaviour
After a failed risk check the retry button allows a manual trigger of the risk check.

## Additional context

![0E5D66F5-1292-421C-A032-7861F30C45F2](https://user-images.githubusercontent.com/6118267/142933043-234e184e-aaba-49d6-8438-1109f4226c15.png)

---
Internal Tracking ID: [EXPOSUREAPP-10742](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10742)

**Comment by Ein-Tim** [comment]
Related issue:
- https://github.com/corona-warn-app/cwa-documentation/issues/722

**Comment by ndegendogo** [comment]
Well - I have WLAN coverage here. Still the link does not work.

**Comment by ndegendogo** [comment]
Can it be overload??

**Comment by Ein-Tim** [comment]
> Well - I have WLAN coverage here. Still the button does not work.

@ndegendogo This is really strange! That the button doesn't work without internet: Ok, maybe just a missing notification pop up that the app does need access to the internet.

> Can it be overload??

You mean on the device? Could be possible, did the card turn green (or red 😅) after some time or is the card still showing "Risk Check failed"?

**Comment by ndegendogo** [comment]
Still failed.
I will investigate myself later - I have got an error log

**Comment by Ein-Tim** [comment]
@ndegendogo 

Mh, okay. Maybe you wanna update to 2.14.1 to check if that changes something? 

But hey, an error log is great! Nice that you were able to capture this!

**Comment by ndegendogo** [comment]
Insights from my error log:
- the retry button does not work because it thinks the risk check s already running.

**Comment by ndegendogo** [comment]
I swiped cwa out of memory, then opened it. **The risk check is working again now.**

**Comment by ndegendogo** [comment]
Possibly related:
#3432

**Comment by ndegendogo** [comment]
@dsarkar I have the impression (gut feeling) that the risk check might be unrobust in a situation with bad / instable network connection.
Could you ask the developers how they see this?

Thanks!

**Comment by JensFF** [comment]
I had the same issue with 2.14.1 on an iPhone 11 with iOS 15.1 at different places with different internet access.
Restarting the App (not the phone) did fix it for me.

**Comment by ndegendogo** [comment]
@JensFF yes, exactly. 
So, on the one side I am happy that I know the work-around to recover it.
On the other side I am worried, because I must watch it all the time. I just cannot rely blindly. 
Also I am worried, assuming it is indeed unrobust: how widespread is this issue? How many of the users watch it closely all the time?

**Comment by larswmh** [comment]
Hi @ndegendogo, thanks for reporting. We have created an internal ticket and will rise this topic internally. 

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-10742](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10742)

**Comment by thomasaugsten** [comment]
@ndegendogo Can you please submit the complete error log?

**Comment by ndegendogo** [comment]
@thomasaugsten unfortunately I have restarted error logging only yesterday - so I cannot submit it "the official way".
But I have captured it locally, so I'll try if I can post it here.

**Comment by ndegendogo** [comment]
[cwa-log.zip](https://github.com/corona-warn-app/cwa-app-ios/files/7603213/cwa-log.zip)

**Comment by dsarkar** [comment]
FYI PR https://github.com/corona-warn-app/cwa-app-ios/pull/4017

**Comment by Ein-Tim** [comment]
@ndegendogo Can you recheck under version 2.16?

**Comment by Ein-Tim** [comment]
The button now behaves like this in version 2.16. Not a really big improvement, IHMO. A pop up informing the user about **why** the exposure check failed (e.g. in my case due to missing connection to the internet) is not shown.


https://user-images.githubusercontent.com/67682506/149987976-d6d12286-6f0e-48a4-bfe9-df4114546c21.mp4

**Comment by svengabr** [comment]
I have just checked the linked Jira issue.

Jira Ticket is flagged as:
Resolution: `Fixed`
Status: `Completed`
Fix Version/s: `Release 2.16`

Developer comment:
> https://github.com/corona-warn-app/cwa-app-ios/pull/4017
> 
> Please test with 2.16.0(4) 
> 
> When you press the restart button, a message (Daten werden heruntergeladen) will be displayed and we have also added a delay of one second, so the user can see it before it fails due to network error.
