### ISSUE TITLE
Integrate the Digital Registration on Entry into the CWA

### ISSUE THREAD

**Issue by Maximisch** [corona-warn-app/cwa-app-ios#3881]
## Avoid duplicates
* [x] This enhancement request has not already been raised before
* [ ] Enhancement request is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)
* [ ] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation
There is no such feature present yet. Realization would likely be most similar to the current implementation of quick test results.

## Suggested Enhancement
Integrate the flow for the Digital Registration on Entry (as required by the federal government for international travellers, see [Einreiseanmeldung.de](https://www.einreiseanmeldung.de/#/)) into the CWA. The registration requires users to enter their personal contact information and upload the proof of vaccination. This information is already present in the CWA and could thus be sent with a single button from there. The resulting code for proof of a completed registration on entry could then be stored like the quick test results in the app for presentation at checks.

## Expected Benefits
Significant time savings for international travellers and smart enhancement of the CWA.

**Comment by Ein-Tim** [comment]
Hey @Maximisch 

Thank you for proposing this! 
We already have this feature request in https://github.com/corona-warn-app/cwa-wishlist/issues/627, the central repository for feature/enhancement requests by the community. 

I would recommend to close this issue, monitor https://github.com/corona-warn-app/cwa-wishlist/issues/627 and follow up there if necessary. 

Thank you & have a nice day!

**Comment by Maximisch** [comment]
@Ein-Tim thank you! I was unaware of the mentioned repo, will +1 there and close this as suggested! :-)

**Comment by dsarkar** [comment]
@Maximisch Thanks for the proposal,
@Ein-Tim Thanks for pointing out the duplicate.

---
Corona-Warn-App Open Source Team
