### ISSUE TITLE
fix design for print view

### ISSUE THREAD

**Issue by tmechen** [corona-warn-app/cwa-app-ios#3883]
## Avoid duplicates
* [x] This enhancement request has not already been raised before
* [x] Enhancement request is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)
* [x] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation
![21-11-24 09-01-51 1985](https://user-images.githubusercontent.com/9123876/143199092-43af50b8-d364-4322-8098-fb202140f227.png)

### Reproduce
* IPhone SE Gen 2 - CWA 2.14.1 - iOS 15.1 (19B74)
* Certificates tab
* open any certificate 
* scroll to bottom, open certificates
* click more -> Display Print Version -> Continue
(heck, why are there this many steps to take to get to the print view in the first place Oo)

## Suggested Enhancement
the transparent approach makes this view ugly und difficult to use. there are two "back" buttons visible, the share button (while being at the top) is less visible than the closing X of the background 

## Expected Benefits
* make this view more usable

**Comment by tmechen** [comment]
ah sry, looks like duplicate: https://github.com/corona-warn-app/cwa-app-ios/issues/3731

**Comment by larswmh** [comment]
Thanks for your report @tmechen. We will add the information to the internal ticket.
