### ISSUE TITLE
App not available in non-german app store

### ISSUE THREAD

**Issue by smitthakkar96** [corona-warn-app/cwa-app-ios#3887]
Hello there,

I am trying to download this app but it shows me the app is not available in the store of your country. I recently moved to Germany and I am yet to change the country and region on my apple ID due to one going subscriptions. This app is very critical for someone to have on their phone. It would be great to have it available on all app stores and not just Germany.

**Comment by Ein-Tim** [comment]
@smitthakkar96

This is intended, more information & the reason for this can be found in this FAQ entry: https://www.coronawarn.app/en/faq/#international

**Comment by ndegendogo** [comment]
@smitthakkar96 yes, legal reasons.
It is mandatory that before every release on a foreign store first the lawyers must confirm that the app complies to the legal requirements of that country. With regard to data privacy, medical data, and similar.

Meanwhile you can check our [wishlist](https://github.com/corona-warn-app/cwa-wishlist/issues) if there is already a ticket for your desired country, and upvote that ticket; or else submit such a ticket.

**Comment by larswmh** [comment]
Hi @smitthakkar96, thanks for your request. As @Ein-Tim and @ndegendogo already pointed out, there are legal reasons for the unavailabiility in some other countries. However, there is a list of the countries where the app is already available. See @Ein-Tim's and @ndegendogo's comments.
