### ISSUE TITLE
App verarbeitet den App-Link nicht, geht einfach nur auf

### ISSUE THREAD

**Issue by pegonia** [corona-warn-app/cwa-app-ios#3902]
Ich möchte den Befund  per E-Mail als App-Link zustellen, damit man mit Klick auf den Link den Test in der App sieht.

Als Test-Link nehme ich:

https://s.coronawarn.app?v=1#eyAiZm4iOiAiRXJpa2EiLCAibG4iOiAiTXVzdGVybWFubiIsICJkb2IiOiAiMTk5MC0xMi0yMyIsICJ0aW1lc3RhbXAiOiAxNjE4Mzg2NTQ4LCAidGVzdGlkIjogIjUyY2RkZDhlLWZmMzItNDQ3OC1hZjY0LWNiODY3Y2VhMWRiNSIsICJzYWx0IjogIjc1OUY4RkYzNTU0RjBFMUJCRjZFRkY4REUyOThEOUU5IiwgImhhc2giOiAiNjdhNTBjYmE1OTUyYmY0ZjZjN2VjYTg5NmMwMDMwNTE2YWIyZjIyOGYxNTcyMzc3MTJlNTJkNjY0ODlkOTk2MCIgfQ

Wenn ich daraus einen QR-Kode generiere und den mit der App einlesen, dann wird es korrekt verarbeitet.

Aber als Link in der E-Mail passiert immer nur eins: die App geht auf, ohne etwas zu tun.
Ich erwarte: die App geht auf und liest den Parameter hinter dem Hash-Zeichen und legt einen Test an.

Was muss ich bei dem Link anders machen, damit die App es als Neuen Schnelltest nimmt?

**Comment by ndegendogo** [comment]
@pegonia 
versteh ich das richtig? Der Parameter hinter dem Hash-Symbol ist der codierte QR-code?

@dsarkar @larswmh 
1) please clarify with the developers if the app currently supports to import a QR code as hex string instead of image.
2) if not, this request could go into our wishlist?

**Comment by ndegendogo** [comment]
Possibly related:
https://github.com/corona-warn-app/cwa-wishlist/issues/302
https://github.com/corona-warn-app/cwa-wishlist/issues/227

**Comment by thomasaugsten** [comment]
When I open your link here in github with Safari the apps opens and wants to register a test.

**Comment by dsarkar** [comment]
@pegonia Wich browser are you using?

**Comment by ilya-smirnov-berlin** [comment]
Mögliche Lösung hier:
https://github.com/corona-warn-app/cwa-quicktest-onboarding/wiki/FAQ#warum-f%C3%BChrt-ein-app-link-nicht-zur-cwa-sondern-zum-browser--app-store--google-play

**Comment by pegonia** [comment]
Für mich ist das Problem jetzt gelöst.
In der WRU-Phase, also mit der I OS app aus dem Test Flight hat der App-Link schlichtweg nicht funktioniert.
Aber... derselbe Link funktioniert in der produktiven Version der App sowohl unter Android als auch uner I OS.
Ich schließe daher jetzt diesen Post.
Für die Leute, die für die TestFlight-Version der IOS App zuständig sind: guckt bitte mal, was da los ist mit dem App-Link.

Danke an alle für Eure Rückmeldungen.
