### ISSUE TITLE
DCC_COMP_202 error EU Digitcal Corona Certificate for Rapid Antigen Test

### ISSUE THREAD

**Issue by cariad-robert-abel** [corona-warn-app/cwa-app-ios#3934]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue:  
Unsure; might be related to #3256 or might not be.

## Technical details

- Device name: iPhone SE
- iOS version: 15.1
- App version: 2.14.1

## Describe the bug

Repeatedly encountered error DCC_COMP_202 while retrieving EU Digital COVID Test Certificate.
I tried numerous times using the "Try Again" button, but always the same error message, see screenshots:

<img width="375" alt="20211205_124628324_iOS" src="https://user-images.githubusercontent.com/32576332/144747779-179abd92-fc22-4050-ba3d-462a414d570b.png"><img width="375" alt="20211205_124610903_iOS" src="https://user-images.githubusercontent.com/32576332/144747777-c41c0e8c-54a8-425c-9f61-d3761208012a.png">

I tried closing and re-opening the CWA and have rebooted the phone and tried again but it would not work.

## Steps to reproduce the issue

1. Scan CWA Rapid Test Result QR Code
2. Accept to retrieve the EU DCC after QR scan dialgo
3. See correctly imported Rapid Test result in Status tab.
4. Change to Certificates tab
5. Encounter Error DCC_COMP_202

## Expected behaviour

CWA should be able to retrieve the EU DCC and display its QR code.

## Additional context

I submitted an error report of a single "Try Again" run. Error Report ID 925761762EB6D9B37A17.

I know the [Coronatest Bayern](https://corona-test-bayern.de) rapid test station _Ingolstadt Süd am Positiv Fitness, Münchener Str. 144, 85051 Ingolstadt_ is not listed using the EU flag on https://map.schnelltestportal.de/, however, they did issue EU DCC last week (28 Nov 2021), so I don't see why they should have stopped being able to issue them.

![image](https://user-images.githubusercontent.com/32576332/144747757-a6c1661a-bcea-4101-ac98-a47b89fc5f3a.png)

I had the previous test result from 28 Nov 2021 in the CWA and only removed it after I finished the import of the current Rapid Test and requested the EU DCC. Maybe this has something to do with it as the App repeatedly states it can only handle one Rapid Test at a time? I don't know and I can't find out, because I cannot import the CWA QR code in a clean app as it's already been imported before...

---
Internal Tracking-ID: [EXPOSUREBACK-1351](https://jira-ibs.wbs.net.sap/browse/EXPOSUREBACK-1351)

**Comment by Ein-Tim** [comment]
Hi @cariad-robert-abel 

In the OP of https://github.com/corona-warn-app/cwa-app-ios/issues/3256 I posted the relevant part of my error log, could you check whether your log has the same content? If yes, we can probably merge both issues (rename #3256 so that it covers both, RAT and PCR).

**Comment by cariad-robert-abel** [comment]
Hi @Ein-Tim,

I was unable to retrieve the error log of the report ID above, but I did create a new report just now: [application.log](https://github.com/corona-warn-app/cwa-app-ios/files/7655932/application.log)
I'm guessing the relevant part is this:

```
Info 2021-12-05T13:24:15Z
[ENA/HealthCertificateService.swift:302] [executeTestCertificateRequest(_:retryIfCertificateIsPending:completion:)]
[HealthCertificateService] Executing test certificate request: 🙈🙉🙊

Debug 2021-12-05T13:24:15Z
[ENA/CachedAppConfiguration.swift:77] [shouldFetch()]
timestamp >= 300s? 14.586901903152466 >= 300)

Debug 2021-12-05T13:24:15Z
[ENA/CachedAppConfiguration.swift:37] [appConfiguration(forceFetch:)]
fetching cached app configuration

Info 2021-12-05T13:24:15Z
[ENA/HealthCertificateService.swift:336] [executeTestCertificateRequest(_:retryIfCertificateIsPending:completion:)]
[HealthCertificateService] waitAfterPublicKeyRegistrationInSeconds: 10.0, waitForRetryInSeconds: 10.0

Info 2021-12-05T13:24:15Z
[ENA/HealthCertificateService.swift:393] [executeTestCertificateRequest(_:retryIfCertificateIsPending:completion:)]
[HealthCertificateService] Public key already registered, immediately requesting certificate.

Info 2021-12-05T13:24:15Z
[ENA/HealthCertificateService.swift:891] [requestDigitalCovidCertificate(for:rsaKeyPair:retryIfCertificateIsPending:waitForRetryInSeconds:completion:)]
[HealthCertificateService] Requesting certificate…

Error 2021-12-05T13:24:15Z
[ENA/HTTPClient.swift:611] [getDigitalCovid19Certificate(registrationToken:isFake:completion:)]
HTTP error code 202. DCC is pending.

Error 2021-12-05T13:24:15Z
[ENA/HealthCertificateService.swift:921] [requestDigitalCovidCertificate(for:rsaKeyPair:retryIfCertificateIsPending:waitForRetryInSeconds:completion:)]
[HealthCertificateService] Certificate request failed with error The operation couldn’t be completed. (ENA.DCCErrors.DigitalCovid19CertificateError error 5.)
```

This part seems to match your log messages. However, there is another similar part that is interspersed with some error messages and I'm not sure what to make of that:
```
Info 2021-12-05T13:25:26Z
[ENA/HealthCertificateService.swift:302] [executeTestCertificateRequest(_:retryIfCertificateIsPending:completion:)]
[HealthCertificateService] Executing test certificate request: 🙈🙉🙊

Debug 2021-12-05T13:25:26Z
[ENA/CachedAppConfiguration.swift:77] [shouldFetch()]
timestamp >= 300s? 85.63109195232391 >= 300)

Debug 2021-12-05T13:25:26Z
[ENA/CachedAppConfiguration.swift:37] [appConfiguration(forceFetch:)]
fetching cached app configuration

Info 2021-12-05T13:25:26Z
[ENA/HealthCertificateService.swift:647] [invalidateTimer()]
Invalidate scheduled validity timer

Info 2021-12-05T13:25:26Z
[ENA/HealthCertificateService.swift:574] [scheduleTimer()]
no next date in the future found - can't schedule timer

Info 2021-12-05T13:25:26Z
[ENA/EventCheckoutService.swift:294] [didBecomeActiveNotification(_:)]
[EventCheckoutService] 'DidBecomeActive' notification triggered.

Info 2021-12-05T13:25:26Z
[ENA/EventCheckoutService.swift:32] [checkoutOverdueCheckins()]
[EventCheckoutService] Checkout overdue checkins.

Info 2021-12-05T13:25:26Z
[ENA/HealthCertificateService.swift:336] [executeTestCertificateRequest(_:retryIfCertificateIsPending:completion:)]
[HealthCertificateService] waitAfterPublicKeyRegistrationInSeconds: 10.0, waitForRetryInSeconds: 10.0

Info 2021-12-05T13:25:26Z
[ENA/HealthCertificateService.swift:393] [executeTestCertificateRequest(_:retryIfCertificateIsPending:completion:)]
[HealthCertificateService] Public key already registered, immediately requesting certificate.

Info 2021-12-05T13:25:26Z
[ENA/HealthCertificateService.swift:891] [requestDigitalCovidCertificate(for:rsaKeyPair:retryIfCertificateIsPending:waitForRetryInSeconds:completion:)]
[HealthCertificateService] Requesting certificate…

Error 2021-12-05T13:25:26Z
[ENA/HTTPClient.swift:209] [getTANForExposureSubmit(forDevice:isFake:completion:)]
Failed to get TAN due to error: fakeResponse.

Debug 2021-12-05T13:25:26Z
[ENA/HTTPClient.swift:127] [getTestResult(forDevice:isFake:completion:)]
Received TestResult

Info 2021-12-05T13:25:26Z
[ENA/CoronaTestService.swift:745] [getTestResult(for:force:duringRegistration:presentNotification:_:)]
[CoronaTestService] Got test result (coronaTestType: antigen, testResult: negative), sampleCollectionDate: Optional(1638697140)

Info 2021-12-05T13:25:26Z
[ENA/PPAnalyticsCollector.swift:41] [collect(_:)]
Forbidden to log any analytics data due to missing user consent```

Maybe this snippet just retrieved the "regular" test result shown on the Status tab? Not too sure why it's concerned with TAN when that should only be required for PCR tests as far as I know...

**Comment by dsarkar** [comment]
@cariad-robert-abel Thanks for you report. We have added your case to an Internal Tracking ID: [EXPOSUREAPP-1351](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-1351). Best, DS

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
Internal Tracking-ID: [EXPOSUREBACK-1351](https://jira-ibs.wbs.net.sap/browse/EXPOSUREBACK-1351)

**Comment by Ein-Tim** [comment]
@cariad-robert-abel Mh, okay. I'm not sure whether this is the same issue or not, let's wait for the devs then.

**Comment by Taeufer** [comment]
Testcenter Softwareprovider has to check or maybe restart there Services first, maybe you´re able to check the Provider @dsarkar and ask the. Worked for my problem. This seems so be similar. HTTP error code 202. DCC is pending, may means "Service not reachable popperly" at the Interface, still "online" but not "transfer data".

**Comment by Ein-Tim** [comment]
@thomasaugsten I have a Twitter user who is seeing the DCC 202 error.
The test was carried out at the testing station: 

Corona City Teststation
Sparkassenplatz 1
73430 Aalen

Tel: 0152 29836338
*corona-city-teststation@mail.de

Can you relay this to them?

[Link to Twitter](https://twitter.com/zaiininadeem/status/1489923253477031937?s=21)

**Comment by dsarkar** [comment]
@Ein-Tim thanks, forwarded to Internal Tracking ID: [EXPOSUREBACK-1351](https://jira-ibs.wbs.net.sap/browse/EXPOSUREBACK-1351) 

Enjoy your Sunday! Best wishes, DS

**Comment by ndegendogo** [comment]
Just retried / now the error is gone 🤷

🎉

**Comment by svengabr** [comment]
Jira ticket is closed.
According to other feedback on this issue, the issue seems resolved.

> Tested on WRU. Bug is not occuring on WRU environment.
>
> When it's only occuring on PROD for a special test center, it should be tracked by a PROD incident.
> 
> Bug can be closed.
