### ISSUE TITLE
Twitter Report: CWA show 3/3 certificate as invalid for entry to France, CovPass shows valid

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#3935]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Not relevant
- iOS version: 15.1.1
- App version: 2.14.1

## Describe the bug

CovPass shows a 3/3 vaccination certificate as valid for the entry of France, CWA shows it as invalid.

| CWA | CovPass |
|---|---|
| <img src="https://user-images.githubusercontent.com/67682506/144757107-40ee54f8-6caa-41b9-a2f3-b74dc46e5e19.jpeg" width="300"> | <img src="https://user-images.githubusercontent.com/67682506/144757109-ff9df0c9-371d-4754-9ad6-66ca57fff0af.jpeg" width="300"> |

The rule which failed in CWA is: 
"With Moderna vaccine, a finished vaccination course is considered protective earliest from 28 days after the date of the last vaccination."

## Steps to reproduce the issue

1. Add a Booster certificate to your CWA and your CovPass
2. Check the validity for France
3. See that CWA shows invalid, CovPass shows valid

Note: It seems like this only happens for 6 days after the vaccination in the CWA.

## Expected behaviour

CWA and CovPass should show the same result.

## Additional context
1. Link to Twitter: https://twitter.com/diluvium76/status/1467126523618643968?s=20
2. @vaubaehn & @timokoenig I guess you could be interested in this.

**Comment by thomasaugsten** [comment]
The CWA is here correct. 
France has the clear rule independent of 2/2 or 3/3. 
The vaccination is valid after 7 days.
The english translation states 28 days but the rule checks for 7 days like the french description
Avec le vaccin BioNTech/Pfizer, un parcours vaccinale terminé est  concideré comme protecteur au plus tôt à partir de 7 jours apres la date de la derniere injection.
https://distribution.dcc-rules.de/rules/FR/4d1ff7f7a52eb59e4f93752c227a09e2d1e6748fcdb32fa67ad1e9c4686f1147

Im not sure why CovPass is not checking correctly maybe it using the 2/2 instead of 3/3

**Comment by Ein-Tim** [comment]
@thomasaugsten 

Thanks for your answer!

I see, I will open the issue in the CovPass repo then.

> Im not sure why CovPass is not checking correctly maybe it using the 2/2 instead of 3/3

The user removed the 2/2 cert and still got the same valid message, I will raise the issue in the CovPass repo.

FYI @timokoenig

**Comment by Ein-Tim** [comment]
Closing this issue in favour of https://github.com/Digitaler-Impfnachweis/covpass-ios/issues/76.

**Comment by uwemock** [comment]
> The CWA is here correct.
> France has the clear rule independent of 2/2 or 3/3.
> The vaccination is valid after 7 days.

No, this is not the case. The French Government states:

"Le rappel vaccinal est-il obligatoire pour avoir un "pass sanitaire" valide?
[...]
Toutes les personnes qui font leur rappel disposeront d’un nouveau QR Code, qui deviendra valide 7 jours après leur injection s’il s’agit d’une deuxième dose, ou **immédiatement s’il s’agit d’une 3e dose ou plus.**"

In English: "Is the booster vaccination required to have a valid sanitary pass? [...] All people who receive their booster dose will receive a new QR code which is valid 7 days after their injection if it was their second dose, or **immediately if it was their third dose at least.**"

https://solidarites-sante.gouv.fr/grands-dossiers/vaccin-covid-19/je-suis-un-particulier/dose-de-rappel-covid19
