### ISSUE TITLE
PDF print view header background missing

### ISSUE THREAD

**Issue by mcnesium** [corona-warn-app/cwa-app-ios#3987]
* CWA v2.14.1
* iOS 15.1
* iPhone SE

When in the certificate print view, the header bar is missing a background:

https://user-images.githubusercontent.com/476060/146071018-b9beaa04-f0e6-4744-80bf-140e8c6ae3c2.mov

**Comment by Ein-Tim** [comment]
This issue was already reported in #3731 and will be fixed in the next version.

**Comment by mcnesium** [comment]
ok sorry

**Comment by Ein-Tim** [comment]
@mcnesium No reason to say sorry,  thank you anyways for reporting!
