### ISSUE TITLE
Booster recommendation does not disappear after adding 3/3 certificate to the app

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#4010]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: not important
- iOS version: not important
- App version: 2.14.1

## Describe the bug

The recommendation to get a booster shot does not disappear, even after adding the 3/3 certificate and waiting <24h.

## Steps to reproduce the issue

As this does not affect all users, it's not really clear when this happens. Here are some screenshots:

<img src="https://user-images.githubusercontent.com/67682506/146644348-4a2e670e-f881-4dfb-987f-42bef337bace.jpg" width="300">
<img src="https://user-images.githubusercontent.com/67682506/146644350-4aa1be93-3fe3-4da2-bc6e-348d5b1ea894.jpg" width="300">

## Expected behaviour

The booster recommendation should disappear after adding the 3/3 certificate to the app.

**Comment by Jo-Achim** [comment]
> Here are some screenshots: 

Screenshots missing  ;-).

**Comment by Ein-Tim** [comment]
@Jo-Achim Fixed (:

**Comment by Jo-Achim** [comment]
I would like to add a question for **iOS** and **Android**: If this problem "**Booster recommendation does not disappear after adding 3/3 certificate to the app**" has been solved, the 'Booster' info could not be displayed textually for the corresponding certificate?

The solution to this problem requires that, for example, '3/3 certificate' be recognized as a 'booster' vaccination. Accordingly, here should:

![Screenshot_20211222-135917_Corona-Warn_2](https://user-images.githubusercontent.com/21124877/147099827-3bd0f3d0-65d5-4d21-a2ef-50144aeb43f5.jpg)

or, at the latest, here:

![Screenshot_20211222-135925_Corona-Warn_2](https://user-images.githubusercontent.com/21124877/147099897-0ccf8753-277a-4016-8d42-b805cc01f432.jpg)

be displayed. ("Booster #1" is then the first Booster, #2 the second one, ...)

Comparable to the CovPass discussion here: [IMPORTANT (CovPassCheck): Add a 'Booster'-Info to the "Certificate valid"-Screen...](https://github.com/Digitaler-Impfnachweis/covpass-android/issues/139#issue-1077846503).

Other vaccine combinations, etc. might have to use other algothymes for the 'Booster'-info determination.

**Comment by dsarkar** [comment]
@Jo-Achim Thanks for your suggestion. A few comments: 
1. On the overview view (certificate tab), which shows the "active DCC" there should be not too much information show due to privacy ("Datensparsamkeit"). This view should be used for checking a DCC.
2.  In the detail screen of a DCC your proposal is applicable, so I suggest to open a wishlist item. (I guess in the second screenshot you mean "Impfzertifikate", not "Testzertifikat")

**Comment by Jo-Achim** [comment]
@dsarkar,
>     1. On the overview view (certificate tab), which shows the "active DCC" there should not too much information be shown due to privacy ("Datensparsamkeit"). This view should be used for checking a DCC.

Ok. 

> 
>     2. In the detail screen of a DCC your proposal is applicable, so I suggest to open a wishlist item. (I guess in the second screenshot you mean "Impfzertifikate", not "Testzertifikat")

Yes, of course I mean "vaccination certificates" / "Impfzertifikate" (I didn't pay attention when copying the screenshot) - _Corrected_.


PS; 
Then, I think, there is a wrong Screenshot under Android [de]: [Zertifikate](https://www.coronawarn.app/de/screenshots/#android_certificates) ("Testzertifikat").

**Comment by Ein-Tim** [comment]
Does this still occur with version 2.18?
