### ISSUE TITLE
Make app available in all App Store regions

### ISSUE THREAD

**Issue by datalung** [corona-warn-app/cwa-app-ios#4015]
## Current Implementation

App is currently not available in the US App Store, even though it's possible to change "Exposure Notifications" region independently from App Store region. 

Context: I live in Germany with a US iPhone and was asked to use the app after testing positive for COVID. I can change the "Exposure Notifications" region to Germany, but cannot install the app because it is not listed in the US App Store. Due to active subscriptions, it's highly impractical for me to change App Store region. 

Steps to reproduce: 
1. Set App Store Region to USA
2. Confirm that app is not available in App Store
3. Set Exposure Notification region to Germany, follow prompts
4. The app will say that "Your Region has an Exposure Notification App", but the "Show in App Store" link will link to the US version of that page, presumably because Corona-Warn-App is not available in the US App Store. 

## Suggested Enhancement

Make the app available in all international App Store regions. 

## Expected Benefits

Users in Germany won't need a German App Store account to use the app.

**Comment by Ein-Tim** [comment]
Please take a look at this FAQ entry: https://www.coronawarn.app/en/faq/#international.

Regarding availability in the US-App Store, there is already an open issue in the cwa-wishlist repository on this: https://github.com/corona-warn-app/cwa-wishlist/issues/41

All requests to release the app in another country can be seen here: https://github.com/corona-warn-app/cwa-wishlist/labels/country.

**Comment by dsarkar** [comment]
@datalung Thanks for your suggestion, please, see the answer from @Ein-Tim.

---
Corona-Warn-App Open Source Team

**Comment by datalung** [comment]
@dsarkar @Ein-Tim thanks, and apologies for missing the existing info. I'll close this.

**Comment by dsarkar** [comment]
@datalung No problem at all. Any time, for suggestions, bur reports, questions, etc., please, do not hesitate opening a new issue, or participating in one of the open issues, respectively. Best wishes, DS  

---
Corona-Warn-App Open Source Team

**Comment by treysis** [comment]
Now available in Ukrainian app stores. How is this legally possibly with all the problems explained before?

**Comment by thomasaugsten** [comment]
I think it is related to the extraordinary situation for Ukrainian citizens in the EU and the Ukrainian application for the EU.

**Comment by treysis** [comment]
Yes, sure. But how does this forfait the so called legal problems? I doubt there have been negotiations held with the Ukrainian government/ministry of health right now? Why not make it available without country restriction, finally? Like all the other European countries' apps employing the Exposure Notification Framework.
