### ISSUE TITLE
App throws exception (EN Code: 10) if exposure logging is turned off while exposure check is running

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#4018]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone XR
- iOS version: 15.2
- App version: 2.15.1

## Describe the bug

The app throws an exception if exposure logging is turned off while an exposure check is running.

Here's a little video:

https://user-images.githubusercontent.com/67682506/147409559-b9daeefb-743b-4528-82da-5e2cefea3942.mp4

## Steps to reproduce the issue

1. Wait till a risk check is running
2. Deactivate exposure logging while the check is running
3. See the exception (EN Code 10)

## Expected behaviour

The app should either wait with deactivating exposure logging until the risk check has finished or deactivates exposure logging instantly but not throw an exception. 

## Additional context

The failed risk check is shown in the settings exposure log, so this counts into the 6 checks per day rate limit. 

---
Internal Tracking ID: [EXPOSUREAPP-11132](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11132)

**Comment by larswmh** [comment]
Hi @Ein-Tim, thanks for your report. We have created an internal ticket and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-11132](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11132)

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
@Ein-Tim Thanks for the report. Did you check if this issue is also reproducible on Android?

**Comment by Ein-Tim** [comment]
@dsarkar Under Android I can turn off exposure logging while a check is running, then the check will finish and only then exposure logging is off.

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode, I don't expect this issue to be addressed anymore. I'm therefore closing this issue.

**Comment by ndegendogo** [comment]
Additionally, cwa meanwhile leverages the caching of exposure files (I don't remember the exact version where they introduced this improvement). The exposure check runs much much faster now, and this mitigates this issue a lot, because it is now very unlikely that you get the timing "right" to hit this bug. 😅
