### ISSUE TITLE
Rapid Test date changed after registering in app

### ISSUE THREAD

**Issue by mss1010** [corona-warn-app/cwa-app-ios#4019]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: iPhone Xs
- iOS version: 15.2
- App version: 2.5.1 (2)

## Describe the bug

I registered a rapid antigen test in the app on 24.12. When I opened the app today, I still saw the test. But the real issue is, that **the test date has changed to 27.12.** After the 24.12. I did definitely not register any other test in the app.

The original automatic test entry in the diary: 
![IMG_2906](https://user-images.githubusercontent.com/36116339/147473383-90413de0-7ea3-43cc-97ff-d550ab7a3c0b.PNG)

The same test with a changed, wrong date: 
![IMG_2905](https://user-images.githubusercontent.com/36116339/147473401-018a4ccd-d868-46c5-a906-10744c74595b.PNG)

---
Internal Tracking ID: [EXPOSUREAPP-11119](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11119)

**Comment by Ein-Tim** [comment]
Slightly related: https://github.com/corona-warn-app/cwa-documentation/issues/661

**Comment by dsarkar** [comment]
@mss1010 Thanks for the report. 

1.
In the contact journal on 27.12., there is now (erroneous)  entry of the test? Could you provide also a screenshot of 17.12.?
2.
Just to be sure, the test was conducted on 24.12. And on 27.12. you released that it shows the wrong date, correct?
3.
On the 24.12., everything seemed ok? I.e. contact journal and RAT detail screen were showing the correct date and time=


Thanks for your report.

---
Corona-Warn-App Open Source Team

**Comment by mss1010** [comment]
1. on 27.12. there is nothing in the journal, as well as on 17.12. Actually, the only journal entry is the showed one on 24.12.

![EF4DD122-3416-42C8-A8E0-6D95435D67E7](https://user-images.githubusercontent.com/36116339/147492194-ac690bf5-e009-4b8b-889f-4063fff80e99.png)

2. Yes, correct 
3. On 24.12. everything looked ok. But I dont remember what exactly was shower on the detail screen, nor do I have a screenshot of it from 24.12.

**Comment by dsarkar** [comment]
@mss1010 Thanks for your feedback.

Internal Tracking ID: [EXPOSUREAPP-11119](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11119)


---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
Are there any updates available on this issue?

**Comment by dsarkar** [comment]
@mss1010 The dev team could no reproduce this issue and also had a look into the code. Did you experience similar issues since you reported?

**Comment by mss1010** [comment]
No, I think we can close the issue
