### ISSUE TITLE
Weird behavior of text on RAT profile screen

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#4025]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 6s
- iOS version: 15.2
- App version: 2.15.1

## Describe the bug

The text on the RAT profile screen, which shows the name, dob, etc. of the user, behaves strange:

https://user-images.githubusercontent.com/67682506/147863188-291c547e-3ead-4d52-8ecb-d7eb8294047a.mov

## Steps to reproduce the issue

1. Open the Corona-Warn-App
2. Click on the "Manage Your Tests" box
3. (Scroll down &) click on "Rapid Test Profile"
4. Generate a new profile if one isn't already generated
5. Scroll down and see where the text is 
6. Scroll back up
6. Swipe the screen away (swipe to the right), but only a bit (see the video)
7. Scroll down again
8. See that the text has moved to the middle now
9. Swipe the screen away again (swipe to the right), but only a bit (see the video)
10. See that the text moves again

## Expected behaviour

The text should not move.

---
Internal Tracking ID: [EXPOSUREAPP-11130](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11130)

**Comment by larswmh** [comment]
Hi @Ein-Tim, thanks for your report. We have created an internal ticket and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-11130](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11130)

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
Fix for this: #4037

**Comment by dsarkar** [comment]
@Ein-Tim Thanks for the confirming the fix. Forwarded to internal ticket.
