### ISSUE TITLE
After scanning a location check-in QR code the location information modal cannot be canceled

### ISSUE THREAD

**Issue by miallo** [corona-warn-app/cwa-app-ios#4060]
## Describe the bug

If the user previously has *not* agreed to the event/location check-in when scanning an event QR code (e.g. [this](https://twitter.com/sand2drn/status/1479198386041794561)), a modal explaining the check-in will be shown. The button asks for consent (German: "Einverstanden"), but the user does not have a different choice than pressing it (apart from restarting the App).

The same modal is shown if you already agreed and then (in the check-in tab bar entry) select the dotted menu in the top right and then "Informationen". The difference is that now a cross is shown to dismiss this screen (though I don't understand why the consent button is still shown, because the user clearly already consented):
<img src="https://drive.google.com/uc?export=view&id=1MYRHHVakhjOMoejJdMZkUybKKxt68fLX" width=30% height=30%>

## Expected behaviour

As a user I would expect to have a choice if the wording asks for my consent.

## Possible Fix

I think either the wording of the button should be changed and/or the user should get a choice to cancel (e.g. with the "x" and maybe also with dragging the modal down to dismiss it).

## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation) (probably iOS specific - did not test it on Android)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: iPhone14,3
- iOS version: 15.3
- App version: 2.15.1

---
Internal Tracking ID: [EXPOSUREAPP-11230](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11230)

**Comment by Ein-Tim** [comment]
Related: #3773

**Comment by larswmh** [comment]
Thanks for your report @miallo. We have created an internal ticket for it and will raise this topic internally. 
Internal Tracking ID: [EXPOSUREAPP-11230](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11230)

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
@miallo Thanks for reporting here. Feedback: As long as the user does not give his consent, the consent screen stays open in the "Check-In" Tab. This is intendet. The user can still use all other functions of the app without giving his consent by switching to another tab. There is no need to dismiss the screen without giving consent, this would anyhow just open the screen again if you go to the check-in tab.

**Comment by larswmh** [comment]
Closing due to the abovementioned reasons. Internal ticket was set to obsolete
