### ISSUE TITLE
Link in source outdated

### ISSUE THREAD

**Issue by gicmo** [corona-warn-app/cwa-app-ios#4069]
There are two places in the code that mentions the following link, which does not exist anymore:
https://github.com/corona-warn-app/cwa-app-tech-spec/blob/7779cabcff42afb437f743f1d9e35592ef989c52/docs/spec/exposure-windows.md#aggregate-results-from-exposure-windows

* https://github.com/corona-warn-app/cwa-app-ios/blob/b51a219d354159598ad4450fdc35a0eec9e8c9ad/src/xcode/ENA/ENA/Source/Services/Risk/Calculation/RiskCalculationExposureWindow.swift#L9

* https://github.com/corona-warn-app/cwa-app-ios/blob/b51a219d354159598ad4450fdc35a0eec9e8c9ad/src/xcode/ENA/ENA/Source/Services/Risk/Calculation/RiskCalculation.swift#L37

I think the new correct link might be https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md#risk-calculation (or the permalink version) but I am not 100% sure, otherwise I would have opened a PR.

**Comment by Ein-Tim** [comment]
FYI: This repository actually exists, but is it not available to the public: https://github.com/corona-warn-app/cwa-app-ios/issues/1393

More details in https://github.com/corona-warn-app/cwa-wishlist/issues/376

**Comment by Ein-Tim** [comment]
Can this issue be closed?

**Comment by dsarkar** [comment]
@gicmo @Ein-Tim Question has been answered above. Closing this ticket. Thanks! 

Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@dsarkar I think you forgot to press the "Close" button (-;

**Comment by Ein-Tim** [comment]
@dsarkar Could you please close this issue? Thanks!
