### ISSUE TITLE
App crashes when scanning a certificate

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#4076]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone XR
- iOS version: 15.2
- App version: 2.15.1

## Describe the bug

The Corona-Warn-App for iOS crashes when scanning a specific certificate. Under Android, the app does not crash.

## Steps to reproduce the issue

1. Open the universal QR code scanner
2. Scan the certificate
3. The app crashes

## Expected behaviour

The app should import the certificate and not crash.

## Additional context

I can provide the certificate via mail to you (@thomasaugsten).

---
Internal Tracking ID: [EXPOSUREAPP-11450](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11450)

**Comment by Ein-Tim** [comment]
The crash is still reproducible on version 2.16.2.

Under Android the certificate is still accepted.

I would appreciate if someone could take a look at this, to be sure that this is an edge case and does not happen to more users (@thomasaugsten)

@dsarkar I guess it would be good to get this mirrored to JIRA.

**Comment by thomasaugsten** [comment]
Yes please provide the certificate

**Comment by Ein-Tim** [comment]
@thomasaugsten Your e-mail is thomasaugsten@sap.com, right?

**Comment by larswmh** [comment]
Thanks for your report @Ein-Tim. Internal Tracking ID: [EXPOSUREAPP-11450](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11450)

---
Corona-Warn-App Open Source Team

**Comment by thomasaugsten** [comment]
thomas.augsten@sap.com

**Comment by Ein-Tim** [comment]
@thomasaugsten I send it to thomas.augsten@sap.com.

**Comment by larswmh** [comment]
@Ein-Tim FYI PR #4107

**Comment by Ein-Tim** [comment]
Thanks @larswmh!

Seems like this will be included in a hot fix! 

I was able to confirm that this PR fixes the issue.

**Comment by dsarkar** [comment]
@Ein-Tim Thanks for the feedback!

**Comment by Ein-Tim** [comment]
This has been fixed in 2.17 and I confirmed the fix.
