### ISSUE TITLE
3rd vax cert is hard to find

### ISSUE THREAD

**Issue by adcxyz** [corona-warn-app/cwa-app-ios#4088]
<!--

* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for iOS only
* [x] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 13
- iOS version: iOS 15.2
- App version: 2.15

## Describe the bug
The location of the 3. booster vaccination certificate is very confusing. 
While this is not a technical bug, I do think this is an interface design bug :-)

## Steps to reproduce the issue
After scanning the certificate for the third vaccination, 
the certificates list still only shows 2 certificates: 
The top certificate is the 2.  vaccination, 
the lower certificate looks like the 1. vaccination. 
the third vaccination only becomes visible after you select
and double click the bottom certificate

## Expected behaviour
IMHO, the clearest design for the vax certificates is: 
- all vax certificates in the certificates list show their date already
 (i.e. no need to click on it to see from when it is)
- all vax certificates are shown on the same level (no nesting) 
- vax certificates are sorted by date, newest certificate is always on top of the list

## Additional context
After scanning my 3rd vax certificate, I could not find it in the app;
trying to re-scan it gave me a "VC_ALREADY_REGISTERED" error;
then I scanned the FAQ to figure out how to delete a registered-but-invisible vax cert;
eventually following the few github issues that mention VC_ALREADY_REGISTERED, 
I found out that you need to look in the _older_ vax cert to see the newest one - ???

So, it cost me more than an hour of time to figure out where the app put my booster vax cert... 
and to show it, e.g. when going in to work IRL, I need to remember how to access it. 
- I think this could and should be be much more intuitive. 

hope this is helpful?
best adc

**Comment by Ein-Tim** [comment]
Hi @adcxyz 

Could you provide some details, please?

**Comment by adcxyz** [comment]
Ah sorry, I had written it all up, and apparently did not save the issue properly! 
I'll write it again now.

**Comment by adcxyz** [comment]
iphone 13, current iOS, cwa also current 2.15

I find the way the iOS app shows the 3rd vax cert quite confusing, 
and believe this could be both simpler and clearer. 

Background: 
After scanning my 3rd vax cert, the certif. panel showed me 2 certif. entries, 
just like it was before with two vax dates. 
the two entries look exactly the same, just the QR code.
I expected to see 3 entries now, so it seemed the scan of the 3rd cert had failed. 

On the upper entry of the two, 
clicking on the details showed my second vax date (6/2021);
all the way at the bottom, it has entries for 
vax cert 2 (6/2021) and
vax 1 (5/2 021) .

The lower certif. entry actually shows only the third vaccination;
because I expected this to be the older cert of my 1st vax, I did not 
read this patiently enough, and spent some time trying to repeat the scanning, 
which failed with "VC_ALREADY_REGISTERED" ...

Crosschechkin on the android caw app 2.15.1: 
this shows only a single top vax certificate, also without date, 
and clicking for details shows indiv. vax. dates with newest on top:
vax 3 11/2021,
vax 2 6/2021,  
vax 1 5/2021 

This is already clearer, and I think it could be even clearer:
The top level entries in the certificates panel should also show  
the _date_ of the newest vax (of the series captured) in that entry, 
so users know immediately which QR code to show on entering offices etc. 

Thanks!

**Comment by Ein-Tim** [comment]
iOS should actually behave the same way as Android does and I can confirm that this is the case on my iPhone XR:
![image](https://user-images.githubusercontent.com/67682506/149677312-5470a333-aefd-4ea2-b966-f69305513247.jpeg)
(I have only stored 2/2 and 3/3 cert in the app).

A new tile on the certificates tab is only created if the names or date of births differ from the other certificate.
