### ISSUE TITLE
Translation issue in version 2.16.1

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#4093]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: not relevant
- iOS version: not relevant
- App version: 2.16.1

## Describe the bug

https://github.com/corona-warn-app/cwa-app-ios/blob/release/2.16.x/src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings#L125 says:

"Please get tested, even if you don’t have any symptoms. If you get a warning of increased risk ("red tile”), you are entitled to a test free of charge. Your entitlement to a free rapid antigen test may be limited, depending on the local regulations. We recommend taking a PCR test, especially when it is free of charge."

which is not a correct translation of

https://github.com/corona-warn-app/cwa-app-ios/blob/release/2.16.x/src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings#L126:

"Lassen Sie sich testen, auch wenn Sie keine Symptome haben. Bei einer Warnung über ein erhöhtes Risiko ("Rote Kachel") haben Sie Anspruch auf einen kostenlosen Test. Abhängig von den örtlichen Regelungen kann Ihr Anspruch auf einen kostenlosen Antigen-Schnelltest beschränkt sein. Wir regen an, einen PCR-Test durchführen zu lassen, vor allem, wenn der Test kostenlos ist."

## Expected behaviour

English text should have the same meaning as the German text. 

## Possible Fix

Change the English sentence to:

"Please get tested, even if you don’t have any symptoms. If you get a warning of increased risk (“red tile”), you are entitled to a test free of charge. Your entitlement may be limited to a free rapid antigen test, depending on the local regulations. We recommend taking a PCR test, especially when it is free of charge."

---
Internal Tracking ID: [EXPOSUREAPP-11426](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11426)

**Comment by Ein-Tim** [comment]
@larswmh Can we get this mirrored to JIRA so that it will be fixed in the next translation delivery?

**Comment by larswmh** [comment]
Thanks for your report @Ein-Tim. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-11426](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11426)

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
The text will be removed: https://github.com/corona-warn-app/cwa-app-ios/pull/4121

**Comment by Ein-Tim** [comment]
Closing as fixed in 2.17.

**Comment by dsarkar** [comment]
@Ein-Tim Thanks.
