### ISSUE TITLE
No update of risk state since today

### ISSUE THREAD

**Issue by AnOtherMuenchner** [corona-warn-app/cwa-app-ios#4114]
The app does not update the risk state anymore. The error occurs since today. The last successful update has been yesterday at 21:33 CET.

Phone: iPhone SE 2020.

**Comment by AnOtherMuenchner** [comment]
I see, there is a also the same or a similar bug report for android.

**Comment by dsarkar** [comment]
@AnOtherMuenchner  See comment https://github.com/corona-warn-app/cwa-app-android/issues/4723#issuecomment-1019450264

should be working now

**Comment by AnOtherMuenchner** [comment]
Thank you!

**Comment by Ein-Tim** [comment]
@AnOtherMuenchner 

Can you close this issue?
