### ISSUE TITLE
3rd vaccination certificate not marked as currently used

### ISSUE THREAD

**Issue by pike55** [corona-warn-app/cwa-app-ios#4115]
## Technical details

- Device name: iPhone 12 Pro
- iOS version: 15.2
- App version: 2.16.2

## Describe the bug

I've added the 3rd vaccination certificate scanning the QR code on the pharmacy's printout. The QR code is added, however the new certificate is not marked as "curently used certificate".

Even after deleting all three certs (and also removing them from the recycle bin) and then scanning all three QR code printouts again, the situation is the same: all three certs are shown but only the 2nd one is marked as currently used.

The App now even shows the booster info which, in my case, should not be necessary anymore.
![IMG_AE6FF9248C33-1](https://user-images.githubusercontent.com/5902785/150672001-12f16c49-f61d-45fe-9750-031ee88153b6.jpeg)

## Expected behaviour

The 3rd vaccination certificate should be marked as "currently used certificate" as the CovPass App **does** in my case.

---
Internal Tracking ID: [EXPOSUREAPP-11529](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11529)

**Comment by dsarkar** [comment]
Hi @pike55,

thanks for the report.
Internal Tracking ID: [EXPOSUREAPP-11529](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11529)


Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by ndegendogo** [comment]
@pike55 please try the following:
- select the certificate that you want to be shown as "current"
- you see a switch (see example screenshot).
- activate the switch

![0F067086-37ED-4461-A581-86865D794B07](https://user-images.githubusercontent.com/6118267/151933820-c67bf218-5089-49f4-a990-bd1c9ddc0cda.jpeg)

**Comment by ndegendogo** [comment]
@pike55 

Note: sometimes corona warn app cannot group the 3rd vaccination certificate correctly with the other two. One of the reasons for this is a difference in the "name" field of the certificate.

**Comment by pike55** [comment]
@ndegendogo Thanks for your answer.

Meanwhile I went to the pharmacy where the 3rd cert. had been created. It turned out that there was a typo in the date of vaccination. It was set to 20**21**-01-03 instead of 20**22**-01-03. After the cert. has ben issued again with the correct vacc. date, everything is fine. The CWA now shows the 3rd as currently used.

So, CWA's behaviour was correct (CovPass App's probably not as it did show the certificate with the wrong date as currentl active), however some kind of message like "date of 3rd vacc. cannnot be before the date of 2nd cert." would have helped.

Thanks again. 👍
