### ISSUE TITLE
Question on end of life state

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#4135]
## Avoid duplicates
* [X] Question is not already answered in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Question is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Question has not already been asked in another issue

## Your Question
PR https://github.com/corona-warn-app/cwa-app-ios/pull/1960 (merged into `release/1.13.x`) added the end of life state. It added a new box to the Home Screen, if a positive test result is stored in the app:

Picture from the PR:
<img src="https://user-images.githubusercontent.com/1157991/107514226-b11c5080-6ba9-11eb-82bd-9b4415c5f3d8.PNG" width="300">

As my brother was tested positive, I had the option to take a look at this screen myself & it seems like the box was removed again. The home screen looks as normal but this is shown:
<img src="https://user-images.githubusercontent.com/67682506/151368797-847c5a50-180c-430b-93cb-a209f29e5af4.jpeg" width="300">

Is this intended? If yes, why was the box removed?

**Comment by thomasaugsten** [comment]
Because the ENF framework is not deactivate. But with the latest information we could discuss if the app leave the recover states automatically at the moment this is a manual interaction to remove the pcr test

**Comment by Ein-Tim** [comment]
@thomasaugsten 

Yes exactly, exposure logging stays active, however, the user can't see their risk status. Many users are asking on twitter how they can continue after this screen, so I think the box should be added back (with an adjusted text).

**Comment by Ein-Tim** [comment]
I'll open an enhancement request for this later today.
