### ISSUE TITLE
Print version of test certificate is missing content (CWA creates faulty PDF, CovPass creates the correct one)

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#4136]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone XR
- iOS version: 15.3
- App version: 2.16.2

## Describe the bug

The CWA iOS app creates print versions of test certificates, which don't include all available data.

| CWA | CovPass |
|---|---|
|![CWA](https://user-images.githubusercontent.com/67682506/151444643-523ebdfd-a4c3-442b-91da-25194afda7e4.png)|![CovPass](https://user-images.githubusercontent.com/67682506/151444650-4b11926a-0173-4253-9f58-b233381f2fe0.png)|

As you can see CWA is missing the `-` in the "Name des Tests (beim NAAT-Test fakultativ)" field and is only writing the data before the `,` in the "Testhersteller (beim NAAT-Test fakultativ)" field. 

## Steps to reproduce the issue

1. Get tested with a RAT at a test center which supports the issuance of EU digital test certificates
2. Receive the result via CWA and request a test certicate
3. Export the certificate from the CWA (create a print version)
4. Import the certificate to the CovPass app and create a print version there
5. Compare the two print versions
6. See the difference

## Expected behaviour

Both apps should show the same data.

## Additional context

I can provide the test certificate to one of the devs via E-Mail so that you can better investigate this issue (@thomasaugsten).

---
Internal Tracking ID: [EXPOSUREAPP-11601](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11601)

**Comment by larswmh** [comment]
Thanks for your report @Ein-Tim. Internal Tracking ID: [EXPOSUREAPP-11601](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11601)

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@thomasaugsten Can I send the certificate to you via E-Mail so you have a look at it?

**Comment by Ein-Tim** [comment]
PR https://github.com/corona-warn-app/cwa-app-ios/pull/4343 is the fix for this issue.

**Comment by Ein-Tim** [comment]
Confirm fixed on version 2.20. Therefore closing this issue.

**Comment by dsarkar** [comment]
@Ein-Tim Thanks for the feedback, forwarded the "FIX CONFIRMED".
