### ISSUE TITLE
Cannot verify corona immunization in Apple Health

### ISSUE THREAD

**Issue by frogg** [corona-warn-app/cwa-app-ios#4140]
iOS Version: iOS 15.4 Beta 1

I was able to add the immunization record through a QR code to Apple Health, however iOS could not verify that the immunization is valid. Is that something that the corona app needs to do?

Might be worth to take a look before this version of iOS gets released. 

![image](https://user-images.githubusercontent.com/5204169/151546262-3c74ce58-2169-41f9-a499-97536c57219d.jpeg)

![image](https://user-images.githubusercontent.com/5204169/151546359-ab016fa0-693d-4ccf-a0d2-635c16faf190.jpeg)

![image](https://user-images.githubusercontent.com/5204169/151546379-85619ae9-807e-495a-8252-9d26b4ead553.jpeg)

---
Internal Tracking ID: [EXPOSUREAPP-7811](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7811)

**Comment by Ein-Tim** [comment]
This feature is only controlled by Apple. As this is a beta software, bugs are to be expected. 
Please give feedback to Apple & close this issue.

**Comment by Ein-Tim** [comment]
Also, for others it works: https://github.com/corona-warn-app/cwa-app-ios/issues/2965#issuecomment-1023974605

**Comment by dsarkar** [comment]
@frogg Thanks for your report. Currently, the wallet is not supported by CWA.
Internal Tracking ID: [EXPOSUREAPP-7811](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7811)

Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by frogg** [comment]
Thanks for the feedback, now, one day later, the button turned blue and I was able to add the certificate.
Not sure what was the problem, but Apple seems to have fixed it in the backend.

![IMG_1226](https://user-images.githubusercontent.com/5204169/151658355-0189dd39-667d-4d1b-945f-c3a2a0bf4cf1.jpg)

I am surprised that the developers of the EU app are not aware of this and have been pushing against such a solution, and now the operating system offers such functionality.
