### ISSUE TITLE
Valid Test appointment QR code is wrongly not supported

### ISSUE THREAD

**Issue by bondskin** [corona-warn-app/cwa-app-ios#4143]
## Avoid duplicates
* [ X ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ X ] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 13 Pro
- iOS version: 15.3
- App version: 2.16.2

## Describe the bug

When trying to scan a new test QR code, I get an error message that the code is not valid.

<img width="420" alt="Bildschirmfoto 2022-01-28 um 13 58 17" src="https://user-images.githubusercontent.com/55050117/151551046-3ea8a508-ca32-4cde-91dc-be8ed347e321.png">

![IMG_E6F701282A8C-1](https://user-images.githubusercontent.com/55050117/151550879-466f7c32-bebe-4736-8e99-e82f42787e20.jpeg)

## Expected behaviour

Valid QR code is accepted or a different error message should appear (e.g. "Your test appointment has been registered already")

## Additional context

I have already a valid and active test result (Schnelltest) in my CWA.
And I used the "EINWILLIGUNG ZUR PERSONALISIERTEN ÜBERMITTLUNG (NAMENTLICHER TESTNACHWEIS)" when I register for the test.

**Comment by thomasaugsten** [comment]
Can you please scan the qr code with a qr code app and provide the first part of the url in this qr code

**Comment by bondskin** [comment]
> Can you please scan the qr code with a qr code app and provide the first part of the url in this qr code

https://s.coronawarn.app?v=1#eyJmbiI6Ik1pY2hhZWwiLCJsbiI....

**Comment by thomasaugsten** [comment]
Can you please provide the complete qr code to me

thomas.augsten@sap.com

**Comment by awendt** [comment]
@thomasaugsten I run into the same problem for every RAT. I'd like to get to the bottom of this. Let me know what I can provide to help investigate this.

**Comment by thomasaugsten** [comment]
It looks like it is a display problem of the qr code. When you open the png of the app directly the app should scan the qr code.
Can you please provide the RAT test provider

**Comment by bondskin** [comment]
for me, my local Pharmacy is using https://www.no-q.info

**Comment by awendt** [comment]
@thomasaugsten I did not know you could open the PNG in the app directly. I tried it but it doesn't work for my QR code.

Are these 2 different issues then?

**Comment by thomasaugsten** [comment]
It sounds like can you please provide the qr code via email?

**Comment by bondskin** [comment]
fyi, a new QR code as of today is working as expected, seems that someone tweaked the visualisation
