### ISSUE TITLE
Value for ‚days since last vaccination‘ incorrect

### ISSUE THREAD

**Issue by eurinb** [corona-warn-app/cwa-app-ios#4149]
## Avoid duplicates
* [ x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x ] Bug is not already reported in another issue

## Technical details

- Device name: iPhone X
- iOS version: 15.2.1
- App version: 2.16.2

## Describe the bug

The number of days since last vaccination is incorrect. I got my third vaccination on 5.1.22 and the app displays: ‚Letzte Impfung vor 389 Tagen‘. 

## Steps to reproduce the issue

1. Go to 'Main screen‘
2. Click on 'Zertifikate'
3. Select the latest certificate
3. Scroll down to 'Impfstatus‘

## Expected behaviour

Display correct number of days since last vaccination.

**Comment by dsarkar** [comment]
Hi @eurinb,

thanks for your report. Could you provide screenshots, please? Black out personal data, please.

Thanks. Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by eurinb** [comment]
I am sorry, there is no error in the app. I just noticed that the error was caused by the pharmacy issuing the QR code. They entered 5.1.21 instead of 5.1.22 as the date of vaccination.
