### ISSUE TITLE
Twitter Report: App shows "Begegnungen an 2 Tagen mit erhöhtem Risiko", however, the contact journal only shows an encounter on one day

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#4151]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: not relevant
- iOS version: 15.3
- App version: 2.16.2

## Describe the bug

The app shows this on the "Status" tab:

<img src="https://user-images.githubusercontent.com/67682506/151694994-1eade800-f581-4c48-835e-b7eaf8a868df.jpeg" width="300">

However, in the contact journal only one day is shown:

<img src="https://user-images.githubusercontent.com/67682506/151695021-8804b8d5-f202-4291-938f-e029b1083f8f.jpeg" width="300"> 
<img src="https://user-images.githubusercontent.com/67682506/151695028-c220bd67-1c32-4516-8374-41ebcf5291cf.jpeg" width="300">

## Steps to reproduce the issue

Not clear

## Expected behaviour

If there were encounters on two days, I'd expect two days are marked in the contact journal.

## Additional context

Maybe there were two increased risk encounters with different persons on the 21.?

---
Internal Tracking ID: [EXPOSUREAPP-11612](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11612)

**Comment by Ein-Tim** [comment]
So, today the second day is shown correctly. I guess this is some kind of race condition which can occur.

**Comment by larswmh** [comment]
Thanks for your report @Ein-Tim. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-11612](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11612)

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode, I don't expect this issue to be addressed anymore. I'm therefore closing this issue.
