### ISSUE TITLE
DOB input field scrolls out of view during entering the DOB when requesting a test certificate

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#4152]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 6s
- iOS version: 15.3
- App version: 2.16.2

## Describe the bug

During entering the DOB for the test certificate, the input field scrolls out of view:

https://user-images.githubusercontent.com/67682506/151712434-8f85f67a-d774-4799-926b-2287e32e1359.mp4

## Steps to reproduce the issue

1. Open the CWA
2. Scroll down to the "Sie lassen sich testen?"
3. Click on "Weiter"
4. Click on "QR-Code scannen"
5. Scan the QR code
6. Click on "Einverstanden"
7. Click on "Einmal teilen"
8. Click in the input field
9. See that the view scrolls to far down

## Expected behaviour

The input field should be visible.

---
Internal Tracking ID: [EXPOSUREAPP-11624](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11624)

**Comment by larswmh** [comment]
Thanks for your report @Ein-Tim. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-11624](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11624)

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@larswmh 

What's the status of this ticket? This is quite an annoying and easy to fix issue.

**Comment by Ein-Tim** [comment]
PR: https://github.com/corona-warn-app/cwa-app-ios/pull/4495

**Comment by Ein-Tim** [comment]
Confirm fixed with version 2.22. Closing.
