### ISSUE TITLE
"Vaccination status: last vaccination XX days ago" can be altered by system clock

### ISSUE THREAD

**Issue by johanneskenkel** [corona-warn-app/cwa-app-ios#4161]
Technical details

- Device name: iPhone SE 2nd gen
- iOS version: 15.3
- App version: 2.16.2

Bug description

When changing the system clock to e.g. 1 month in the past, the statement
"Vaccination status: last vaccination XX days ago" (in German: "Impfstatus: Letzte Impfung vor XX Tagen") shows the number of days from the last vaccination to this newly set time.

When the system clock is set to a date **before** the last vaccination, some overflow happens and a value ~4 billion days is shown (2^32 - a few days).

Steps to reproduce the issue
- vaccinated on 11-4-2021 (corect "days ago": 90)
- set the system clock to one month in the past
- restart Corona-Warn-App
- updated "days ago" shows number around 60

Expected behaviour

"last vaccination XX days ago" should not be possible to tamper with.

Possible Fix

- show a warning in "last vaccination XX days ago" when the system clock is set to "manual"
- remember the highest number of "XX days ago" and use it as a lower constraint for this date
- update "XX days ago" with the risky-encounters-data

**Comment by Ein-Tim** [comment]
Same as https://github.com/corona-warn-app/cwa-documentation/issues/642.

**Comment by Ein-Tim** [comment]
Can this issue be closed?
