### ISSUE TITLE
Apple Wallet Integration

### ISSUE THREAD

**Issue by vmax77** [corona-warn-app/cwa-app-ios#4162]
## Current Implementation

Current Implementation of the vaccination ceritificate requires one to open the app, select certificates and then show the vaccination ceritificate. 

## Suggested Enhancement

It would be much easier to display certificate using an Apple Wallet card as the Wallet card can be invoked by double pressing the power button to bring up the vaccination certificate. This can be implemented using a "Add to Wallet" button on the certificates page. - with more info on the wallet card opening the app. People seemed to have implemented in websites like https://covidpass.marvinsextro.de/, but an official one would be much appreciated. 

## Expected Benefits

- Quick access to vaccination ceritificate 
- Improved usability

**Comment by Ein-Tim** [comment]
This has already been proposed & declined in https://github.com/corona-warn-app/cwa-app-ios/issues/2965.

But, there are good news, see https://github.com/corona-warn-app/cwa-app-ios/issues/2965#issuecomment-1023577482.

I recommend to close this issue.

**Comment by vmax77** [comment]
Duped - Following [#2965 ](https://github.com/corona-warn-app/cwa-app-ios/issues/2965#issuecomment-1023577482)
