### ISSUE TITLE
PCR Test can’t be restored after new installation

### ISSUE THREAD

**Issue by coman1977** [corona-warn-app/cwa-app-ios#4199]
Hello,

My wife had Coronavirus in January 2022 and this was confirmed by a PCR test. The app was allowing her to enter the QR code of the test to get the result.

unfortunately, she uninstalled accidentally the app and now I’m trying to enter again the wrong code but the app said that the test was associated already with this number and I should restore the result from recycle bin which is empty due new installation.

Which procedure shall I follow to restore the pcr result?

thanks,
Liviu

**Comment by Ein-Tim** [comment]
Hi, it is not possible to register this test again, sorry. 

Each test result QR code can only be scanned once. After deleting the test result, it is moved into the recycle bin. However, if you deinstall and then reinstall the app, the test is also deleted from the recycle bin.

**Comment by coman1977** [comment]
Any particular reasoning behind why the QR code can be scanned only once? According to the doctor the test result is available online  as pdf for 21 days online. Why the app can’t restore the PCR test?

**Comment by Ein-Tim** [comment]
Due to data protection each test result QR code can only be scanned once.

**Comment by coman1977** [comment]
Thanks for support

**Comment by coman1977** [comment]
> Due to data protection each test result QR code can only be scanned once.

What do you mean by that. QR code is unique and the owner of my test is my wife. I can understand that a QR code can only be registered with one phone once in CoronaWarnApp but why not allowing to restore it if owner of test requested? What protection are you offering?

**Comment by jucktnich** [comment]
@coman1977 I think the problem is, that if you're app registers a test, the app gets a long term registration token in exchange, but the tests GUID is deleted or otherwise made inaccessible from the server. If you now deinstall the app, the registration token is deleted too and there's no change of re-registering the test.

**Comment by dsarkar** [comment]
Hi @coman1977, 
Test codes can only be scanned once: For example, f it was possible to scan it unlimited times, theoretically somebody could scan it on many devices and if positive tested warn from many devices a lot of people and tamper the system.
