### ISSUE TITLE
Check-Ins gone due to full storage 

### ISSUE THREAD

**Issue by leif5672** [corona-warn-app/cwa-app-ios#4207]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for iOS only
* [x] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 8 Plus
- iOS version: 15.0.1
- App version: 2.17.1

## Describe the bug

When opening the CWA after having a lot of forced hard resprings and some manual reboots due to a full device storage, all Check-Ins are gone from the Check In tab. EDIT: The contact journal as well as the created Check-In QR-Codes are wiped completely as well (only certificates stay).
I am not sure if all collected Random-Bluetooth-IDs are gone as well, as you cannot inspect them as a user.

## Steps to reproduce the issue

1. Fill up your Storage Space to the top until your iPhone is begging you to delete something. At some point hard resprings are occuring during normal usage.
2. Use your iPhone normally, just keep on opening apps, websites etc. in between the hard resprings and use the CWA as usual to Check In etc. Probably optional: Pour in some restarts of the device to make iOS run more smoothly.
3. At some undefined moment, all of your Check-Ins in the Check In tab are gone.

In the screenshot one can see the Check-Ins I have done today. All previous Check-Ins are gone (there were a lot):

![Bug](https://user-images.githubusercontent.com/99078143/153585257-dd645903-9b7e-480c-9e57-e30705f10b8d.jpeg)

## Expected behaviour

No loss of Check-Ins (and perhaps Random-Bluetooth-IDs as well), even if your iPhone is fighting a storage-armageddon.

## Suspected Reason

I could imagine this bug occuring due to the lost data being stored with little priority.

## Additional context

It would be very useful to see/read out and export the Random-Bluetooth-IDs to check if they are lost as well. This would be a general great idea for personal analysis, but I am not sure if this feature is possible.

---
Internal tracking ID: EXPOSUREAPP-10759

**Comment by Ein-Tim** [comment]
Did you have certificates or contact journal entries? Are they gone to?

The received Bluetooth IDs are stored by iOS, so there is a good chance that they were not deleted.

**Comment by leif5672** [comment]
> Did you have certificates or contact journal entries? Are they gone to?
Certificates stay (no bug there), however, the contact journal entries (as well as added people/places) are wiped completely.

> The received Bluetooth IDs are stored by iOS, so there is a good chance that they were not deleted.
> The CWA has no access to the collected Bluetooth beacons.
Well, if there is no way to have a look into this, unfortunately we have to neglect it :(

**Comment by Ein-Tim** [comment]
Might be related to #4134.

**Comment by Ein-Tim** [comment]
@thomasaugsten Do you have a guess how this happens? Is it normal that iOS starts deleting data stored in apps if there is no much free space available?

**Comment by leif5672** [comment]
> Might be related to #4134.

@Ein-Tim Wow, you really have a huge overview over all issues! 🥇👍🏼 Difference in the Bug would be that @7u771e lost his certificates as well according to his description.
Because you have such a great overview: Is there an issue already about the huge lagging while the "data is being downloaded" phase after opening the app? Very annoying when you need to Check-In quickly.

> Is it normal that iOS starts deleting data stored in apps if there is no much free space available?

I am confused by this as well. But we need to keep in mind: Not everything is wiped. Certificates stay and of course in other apps like Signal no vital data is lost. For me it seems to be a CWA-Problem.

**Comment by Ein-Tim** [comment]
> Is there an issue already about the huge lagging while the "data is being downloaded" phase after opening the app? Very annoying when you need to Check-In quickly.

No, I am not aware of such an issue and I am not experiencing this on my devices. But feel free to open a new issue reporting this, in the best case with a screen recording attached!

**Comment by thomasaugsten** [comment]
The resprings leads very likely to the corruption of the separate db of checkins, we will add an error message to receive a detailed information when this happens

**Comment by leif5672** [comment]
> I am not experiencing this on my devices.

Strange; after the here issued Bug, my CWA seems to have a normal starting process again.

**Comment by ndegendogo** [comment]
just a stupid question: 
- can it be that iOS starts to swap data into iCloud under tough memory conditions?
- are the journal entries and the check-ins included in an iCloud backup?

**Comment by ndegendogo** [comment]
> huge lagging while the "data is being downloaded" phase after opening the app

... well ... I see regularly a "noticable" time lag after I open cwa, especially on my older device (iPhone 6 with iOS 12). During this phase it does not respond to any user actions (menu, tab change. etc). It is a bit annoying, but not "huge" (maybe a few seconds).

**Comment by dsarkar** [comment]
FYI PR: https://github.com/corona-warn-app/cwa-app-ios/pull/4389

**Comment by Ein-Tim** [comment]
@dsarkar PR https://github.com/corona-warn-app/cwa-app-ios/pull/4389 only talks about the contact journal. Will there also be an error pop up for the check-ins tab itself?

**Comment by svengabr** [comment]
I have just checked the linked Jira issue.

Jira Ticket is flagged as:
Resolution: `Fixed`
Status: `Completed`
Fix Version/s: `Release 2.21`

Developer comment:
> PR: https://github.com/corona-warn-app/cwa-app-ios/pull/4389

**Comment by Ein-Tim** [comment]
@svengabr 

The PR only talks about the contact journal, could you please re-check with the devs.

**Comment by svengabr** [comment]
@Ein-Tim the Jira Issue had 2 Github issues linked:

https://github.com/corona-warn-app/cwa-app-ios/issues/3680
https://github.com/corona-warn-app/cwa-app-ios/issues/3896

According to the communication it should solve both issues.

No 1
> Reopen because we receive a new report.
> 
> Only data from contact journal was affected.
> 
> I suggest to add an simple UI Error message to inform the user and give us details about the reason of the contact journal db corruption.
> 
> My suggestions for the text ist
> 
> Die Daten Ihres Kontakt-Tagebuchs konnten nicht geladen werden. Fehler: {localizedErrorFromiOS}
> 
> Buttons:
> 
> Ignorieren
> Erneut versuchen
> Tagebuch löschen

No 2
> Receive a new report 
> 
> please considering a detailed error message as soon as possible
> 
> [https://github.com/corona-warn-app/cwa-app-ios/issues/4207](https://github.com/corona-warn-app/cwa-app-ios/issues/4207#issuecomment-1036302213)
