### ISSUE TITLE
App shows "2G-Zertifikat" although the status is shown as 1G+ (Version 2.18)

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#4212]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 13 Simulator
- iOS version: 15.2
- App version: 2.18 (local build) 

## Describe the bug

The app shows "2G-Zertifikat" although the status is shown as 1G+.

<img src="https://user-images.githubusercontent.com/67682506/153749065-01600d1c-decc-46ef-bb4f-5e465bee8938.png" width="300">

## Steps to reproduce the issue

1. Import a 3/3 booster certificate into your CWA
2. Import a test certificate for the same person
3. See that the status is now 1G+, but the app talks about a 2G certificate

## Expected behaviour

The app should show "1G Zertifikat" and not "2G-Zertifikat".

---
Internal Tracking ID: [EXPOSUREAPP-11803](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11803)
Internal Tracking ID: [EXPOSUREAPP-11768](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11768)

**Comment by thomasaugsten** [comment]
This is as intended. The view is a general feature to show a 2G certificate or better and a test certificate in one view and a 1G certificate is also fulfilling the 2G requirements

**Comment by Ein-Tim** [comment]
@thomasaugsten 

But correct me if I'm wrong 1G+ is only shown if a booster vaccination & test is in the app, or?

**Comment by thomasaugsten** [comment]
This is correct

**Comment by Ein-Tim** [comment]
Then it is not showing a 2G certificate so 2G is just wrong here, IHMO & will confuse users.

**Comment by Ein-Tim** [comment]
To add some context here:

I understand the reasoning from a developers perspective but we have to look at this "as a normal user".
What a normal user sees is:
The app is showing "1G+" as the status at the top, but then on the button it is talking about a 2G-certificate.
Now I ask myself the question: Am I allowed to enter 1G+ venues with this? Or only 2G+? Is this a fault by the app?

I understand that it is work to handle the case of 1G+ separate, but if we are now **heavily** improving the Status shown in 2.18, why not take the extra step to do it 100% right so that all users are happy and enjoy the update?

Please at least take it into consideration or discuss with the UA team.

**Comment by dsarkar** [comment]
@Ein-Tim This ticket becomes obsolete. https://github.com/corona-warn-app/cwa-documentation/issues/851#issuecomment-1044189220 and following comment.

**Comment by Ein-Tim** [comment]
@dsarkar 

You were faster than me (-;
Closing this issue.
