### ISSUE TITLE
Improve error message for failed risk check because of missing internet / server timeout

### ISSUE THREAD

**Issue by ndegendogo** [corona-warn-app/cwa-app-ios#4237]
## Avoid duplicates
* [ ] This enhancement request has not already been raised before
* [ ] Enhancement request is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)
* [ ] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation

The risk check consists of two phases:
(1) download the key files from the server.
(2) match the keys with the locally captured exposure traces (ENF) and post-process the resulting exposure windows.

If the first phase fails, I get a generic error message that the check failed, and the suggestion to retry. No hint in which phase the error happened.

## Suggested Enhancement

The error message should indicate that it was the download that failed. In addition to a retry, the suggestion should be also to check the internet connectivity.

## Expected Benefits

Better support for trouble-shooting for the user.

Note: I don't think that a hint to check internet is "too technical" for not-so-technical users (let's take my grandma). In most cases she will know somebody who supports her, and this person can act on the suggestion and check her internet, even with no deeper knowledge of cwa.

## Example of current behavior

I give a detailed example with screenshots of the current behavior below in the comments.
(cwa 2.17.1 / iOS 15.1 / iPhone 13 pro).

---
Internal Tracking ID: EXPOSUREAPP-12057

**Comment by ndegendogo** [comment]
Example of the current behavior
(cwa 2.17.1 / iOS 15.1 / iPhone 13 pro)

(1/4) This morning when I checked-out cwa, I saw an error message of the failed risk check, and the suggestion to retry.

![DED7B73C-C02D-4FB0-87B8-79093DC008EE](https://user-images.githubusercontent.com/6118267/154648152-35d0094f-d9ab-4916-a29b-c0545a08decd.png)

**Comment by ndegendogo** [comment]
(2/4) So I pressed the retry button, and it started the download. But then I again got the same error message. And now the **retry button did not even have any visible effect**.

![B438B28A-0B87-4C33-9B4C-969B989729DF](https://user-images.githubusercontent.com/6118267/154648716-dad6e921-a0f8-426a-80e3-fd0aaf71ca36.png)

**Comment by ndegendogo** [comment]
(3/4) I had seen this behavior before, and I know that closing cwa and swiping it out of memory can recover the button. I did this, and could trigger the risk check - but again it failed with the same error message.

![E2F995C6-9AE4-446D-A7B9-926AC810DBA1](https://user-images.githubusercontent.com/6118267/154648948-efe1eda7-7a59-4ee7-bbc2-701b4796a8ec.png)

![23626806-7856-4D1F-96A5-310E7B9E8721](https://user-images.githubusercontent.com/6118267/154649031-f20e5c61-e325-43c2-adeb-14de69b28eaf.png)

**Comment by ndegendogo** [comment]
(4/4) Finally I noticed that our router had been down last night, and **there was WLAN coverage but no internet**.
So the remedy was to restart WLAN on my device.

***An error message with more details would have helped me a lot.***

**Comment by ndegendogo** [comment]
**I just noticed that the error message already contains a hint on the phase that failed**
"Abgleich mit dem Server ist fehlgeschlagen..."
😅😅

So my request boils down to add a (more prominent) suggestion to check the internet

**Comment by larswmh** [comment]
Thanks for your report @ndegendogo. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-12057](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12057)

---
Corona-Warn-App Open Source Team

**Comment by 30mar** [comment]
will set to obsolete as the effect is only until  31.4.2023
