### ISSUE TITLE
Fehler 13

### ISSUE THREAD

**Issue by xenia71120** [corona-warn-app/cwa-app-ios#4247]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name:
- iOS version:
- App version:

**Comment by xenia71120** [comment]
Es öffnet sich eine Push Mitteilung und dort steht es dann drin

**Comment by Ein-Tim** [comment]
Ich habe dir in https://github.com/corona-warn-app/cwa-app-ios/issues/4163 geantwortet.
Ist dieser Issue auch notwendig?

**Comment by Ein-Tim** [comment]
Can this issue be closed?

**Comment by dsarkar** [comment]
@xenia71120 Thanks for reporting, please continue in https://github.com/corona-warn-app/cwa-app-ios/issues/4163. We are closing this issue as duplicate. Do you still have this issue?

Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@dsarkar You said you would close this issue but it is still open. Would you please close it now?
