### ISSUE TITLE
Incorrect vertical text alignment in red warning tile

### ISSUE THREAD

**Issue by kkopper** [corona-warn-app/cwa-app-ios#4303]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 12 Pro
- iOS version: 15.3.1
- App version: 2.18.1

## Describe the bug

The text in the red warning tile on the main screen is not aligned correctly in the vertical direction, both compared to the horizontal separators (especially for the exposure date) and the icons on the left. The alignment is however correct in the similar popup opened when tapping on the tile. See screenshots below.

## Steps to reproduce the issue

![Screenshot main screen with red warning](https://user-images.githubusercontent.com/18163911/157225361-17be4e68-5814-415a-8119-7d5bc16d4ae1.png)
![Screenshot popup red warning](https://user-images.githubusercontent.com/18163911/157225387-b5cc57f5-f7bd-4c6a-92a7-db81426278b7.png)

## Expected behaviour

The text should be aligned correctly w. r. t. the horizontal separators and the icons.

## Possible Fix

At first glance, the problem seems to be the line break in the first row. After all, green tiles only require a single line for *Keine Risikobegegnungen*, and the alignment was always fine there (unfortunately, I have no screenshot to confirm this).

## Additional context

---
Internal Tracking ID: [EXPOSUREAPP-12161](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12161) duplicates
Internal Tracking ID: [EXPOSUREAPP-11914](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11914)

**Comment by dsarkar** [comment]
@kkopper Thanks for reporting, we will create an internal ticket shortly.

**Comment by larswmh** [comment]
Thanks for your report @kkopper. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-12161](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12161)

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
FYI: PR #4308 is the fix for this issue.
