### ISSUE TITLE
I have a mistake on my corona warn app that I can’t see the Risiko people

### ISSUE THREAD

**Issue by Mxyr-ya** [corona-warn-app/cwa-app-ios#4318]
## Avoid duplicates
* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue

## Technical details

- Device name:
- iOS version:
- App version:

**Comment by Ein-Tim** [comment]
@Mxyr-ya Could you please give us more information what exactly you are missing in the app.

**Comment by Ein-Tim** [comment]
I suggest to close this issue due to missing feedback from the author.
