### ISSUE TITLE
cwa anzeige rot obwohl keine begegnungen stattfanden

### ISSUE THREAD

**Issue by uwesimm** [corona-warn-app/cwa-app-ios#4337]
ich sehe aktuell in der cwa fuer ios (ios15.4 oder 15.3.*), dass seit ca. 9.3. ploetzlich ein "erhoehtes risiko" fuer jeden Tag im Kontakttagebuch steht, obwohl keine Kontakte an diesen Tagen stattfanden.
 
Ich sehe dieses Problem seit meinem Wechsel meines Telefons (iphone->iphone) aber auch andere Familienmitglieder sehen Warnungen fuer jeden Tag obwohl keine Kontakte stattfanden

**Comment by Ein-Tim** [comment]
@uwesimm

Konnte ich deine Frage beantworten? Kann dieser Issue geschlossen werden?

**Comment by uwesimm** [comment]
Es wird wohl so sein, dass jemand in der direkten Nachbarschaft C19 hatte.
