### ISSUE TITLE
Data replay attack of configuration data

### ISSUE THREAD

**Issue by haxxbard** [corona-warn-app/cwa-app-ios#434]
As discussed in #2 this issue is to track the investigation of a possible data replay attack targeting the configuration data.

The scenario: An attacker is able to record the encrypted traffic and replays it to the mobile phone to override current configuration settings with old ones.

**Comment by sebastianpicklum** [comment]
Using TLS >= 1.2 prevents replay attacks by using Message Authenticiation Codes (MAC).

The only thing is that we need to make sure that 0-RTT isn't used.

https://tools.ietf.org/html/rfc5246

**Comment by mh-** [comment]
@sebastianpicklum The context is a MITM attack. This was brought up because Certificate Pinning is not enabled for the CDN server certificates.

**Comment by sebastianpicklum** [comment]
I think adding validity information directly into the configuration data would work. 

Draft code for HTTPClient.swift, given that the payload contains validOnDate and we have time windows of 24h as valid period:
```
let appConfig = try SAP_ApplicationConfiguration(serializedData: package.bin)
guard Calendar.current.isDateInToday(appConfig.validOnDate) else {
					completion(nil)
					return
}
completion(try ENExposureConfiguration(from: appConfig.exposureConfig))
```

**Comment by Ein-Tim** [comment]
Is this still possible with version 1.10.1? Maybe @dsarkar could clarify internally. 

Thanks!

**Comment by heinezen** [comment]
@Ein-Tim As far as I can tell from the original issue, this was already fixed last summer by introducing: https://github.com/corona-warn-app/cwa-app-ios/blob/release/1.12.x/src/xcode/ENA/ENA/Source/Client/Security/CoronaWarnURLSessionDelegate.swift

Internal testing could not replicate the results from the BSI anymore. I don't know if the BSI made their own report after the fix and I'll try to find out more about this. But for the time being, this is considered fixed.

----
Corona-Warn-App Open Source Team
