### ISSUE TITLE
Fehler 13

### ISSUE THREAD

**Issue by Xoxlisa** [corona-warn-app/cwa-app-ios#4347]
## Avoid duplicates
* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue

## Technical details

- Device name:
- iOS version:
- App version:

**Comment by Ein-Tim** [comment]
Hi @Xoxlisa

Könntest du bitte ein bisschen näher beschreiben was das Problem ist & welche Version der App du nutzt?

**Comment by Ein-Tim** [comment]
@larswmh 

I suggest to close this issue due to missing author feedback.

**Comment by larswmh** [comment]
Closing due to missing author feedback
