### ISSUE TITLE
Fehler 13 seit >24

### ISSUE THREAD

**Issue by Leblek22** [corona-warn-app/cwa-app-ios#4348]
## Avoid duplicates
* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue

## Technical details

- Device name:
- iOS version:
- App version:

## Additional context

---
Internal Tracking ID: [EXPOSUREAPP-12056](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12056)

**Comment by Ein-Tim** [comment]
Hi @Leblek22 Nutzt du die neuste Version der App?

**Comment by Leblek22** [comment]
Fehler ist weiter vorhanden. Bekomme einerseits die Aufforderung regelmäßig meinen Status zu checken und wenn ich das dann mache höchstens einmal pro Tag, bekomme ich den Fehler 13. letzter Staus ist mittlerweile 8 Tage her. 
Zwischendurch gab es auch die Fehlermeldung noexposurewibdows... :-(

**Comment by Ein-Tim** [comment]
@Leblek22 

Danke fürs melden! Nochmal: Wir müssten bitte wissen welche Version der App du nutzt & welche iOS-Version, sowie welches iPhone-Modell.
Sonst können wir dir leider nicht helfen.
Dankeschön.

**Comment by Leblek22** [comment]
Es handelt sich um ein IPhone 7,IOS 15.1, Corona warn app Release 2.19

**Comment by Ein-Tim** [comment]
@thomasaugsten Vermutlich wäre hier ein Fehlerbericht hilfreich, oder? Weil eigentlich sollte die App ja den Fehler unterdrücken.

**Comment by Ein-Tim** [comment]
Danke @Leblek22!

**Comment by thomasaugsten** [comment]
Ja wäre hilfreich.
Aber noexposurewindows deutet darauf hin das ein Verbindungsproblem im Netzwerk gibt bei dem vielleicht die https Verschlüsselung unterbrochen ist.

**Comment by Ein-Tim** [comment]
@Leblek22 

Kannst du bitte wie in diesem [Blog](https://www.coronawarn.app/de/blog/2021-05-12-corona-warn-app-version-2-2/) weiter unten beschrieben einen Fehlerbericht aktivieren?
Einfach anschalten und dann für ca. 24h Std. laufen lassen.

**Comment by Leblek22** [comment]
Fehlerbericht ist gestartet,werde ihn morgen Abend senden.

Vielen Dank!

**Comment by Leblek22** [comment]
Guten Abend habe den Fehlerbericht gesendet 
ID A2D99BE96EA9C2F1AE7.
Konnte ab heute Nachmittag den Fehler nicht mehr reproduzieren, da er nicht mehr erschien, nachdem ich einen positiven Test hochgeladen habe.

Vielen Dank für eure Mühe und viele Grüße

**Comment by dsarkar** [comment]
@Leblek22 Danke für das Feedback. Ist der Fehler auch aufgetreten während das Error-Logging lief, oder ist nach dem Starten des Fehlerberichtes der Fehler nicht mehr aufgetreten?

**Comment by dsarkar** [comment]
@Leblek22 Idealerweise bräuchten wir den Fehlerbericht, der lief, während der Fehler auftrat. Ist das ID A2D99BE96EA9C2F1AE7 ?

**Comment by Leblek22** [comment]
Ja.

**Comment by Leblek22** [comment]
Wurde der Fehler gefunden? Kann ich irgendetwas tun?

**Comment by Leblek22** [comment]
Ja, 2.19.04.Gesendet mit der GMX Mail AppAm 18.03.22 um 10:04 schrieb Tim
                
            
            
                
                    Von: "Tim" ***@***.***>Datum: 18. März 2022An: "corona-warn-app/cwa-app-ios" ***@***.***>Cc: "Mention" ***@***.***>,"Leblek22" ***@***.***>Betreff: Re: [corona-warn-app/cwa-app-ios] Fehler 13 seit >24 (Issue #4348)
                
                
Hi @Leblek22 Nutzt du die neuste Version der App?

**Comment by dsarkar** [comment]
@Leblek22 Das Problem besteht weiterhin auf mit CWA Version 2.27? Wenn dem so ist, bitte noch mal Fehlerlogging starten und mindestens 24 h laufen lassen und auch die Fehlermeldung(en) abwarten bevor der Fehlerbericht abgeschickt wird. Im Anschluss bitte die Fehlerbericht ID uns hier mitteilen und in welchem Zusammenhang (wenn offensichtlich) der Fehlerauftritt, z.B. Testregistrieren, Testergebnis abfragen, ect. 

Vielen Dank!

Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@dsarkar I think this issue is stale and should be closed.

**Comment by 30mar** [comment]
will set to obsolete as the effect is only until  31.4.2023
