### ISSUE TITLE
No notification on additional risk encounter

### ISSUE THREAD

**Issue by mss1010** [corona-warn-app/cwa-app-ios#4357]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: iPhone Xs
- iOS version: 15.4
- App version: 2.19

## Describe the bug

I had already red card in the app with one risk encounter on some day. For this red card I got a notification on the iPhone.
A week later, I opened the app again and saw, that the high (red) risk encounters had increased to 2. But for the additional encounter, the app did not show a notification on the iPhone.
I´m sure, that the additional encounter was NOT detected after an update after opening the app manually (this takes usually 30 seconds on my device). The new encounter was already there and was instantly displayed as a total of two high risk encounters after opening the app.

## Expected behaviour

The app should show a notification after every new detected risk encounter. Even if the status does not change (red > red), a new risk encounter is a very relevant information.

## Additional context

Internal Tracking ID: [EXPOSUREAPP-12100](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12100)

**Comment by Ein-Tim** [comment]
This will be implemented in the next version: https://github.com/corona-warn-app/cwa-app-ios/pull/4320

**Comment by mss1010** [comment]
Ok, so I would close the issue after the update is released, or let the admins here handle it.

**Comment by Ein-Tim** [comment]
@mss1010 Version 2.20's out. Would you like to close this issue now?

**Comment by mss1010** [comment]
Ok
