### ISSUE TITLE
Overridden notification token in `ExposureSubmissionNavigationController`

### ISSUE THREAD

**Issue by Tantalum73** [corona-warn-app/cwa-app-ios#44]
In [ExposureSubmissionNavigationController](https://github.com/corona-warn-app/cwa-app-ios/blob/development/src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionNavigationController.swift#L152), `keyboardWillShowObserver` and `keyboardWillHideObserver` will store tokens for a registered notification-center observation.

However, a third kind of notification is handled, `keyboardWillChangeFrameNotification` and its token is __also__ stored in `keyboardWillHideObserver`. 

Thus, the registered block will not be de-registered.

**Comment by fbernutz** [comment]
I think this can be closed since the PR #46 is already merged?

**Comment by Tantalum73** [comment]
Thank you for the good work 👏🏼

You’re right, this can be closed now.
