### ISSUE TITLE
[HELP WANTED][README] Text / Translations

### ISSUE THREAD

**Issue by inf2381** [corona-warn-app/cwa-app-ios#440]
Dear contributers,

as we are getting into the final stage regarding all texts and translations within the app, we would appreciate your support in this area!
If you spot anything unsual within the German / English text files, please report your findings as a comment in this issue.

Since the texts and translations are not provided by the development team but by a dedicated stream and have to be approved by the stakeholders first (depending on the change), it is easier for the stream to check this issue for findings and provide fixes when necessary.
Please don't create pull requests directly, the string files will be overwritten when we import changes from our translation stream.

Please be aware that all legal texts including their translations (Terms of Use, Publication Details, Data Privacy Information, Legal Notices) are handled separately,
Neither developers nor the text / translation stream have any influence on spelling or wording, as these texts require dedicated approval.
We will certainly collect your suggestions and pass them on, but it can take time until improvements are included (if at all).

Thank you for your your help!
Best regards,
Marc

**Comment by monikaschmitt** [comment]
Spelling mistake in the overview section: exhange > exchange 
![image](https://user-images.githubusercontent.com/66128524/84363649-5623fb00-abcf-11ea-9e2e-adf3fd43c1b6.jpeg)

**Comment by codebarista** [comment]
Apart from the fact that the amount of text is confusing and some of the texts raise more questions than answers for the common people, the (partly inconsistent) wording could be a bit more user-centric. You require a lot of (technical) prior knowledge and you even change terms within a single sentence. 

**Example**
> Die Risiko-Ermittlung funktioniert, indem Ihr **Handy** per Bluetooth verschlüsselte Zufallscodes anderer Nutzerinnen und Nutzer empfängt und Ihren eigenen Zufallscode an deren **Smartphones** weitergibt. Die Funktion lässt sich jederzeit wieder deaktivieren.
> 
> Die verschlüsselten Zufallscodes geben nur Auskunft über das Datum, die Dauer und die anhand der Signalstärke berechnete Entfernung zu Ihren Mitmenschen. Persönliche Daten wie Name, Adresse oder Aufenthaltsort werden zu keiner Zeit erfasst. Konkrete Rückschlüsse auf Personen sind nicht möglich.

Note: The cell phones exchange the codes, not the users

**Hallway Testing**
As a developer with a technical background, I understand what you want to communicate. But, neither my 70-year-old mother, nor my 40-year-old sister, a teacher, nor my 13-year-old nephew really understand what is going on in the app. For them, that's an app for nerds with a diploma in Bluetooth.

**Possible simplification**
> Für die Risikoermittlung einer möglichen Infektion tauschen aktivierte Smartphones in erreichbarer Nähe zufällige Nummern aus. Zu einer solch anonymen Nummer werden Datum, Kontaktdauer und Entfernung sicher und zeitlich begrenzt in der App gespeichert.

**Suggestions**
- write less personally, judgmentally, reproachfully, dramatically and overly didactic
- instead of "warning" others, you might want to "inform" others
- "unerkannt bleiben" has a negative connotation towards crime
- my impression is that too many hyphens are used overall

Example:
> Da Sie Ihre Begegnungs-Aufzeichnung noch nicht lange genug aktiviert haben, konnten wir für Sie kein Infektionsrisiko berechnen.

Suggestion:
> Ihr Infektionsrisiko konnte aufgrund der kurzen Aufzeichnungsdauer noch nicht berechnet werden.

Btw, the related button for "Begegnungs-Aufzeichnung" is labeled with "Risiko-Ermittlung".

Example:
> Helfen Sie mit, die Infektionskette zu durchbrechen und warnen Sie Andere.

Suggestion:
> Helfen Sie mit, die Infektionskette zu durchbrechen und übermitteln Sie Ihre Kontaktcodes.

Note: Instead of teaching someone about correct behaviour, you may just want to identify a risk in this area or the entire app.

**Separation of concerns**
So, my recommendation to stakeholders is to Keep It Stupid and Simple and leave app development to developers. Let the app be an app and all the information and advice a website.

**Comment by n-thumann** [comment]
https://github.com/corona-warn-app/cwa-app-ios/blob/16c1d5b2ae78ca45adf2108b88d09f33e68b344b/src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings#L169
"[...] in Ihrer Nähe [...]" instead of "[...] in ihrer Nähe [...]": wrong Capitalization

https://github.com/corona-warn-app/cwa-app-ios/blob/16c1d5b2ae78ca45adf2108b88d09f33e68b344b/src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings#L189
"[...] stimmen Sie mit Antippen des Buttons „Risiko-Ermittlung aktivieren“ zu." instead of "[...] stimmen Sie mit Antippen des Buttons: Risiko-Ermittlung aktivieren zu.": enhanced quoting

"[...] können, müssen Sie [...]" instead of "[...] können müssen Sie [...]": missing comma

https://github.com/corona-warn-app/cwa-app-ios/blob/9b7601e37009c0baafeaea90d197a277e3b9d632/src/xcode/ENA/ENA/Resources/Localization/de.lproj/usage.html#L123
https://github.com/corona-warn-app/cwa-app-ios/blob/9b7601e37009c0baafeaea90d197a277e3b9d632/src/xcode/ENA/ENA/Resources/Localization/de.lproj/usage.html#L160
"Welche Funktionen hat die App?" instead of "Welche Funktionen hat die APP?": wrong Capitalization

**Comment by inf2381** [comment]
> ## Current Implementation
> During the onboarding process, the app shows a view informing about what happens when you are tested positive. The text on this page says [_People whose encrypted random IDs your device has collected will now receive a warning..._](https://github.com/corona-warn-app/cwa-app-ios/blob/ce3299e0a37caea5c8419c3a02133e1f8c748224/src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings#L208) in the English localization and [_Die Personen, deren verschlüsselte Zufallscodes Sie gesammelt haben, erhalten nun eine Warnung..._](https://github.com/corona-warn-app/cwa-app-ios/blob/ce3299e0a37caea5c8419c3a02133e1f8c748224/src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings#L208) in the German localization.
> 
> According to my understanding of the protocol, people who have collected an encrypted random ID of my device are notified. The current text may allow the interpretation, that the IDs my device collects are shared with the server in case of a positive test.
> 
> ## Suggested Enhancement
> State clearly that people who have collected an ID of my device are notified.

https://github.com/corona-warn-app/cwa-app-ios/issues/628#issue-639418920

**Comment by muellermartin** [comment]
As mentioned in PR #637, there is a small typo in the German privacy policy:

"auch als Zufallscodes zu bezeichnet" → "auch als Zufallscodes bezeichnet"
https://github.com/corona-warn-app/cwa-app-ios/blob/a6b885f42f9444d890210a4f59d62041ca0c834d/src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html#L274

**Comment by mynchau** [comment]
Adding https://github.com/corona-warn-app/cwa-app-ios/issues/642 to this issue here.

**Comment by inf2381** [comment]
Adding #641

**Comment by njashley** [comment]
Untranslated section of EN text.

https://github.com/corona-warn-app/cwa-app-ios/blob/ac53b8534fd231ca696eb936c8ea02307928bb5f/src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings#L537-L541

"Home_Risk_Inactive_Activate_Item_Unknown_Title" = "Unknown Risk";
"Home_Risk_Inactive_Activate_Item_Low_Title" = "Low Risk";
"Home_Risk_Inactive_Activate_Item_High_Title" = "High Risk";

Forced DE link on websites

https://github.com/corona-warn-app/cwa-app-ios/blob/ac53b8534fd231ca696eb936c8ea02307928bb5f/src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings#L740

"InviteFriends_ShareUrl" = "https://www.coronawarn.app/";
or
"InviteFriends_ShareUrl" = "https://www.coronawarn.app/en/";

https://github.com/corona-warn-app/cwa-app-ios/blob/ac53b8534fd231ca696eb936c8ea02307928bb5f/src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings#L762

Link redirects to DE version - have EN reditect link setup? (e.g. https://www.bundesregierung.de/corona-warn-app-faq-en)
https://www.bundesregierung.de/breg-de/themen/corona-warn-app/corona-warn-app-englisch/corona-warn-app-faq-1758636

**Comment by seb-1204** [comment]
I, and other suggest to replace Mundschutz to "Mund-Nasen-Schutz" or "Mund-Nasen-Bedeckung" in "ExposureDetection_Guide_Mask"

**Comment by bkrannich** [comment]
https://github.com/corona-warn-app/cwa-app-ios/blob/042b3e9bbff5eac85f5b7f522e90d66d9f3e48d3/src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings#L876 talks about "mit anderen CWA-Nutzern teilen". As far as I could see, the abbreviation CWA is used nowhere else in the UI (additionally, it seems like the English and Turkish texts talk about "app users").

Suggestions:
* Change the text to "mit anderen Corona-Warn-App-Benutzern teilen." ["Corona-Warn-App" is used in other UI strings]
* Change the text to "mit anderen App-Benutzern teilen." [matches the version in other languages]
* Change the text to "mit anderen Benutzern teilen."

**Comment by ferdinand** [comment]
@bkrannich I've already reported that.  Unfortunately one gets the impression that comments on this issue disappear into a black hole unheard by the maintainers.

**Comment by bkrannich** [comment]
@ferdinand: Ah, sorry, missed to check the rest of this thread for duplicates. Given the initial description of the process of text changes by @inf2381, I can imagine that these types of changes taking longer than they would if developers would have the ability to change strings directly.

**Comment by kaluju** [comment]
> Here’s my feedback on the German localisation:
> 
> https://github.com/corona-warn-app/cwa-app-ios/blob/5f76a4facb4f93a7be91118a70521bda54beee88/src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings#L14
> 
> sodass > damit **--> changed**
> 
> https://github.com/corona-warn-app/cwa-app-ios/blob/5f76a4facb4f93a7be91118a70521bda54beee88/src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings#L171
> 
> Placeholder that should be replaced. **--> replaced**
> 
> https://github.com/corona-warn-app/cwa-app-ios/blob/5f76a4facb4f93a7be91118a70521bda54beee88/src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings#L173
> 
> pseudonym > pseudonymisiert **--> changed**
> Second /n missing after the address.
> 
> https://github.com/corona-warn-app/cwa-app-ios/blob/5f76a4facb4f93a7be91118a70521bda54beee88/src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings#L189
> 
> https://github.com/corona-warn-app/cwa-app-ios/blob/5f76a4facb4f93a7be91118a70521bda54beee88/src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings#L191
> get
> For ellipses there’s an own Unicode character (…), which is probably better for accessibility.
> 
> https://github.com/corona-warn-app/cwa-app-ios/blob/ac53b8534fd231ca696eb936c8ea02307928bb5f/src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings#L441
> 
> Should be translated to German. --> changed to "Fehler bei der Schlüsselübermittlung"
> 
> https://github.com/corona-warn-app/cwa-app-ios/blob/ac53b8534fd231ca696eb936c8ea02307928bb5f/src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings#L585
> 
> “die App **nicht** haben” or “die App **nicht installiert** haben” **--> changed**
> 
> https://github.com/corona-warn-app/cwa-app-ios/blob/ac53b8534fd231ca696eb936c8ea02307928bb5f/src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings#L636
> 
> ellipsis Unicode character
> 
> https://github.com/corona-warn-app/cwa-app-ios/blob/ac53b8534fd231ca696eb936c8ea02307928bb5f/src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings#L716
> 
> pseudonym > pseudonymisiert **--> changed**
> 
> https://github.com/corona-warn-app/cwa-app-ios/blob/ac53b8534fd231ca696eb936c8ea02307928bb5f/src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings#L718
> 
> Placeholder that should be replaced. **--> replaced**
> 
> https://github.com/corona-warn-app/cwa-app-ios/blob/ac53b8534fd231ca696eb936c8ea02307928bb5f/src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings#L829
> 
> Not sure if users know what CWA stands for. **--> changed to "App-Nutzern"**
> 
> In general, I’m not sure about the heavy use of hyphens. In my opinion it should be Geräteeinstellungen not Geräte-Einstellungen, Risikoermittlung not Risiko-Ermittlung, Begegnungsaufzeichnung not Begegnungs-Aufzeichnung, etc. 

**--> The heavy use of hyphens is due to the fact that the app tries to use Leichte Sprache, simple language. You can find more information here https://de.wikipedia.org/wiki/Leichte_Sprache or here https://www.bundesregierung.de/breg-de/leichte-sprache**

**Comment by kaluju** [comment]
> https://github.com/corona-warn-app/cwa-app-ios/blob/042b3e9bbff5eac85f5b7f522e90d66d9f3e48d3/src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings#L876
> 
> talks about "mit anderen CWA-Nutzern teilen". As far as I could see, the abbreviation CWA is used nowhere else in the UI (additionally, it seems like the English and Turkish texts talk about "app users").
> Suggestions:
> 
> * Change the text to "mit anderen Corona-Warn-App-Benutzern teilen." ["Corona-Warn-App" is used in other UI strings]
> * Change the text to "mit anderen App-Benutzern teilen." [matches the version in other languages] --> **changed to this suggestion**
> * Change the text to "mit anderen Benutzern teilen."

**Comment by kaluju** [comment]
> https://github.com/corona-warn-app/cwa-app-ios/blob/ac53b8534fd231ca696eb936c8ea02307928bb5f/src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings#L817
> 
> _erfolgt ungefähr alle zwei Stunden automatisch_**--> changed**
> instead
> _erfolgt automatisch ungefähr alle zwei Stunden_ 
> 
> https://github.com/corona-warn-app/cwa-app-ios/blob/5f76a4facb4f93a7be91118a70521bda54beee88/src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings#L185
> 
> _Apple “ aktivieren_
> there is something missing in between those quotation marks **--> fixed**
> 
> https://github.com/corona-warn-app/cwa-app-ios/blob/5f76a4facb4f93a7be91118a70521bda54beee88/src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings#L825
> 
> _Corona-Warn-App-Nutzern_
> instead
> _CWA-Nutzern_ **--> changed to App-Nutzern**
> 
> https://github.com/corona-warn-app/cwa-app-ios/blob/ac53b8534fd231ca696eb936c8ea02307928bb5f/src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings#L602
> 
> _Zufallscodes_ -**-> changed**
> instead
> _Zufallcodes_

**Comment by kaluju** [comment]
> https://github.com/corona-warn-app/cwa-app-ios/blob/16c1d5b2ae78ca45adf2108b88d09f33e68b344b/src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings#L169
> 
> 
> "[...] in Ihrer Nähe [...]" instead of "[...] in ihrer Nähe [...]": wrong Capitalization **--> fixed**
> https://github.com/corona-warn-app/cwa-app-ios/blob/16c1d5b2ae78ca45adf2108b88d09f33e68b344b/src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings#L189
> 
> 
> "[...] stimmen Sie mit Antippen des Buttons „Risiko-Ermittlung aktivieren“ zu." instead of "[...] stimmen Sie mit Antippen des Buttons: Risiko-Ermittlung aktivieren zu.": enhanced quoting **--> fixed**
> "[...] können, müssen Sie [...]" instead of "[...] können müssen Sie [...]": missing comma **--> fixed**
> 
> https://github.com/corona-warn-app/cwa-app-ios/blob/9b7601e37009c0baafeaea90d197a277e3b9d632/src/xcode/ENA/ENA/Resources/Localization/de.lproj/usage.html#L123
> 
> 
> https://github.com/corona-warn-app/cwa-app-ios/blob/9b7601e37009c0baafeaea90d197a277e3b9d632/src/xcode/ENA/ENA/Resources/Localization/de.lproj/usage.html#L160
> 
> 
> "Welche Funktionen hat die App?" instead of "Welche Funktionen hat die APP?": wrong Capitalization **--> Unfortunately, this is a legal text and it can't be changed by me directly. I have forwarded the comment to the people responsible.**

**Comment by kaluju** [comment]
> As mentioned in PR #637, there is a small typo in the German privacy policy:
> 
> "auch als Zufallscodes zu bezeichnet" → "auch als Zufallscodes bezeichnet" **--> Unfortunately, this is a legal text and it can't be changed by me directly. I have forwarded the comment to the people responsible.**

> https://github.com/corona-warn-app/cwa-app-ios/blob/a6b885f42f9444d890210a4f59d62041ca0c834d/src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html#L274

**Comment by kaluju** [comment]
> I, and other suggest to replace Mundschutz to "Mund-Nasen-Schutz" or "Mund-Nasen-Bedeckung" in "ExposureDetection_Guide_Mask"

**--> changed to Mund-Nasen-Schutz**

**Comment by kaluju** [comment]
> Spelling mistake in the overview section: exhange > exchange
> ![image](https://user-images.githubusercontent.com/66128524/84363649-5623fb00-abcf-11ea-9e2e-adf3fd43c1b6.jpeg)

@monikaschmitt fixed it

**Comment by kaluju** [comment]
> Untranslated section of EN text. **--> fixed**
> 
> https://github.com/corona-warn-app/cwa-app-ios/blob/ac53b8534fd231ca696eb936c8ea02307928bb5f/src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings#L537-L541
> 
> "Home_Risk_Inactive_Activate_Item_Unknown_Title" = "Unknown Risk";
> "Home_Risk_Inactive_Activate_Item_Low_Title" = "Low Risk";
> "Home_Risk_Inactive_Activate_Item_High_Title" = "High Risk";
> 
> Forced DE link on websites **--> changed to EN**
> 
> https://github.com/corona-warn-app/cwa-app-ios/blob/ac53b8534fd231ca696eb936c8ea02307928bb5f/src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings#L740
> 
> "InviteFriends_ShareUrl" = "https://www.coronawarn.app/";
> or
> "InviteFriends_ShareUrl" = "https://www.coronawarn.app/en/";
> 
> https://github.com/corona-warn-app/cwa-app-ios/blob/ac53b8534fd231ca696eb936c8ea02307928bb5f/src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings#L762
> 
> Link redirects to DE version - have EN redirect link setup? (e.g. https://www.bundesregierung.de/corona-warn-app-faq-en)
> https://www.bundesregierung.de/breg-de/themen/corona-warn-app/corona-warn-app-englisch/corona-warn-app-faq-1758636 **--> changed to EN**

**Comment by kaluju** [comment]
@inf2381  I tried to answer all the feedback we got and I incorporated it. In my opinion, we could close this issue.

**Comment by bkrannich** [comment]
@inf2381: I just updated to version 1.1.1, but it looks like (some of) the text suggestions taken over by @kaluju haven't made it into this version. Any forecast on when these changes will be reflected? Thanks in advance.

**Comment by inf2381** [comment]
@bkrannich Due to a lot of discussions with too many stakeholders, we merged our development branch into staging 3 weeks ago. That commit + bugfixes is now available as 1.1.1. The updated texts and other features will be shipped with version 1.2.x Hopefully, it doesn't take three weeks this time to get this shipped.

**Comment by heinezen** [comment]
Since this discussion was relevant for a much older release, I will close this issue.

----
Corona-Warn-App Open Source Team
