### ISSUE TITLE
Risk check not successfull

### ISSUE THREAD

**Issue by ndegendogo** [corona-warn-app/cwa-app-ios#4408]
## Avoid duplicates
* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 13 pro
- iOS version: 15.2
- App version: 2.19.1 (0)

## Steps to reproduce the issue

My last successful risk check was today at 16:04. Now it is 21:34, more that 4 hours later. When I open cwa, it starts a risk check, but then shows still the last check was at 16:04.
It looks like the check is not successful or aborted before it is finished.

Note: I have already tried to swipe cwa out of memory - this helped sometimes in the past but today it does not help.

## Expected behaviour

Successfull risk check

**Comment by Ein-Tim** [comment]
Last successful check for me: 20:41h.

Anything helpful in an error log?

**Comment by ndegendogo** [comment]
YES - just tried again, now successfull (22:51).
Yesterday I had a check at 21:43; and today 4 successful checks till 16:04.

**Comment by Ein-Tim** [comment]
Nice to hear that it works again :D
Don't forget to update to 2.20.3 😉

**Comment by Ein-Tim** [comment]
@ndegendogo Do you still need this issue open?

**Comment by ndegendogo** [comment]
> Do you still need this issue open?

@Ein-Tim not really ... but I had planned to have a look at my error log and report if I find anything interesting what happened.
I'll try to find time for that on the weekend....

**Comment by Ein-Tim** [comment]
@ndegendogo No rush, as you & @dsarkar noticed, I finally found time to do some housekeeping in this repo.

**Comment by Ein-Tim** [comment]
@ndegendogo Please close this issue now. There has not been any activity here for a prolonged period of time.

**Comment by ndegendogo** [comment]
@Ein-Tim thanks for your reminder.

Indeed, it is time to close this ticket. **cwa has been very reliable in the last months.** 🎉🎉🎉
