### ISSUE TITLE
Tests are no longer shown in the contact journal

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#4410]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Not important
- iOS version: Not important
- App version: 2.20.3

## Describe the bug

It seems like there is an issue with the storage of test results in the contact journal, introduced with version 2.20. 

## Steps to reproduce the issue

1. Register a RAT in the app
2. Wait till the result is available
3. Take a look at the contact journal and notice that the result is not shown there

## Expected behaviour

Result should be shown in the contact journal.

## Additional context

This report is based on multiple reports on Twitter:
- https://twitter.com/betty91119/status/1509795827488804864?s=20&t=bBKk6EVuhgzVkBOg-_8dcA
- https://twitter.com/wutti/status/1509607741526052879?s=20&t=bBKk6EVuhgzVkBOg-_8dcA
- https://twitter.com/bembeltogo/status/1509489892258107397?s=20&t=bBKk6EVuhgzVkBOg-_8dcA

[Jira](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12401)

**Comment by Ein-Tim** [comment]
Just confirmed this issue on my own device. 

## Technical details

- Device name: iPhone XR
- iOS version: 15.4.1
- App version: 2.20.3

**Comment by ndegendogo** [comment]
Same here.
cwa 2.20.3 (0) / CCL 2.0.0 / iOS 15. / iPhone 13 Pro

**Comment by fernandonajera** [comment]
Same here

**Comment by Ein-Tim** [comment]
According to the [@coronawarnapp](https://twitter.com/coronawarnapp/) Twitter account, this bug will be fixed soon: https://twitter.com/coronawarnapp/status/1510875750613848067?s=21&t=PyQALfczJjVfkYAeAAI7yQ

**Comment by dsarkar** [comment]
FYI PR https://github.com/corona-warn-app/cwa-app-ios/pull/4383

**Comment by Ein-Tim** [comment]
This has been fixed.
