### ISSUE TITLE
Cannot launch cwa after upgrade to 2.20.3

### ISSUE THREAD

**Issue by ndegendogo** [corona-warn-app/cwa-app-ios#4416]
## Avoid duplicates
* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 8
- iOS version: 14.4.1
- App version: 2.20.3

## Steps to reproduce the issue

Today in the morning I pressed the cwa icon to launch cwa. I saw the "updating" animation (you know what I mean?) and then happened ... nothing. I tried again, but it just did not launch.
I was able to start it via the shortcut (show certificate), and it showed the "new functions" dialog for 2.20. But the "normal way" to launch cwa does no longer work.

Yesterday evening I could launch it successfully, my risk status is green, and it announced a fresh green contact.
According to my ENF log there was another successfull risk check today at 07:41 (= from background, before the update)

## Expected behaviour

Launch cwa successful by pressing the icon

## Additional context

I swiped cwa out of memory - this did not help.

- I will now try to reboot the device
- I would check for crash logs - but where do I find them?
- I can offer to send you my error log and/or check it myself

Any more ideas?

---
Internal Tracking ID: [EXPOSUREAPP-12602](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12602)

**Comment by ndegendogo** [comment]
Note: usually I don't see the "updating animation" - usually it just silently updates in the background.

**Comment by Ein-Tim** [comment]
From which version did you update?

**Comment by ndegendogo** [comment]
Cannot tell for sure. I have auto-update active and usually it updates late. So, could be from 2.19, or maybe from 2.20.x, I don't know.

Maybe the error log gives more details.

**Comment by Ein-Tim** [comment]
> I would check for crash logs - but where do I find them?

Under "Einstellungen" -> "Datenschutz" -> "Analyse & Verbesserungen" -> "Analysedaten" 

search for an entry with the title "ENA" in it.

**Comment by ndegendogo** [comment]
@Ein-Tim Thanks!

Unexpectedly, there is no fresh crash log with ENA.
Actually, I checked the dates of *all* crash logs, and none of today ... strange ...

**Comment by Ein-Tim** [comment]
If this is a bug in iOS, you would probably have to look through all these other logs, but I hardly understand them. 

AFAIK there are tools to analyze them.

**Comment by dsarkar** [comment]
@ndegendogo Thanks for the report, we will create an internal ticket.

**Comment by ndegendogo** [comment]
> if this is a bug in iOS, you would probably have to look through all these other logs, but I hardly understand them.
AFAIK there are tools to analyze them.

If this was a bug in iOS I hope very much that it recovers with the reboot. (I plan to try this today after work when I am back in my WLAN.)

**Comment by ndegendogo** [comment]
All is well again after the reboot!
And it did even perform a risk check from background today at 19:55 / before the reboot.

**Comment by ndegendogo** [comment]
@Ein-Tim by the way, I had a look at my error log.

> From which version did you update?

The previous version was 2.19.1.

Also I see no log entry corresponding to my failed launching attempts. It looks indeed as if iOS performed the update to 2.20.3, but somehow "choked" on the icon, or on the launching link from the icon to the app 🤷🤷🤷

Closing as fixed.
