### ISSUE TITLE
What happens when I reset "Location and Privacy settings"?

### ISSUE THREAD

**Issue by iDjay** [corona-warn-app/cwa-app-ios#4424]
I have to reset my "Location and Privacy settings" on iOS 15.4.1 what will happen to my exposure notifications? Will they be deleted too? I know from a friend of mine, that it gets disabled and he has to enable it afterwards again, but he couldn't confirm if something got deleted. Maybe someone can test it on a second iPhone?

**Comment by Ein-Tim** [comment]
I can test it on a secondary device in a few hours, but I don't think that something will be deleted.

**Comment by Ein-Tim** [comment]
@dsarkar I don't think a new FAQ entry should be added, this is a very specific question and as resetting does not have any influence, users can safely do this without even thinking about the CWA.

**Comment by Ein-Tim** [comment]
@dsarkar Coule you please either close this issue or label as `ready to close`?
