### ISSUE TITLE
Text alignment contact diary

### ISSUE THREAD

**Issue by jajoho** [corona-warn-app/cwa-app-ios#4457]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 11 Pro
- iOS version: 15.4.1
- App version: 2.20.2

## Describe the bug

When a day in the contact diary contains a day with an red alert the text alignment for day and date is wrong

## Steps to reproduce the issue

Have a day with an alert and one without in your contact diary

1. Go to contact diary

## Expected behaviour

Text should align the same if alert is presented or not

## Possible Fix

Change text alignment

![7A9DB7F4-697E-40AF-A546-CB7315164FDE](https://user-images.githubusercontent.com/15175599/163484685-90c67234-c05a-4d94-8b7a-e28b0dde0c8b.jpeg)

---
Internal Tracking ID: [EXPOSUREAPP-12879](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12879)

**Comment by ndegendogo** [comment]
@jajoho I am not sure if I understand what you mean. The lines are **left-aligned**. On the right side there is no alignment. Independent if you have a red warning or not.

**Comment by ndegendogo** [comment]
![76C871C4-96D2-46B6-8384-DA7E29DBB140](https://user-images.githubusercontent.com/6118267/163942127-21277bfd-8dad-4ade-8e07-b463fc4af3a0.jpeg)

**Comment by Ein-Tim** [comment]
@ndegendogo 

If I understand the OP correctly the problem is not the alignment x-wise but y-wise (if there is a warning, the text is not in the middle of the box).

**Comment by jajoho** [comment]
@Ein-Tim @ndegendogo 
Yes exactly. That’s what I was trying to report

**Comment by larswmh** [comment]
Thanks for your report @jajoho. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-12879](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12879)

---
Corona-Warn-App Open Source Team

**Comment by 30mar** [comment]
@larswmh this was set to obsolete as per the attached jira ticket
