### ISSUE TITLE
App uses wrong FAQ link `hc_prefix_invalid` instead of `hc_invalid_prefix`

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#4461]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone XR
- iOS version: Not important
- App version: 2.21

## Describe the bug

The CWA iOS app uses a wrong FAQ link here: 
https://github.com/corona-warn-app/cwa-app-ios/blob/54414c24d835b4d5b95e07e16f8ab1718f06388c/src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.links.strings#L31

## Steps to reproduce the issue

(Easiest way):
1. Register a certificate in the app
2. Scan the QR code of the register certificate again
3. Click the link to the FAQ
4. See that you are stranded there without any information 

## Expected behaviour

The app should link to the working FAQ entry with the anchor: `hc_invalid_prefix`

## Possible Fix

Change the code here: 
https://github.com/corona-warn-app/cwa-app-ios/blob/54414c24d835b4d5b95e07e16f8ab1718f06388c/src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.links.strings#L31

**Comment by Ein-Tim** [comment]
Corresponding website issue: https://github.com/corona-warn-app/cwa-website/issues/2792

**Comment by Ein-Tim** [comment]
@dsarkar I would like to provide a PR for this, changing the link from `hc_prefix_invalid` to `eu_dcc`.
Could you let me know if such a change would be accepted. Keep in mind that I would also like to add a FAQ redirect, but I still think the iOS app should be fixed in this regard.

**Comment by MikeMcC399** [comment]
- See my comment in https://github.com/corona-warn-app/cwa-website/issues/2792#issuecomment-1102932547

This issue needs investigation. At this time the website has some issues displaying selected articles correctly under some circumstances.

**Comment by Ein-Tim** [comment]
@MikeMcC399 The problem is the word order in the link from the iOS app. 

The iOS app uses the (invalid) link: https://www.coronawarn.app/de/faq/#hc_prefix_invalid
The website holds an FAQ entry with the link: https://www.coronawarn.app/en/faq/results/#hc_invalid_prefix

**Comment by Ein-Tim** [comment]
@MikeMcC399 You said in your comment https://github.com/corona-warn-app/cwa-website/issues/2792#issuecomment-1102932547 that you think `eu_dcc` would be the wrong URL for troubleshooting here.
Probably, as I know understand that the issue is not that the FAQ entry has been deleted but only the link in the iOS app code is wrong, this is not so relevant anymore, but as I [commented on your issue ](https://github.com/corona-warn-app/cwa-app-android/issues/5099#issuecomment-1102928270), the iOS app has only one general error link, so I'm unsure if a link to https://www.coronawarn.app/en/faq/results/#hc_invalid_prefix is really appropriate here, as the iOS app also shows this link in the case that a certificate is already registered. 

I will think about this.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

Probably it will be easiest to resolve this mismatch by making changing to the website.

**Comment by Ein-Tim** [comment]
@MikeMcC399 I agree. Closing this issue as it should be fixed on the website.
