### ISSUE TITLE
Add different FAQ links for different certificate issues (prefix_invalid, already registered, etc.)

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#4463]
## Avoid duplicates
* [X] This enhancement request has not already been raised before
* [X] Enhancement request is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)
* [X] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation

Currently, the iOS app only has one link defined, which is always shown if there was an error registering certificates:
https://github.com/corona-warn-app/cwa-app-ios/blob/54414c24d835b4d5b95e07e16f8ab1718f06388c/src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.links.strings#L31

## Suggested Enhancement

Align the behavior of the iOS app to the one of the [Android app](https://github.com/corona-warn-app/cwa-app-android/blob/c7292d5f93348b69ef335237a7e6d8d7ed622b5b/Corona-Warn-App/src/main/res/values/links.xml#L23-L26) and include two, better three links:

1. Already registered error - link to FAQ entry https://www.coronawarn.app/en/faq/results/#hc_already_registered
2. Prefix_invalid error - link to https://www.coronawarn.app/en/faq/results/#hc_invalid_prefix
3. Another error - link to https://www.coronawarn.app/en/faq/results/#support_certificates

## Expected Benefits

Users are presented with really helpful information instantly and not only after searching for it in the FAQ. 

---
Internal Tracking ID: [EXPOSUREAPP-12984](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12984)

**Comment by larswmh** [comment]
Thanks for your enhancement request @Ein-Tim. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-12984](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12984)

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@larswmh / @dsarkar Could you please check if such a change could be included in one of the next releases?

**Comment by larswmh** [comment]
> Could you please check if such a change could be included in one of the next releases?

@Ein-Tim We can not assure that this will be included in one of the next releases, but be assured that we're raising Mike's (https://github.com/corona-warn-app/cwa-app-android/issues/5099) and your issue internally.

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode, I don't expect this issue to be addressed anymore. I'm therefore closing this issue.
