### ISSUE TITLE
GH Actions workflow "Nightly Checks and Tasks" doesn't run due to startup failure

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#4474]
See https://github.com/corona-warn-app/cwa-app-ios/actions/workflows/Nightly.yml.

@marcussc is probably the best to investigate this & already aware of the issue.

**Comment by Ein-Tim** [comment]
Seems to [run correctly](https://github.com/corona-warn-app/cwa-app-ios/actions/runs/2225996233) now, is this fixed @marcussc?

**Comment by marcussc** [comment]
Yep, its working again, closing the Issue therefore.
