### ISSUE TITLE
Where do I see my notifications from cwa?

### ISSUE THREAD

**Issue by ndegendogo** [corona-warn-app/cwa-app-ios#4512]
## Avoid duplicates
* [ ] Question is not already answered in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Question is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Question has not already been asked in another issue

## Your Question

* Source File:
* Line(s):
* Question:
Today I got a notification that cwa has news for me. But when I opened cwa, there was nothing.
Is there any place where I can see the message?

cwa 2.21.2(0) / CCL 2.1.4 / iOS 12.5.5 / iPhone 6

**Comment by ndegendogo** [comment]
Can it be a red warning that expired at the moment when I opened cwa? 
I was green before with no warnings, and am still / again green. I opened cwa shortly after midnight local time. My last successful check was before midnight.

**Comment by ndegendogo** [comment]
![IMG_0023](https://user-images.githubusercontent.com/6118267/166835555-f6868315-3564-4385-b83c-8397b1899906.PNG)

**Comment by thomasaugsten** [comment]
There is no overview of the message only in a running error report
Maybe it was a notification about a booster notification in one of your certificates

**Comment by ndegendogo** [comment]
@thomasaugsten 

> Maybe it was a notification about a booster notification in one of your certificates

Yes!! Indeed, there is a red badge on my certificates tab. And I can follow the trail of red badges and finally get a hint that I should consider a booster vaccination.

**Comment by ndegendogo** [comment]
Closing as answered.
