### ISSUE TITLE
UI glitch when turning exposure logging on/off

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#4518]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone XR
- iOS version: 15.4.1
- App version: 2.22.1

## Describe the bug

The UI glitches when exposure logging is turned off/on. See this video: 

https://user-images.githubusercontent.com/67682506/167314101-60383bc7-4523-4ac7-846e-cd16d7fcb0d4.MP4

## Steps to reproduce the issue

1. Open the CWA
2. Click on "Exposure Logging Active/Stopped"
3. Use the switch to switch exposure logging on/off
4. Notice that the UI glitches/the view scrolls when activating/deactivating exposure logging

## Expected behaviour

No UI glitch.

## Possible Fix

From what we've seen in the past I'd say this is some sort of data reload issue or similar. But could be that I'm mistaken here.

---
Internal Tracking ID: [EXPOSUREAPP-13052](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13052)

**Comment by larswmh** [comment]
Thanks for your report @Ein-Tim. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-13052](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13052)

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
PR #4647

**Comment by Ein-Tim** [comment]
- PR https://github.com/corona-warn-app/cwa-app-ios/pull/4669 reverted the fix https://github.com/corona-warn-app/cwa-app-ios/pull/4647

@dsarkar please remove the `Fix 2.25` label.

**Comment by Ein-Tim** [comment]
This issue is still reproducible under version 3.0, I'm still hoping for a fix in version 3.2 for this, as this should be an easy fix. I'll therefore leave this issue open for the time being.

**Comment by 30mar** [comment]
will set to obsolete as the effect is only until  31.4.2023, exposure logging will be switched off afterwords
