### ISSUE TITLE
Exposure detail card may be empty while risk check is running

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#4536]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone XR
- iOS version: 15.4.1
- App version: 2.22.1

## Describe the bug

The exposure detail card may be empty while a risk check is running:

| Home Screen | Exposure Detail Screen |
|--- | --- |
| ![52083E98-2349-488A-8449-1AF9D5F1EE39](https://user-images.githubusercontent.com/67682506/168446064-55e698a0-75ca-45b4-afc2-4df75cb9255e.jpeg) | ![22ACC234-7374-4E9C-AFB8-E149BD3E362A](https://user-images.githubusercontent.com/67682506/168446062-da8fe93b-b61d-4a5e-bcad-05a03fc04cc5.jpeg) |

## Steps to reproduce the issue

Not really clear as this does not happen always. 

## Expected behaviour

The screen shouldn’t be empty. 

## Additional context

I was connected to a **very** slow WLAN, so the risk check took quite some time. Maybe this is related to the bug. 

---
Internal Tracking ID: [EXPOSUREAPP-13106](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13106)

**Comment by dsarkar** [comment]
@Ein-Tim Thanks for reporting; Internal Tracking ID: [EXPOSUREAPP-13106](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13106). Best, DS

**Comment by Ein-Tim** [comment]
@dsarkar Please inform the developers that thus is reliably reproducible under circumstances where the device is connected to a network which has no internet connection.

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode, I don't expect this issue to be addressed anymore. I'm therefore closing this issue.
