### ISSUE TITLE
Text covered by button panel

### ISSUE THREAD

**Issue by dbarbos** [corona-warn-app/cwa-app-ios#457]
Rating: Low

Description:

On the main screen, after selecting the second panel, in this case, with "Risk Unknown", it opens a modal screen stating that you should activate risk identification. When scrolling down the instructions, in order to read the entire Risk of Infection text you have to hold the screen above the button panel. The text of the Risk of Infection instruction is covered by the button panel. 
This bug represents no risk to the integrity of the app.
   
Expected behaviour:

The entire Risk of Infection instruction text should appear above the button panel after scrolling hit the bottom.

1. Go to 'Main Screen'

2. Click on 'Risk Unknown' panel

![Screen Shot 2020-06-10 at 11 01 14](https://user-images.githubusercontent.com/2342417/84278251-e4827900-ab0a-11ea-8c50-44c5e94cea95.png)

3. Scroll down until hit the bottom

![Screen Shot 2020-06-10 at 11 01 34](https://user-images.githubusercontent.com/2342417/84278497-34f9d680-ab0b-11ea-9a7b-6e2dd0e9df60.png)

4. See error "Text is covered by the panel button"

![CWA-Text-Covered](https://user-images.githubusercontent.com/2342417/84278994-d2550a80-ab0b-11ea-848d-6a53b97ab0fb.gif)

**Comment by EisvogelSAP** [comment]
Fixed in #540
