### ISSUE TITLE
Bye Bye 👋

### ISSUE THREAD

**Issue by marcussc** [corona-warn-app/cwa-app-ios#4602]
Dear Community,

after nearly two years my time has come to move on to an other project. 

Believe me when I say CWA was the most fun and stress I have ever had in a project. I am very glad that I was giving this opportunity where I could do something meaningful in the fight against Corona. 

It was also nice to have such an amazing community to support us. Thank you for bearing with us through the hard and feature driven times. 

Words can not express the gratitude I fell, so you will have to live with a simple "Thank you" 😉

So long,
Marcus

**Comment by Ein-Tim** [comment]
Dear Marcus, thanks for the great cooperation between you and the community, thank you for always being open for feedback from us, thanks for answering questions in PRs, working on Sundays when Apple wants something changed, making sure that the `main` branch is always up to date (-;, etc. etc..

It's sad to see you leaving, but I know that the rest of the great team will keep up to the standards you established!

Thank you, all the best for your future projects! ❤️

Tim

**Comment by ndegendogo** [comment]
Dear Marcus, thank you for your time and effort you spent in this amazing project! 🎉
I have done my very first steps in Swift here with the cwa code, and I remember well the feedback and discussions with you when you reviewed my PRs. 😅

So I can only repeat what @Ein-Tim  already said: Thank you, stay healthy, and all the best wishes for your future projects! 🍀🍀🍀

**Comment by Ein-Tim** [comment]
@nickguendling 

Hey Nick, hope you're doing well! Did you also leave the project? I didn't see any PRs from you in the last months. 😅

**Comment by nickguendling** [comment]
@Ein-Tim 

Hey Tim! I started a new project in June, working on CWA is not my main focus anymore. That's why you haven't seen new PRs from me. But I'm still available for the remaining team to help out, so I haven't fully left the project.

**Comment by Ein-Tim** [comment]
@nickguendling 

Okay, nice to hear! All the best for your new project! Thanks for the great work you've done here!

**Comment by nickguendling** [comment]
@Ein-Tim

Thank you! I enjoyed it a lot to put everything I had into this project for almost two years. And I appreciate your continuing support, as well as the support we got and still get from all members of this community!

**Comment by dsarkar** [comment]
Dear @Ein-Tim, @MikeMcC399 and community! FYI, in August we, @larswmh, @svengabr, and @dsarkar from the Corona-Warn-App Open Source Team, will have only very sporadically a look here at the GitHub repositories of the CWA project. Thanks for all your input, contributions, constructive criticism .... Wish you all a pleasant August! Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
Hey @dsarkar, thanks for the information!

I have some questions:

- What is the plan reg. mirroring issues to JIRA? Will this be done by the developers themselves?
- What about the CWA website? CMs always were responsible for updating its content, merging & reviewing PRs, etc.?
- Is this _break_ only planned for August or for an undefined period of time?

**Comment by GisoSchroederSAP** [comment]
All, 
as we all waiting for further decission about the way forward, the current situation unfortunately, is quite strange: Capacity is limited in all areas of the app and infrastructure teams. Therefore, a significant number of tasks will definitely slow down for the next couple of weeks, until new decisions are made. Sorry for the inconveniences this might cause.

**Comment by Ein-Tim** [comment]
Hi @GisoSchroederSAP,
thanks for the information and for the insight! Is it possible for you to answer the questions I asked above or is this in the current situation not possible

**Comment by Ein-Tim** [comment]
I'll use this issue, as it doesn't seem necessary to open a new issue just for this. I also have some news reg. my participation in this project, you can find them in the CWA-Community slack: https://covidapps.slack.com/archives/C0194ML0MLN/p1675094514976179
