### ISSUE TITLE
Exposure logging doesn’t work

### ISSUE THREAD

**Issue by tiny-slayer** [corona-warn-app/cwa-app-ios#4612]
My exposure logging doesn‘t work anymore.
![D83D539D-46A3-4613-B820-CA19B424531B](https://user-images.githubusercontent.com/81304114/173046087-577e5fa7-e066-4102-b8f7-a8404e885a5c.png)

**Comment by Ein-Tim** [comment]
Hey @tiny-slayer 

Thanks for the report!

How long are you seeing this issue already?

**Comment by Ein-Tim** [comment]
For your information: There is also a FAQ entry on this error:  https://www.coronawarn.app/en/faq/results/#ENError13

**Comment by tiny-slayer** [comment]
Hi Tim, it’s been a week. I get the error when I click on “restart”. The last update was on 4th of June, I guess since then I get that error.
![C1C48A7F-4528-4073-A7B7-CD8166942DD4](https://user-images.githubusercontent.com/81304114/173089595-58690d4e-0684-4a2e-ab1e-4680ae0b8d31.png)

**Comment by Ein-Tim** [comment]
Hey @tiny-slayer, thanks for the feedback! Could you try turning exposure logging off completely for 24 hours, and then reactivating it again? This might help. Please note, that the app does not collect any random IDs if you turn exposure logging off.

Could you please also let us know:
- iOS version
- App version
- iPhone model

Thanks!

**Comment by tiny-slayer** [comment]
Hi again, 
IOS version is iOS 15.3.1
App version is 2.23.2 (0)
Phone model is iPhone 11

**Comment by tiny-slayer** [comment]
Yes, I did already. I’m going to turn it on again tomorrow.

**Comment by tiny-slayer** [comment]
It still doesn’t work:(
Now there is another error.
![ED03AC13-2AE4-4C7F-8655-8DA8C7CA69B8](https://user-images.githubusercontent.com/81304114/173206809-aa939184-4021-4eb2-b814-5a438bd3ebd3.png)

**Comment by Ein-Tim** [comment]
@thomasaugsten Please, could you have a look at this?

**Comment by thomasaugsten** [comment]
Please deactivate the ENF for 24 and activate the error report/ Fehlerbericht an activate the ENF after 24 error. We need an error report of the no exposure window error

**Comment by Lulara14** [comment]
Hi, i have the same issue. Can you support in fixing it?

**Comment by Ein-Tim** [comment]
@Lulara14

Please, could you enable error logging like this:

<details>
<summary>German steps</summary>

1. In der CWA auf dem Reiter "Status" ganz nach unten scrollen
2. Auf "App-Informationen" scrollen
3. Auf "Fehlerberichte"
4. Auf "Starten" tippen
5. Einmal _machen_, dass der Fehler auftaucht
6. Schritte 1-3 wiederholen
7. Auf "Fehlerbericht senden" tippen
8. Auf "Einverstanden und senden" tippen
9. Nach unten scrollen
10. Auf "ID-Historie" tippen
11. Die jeweilige ID hier in den GitHub Issue stellen

</details>

<details>
<summary>English steps</summary>
1. In CWA, scroll down to the very bottom of the "Status" tab
2. Tap on "App Information"
3. Tap on "Error Reports"
4. Tap "Start"
5. Do the steps that cause the error
6. Rebelst steps 1-3
7. Tap on "Send Error Report"
8. Tap on "Agree and Send"
9. Scroll down
10. Tap on "ID History"
11. Let us know the corresponding ID in this GitHub issue

</details>

After you did this, please perform the following steps to fix the problem:

<details>
<summary>German steps</summary>

1. iOS-Einstellungen öffnen
2. Bis zu "Begegnungsmitteilungen" scrollen & "Begegnungsmitteilungen" antippen
3. Auf "Corona-Warn-App" ("Aktive Region") tippen
4. Auf "Corona-Warn-App" tippen
5. Runterscrollen
6. "Begegnungsinformationen teilen" deaktivieren
7. Etwas mehr als 24 Stunden warten
8. Schritte 1-5 wiederholen
9. "Begegnungsinformationen teilen" aktivieren
10. Oben auf den blauen Text "Als aktive Region festlegen" tippen
11. CWA öffnen und prüfen ob alles wieder funktioniert


</details>

<details>
<summary>English steps</summary>

1. Open the iOS Settings
2. Scroll down to "Exposure Notifications" 
3. Tap on "Corona-Warn-App" ("Active Region")
4. Tap on "Corona-Warn-App"
5. Scroll down
6. Deactivate "Share Exposure Information"
7. Wait for a bit more than 24 hours
8. Perform steps 1-5
9. Activate "Share Exposure Information"
10. Tap on the blue text above "Set As Active Region"
11. Open up CWA and check if everything works again

</details>

**Comment by Ein-Tim** [comment]
Hey @Lulara14 & @tiny-slayer, does the error still occur for you? Or can we close this issue?

**Comment by Lulara14** [comment]
It is solved now! Tks

**Comment by tiny-slayer** [comment]
The error is not happening anymore, thank you!

Kindest regards,
Aizhan

**Comment by Ein-Tim** [comment]
@thomasaugsten Please, could you close this issue?
