### ISSUE TITLE
CWA requires granting Photos Library access before presenting photo picker

### ISSUE THREAD

**Issue by toco** [corona-warn-app/cwa-app-ios#4617]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: Any iOS Device
- iOS version: Any iOS
- App version: 2.24.x and later

## Describe the bug

CWA requests Photo Library access before presenting the photo picker, this is not necessary and explicitly against Apple guidance.

https://github.com/corona-warn-app/cwa-app-ios/blob/39e858a9e3e1500317889c84bdbd25b297a76218/src/xcode/ENA/ENA/Source/Scenes/FileScanner/FileScannerCoordinator.swift#L185-L222

## Steps to reproduce the issue

1. Go to "Scanner Tab"
2. Tap on bottom left button "Open document"
3. Tap on Photo Library 

CWA prompts for Photo Library access and doesn't present the picker if no access is granted.

## Expected behaviour

The System Photo Picker opens without any prompting for Photos Library access.
Apple explicitly recommends not to prompt for access before presenting the picker:

https://developer.apple.com/videos/play/wwdc2020/10652/?time=832
> […] please don't prompt for photo library access before showing the picker and don't require the user to grant you access before showing the picker. There's no need to do any of this. And it doesn't help with the users trust into your app.

`PHPickerViewController` is running out of process and doesn't require your app to access the library directly, the same has been the case for `UIImagePickerViewController` since iOS 11.

## Possible Fix

Remove all `PHPhotoLibrary` authorization calls and all `NSPhotoLibrary(Add)UsageDescription` entries from all Info.plist files.
https://github.com/corona-warn-app/cwa-app-ios/blob/39e858a9e3e1500317889c84bdbd25b297a76218/src/xcode/ENA/ENA/Source/Scenes/FileScanner/FileScannerCoordinatorViewModel.swift#L100-L120
https://github.com/corona-warn-app/cwa-app-ios/blob/39e858a9e3e1500317889c84bdbd25b297a76218/src/xcode/ENA/ENA/Source/Scenes/FileScanner/FileScannerCoordinator.swift#L185-L222
https://github.com/corona-warn-app/cwa-app-ios/blob/release/2.24.x/src/xcode/ENA/ENA/Resources/Info_Debug.plist#L50-L53

## Additional context

---
Internal Tracking ID: [EXPOSUREAPP-13375](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13375)

**Comment by larswmh** [comment]
Thanks for your report @toco. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-13375](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13375)

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
Hey @toco,

I can confirm that this was implemented/fixed with version 2.25. Could you please cross check?

**Comment by toco** [comment]
Verified as fixed in 2.25.0 (5).
Tested with all camera/image picking flows I found in the app.
Thanks!

**Comment by toco** [comment]
Sorry @Ein-Tim, I though I used the Close with comment button, but apparently not. Closing now.
