### ISSUE TITLE
Red badge reappears permanently on status tab

### ISSUE THREAD

**Issue by ndegendogo** [corona-warn-app/cwa-app-ios#4621]
## Avoid duplicates
* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 13 Pro
- iOS version: 15.4.1
- App version: 2.23.2 (0) / CCL 3.0.1

## Steps to reproduce the issue

- have a red warning
- see the red badge (news indicator) on Status tab as expected
- switch to the Status tab. cwa assumes that you have now noticed the red warning. The red badge disappears.
- switch to a different tab
- close cwa
- open cwa again. It shows the last tab as expected.
- but the Status tab has again the red badge

## Expected behaviour
The red badge should remember that you have seen the warning, and appear only if there are true news (e.g. a more recent day with red exposures).

## Additional context

Note: actually, the badge diappears already as soon as you return to the Home screen (top level of the status tab), even if you didn't scroll up to see the risk card. So although the current behaviour is a bit confusing (I was worried and tried to find the additional news); but maybe it is intended and good, because it is harder now to miss a notification.

---
Internal Tracking ID: [EXPOSUREAPP-13184](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13184)

**Comment by ndegendogo** [comment]
![4DA2AB8F-1128-430E-96CC-E64C8AE4C8C2](https://user-images.githubusercontent.com/6118267/173694472-285d96ee-5f62-46e9-a4ac-0d6c70098319.png)

**Comment by ndegendogo** [comment]
![9B893B43-4D96-4664-B6AE-917194772FB6](https://user-images.githubusercontent.com/6118267/173694688-1547e2a8-b03d-4f90-be96-3ad60fa2b7c3.png)

**Comment by Ein-Tim** [comment]
- PR: https://github.com/corona-warn-app/cwa-app-ios/pull/4608

**Comment by ndegendogo** [comment]
@Ein-Tim wow - this is a fast fix! 🎉🎉🎉

**Comment by larswmh** [comment]
Thanks for your report @ndegendogo. As mentioned by @Ein-Tim, there's already a PR fixing this. Your issue will be attached to the related internal ticket. 
Internal Tracking ID: [EXPOSUREAPP-13184](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13184)

---
Corona-Warn-App Open Source Team

**Comment by ndegendogo** [comment]
@larswmh thank you for the fast response!
And please tell also the developer team how much I appreciate their fast acting on bugs!
🎉🎉🎉

**Comment by dsarkar** [comment]
Hi @ndegendogo, Thanks for reporting, @Ein-Tim Thanks for linking the PR. Just FYI, in this case the testing team had already discover the bug before your report. Anyway, @ndegendogo I will forward your compliments. Thanks!

**Comment by ndegendogo** [comment]
Sorry, but this is not fixed in cwa 2.24(0)

**Comment by Ein-Tim** [comment]
@ndegendogo The PR was merged into the `release/2.25.x` branch.

**Comment by Ein-Tim** [comment]
@dsarkar / @larswmh Please fix the label on this issue. It should be https://github.com/corona-warn-app/cwa-app-ios/labels/Fix%202.25 but is https://github.com/corona-warn-app/cwa-app-ios/labels/Fix%202.24.

**Comment by Ein-Tim** [comment]
So I'm red again and can confirm that this issue is fixed in version 2.25.

**Comment by ndegendogo** [comment]
> So I'm red again

@Ein-Tim I wish you all the best - stay healthy!

**Comment by ndegendogo** [comment]
> with the fix in place in 2.25, are you ok with closing this issue

@mlenkeit sure - sorry, I forgot to mention this 

And, by the way, meanwhile I am red again 👹👹 so I am even able to verify it myself.

Closing as resolved 🎉🎉
