### ISSUE TITLE
UI Glitch on soon expiring or already expired certificate screen (Symbol is squeezed together)

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#4677]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 6s
- iOS version: 15.5
- App version: 2.24.1

## Describe the bug

There is an UI Glitch / issue on the soon expiring / already expired EU DCC screen. The symbol is squeezed together. Here is a screenshot of the bug under iOS & for comparison one from Android where the symbol is displayed correctly:

| iOS (wrong) | Android (right)
|---|---|
| <img src="https://user-images.githubusercontent.com/67682506/179395041-0f750838-5e76-4c47-a276-6e6976dba910.jpeg" width="300"> | <img src="https://user-images.githubusercontent.com/67682506/179395046-2373010d-be31-457a-aa8d-2c060779db11.jpg" width="300"> |

## Steps to reproduce the issue

1. Open the CWA
2. Click on "Certificates"
3. Click on the person from whom you have a soon expiring or an already expired certificate in the app
4. Scroll to the very bottom
5. Click on the certificate that is soon expiring or is already expired
6. See the symbol which is squeezed together

## Expected behaviour

The symbol should not be squeezed together.

---
Internal Tracking ID: [EXPOSUREAPP-13640](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13640)

**Comment by larswmh** [comment]
Thanks for your report @Ein-Tim. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-13640](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13640)

Unfortunately, I was personally not able to reproduce this on both an iPhone 11 Pro Max (iOS 16 Beta) and an iPhone 8 (iOS 15.5) using the latest Corona-Warn-App versions. Is there any other step that is essential to reproduce this issue?
---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@larswmh Maybe this bug is specific to the iPhone 6(s) display aspect ration. I can reliably reproduce this bug as well as on my real iPhone 6s & on an emulator iPhone 6s. 

I will see if I can reproduce this on other iPhones using the emulator.

**Comment by Ein-Tim** [comment]
- PR https://github.com/corona-warn-app/cwa-app-ios/pull/4690

**Comment by puneetmahali1** [comment]
@Ein-Tim Thanks for mentioning the PR link. The bug has fixed now.

**Comment by Ein-Tim** [comment]
Fixed.
