### ISSUE TITLE
2.25.0-RC5 released as latest version

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#4689]
https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v2.25.0-rc.5 was released
a) as latest version, although it should be a Pre-Release
~b) there are no release notes in the release.~

Please address these two points.

cc @30mar

**Comment by Ein-Tim** [comment]
Will this issue be fixed soon? @naveeddotio

**Comment by Ein-Tim** [comment]
@naveeddotio

Hey Naveed, I hope you had a relaxing weekend! By any chance, could you fix this issue soon?

Stay safe & cool!
Tim

**Comment by naveeddotio** [comment]
@Ein-Tim @dsarkar Fixed.
