### ISSUE TITLE
Infinite zoom out when previewing certificates using "Export all certificates"

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#4703]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone XR
- iOS version: 16.0 Public Beta 2
- App version: 2.25.0

## Describe the bug

When previewing the PDFs which were created using the "Export all certificates" feature of CWA, there is no (senseful) limitation how far the user can zoom out.
Here's a a picture:

<img src="https://user-images.githubusercontent.com/67682506/182237014-9fccf5cb-b55c-42b0-907d-c1140f3c1eb7.png" width="300">

## Steps to reproduce the issue

1. Open the app
2. Tap on "Certificates"
3. Click on the export icon in the top right corner
4. Click on "Continue"
5. Wait until the PDF is created & the preview opens
6. Zoom out & notice that there is no senseful limit implemented.

## Expected behaviour

It shouldn't be possible to zoom out more than the size of a DINA4 page.

---
Internal Tracking ID: EXPOSUREAPP-13781

**Comment by sapcoder123** [comment]
@Ein-Tim Thank you for reporting the issue!

**Comment by Ein-Tim** [comment]
- PR https://github.com/corona-warn-app/cwa-app-ios/pull/4802 fixes this issue. 

The label `Fix 2.28` can be added to this issue.

**Comment by Ein-Tim** [comment]
Confrim fixed.

**Comment by dsarkar** [comment]
@Ein-Tim Thanks for the feedback.
