### ISSUE TITLE
Fehler 13 persists After several weeks

### ISSUE THREAD

**Issue by Johnnydriver38** [corona-warn-app/cwa-app-ios#4711]
Hi everyone,
After I‘m receiving the Fehler 13 Since several Weeks I‘m reporting this Now as documented in your FAQs.

![DF479C66-C29C-4A2C-AB3A-6CE2DA2D60BC](https://user-images.githubusercontent.com/110676188/183085121-8e2e801d-869a-4586-9e05-bd8479a864e7.png)

## Technical details

- Device name: iPhone 6s
- iOS version: 15.6
- App version: 2.25.0

## Describe the bug
Mentioned error Comes up all the Time when Risk Shall be calculated

## Steps to reproduce the issue
Open the App. After Several Minuten of Processing the error Fehler 13 appears

## Expected behaviour
Well, Risk calculation Should Happen without errors

---
Internal Tracking ID: EXPOSUREAPP-13731

**Comment by Ein-Tim** [comment]
Hi @Johnnydriver38, thanks for reporting this issue!

Could you please activate error logging in the app for the next 24h and send us the ID tomorrow? 

<details>
<summary>German steps</summary>

1. In der CWA auf dem Reiter "Status" ganz nach unten scrollen
2. Auf "App-Informationen" scrollen
3. Auf "Fehlerberichte"
4. Auf "Starten" tippen
5. Einmal _machen_, dass der Fehler auftaucht & den Fehlerbericht für 24 Std. laufen lassen
6. Schritte 1-3 wiederholen
7. Auf "Fehlerbericht senden" tippen
8. Auf "Einverstanden und senden" tippen
9. Nach unten scrollen
10. Auf "ID-Historie" tippen
11. Die jeweilige ID hier in den GitHub Issue stellen

</details>

<details>
<summary>English steps</summary>
1. In CWA, scroll down to the very bottom of the "Status" tab
2. Tap on "App Information"
3. Tap on "Error Reports"
4. Tap "Start"
5. Do the steps that cause the error & let the report run for at least 24h
6. Rebelst steps 1-3
7. Tap on "Send Error Report"
8. Tap on "Agree and Send"
9. Scroll down
10. Tap on "ID History"
11. Let us know the corresponding ID in this GitHub issue

</details>

**Comment by Johnnydriver38** [comment]
Hi @Ein-Tim,

sure, already done.
I‘ll come back to you tomorrow.

Best regards 
Johnnydriver38

**Comment by Ein-Tim** [comment]
@thomasaugsten FYI

**Comment by Johnnydriver38** [comment]
Hi @Ein-Tim,

here is the ID of the requested log
![94F15C29-CE80-4CF4-8CE9-34D863B29444](https://user-images.githubusercontent.com/110676188/183252017-47abbec1-3afa-47d3-9bcb-5a05d31014a9.png)

Hopefully this helps to Identity the Root cause.
If you require anything else just let me know.

best regards 
Johnnydriver38

**Comment by thomasaugsten** [comment]
The error log is very exact 24h but we need a little bit more minutes then 24h.
I would assume you should also see a different error then error 13.

**Comment by Johnnydriver38** [comment]
Hi @thomasaugsten,

I‘ve just checked the App again: I Received the Same error again, just as it is for weeks:

please Find the error and the log ID
below:
![A1EEEA75-7A5A-4980-95E3-0248BE3CC093](https://user-images.githubusercontent.com/110676188/183252864-af5ef0bb-2981-4aa5-944b-1dfccba388b2.png)
![BAFC95D6-2F3B-4BEB-9F68-984216FDA4BB](https://user-images.githubusercontent.com/110676188/183252867-529b71f8-4bcf-42c7-88fd-440a2351cb5a.png)

**Comment by thomasaugsten** [comment]
@Johnnydriver38 Can you please provide again a error report which runs over the last days?

**Comment by Johnnydriver38** [comment]
Hi @thomasaugsten,

sure, I‘ve run the log the Last days and the error persisted. 

Here‘s the latest Log ID
![037A6FC4-71F0-42D6-A82D-15655E8DFB60](https://user-images.githubusercontent.com/110676188/183387648-99e61017-d68f-45c6-bdfc-3b3ea97ecc5a.png)

Best regards 
Johnnydriver38

**Comment by thomasaugsten** [comment]
@Johnnydriver38 
How much space is left on the device?
Please deactivate the "Hintergrundaktualisierung" in Corona-Warn settings of the iOS Settings.
And try to do a exposure check manually in the app if you see the error 13 please wait 24h to check manually  for exposures

**Comment by Johnnydriver38** [comment]
Hi @thomasaugsten,

there are around 8 GB Space available on my  device (which should be pretty sufficient).
I‘ve deactivated background updates as recommented and Check if manual exposure Work tomorrow.

**Comment by Johnnydriver38** [comment]
Hi @thomasaugsten,

I‘ve tried your proposed steps. They led however to the Same result, meaning getting Fehler 13 again

**Comment by thomasaugsten** [comment]
Ok can you provide a new error report id

**Comment by Johnnydriver38** [comment]
Hi @thomasaugsten,

sure, here is the latest Log & its ID.
![41881FB1-5643-49EB-885A-19B79B1444AC](https://user-images.githubusercontent.com/110676188/183928148-95e01ae4-00a3-4f31-a73a-6bb5ac287d64.png)

**Comment by thomasaugsten** [comment]
It looks like it is not issue on App side we need a log on operation system level.
Please contact me directly for a detailed instruction.
thomas.augsten@sap.com

**Comment by Johnnydriver38** [comment]
@thomasaugsten: Done :)

**Comment by Johnnydriver38** [comment]
@thomasaugsten I‘ve Provided you the requested data

**Comment by Johnnydriver38** [comment]
Hi @thomasaugsten,

any news/ Updates about this issue?

best regards 
Johnnydriver38

**Comment by thomasaugsten** [comment]
We are still try to understand the issue. On the sysdiagnose it runs good no exception visible but from app side the exposure checks are not returning any results. I thinks it is device related the next step would be disabling and enabling the ENF in the OS settings.

**Comment by Johnnydriver38** [comment]
Hi @thomasaugsten,
well it seems your last suggestion did it 👍🏼
Now the App is working as expected again!
Thanks for your time, Patience & guidance!
Cheesrs 
Johnnydriver38
