### ISSUE TITLE
Rename v2.26.0 release to v2.26.0-rc5?

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#4749]
Should the https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v2.26.0-rc.5 release be renamed from `v2.26.0` to `v2.26.0-RC4`? Or is this the final version which has been released before the public release in the App Store?

cc @naveeddotio

**Comment by Ein-Tim** [comment]
@naveeddotio Could you please have a look & release version 2.26 as latest and fix this issue as well as #4751? That would be great!

**Comment by naveeddotio** [comment]
@Ein-Tim It is correctly named as v2.26.0 as it was the final version release to the public.
