### ISSUE TITLE
2.26.1-RC0 is marked as latest release

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#4751]
https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v2.26.0-rc.6 is a RC but has the tag "Latest Release" to it. Please change it to "Pre Release" @30mar. 

Thanks!

**Comment by naveeddotio** [comment]
@Ein-Tim It is the latest release as it is the hot fix. The name contained RC which I have removed now.

**Comment by Ein-Tim** [comment]
@naveeddotio 

Thanks, I'm fine with the releases now!
