### ISSUE TITLE
Don't show UQS pop up for new installations (Align iOS to Android)

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#4752]
## Avoid duplicates
* [X] This enhancement request has not already been raised before
* [X] Enhancement request is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)
* [X] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation
Under iOS, the UQS pop up is shown on a fresh install to inform the user of the UQS. Under Android the UQS pop up was removed for all fresh installations, as the feature is not new anymore and thus does not need extra introduction (see https://github.com/corona-warn-app/cwa-app-android/pull/5366#issuecomment-1191171812).

## Suggested Enhancement
Align iOS to Android and don't show the UQS pop up for new installations.

## Expected Benefits
Feature parity between iOS & Android & cleaner UX.

---
Internal Tracking ID: EXPOSUREAPP-13927

**Comment by sapcoder123** [comment]
@Ein-Tim Thank you for reporting the issue!

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode, I don't expect this issue to be addressed anymore. I'm therefore closing this issue.
