### ISSUE TITLE
Wrong Button text if Background App Refresh is off & the device is connected via a cellular connection ("Aktualisierung nur alle 4 Stunden" instead of "Aktualisierung nur alle 24 Stunden")

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#4754]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 12 Pro Max
- iOS version: 15.6.1
- App version: 2.25.0

## Describe the bug

CWA shows the text "Aktualisierung aller 4 Stunden" even if a device is connected to the internet via a cellular connection. The text is wrong and this can lead to confusing situations like this:

<img src="https://user-images.githubusercontent.com/67682506/187493410-db924db8-8494-4854-bff1-d1ac693106fc.jpeg" width="300">

The app shows that a risk check can only be carried out all 4h, even though the last check was more than 4 hours ago.

## Steps to reproduce the issue

1. Turn off "Background App Refresh" in the iOS settings for CWA
2. Connect to the internet via a cellular connection and perform a risk check in the app
3. Notice that the button still says "Aktualisierung nur alle 4 Stunden" although the app will only offer to perform a new check in 24h

## Expected behaviour

The text should say "Aktualisierung nur alle 24 Stunden" if the device is connected to the internet via a cellular connection. 

---
Internal Tracking ID: EXPOSUREAPP-13928

**Comment by sapcoder123** [comment]
@Ein-Tim Thank you for reporting the issue!

**Comment by Ein-Tim** [comment]
- PR fixing this: https://github.com/corona-warn-app/cwa-app-ios/pull/4980

Label `Fix 3.1` can be added to this issue.

**Comment by Ein-Tim** [comment]
I can confirm that this has been **fixed** with version 3.1, and I'm therefore closing this issue as completed.
