### ISSUE TITLE
Missing GitHub release for version 2.27

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#4806]
There is no GitHub release for version 2.27 which is available in the App Store. Please create the corresponding GitHub release.

**Comment by Ein-Tim** [comment]
@naveeddotio / @30mar 

I'd be happy if you could
a) either change https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v2.27.0-rc.5 from a pre release to the latests version
b) or release a version 2.27.0 with the same text as https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v2.27.0-rc.5

**Comment by sapcoder123** [comment]
In the meantime the release is labeled with “Latest” in the sense of your described option a), right? The visible date is not the exact release date but this is also not the case in the past.

@Ein-Tim Would you like to close this issue now?

**Comment by Ein-Tim** [comment]
> The visible date is not the exact release date but this is also not the case in the past.

It was quite often the exact release date to the public in the past, but I'm satisfied with how it is now.
