### ISSUE TITLE
Falscher Impfstatus

### ISSUE THREAD

**Issue by Neuwessi11** [corona-warn-app/cwa-app-ios#4813]
Ich habe in der App nur meine letzten zwei von drei Impfungen gespeichert. Auch wenn die dritte Impfung als Auffrischimpfung gegeben und (meines Wissens) zertifiziert wurde, zeigt mir die CWA deshalb seit einem der letzten Updates einen unvollständigen Impfstatus an. Mein Impfstatus ist aber, wie gesagt, vollständig (Alter: 47).

Ein Versuch, den QR-Code der ersten Impfung zu scannen, misslang, weil die Impfung zu lange her und daher das "technische Ablaufdatum" überschritten sei.

Erwartetes Verhalten: Falls in dem QR-Code hinterlegt ist, ob es sich um eine Auffrischimpfung handelt oder nicht, sollte die CWA das auslesen und verarbeiten, unabhängig davon, wie viele Impfungen in der App gespeichert sind.
Falls das in dem QR-Code nicht hinterlegt ist, sollte die App das nachträgliche Scannen auch abgelaufener Impfzertifikate erlauben, da die CWA anscheinend nur prüft, ob drei Impfungen erfolgt sind oder nicht. Wenn ich aber meine erste Impfung nicht nachträglich scannen kann, werde ich niemals einen vollständigen Impfstatus angezeigt bekommen.

---
Internal Tracking ID: [EXPOSUREAPP-14023](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14023)

**Comment by Neuwessi11** [comment]
Hallo Ein-Tim,
danke für die schnelle Nachfrage.

Aus dieser Nachfrage würde ich schließen, dass es sich um ein neues Janssen-Problem handeln könnte.

Auf meinem ersten (Papier-)Zertifikat steht: Janssen 1/1
Auf meinem zweiten Zertifikat steht Comirnaty 2/2
Auf meinem dritten Zertifikat steht Comirnaty 2/1

In der App wurde das auch so übernommen.
Für die dritte Impfung steht "2 of 1"
Für die zweite Impfung steht "2 of 2"
Die erste Impfung ließ sich ja nicht scannen.

**Comment by Neuwessi11** [comment]
Und nein, das sind keine Tippfehler meinerseits, sondern die von mir korrekt wiedergegebenen Angaben aus den Zertifikaten.

**Comment by thomasaugsten** [comment]
Das dritte Zertifikat wurde nach einem falschen Schema ausgestellt. Korrekt wäre ein 3/3 gewesen. Deswegen solltest du auf die ausstellende Stelle zugehen und eine Korrektur beantragen.

**Comment by Neuwessi11** [comment]
Vielen Dank für die schnelle Antwort1

Werde ich ausprobieren. Mal sehen, was sie sagen ...

**Comment by dsarkar** [comment]
@Neuwessi11 

> Ein Versuch, den QR-Code der ersten Impfung zu scannen, misslang, weil die Impfung zu lange her und daher das "technische Ablaufdatum" überschritten sei.

Das sollte eigentlich funktionieren. Wie lautet die genaue Fehlermeldung? Evtl Screenshot?

Best wishes, DS
---
Corona-Warn-App Open Source Team

**Comment by Neuwessi11** [comment]
Hm, anscheinend muss ich da auch zurückrudern. Gerade eben kam nur die Fehlermeldung, dass das Zertifikat bereits in der App registriert sei, was soweit auch stimmt. Zwar mit "Zertifikat abgelaufen", was ja auch richtig ist, allerdings kann man auch keinen QR-Code des Zertifikats sehen, was mich ein bisschen wundert, aber u.U. auch erwünschtes Verhalten sein könnte.

Da ich jetzt selber wissen wollte, was mich da vor drei Tagen so irritiert hatte, habe ich das Zertifikat endgültig (auch aus dem Papierkorb) gelöscht und erneut gescannt. Danach erscheint "Zertifikat abgelaufen" und ein Erklärtext. Dort, wo der QR-Code sein sollte, ist aber nichts, sondern nur ein graues Dreieck mit Ausrufezeichen.
Wahrscheinlich hat dieser nicht angezeigte QR-Code in Verbindung mit der Meldung, dass ich nicht alle erforderlichen Impfungen hätte, bei mir zu dem falschen Schluss geführt, dass die App das Zertifikat nicht erkennen würde. Womit ich aber falsch lag.
Tut mir leid!

**Comment by dsarkar** [comment]
@Neuwessi11 Kann dieses Issue geschlossen werden? Gibt es Neuigkeiten dazu?

**Comment by Neuwessi11** [comment]
Ich bin noch nicht dazu gekommen, beim Arzt vorbeizuschauen.
Wenn ich aber mal davon ausgehe, dass Ihr wisst, was Ihr sagt, würde ich sagen, dass es geschlossen werden kann. Und wenn sich später wider Erwarten herausstellen sollte, dass das Problem doch eine andere Ursache hat, kann ich mich ja in diesem Thread erneut melden, um ihn ggf. wieder öffnen zu lassen, oder?
Vielen Dank nochmal!

**Comment by dsarkar** [comment]
@Neuwessi11 Ok, danke, wir warten auf's Feedback!

**Comment by Neuwessi11** [comment]
So, jetzt war ich endlich wieder bei meinem Hausarzt, habe neue Impfzertifikate bekommen und sie gleich eingescannt. Ergebnis: Ich bin jetzt offiziell CWA-bestätigt vollständig geimpft. Es lag also wirklich an falsch ausgestellten Zertifikaten.

Es hing wohl tatsächlich damit zusammen, dass meine erste Impfung eine Janssen-Impfung war.
Wie auch immer - auf den Zertifikaten, mit denen es jetzt funktioniert, steht: Für die zweite Impfung unter "Erstimpfung/Wiederimpfung" 2/1
und für die dritte Impfung unter "Erstimpfung"Wiederimpfung" 3/1.

Vielen Dank für die Hilfe!
