### ISSUE TITLE
Please merge the 2.29.0 & 3.0.0 milestone

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#4893]
* [X] None of the other issue templates apply to this issue.

Could you please merge the 2.29.0 & 3.0.0 milestone? This would be easiest by just renaming the 2.29.0 one and deleting the 3.0.0. All PRs earlier assigned to the 3.0.0 milestone, which you delete, should then be assigned to the renamed 2.29.0 one.

**Comment by Ein-Tim** [comment]
@naveeddotio Would you do that, please?

**Comment by Ein-Tim** [comment]
Reminder that this is still a problem. @brianebeling maybe it makes sense to create a JIRA ticket for this?

**Comment by larswmh** [comment]
@Ein-Tim 
Thanks for opening this issue. I have merged all issues from the 2.29.0 milestone into the 3.0.0 milestone. In addition to that, I deleted the 2.29.0 as it is not needed anymore.
