### ISSUE TITLE
Bad behavior of CWA when connected to WLAN without connection to the internet

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#4931]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone XR
- iOS version: 16.1.2
- App version: 2.28.0

### Precondition
Be connected to WLAN, which however, has currently no access to the internet.

### Bug
If the above-mentioned pre-condition is made, opening the app leads to a loading screen, which loads for up to 60 seconds(!!!) before timing out. 

Here's a video:

https://user-images.githubusercontent.com/67682506/206857485-eefca106-1a31-45bf-b4f9-7c44a6a860eb.mov

## Steps to reproduce the issue

1. Connect your device to WLAN
2. Make sure the WLAN has no connection to the internet
3. Open the Corona-Warn-App
4. Just wait...

## Expected behavior

The Corona-Warn-App should never let the user wait for more than ca. 10 sec. during the app starting process.

## Possible Fix

Probably the time-out for some actions which are performed during app startup are too long. 

---
Internal Tracking ID: [EXPOSUREAPP-14416](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14416)

**Comment by larswmh** [comment]
Thanks for your report @Ein-Tim. I have created an internal ticket for it. Unfortunately, I was not able to reproduce this myself (iPhone 11 Pro Max, iOS 16.1.1 (20B101) and iOS 16.1.2 (20B110), CWA 2.28.0). There was no loading screen at all and I immediately got into the app.
Internal Tracking ID: [EXPOSUREAPP-14416](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14416)

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@larswmh 

Thank you! Would you let me know how you tested it?

**Comment by larswmh** [comment]
@Ein-Tim 

> Thank you! Would you let me know how you tested it?

Sure, I have attached a video of it. I had to cut out the first part where I "turned off" the internet because the screen contained too much confidential information. In short, I have a satellite connection and it lets me disable the satellite dish while keeping the router running. This way, the WLAN connection to the phone remains. I then check if the connection is really gone by accessing one of the headlines that you'll be presented with by swiping to the right on your home screen. After that, I open the Corona-Warn-App and notice there was just a very short loading screen, but it pretty much let me into the app instantly. To confirm that the connection hasn't been reestablished in the meantime, I'll check with a headline again.

https://user-images.githubusercontent.com/88365935/207254043-9892457a-fa79-43cd-8b3b-6206d973b53e.mov

**Comment by Ein-Tim** [comment]
@larswmh Thanks for sharing! That's quite strange. The app was completely closed before you opened it?

**Comment by larswmh** [comment]
@Ein-Tim 

> The app was completely closed before you opened it?

Yes, I double-checked yesterday evening to confirm.

**Comment by Ein-Tim** [comment]
Strange. I'll try to reproduce this with an error log running.

**Comment by Ein-Tim** [comment]
@larswmh 
Indeed, I also can't reproduce the issue currently. I will try other it in another way. OP updated.

**Comment by Ein-Tim** [comment]
This seems to be a weird, very hard to reproduce edge case. I was not able to reproduce it. I will enable logging on my device and hope that I can catch the error another time with logging active.

**Comment by Ein-Tim** [comment]
- PR fixing this: https://github.com/corona-warn-app/cwa-app-ios/pull/4972
@dsarkar Please apply the `Fix 3.1` label to this issue.

**Comment by Ein-Tim** [comment]
@larswmh 

- Please remove the label again, the PR has been reverted: https://github.com/corona-warn-app/cwa-app-ios/pull/5002

Could you cross-check why, please?

**Comment by larswmh** [comment]
@Ein-Tim 

> * Please remove the label again, the PR has been reverted: [Revert " Fix/14416 Bad-behavior-of-CWA-when-WLAN-has-no-connection" #5002](https://github.com/corona-warn-app/cwa-app-ios/pull/5002)
> 
> Could you cross-check why, please?

Good morning Tim, about two weeks ago someone posted a comment mentioning that changing the timeouts would be rather risky, but I cannot tell for certain if that was really the reason why it was reverted now. There has been no communication on the linked in internal ticket after that.

**Comment by Ein-Tim** [comment]
@larswmh 

Thank you for the answer! Could you maybe ask the team if they plan to fix this in another way?

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode, I don't expect this bug to be fixed anymore.. I'm therefore closing this issue now.
