### ISSUE TITLE
Disable "Risiko Ermittlung" on Startup.

### ISSUE THREAD

**Issue by Weble-xx** [corona-warn-app/cwa-app-ios#495]
## Describe the bug

Disable "Risiko ermittlung" on Start.

## Expected behaviour

Click on "Nicht aktivieren" when starting. And then the whole thing is deactivated.

## Steps to reproduce the issue

1. Start the App in the Simulator. (Simulator settings: Language German)
2. On The Start Sceen "Wie Sie die Risiko-Ermittlung ermöglichen" click "Nicht aktivieren"
3. On the Dashboard click "Risiko-Ermittlung aktiv"
4. We see, despite the fact that the whole thing was not activated during setup. Is this active.

See Video: https://www.youtube.com/watch?v=KuYQPEE2Qwg

## Technical details

- Host Machine OS (Windows/Linux/Mac):
Mac / iPhone 8 Simulator

**Comment by sebastianpicklum** [comment]
@Weble-xx You are using the ENACommunity Scheme, right? Then you are using only a mock of the Exposure API which in most cases doesn't do anything but return default values that work.

**Comment by inf2381** [comment]
@sebastianpicklum gave the correct response. This behavior is intended.
