### ISSUE TITLE
3.0.0 RC-15 released as "Latest" and not "Pre-release"

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#4982]
* [X] None of the other issue templates apply to this issue.

https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v3.0.0-rc.15 has been released as "Latest" and not as "Pre-release". Please change that @30mar!

---
Internal Tracking ID: [EXPOSUREAPP-14605](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14605)

**Comment by larswmh** [comment]
@Ein-Tim 

Thanks for your report. [Release v3.0.0-RC15](https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v3.0.0-rc.15) has been updated and it now says "Pre-release" instead of "Release".
