### ISSUE TITLE
Close button missing for RiskLegend

### ISSUE THREAD

**Issue by benekuehn** [corona-warn-app/cwa-app-ios#50]
## Describe the bug
The RiskLegend.storyboard is missing a button to dismiss the page sheet.

## Expected behaviour
A close button in the top right corner, to over a button to close the sheet as stated in the development guidelines by apple.
>People dismiss a card by:
> - Swiping down from the top of the screen
> - Swiping down from anywhere on the screen when card content is scrolled to the top
> - **Tapping a button**

[Human Interface Guidelines – Modality](https://developer.apple.com/design/human-interface-guidelines/ios/app-architecture/modality/)

## Steps to reproduce the issue
1. Open the app
2. Click on the information icon in the top right corner

## Possible Fix
Include a close button in the top navigation bar on the RiskLegend page

**Comment by steins-code** [comment]
Risk legend is only draft at the moment and will be completely reworked starting from tomorrow :)

**Comment by benekuehn** [comment]
@steins-code sorry, just saw you comment. Anyway, time for one more coffee tomorrow for the devs :)

**Comment by benekuehn** [comment]
@EisvogelSAP can't this one be closed as the close button is now fixed?
