### ISSUE TITLE
3.0.0 RC-18 released as "Latest" and not as "Pre-release"

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#5004]
* [X] None of the other issue templates apply to this issue.

https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v3.0.0-rc.18 has been released as "Latest" and not as "Pre-release". Please change that @30mar!

Also: Please, could you make sure to correctly tag releases before releasing them? Thank you!

---
Internal Tracking ID: [EXPOSUREAPP-14605](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14605)

**Comment by larswmh** [comment]
Thanks for your report @Ein-Tim, I've changed it to "Pre-release".

About tagging, could you elaborate what you mean by tagging "correctly"?

**Comment by Ein-Tim** [comment]
@larswmh I meant that any RCs (Release Candidates) should be correctly tagged/labeled as "Pre-release" and only final versions (i.e. the versions that are shipped to the App Store) should be marked as "Latest". 

I will close this issue now.
