### ISSUE TITLE
v3.1.0-rc.1 released as "Latest" and not "Pre-release"

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#5008]
* [X] None of the other issue templates apply to this issue.

https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v3.1.0-rc.1 has been released as "Latest" and not as "Pre-release". 

@30mar It would be easier for all of us if you could just, when creating the release, check the box next to the text "This is a pre-release" & not the box next to the "Set as the latest release" text! Thank you!

---
Internal Tracking ID: [EXPOSUREAPP-14605](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14605)

**Comment by larswmh** [comment]
@Ein-Tim 

Thanks for your report, it has been set to "Pre-release" and this case has been forwarded to the internal ticket
