### ISSUE TITLE
What are you using to ensure app integrity under iOS?

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#5010]
## Avoid duplicates
* [X] Question is not already answered in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Question is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Question has not already been asked in another issue

## Your Question
Which API/tool are you using to check the app's integrity under iOS? I searched the code with the term "DCAppAttestService", as this is the standard method for doing such checks under iOS ([Apple Developer link](https://developer.apple.com/documentation/devicecheck/establishing_your_app_s_integrity)), however, I didn't find anything. So I wonder what API/tool are you actually using to check the app's integrity here?

**Comment by thomasaugsten** [comment]
The DeviceCheck API is used
https://developer.apple.com/documentation/devicecheck

https://github.com/corona-warn-app/cwa-app-ios/blob/release/3.1.x/src/xcode/ENA/ENA/Source/Services/PPAccessControl/PPACDeviceCheck.swift

**Comment by Ein-Tim** [comment]
Thanks Thomas, closing as answered!
