### ISSUE TITLE
Help wanted: Attempting to run tests only throws error

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#5031]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details
- Device name: Simulator on MacBook Air M1
- iOS version: 16.2 on Xcode 14.2 
- App version: 3.0.0 or another, newer branch

## Describe the bug

When I attempt to run tests on my machine, I only get the error 
```
cwa-app-ios/src/xcode/ENA/HealthCertificateToolkit/Tests/HealthCertificateToolkitTests/CertificateAccess/DigitalCovidCertificateAccessTests.swift:7:18 Module 'HealthCertificateToolkit' was not compiled for testing
```

## Steps to reproduce the issue

1. Download the source code of this repository
2. Attempt to run any test (in my case I tried to run https://github.com/corona-warn-app/cwa-app-ios/blob/release/3.2.x/src/xcode/ENA/ENA/Source/Scenes/AppClosureNoticeDetails/__tests__/AppClosureNoticeDetailsViewModelTests.swift)
3. See that Xcode only throws the above-mentioned error message

## Expected behaviour

Xcode should run the tests and not throw an error message. 

## Possible Fix

No idea, I'm opening this issue because I hope to get some ideas on how to fix this from the community/developers (:

---
Internal Tracking ID: [EXPOSUREAPP-14694](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14694)

**Comment by dsarkar** [comment]
@Ein-Tim  Dev team members are pretty much occupied with priority issues, please expect some delay in response regarding this ticket.

**Comment by 30mar** [comment]
@Ein-Tim is the issue still reproducable? we fixed a problem with community build recently please check again.

**Comment by Ein-Tim** [comment]
I will cross check later

**Comment by Ein-Tim** [comment]
Can't reproduce.
