### ISSUE TITLE
Dark Mode Background Color in ExposureNotificationSettingVC

### ISSUE THREAD

**Issue by larsaugustin** [corona-warn-app/cwa-app-ios#51]
## Describe the bug
In the `ExposureNotificationSettingViewController`, the `TracingHistoryTableViewCell` and `DescriptionTableViewCell` use a background color on the label that's different from the background color of the cell. While both colors appear the same in light mode, they differ in dark mode.

## Expected behaviour
The same dynamic color should be used for both backgrounds. 

## Steps to reproduce the issue
The different colors can be seen when having dark mode turned on and opening the exposure notification setting view controller.
![dark mode color bug](https://user-images.githubusercontent.com/37324823/83353553-b0ad9380-a353-11ea-8456-0731db04c2be.png)

## Possible Fix
Use the same dynamic colors

**Comment by larsaugustin** [comment]
I can also fix this issue!

**Comment by steins-code** [comment]
done
