### ISSUE TITLE
Status tab app closure notice arrow is not aligned correctly

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#5132]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone XR
- iOS version: 16.4
- App version: 3.1.0

## Describe the bug

The app closure notice arrow is not aligned correctly. Here's a screenshot with added lines so that the esthetical problem becomes clear:
<img src="https://user-images.githubusercontent.com/67682506/228864388-d345d3b3-9836-4687-a782-5430d97f1806.jpeg" width="300">

## Steps to reproduce the issue

1. Open your eyes (-;
2. Open the CWA
3. Take a look at the alignment of the arrows on the "Status" tab and notice, that the app closure info box arrow is not aligned correctly

## Expected behaviour

The arrows should all be in one line.

## Possible Fix

Probably add some padding, etc.

## Additional context

I hope this wasn't already fixed and I oversaw the PR?

---
Internal Tracking ID: [EXPOSUREAPP-15005](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-15005)

**Comment by larswmh** [comment]
Thanks for your report @Ein-Tim. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-15005](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-15005)

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
Thanks Lars, you can also add the UX label to this issue!

**Comment by larswmh** [comment]
Fix PR: #5135

**Comment by Ein-Tim** [comment]
Confirm fixed, thanks!
