### ISSUE TITLE
Quick actions are not reduced correctly in hibernation state

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#5166]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 14 Pro
- iOS version: 16.4.1
- App version: 3.2.1

## Describe the bug

The quick actions of the CWA iOS app are not correctly adapted in the hibernation state.

Here's a screenshot, taken with version 3.2.1, with CWA showing all 4 quick actions, although it should only show "Zertifiakte anzeigen" & "Eintrag hinzufügen":

<img src="https://user-images.githubusercontent.com/67682506/235525305-a5ff271e-333e-41d4-ae5b-10b8335717fb.PNG" width="300">

## Steps to reproduce the issue

1. Install version 3.2.1 from the app store
2. Long press the CWA icon
3. See the quick actions

## Expected behaviour

The quick actions "QR-Codes sannen" & "Check-ins anzeigen" should not be shown in hibernation state. For comparison how it should look, you can take a look at Android, where the actions were reduced correctly. 

---
Internal Tracking ID: [EXPOSUREAPP-15131](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-15131)

**Comment by Ein-Tim** [comment]
@dsarkar FYI: The JIRA ticket ID is missing here

**Comment by larswmh** [comment]
@Ein-Tim 

> FYI: The JIRA ticket ID is missing here

The JIRA ticket ID has now been added, thanks for your report!

**Comment by flxschmidt** [comment]
Good catch @Ein-Tim 👍 

PR: https://github.com/corona-warn-app/cwa-app-ios/pull/5169

**Comment by Ein-Tim** [comment]
Confirm fixed with version 3.2.2.
