### ISSUE TITLE
Missing Pull Request Template

### ISSUE THREAD

**Issue by SvenTiigi** [corona-warn-app/cwa-app-ios#58]
## Current Implementation
Currently there is no pull request template available in the cwa-app-ios GitHub repository.

## Suggested Enhancement
Adding one or more pull request templates.
https://help.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository

## Expected Benefits
Standardized pull requests in terms of contribution guidelines, motivation, solution, implementation, tests, etc.

**Comment by haosap** [comment]
Hi @LukasMasuch ,
Do we have any plan to do it for every Repos?
Thanks.
Best regards
Hao
