### ISSUE TITLE
[UI] TAN Entry view breaks when gestures are cancelled

### ISSUE THREAD

**Issue by tens0rfl0w** [corona-warn-app/cwa-app-ios#591]
## Describe the bug
Just a quick reminder that in the latest development build, the TAN entry view submit button still breaks when doing the back swipe gesture and cancelling it half way. The button then gets enabled and clickable by the user even without a valid TAN entered. Another bug regarding the TAN entering view is when you swipe down to close the pop up view and cancel it half way, the button snaps to the bottom and gets invisible because of the keyboard laying above it.

![FCDC9162-CC99-416F-BE1A-3F1A6B6C4B01](https://user-images.githubusercontent.com/57523343/84564923-c4022b00-ad65-11ea-8b8b-56a0d6750b3f.png)
![DF24DB59-8BF9-4B13-BD11-E5E8E23B9A0B](https://user-images.githubusercontent.com/57523343/84564927-c795b200-ad65-11ea-9a59-25479295e7b1.png)

**Comment by hansemannn** [comment]
PR: https://github.com/corona-warn-app/cwa-app-ios/pull/594
