### ISSUE TITLE
Refactor/Rewrite HomeViewController + HomeInteractor

### ISSUE THREAD

**Issue by ChristianKienle** [corona-warn-app/cwa-app-ios#60]
`HomeViewController` + `HomeInteractor` are in a less than ideal state. The `HomeViewController` is the the most important thing for both, the user and for developers. It is a central piece of code and is modified frequently. Because of that it should be easy to understand how it works and how one can change it.

It seems that many developers struggle to understand how it actually works.

We should come up with an easy to understand implementation.

Rem: This issue is currently on hold because it is discussed who will actually do it. This issue is a reminder for us to actually do it and signals to the community that we are very well aware of the shortcomings of the current implementation. That being said the current implementation served us very well up to this point. Every piece of code gets rewritten sooner or later. :)

---
Internal Tracking ID: EXPOSUREAPP-1958

**Comment by dasdom** [comment]
Refactoring works better with tests. I would like to add tests for methods like `showExposureSubmission(with:)`. A test would look like this:

```
func testShowExposureSubmission_presentsExposureSubmissionNavigationController() {
	let window = UIWindow(frame: CGRect(x: 0, y: 0, width: 200, height: 200))
	window.rootViewController = sut
	window.makeKeyAndVisible()
	
	sut.showExposureSubmission()
	
	XCTAssertTrue(sut.presentedViewController is ExposureSubmissionNavigationController)
}
```

Do you think those tests would be valuable?

**Comment by dasdom** [comment]
I tried to add some tests. But the really useful tests are not possible to write because `homeInteractor` is private.

**Comment by marcussc** [comment]
Has been rewritten in release/1.11
