### ISSUE TITLE
Image mistake

### ISSUE THREAD

**Issue by Luca1719** [corona-warn-app/cwa-app-ios#604]
## Current Implementation

The asset Illu_Onboarding_Datenschutz under cwa-app-ios/src/xcode/ENA/ENA/Resources/Assets/Assets.xcassets has a mistake in the shape. On the overlap between the woman's left arm and her body is a white stripe.

---
Internal Tracking ID: EXPOSUREAPP-1873

**Comment by christian-weiss** [comment]
The arm should have a (white) outline to distinguish the arm (foreground) from body (background).
"Outline" of torso should NOT "cut" the arm in 2 pieces.

This applies to all instances of that woman (other files affected).

**Comment by mynchau** [comment]
Hi christian-weiss, thanks for your contribution and this finding! Your issue is being forwarded. 
Best regards
MC
Your Corona Warn-App Open Source Team

**Comment by Luca1719** [comment]
I found this 😅

**Comment by stahlmagnat** [comment]
talking about image mistakes, isn't it a mistake that all shown people in images don't wear masks? :) At least some mask reference would be great...

**Comment by heinezen** [comment]
This was fixed in CWA version 1.5

----
Corona-Warn-App Open Source Team
