### ISSUE TITLE
Inconsistency between App Store metadata and in-app privacy statement

### ISSUE THREAD

**Issue by mlenkeit** [corona-warn-app/cwa-app-ios#621]
## Describe the bug

In the App Store, the app is classified as `17+` in the Age category. However, the (english) privacy statement says "aimed at people [...] at least 16 years old".

Screenshot App Store:

![image](https://user-images.githubusercontent.com/2060790/84732846-05305000-af9d-11ea-9710-c494f16c71eb.png)

Screenshot privacy statement

![image](https://user-images.githubusercontent.com/2060790/84732855-09f50400-af9d-11ea-8430-7f5b58aff48e.png)

## Expected behaviour

But should be consistent.

## Steps to reproduce the issue

Compare App Store with the (english) privacy statement in the app.

## Technical details

- Host Machine OS (Windows/Linux/Mac): n/a

**Comment by SebastianWolf-SAP** [comment]
There is simply no 16+ category in the App Store. Please see https://help.apple.com/app-store-connect/#/dev269f11291 for details.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by mlenkeit** [comment]
Good catch, thank you 👍
