### ISSUE TITLE
Inconsistent screen transitions on 'Notify and Help > Selection' screen

### ISSUE THREAD

**Issue by mlenkeit** [corona-warn-app/cwa-app-ios#622]
## Describe the bug

On the screen titled "Selection" where I can choose to scan a QR code, enter a TAN, or request a TeleTAN, the transitions between the screens are inconsistent:

- when clicking on "TAN" to enter a TAN, the title is changed in-place (from "Selection" to "TAN Entry") while the TAN fields slide in from the right.
- when clicking on "No TAN yet?", the entire next screen (including the title) slide in from the right.

## Expected behaviour

Consistent screen transitions in the same context.

## Steps to reproduce the issue

Click on "Notify and Help", proceed to "Selection", and tap on either "TAN" or "No TAN yet?" and observe the different screen transitions.

## Technical details

- Host Machine OS (Windows/Linux/Mac): n/a

**Comment by tens0rfl0w** [comment]
There is already a open PR addressing some issues with this view controller (not the ones mentioned above): #594 
(Just mentioning this so there is no inconsistency when working on that issue.)

**Comment by mlenkeit** [comment]
@mynchau I noticed that you assigned me to the issue. I'm not a developer on the project. Was this assigned to me on purpose?

**Comment by tens0rfl0w** [comment]
@mlenkeit This has been fixed, you can close this issue for now!🙂

**Comment by mlenkeit** [comment]
@tens0rfl0w thanks for the fix!
