### ISSUE TITLE
Wrong URL for sharing the app

### ISSUE THREAD

**Issue by ThomEls** [corona-warn-app/cwa-app-ios#625]
## Describe the bug

When sharing the app using functio „Corona-Warn-App teilen“, the URL https://www.corona-warn-app.de/ is Shared, but this URL doesn’t work. 

## Expected behaviour

The URL https://www.coronawarn.app should be used instead.

## Steps to reproduce the issue

1. Go to CWA main screen 
2. Click on „Corona-Warn-App teilen“
3. Select e.g. WhatsApp
4. See wrong URL
## Technical details

- Host Machine OS (Windows/Linux/Mac):
iPhone

**Comment by SebastianWolf-SAP** [comment]
The app has not yet been officially presented, it may take some time until the respective site are live and running... Thank you in advance for your patience!

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by ThomEls** [comment]
Ok, dann war ich wohl zu schnell, danke für die Info!
