### ISSUE TITLE
Misleading information about the data exchange during onboarding

### ISSUE THREAD

**Issue by skyfmmf** [corona-warn-app/cwa-app-ios#628]
## Current Implementation
During the onboarding process, the app shows a view informing about what happens when you are tested positive. The text on this page says [_People whose encrypted random IDs your device has collected will now receive a warning..._](https://github.com/corona-warn-app/cwa-app-ios/blob/ce3299e0a37caea5c8419c3a02133e1f8c748224/src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings#L208) in the English localization and [_Die Personen, deren verschlüsselte Zufallscodes Sie gesammelt haben, erhalten nun eine Warnung..._](https://github.com/corona-warn-app/cwa-app-ios/blob/ce3299e0a37caea5c8419c3a02133e1f8c748224/src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings#L208) in the German localization. 

According to my understanding of the protocol, people who have collected an encrypted random ID of my device are notified. The current text may allow the interpretation, that the IDs my device collects are shared with the server in case of a positive test.

## Suggested Enhancement
State clearly that people who have collected an ID of my device are notified.

**Comment by inf2381** [comment]
Thanks for the remark! I copied your text to #440
