### ISSUE TITLE
Need to enable bluetooth

### ISSUE THREAD

**Issue by Mucithe** [corona-warn-app/cwa-app-ios#629]
Are you 100% sure that the device must have fully activated Bluetooth (and thus broadcast its device name) under iOS as checked by ActionTableViewCell.swift?  Where did you get this information from?  The settings app is completely fine with me having contact tracing enabled (privacy -> health -> contact tracing) while Bluetooth is disabled and I couldn't find this requirement anywhere in the documentation of the framework. Is uncertainty the reason why you are warned about a "limitation" instead of a deactivation? If this is mistakenly seen as a prerequisite, it could have a massive impact on public acceptance.

**Comment by Luca1719** [comment]
I don’t though this too, because the API from Apple and Google does indeed not need a Bluetooth connection because it’s all over BLE. Therefore I wrote an Email to the CWA-Team, where they explained that Blietooth enabled in settings/ control center is a requirement

**Comment by StephanGeorg** [comment]
I also wondered why the app does not warn me that Bluetooth is disabled but shows "Exposure logging active".

**Comment by inf2381** [comment]
> I also wondered why the app does not warn me that Bluetooth is disabled but shows "Exposure logging active".

Thanks for the remark! Did "disconnect" bluetooth from the control center or did you completely disable it using Siri or the system settings? Because BLE stays on if you only disconnect bluetooth

**Comment by StephanGeorg** [comment]
It was completely disabled from the device settings when I installed the app.

**Comment by Mucithe** [comment]
@StephanGeorg You might want to open a new issue for that. I just didn’t read careful enough. While it isn’t mentioned in the documentation, it is mentioned under "more information" in the settings app.
