### ISSUE TITLE
Error message on app start

### ISSUE THREAD

**Issue by Phill93** [corona-warn-app/cwa-app-ios#630]
## Describe the bug

Every time the app is started and when there is activity in the app, the attached error message appears.

![20-06-16 09-11-17 2763](https://user-images.githubusercontent.com/1454797/84747652-d2478580-afb7-11ea-883d-d4962d59a52c.png)

## Expected behaviour

No error message.

## Steps to reproduce the issue

1. Open the app

## Technical details

iPhone XR iOS 13.5 (17F5065a)

**Comment by inf2381** [comment]
Hi @Phill93. Does this error occur when running the App Store version of this app or when building the community scheme?

**Comment by Phill93** [comment]
I am running the AppStore Version

**Comment by inf2381** [comment]
Okay 😞 . Did this error occur directly on your first app start or did you do something prior to that?

**Comment by svewag** [comment]
@Phill93 do you already have installed another app which uses the tracing-api?

**Comment by Phill93** [comment]
> Okay 😞 . Did this error occur directly on your first app start or did you do something prior to that?

Yes on the first start.


> @Phill93 do you already have installed another app which uses the tracing-api?

No, it’s the first app of this sort.

**Comment by inf2381** [comment]
Could you please follow the subsequent steps? If the error still persists afterwards, we can have a deeper look at your issue.

- In Settings > Privacy > Health > COVID-19 Exposure Notifications, press "Delete exposure log" (if possible)
- Delete the App
- Reboot your smartphone after updating to iOS 13.5
- Insert a valid SIM card (whether physical SIM or eSIM)
- Switch off flight mode and activate Bluetooth
- Install the app and do not reject the dialogs

**Comment by Phill93** [comment]
Sorry for the late answer, i have done the tasks.
The message is now no longer displayed.

**Comment by Phill93** [comment]
Correcting my older Comment. The message is not gone.

**Comment by Phill93** [comment]
Hello,

I have found the solution to my problem. On the device with the error message I use the iOS beta versions (build number 17F5065a = iOS13.5 Beta 4), app seems to have problems with this version. I have now installed the normal iOS version and the error has disappeared.
