### ISSUE TITLE
"Download-Link versenden" is wrong and leads to an unsafe webpage!!!

### ISSUE THREAD

**Issue by miguelcarrero** [corona-warn-app/cwa-app-ios#631]
## Describe the bug

The link provided under "Download-Link versenden" is wrong and leeds to an unsage webpage!

## Technical details

- Host Machine OS (Windows/Linux/Mac):
iOS

**Comment by noahleal** [comment]
Could you provide more information, i.e. a screenshot? On both the English and German versions of the app the link is for corona-warn-app.de which is the correct address. 
![IMG_0978](https://user-images.githubusercontent.com/34426996/84748676-3e76b900-afb9-11ea-9dde-385cf8116270.PNG)

**Comment by tens0rfl0w** [comment]
The website now redirects to the correct download page from the 'Bundesregierung'.(https://www.bundesregierung.de/breg-de/themen/corona-warn-app)

This was just updated approx. 1 hour ago, so maybe the page is cached on your device. Try refreshing the website to get redirected to the correct webpage.

**Comment by miguelcarrero** [comment]
Looks like its an issue with the male ware software used by my employee 

https://malware.opendns.com/main?url=corona-warn-app.de&server=ams15&prefs=&tagging=&nref

However https://www.coronawarn.app/en/ works fine!

Best regards,
Miguel
