### ISSUE TITLE
Spelling error on screenshot in German Apple App Store

### ISSUE THREAD

**Issue by MauriceArikoglu** [corona-warn-app/cwa-app-ios#633]
"anonym" was spelled incorrectly.

## Expected behaviour

Word spelled correctly.

## Additional context

![IMG_238ABFB70137-1](https://user-images.githubusercontent.com/5528623/84749649-85b17980-afba-11ea-9191-5362cae1ff57.jpeg)

**Comment by crykn** [comment]
Furthermore, "ihre" should be capitalised.

**Comment by felixbohnacker** [comment]
> Furthermore, "ihre" should be capitalised.

If I'm not mistaken, "ihre" is third-person plural here. Therefore, I don't think that it should be capitalised.

**Comment by MauriceArikoglu** [comment]
@felixbohnacker correct.

**Comment by crykn** [comment]
@felixbohnacker ah darn, that's true! Thanks for the correction.

**Comment by inf2381** [comment]
Will be fixed in the next update
