### ISSUE TITLE
No warning that bluetooth is disabled when disabling via Control Center

### ISSUE THREAD

**Issue by lennarto** [corona-warn-app/cwa-app-ios#635]
When disabling bluetooth in the Settings, I get a warning in the Corona Warn App. However, if disabling bluetooth via the Control Center (the swipe up menu) then I don't get a warning in the Corona Warn App.
(Device: iPhone 7, iOS: 13.5.1)

**Comment by tens0rfl0w** [comment]
BLE doesn't gets deactivated when you 'turn-off' (not really turning it off) Bluetooth from the Control Center. To turn off BLE you have to deactivate Bluetooth from the System settings. Thats why Exposure Tracking still works when doing that.

**Comment by lennarto** [comment]
Good to know. Thank you!
