### ISSUE TITLE
Chinese iPhones shows Germany Version instead of English Version

### ISSUE THREAD

**Issue by Lhendrichs** [corona-warn-app/cwa-app-ios#636]
-->

## Expected behaviour

Chinese iPhones shows Germany Version instead of English Version

## Steps to reproduce the issue

Just installed the App.

## Technical details

iOS 13.5.1 on iPhone Xr

## Possible Fix

Either a button to switch the language or a Fallback to English instead of German.

**Comment by steins-code** [comment]
The selection of the language depends on your user preference settings in iOS. In order to select english for the app, please make sure English is in higher order than German like shown in the screenshot below.
![Uploading IMG_BF61721CE6A2-1.jpeg…]()

**Comment by darkdragon-001** [comment]
@steins-code What if neither German nor English is set there?

**Comment by Lhendrichs** [comment]
Thanks Conrad. Tested and worked!
