### ISSUE TITLE
Apple COVID-19-Kontaktprotokoll: “In deiner Region nicht verfügbar”

### ISSUE THREAD

**Issue by VolutionLabs** [corona-warn-app/cwa-app-ios#638]
## Current Behaviour
I can not activate Apple COVID-19-contact protocol (neither within the app nor in settings)
Within app: when I try to activate “Risiko-Ermittlung” and accept the legal infos / authorize, “Risiko-Ermittlung” stays deactivated.
Within settings:
 Apple COVID-19-contact protocol: "not available in your region". (My region is Germany (also checked the settings of my location in my Apple ID. My region is set correctly))

## Technical details

iPhone 6s, iOS 13.5.1

**Comment by inf2381** [comment]
@VolutionLabs Would it be possible for you to test your device with the Italian app [Immuni](https://apps.apple.com/us/app/immuni/id1513940977) to find out whether this issue is our fault or a bug on iOS?

**Comment by VolutionLabs** [comment]
@inf2381 I installed Immuni. When I click on 'activate', it does not work either. So I guess it is definitively a bug in iOS.

I am not using an active corporate profile.

**Comment by inf2381** [comment]
@VolutionLabs Others are also facing this issue. Some of them fixed it by inserting a SIM card and then reinstalling the app.

**Comment by VolutionLabs** [comment]
@inf2381 
Update: 
I restarted the iPhone. Now it works. 

(I had to update to 13.5.1 before I could install the app. This might have been the cause and maybe is not an issue of the app, but of iOS.)

**Comment by elektromutti** [comment]
same here, in my iphone 6S. 

well, i updated my phone to 13.5.1,  i restarted my it twice, i re-installed the app and again restarted the phone - but still i am experiencing the same problem (settings -> privacy -> health: "in deiner region nicht verfügbar") 
duh.

(wife uses exact same type of phone, exact same age: it works. it makes me mad.)

**Comment by PeterJLo** [comment]
Hi! I do have the same problem with my iPhone 6S. The function couldn't be activated saying that this function is not available in my region. After a restart, it worked.

**Comment by elektromutti** [comment]
that's nice!
in mine, it didn't. 
nothing of all worked. 
nothing at all changed.

**Comment by VolutionLabs** [comment]
I posted another issue #663.

Suggested Enhancement:
further infos in FAQ on updating, installation and workaround for specific devices

**Comment by lasscap** [comment]
I had the same problem on an iPhone 6S. After restarting the device twice it worked.

Judging by the other comments, this seems to be a problem with iOS which is most prevalent on iPhone 6S.

**Comment by chapolote** [comment]
In our case it helped to switch off WLAN, activate contact-protocol and then switch on WLAN again

**Comment by itinance** [comment]
I've got the same error after I left my district in Berlin, where I live, and moved to another district for some hours. When I came back, this error appeared 

<img width="315" alt="Screenshot 2020-06-19 19 46 02" src="https://user-images.githubusercontent.com/1758597/85165251-d39dda00-b265-11ea-8156-781369a0f536.png">

**Comment by engelchrisi** [comment]
chapolote is right. When the notifications are always disabled in the COVID-19 settings then this can be caused by the WIFI. I faced exactly the same with the XR of my daughter and 13.5.1. 
**SOLUTION**: simply **turn off the Wifi** and suddenly your region is support and you can switch on the contact protocol. Go to the RKI app and click on the authorization button and accept. Then it should be enabled.
Enabling WIFI seems not to have an effect anmore.

This is an IOS not a Corona App bug.

**Comment by Tobias-Keller** [comment]
had the same problem, turn off wlan and it works...

**Comment by pandabear-de** [comment]
> chapolote is right. When the notifications are always disabled in the COVID-19 settings then this can be caused by the WIFI. I faced exactly the same with the XR of my daughter and 13.5.1.
> **SOLUTION**: simply **turn off the Wifi** and suddenly your region is support and you can switch on the contact protocol. Go to the RKI app and click on the authorization button and accept. Then it should be enabled.
> Enabling WIFI seems not to have an effect anmore.
> 
> This is an IOS not a Corona App bug.

This also worked for me.

New iOS S6 phone with currently no cell connection. After I turned off WiFi I was able to activate the Covid-19 settings.

**Comment by lochmeli** [comment]
My Iphone 6s with iOS 13.5.1. , no wifi switched on , rebooted twice and can still not activate the tracing. Nor on Datenschutz. Still shows : in deiner Region nicht verfügbar

**Comment by Alexcirlan** [comment]
I have a different problem and switching off wifi didn’t solve. Restarted... deleted and reinstalled the app... nothing worked
![1ED88482-302C-4959-9F1D-FE8115334671](https://user-images.githubusercontent.com/54180350/86506727-77dd6000-bdd2-11ea-8d4c-12e93285b00d.png)


![54E3397C-0C01-46E0-A22D-78CDE070B9A7](https://user-images.githubusercontent.com/54180350/86506724-7449d900-bdd2-11ea-9889-1ff52898f25a.png)

**Comment by USR123456** [comment]
Look guys this issue is not solved. I don't understand why this was closed. Yesterday I swapped phones (both on iOS13.6). 

My behaviour is identical with the original poster. Not able to activate in the app and settings say: Not available in your Region. 

My device is an iPhone X. I tried restarting multiple times and turning Wifi and Mobile Data off. Problem persists.

> ## Current Behaviour
> I can not activate Apple COVID-19-contact protocol (neither within the app nor in settings)
> Within app: when I try to activate “Risiko-Ermittlung” and accept the legal infos / authorize, “Risiko-Ermittlung” stays deactivated.
> Within settings:
> Apple COVID-19-contact protocol: "not available in your region". (My region is Germany (also checked the settings of my location in my Apple ID. My region is set correctly))
> 
> ## Technical details
> iPhone 6s, iOS 13.5.1

**Comment by SebastianWolf-SAP** [comment]
@USR123456 Indeed, this issue was closed a little prematurely as iOS 13.6 (which was supposed to include a complete fix) was released just the day before yesterday. However, with 13.6 we got another bug which you are also describing. Please follow-up in #911 for this problem.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by Alexcirlan** [comment]
Still not solved

**Comment by m33x** [comment]
iOS 13.6 installed two days ago. Today, the Notification showed up again.

iOS 13.6 does not fix this issue!!!

**Comment by SebastianWolf-SAP** [comment]
In this case we are reopening this issue. In case anybody else can confirm this issue with iOS 13.6, please let us know.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by SebastianWolf-SAP** [comment]
Sorry, also this one was a little too early. We already have open issues for all of the known alternatives. Let's extend the scope of these issues to all versions if they occur in both versions 13.5 and 13.6

- In case you are getting the error "Region not supported", please follow-up in #911
- In case you are still getting the "Region changed" popup, please follow-up in #645

Mit freundlichen Grüßen/Best regards,
SW
Corona Warn-App Open Source Team
