### ISSUE TITLE
(1) different information: app vs. government sites / (2) app always running yes/no

### ISSUE THREAD

**Issue by JayBrown** [corona-warn-app/cwa-app-ios#641]
If I remember correctly, in the app it says to always ("dauerhaft") keep the "Risikoermittlung" active. On a governmental site I've read that users should enable this feature whenever they leave the house. For what it's worth, the latter governmental information is useless if you receive visitors at home. At any rate, there's an informational discrepancy.

Furthermore, there is no information if the app itself needs to be running in the background all the time, or if it's OK to swipe-to-quit the app. The latter depends on iOS behavior: does the BLE contact scan continue after the user has quit the app? Does the app need to be launched to contact the server to access/download the exposure ID database?

**Comment by max-hzi** [comment]
> Furthermore, there is no information if the app itself needs to be running in the background all the time, or if it's OK to swipe-to-quit the app. The latter depends on iOS behavior: does the BLE contact scan continue after the user has quit the app? Does the app need to be launched to contact the server to access/download the exposure ID database?

Actually it's described in the ToS/ Nutzungsbedinungungen. But I agree, there is no sharp answer and maybe this aspect should be included in the user guide.

**Comment by thomasaugsten** [comment]
As far as I know, the OS does the BLE scanning and sending and the background task of the app to do risk analysis and notification is also running when the app is swipe-to-quit.  You can manually disable the exposure notification but when you leave the house you should manually enable it again

**Comment by SteLei1973** [comment]
In the "Nutzungsbedingungen" under paragraph 7 it states:
**Die App muss auf dem Endgerät laufen und eingeschaltet sein**
Furthermore it states:
"Wenn Sie die App nicht starten, ausschalten oder beenden speichert die App keine Begegnungen mit anderen Personen und erzeugt keine Zufallscodes zur Speicherung durch andere Personen. Wenn Sie das Endgerät neu starten (z.B. nach dem Ausschalten, nachdem die Batterie leer war oder nach einem Update des Betriebssystems), müssen Sie auch die App neu starten"

So it seems, that it **is** necessary to have the app at least running in the background, and that a swipe-to-quit would stop the app from saving encounters with other people and creating random ids to share with other people, or am I wrong?

**Comment by JayBrown** [comment]
If this is true, you can't tuck away this important info in the terms of use. Nobody will read the fine print. It needs to be front-and-center when launching the app. I swipe-to-quit all my apps I don't need. But afaik, the app is just a simple frontend, while iOS (the exposure notification system) does all the heavy lifting. So the default expectance would be: launch the app to enable BLE contact scans, swipe-to-quit, and then the system will do the rest, scan for BLE contacts, and you only need the app if you want some info, or if you've contracted the WuFlu & need to scan a QR code or something. Question would then be: does the app still have its own background processes after swipe-to-quit, i.e. polling the server for db updates?

**Comment by max-hzi** [comment]
From German FAQ; https://www.coronawarn.app/de/faq/

>Muss ich die App immer geöffnet lassen, damit Begegnungen aufgezeichnet werden?

>Nein. Solange Du in der App die Risiko-Ermittlung aktiviert hast und Bluetooth eingeschaltet ist, werden Begegnungen aufgezeichnet. Du kannst die App schließen.

So swipe-to-quit does not affect the functionality.

**Comment by JayBrown** [comment]
Maybe the current version of the in-app terms-of-use are still from a time when the project was supposed to use the centralized approach… I think it was called PEPP-PT. Without the Apple API, the user would probably have had to keep the app running all the time.

But we can't know for sure. And we don't know which information is true. For now I will go with the official online FAQ and swipe-to-quit the app.

**Comment by SteLei1973** [comment]
I think this definitly has to be clarified and streamlined in both (or even more?) places, so that the FAQ and the TOS/Nutzungsbedingungen state the same. I hope a developer could comment which one is the current behaviour of the released app "1.0.2 (2)", although it seems to be like @max-hzi states, but I just want to be sure about that ...

**Comment by max-hzi** [comment]
>I think this definitly has to be clarified and streamlined in both (or even more?) places

I highly agree. If you refer to my first answer in this thread, you can see that I even thought I read it in the ToS, but I must have read it somewhere else when I set it up.

**Comment by inf2381** [comment]
Thanks for the fruitful discussion. I already linked this issue in #440 where we gather all text related issues for the content providers. As @thomasaugsten already mentioned, the contact tracing still works after a swipe-to-quit. It will also not affect the tracing history within the app as long as you don't go to the system settings and manually revoke permissions for the Corona-Warn-App.

**Comment by kaluju** [comment]
> I think this definitly has to be clarified and streamlined in both (or even more?) places, so that the FAQ and the TOS/Nutzungsbedingungen state the same. I hope a developer could comment which one is the current behaviour of the released app "1.0.2 (2)", although it seems to be like @max-hzi states, but I just want to be sure about that ...

**--> I have forwarded this request, as it concerns a legal text (Nutzungsbedingungen), that I can't change myself.**
