### ISSUE TITLE
Inconsistent confusing wording in iOS

### ISSUE THREAD

**Issue by schramm-michael** [corona-warn-app/cwa-app-ios#642]
## Describe the bug
Inconsistent (confusing) wording in message container for  determined risk:
Da Sie Ihre **Begegnungs-Aufzeichnung** ...  (feels like an additionally untold tracking)
![20200616_123253](https://user-images.githubusercontent.com/5102797/84766752-a0431d00-afd1-11ea-8c30-defae3581aab.png)

## Expected behavior
App-wide consistent wording, against confusion about possible inappropriate tracking.
The user has activated "Risiko-Ermittlung" not "Bewegungs-Aufzeichnung".

Da Sie Ihre **Risiko-Ermittlung** ... 

## Steps to reproduce the issue
Newly installed App shows this for the first 24 hours after starting on the first screen

## Technical details

- Host Machine OS (Windows/Linux/Mac):
App-Version 1.0.2 (2)
iOS13.5.1
iPhone XS
Locale DE_de
## Possible Fix
Please replace Begegnungs-Aufzeichnung by Risiko-Ermittlung:

**Comment by mynchau** [comment]
Thanks for your contribution! I've added your issue to #440 where we collect text related enhancement requests. I'm closing this issue here. 
Best regards
MC
Your Corona Warn-App Open Source Team

**Comment by mynchau** [comment]
As texts are provided by the RKI and the Bundesregierung, please list future findings to #440. Thank you for your support!
