### ISSUE TITLE
Implement a warning for Bluetooth, so users don't deactivate it

### ISSUE THREAD

**Issue by thisdudeisvegan** [corona-warn-app/cwa-app-ios#648]
## Current Implementation
Currently the app shows the request to activate the iOS (and Google on Android) exposure API, so the app is working.

## Suggested Enhancement
Add a warning message for people who deactivate their Bluetooth, to declare, that the app needs it to work properly. 

## Expected Benefits
Better results because people who are not much into IT will know, that they need to let their Bluetooth activated.

**Comment by jlnprssnr** [comment]
The app does give a warning when Bluetooth is disabled in the settings. Keep in mind that the Bluetooth swtich in iOS control center does not turn off the Bluetooth radio, but just disables pairing to known devices.

**Comment by thisdudeisvegan** [comment]
Well...thanks for clarification. I didn't had that in my mind while opening the issue. Closed. :)
