### ISSUE TITLE
"Risiko-Ermittlung aktiv" when bluetooth disabled

### ISSUE THREAD

**Issue by hajo62** [corona-warn-app/cwa-app-ios#652]
When I disable Bluetooth, the ios-app still shows "Risiko-Ermittlung aktiv". 
Only when switched to "Flug-Modus", Risiko-Ermittlung is inaktiv.

If Bluetooth is off, but the app is still working, that should be clarified i.e. in FAQ.
If Bluetooth is off, but the app stops working, the status value displayed is wrong.

**Comment by tens0rfl0w** [comment]
Did you disabled Bluetooth via the Control Center or the settings app? (Is the Bluetooth symbol in the Control Center grey or dark?)

**Comment by hajo62** [comment]
Not in App.
System setting. It's grey.

**Comment by tens0rfl0w** [comment]
Ok all right, that means you didn't turned Bluetooth off, you just disconnected every device and disabled re-connecting/discovery. That does not turn off Bluetooth and the needed Bluetooth Low Energy.

**Comment by hajo62** [comment]
thanks for clarifying. Maybe something for a technical part of FAQ?!
