### ISSUE TITLE
Publish download numbers

### ISSUE THREAD

**Issue by benzman81** [corona-warn-app/cwa-app-ios#655]
Hi,

since the app needs a high number of users to work efficiently, it is interesting to know the current number of installations/downloads. Are there any plans to share this on regluar basis?

Regards,
Markus

**Comment by KevinMuessig** [comment]
Hello @benzman81 ,

thank you for your question. We will get back to you as soon as possible.

Thank you.
KM

**Comment by SebastianWolf-SAP** [comment]
To our knowledge our partners (especially the RKI) will definitely communicate the respective figures regularly. We will also see quite some advertising campaigns to motivate people to download and use the app.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
