### ISSUE TITLE
URL used in HTTPClient does not point to "*.coronawarn.app", but to t-online.de

### ISSUE THREAD

**Issue by abds040** [corona-warn-app/cwa-app-ios#658]
I checked the source code, and found the app does not only send data to “*.coronawarn.app”, but also to “https://svc90.main.px.t-online.de”.
 
What data is send to this address?

Code is found at:
https://github.com/corona-warn-app/cwa-app-ios/blob/next/src/xcode/ENA/ENA/Source/Client/HTTP%20Client/HTTPClient%2BConfiguration.swift

Snipped with t-online-URL:

endpoints: Configuration.Endpoints(
  distribution: .init(
    baseURL: URL(staticString: "https://svc90.main.px.t-online.de"),
    requiresTrailingSlash: false
  ),
  submission: .init(
    baseURL: URL(staticString: "https://submission.coronawarn.app"),
    requiresTrailingSlash: false
  ),
  verification: .init(
    baseURL: URL(staticString: "https://verification.coronawarn.app"),
    requiresTrailingSlash: false
  )
)

**Comment by thomasaugsten** [comment]
You can see in the code no data is send to this address. It's the url to the CDN to download the diagnoses keys and all other information to do the risk analysis on each phone.

**Comment by ChristianKienle** [comment]
At @thomasaugsten said, this URL is correct and is used for the production build of the app. I am closing this issue. If you have any additional question feel free to open another issue (or re-open this one if possible).
