### ISSUE TITLE
Error when switching between WiFi and Mobile Data [via Email]

### ISSUE THREAD

**Issue by tkowark** [corona-warn-app/cwa-app-ios#660]
beim Wechsel der Internetverbindung von WLAN auf Mobilfunk zeigt die App keine Verbindung zum Internet an, obwohl in den Einstellungen alles freigegeben ist. 

(Iphone XR, iOS 13.5.1)

Das Gerät wird über ein externes Mobile Device Management von 7P verwaltet/geschützt, das Einfluss auf die Internetverbindung hat. Bisher führte dies aber bei keiner App zu einer Behinderung der Verbindung über Mobilfunk. 

---
Internal Tracking ID: EXPOSUREAPP-1572

**Comment by steins-code** [comment]
Can you provide some more information on how to reproduce the bug :) maybe some short video or steps to take ...

**Comment by tkowark** [comment]
Unfortunately not. I'll contact the email sender, and if we do not get more information, we'll have to close the issue accordingly.

**Comment by SebastianWolf-SAP** [comment]
We received the video. Please find it attached.

[cwa-app-ios-660.zip](https://github.com/corona-warn-app/cwa-app-ios/files/4800799/cwa-app-ios-660.zip)

**Comment by gkgg** [comment]
I ran into the same or at least a similar problem a couple of days ago. At the moment, I am not able to force/reproduce the behaviour.
On my device (running iOS 13.5.1), the issue appeared (once, so far) after re-activating the WLAN, which I had turned off for the night using the switch in the Preferences section.
The device is not managed remotely (no MDM), and I am not using a tool that interacts with the network connection on a default basis.

**Comment by databus23** [comment]
Not sure if its the same issue but I had multiple times (> 5) where the iOS app would show "No internet connection" and nothing but force quitting the app could make the warning go away. For what its worth this is happening on a SAP issued phone (with MDM). This happens without specific user interaction (e.g. disabling WiFi). This seemingly just happens at random, I found no way to reproduce it.

**Comment by apuehl** [comment]
Corona-Warn-App 1.0.6 (0)
iOS 13.5.1
iphone 6s 
"Build" : "17F80"
Hatte heute (12.07.2020) die gleiche Fehlermeldung "Keine Internetverbindung" auf dem Home screen und damit war auch keine Risiko-Ermittlung mehr möglich. Durch kurzfristiges aus- und einschalten der Risiko-Ermittlung konnte die Fehlermeldung beseitigt und eine Kontaktüberprüfung durchgeführt werden.
Bei Durchsicht des  Kontaktprotokolls musste ich aber feststellen, dass aktuell nur 7 Datensätze übertragen bzw. geprüft wurden  statt der 14 Datensätze aus den letzten Tagen. Ist das ein Fehler? Warum werden jetzt 7 Datensätze nicht mehr berücksichtigt?
[ExposureChecks-2020-07-12.txt](https://github.com/corona-warn-app/cwa-app-ios/files/4908949/ExposureChecks-2020-07-12.txt)

**Comment by sin-azucar** [comment]
> Bei Durchsicht des Kontaktprotokolls musste ich aber feststellen, dass aktuell nur 7 Datensätze übertragen bzw. geprüft wurden statt der 14 Datensätze aus den letzten Tagen. Ist das ein Fehler? Warum werden jetzt 7 Datensätze nicht mehr berücksichtigt?

See #880, this is a bug that was fixed yesterday, but the fix seems to be still pending review from Apple.

**Comment by gkgg** [comment]
[update] I just had that very issue after syncing the iPhone (iOS 13.6) with my Mac (macOS 10.15.6).

The app (v1.0.7) indicated that there would be no internet connection, even though WLAN (as well as mobile data) was activated.

Quitting and restarting the app didn't change anything. Switching Airplane Mode on and off is a workaround (sort of).

**Comment by tkowark** [comment]
As written in https://github.com/corona-warn-app/cwa-app-ios/issues/942#issuecomment-663411355 , the internet connectivity display will be overhauled in future versions. Hence, this issue will be then no longer present but a dedicated warning shall be displayed in cases the app really needs the connectivity and it is in fact not there.

**Comment by gkgg** [comment]
Thanks for that hint, @tkowark … but may I ask if there is still some sort of investigation underway?
The reason why I am asking: I am under the impression (without any proof at hand, sadly) that changes in the connectivity type itself as well as "quality" of the service (i.e. G3 vs. EDGE) might be involved with some interesting of the app. (I am referring to cases like background task not downloading anything etc.)

**Comment by tkowark** [comment]
@gkgg we need to separate two things here. 

Since the "No Internet connection" display will be gone soon, there will not be much time spent on investigating which connection changes might trigger a wrong warning.

On the other hand, we will of course check any issues that affect the downloading of diagnosis keys or test results both when triggered within the app and as part of the background task.

**Comment by UGatgithub** [comment]
14 days ago the message was the display will be **gone soon** but it still confuses users ... When will this update be available?

> Since the "No Internet connection" display will be **gone soon**, there will not be much time spent on investigating which connection changes might trigger a wrong warning.

It is also not only connection changes triggering wrong warnings, I had it last night directly after the daily exposure check ... (https://github.com/corona-warn-app/cwa-app-ios/issues/942)

**Comment by USR123456** [comment]
I also had this issue today. It seems that in my Wifi there is no Internet connection possible. If I deactivate Wifi and launch the app over Mobile Data everything works. As soon as Wifi is reactivated the warning appears again. Very strange behaviour!

**Comment by databus23** [comment]
I think the problem today is that https://svc90.main.px.t-online.de is not reachable:
```
> curl -v https://svc90.main.px.t-online.de                                                                                                                                                                                                                                                         exit: 130
*   Trying 87.140.209.57...
* TCP_NODELAY set
* Connection failed
* connect to 87.140.209.57 port 443 failed: Operation timed out
```

**Comment by GPclips** [comment]
This issue has been completed (Reselase 1.3) and will be closed now.
