### ISSUE TITLE
Risk weights not assigned

### ISSUE THREAD

**Issue by ay-kay** [corona-warn-app/cwa-app-ios#665]
cwa-server provides various risk weights:

https://github.com/corona-warn-app/cwa-server/blob/eb8be6c3e9c723c62c619784e41889d10054cc93/services/distribution/src/main/resources/master-config/exposure-config.yaml#L11-L16

However, the weight values seem currently not to be used within the `ENExposureConfiguration`. Is this intended?

**Comment by awein** [comment]
Adding the weights to [HTTPClient.swift](https://github.com/corona-warn-app/cwa-app-ios/blob/45e9acca70beeef6161eab6b3ff38eea044a6c35/src/xcode/ENA/ENA/Source/Client/HTTP%20Client/HTTPClient.swift#L453-L456) should fix this

```
attenuationLevelValues = riskscoreParameters.attenuation.asArray
attenuationWeight = riskscoreParameters.attenuationWeight
daysSinceLastExposureLevelValues = riskscoreParameters.daysSinceLastExposure.asArray
daysSinceLastExposureWeight = riskscoreParameters.daysWeight
durationLevelValues = riskscoreParameters.duration.asArray
durationWeight = riskscoreParameters.durationWeight
transmissionRiskLevelValues = riskscoreParameters.transmission.asArray
transmissionRiskWeight = `riskscoreParameters.transmissionWeight
```

**Comment by haosap** [comment]
Hi @ay-kay @awein ,
Thanks for reviewing our code. 
In fact, Apple has dropped the weights for calculating the value.
Please see the apple doc:
https://developer.apple.com/documentation/exposurenotification/enexposureconfiguration
Thanks.
