### ISSUE TITLE
TAN input not possible

### ISSUE THREAD

**Issue by trispo** [corona-warn-app/cwa-app-ios#667]
I wanted to insert the TAN of my (negative) Corona test but found that I cannot enter the TAN I was given as it begins with a leading 0. The format of my TAN seems to be correct. 

![image](https://user-images.githubusercontent.com/1045441/84830565-dd3afe00-b029-11ea-83c9-bffa0ea00ce3.png)

Why am I not able to enter this TAN?

**Comment by jhilgert** [comment]
Numbers 0 and 1 are not part of the character set used for TANs. It should be the uppercase letter O instead.

**Comment by trispo** [comment]
With a O it doesn’t work, too.

**Comment by thomasaugsten** [comment]
This TAN input allows only TANs by the Corona-Warn-App Verification hotline. 
TANs from a corona test are not working and there is no need to enter a negative test.

**Comment by trispo** [comment]
Ah, I see. Thanks
