### ISSUE TITLE
Exposure log not being checked

### ISSUE THREAD

**Issue by esskar** [corona-warn-app/cwa-app-ios#675]
## Describe the bug

It looks like that the exposure log is not being checked at all

![image](https://user-images.githubusercontent.com/65206/84886278-7e5e9e80-b094-11ea-90bb-9c648542bd04.jpeg)

## Expected behaviour

Exposure log is checked at least once

## Technical details

- iOS 13.5.1

## Additional context

App is installed 24+ hours

**Comment by thomasaugsten** [comment]
At the moment there are no submitted diagnoses keys available to check it again your collected random IDs. It will take a few days for the first diagnoses keys.
