### ISSUE TITLE
FAQ redirecting to german homepage when app uses English version.

### ISSUE THREAD

**Issue by heberbrandao** [corona-warn-app/cwa-app-ios#683]
## Describe the bug

Currently using an iOS in English. Whenever I click the FAQ section, I am redirected to the german version of the page.

## Expected behaviour

If I am using the english version, I should be redirected to the english website of the Bundesregierung.

## Steps to reproduce the issue

1. Set the iPhone language to English
2. Open Corona-Warn-App
3. Click on FAQ

## Technical details

- Host Machine OS (Windows/Linux/Mac):

**Comment by tens0rfl0w** [comment]
Already fixed in #644 

Will be included in the next update.
