### ISSUE TITLE
Risk tracing labeled as active despite Bluetooth turned off

### ISSUE THREAD

**Issue by TonioS** [corona-warn-app/cwa-app-ios#684]
## Describe the bug

Dear all, 

the application does not indicate the Bluetooth is not working. It continues showing "Risiko-Ermittlung aktiv" despite Bluetooth turned off. 

## Expected behaviour
The app should indicate that the Bluetooth is turned off. 

## Technical details

- Host Machine OS (Windows/Linux/Mac): iOS 13.5.1.

**Comment by haosap** [comment]
Hi @TonioS ,
How did you turn on/off the bluetooth? Did you do it via the control center?

**Comment by MakrisNk** [comment]
Keep in mind that when turning bluetooth off via control center, you don't actually turn off the connection but rather disconnecting bluetooth devices. Also figured this out recently.

**Comment by TonioS** [comment]
> 
> 
> Keep in mind that when turning bluetooth off via control center, you don't actually turn off the connection but rather disconnecting bluetooth devices. Also figured this out recently.

Wow. Sorry about that, my bad (not a fan of iOS to be honest). Thanks for the great support and amazing response rate!

**Comment by TonioS** [comment]
> 
> 
> Hi @TonioS ,
> How did you turn on/off the bluetooth? Did you do it via the control center?

My bad - sorry Hao! Closing the issue.
