### ISSUE TITLE
Add changelog as .md file

### ISSUE THREAD

**Issue by alqu** [corona-warn-app/cwa-app-ios#691]
## Current Implementation

There is no `CHANGELOG.md` or `HISTORY.md` file in this repo.

## Suggested Enhancement
Add a file in order to make it easier to follow all changes. This is especially useful after you start to use git-tags for releases.

There are some best-practices out there. Either you update the changelog manually as outlined [here](https://keepachangelog.com/en/1.0.0/) or you automagically create the changelog somewhere in your build chain, e.g. with https://github.com/github-tools/github-release-notes.

I know that there is a page for that [here](https://github.com/corona-warn-app/cwa-app-ios/releases), but it is not exactly what I am referring to.

## Expected Benefits
A proper documentation of what was changed in which release would benefit all developers who want to have a closer look into this project.
Also, you could use the generated changelog as base for e.g. i18n'ed release notes in the AppStore.

**Comment by inf2381** [comment]
Thanks for the suggestion. We already thought about it and will add it within the next week.

**Comment by alqu** [comment]
Cool, thanks!

**Comment by pzumk** [comment]
Please add the release notes to the app’s changelog on the App Store when updating CWA
