### ISSUE TITLE
it's not available on the Ipads !? why 

### ISSUE THREAD

**Issue by basharbachir** [corona-warn-app/cwa-app-ios#693]
Hi,
i noticed, that the App is not available for the Ipads on AppStore Why is that.
Thanks in Advance

**Comment by tens0rfl0w** [comment]
If I may ask: Why should it be available for iPads? You should carry the device with you on every possible situation you meet other people, typically you don't do that with an iPad. In my opinion the use/cost factor is not really good here.

**Comment by basharbachir** [comment]
I’m carrying my Ipad all the time Max, and there is no reason to don’t let
it available on the Ipads. And i also don’t have a phone for sorry. That’s
why.
Thanks for your reply .

**Comment by inf2381** [comment]
Please have a look at our [FAQ](https://www.coronawarn.app/en/faq/#smartwatch) as this question has already been asked before.

Another thing I would like to bring up is that there should be a collaborative and respectful atmosphere on GitHub. Please keep that in mind in future issues or comments.

**Comment by basharbachir** [comment]
Thanks for your response, may i ask where in my sentences i was not
respectful!
Best regards

**Comment by F3000** [comment]
I know some people which only have an iPad mini instead of a phone .

I think it would be a grid idea to bring it to iPad when the APImis working here
