### ISSUE TITLE
App is reportedly not checking the log of collected IDs

### ISSUE THREAD

**Issue by pxnt** [corona-warn-app/cwa-app-ios#704]
## Describe the bug
When viewing the COVID-19 Exposure Logging Page ( `Settings > Privacy > Health` ), Apple reports that the Corona-Warn App has checked the log of of collected random IDs 0 times over the past 24 hours. 

There’s also no history of exposure checks to be found in the tab below. Meanwhile, inside the app, it reported to already have checked those logs once, 10 hours ago as of posting.

## Expected behaviour
There should be at least one access logged in the settings page, as the app reports to have performed one check.

## Steps to reproduce the issue
Navigate to this page in the Settings app: COVID-19 Exposure Logging ( `Settings > Privacy > Health` )

![E955A4A9-CD44-4A96-A350-E450178DC5B4](https://user-images.githubusercontent.com/19843204/85010372-2f7e3b00-b160-11ea-88fd-30714b3efaf3.jpeg)

Open the 14-day history to confirm

![1F9A0075-4809-4618-ACE6-E0F0FC79AE69](https://user-images.githubusercontent.com/19843204/85010581-871ca680-b160-11ea-827a-c09d4408304b.jpeg)

For comparison, the app reports one check performed:

![FD297E48-D8DA-405A-971F-0CD173A7C317](https://user-images.githubusercontent.com/19843204/85010610-94d22c00-b160-11ea-8e6b-a0b6b4481f01.jpeg)

## Technical details

iOS 13.6 Public Beta, iPhone XR

## Additional context
It’s worth noting that this issue could also be on iOS if it happens to fail the reporting of exposure log checks and the check was in fact performed.

**Comment by pxnt** [comment]
Found duplicate

**Comment by mohe2015** [comment]
Duplicate of https://github.com/corona-warn-app/cwa-app-ios/issues/675 for other people looking for it.
