### ISSUE TITLE
Move all AccessibilityIdentifiers to central file

### ISSUE THREAD

**Issue by melloskitten** [corona-warn-app/cwa-app-ios#707]
As discussed with @i336616, it would be handy if we had all AccessibilityIdentifiers in one place. Currently, most of these are hard-coded.

## Current Implementation
Just an excerpt of how it is handled now, from `ImageTableViewCell.swift`:
![image](https://user-images.githubusercontent.com/15066374/85013433-da90f380-b164-11ea-8ffc-28eca543351a.png)

## Suggested Enhancement
Move the AccessibilityIdentifiers to a central file, similar to `AppStrings.swift`.

**Comment by haosap** [comment]
Hi @melloskitten , Hi @i336616 
My question is, shall we put everything on AppStrings.swift file?
The file is super fat now.
Thanks.

**Comment by melloskitten** [comment]
Hi Hao, 
I meant "similar" to AppStrings.swift - would make a separate file just for the Accessibility Identifiers. Sorry if I didn't explain it correctly

**Comment by haosap** [comment]
> Hi @haosap,
> I meant "similar" to AppStrings.swift - would make a separate file just for the Accessibility Identifiers. Sorry if I didn't explain it correctly

Hi @melloskitten ,
sorry, my bad, oversaw the "similar". :-)
