### ISSUE TITLE
in-app FAQ links to bundesregierung.de, which is broken

### ISSUE THREAD

**Issue by Libavius** [corona-warn-app/cwa-app-ios#712]
The in-app FAQ button "Häufige Fragen" links to [this website](https://www.bundesregierung.de/breg-de/themen/corona-warn-app) hosted by bundesregierung.de
If and only if the language is German, this website is blocked by a survey pop-up (see picture below), which can neither be closed nor be started or rejected on iOS 13.5.1 and iPhone SE 2020.

The German FAQ is thus not accessible.

I know, this is not really app-related (it's website related), but it affects the app and the bundesregierung website is not hosted on github.

Why is the FAQ button not linking to the website https://www.coronawarn.app/de/faq/ which has a github repo and is probably in better hands?

![CoronaUmfrage](https://user-images.githubusercontent.com/35964644/85033972-d4f5d680-b181-11ea-90ab-345cfaecb166.jpeg)

Edit: Corrected iOS version (13.5.1 instead of 13.5) and added phone model
Edit2: Added link to the broken website

**Comment by inf2381** [comment]
Dear @Libavius, thanks for bringing up that issue. However, please understand that the representation in the app stores is the exclusive responsibility of the Federal Press Office. Please reach out to them at their [website](https://www.bundesregierung.de/breg-en/service/contact/contactform).

**Comment by Libavius** [comment]
@inf2381 Thanks, I'll fill out that form.

Yet, this is **not** app store related. The survey appears if I tap the in-app button "Häufige Fragen". Thus any German iOS user searching for the FAQ in the app atm can't view it. I understand, that you can't change anything about it. However I thought, that you might be in contact with the responsible people at bundesregierung.de.
I think, that this issue is quite urgent, since not being able to open and read the FAQ undermines the users trust. =/

**Comment by inf2381** [comment]
@Libavius I totally agree with you and we will of course try to escalate that. But the more people complain the better 😊 .

**Comment by Libavius** [comment]
@inf2381 I agree =).

A last remark: For issues that you can't to anything about, I think its still best to leave them open until they are resolved. (There was a similar issue regarding the age restriction for the iOS app store: #632).
This way:
- people are aware, that you are aware of the issue and don't bring it up again (nobody looks into closed issues for an issue, which is not fixed)
- if - as you say - 'the more people complain the better' this is the way to do it, since people read open issues and complain

In order for you to stop worrying about the issue, you could attach a lable like "not our responsibility"  but not close the issue until it is solved.

So I'd say, its best to reopen this issue and #632.

**Comment by Libavius** [comment]
Update: This issue is resolved, the survey is taken from the website.

**Comment by Libavius** [comment]
For me, the survey pop-up is gone for good. Can this be confirmed by anyone else?

**Comment by tens0rfl0w** [comment]
`Fixed`👍🏽

**Comment by Libavius** [comment]
Alors, I close this issue for now =)
