### ISSUE TITLE
App kann nicht in der iOS Familienfreigabe installiert werden.

### ISSUE THREAD

**Issue by staude** [corona-warn-app/cwa-app-ios#716]
die App ist als +17 im Appstore eingepflegt. Damit kann das Kind die App nicht installieren, es gibt auch keine Möglichkeit die Erlaubnis beim Erziehungsberechtigten einzufordern.

**Comment by Libavius** [comment]
related to #632, #677, and #690

**Comment by melloskitten** [comment]
Hi! 
Thank you for submitting this issue. As I personally don't have access to iOS-family sharing, I would like to ask you, whether this 'workaround' that fellow community member @jdslab proposed, works for you?
> The way I understand it is: iOS age restrictions are set on device, and installation of 17+ apps can be explicitly allowed in iOS Settings in _Screen Time -> Content & Privacy Restrictions -> Content Restrictions -> Apps_. This can also be done temporarily, just for downloading this single app. Could be at least a workaround.

Thanks a bunch 👍

**Comment by staude** [comment]
Yes this works for me with the temporary exception. Thanks for the hint

**Comment by melloskitten** [comment]
Thank you very much for confirming. 
I believe we are not able to change the requirements in regards of required age for the app, but I will definitely run this by our higher ups. I hope we can at least add this information to the FAQ, so that the information can be found easier than having to scan github comments for a solution. Thanks for your time & help! 😊👍

**Comment by christofheurung** [comment]
Hallo, bei meiner Tochter (12) stellt sich das Problem wie folgt dar. Durch die temporäre Erhöhung der Altersfreigabe lässt sich die App installieren, sobald ich die Altersfreigabe aber wieder reduziere ist die App nicht mehr sichtbar und funktioniert aus meiner Sicht dann auch nicht mehr. Zumindest kommt auch Wochen nach der Installation nach wie vor die Meldung dass keine Aussage möglich ist da die APp nicht lange genug aktiv ist. Gibt es zu dem hier geschilderten Sachverhalt eine andere Lösung? 
Evtl. eine Corona-Warn-App-Kids für iOS-Geräte bei der die Installation möglich ist, sobald ein Elternteil die Freigabe dafür gegeben hat? Ich bin kein Entwickler bringe mich aber gerne konzeptionell in eine Diskussion ein.

**Comment by rgattung** [comment]
As of iOS 14 the work around no longer works - the app can be downloaded if the age settings are temporarily removed, but once the age rating is enforced again, the app vanishes from the home screen. Therefore it can no longer be accessed to check wether or not a risk encounter took place.

This leaves parents with the choice of
  a) disabling child protection setting on iOS completely and using the CWA or
  b) not using the CWA for their kids
