### ISSUE TITLE
Support on non-iPhone iOS >= 13.5 devices

### ISSUE THREAD

**Issue by DanielS08663** [corona-warn-app/cwa-app-ios#720]
Technically cwa should work on all devices running iOS >= 13.5 and supporting BLE. 
This includes iPads and some iPod touch models. I know this is an uncommon use case, 
but if it's just ticking additional checkboxes in the AppStore, this might be a feasible thing to do.

**Comment by max-hzi** [comment]
This should be forwarded to Apple, as they provide the API/ technology behind the app.

**Comment by inf2381** [comment]
Please use the issue template. First info there was to have a look at the FAQ
> ## Avoid duplicates
> * [ ] Question is not already answered in the [FAQ](https://www.coronawarn.app/en/faq/)

This question has already been answered there.

**Comment by SergeyPodgornyy** [comment]
@inf2381 If you will not use the **new** notification API, then you can support older iOS version, what is more important. 🤦‍♂️
