### ISSUE TITLE
Contact Tracing Protocol seems not to get checked ever

### ISSUE THREAD

**Issue by stahlfabrik** [corona-warn-app/cwa-app-ios#721]
Hello,

looking at "Einstellung"/"Datenschutz"/"Health"/"COVID-19-Kontakprotokoll" there is a counter that states that the app was doing zero (0) checks in the last 24 hours. It has been like this ever since I installed the app Tuesday morning.

![IMG_1420](https://user-images.githubusercontent.com/4614972/85111076-2058c500-b214-11ea-8f1f-37d992dcfe2d.png)

The app on the other hand states that it checks every 24 hours and suggested it did actually so.

![IMG_1421](https://user-images.githubusercontent.com/4614972/85111121-3070a480-b214-11ea-9a74-7ddedfb9d5f6.png)

So do I have a false understanding of how it should work? Are the Corona-Warn servers not actually up and running and serving yet? Is there a bug in Apple's framework or in the App itself?

I posted this as a question, well because I can only ask for enlightenment. Thank you!

Best regards!

**Comment by stahlfabrik** [comment]
I forgot to mention: On my wife's phone, which is the most recent phone, the situation is the same.

**Comment by n-thumann** [comment]
As there are haven´t been any diagnosis keys submitted, there aren´t any to check :)
See https://github.com/corona-warn-app/cwa-app-ios/issues/671#issuecomment-645942587 & https://github.com/corona-warn-app/cwa-app-ios/issues/675

**Comment by msdvMarcus** [comment]
I just wanted to post the same issue. Had already everythin ready. But have the red the informations
from IOS regarding this feature twice. When there is risk that you have been affected then the apps asks yout to give the IDs free and then contact protcol is accessed. As long as you are not expected to be infected only the random keys are exchanged with server. May be the documentation for the end user and also the achitecture documentation can be actualized to reflect this more better as we have several issues regarding this.

**Comment by tkowark** [comment]
Thanks for all your comments. This is a similar question to #675 and corona-warn-app/cwa-documentation#311 and as stated, the reason is just that there are no diagnosis keys to check against. We'll add that to the FAQs in the near future

**Comment by stahlfabrik** [comment]
Thanks for the super quick replies.

So I understand the reason but I do not understand Apple's choice to show 0 there. I mean "no news is good news". But when it DOES check there are no news, it should +1 that counter. So as the developers of the app you might choose to file a radar at apple.

Will that counter suddenly show 1 (exactly and constantly 1) when the framework receives the first "infected" IDs? (My assumption is 1 exactly because the App says it is checking once in 24h)?

**Comment by msdvMarcus** [comment]
@stahlfabrik: No, the detailed help of the Contact Protocol feature in IOS explains: the diagnosis keys
related to phones are exchanged with an infrastrcture. E.g. the app exchanges the diagnosis keys related to the phones with the RKI servers. The RKI servers check the diagnosis keys against the data of diagnosis keys in the infected people database, when a key is found the app is informed about this and requests from you that you share the IDs of your phone with RKI database to inform the people that they might be infected via the app. When the app has requested to share ids and you committed, then you in IOS "Datenschutz, Health..." x access to the contact tracing protocol.
As this protocol is reset every 14 days and the app is check the infection every day you can have as maxium 14 access to the contact tracing protocol - assuming that you meet every day new people which might be infected and the app is requesting everday that you share the IDs and you allow it every day.

**Comment by n-thumann** [comment]
@msdvMarcus I´m not quite sure, if this is correct 🤔
The diagnosis keys are not shared with the RKI as long as you aren´t tested positive and agreed sharing your diagnosis keys. The app regularly downloads any "positive keys" from the server and passes them to the Exposure Notification Framework (by Apple and Google) to check for any matches. If a key matches (and fulfills the other criteria, e.g. duration, distance, etc.) the app will let you know that you have a higher risk. If you are then tested positive, you can upload your keys for other users to check, if they had captured your keys.
@stahlfabrik I agree with you! According to [Apples Documentation](https://developer.apple.com/documentation/exposurenotification/enmanager/3586331-detectexposures#discussion) this is the "number of diagnostic key checks", so in the case of this app, one every 24 hours (if data is available soon) 👍

**Comment by stahlfabrik** [comment]
Thank you both!

I will read the docs from Apple. Or at least skim over them. Meanwhile I watch the other issue that shall be closed after the FAQ gets updated to explain this issue

**Comment by MikeJayDee** [comment]
Since diagnostic keys are being made available now by the server, this issue should soon be "solved" in that it should show most of the time that the IDs have been checked once in the last 24 hours.
