### ISSUE TITLE
Risiko-Ermittlung nicht möglich

### ISSUE THREAD

**Issue by matsches59** [corona-warn-app/cwa-app-ios#722]
Hello,

Iphone 8 IOS 13.5.1. After the installation of Corana-Warn-App I got (in a grey box) the message:
Risiko-Ermittlung nicht möglich.
One day later I got - in a green box - Risiko-Ermittlung gering.
All fine so far.
One day later (having updated from IOS 13.5 to IOS 13.5.1 I consistently have again - in a grey box - the message: Risiko-Ermittlung nicht möglich. According to the message the last "Risiko-Ermittlung was the time when the app was installed. Of course the "Risiko-Ermittlung" is active all the time.
Looks like "Risiko-Ermittlung got stuck". 
Kind regards

**Comment by Libavius** [comment]
Maybe check [this answer](https://github.com/corona-warn-app/cwa-app-ios/issues/630#issuecomment-645264063)

**Comment by matsches59** [comment]
Hello,
I do not get an error when starting the app.
After the installation I got the  message
„Region für Kontaktmitteilungen geändert“ that seems to be related to a bug Apples's ExposureNotification-Framework and from my perspective that can be ignored.
Deleting the exposure log and reinstalling the app would probably delete the contacts collected so far?

**Comment by jlnprssnr** [comment]
"Region für Kontaktmitteilungen geändert" --> #645

**Comment by jnmng** [comment]
Same here: iPhone 11 Pro, after updating to iOS 13.5.1

![IMG_0553](https://user-images.githubusercontent.com/30359578/85203595-25e70580-b30f-11ea-80d7-0dc82d9ea6d5.jpg)

**Comment by httpdop** [comment]
Problem starts today iPhone Xs/iOS 13.5.1 without iOS Update.

**Comment by matsches59** [comment]
Hello,
issue could be solved in the morning by simply tapping on the "Aktualisiert" text in the grey box. All at the sudden the box turned into green and text turned into "Niedriges Risiko. Looks fine at the moment.
Kind regards

**Comment by JoachimSeuling** [comment]
Risikoermittlung läuft nur scheinbar und meldet grün, das Kontaktprotokoll ist aber leer und meldet „Corona-Warn“ hat dein Protokoll mit erfassten IDs während der letzten 24 Stunden 0-mal überprüft. Das sieht so aus, als ob gar keine IDs aufgezeichnet werden, denen ich begegne - ich war 1. während der 6 Tage, die die App aktiv ist unterwegs unter Menschen und 2. hat meine Frau die App ebenfalls installiert, deren ID sollte auf jeden Fall als Kontakt gespeichert sein

**Comment by matsches59** [comment]
in der Tat, sieht bei mir genauso aus, danke.

**Comment by matsches59** [comment]
laut https://www.coronawarn.app/de/faq/
heisst das aber wohl nicht dass die kKontaktaufzeichnung nicht funktioniert:

Apple: In den Einstellungen für das COVID-19-Kontaktprotokoll steht: 'Corona-Warn hat dein Protokoll mit erfassten zufälligen IDs während der letzten 24 Stunden 0-mal überprüft'. Funktioniert die Risiko-Ermittlung nicht?
Doch, die Risiko-Ermittlung funktioniert. Dieser Hinweis unter 'Einstellungen' > 'Datenschutz' > 'Health' > 'COVID-19-Kontaktprotokoll' stammt von iOS und bedeutet, dass der Backend-Server noch keine Diagnoseschlüssel (Positivkennungen) an Dein Gerät versendet hat und die Corona-Warn-App damit auch noch keinen Abgleich mit den auf Deinem Gerät gesammelten Zufallscodes durchführen konnte. Sobald Corona-positiv getestete Personen ihren Diagnoseschlüssel (Positivkennung) hochgeladen haben, wird dieser Abgleich ausgelöst.

**Comment by haosap** [comment]
Duplicate #741

**Comment by JoachimSeuling** [comment]
no duplicate, andere Aspekt

**Comment by matsches59** [comment]
After another 2 days had again this screen:

![IMG_1576](https://user-images.githubusercontent.com/67143356/85516969-144b7980-b5ff-11ea-8bbf-5206bdc5ebc9.PNG)

Then I tapped again on the "Aktualisiert" text field and got this screen:

![IMG_1578](https://user-images.githubusercontent.com/67143356/85517158-4957cc00-b5ff-11ea-9549-70c7906f0f95.PNG)

When tapping the "Aktualisieren" button the app is running into an error:

![image](https://user-images.githubusercontent.com/67143356/85517723-d26f0300-b5ff-11ea-83a3-8189bc1fc95e.png)

The app is definitely not working properly. Any hint on that error?

**Comment by matsches59** [comment]
Just like #759

**Comment by haosap** [comment]
Hi,
Copied directly from the header file of EN Framework.
```swift
 ENErrorCodeInternal = 11, /// Internal error. This indicates a bug in this framework. 
```
It seems an issue of the framework.

**Comment by matsches59** [comment]
Restart however fixed the problem. Leaving the issue open since it looks that the automatic update does not work properly.

**Comment by itechdaniel** [comment]
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/67371822/85548409-33f29a00-b61f-11ea-88a1-2d643fbac859.png)
Ich habe die App auf meinem iPhone (iOS 13.5.1) installiert und alle Fragen auch brav mit "erlauben" beantwortet.
Aber in den Einstellungen muss zusätzlich noch angegeben werden, welche App für die Covid-Protokollierung benutzt wird. Ohne diese Einstellung nachträglich händisch vorzunehmen, dürfte die App völlig nutzlos sein.
Wenn die App diese Einstellung nicht bei der Installtion vornehmen kann, sollte ein deutlicher Hinweis in der App erfolgen, was man noch zu tun hat.
Ganz schlecht ist, dass die App sich so verhält (zumindest war das bei mir so), als ob Alles OK wäre und ich halt keinen kritischen Kontakt hatte.

**Comment by jonasreiher** [comment]
This is probably related to #784.
However, no error message is thrown there.
Enabling Background App Refresh (Hintergrundaktualisierungen) fixed it for me (see [here](https://github.com/corona-warn-app/cwa-app-ios/issues/784#issuecomment-655002658)).

**Comment by matsches59** [comment]
Was a little bit confused that the background actualization did not work as expected. It was highlighted green in "Einstellungen -> Corona-Warn" but the button was not active (could not be switched). This was caused by contrary settings in "Einstellungen -> Allgemein -> Hintergrundaktualisierung". Had to activate the background actualization for the app there too. In the meantime the app is running more or less smoothly now. Had to restart the phone once to overcome the "ENErrorCodeInternal = 11" issue. Since this seems to be related to a bug in the Apple framework I have to wait for that fix. 
But for now the issue is solved.
