### ISSUE TITLE
Show Statistics

### ISSUE THREAD

**Issue by ststoessel** [corona-warn-app/cwa-app-ios#723]
It would be highly interesting to have a dashboard with statistics included!

How many contacts you had during a day:
Total / per Hour
Number of Cell Phones with Bluetooth
Number of Cell Phones with Corona-Warn-App

And also a view that shows how many contacts you had within a special duration (histogram):
<1m
<5m
<10m
<15m
>15m

**Comment by inf2381** [comment]
Added your request to the related issue #678
