### ISSUE TITLE
Corona-Warn-App for Apple-Watch

### ISSUE THREAD

**Issue by ststoessel** [corona-warn-app/cwa-app-ios#724]
Please consider an additional Corona-Warn-App for the Apple-Watch.

**Comment by inf2381** [comment]
Please use the issue template. First info there is to have a look at the FAQ
> ## Avoid duplicates
> * [ ] Question is not already answered in the [FAQ](https://www.coronawarn.app/en/faq/)

This question has already been answered there.

**Comment by tkowark** [comment]
While this is a duplicate here, we think that it could be a viable addition in the future. Thus, we'll move this issue to the wishlist repository and let users discuss how this could work, which other secondary devices might be interesting, etc.
