### ISSUE TITLE
App only available in German App Store

### ISSUE THREAD

**Issue by manudar** [corona-warn-app/cwa-app-ios#727]
Hi, there are many people living in Germany with phones tied to non German App Store and the app is only available in the German App Store.
I have send emails to the German department handling this, I have called to the Corona-Warn-App hotline and I reached no solution.
I know that this is not a code problem I don't know what else to do.
Please make the app available on other iOS App stores.!

**Comment by inf2381** [comment]
Please use the issue template. First info there is to have a look at the FAQ
> ## Avoid duplicates
> * [ ] Question is not already answered in the [FAQ](https://www.coronawarn.app/en/faq/)

This question has already been answered there and it's a pinned issue
