### ISSUE TITLE
Coronawarn

### ISSUE THREAD

**Issue by thoraxinum** [corona-warn-app/cwa-app-ios#73]

**Comment by haosap** [comment]
Hi @thoraxinum ,
If you don't have any input here, the issue will be closed tomorrow.
Thanks.

**Comment by tkowark** [comment]
@thoraxinum this is the third issue you create without any content. Please consider this a warning in accordance with our [Code of Conduct](https://github.com/corona-warn-app/cwa-app-ios/blob/development/CODE_OF_CONDUCT.md). If you continue to spam our repositories with empty issues, we will have to temporarily ban your account from contributing.
