### ISSUE TITLE
Getting some error notiification message again and again

### ISSUE THREAD

**Issue by saha-anik** [corona-warn-app/cwa-app-ios#730]
## Describe the bug

**Everyday I am getting same error message again and again.**
 
![image](https://user-images.githubusercontent.com/8160649/85159758-33908280-b25e-11ea-9baf-86228752ec33.png)

**My region is Germany. I have only one corona based application installed in my mobile.**

![image](https://user-images.githubusercontent.com/8160649/85160030-9eda5480-b25e-11ea-922c-2c626b999a79.png)

**Comment by tens0rfl0w** [comment]
Duplicate of #645
