### ISSUE TITLE
ExposureDetection_Explanation_Subtitle_Active/Inactive Flipped?

### ISSUE THREAD

**Issue by MichaelPFrey** [corona-warn-app/cwa-app-ios#734]
## Avoid duplicates

* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is not already reported in another issue

## Describe the bug

I think the active and Inactive Strings are "flipped". Under iOS,

- _active_ uses the verb *was calculated*
and
- _inactive_ uses the verb *is calculated*.

https://github.com/corona-warn-app/cwa-app-ios/blob/5bb223ba341f388ba1e3a1371ce065605e1e79a8/src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings#L82-L84

https://github.com/corona-warn-app/cwa-app-ios/blob/5bb223ba341f388ba1e3a1371ce065605e1e79a8/src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings#L82-L84

*Outdated* uses _inactive_ meaning the *is calculated* phrasing.

https://github.com/corona-warn-app/cwa-app-ios/blob/5bb223ba341f388ba1e3a1371ce065605e1e79a8/src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewController%2BDynamicTableViewModel.swift#L313-L332

should that not be *was calculated*?

where as the android version uses the *was calculated* phrasing for *risk_past*

https://github.com/corona-warn-app/cwa-app-android/blob/ddb1f94f1d577f08863ae319c195d80cacf0bc3e/Corona-Warn-App/src/main/res/values-en/strings.xml#L295-L297

Something seams/feels off here.

I would not simply switch the two phrasings, as that would become an issues with *unknownRiskModel*, as this is correctly _inactive_ resulting in correctly *is calculated*.

https://github.com/corona-warn-app/cwa-app-ios/blob/5bb223ba341f388ba1e3a1371ce065605e1e79a8/src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewController%2BDynamicTableViewModel.swift#L334-L338

## Expected behaviour

Consistency between iOS and android version

## Steps to reproduce the issue

see above

## Technical details

- iOS Version: independent, see source code above
- Device: independent, see source code above

## Additional context

---
Internal Tracking ID: EXPOSUREAPP-1957

**Comment by MichaelPFrey** [comment]
Digging into the code to give you the hooks to look into all uses/cross references:

https://github.com/corona-warn-app/cwa-app-ios/blob/5bb223ba341f388ba1e3a1371ce065605e1e79a8/src/xcode/ENA/ENA/Source/View%20Helpers/AppStrings.swift#L231

https://github.com/corona-warn-app/cwa-app-ios/blob/5bb223ba341f388ba1e3a1371ce065605e1e79a8/src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewController%2BDynamicTableViewModel.swift#L287

https://github.com/corona-warn-app/cwa-app-ios/blob/5bb223ba341f388ba1e3a1371ce065605e1e79a8/src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewController%2BDynamicTableViewModel.swift#L307

https://github.com/corona-warn-app/cwa-app-ios/blob/5bb223ba341f388ba1e3a1371ce065605e1e79a8/src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewController%2BDynamicTableViewModel.swift#L326

https://github.com/corona-warn-app/cwa-app-ios/blob/5bb223ba341f388ba1e3a1371ce065605e1e79a8/src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewController%2BDynamicTableViewModel.swift#L342

https://github.com/corona-warn-app/cwa-app-ios/blob/5bb223ba341f388ba1e3a1371ce065605e1e79a8/src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewController%2BDynamicTableViewModel.swift#L360

https://github.com/corona-warn-app/cwa-app-ios/blob/5bb223ba341f388ba1e3a1371ce065605e1e79a8/src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewController%2BDynamicTableViewModel.swift#L392

**Comment by dsarkar** [comment]
Hi @MichaelPFrey,

these 
https://github.com/corona-warn-app/cwa-app-ios/blob/5bb223ba341f388ba1e3a1371ce065605e1e79a8/src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings#L82-L84
https://github.com/corona-warn-app/cwa-app-ios/blob/5bb223ba341f388ba1e3a1371ce065605e1e79a8/src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings#L82-L84

have been changed to 
https://github.com/corona-warn-app/cwa-app-ios/blob/ac22075fb1aeeae40c37035c5da185426429676f/src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings#L106
https://github.com/corona-warn-app/cwa-app-ios/blob/ac22075fb1aeeae40c37035c5da185426429676f/src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings#L106

We suggest closing this issue therefore. Many thanks for your contributions ! Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by MichaelPFrey** [comment]
Thank you very much.
Feel free to close - this issue in its current form is outdated.
