### ISSUE TITLE
iPhone 6s, iOS updated to newest version. No SIM. Not possible to activate tracking. Why?

### ISSUE THREAD

**Issue by jwildeboer** [corona-warn-app/cwa-app-ios#735]
## Describe the Bug

iPhone 6s, iOS updated to newest version. No SIM. Not possible to activate tracking

## Expected behaviour

Tracking activation should work without SIM. 

## Steps to reproduce the issue

Install app.
Try to activate tracking. 
Doesn’t work. 

## Technical details

iPhone 6s, iOS 13.5.x

## Possible Fix

Make activation work without sim. ![image](https://user-images.githubusercontent.com/873028/85208471-1bd5fe80-b331-11ea-93cf-31fa2f82b552.png)

**Comment by jwildeboer** [comment]
![Uploading 85208488...]()

**Comment by jwildeboer** [comment]
![Uploading 85208495...]()

**Comment by jwildeboer** [comment]
I inserted my SIM card in the other phone and could activate tracking.

**Comment by KevinMuessig** [comment]
Dear @jwildeboer ,

This is probably related to a bug in Apple's Exposure Notification Framework. It has been addressed and will probably be fixed soon. In the meantime, please use this workaround:

      •     In Settings > Privacy > Health > COVID-19 Exposure Notifications, press "Delete exposure log" (if possible)

        •     Delete the App

        •     Reboot your smartphone after updating to iOS 13.5

        •     Insert a valid SIM card (whether physical SIM or eSIM)

        •     Switch off flight mode and activate Bluetooth

        •     Install the app and do not reject the dialogs

Please try out that workaround and close the issue if it worked.
Thank you,
KM

**Comment by jwildeboer** [comment]
We used the workaround and it worked without reboot.
