### ISSUE TITLE
Switch to a new iPhone

### ISSUE THREAD

**Issue by s-englert** [corona-warn-app/cwa-app-ios#736]
I've switched to a new iPhone and had the App installed on the old one. If you choose sync Data via Bluetooth to the new iPhone, the Coronawarn-App is there. But you can't enable Risk-Detection.

You can start the App, enable Risk-Detection via Selector. Go Back and you get „Risk-Detection not enabled“.

The only way is to delete the App and Reinstall to enable Risk-Detection. But all Data is lost from  the old iPhone.

I think that's essential, if someone switching the Device.

Hope this helps.

Switch from iPhone7 to iPhone11 - same iOS Version.

**Comment by tkowark** [comment]
Unfortunately, this is currently not supported by neither Google nor Apple. We are tracking this as an idea in the wishlist repository (corona-warn-app/cwa-wishlist#8), but as stated there, this will not be implementable by the Corona-Warn-App but needs to become part of the Exposure Notification Framework.
