### ISSUE TITLE
Not enough memory notification

### ISSUE THREAD

**Issue by janberlin** [corona-warn-app/cwa-app-ios#737]
## Avoid duplicates

* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is not already reported in another issue

## Describe the bug

Notification of low memory. the Device has 40GB free. RAM?
![EC7F6782-A7D3-4694-A24F-D81F3230DDA3](https://user-images.githubusercontent.com/8312244/85212210-d3c6d400-b350-11ea-817a-f895ffbec973.jpeg)

## Expected behaviour

No notification. 

## Technical details

- iOS Version: 13.5.1
- Device: iPhone XR

**Comment by carmenb80** [comment]
This happened to me as well. This notification was the first thing my iPhone displayed yesterday in the morning. The battery usage of Covid-19-Tracking was at 60% after that night.
Today it was back to normal saying 4% in the morning.

**Comment by odyvankinoby** [comment]
Same issue on my iPhone XR 64GB, enough memory available. Also first notification in the morning after 6 hrs on charger. Message never showed up again.

![DC4A286F-1B3B-46BB-A43E-1F287FC5B905](https://user-images.githubusercontent.com/50707149/85231591-d4b34080-b3f8-11ea-9cda-6a30e5115094.jpeg)
![69CB9924-0075-4EA5-812A-23337EBF063D](https://user-images.githubusercontent.com/50707149/85231594-d7ae3100-b3f8-11ea-9b50-51575721cd03.jpeg)

**Comment by thomasaugsten** [comment]
This is a bug by Apple will be fixed in the next iOS. The Corona-Warn-App functionality is not affected. It is only a wrong error like the region alert.
