### ISSUE TITLE
Remove `private` annotations to make HomeViewController and HomeInteractor testable

### ISSUE THREAD

**Issue by dasdom** [corona-warn-app/cwa-app-ios#738]
## Avoid duplicates

* [x] This issue has not already been raised before
* [x] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation

Most properties in `HomeViewController` and `HomeInteractor` are declared as `private` as this is good practice to hide internal implementation from other classes.

## Suggested Enhancement

I suggest to change most properties to `internal` to make `HomeViewController` and `HomeInteractor` testable. Only `internal` properties and methods can be altered and checked from a test target. To set up a `HomeViewController` with test data, we need access to `homeInteractor` from the test.

## Expected Benefits

`HomeViewController` and `HomeInteractor` become testable via Unit Tests. This means we could write a unit test for selecting a cell in `HomeViewController` and asserting that the expected action (for example showing another screen) happens.

---
Internal Tracking ID: EXPOSUREAPP-1956

**Comment by ChristianKienle** [comment]
HomeViewController + Interactor are currently re-implemented to address exactly those issues. #717

**Comment by marcussc** [comment]
Interactor got removed in 1.11, therefore closing this issue.
