### ISSUE TITLE
Can we see, how many people are using the CoronaWarnApp in our Location?

### ISSUE THREAD

**Issue by capsload2** [corona-warn-app/cwa-app-ios#742]
## Avoid duplicates
* [x ] Question is not already answered in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x ] Question has not already been asked in another issue

## Your Question

* Source File:
* Line(s):
* Question: Hey! Is there any possible way to see or know, how many users in a radius of X km are using the app in our city?

Hallo - ist es irgendwie möglich zu Erfahren, wie viele Nutzer CoronaWarnApp in der Stadt oder im Umkreis / Landkreis nutzen?

Gruß

**Comment by haosap** [comment]
Hi @capsload2 ,
Due to the data privacy, we don't use any location service in our app. Therefore, it's not possible to see how many people are using the app. 
Thanks.

**Comment by capsload2** [comment]
Maybe it would be possible to make a optional opt-in setting for that.
