### ISSUE TITLE
Not enough memory for contact protocol

### ISSUE THREAD

**Issue by GismoNo1** [corona-warn-app/cwa-app-ios#748]
## Avoid duplicates

* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is not already reported in another issue

## Describe the bug

Today I got an error that there is not enough memory for the contact protocol. It's the 6th day I'm using the app on an iPhone 11 pro with 30GB free memory.

## Technical details

- iOS Version: iOS 13.5.1
- Device: iPhone 11 pro

**Comment by ChristianKienle** [comment]
Thank you very much for reporting this issue. Was this error reported by the app itself or was this an error generated by the OS? (if you know)

Just for clarification: Are you talking about random access memory or disk space? It seems like you have received a disk space warning. Could you confirm that by looking at your usage settings in system preferences?

**Comment by haosap** [comment]
Hi @GismoNo1 ,
I think your issue might be also mentioned at:
https://github.com/corona-warn-app/cwa-app-ios/issues/645#issuecomment-644876375
Thanks.

**Comment by GismoNo1** [comment]
> Thank you very much for reporting this issue. Was this error reported by the app itself or was this an error generated by the OS? (if you know)
> 
> Just for clarification: Are you talking about random access memory or disk space? It seems like you have received a disk space warning. Could you confirm that by looking at your usage settings in system preferences?

Thanks for the fast reply! Since the error was reported in form of a two-button alert, I think it came from the app itself and not from the OS. Sadly, I have no screenshot because it was the device of my girlfriend. We will provide a screenshot if the error occurs again.

**Comment by GismoNo1** [comment]
> Hi @GismoNo1 ,
> I think your issue might be also mentioned at:
> [#645 (comment)](https://github.com/corona-warn-app/cwa-app-ios/issues/645#issuecomment-644876375)
> Thanks.

It's not the OS-based "region changed" error, but might be associated with it. We got the "region changed" error a couple of times before and this one definitively looked different.

**Comment by haosap** [comment]
Hi @GismoNo1 ,
Thanks for your bug report. If you got the error again, please post the screenshot here.
The "storage" insufficient bug we also encountered it before. I think it should be from OS level instead of the App.

**Comment by FSpitzer** [comment]
The bug is from the OS and should be fixed with the next iOS update according to the last paragraph in this article: [heise.de](https://www.heise.de/news/Corona-Warn-App-iPhone-Nutzer-angeblich-ueberrepraesentiert-4791616.html)

**Comment by GismoNo1** [comment]
> The bug is from the OS and should be fixed with the next iOS update according to the last paragraph in this article: [heise.de](https://www.heise.de/news/Corona-Warn-App-iPhone-Nutzer-angeblich-ueberrepraesentiert-4791616.html)

Good to know. So we'll see if it's patched by Apple with the next updates. Thanks to the community and the developers. Keep on the good work!

**Comment by daimpi** [comment]
This bug seems still not to be fixed on iOS. I just had [someone on twitter](https://twitter.com/connor_larkin/status/1280478329620004864) with this problem. Maybe the information from the heise article should be added to the iOS FAQ page. The information there is currently not saying anything about an iOS bug: https://www.coronawarn.app/de/faq/#memory
