### ISSUE TITLE
App doesn't work with iOS 14 beta

### ISSUE THREAD

**Issue by Jan10** [corona-warn-app/cwa-app-ios#749]
## Avoid duplicates

* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is not already reported in another issue

## Describe the bug
The app does not load with the latest beta version of iOS 14.

## Steps to reproduce the issue

Nothing happens when you open the app.

Screenshot:
![IMG_2595](https://user-images.githubusercontent.com/192557/85335462-57153080-b4dd-11ea-8808-cbeb4805221d.PNG)

## Technical details

- iOS Version: 14.0
- Device: iPhone 11

**Comment by Tobitobsen81** [comment]
![94310A4E-E6CF-4638-B23B-25FBBF1C45A1](https://user-images.githubusercontent.com/29689172/85337722-4070d880-b4e1-11ea-9912-d4c8860ddd34.png)
Additional information to this issue: If you reinstall the app you will get this failure message and the app will not work on ios 14 iphone 11

**Comment by silviokennecke** [comment]
Experiencing the same issue on my iPhone XS

**Comment by maxleonalbrecht** [comment]
Same Issue on the XR

**Comment by Nils-ber** [comment]
I think it might be an iOS 14 issue.
Additional screenshots.
![WhatsApp Image 2020-06-23 at 00 13 48 (1)](https://user-images.githubusercontent.com/67294938/85340495-7f555d00-b4e6-11ea-8681-64f27fc189c3.jpeg)
![WhatsApp Image 2020-06-23 at 00 13 48](https://user-images.githubusercontent.com/67294938/85340497-7fedf380-b4e6-11ea-86b8-7da3a43f2efd.jpeg)
Device:
iPhone Xs
iOS 14

**Comment by KizzyCode** [comment]
See also https://developer.apple.com/documentation/ios-ipados-release-notes/ios-ipados-14-beta-release-notes/: "ExposureNotification isn’t currently available in iOS 14 beta. Use iOS 13.6 beta to preview the latest functionality. (64433241)"

**Comment by F3000** [comment]
Seen on iPhone 11 Pro too

**Comment by PaxonicYT** [comment]
same on my 6s

**Comment by haosap** [comment]
Dear colleagues,
I think @KizzyCode already mentioned that, the ExposureNotification isn't currently available in iOS 14 beta. See:
 https://developer.apple.com/documentation/ios-ipados-release-notes/ios-ipados-14-beta-release-notes

If you want to use the ExposureNotification, please switch to 13.5 or 13.6 at the moment.
Thank you for your support.

**Comment by GranitGjevukaj** [comment]
Same on my iPhone 11 Pro Max.

**Comment by tkowark** [comment]
We now added this question to the [FAQ](https://www.coronawarn.app/en/faq/#ios_14_beta) and since the developers cannot do anything against these circumstances, we'll close the issue accordingly.

**Comment by Heavy02011** [comment]
Do I get it right? We knew the app does not work under ios 14 beta and closed the issue because we can not do anything? And now after updating to ios 14 I‘m having the same issue: the app does not work anymore....

**Comment by Heavy02011** [comment]
The symptoms decribed above are exactly what I experienced after updating to ios 13.6, see https://github.com/corona-warn-app/cwa-app-ios/issues/911
Just closing an issue just because „the developers can’t do anything against the circumstances“ is not an option in a pandemic.
The App ist NOT working anymore, even after a complete reinstall.

**Comment by tkowark** [comment]
They are not exactly the same symptoms. iOS 14 *BETA* currently just does not include the exposure notification framework (see FAQ). Thus, the app cannot work on iOS 14 until that framework is available. 

That is different from any potential problems with the iOS 13.6 *Release* version, which we of course are looking into.

**Comment by tens0rfl0w** [comment]
### **UPDATE:**
The Exposure Notification framework is now available with the release of the iOS 14 Developer Beta **4**.

**Comment by RalphRichter** [comment]
Latest Beta Developer release on iOS is now supporting exposure notifications [Beta Release Notes](https://developer.apple.com/documentation/ios-ipados-release-notes/ios-ipados-14-beta-release-notes )

**ExposureNotification**
Resolved in iOS & iPadOS 14 beta 4
ExposureNotification is now available. (64433241)

![IMG_154EB6FE8496-1](https://user-images.githubusercontent.com/67153468/89332454-b72df380-d693-11ea-8b78-045089c8fe0f.jpeg)

**Comment by stefandesu** [comment]
I understand that official support will only come with the public release of iOS 14, but can I ask if there is anything in the app that's currently not working in iOS 14?

**Comment by tens0rfl0w** [comment]
@stefandesu Up to now I couldn't find any issue with the app running on iOS 14. First exposure check after 24 hours was successful with 14 delivered data sets. Couldn't trigger any app crash/bug thats exclusive for iOS 14 up to now.

So, without valid testing, for me it works fine.
