### ISSUE TITLE
won´t open on ios 14

### ISSUE THREAD

**Issue by Pikotaro** [corona-warn-app/cwa-app-ios#756]
## Describe the bug
App won´t start, stays white after the splash screen

## Steps to reproduce the issue
just try to open the app

## Technical details
- iOS Version: 14
- Device: 6S-8

**Comment by n-thumann** [comment]
Duplicate of https://github.com/corona-warn-app/cwa-app-ios/issues/749 😊

**Comment by Pikotaro** [comment]
sorry
