### ISSUE TITLE
Onboarding sequence 3rd step - discontinuing flow by "Do not activate" button

### ISSUE THREAD

**Issue by CrazyNexus** [corona-warn-app/cwa-app-ios#76]
In the Onbording views the user will see a short overview about the function of the app. Step 1 and step 2 have only one button "Let's go" or "Continue"on the bottom. But step 3 (How to enable risk detection) has 2 buttons ("Continue" and "Do not activate"). Unfortunately the "Do not activate" button is on the place where the "Continue" button was in the past views. IMHO that will lead to disabled risk detection by mistake. The same thing happens in step 5 (Receive warnings, know the risk").

The users are lazy and do not want to move their finger. They capture the message and intuitively just keep typing. 
With the current arrangement of the buttons they deactivate the capture of random IDs because they expect the "Continue" button at this point. 

<img width="881" alt="Bildschirmfoto 2020-05-31 um 23 25 32" src="https://user-images.githubusercontent.com/2306075/83363034-6699d180-a396-11ea-816e-26875502950a.png">

It would be better if these two buttons were swapped and the "Do not activate" button is above the "Continue" button, which is again at the same position as in the two previous views.
This is in my opinion a better user experience and leads to less involuntary "deactivations".

Steps to reproduce:
1) start the app first time (or remove the existing from your device/simulator)
2) read first and second onboarding view
3) see risk detection screen and your finger is over the "Do not activate" button

Give me a hint when I should fix it.

**Comment by CrazyNexus** [comment]
same thing in step 5 of the onboarding

**Comment by CrazyNexus** [comment]
Sorry, it's late today.

**Comment by pke** [comment]
Maybe such onboarding screens are boring and no sane user reads them anyway (there are studies about that). 
Maybe as a conclusion it could be better to have exactly one screen with 2 buttons?

**Comment by ChristianKienle** [comment]
Thank you very much for creating this issue. @CrazyNexus your point makes sense. I will run this by our UX/UI colleagues and ask for their view on this.

**Comment by SebastianWolf-SAP** [comment]
Dear colleagues,

in the meanwhile we got feedback from our UX/UI team and they want to say thank you for this input! It will be part of one of the next usability tests. Results are expected somewhen around end June/beginning of July. We will keep this issue open and "on hold" until then and get back to you with the feedback!

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by tkowark** [comment]
After reviewing, the UX team decided to stick with the original design. As a separate dialog is also in place in case "Do not Activate" is pressed that warns about the consequences, even less attentive users should not really disable this accidentally. 

Thank you very much for input!
