### ISSUE TITLE
change wording Mundschutz to Mund-Nasen-Schutz

### ISSUE THREAD

**Issue by seb-1204** [corona-warn-app/cwa-app-ios#762]
## Avoid duplicates

* [X ] This issue has not already been raised before
* [ ] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation

word used: Mundschutz
## Suggested Enhancement

use word:  Mund-Nasen-Schutz
## Expected Benefits

it is important to cover both mouth and nose with the mask (any kind of mask), the working suggest the latter.

**Comment by seb-1204** [comment]
Pull request
https://github.com/corona-warn-app/cwa-app-ios/pull/761

**Comment by inf2381** [comment]
See PR
