### ISSUE TITLE
Exposure sync/Check delayed every day by 1 hour

### ISSUE THREAD

**Issue by jwildeboer** [corona-warn-app/cwa-app-ios#763]
## Avoid duplicates

* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is not already reported in another issue

## Describe the bug

The update time (sync time) is 1 hour later every day. After installing the app sync was at 9 in the morning, now it is at 18 in the evening. This means that between publishing of infected keys and sync up to 20 hours have passed in my case. No manual sync possible. This delays warnings and should be fixed.

## Expected behaviour

Update/sync should happen at least at the same time every day, maybe even more than once. 

## Steps to reproduce the issue

1. Install app
2. Note time of update after 24 hours
3. Check again a few days later
4. Note it gets delayed around an hour every day

After install, update at 9:20

![image](https://user-images.githubusercontent.com/873028/85521870-2cbe9280-b605-11ea-9a93-3212a77365b8.png)

A week later, update at 18:20

![image](https://user-images.githubusercontent.com/873028/85521957-4eb81500-b605-11ea-85b1-581690af6150.jpeg)

## Technical details

- iOS Version: 13.5.1
- Device: iPhone 11, MWM32ZD/A

## Possible Fix

Make sure Update time drifts max 1-2 hours.

**Comment by jwildeboer** [comment]
So AFAICS the first set of keys has been published last night. I will not get them before this evening. I don't know how long the check itself will take, but I definitely will not get a warning before 24 hours have passed after publication o the keys.

This means that I can earliest act tomorrow, so more or less 48 hours later. That is IMHO a lot of time passing. Shouldn't the goal be to enable fast reactions to possible contacts?

**Comment by muellermartin** [comment]
This issue is related to #740

**Comment by jwildeboer** [comment]
As you can clearly see, the checks drift between 20-60 minutes every day. So the official statement of a check “every 24 hours” is not working for me. It’s definitely more than 24 hours every day.

I really hope this will be fixed. 

![image](https://user-images.githubusercontent.com/873028/86100698-7b62a580-bab9-11ea-8b13-667e86a34c2f.jpeg)

**Comment by jwildeboer** [comment]
And another 50 minutes later. I’ve opened the app many times, so I really don’t understand how I got from 9 innige morning to this late in the evening. ![image](https://user-images.githubusercontent.com/873028/86354226-ebfbf480-bc68-11ea-83a7-51c1eb1e076d.png)

**Comment by jwildeboer** [comment]
Now tracked in #916 so closing this one is fine.
