### ISSUE TITLE
iOS 14 blackscreen 

### ISSUE THREAD

**Issue by JoshuaSokolowski** [corona-warn-app/cwa-app-ios#771]
In iOS 14 the App opens just a blackscreen

**Comment by SebastianWolf-SAP** [comment]
Dear @JoshuaSokolowski,

please see the respective answer in our FAQ for details: https://www.coronawarn.app/en/faq/#ios_14_beta

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
