### ISSUE TITLE
Make App compatible to iOS 14 Beta

### ISSUE THREAD

**Issue by cmoellerffo** [corona-warn-app/cwa-app-ios#772]
## Avoid duplicates

* [ ] This issue has not already been raised before
* [ ] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

**Comment by cmoellerffo** [comment]
App only shows blank screen on latest developer Preview (iOS 14 Beta 1)

**Comment by lucsoft** [comment]
Duplicate beta 1 doesn’t support it

**Comment by tkowark** [comment]
-> FAQ
