### ISSUE TITLE
Not working on iOS 14 Beta 1 -> blank screen

### ISSUE THREAD

**Issue by uzzero** [corona-warn-app/cwa-app-ios#774]
### Describe the bug
The application is not working with the new iOS 14 Beta 1 version.
When starting the application it just shows an blank AppBar and screen.

![IMG_89AF09C9B483-1](https://user-images.githubusercontent.com/2923629/85688270-e3884480-b6d1-11ea-813f-dc51124ba85f.jpeg)

**Comment by tens0rfl0w** [comment]
Duplicate. Please look in the FAQ and close this.

**Comment by uzzero** [comment]
Duplicate. See FAQ. Exposure Notification API not available on iOS 14 Beta 1.
