### ISSUE TITLE
Progress bar full+checkmark with 9 of 14 days

### ISSUE THREAD

**Issue by Bandyt** [corona-warn-app/cwa-app-ios#775]
The risk summary shows "9 of 14 days saved", but the progress bar next to it is full and displays a checkmark. Tapping on it for details shows the progress bar correctly.

PS: Android is working correctly.

**Comment by EisvogelSAP** [comment]
Hey @Bandyt, thanks for your feedback. This has already been fixed with #634 and will be part of the next release. :-)
