### ISSUE TITLE
iOS 14 not launching

### ISSUE THREAD

**Issue by Geriatrix** [corona-warn-app/cwa-app-ios#777]
Since I’ve updated to iOS 14 beta I can’t launch the app anymore.
Splash screen shows for a second then only a black screen.
I can see it accessing my location 
iPhone 11 Pro Max iOS 14.0
![93863B5F-784E-4F9B-9FE7-689CC9A6A16D](https://user-images.githubusercontent.com/67414429/85693808-d9b51000-b6d6-11ea-9c18-26be982f50ca.jpeg)

**Comment by MoonPadUSer** [comment]
Hi I am using iOS 14.0 on an iPhone XR, I experience the same behavior. I assume it has smth to do with permissions, just a wild guess tho

**Comment by Kabulla** [comment]
It is not so much a "black" screen but more of an "empty" screen (depending on your iPhone-setting).

One needs to realize, of course, that iOS 14 is in "early beta status", hence not so much a "bug" in terms of the current version of the CWQ, which is designed for iOS 13!

Having said that, I do concur that this needs to be addressed in the not so far out future (definitely not of any urgency for the moment).

Note:
The core problem is (for the time being) that the documentation of contacts (Apple iOS side) is deactivated for our (Germany) region for the moment (check "COVID-19-Kontaktprotokoll in your settings) from Apple's side.
The App-Developers will not be able to do anything about the problem, until this is "lifted" (probably with the start of the "public-Beta", maybe mid-July).
It is not even unreasonable to guess that this will solve the problem, entirely.

So IF you SERIOUSLY want to run CWA on your phone, please revert back to iOS 14 in the meantime...
![IMG_1976](https://user-images.githubusercontent.com/20712583/85697084-c6577400-b6d9-11ea-957e-11969bb2db3a.jpg)

**Comment by uzzero** [comment]
Please close issue request. 

See #774

**Comment by MoonPadUSer** [comment]
@Kabulla, pls change the last iOS 14 to iOS 13 (in your comment I mean)

**Comment by Kabulla** [comment]
> @Kabulla, pls change the last iOS 14 to iOS 13 (in your comment I mean)

done... "Freud at work"... sorry...

**Comment by tens0rfl0w** [comment]
Please take a look at the FAQ **before** posting a new issue. This issue got poste several times in the last days, and for the devs it can get really annoying seeing the same „issue“ again and again. (On top it is not an issue that can be solved right now, because the EN framework got temporarily disabled in Beta 1)

You can close this issue🙂

**Comment by JulianBerger** [comment]
Can confirm that

**Comment by Geriatrix** [comment]
Apologies! Searched before I posted. Just wanted to let you guys know, not an issue for me, having a developer OS brings it’s flaws...
