### ISSUE TITLE
Restarting the phone and reinstalling the app would not help for error 13, because this key file limit is an iOS setting, and is not reset by restarting the phone or deleting the app. Only a factory reset of the device or iOS software update seem to reset the limit in our tests.

### ISSUE THREAD

**Issue by mf71** [corona-warn-app/cwa-app-ios#781]
Restarting the phone and reinstalling the app would not help for error 13, because this key file limit is an iOS setting, and is not reset by restarting the phone or deleting the app. Only a factory reset of the device or iOS software update seem to reset the limit in our tests.

_Originally posted by @pavshr in https://github.com/corona-warn-app/cwa-app-ios/issues/759#issuecomment-649519513_

Yesterday, I had error 11. Not 13. I documented the error in this thread. See above. Restarting the phone helped and error 11 did not return until now. I did not uninstall. The app shows 'Aktualisiert' by time of the restart now. The 'Region für die Kontaktmitteilung...' message also did not return until now. At least for the moment, problem is solved on my device.

**Comment by pavshr** [comment]
I would guess then that error 11 that you received on your device was not related to error 13.

**Comment by mf71** [comment]
Sorry, wanted to contribute to another issue. This entry can be deleted

**Comment by tocotronaut** [comment]
What about resetting Ad-ID? Would that help?

in My German Phone Einstellungen -> Datenschutz -> Werbung -> Reset Ad-ID

In english should be Preferences -> Privacy -> _Ads_ -> Reset Ad ID.
