### ISSUE TITLE
exposure log contains only entries for three days, two of them the same day

### ISSUE THREAD

**Issue by dkl23** [corona-warn-app/cwa-app-ios#782]
## Avoid duplicates

* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is not already reported in another issue

## Describe the bug

When looking up the exposure log  it shows me three data entries. Two of them show the date of today and the same number of received IDs.

## Expected behaviour

The menu item states 'This is a record of all requests to check your Exposure Log from the past 14 days.' and since I had CWA active for 9 days now, I expected at least 8 or 9 entries.
Additionally two of those entries have the same date and also the same number of received IDs.
(JSON export attached below)

## Steps to reproduce the issue
Go to iOS settings: Privacy->Healthy->COVID-19 Exposure Logging->Exposure Checks"

![screenshot](https://user-images.githubusercontent.com/1855503/85749917-c9159180-b6f8-11ea-9a7a-532d93665b3f.png)

## Technical details

- iOS Version: 13.5.1
- Device: iPhone SE (the first one)

## Additional context
My data as json export (same as the data shown in the settings menu itself):
{
  "Build" : "17F80",
  "ExportVersion" : 1,
  "ExposureChecks" : [
    {
      "Hash" : "F5430B4B125B23E7D714C49745DD90BEBF53CB3A697EE940322B69FE24D43EC2",
      "RandomIDCount" : 503,
      "MatchCount" : 0,
      "DataSource" : "de.rki.coronawarnapp",
      "Timestamp" : "2020-06-24 11:58:00 +0200"
    },
    {
      "Hash" : "F5430B4B125B23E7D714C49745DD90BEBF53CB3A697EE940322B69FE24D43EC2",
      "RandomIDCount" : 503,
      "MatchCount" : 0,
      "DataSource" : "de.rki.coronawarnapp",
      "Timestamp" : "2020-06-25 13:59:58 +0200"
    },
    {
      "Hash" : "FC612A4E62DDA3B5931849E56A397D126320E94CDAEA6282F6AD06897C9F09E3",
      "RandomIDCount" : 720,
      "MatchCount" : 0,
      "DataSource" : "de.rki.coronawarnapp",
      "Timestamp" : "2020-06-25 13:59:58 +0200"
    }
  ],
  "DeviceProductType" : "iPhone8,4"
}

**Comment by tkowark** [comment]
That‘s not a bug. Diagnosis keys are only distributed since yesterday and the log you mention shows the attempts of the app to let the Exposure Notification Framework check for potential risky contacts based on downloaded keys. So, the first entry is for the first downloaded package yesterday, the other two for the ones downloaded today. We‘ll make that clearer in the FAQ.

**Comment by inf2381** [comment]
Also answered in #778

**Comment by tkowark** [comment]
And now part of the FAQ: https://www.coronawarn.app/en/faq/#multiple_exposure_checks

**Comment by dkl23** [comment]
Thanks for the amazingly fast resolution. The FAQ is helpful.
