### ISSUE TITLE
iOS 14 beta App cannot activate "Risiko Ermittlung"

### ISSUE THREAD

**Issue by Jensap** [corona-warn-app/cwa-app-ios#788]
- iOS Version: 14 beta
- Device: iPhone X

Cannot activate "Risiko ermittlung"

Error: unknown("Der Vorgang konnte nicht abgeschlossen werden. (ENErrorDomain-Fehler 3).)")

![IMG_2C642478DF22-1](https://user-images.githubusercontent.com/46930251/85848189-06d1f300-b7a9-11ea-9987-100d3791681f.jpeg)

**Comment by tkowark** [comment]
-> [FAQ](https://www.coronawarn.app/de/faq/#ios_14_beta)
