### ISSUE TITLE
[API] Double check of data set

### ISSUE THREAD

**Issue by tens0rfl0w** [corona-warn-app/cwa-app-ios#790]
## Avoid duplicates

* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is not already reported in another issue

## Describe the bug
**Note:** This is not the same issue that was mentioned before.

As today marks the third day after the first data set was published, today the framework should have been accessed 3 times (=3 data sets). But today it was accessed 6 times, so every data set was checked 2 times.

This is more just an information than a bug report, because I can't give any further input.

![image](https://user-images.githubusercontent.com/57523343/85872380-ef5a3080-b7cf-11ea-8421-a3143b42c37e.png)

This alert was sent some hours before without any action before:
![image](https://user-images.githubusercontent.com/57523343/85872421-01d46a00-b7d0-11ea-8afe-900675492266.png)

**Comment by arnegns** [comment]
Hi, I have the same issue.
![AA320A90-1F1A-4930-BF38-6E59C87E0E21](https://user-images.githubusercontent.com/12628806/85918425-fd0cc600-b862-11ea-9398-8d1f13a5025e.png)
![AFD34241-43C1-4D90-80FC-F9DEDD5AEB5B](https://user-images.githubusercontent.com/12628806/85918427-00a04d00-b863-11ea-891d-a330d3211194.png)

**Comment by tens0rfl0w** [comment]
Hey @arnegns,
This does not look like you have the same issue. 3 checks yesterday are completely normal.

**Comment by arnegns** [comment]
Okay then I don’t understand this. Why there are 3 checks with the same time? Three api calls? For each day a api call?

**Comment by tens0rfl0w** [comment]
For every data set on check. So 3 days=3 data sets, and this means =3 API calls for the third day.

**Comment by arnegns** [comment]
Allright. Thank you :)

**Comment by mss1010** [comment]
Can someone explain, why every day the exposure keys of all (14) previous days have to be downloaded again?
Can´t they just be saved on the device? Or is this also part of data privacy?

**Comment by inf2381** [comment]
> Can someone explain, why every day the exposure keys of all (14) previous days have to be downloaded again?
> Can´t they just be saved on the device? Or is this also part of data privacy?

They are only downloaded once and stored in a local database. For each day, we have two files: one .bin file which contains the keys and one .sig file that contains the signature of our server. Every 24 hours, we download the latest day, fetch all relevant files from the local db and then feed them into the framework. That's what you see in the system settings: All files that have been provided for a detection session. The API function is documented [here](https://developer.apple.com/documentation/exposurenotification/enmanager/3586331-detectexposures).

**Comment by nlorke** [comment]
I’m also experiencing this issue. 

iPhone XR iOS 13.5.1
App Version 1.0.4

I also get an alert that exposure notifications may not be available in my region at least once a day. I’ll try to remember to take note of the time when it occurs next, and will look for or open an issue.

![1B0DD815-29DF-406A-A057-5B17B945A7CB](https://user-images.githubusercontent.com/23309894/86532282-08966780-bec9-11ea-98de-eeb3e77260d2.png)

**Comment by tkowark** [comment]
Since we could neither recreate nor experience this problem again, we'll close this issue. If the problem occurs again, please open a new, dedicated issue for that.
