### ISSUE TITLE
Number of provided keys not readable if using slighty higher font size

### ISSUE THREAD

**Issue by holgergp** [corona-warn-app/cwa-app-ios#791]
## Avoid duplicates

* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is not already reported in another issue

## Describe the bug
Not sure if this is provided by the cwa-app itself. 
In the contact review section the number of provided keys is not visible if using a slighty higher font size. Three dots are displayed instead.

## Expected behaviour
Number of provided keys is readable. Maybe an abbreviation of the label ('number of provided keys') is used instead of the full label text.

## Steps to reproduce the issue
![defaultFontSize](https://user-images.githubusercontent.com/253009/85898340-61486f00-b7fc-11ea-80ab-dafc06b59f91.jpg)
![slightlyHigherFontsize](https://user-images.githubusercontent.com/253009/85898343-63aac900-b7fc-11ea-925d-22365b69a344.jpg)

## Technical details

- iOS Version: 13.5.1
- Device: iPhone 11 Pro

**Comment by n-thumann** [comment]
Yes, you´re right: This view isn´t provided by CWA but by Apple and therefore only fixable by them ✌️

**Comment by holgergp** [comment]
Thanks! Should we close this then? Is there a way to report this to Apple? Do you as CWA team have some better link to Apple?

**Comment by holgergp** [comment]
I submitted it here: https://www.apple.com/feedback/iphone.html Not sure if this is the "correct" way.

**Comment by inf2381** [comment]
Thank you for bringing this up! You could also file a radar. Have a look [here](https://developer.apple.com/bug-reporting/).

**Comment by dideldei** [comment]
As a workaround feel free to choose a smaller font.

**Comment by holgergp** [comment]
@dideldei not sure if trolling. That's what I did learn about the issue in the first place.
