### ISSUE TITLE
Number of active days is misleading

### ISSUE THREAD

**Issue by christianbrb** [corona-warn-app/cwa-app-ios#794]
## Avoid duplicates

* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is not already reported in another issue

## Describe the bug

I have installed the App ~10 days ago. After running into issue #766 I have deinstalled and installed the app. According to @thomasaugsten the contact protocol is stored in the OS. If this is the case the number of active days (“x von 14 Tagen aktiv”) in the app is misleading for me.

## Expected behaviour
- x should be the number days the tracking function of the OS contains data and has been active.
## Steps to reproduce the issue

1. Install App
2. Use it 10 days
3. Deinstall
4. Install
## Technical details

- iOS Version:
- Device:

**Comment by thomasaugsten** [comment]
The issue is only the OS knows the number of keys in the contact protocol and when they are collected. We can only show how many days the app is active. When the app is uninstalled also this day count of the app is deleted.

**Comment by christianbrb** [comment]
@thomasaugsten Thanks for your response :)

Is there a way how to access that data? At least on an aggregated level?

**Comment by inf2381** [comment]
You can tell the date from the key's rolling start period. But there are two issues:
* To access the own keys, the user has to grant permission (The system will prompt an alert to ask whether the user wants to share the keys)
* If you deactivate the contract tracing protocol 10am for instance, a key may already be generated although the app hasn't been active the whole day
