### ISSUE TITLE
cwa not working under iOS 14 beta

### ISSUE THREAD

**Issue by Mezmerized** [corona-warn-app/cwa-app-ios#797]
## Avoid duplicates

* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is not already reported in another issue

## Technical details

- iOS Version:
- Device:

**Comment by tkowark** [comment]
-> [FAQ](https://www.coronawarn.app/de/faq/#ios_14_beta)
