### ISSUE TITLE
Corona-Warn-App Spanish translation

### ISSUE THREAD

**Issue by adrianapintod** [corona-warn-app/cwa-app-ios#801]
## Avoid duplicates

* [x] This issue has not already been raised before
* [ ] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation

No Spanish language support. 

## Suggested Enhancement

Translate the Corona-Warn-App into Spanish language.

## Expected Benefits

Spanish community will be able to leverage the application enabling the app to reach a bigger audience in Germany.

**Comment by adrianapintod** [comment]
I'm already working on this translation. I would like to later send the PR with the issue resolution.

**Comment by tkowark** [comment]
Dear @adrianapintod , thank you for your offer. As noted in corona-warn-app/cwa-documentation#350 translations are done by a dedicated team in close collaboration with the RKI. Hence, we cannot accept community translations at this point.
