### ISSUE TITLE
Tracking could not be activated after data transfer to new iPhone

### ISSUE THREAD

**Issue by stritti** [corona-warn-app/cwa-app-ios#802]
## Describe the bug

I received today a new iPhone 11 and started data transfer via direct WiFi from my current iPhone 8.
The App was transfered correctly and showed the traced days as before on the old iPhone (may be this is the problem?). 
The tracking was disabled and I tried to enable it again and the switch changed to "on". But on reopen the app it was disabled again. I had to delete the App and reinstall it. Maybe the transfered data from the previous iPhone does not match correct, because now i start again on day 0.

## Expected behaviour

The tracking status could be enabled without reinstall.

## Steps to reproduce the issue

Hm somehow difficult: You have to transfere your iPhone data to a new iPhone by the Apple assistant.

## Technical details

- iOS Version: 13.5.1
- Device: iPhone 8 -> iPhone 11

## Possible Fix

Maybe the stored data could be marked as "not to transfer"? Or they should be resetted if new device is found.

**Comment by tkowark** [comment]
thanks for reporting. We're tracking this issue already in #754
