### ISSUE TITLE
History got lost after 14 days

### ISSUE THREAD

**Issue by KarstenSchiller** [corona-warn-app/cwa-app-ios#805]
Hello, this morning I reached the level of 14 days using the corona warn app on iPhone.
I was surprised that I saw the risk state "Unbekanntes Risiko". The app indicates, that I am not using the app long enough to receive a risk state.

Yesterday evening I shortly deactivated the "Risiko-Ermittlung". Maybe this has an impact.

Regards
Karsten Schiller

**Comment by haosap** [comment]
Hi @karstenschiller ,
Thanks for reporting this bug. Could you please tell us more detail, for example:
1. How long did you disable the "Risiko-Ermittlung"?
2. Do you disable it in the app or in the system setting?
Thanks.

**Comment by karstenschiller** [comment]
Hi, to switch of "Risiko-Ermittlung" I used the switch within the app. I went back to the main screen. There I saw the status, that "Risiko-Ermittlung" was inactive. After that I activated it again within the app. So the deactivation phase was <=1 min.

Some hours later I still saw on the main screen that the app was collecting data 13/14 days but the last update/sync ("Aktualisiert") was before the point in time, when I deactivated "Risiko-Ermittlung"

Most likely the loss of historical data appeared after the 14 day level was reached.

**Comment by haosap** [comment]
> Hi, to switch of "Risiko-Ermittlung" I used the switch within the app. I went back to the main screen. There I saw the status, that "Risiko-Ermittlung" was inactive. After that I activated it again within the app. So the deactivation phase was <=1 min.
> 
> Some hours later I still saw on the main screen that the app was collecting data 13/14 days but the last update/sync ("Aktualisiert") was before the point in time, when I deactivated "Risiko-Ermittlung"
> 
> Most likely the loss of historical data appeared after the 14 day level was reached.

Hi @karstenschiller ,
Thanks very much. cc @inf2381

**Comment by Debilski** [comment]
Hi, same problem here and I have not deactivated anything yesterday. Counter just went down to 0.

![CB59BFF0-DD45-494D-918D-FF5B224D388F](https://user-images.githubusercontent.com/216179/86126768-276ab780-badf-11ea-862c-2e5cfcedabf2.png)

**Comment by ChristianKienle** [comment]
Bug fixed - tests written - PR opened (#807 – still in draft to iron out the rough edges).

**Comment by jwildeboer** [comment]
Same here. Counter is back to 0 days, I had not deactivated tracking. Question: what is the impact? Will checks still work? Does this have an impact on the reliability of the app?

**Comment by cbs** [comment]
Similar problem here. Today my counter went from 14/14 days down to 9/14 days. Tracking switch was on the whole time. I just opened the app again after a few hours.

**Comment by KarstenSchiller** [comment]
The same problem also happens on android devices.

**Comment by haosap** [comment]
> The same problem also happens on android devices.

Hi @KarstenSchiller ,
Thanks again for your test on Android. Could you please share more information for our Android devs?
cc @jakobmoellersap @harambasicluka

**Comment by KarstenSchiller** [comment]
It is not a 100% problem:
On the smartphone of my wife we see the grey risk status on the main screen only for around 1s after starting the app. After that, I see 14/14 days in green.

On a Samsung tablet I see in grey "Unbekanntes Risiko" (not sure since when). The app was installed on June 16th. I did not open the app between ~June 20th and today. 
On this device I meanwhile received an error message (Ursache: 2) which indicates a lack of memory. The details show an exception "NotEnoughSpaceOnDive" and some more problems. I'll delete some apps and test again.

**Comment by KarstenSchiller** [comment]
After deleting some other apps "corona warn" seems to work fine: "13 von 14 Tagen aktiv" / "Aktualisiert: Heute, 20.15".
I'll send an update tomorrow evening in case of a problem after 14 days.

**Comment by odyvankinoby** [comment]
Same here, history reset after 14 days, did not touch app or settings (iOS 13.5.1, iPhone XR)

![6604FB08-D5CB-420F-96FF-DF6FE8315DC6](https://user-images.githubusercontent.com/50707149/86163655-dd9ac500-bb10-11ea-921d-0c38ad17f84d.png)

**Comment by pzumk** [comment]
Mine went from 14/14 and “Niedriges Risiko” to 10/14 (“Niedriges Risiko), last updated 18:44 as expected. 

My wife’s app went from 9/14 (“Niedriges Risiko) to 0/14 and had to tap through the introduction of the app again which is now showing “Risiko unbekannt”.

Neither of us changed any settings but I know she’s had airplane mode activated last night.

**Comment by jwildeboer** [comment]
Observation: on my private iPhone, everything still works. Shows 14/14 days, check was done half an hour ago. 

On my work iPhone I get the „not enough data“ error and 0/14 days since the check ran today. 

Main difference: I open the app at least once daily on my private phone, but not every day on my work phone. Maybe that’s part of the reason why it fails. I guess the app does some „stuff“ when you open it and that should be done daily. If there’s too nicht time between the app being run, this happens. It’s just a guess, though.

**Comment by Baeda73** [comment]
I didn’t switch off anything. Yesterday it was 13/14 and today it dropped to 7/14 with no reason... or I just don’t understand the reason...

**Comment by pheraph** [comment]
Didn’t switch off anything, too, and am down to 4 days, but installed on day one and had reached 14th day today. How can I help you with this issue?
![8F8E06F4-1D28-4DC6-8C00-534E4D97F00C](https://user-images.githubusercontent.com/58503/86176875-f2358800-bb25-11ea-9d30-76d6dbf1fbe6.jpeg)

**Comment by NoFr1ends** [comment]
Having the same issue. Never deactivated anything.
Did the app pruned the history or is it just a visual bug?

**Comment by diveflo** [comment]
> Observation: on my private iPhone, everything still works. Shows 14/14 days, check was done half an hour ago. 
> 
> On my work iPhone I get the „not enough data“ error and 0/14 days since the check ran today. 
> 
> Main difference: I open the app at least once daily on my private phone, but not every day on my work phone. Maybe that’s part of the reason why it fails. I guess the app does some „stuff“ when you open it and that should be done daily. If there’s too nicht time between the app being run, this happens. It’s just a guess, though. 

At least for me, that‘s not the issue.
Installed day one and I opened the app at least once a day. Still now down to 7/14.

**Comment by AnKaRo** [comment]
Same problem here (iPhone7/ Softwareversion 13.5.1)
After showing me „14 von 14 Tagen aktiv“ it‘s like that
![8D9DC63A-A1C8-4BB4-9944-BF318A14D75F](https://user-images.githubusercontent.com/67675866/86207544-12d60000-bb6f-11ea-96dc-251345b73f8c.png)
But I can still find the „Kontaktprotokoll“ on my phone:
![3EAF02C4-9705-40D4-ADA7-EAE05B66AB79](https://user-images.githubusercontent.com/67675866/86207678-50d32400-bb6f-11ea-97f7-f9021cd7af8e.png)
![7EDF7B97-CF74-4FED-8829-B77EB7D08AA2](https://user-images.githubusercontent.com/67675866/86207688-53ce1480-bb6f-11ea-86ed-569ac48bdd8b.png)

**Comment by haosap** [comment]
Dear app users,
The hot fix is available at App Store now. Please update your app.
Thank you very much for your support.

**Comment by glueckskastanie** [comment]
Downloaded the update just now, but nothing changed - it still says 7/14 days saved instead of 14. Does that mean my exposure checks from before 24 June have been permanently lost?

**Comment by pheraph** [comment]
The update didn’t bring back my lost days, too.

**Comment by jwildeboer** [comment]
Update installed. Still says 0/14 days. Will this fix itself when the app does its first check?![image](https://user-images.githubusercontent.com/873028/86213790-83364e80-bb7a-11ea-8058-b368c98ff7c3.jpeg) ![image](https://user-images.githubusercontent.com/873028/86213806-8af5f300-bb7a-11ea-9e96-82736a798d3c.jpeg)

**Comment by tkowark** [comment]
Yes, the update is not able to fix counters that jumped back to 7 days (or any other values), but will only prevent that from happening in the future. Your contact events are, however, NOT affected by that, since they are not stored by the app but the exposure notification framework.

**Comment by jwildeboer** [comment]
Ok. So I just have to wait at least 24 hours from now? And hope it’ll do the check sometime? I cannot force it to manually update and I also cannot predict when it will do the check. So for the next 24 hours i will not now about possible risks, correct?

**Comment by glueckskastanie** [comment]
Events saved in the exposure notification framework would be visible in my device’s settings as “exposure checks”, right? Because those only go back to 24 June (7 days) for me, just like the counter in the app - even though I’ve had it installed for 15 days now, which is what sparked my concern about contact events being lost in the first place.

**Comment by jwildeboer** [comment]
> Because those only go back to 24 June (7 days) for me

That is correct. The first „infected“ keys were distributed to the app a week ago. So perfectly normal.

**Comment by glueckskastanie** [comment]
> > Because those only go back to 24 June (7 days) for me
> 
> That is correct. The first „infected“ keys were distributed to the app a week ago. So perfectly normal.

Makes sense, thanks!

**Comment by jwildeboer** [comment]
Update from my side: my app is back to „normal“ though it „lost“ 14 days. But risk calculation seems to work again and I am relieved to see that. 

Thank you to the team for fixing this nasty, but ultimately not severe bug in 24 hours! !![image](https://user-images.githubusercontent.com/873028/86230555-86890480-bb91-11ea-89dc-7e0cc4615eff.jpeg)

**Comment by tkowark** [comment]
Since the bug was fixed with a previous hotfix, we'll close the issue accordingly. If you experience it again with latest app and iOS version, please open a new, dedicated issue for that
