### ISSUE TITLE
Not working under iOS14

### ISSUE THREAD

**Issue by tjonas331** [corona-warn-app/cwa-app-ios#806]
## Avoid duplicates

* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is not already reported in another issue

## Describe the bug

The app won’t open in iOS14

## Technical details

- iOS Version: 14
- Device: iPhone XS

**Comment by inf2381** [comment]
Please look at the FAQ
