### ISSUE TITLE
Status unclear

### ISSUE THREAD

**Issue by benzman81** [corona-warn-app/cwa-app-ios#813]
## Avoid duplicates

* [x ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ x] Bug is not already reported in another issue

## Describe the bug
The status the app is currently showing is unclear.

![2A787DA3-5C9F-4624-BBA3-C320589DE1FC](https://user-images.githubusercontent.com/14224592/86178426-9e786e00-bb28-11ea-8ad9-b8cbc1fcbeca.png)

It tells me, that I habe a low risk although it shows me one risk encounter. I didnt get a notification. So for
now, I dont know what to do with this information. Was there really a risk encounter and the status is shown wrong and notification sending failed, or wasnt there an a risk encounter and everthing is fine? App restart didnt change anything.

## Technical details

- iOS Version: 13.5.1
- Device: iPhone Xs Max

**Comment by tkowark** [comment]
As mentioned in corona-warn-app/cwa-documentation#344 , this will be tracked centrally for both apps.
