### ISSUE TITLE
Misleading display of days saved: "15 of 14 days saved"

### ISSUE THREAD

**Issue by BjoernKW** [corona-warn-app/cwa-app-ios#815]
## Avoid duplicates

* [ X ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ X ] Bug is not already reported in another issue

## Describe the bug

After 15 days of using the app the main status card says "15 of 14 days saved". Moreover, in the "Exposure Logging" view the blue circular status indicator also shows 15/14 says.

## Expected behaviour

I'm not sure about the implemented behaviour right now. Depending on if a.) the last fortnight's data is discarded entirely after that period is up or if b.) only the least recent day's data is discarded (essentially a FIFO queue of days) the correct behaviour - and consequently user feedback - would differ:

In the first case, I'd expect the app to reset to "1 of 14 days saved" after 14 days. In the second case, it should display a 14 days moving window. The latter might be tricky to do design-wise because it'd involve a more complex timeline display. 

## Steps to reproduce the issue

![IMG_1048](https://user-images.githubusercontent.com/125270/86214422-77975780-bb7b-11ea-8347-216837a07041.PNG)
![IMG_1047](https://user-images.githubusercontent.com/125270/86214431-79611b00-bb7b-11ea-9e85-19194e4b7565.PNG)

## Technical details

- iOS Version: 13.5.1
- Device: iPhone XS

**Comment by haosap** [comment]
Hi @BjoernKW,
The hot fix is available at App Store now. Please update your app.
Thank you very much for your support.

**Comment by HrFlorianHoffmann** [comment]
What about the Android app? Same bug? Solution already in progress/available?

**Comment by inf2381** [comment]
> What about the Android app? Same bug? Solution already in progress/available?

Let me check that for you ...
[796](https://github.com/corona-warn-app/cwa-app-android/issues/796)

**Comment by tkowark** [comment]
Since this bug has not resurfaced after the recent updates, we'll close the issue accordingly. If your experience it again with the latest app and iOS version, please open a new, dedicated issue.

Thanks for all your input!
