### ISSUE TITLE
Risikostatus "Niedriges Risko" trotz "1 Risiko-Begegnung"

### ISSUE THREAD

**Issue by cgdd1974** [corona-warn-app/cwa-app-ios#817]
## Avoid duplicates

* [ x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x ] Bug is not already reported in another issue

## Describe the bug

Die IOs App zeigt "Niedriges Risko" bei gleichzeitig "1 Risiko-Begegnung"

## Expected behaviour

Nach der FAQ  https://www.bundesregierung.de/breg-de/themen/corona-warn-app/corona-warn-app-faq-1758392 ist niedriges Risiko, wenn die App keine Risiko Kontakte erkannt hat. Schon wenn eine Riskio-Begegung stattgefunden hat sollte, so verstehe ich die FAQ, ein erhöhtes Risiko ausgewiesen werden.  

> "niedriges Risiko:
> 
> Die Person wird darüber informiert, dass die Risiko-Überprüfung ihrer Begegnungs-Aufzeichnung keine Begegnung mit nachweislich Corona-positiv getesteten Personen ergeben hat oder dass etwaige Begegnungen nicht über dem definierten Schwellenwert lagen.
> 
> Die Person wird über allgemein geltenden Abstandsregelungen und Hygiene-Empfehlungen informiert.
> 
> erhöhtes Risiko:
> 
> Die Person wird darüber informiert, dass die Risiko-Überprüfung ihrer Begegnungs-Aufzeichnung ein erhöhtes Infektionsrisiko ergeben hat, da innerhalb der vergangenen 14 Tage Begegnungen mit mindestens einer Corona-positiv getesteten Person stattgefunden haben."

Die in-App Hilfe beschreibt dabei "Risiko-Begegung" als 

> "Jene Begegnung mit einer Corona-positiv getesteten Person, die über einen längeren Zeitraum und in geringer Distanz stattfanden."

![photo_2020-07-01_10-33-41](https://user-images.githubusercontent.com/25890077/86222318-5be57e80-bb86-11ea-9bb7-b339a960a9c2.jpg)

Ich würde also erwarten, das eine erkannte Risiko Begegnung zu eine Risiko Hochstufung auf "erhöhtes Risiko" führt.

## Steps to reproduce the issue

![photo_2020-07-01_10-21-10](https://user-images.githubusercontent.com/25890077/86221115-c2699d00-bb84-11ea-8202-3e282f7e09fe.jpg)

"Niedriges Risko" trotz "1 Risiko-Begegnung" vor dem heutigen update, welches das 14/15-Tage Problem behoben hat.

![photo_2020-07-01_10-26-00](https://user-images.githubusercontent.com/25890077/86221519-4b80d400-bb85-11ea-8757-7874799772cc.jpg)

Detailansicht nach dem Update (14/14 Tage gefixt).

## Technical details

- iOS Version: 13.5.1
- Device: MQAC2ZD/A (Iphone X)

## Possible Fix

Eventuell lese ich die FAQ auch falsch - dann könnte man die Formulierung ggf. noch deutlicher machen?

**Comment by inf2381** [comment]
Please have a look [here](https://github.com/corona-warn-app/cwa-documentation/issues/344)
