### ISSUE TITLE
Risikoermittlung nicht möglich seit Installation, Zahl aktiver Tage wechselt nach 14 Tagen zu zufälligem Wert

### ISSUE THREAD

**Issue by jangerritha** [corona-warn-app/cwa-app-ios#818]
-App wurde nach Installationsanleitung installiert und hat alle Berechtigungen
-Bluetooth war durchgehend aktiviert
-Das Handy war einmal ausgeschaltet

-Seit Installation kommt die Fehlermeldung: "Risikoermittlung nicht möglich"
--Eine grüne, gelbe oder rote Box mit Risikoprognose wurde nie angezeigt

-Zahl der aktiven Tage hat korrekt hochgezählt und hat am 14. Tag einen (vermutlich) zufälligen Wert eingenommen, in diesem Fall 6/14

-Ein Video befindet sich im Anhang
-Please review, Ich dachte bis das verwirrende  Verhalten des aktive Tage Zählers aufgetreten ist, dass das Verhalten gewünscht ist.
[fehler_corona_app.zip](https://github.com/corona-warn-app/cwa-app-ios/files/4856773/fehler_corona_app.zip)

**Comment by jwildeboer** [comment]
Heute wurde ein Update auf Version 1.0.3 veröffentlicht das dieses Problem beheben sollte. Bitte das Update installieren und ein paar Stunden warten, damit die Risikoberechnung im Hintergrund durchgeführt wird. Danach sollte alles funktionieren. 

Ich hatte ein ähnliches Problem und es wurde mit dem Update heute gelöst.

**Comment by ferdinand** [comment]
Die fehlerhafte Zählung von aktiven Tagen scheint ein Duplikat von #804 zu sein. Es gibt ein Update im App Store, dass dieses Problem beheben sollte.

Dass deine Risikoermittlung nicht möglich ist, scheint ein davon unabhängiges Problem zu sein.

**Comment by haosap** [comment]
Hi @jwildeboer ,
Danke für Ihre Unterstützung. 👍

**Comment by inf2381** [comment]
@jangerritha Was passier bei einer manuellen Überprüfung? Also in den iOS Systemeinstellungen die Hintergrundaktualisierungen für die App ausschalten und dann in der App im Homescreen manuell "Aktualisieren" drücken.

**Comment by jangerritha** [comment]
@inf2381 Auf dem IPhone sind automatische Aktualisierungen aktiviert. Die neue Version wurde im laufe des Vormittags installiert, dies hatte aber keine Auswirkungen, der Fehler blieb bestehen. Ich habe die App entfernt und neu installiert. Nun scheint die Risikoprognose (vorerst) zu funktionieren, bzw. wird "Unbekanntes Risiko" angezeigt. Der Zähler steht auf 0/14. Leider kann Ich den Sachverhalt mit der Hintergrundaktualisierung nun offensichtlich nicht mehr überprüfen. Falls der Fehler erneut auftritt werde Ich dies überprüfen und das Resultat hier mitteilen.

**Comment by below** [comment]
> Heute wurde ein Update auf Version 1.0.3 veröffentlicht das dieses Problem beheben sollte. Bitte das Update installieren und ein paar Stunden warten, damit die Risikoberechnung im Hintergrund durchgeführt wird. Danach sollte alles funktionieren.
> 
> Ich hatte ein ähnliches Problem und es wurde mit dem Update heute gelöst.

Nach dem Update hatte ich zuerst den grauen Hinweis "Unbekanntes Risiko", heute dann "Geringes Risiko 1 von 14 Tagen", obwohl ich die App seit dem ersten Tag installiert habe

**Comment by inf2381** [comment]
> > Heute wurde ein Update auf Version 1.0.3 veröffentlicht das dieses Problem beheben sollte. Bitte das Update installieren und ein paar Stunden warten, damit die Risikoberechnung im Hintergrund durchgeführt wird. Danach sollte alles funktionieren.
> > Ich hatte ein ähnliches Problem und es wurde mit dem Update heute gelöst.
> 
> Nach dem Update hatte ich zuerst den grauen Hinweis "Unbekanntes Risiko", heute dann "Geringes Risiko 1 von 14 Tagen", obwohl ich die App seit dem ersten Tag installiert habe

Das liegt wahrscheinlich daran, dass die History durch den alten Code bereits vor dem Update gelöscht wurde. In der Zukunft sollte das Problem durch den letzten Hotfix nicht mehr auftreten.

**Comment by below** [comment]
> Das liegt wahrscheinlich daran, dass die History durch den alten Code bereits vor dem Update gelöscht wurde. In der Zukunft sollte das Problem durch den letzten Hotfix nicht mehr auftreten.

Funktioniert denn die Risikoermittlung für die vergangenen Tage noch, oder fange ich jetzt tatsächlich von vorne an?

**Comment by jwildeboer** [comment]
Ich kann zwar sehen das heute 9 Checks durchgeführt wurden, aber es gibt wohl keine Möglichkeit in Erfahrung zu bringen wieviele BegegnungsKeys seit wie vielen Tagen lokal auf dem iPhone erfasst wurden. Daher kann ich nur hoffen, das die ganzen keys der letzten 14 Tage noch da sind. Eventuell Vorschlag an Apple den Status der erfassten Begegnungskeys irgendwie sichtbar zu machen?

**Comment by inf2381** [comment]
> Funktioniert denn die Risikoermittlung für die vergangenen Tage noch, oder fange ich jetzt tatsächlich von vorne an?

Die Risikoermitting funktioniert nach wie vor. Das ist ein reines Anzeigeproblem. Außer es wäre auf 0 zurückgesprungen. Dann würde für 24h keine Überprüfung gemacht werden.

**Comment by inf2381** [comment]
> Ich kann zwar sehen das heute 9 Checks durchgeführt wurden, aber es gibt wohl keine Möglichkeit in Erfahrung zu bringen wieviele BegegnungsKeys seit wie vielen Tagen lokal auf dem iPhone erfasst wurden. Daher kann ich nur hoffen, das die ganzen keys der letzten 14 Tage noch da sind. Eventuell Vorschlag an Apple den Status der erfassten Begegnungskeys irgendwie sichtbar zu machen?

Die Keys der letzten 14 Tage sind definitiv noch vorhanden. Selbst ein kurzzeitiges Deinstallieren und würde das nicht beeinträchtigen. Apple hat für iOS 14 eine neue API angekündigt. Wir sind selbst auf die Änderungen gespannt, haben aber unsere Vorschläge angebracht.

**Comment by jwildeboer** [comment]
@inf2381 bei mir ist es tatsächlich auf 0 zurückgesprungen. ![image](https://user-images.githubusercontent.com/873028/86488894-cf43e780-bd62-11ea-8aff-aa3aa1456a7d.jpeg)

**Comment by tkowark** [comment]
Since this bug has not resurfaced after the recent updates, we'll close the issue accordingly. If you experience it again with the latest app and iOS version, please open a new, dedicated issue.

Thanks for all your input!
