### ISSUE TITLE
Show 3rd party libs usage in App Informationen

### ISSUE THREAD

**Issue by haosap** [corona-warn-app/cwa-app-ios#82]
## Feature description

As an open source project, we also leverage several open source projects from community. These projects should be shown in our app. After aligning with Ux colleagues, the screenshot looks like:

### Screenshot
![image](https://user-images.githubusercontent.com/64405225/83384773-4266e080-a3e8-11ea-8bf8-f7c325b3279c.png)

## Actions
- [ ] Create Rechtliche Hinweise on App Informationen
- [ ] Create a static file containing all information from THIRD-PARTY-NOTICES
- [ ] Create the Rechtliche Hinweise Viewcontroller and render the contents as the screenshot showed. (**No storyboard**)

**Comment by haosap** [comment]
Anyone who wants to take over this task, please firstly assign it to yourself.

**Comment by frnkschmtt** [comment]
Hi @haosap, I can take care of this one.
Can you please provide the asset shown in the mockup?

**Comment by haosap** [comment]
HI @frnkschmtt ,
Please check it here. thanks.
[Illu_Appinfo_RechtlicheHinweise.pdf](https://github.com/corona-warn-app/cwa-app-ios/files/4710880/Illu_Appinfo_RechtlicheHinweise.pdf)

**Comment by haosap** [comment]
Hi @frnkschmtt ,
Where do you load the text of 3rd party lib?

**Comment by frnkschmtt** [comment]
> Hi @frnkschmtt ,
> Where do you load the text of 3rd party lib?

Hi @haosap, let's discuss the details in the corresponding [pull request](https://github.com/corona-warn-app/cwa-app-ios/pull/111).
