### ISSUE TITLE
missing Changelog Version 1.0.3

### ISSUE THREAD

**Issue by hagct** [corona-warn-app/cwa-app-ios#826]
## Avoid duplicates
* [ ] Question is not already answered in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Question has not already been asked in another issue

## Your Question

* Source File: https://github.com/corona-warn-app/cwa-app-ios/blob/develop/CHANGELOG.md
* Line(s):
* Question: The Changelog only includes Version 1.0.2.4 but I couldnt find infos on the new Version 1.0.3 that was just updated under iOS. Where can I find infos about Version 1.0.3?

**Comment by jwildeboer** [comment]
AFAICS it was a very fast hotfix release to solve the issues described in #804, #805, #815, #818. TL;DR Saved Day calculation didn’t work es expected, causing app to either Display wrong number of saved days or even say that risk calculation wasn’t possible. Technically more it less a display issue, as the risk calculation and updates/downloads of keys continued to work. 

HTH

**Comment by inf2381** [comment]
My bad. I ran `gren release` but forgot `gren changelog`. In my defense, it was 1:30am :grin:
