### ISSUE TITLE
iOS 14 Developer Beta 

### ISSUE THREAD

**Issue by peternc10** [corona-warn-app/cwa-app-ios#836]
## Avoid duplicates

* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is not already reported in another issue

## Describe the bug
Die App funktioniert unter der iOS 14 Developer Beta 1 nicht. 

## Technical details

- iOS Version:
- Device:

**Comment by chris-redbeed** [comment]
iOS 14 didn't support the API currently - mention already in the FAQ: https://www.coronawarn.app/en/faq/#ios_14_beta

**Comment by nitaco** [comment]
The bug was fixed in the iOS and iPadOS 14.0 Developer Beta 4!
