### ISSUE TITLE
Inconsistent display of timestamps

### ISSUE THREAD

**Issue by PalminX** [corona-warn-app/cwa-app-ios#837]
## Avoid duplicates

* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is not already reported in another issue

## Describe the bug

The timestamp which is displayed in the App on the Exposure Detection view ("Aktualisiert: Heute, 02:25") is inconsistent with what is displayed by the iOS "COVID-19-Kontaktprotokoll" ("Heute, 00:25").
This is confusing and probably due to a wrong interpretation of timezones, since the timestamps displayed in the App and in the iOS settings should be the same, according to the timezone which is set in the device settings.

## Expected behaviour

The timestamps displayed for exposure detection in the app should be the same as the ones displayed in the iOS settings.

## Steps to reproduce the issue

1. Open the Corona-Warn-App and note the timestamp showing the last update ("Aktualisiert: Heute, 02:25")
2. Go to the COVID-19-Kontaktprotokoll in the iOS settings and open "Kontaktüberprüfungen", check the timestamps ("Heute, 00:25")
3. The timestamps show a difference of two hours

![image](https://user-images.githubusercontent.com/28887826/86461475-55900780-bd2a-11ea-9e49-0e0b9e55b66e.png)

![image](https://user-images.githubusercontent.com/28887826/86461503-5f196f80-bd2a-11ea-8479-833ef4236311.png)

## Technical details

- iOS Version: 13.5.1

## Possible Fix

It seems that the timezone handling in the app is not quite correct. Exporting the contact protocol from the iOS settings shows the original timestamps:

```
    {
      "Hash" : "...",
      "RandomIDCount" : XXXX,
      "MatchCount" : 0,
      "DataSource" : "de.rki.coronawarnapp",
      "Timestamp" : "2020-07-03 00:25:48 +0200"
    }
```

This means that the update was done at 00:25 CEST (UTC+2), not at 02:25 CEST

**Comment by jwildeboer** [comment]
Interesting. What is your time zone setup? I have automatic, Berlin and don‘t experience this problem. 

![image](https://user-images.githubusercontent.com/873028/86490410-93f7e780-bd67-11ea-9a16-a107dbfde646.jpeg)

![image](https://user-images.githubusercontent.com/873028/86490416-9b1ef580-bd67-11ea-818d-5f13e6c07df6.jpeg)

![image](https://user-images.githubusercontent.com/873028/86490427-a1ad6d00-bd67-11ea-9a76-ce8e8f80c17d.jpeg)

**Comment by PalminX** [comment]
@jwildeboer I have the same timezone setting (automatic, Berlin).
The screenshots that you have posted are not the issue. This is consistent for me as well. 
What does your in-app update timestamp say? Is it 21:31 as well?

**Comment by PalminX** [comment]
I could now confirm this on another iPhone: the CWA last update timestamps are two hours later than the correct timestamps in the system exposure notification settings

**Comment by jwildeboer** [comment]
@palminx my app shows the same time, that’s why I said I don’t see the problem on my side. ![image](https://user-images.githubusercontent.com/873028/86492737-62831a00-bd6f-11ea-9b52-d99d653b9521.jpeg)

**Comment by PalminX** [comment]
OK, that's interesting. As I said, I have seen this in two different phones now.

**Comment by PalminX** [comment]
The two phones I checked have the language set to German, yours is English.

**Comment by diveflo** [comment]
Just to add more data:
Timestamps are consistent on my phone (iPhone X - iOS 13.5.1). Language set to English. Time zone Berlin, automatic.

**Comment by PalminX** [comment]
Last night’s update now shows consistent timestamps. I switched to English language settings and back, and now I cannot be sure if this is related to the language setting. I will check again tomorrow.

**Comment by jwildeboer** [comment]
I guess the time stamps are fine now? Safe to close this bug?

**Comment by PalminX** [comment]
I haven't been able to reproduce this issue for the last two days. It seems that there is/was some initial condition which made it appeared, which is no longer applicable.

Closing
