### ISSUE TITLE
IOS 14, ENErrorDomain 3, Not startable

### ISSUE THREAD

**Issue by z-vpn** [corona-warn-app/cwa-app-ios#839]
## Describe the bug

The app doesn't get permission for the Corona data, so the app can no longer be used effectively or started.

## Expected behaviour

The app should be given Corona permission. In addition, the app should start normally when it starts.

## Steps to reproduce the issue

![image](https://user-images.githubusercontent.com/67786572/86463042-08f9fb80-bd2d-11ea-954d-1fe93f3858c7.png)

![image](https://user-images.githubusercontent.com/67786572/86463051-0e574600-bd2d-11ea-9309-6800d77de50c.png)

1. Open the newly installed app
2. Go to the point where you have to give permission for the Corona data
3. If you try to grant permission now, the error in the image will come.

If you want to open the app after setup, you only see an empty white app. (Second image)

## Technical details

- iOS Version: 14 (dev beta 1)
- Device: IPhone 11 Pro (64 GB)

## Possible Fix

Not known yet

## Additional context

This bug report was translated from German into English with Apple's new Translate app.

**Comment by chris-redbeed** [comment]
iOS 14 didn't support the API currently - mention already in the FAQ: https://www.coronawarn.app/en/faq/#ios_14_beta

**Comment by ferdinand** [comment]
## Avoid duplicates

* ❌ Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/#ios_14_beta)
* ❌ Bug is not already reported in another [issue](https://github.com/corona-warn-app/cwa-app-ios/issues/783)

**Comment by inf2381** [comment]
Thanks @ferdinand, @chris-redbeed !

@z-vpn: The issue template is there for a reason.
