### ISSUE TITLE
Tracking data lost / active days resetted / active days not fitting to tracked contacts / active days not increasing

### ISSUE THREAD

**Issue by HollyJonsen** [corona-warn-app/cwa-app-ios#845]
## Avoid duplicates

* [x ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x ] Bug is not already reported in another issue

## Describe the bug

I installed the Corona-Warn-App at the first day of its release (16.06.2020) at my iPhone 8 iOS 13.5.1.
The app appeared correct working till 01.07.2020. My active days counter increased as expected till 14 of 14 days (green). 
When I checked the second time at the 01.07.2020 my risk estimation was set back to "Unknown risk".
Since 01.07.2020 the active days are increasing again.

Today I wanted to create a issue for my findings then I realized: the tracked contacts are not fitting to the determined active days (see the attached picture from 12:25 today).

![Corona-Warn-App-RiskDetection-reset](https://user-images.githubusercontent.com/63231801/86484936-ab2ed900-bd57-11ea-8436-e6cc83c36582.png)

The tracked data is not from the last 14 days and I can't delive I didn't met someone else with a Corona-Warn-App at some days.
The oldes entry in the tracking is "Timestamp" : "2020-06-24 05:14:00 +0200". I have trackings on all following days till today.

Now I realized the app made a data update at 17:19 and didn't increased the number of active days (see the second screenshot from 17:47 today).

![Corona-Warn-App-RiskDetection-update](https://user-images.githubusercontent.com/63231801/86484942-aec26000-bd57-11ea-8aa7-0fdbe81c9fb2.png)

## Expected behaviour

The active day count should stay at 14 of 14 days.
The contact tracking should show contacts of the last 14 days.

## Steps to reproduce the issue

I have no idea how to reproduce.

## Technical details

Export: "Build" : "17F80",
- iOS Version:  iOS 13.5.1
- Device: iPhone 8

**Comment by inf2381** [comment]
Please have a look at #815 and #818. This explains why the counter "jumped" back from 14 to 3 days. A hotfix to address this issue has been provided on Wednesday morning. That hotfix will not bring you back to 14/14 but will prevent this from happening again.

**Comment by HollyJonsen** [comment]
The issue is fixed with the Version 1.1.2 (0)
