### ISSUE TITLE
iOS 14 - App not launching

### ISSUE THREAD

**Issue by TheProgrammingM** [corona-warn-app/cwa-app-ios#847]
When you try to open the CWA app on a iPhone, which has iOS 14 Beta v1 installed, it will start an go immediately to a grey screen with a dark grey bar at the top.

## Expected behaviour

App should start normally (normal UI).

## Steps to reproduce the issue

1. Install iOS 14 Beta from developers.apple.com
2. Install CWA App.
3. Open CWA APP.

## Technical details

- iOS Version: 14 Beta v1
- Device: iPhone Xs

## Possible Fix

Update for iOS 14.

**Comment by Jan10** [comment]
Duplicate #749
