### ISSUE TITLE
IOS Power safe mode is blocking app updates

### ISSUE THREAD

**Issue by LowPerfect** [corona-warn-app/cwa-app-ios#848]
Hintergrundaktualisierung is blocked if the power safe mode is aktive
![F9694FCE-0580-4F21-B936-6F98BC642C4F](https://user-images.githubusercontent.com/67806506/86497162-ceba4980-bd80-11ea-9d23-eac0d50b9ecb.png)

But most of the time my iphone is in power safe mode because of a second feature
![B1E2F76B-B97E-4EB2-A40B-E26C4882EE01](https://user-images.githubusercontent.com/67806506/86497128-a894a980-bd80-11ea-8c4e-9ff086dc9cc2.png)

Problem is that i can not overide manual the switch because it is blocked from IOS

So i need always to go manual to the app and update the status if i have met someone who has reported that he is ill 
That brakes the whole use case

Please clarify with apple why i can not overide the deaktivate Hintergrundaktualisierung or find a way that the app works in. Power safe mode

**Comment by christianneu** [comment]
This is a duplicate, please have a look here: #650
