### ISSUE TITLE
Wrong state of the app

### ISSUE THREAD

**Issue by tank6b** [corona-warn-app/cwa-app-ios#850]
![image](https://user-images.githubusercontent.com/794409/86510191-dfed6f80-bded-11ea-92d9-40751a7aeda6.png)

**Comment by christianneu** [comment]
This is duplicate, please have a look here: #741

**Comment by tank6b** [comment]
That’s a duplicate don’t solve the problem. I think the repo and managing the repo is more important than fixing the app. It only worked properly 4 days since it was released.
