### ISSUE TITLE
[UI] TAN entry view glitches (v1.0.5-dev)

### ISSUE THREAD

**Issue by tens0rfl0w** [corona-warn-app/cwa-app-ios#851]
**NOTE:** This is a follow up to the PR #687 that closed issue #591 .

This is not a _"serious"_ bug that needs an instant fix, but if someone finds the time to look at this, this would be a good thing to improve.
___
## Description
After the above mentioned PR, the TAN entry view was drastically improved and nearly all big glitches were fixed. But there are still some situations left where certain glitches occur that not have been mentioned before.

**NOTE:** All mentioned glitches are _very hard_ to trigger and are not likely to be triggered by a user that uses the app in "normal" use cases.
___
Visual examples for (some) glitches:
|Submit button breaks|Call button breaks|TAN entry field breaks|Another example for the button glitch|
|-|-|-|-|
| <img src="https://user-images.githubusercontent.com/57523343/86510984-0f53aa80-bdf5-11ea-9964-2d74c6d7cea6.gif" width="600"/> | <img src="https://user-images.githubusercontent.com/57523343/86511007-5e99db00-bdf5-11ea-9656-381bbaebdab1.gif" width="600"/> | <img src="https://user-images.githubusercontent.com/57523343/86511082-f26ba700-bdf5-11ea-92c6-141260594193.gif" width="600"/> | <img src="https://user-images.githubusercontent.com/57523343/86511086-f8fa1e80-bdf5-11ea-9a31-157005069fcd.gif" width="600"/> |

(Better open every GIF in a separate tab, looking at all 4 at the same time hurts your eyes.😅)

- Regarding bug shown in column **2**: This bug is the hardest to trigger, but if this bug happens the complete UI freezes and gets really weird flashes when trying to swipe back.
- Regarding bug shown in column **1**: This bug is really easy to trigger and if this happens the complete UI freezes too.
- Regarding bug shown in column **3**: I can't reproduce this glitch, this was a "random" finding when testing the UI.
- Regarding bug shown in column **1** & **3**: Both occur in the "Intro" -> "Hotline" -> "TAN entry" and "Intro" -> "TAN entry" call logic.
___
There is a high chance that there are more glitches in this view controller due to the high number of combined custom views.
I know that swipe gestures are really pain when working with custom views so I don't expect a fix at all. Maybe a rework of the whole view logic would be a better approach (some time in the future).😀

---
Internal Tracking ID: EXPOSUREAPP-1879

**Comment by heinezen** [comment]
This is no longer reproducible for us since CWA version 1.5, so I assume the issue is fixed @tens0rfl0w 

----
Corona-Warn-App Open Source Team
