### ISSUE TITLE
Number of Active Days stuck

### ISSUE THREAD

**Issue by mss1010** [corona-warn-app/cwa-app-ios#853]
## Avoid duplicates

* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is not already reported in another issue

## Describe the bug

Since 3 days in a row, the display of active days in the app shows "13/14 days". I saw the other issues related to a rounding issue of active days, but I think this is different, because in the meanwhile, the active days should be more than 14.

## Steps to reproduce the issue

I installed the app on the day when it came out. Also the updates were installed immediately on the days when the were released. On the day of the latest update 1.0.4 the days showed 13/14 before and after the update, and did not change since then.

## Technical details

- iOS Version: 13.5.1
- Device: iPhone Xs

**Comment by sysfyg** [comment]
I do have the same issue

**Comment by dwd0tcom** [comment]
Same for me!

**Comment by Tho-Mat** [comment]
I think with the last update it will stuck there. My wife has the same issue.

I did not update right now and my phone shows "19 of 14 days".

Both is not ideal. 
But i prefer 19/14 rather than 13/14. 

Two things that do not belong are attached together.
14 show the maximum number of days, that can be handled.
19 on my device shows the number of days the app is running.
13 on the other hand shows the maximum number of keys that could be transmitted.

Not really sure about that, but it could explain the behavior.

**Comment by mss1010** [comment]
I think this whole feature doesnt make sense. What is it supposed to show if you have more than 14 days active?

I think in that form it creates more confusion than it helps, and would remove it.

**Comment by inf2381** [comment]
We already know about this issue. We even tried to provide a hotfix on Friday but that update (1.0.4) only fixed it on the screen where you enable / disable the tracing. The PR to really fix it is already linked to this issue and we will ship that with the next update (end of this week). Other than that PR, #634 is already merged into our development branch. So you will at least see a difference between 14/14 and other numbers.
Unfortunately, the RKI insists on this feature so we cannot remove it.

**Comment by bombadiltom** [comment]
same here, and why does it even count up to 14? IMHO every day a new period of 14 days starts. And also: what about the delay between testing and entering it into the app?

**Comment by inf2381** [comment]
1.0.5 is available now. A hotfix usually takes just one day. But 1.0.5 fixed a lot more than just this issue.
