### ISSUE TITLE
app not working on iOS 14 developer beta

### ISSUE THREAD

**Issue by PeerRich** [corona-warn-app/cwa-app-ios#854]
## Describe the bug

![image](https://user-images.githubusercontent.com/8019099/86532341-6b87fe80-bec9-11ea-9a00-e6efbff210b1.png)

Once “cancelled” the NEXT buttons also stopped working, see video: 
https://youtu.be/5IObvfRpxIs

## Steps to reproduce the issue

1. Download iOS 14 Profile
2. Start Corona Warn App

## Technical details

- iOS Version: iOS 14
- Device: iPhone XR

**Comment by inf2381** [comment]
![FAQ](https://user-images.githubusercontent.com/15961043/86533289-74c89980-bed0-11ea-87fa-8d2db9fc7388.png)
https://www.coronawarn.app/en/faq/#ios_14_beta

**Comment by PeerRich** [comment]
overlooked that, my bad!
