### ISSUE TITLE
EnDomain–Error 13

### ISSUE THREAD

**Issue by Happyfeet01** [corona-warn-app/cwa-app-ios#855]
When i open the App i get this error

![image](https://user-images.githubusercontent.com/3295104/86532496-beae8100-beca-11ea-8c0f-4f4d334f4f09.png)

## Technical details

- iOS Version: 13.5.1
- Device: iphone Xr

**Comment by inf2381** [comment]
![FAQ](https://user-images.githubusercontent.com/15961043/86533274-4e0a6300-bed0-11ea-9d20-c92d0a039ea3.png)
The next update will provide a more meaningful message for this issue.
