### ISSUE TITLE
iOS 13 Support is not enough

### ISSUE THREAD

**Issue by vincentschroeder** [corona-warn-app/cwa-app-ios#860]
I have an Iphone 6 which is not really old but it's not supported for the corona-warn-app. To make this app broadly usable and not only to privileged user which can afford the latest iphone, please consider to make it at least iOs 12 working. This should have been a no1 requirement in the planning, because the success of the app depends on how many user can use it.

**Comment by Ein-Tim** [comment]
https://www.coronawarn.app/de/faq/#ios135

**Comment by melloskitten** [comment]
As fellow community member @Ein-Tim has pointed out, you can check out the FAQ to find out the reasoning behind this decision. Closing this now. Have a great day & cheers! 👍😊

**Comment by vincentschroeder** [comment]
Thanks, did you address this to apple? This seems to be an artificial limitation, the hardware should support that.
