### ISSUE TITLE
[Discussion] Why is there no documentation/comments in the code

### ISSUE THREAD

**Issue by pixelass** [corona-warn-app/cwa-app-ios#861]
If you expect trust, you should maybe look at some basic best practices in your code.
Maybe adding comments or basic documentation in your code would be a nice way to start.

It's really hard (IMHO impossible) to trust a codebase like this.

**Comment by tkowark** [comment]
Dear @pixelass ,

thank you very much for raising these concerns. While we do have some [basic documentation](https://github.com/corona-warn-app/cwa-app-ios/blob/develop/docs/architecture-overview.md) and also provided explanatory comments in some code files, we could, of course, always do more.

We will leave this issue open as a reminder to improve comment quantity and quality and investigate if and how to support it in our CI process.

**Comment by Ein-Tim** [comment]
There are many comments in the code now. 
I think this can be closed. 👍

**Comment by pixelass** [comment]
Great work. Thank you so much for the effort.

**Comment by dsarkar** [comment]
@pixelass and community,

Thanks for contributing! Best wishes, DS

---
Corona-Warn-App Open Source Team
