### ISSUE TITLE
Risikoermittlung in iOS 13.5.1 nicht möglich

### ISSUE THREAD

**Issue by svesch2006** [corona-warn-app/cwa-app-ios#872]
Hallo,

seit ein paar Tagen habe ich das Problem unter iOS 13.5.1, dass die Risikoermittlung nicht mehr möglich isst. Es wird ein grauer Kasten angezeigt, und man wird darauf hingewiesen, dass man die Risikoermittlung einschalten soll. 
![IMG_3112](https://user-images.githubusercontent.com/68024334/86948019-e3199000-c14c-11ea-856f-17058b3ada66.jpeg)

Diese ist jedoch aktiv, Bluetooth ist ebenfalls an. Alle bisherigen Punkte, die eine Lösung sein sollen haben bei mir bislang nicht funktioniert - ist dies ein Problem welches durch die Entwickler auf Seiten der App (SAP und Telekom) oder auf Seiten von Apple in Form einer neuen iOS Version beheben können?

![IMG_3113](https://user-images.githubusercontent.com/68024334/86948265-2b38b280-c14d-11ea-9e33-16dc9e1ae4ce.jpeg)

Vielen Dank für weitere Hinweise, was ich noch prüfen oder tun kann, damit die App wieder wie gewünscht funktioniert.

Viele Grüße

**Comment by SebastianWolf-SAP** [comment]
Der Fehler deutet darauf hin, dass Sie über längere Zeit keine Internetverbindung hatten. Diese wird benötigt, um die neuesten Diagnoseschlüssel herunterzuladen. Nur mit den neuesten Schlüsseln kann die Risikoermittlung durchgeführt werden.

Bitte stellen Sie sicher, dass Sie die neueste Version der App installiert haben (aktuell 1.0.4, siehe App-Informationen). Versuchen Sie im Zweifel einen Neustart des Gerät, stellen Sie sicher, dass Sie mit dem Internet verbunden sind und starten die Corona-Warn-App. Im Anschluss müssten die neuesten Schlüssel heruntergeladen und die Risikoermittlung durchgeführt werden können.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by svesch2006** [comment]
Hallo Sebastian,Vielen Dank für die Rückmeldung.Eine Internetverbindung war und ist vorhanden - zuhause und im Büro über WLAN, unterwegs mobil mittels 4G (überwiegend), ansonsten 3G - also eine Verbindung war definitiv vorhanden!Ich hatte bei meiner Ursprungsfrage leider vergessen anzugeben, dass ich neben dem aktuellen iOS 13.5.1 auch die Corona App in der neuesten verfügbaren Version 1.0.4 installiert habe - laut AppStore seit dem 03.07.2020.Ich habe mein iPhone bereits mehr als ein Mal in den letzten Tagen neu gestartet- leider ohne Erfolg.Also aus meiner Sicht sind alle Punkte erfüllt, und dennoch funktioniert die App nicht (mehr).Weitere Ideen oder Vorschläge?Freundliche Grüße Am 08.07.20 um 19:41 schrieb Sebastian Wolf
                
            
            
                
                    Von: "Sebastian Wolf" <notifications@github.com>Datum: 8. Juli 2020An: "corona-warn-app/cwa-app-ios" <cwa-app-ios@noreply.github.com>Cc: "Author" <author@noreply.github.com>,"svesch2006" <sa_s@gmx.net>Betreff: Re: [corona-warn-app/cwa-app-ios] Risikoermittlung in iOS 13.5.1 nicht möglich (#872)
                
                

Der Fehler deutet darauf hin, dass Sie über längere Zeit keine Internetverbindung hatten. Diese wird benötigt, um die neuesten Diagnoseschlüssel herunterzuladen. Nur mit den neuesten Schlüsseln kann die Risikoermittlung durchgeführt werden.

Bitte stellen Sie sicher, dass Sie die neueste Version der App installiert haben (aktuell 1.0.4, siehe App-Informationen). Versuchen Sie im Zweifel einen Neustart des Gerät, stellen Sie sicher, dass Sie mit dem Internet verbunden sind und starten die Corona-Warn-App. Im Anschluss müssten die neuesten Schlüssel heruntergeladen und die Risikoermittlung durchgeführt werden können.

Mit freundlichen Grüßen/Best regards,

SW

Corona Warn-App Open Source Team



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/corona-warn-app/cwa-app-ios/issues/872#issuecomment-655661057",

"url": "https://github.com/corona-warn-app/cwa-app-ios/issues/872#issuecomment-655661057",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by Tatti01** [comment]
Ich kann das Problem von svesch bestätigen. Ich habe den gleichen Fehler. Bei mir kommt zusätzlich noch das Fenster mit der Meldung "Etwas ist schief gelaufen. Der Vorgang konnte nicht abgeschlossen werden.  (ENErrorDomain-Fehler 13.). Im Netz ist dazu zu lesen, dass im Allgemeinen nach einem Neustart die Meldung irgendwann verschwindet- also eher in Richtung Schönheitsfehler, der mit dem nächsten iOS-Update beseitigt ist . Bei mir jedoch wird angezeigt, dass die letzte Aktualisierung am 06.07.2020, 13:39 war. Also nun schon fast 3 Tage her. Das klingt ja schon eher so, also würde sie nicht mehr funktionieren.
Ich habe ein iPhone X mit aktuellem iOS und aktueller Corona-Warn-App. In der Zeit, während ich schlafe, aktiviere ich den Flugmodus, ansonsten habe ich ständig eine Internet-Verbindung.

**Comment by SebastianWolf-SAP** [comment]
Ja, Apple-Framework-seitig gibt es da noch einige Problemchen. Wenn aber hier alles auf dem aktuellen Stand ist und Internet da ist, könnte es auch an dem Problem liegen, was in #740 angesprochen wurde. Der Hintergrund-Job funktioniert entweder nicht richtig oder schlägt fehl. 

Bitte nochmal kurz überorüfen, ob in den Einstellungen -> Corona-Warn die Hintergrundaktualisierung eingeschaltet ist. Dann die App auf jeden Fall nochmal komplett schließen, also nicht nur in den Hintergrund schicken, sondern in der Ansicht der aktiven Apps wegswipen und dann nochmal starten.

Mit freundlichen Grüßen/Best regards,
SW
Corona Warn-App Open Source Team

**Comment by Tatti01** [comment]
Die Hintergrundaktualisierung für Corana-Warn war von Anfang an eingeschaltet. Habe ich auch noch einmal überprüft.  Aus dem Speicher entfernen bringt auch nichts. Die Aktualisierung bleibt auf 06.07.2020 stehen. Was ich nicht probiert hatte, wie in #740 steht, ist einen Tag zu warten, bevor die App wieder neu gestartet wird. 

Viele Grüße
Michael

**Comment by JThoennes** [comment]
Hab seit Neuestem auch dieses Problem. Dazu kommt wechselweise der Fehler-Popup vom iOS mit "ENErrrorDomain Fehler 11" oder "... Fehler 13". Vorher kam immer etwas mit Region. Jetzt ist die App völlig funktionsunfähig. Internet habe ich natürlich, sowohl WLAN und Mobiles Internet. Auch Kaltstart von iOS hat nicht geholfen. Die App ist meines Erachtens richtig kaputt, Neuinstallation ist auch keine echte Lösung, da dann die Historie verloren geht oder?

**Comment by JThoennes** [comment]
Bezüglich #740 -- das hatte ich vorher, jetzt ist es noch schlimmer!!

**Comment by JThoennes** [comment]
Das Kontaktprotokoll zeigt, dass ich heute früh eine Kontaktüberprüfung hatte. Aber vorher zuletzt am 6. Juli.

**Comment by Tatti01** [comment]
> Das Kontaktprotokoll zeigt, dass ich heute früh eine Kontaktüberprüfung hatte. Aber vorher zuletzt am 6. Juli.

Das Kontaktprotokoll zeigt bei mir auch aktuelle Einträge. Offenbar wird aber nichts mehr übermittelt.

**Comment by svesch2006** [comment]
Dann scheine ich wohl nicht alleine mit dem Problem zu sein - beruhigt mich allerdings nicht wirklich, wenn es bei so einer Angelegenheit so viele Probleme gibt.Die Hintergrundaktualisierung für die App ist seit dem ersten Tage aktiv. In meinem Kontaktprotokoll erscheint der letzte Eintrag vom 04.07.2020, 19:05 - ist schon ein paar Tage her.Löschen und neu installieren möchte ich nicht in Erwägung ziehen, da sonst die bisher gesammelten Informationen verloren wären.Weitere Ideen um die App wieder ans laufen zu bekommen?Am 09.07.20 um 14:43 schrieb Tatti01
                
            
            
                
                    Von: "Tatti01" <notifications@github.com>Datum: 9. Juli 2020An: "corona-warn-app/cwa-app-ios" <cwa-app-ios@noreply.github.com>Cc: "svesch2006" <sa_s@gmx.net>,"Author" <author@noreply.github.com>Betreff: Re: [corona-warn-app/cwa-app-ios] Risikoermittlung in iOS 13.5.1 nicht möglich (#872)
                
                



Das Kontaktprotokoll zeigt, dass ich heute früh eine Kontaktüberprüfung hatte. Aber vorher zuletzt am 6. Juli.



Das Kontaktprotokoll zeigt bei mir auch aktuelle Einträge. Offenbar wird aber nichts mehr übermittelt.



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/corona-warn-app/cwa-app-ios/issues/872#issuecomment-656104777",

"url": "https://github.com/corona-warn-app/cwa-app-ios/issues/872#issuecomment-656104777",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by inf2381** [comment]
Wir versuchen gerade, das instabile Framework so gut es geht in den Griff zu bekommen. Deshalb wird es innerhalb der nächsten 24 Stunden ein neues Update geben. Wenn der Background-Task nicht läuft, kann das verschiedenste Gründe haben:
1. Internetverbindung war nicht aktiv oder zu schlecht als der Task lief
2. iOS glaubt, das Gerät befindet sich außerhalb Deutschland
3. Das Framework läuft in einen internen Fehler bei `detectExposures`

Folgende Schritte würde ich empfehlen:
* App schließen; Hintergrundaktualisierungen ausschalten; App starten, Risikoermittlung manuell starten
  -> Falls es einen internen Fehler gibt, wird er hier als Pop-Up kommen
* Die App öffnen, in den Hintergrund schicken und dann erst abschießen und danach 24 Stunden die App nicht mehr öffnen
* Falls nichts davon hilft: App nach dem Update auf 1.0.5 neu installieren (Hier wird lediglich die History für wie lange das Tracing aktiv ist gelöscht) und 24 Stunden warten bist zum ersten Mal wieder eine Aktualisierung möglich ist

**Comment by JThoennes** [comment]
@inf2381 Ich hab immer noch nicht verstanden, wie man die Risiko-Ermittlung "manuell" einschaltet.

**Comment by SebastianWolf-SAP** [comment]
@JThoennes Hierzu muss man die Hintergrundaktualisierung ausschalten. Um das zu tun, bitte in die App Einstellungen -> Corona-Warn (in der Liste der Apps weiter unten) und da "Hintergrundaktualisierung" ausschalten. Danach erscheint in der App ein Button zur manuellen Aktualisierung. Dieser ist aktiv, wenn seit der letzten Aktualisierung mehr als 24 Stunden vergangen sind.

Mit freundlichen Grüßen/Best regards,
SW
Corona Warn-App Open Source Team

**Comment by JThoennes** [comment]
@SebastianWolf-SAP Danke, hatte vorher in die FAQ geschaut ;-)

**Comment by Tatti01** [comment]
Und ich habe gerade den ersten Punkt von Marc Bormeth ausprobiert. Also Hintergrundaktualisierung ausgeschaltet, App neu gestartet. Plötzlich wieder alles wie es sein soll. Bei der Aktualisierung steht: Heute, 16,55 Uhr.
Warum das jetzt ohne Fehlermeldung alles tut, entzieht sich mir komplett. Ich wüsste nicht, dass ich anders ausprobiert habe, als die letzten 2 Tage.
Danke aber an alle für Eure Unterstützung
Michael

**Comment by JThoennes** [comment]
Ich bin normalerweise immer auf Batterie-Sparen, sind damit _diese_ Hintergrundaktualisierungen auch schon ausgeschaltet?

**Comment by mlthlschr** [comment]
Moin,
hab das gleiche Problem. Hab mein Nutzungsverhalten seit Start nicht grundlegend geändert. Das einzige, was eventuell problematisch war, war ein kurzzeitiges Deaktivieren vom Bluetooth (und das Update auf 13.5.1). Weiß allerdings nicht, ob das auch Auswirkungen auf das exposure logging hat.

**Comment by allesmatze** [comment]
> Ich bin normalerweise immer auf Batterie-Sparen, sind damit _diese_ Hintergrundaktualisierungen auch schon ausgeschaltet?

Ja, im Stromsparmodus sind alle Hintergrundaktualisierungen deaktiviert.

**Comment by JThoennes** [comment]
> > Ich bin normalerweise immer auf Batterie-Sparen, sind damit _diese_ Hintergrundaktualisierungen auch schon ausgeschaltet?
> 
> Ja, im Stromsparmodus sind alle Hintergrundaktualisierungen deaktiviert.

Auf #740 hatte ich verstanden, dass diese Art von Aktualisierungen eine Sonderrolle spielen. Daher fragte ich.

**Comment by svesch2006** [comment]
Hallo, Kleines Update von meiner Seite. Ich habe heute Morgen gleich das Update 1.0.4 der App auf meinem iPhone installiert. Leider ist das Verhalten immer noch so, wie zuvor. Heißt dies nun einfach warten oder liegt doch nich ein Problem vor?Aufgrund der Hinweise bzgl. der Hintergrundaktualisierung habe ich mir die Einstellung nochmals angeschaut und musste feststellen, dass der Schieber aktiviert ist, allerdings kann ich diesen nicht bewegen - ist das ggf die Ursache für das Problem?Am 09.07.20 um 18:52 schrieb Jörg Thönnes
                
            
            
                
                    Von: "Jörg Thönnes" <notifications@github.com>Datum: 9. Juli 2020An: "corona-warn-app/cwa-app-ios" <cwa-app-ios@noreply.github.com>Cc: "Author" <author@noreply.github.com>,"svesch2006" <sa_s@gmx.net>Betreff: Re: [corona-warn-app/cwa-app-ios] Risikoermittlung in iOS 13.5.1 nicht möglich (#872)
                
                


Ich bin normalerweise immer auf Batterie-Sparen, sind damit diese Hintergrundaktualisierungen auch schon ausgeschaltet?

Ja, im Stromsparmodus sind alle Hintergrundaktualisierungen deaktiviert.

Auf #740 hatte ich verstanden, dass diese Art von Aktualisierungen eine Sonderrolle spielen. Daher fragte ich.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/corona-warn-app/cwa-app-ios/issues/872#issuecomment-656238219",
"url": "https://github.com/corona-warn-app/cwa-app-ios/issues/872#issuecomment-656238219",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by BettinaPfeifer** [comment]
Danke an die Fragesteller und Kommentierer hier, meine CWA war bei 13/14 seit Tagen eingefroren. Jetzt, nach App abschiessen, Hintergrundaktualisierung abstellen und App neu öffnen, Hintergrundaktualisierung wieder anschalten scheint es keine nervigen (und auch verunsichernde) Fehlermeldungen und tagelage 13/14 Tagen aktiv-Darstellung mehr zu geben.

**Comment by SebastianWolf-SAP** [comment]
![image](https://user-images.githubusercontent.com/46522656/87222525-6f59cc00-c374-11ea-83f1-dc4c92802e6d.png)

Another probably related hint for this error that came in via e-mail: Background update is switched on but "light green"...

**Comment by nitramred** [comment]
Ich hatte ebenfalls den Fall, dass die Exposure Checks nicht mehr geladen wurden – Background App Refresh hatte ich komplett für alle Apps ausgeschaltet und in der Warnapp manuell aktualisiert. Aber offensichtlich seit Donnerstag dann über 24 (48? 72?) Stunden nicht mehr. Durch den ausgeschalteten App Refresh kamen keine Aktualisierungen mehr, aber ein entpsrechender Button zum manuellen Aktualisieren in der App war dann anscheinend dem Hinweis gewichen, doch die Risiko-Ermittlung einzuschalten (die aber nach wie vor angeschaltet war). Nach Einschalten des generellen Background App Refreshs und Neustart der App war wieder alles "grün". Habe den Background App Refresh wieder ausgeschaltet und beobachte die nächsten Tage – oder bis zum nächsten Update (aktuell bin ich auf Version 1.0.6
![IMG_5148](https://user-images.githubusercontent.com/4311852/87247348-a81ca280-c453-11ea-8d6f-cf0ecceda83b.png)
![IMG_5146](https://user-images.githubusercontent.com/4311852/87247339-a521b200-c453-11ea-9a50-b26807a9a2e6.png)
![IMG_5147](https://user-images.githubusercontent.com/4311852/87247345-a652df00-c453-11ea-8e16-93f4ce74fa1d.png)
![IMG_5149](https://user-images.githubusercontent.com/4311852/87247346-a6eb7580-c453-11ea-900f-36c5319c2492.png)

**Comment by PalminX** [comment]
A lot of this has been covered in #740 already, but I think another contributing factor is that after an app update through the Apple AppStore, the app would need to be manually opened at least once to register the background tasks. If this isn't done, the tasks will not be scheduled.

**Comment by nitramred** [comment]
> the app would need to be manually opened at least once to register the background tasks.

Thanks for this clue – sure something an update can fix...?

**Comment by Ulenrich** [comment]
Are you all missing this following configuration? Those users might be affected who only have mobile data with their Telecommunications Company but most of the time don't have wifi available:

Config App:
General -> background act. -> backgroung act. -> (3) wifi & mobile data

(german) Einstellungen:
Allgemein -> Hintergrundaktualisierung -> Hintergrundaktualisierung -> (3.) WLAN & Mobile Daten

**Comment by mlthlschr** [comment]
@Ulenrich indeed. I had it switched off completely (background app refresh Off). Now that I switched it to Wi-Fi, the issue disappeared and the app works again.
Strangely, even though I had switched off background app refresh, it was forcefully switched on in the app settings (light green).

**Comment by Ulenrich** [comment]
If you are on the road during a journey, don't forget to switch to the 3. option Wifi & Mobile Data

**Comment by PalminX** [comment]
> > the app would need to be manually opened at least once to register the background tasks.
> 
> Thanks for this clue – sure something an update can fix...?

I think the app would need to start using Push Notifications in addition to the scheduled background tasks.

**Comment by tkowark** [comment]
@svesch2006 Did any if the last updates (app and/or iOS) resolve your issue?

**Comment by Tatti01** [comment]
Yes, my issues are resolved.
Thank you all for your help.

**Comment by daimpi** [comment]
I just heard from someone on Twitter still encountering this Problem under iOS 13.6: https://twitter.com/Hanno_Bender/status/1289985541581049858

**Comment by SebastianWolf-SAP** [comment]
Thanks, @daimpi for the link. However, it seems that after short time it worked again for the respective user: https://twitter.com/Hanno_Bender/status/1290020997685379072

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by daimpi** [comment]
@SebastianWolf-SAP Yes. I know. I directed him to follow the instructions laid out [here](https://github.com/corona-warn-app/cwa-app-android/issues/637#issuecomment-655543400) to activate "Background App refresh". At first it seemed as if it didn't work, but then it actually did.

Is this something which the App could activate itself? Otherwise it might be useful to add those instructions in the FAQ, as this is not the first person I've encountered with this specific problem ("Risikoermittlung nicht möglich").

**Comment by SebastianWolf-SAP** [comment]
We are still working on a larger update which also addresses several issues with respect to background updates. Notifications will be made available to the end user both in the app itself (especially on Android), but as well in our FAQ.
However, as such settings always need a user confirmation, the only thing we can do is present the options as prominently as possible, so that the respective settings are made...

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by GPclips** [comment]
Hello @svesch2006 and community,

can you confirm that the issue is gone or does it still exist?

Thanks,
LMM

Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
I don't know but since the App now requires min. iOS 13.6 I think this can be closed

**Comment by heinezen** [comment]
Superceded by #741
