### ISSUE TITLE
Screen shows "Risikoermittlung gestoppt"

### ISSUE THREAD

**Issue by HeiDasGri** [corona-warn-app/cwa-app-ios#878]
## Avoid duplicates

* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is not already reported in another issue

## Describe the bug

After Update to 1.0.5 the text changed from "Niedriges Risiko" to "Risikoermittlung gestoppt"

## Expected behaviour

The old text "Niedriges Risiko" is correct

## Steps to reproduce the issue

See screenshot before and after update

## Technical details

- iOS Version: 13.5.1
- Device: iPhone 7, iPhone 8 and iPhone 11

## Additional context
Before update:
![IMG_0160](https://user-images.githubusercontent.com/67737547/87118429-a8624580-c27b-11ea-8cbe-ab33c0364411.PNG)
after update:
![IMG_0162](https://user-images.githubusercontent.com/67737547/87118434-ab5d3600-c27b-11ea-86db-b4261e90d3a4.PNG)

**Comment by jenswet** [comment]
I can reproduce this. 

iPhone XS, iOS 13.5.1

**Comment by inf2381** [comment]
Closed by #879. Update will be shipped within the next 6 hours.

**Comment by Ein-Tim** [comment]
I also have this bug.

iPhone XR, iOS 13.6 Public Beta 3
