### ISSUE TITLE
Change configuration for vector PDFs in asset catalogs

### ISSUE THREAD

**Issue by yannikbloscheck** [corona-warn-app/cwa-app-ios#88]
## Current Implementation
PDF vector graphics are configured in some asset catalogs as multiple scale versions instead as a single scale vector file. Open an image in an access catalog (for example "enSettings/Icons_Bluetooth" in "Assets.xcassets") and you will see slots for multiple size versions although the original file used is a vector PDF:
![Current](https://user-images.githubusercontent.com/1571006/83403051-33902600-a408-11ea-9862-8ebfc767333a.png)

## Suggested Enhancement
Set "Resizing" to "Preserve Vector Data" and "Scales" to "Single Scale" for all vector PDFs files in all asset catalogs:
![Better](https://user-images.githubusercontent.com/1571006/83403047-32f78f80-a408-11ea-9f28-3f9bfca056c8.png)

## Expected Benefits
Correct use of asset catalogs everywhere with maybe better image quality on all current and possible future devices

**Comment by steins-code** [comment]
#102
