### ISSUE TITLE
Release Notes in GH

### ISSUE THREAD

**Issue by robertoschwald** [corona-warn-app/cwa-app-ios#881]
In the  [(GH Tag page for 1.0.6),](https://github.com/corona-warn-app/cwa-app-ios/releases/tag/1.0.6) you barely state fixes and enhancements. E.g: For 1.0.6, it just says "Fix text on risk detail page #879".
Via Email, I got full details of the update. 
Please add this info to the Tag page as well (and in the future):

Bug fixes

Fix text on risk detail page #879
Fix blank Data Privacy page after 5 minutes without user interaction #825
Fixed wrong implementation of shouldPerformExposureDetection #869
Error 13 mitigations #863
fixes wrong days with tracing info on home screen #849
Updating of home cells #822
Fixed number of active days #841
Remove error when submitting 0 keys #800
Fix number of days since last exposure #811
Hotfix/pruning 2 #812
Fix pruning of tracing history #807
[bug] Mitteilungen - image not focusable with voice over (closes 1427) #725
Fixed deadlock when clicking on risk cell (closes #747) #746
[Bug] Nutzung Chapter 7 link (de) updated #779
[Bug] Remove invite friends footer translucency #751
[Bug] Submission Flow Navigation #687
EXPOSUREAPP-1531 Sharing function is missing explanation text #745
show indicator progress on the risk cell #634
Fixed: Link to English FAQs when running the App in English (closes #643) #644
[Bug] Fix ActionTableViewCell accessibility issue (closes #670) #673
[Bugfix] Only request user notifications where necessary #674
[fix] change timeout interval #676
[Bug] Disable iTunes file sharing for the app (closes #700) #705
[Bug] Fixed risk view #718
[Bug] Fix height of manual refresh button on home screen. #606
Fix unknown out dated card button #611
[Bug] Fix unknown outdated risk detail screen #613
[HOTFIX] Set earliestBeginTime to nil #612
New features

Tracing Status Animation #821
Added Arabic and Russian translation #858
Updated [TR] html content to Turkish translations #829
Translation for turkish added #773
[Feature] ENAButton activity indicator for submission flow #753
[Feature] ENAButton accessibility #752
Enhancements

Add home screen risk cell update button countdown #866
Home Screen Risk Cell Update on App start + Risk Calc Refinements #874
Reschedule bgtasks #824
Risk Calculation Errors - Alert Refinement #868
ExposureDetectionViewController refresh countdown #838
integrate new localized errors for exposurenotification settings #840
Exposure Submission Flow - Error Alert adjustments #843
Update turkish translation #832
Added the missing localizations for the alerts. #672
Update ExposureSubmissionService.swift #608
[HOTFIX] Call requestRisk on sceneWillEnterForeground #607
Others

**Comment by inf2381** [comment]
That's a weakness of GitHub release notes. I creates release notes for everything that has been closed since the last release. But since this hotfix contains only the one PR that has been merged into master branch (not everything we already have in develop branch) I had to manually remove all PRs that are not part of this release from the release notes.

**Comment by robertoschwald** [comment]
Thanks for clarification.
