### ISSUE TITLE
App startet nicht unter ios 14 beta

### ISSUE THREAD

**Issue by digitalGoldi** [corona-warn-app/cwa-app-ios#885]
Unter ios 14 beta startet die App nicht mehr. Es wird nur ein weißer Bildschirm angezeigt.

Haupthandy ist natürlich weiterhin bei 13, aber auf dem Entwicklungshandy klemmt es.

Handy: IPhone 11 Pro
Version: 14.0 Beta (18A531i)
Corona App: 1.0.5

**Comment by inf2381** [comment]
Please look at the FAQ

**Comment by SebastianWolf-SAP** [comment]
Unter iOS 14 Beta wird seitens Apple das Exposure Notification Framework noch nicht unterstützt, siehe unsere FAQ: https://www.coronawarn.app/de/faq/#ios_14_beta

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
