### ISSUE TITLE
iOS 14 Public Beta

### ISSUE THREAD

**Issue by webtimo-de** [corona-warn-app/cwa-app-ios#886]
Hallo, ich als Entwickler verwende gerade das neue iOS 14 Public Beta! Und wenn ich die App starte, sehe ich nur ein leeren Container.  Allerdings weiß ich nicht ob dies an Apple oder an der App liegt. 

Ich würde mich freuen über eine schnelle Probleme Lösung. 

Und bitte teilen sie mir mit wenn es nicht an der App liegt, sondern an Apple, dass ich dann wieder auf iOS 13 downgraden kann.

Grüße
Timo

**Comment by tens0rfl0w** [comment]
Sie als Entwickler sollten dann vielleicht vorher auch mal einen Blick in das FAQ dieses Projektes werfen:
https://www.coronawarn.app/de/faq/#ios_14_beta

Das Fehler Template hat ja nicht ohne Grund die Checkliste um zu prüfen, ob ein Duplikat existiert. Auch unter „geschlossenen Fehlern“ können sie nachvollziehen, dass dieser Fehler in den letzten 2 Wochen bestimmt über 10 mal gestellt wurde.

Das erspart den Entwicklern viel Arbeit!
Danke!😊

**Comment by webtimo-de** [comment]
> 
> 
> Sie als Entwickler sollten dann vielleicht vorher auch mal einen Blick in das FAQ dieses Projektes werfen:
> https://www.coronawarn.app/de/faq/#ios_14_beta
> 
> Das Fehler Template hat ja nicht ohne Grund die Checkliste um zu prüfen, ob ein Duplikat existiert. Auch unter „geschlossenen Fehlern“ können sie nachvollziehen, dass dieser Fehler in den letzten 2 Wochen bestimmt über 10 mal gestellt wurde.
> 
> Das erspart den Entwicklern viel Arbeit!
> Danke!😊

Danke. Bin auch vor 10 min wieder auf iOS 13.5 gegangen. Da ich demnächst nach Mallorca fliege, brauch ich eine Funktionierde Corona App. Ich werde aber das FAQ in blick behalten. Danke für die Schnelle antwort!

Grüße
Timo

**Comment by tens0rfl0w** [comment]
@webtimo-de War auch nicht böse gemeint! Nur ein kleiner Hinweis😅

Wenn du möchtest, kannst du den Fehler jetzt auch selber schließen, dass erspart dem Team auch etwas Arbeit!😊
