### ISSUE TITLE
With iOS 14 Beta 2 only black screen at startup

### ISSUE THREAD

**Issue by dabigloosa** [corona-warn-app/cwa-app-ios#887]
No further info as I am not a dev, but it seems that there has something being changed in iOS14 which causes this app to black screen on startup. 
No Error message is thrown, it just stays in the black screen.

**Comment by SebastianWolf-SAP** [comment]
Please see our FAQ: https://www.coronawarn.app/en/faq/#ios_14_beta

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
