### ISSUE TITLE
13 of 14 Days display problem

### ISSUE THREAD

**Issue by slage16** [corona-warn-app/cwa-app-ios#888]
I have still the display problem that shows me 13 of 14 day active but I installed the app on 16.06.2020. 
iPhone XS
iOS 13.5.1
I install the update today before the app has synchronized

**Comment by SebastianWolf-SAP** [comment]
Please ensure to have the latest version 1.0.6 installed. This should fix the mentioned issue. If you still face the issue, please follow-up in the already existing issue #804 

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
