### ISSUE TITLE
App fails to load in iOS 14 Public Beta 2

### ISSUE THREAD

**Issue by j-rahman** [corona-warn-app/cwa-app-ios#889]
I installed the public beta of iOS 14 today and since then, the app has stopped working. It hangs up in the initial blank loading screen and stays there for eternity.

**Comment by ferdinand** [comment]
## Avoid duplicates

* ❌ Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/#ios_14_beta)
* ❌ Bug is not already reported in another [issue](https://github.com/corona-warn-app/cwa-app-ios/issues/783)

**Comment by gennadigennadigennadi** [comment]
The problem you are mentioning already occurs on the first 14 dev beta.

**Comment by codertrix** [comment]
From the release notes:


ExposureNotification isn’t currently available in iOS 14 beta.
