### ISSUE TITLE
Navigation bar image does not adapt to dark mode (HomeView)

### ISSUE THREAD

**Issue by tens0rfl0w** [corona-warn-app/cwa-app-ios#89]
## Describe the bug

The asset "navi_bar_icon.pdf" in "Assets.xcassets" is missing an dark appearance, so it looks off when 'dark mode' is selected as the 'userInterfaceStyle'. Also, the navigationItem is never redrawn after init creation, so even if there is an asset for the dark mode, when the app is running and the user initiates an appearance change, the navigationItem will not adapt to the new environment style.

## Expected behaviour
Expected handling | Current handling
------------ | -------------
<img src="https://user-images.githubusercontent.com/57523343/83405982-fb8be180-a40d-11ea-82aa-c1d9fccd63cb.png" width="70%" /> | <img src="https://user-images.githubusercontent.com/57523343/83405990-fcbd0e80-a40d-11ea-8436-ac4f05de03c0.png" width="70%" />

## Possible fix
* Creating an asset file (vector) with a white text color to display correctly when dark mode is enabled.
* Redraw the navigationItem when the appearance is changed (dark-to-light or vice versa).

I already created a vector file with the same specs as the current asset file but with a white text color and called the redrawing of the navigationItem inside the super method 'traitCollectionDidChange' from UIViewController. If it's possible to merge my commit, I will create a pull-request for this issue, so just let me know.

**Comment by haosap** [comment]
Hi @tens0rfl0w ,
Please go ahead.
Thanks.
