### ISSUE TITLE
Not working under iOS 14 Beta 2

### ISSUE THREAD

**Issue by paylinn** [corona-warn-app/cwa-app-ios#890]
## Describe the bug
After installing iOS 14 Open Beta the app shows just a Black screen 

## Expected behaviour
Starts App just like before 

## Steps to reproduce the issue
Install iOS while app is on the phone 

## Technical details

- iOS Version: Open Beta iOS 14
- Device: iPhone 11 Pro

**Comment by SebastianWolf-SAP** [comment]
Please see our FAQ https://www.coronawarn.app/de/faq/#ios_14_beta and and previous issues #889, #887, #886, #885, #854, #852, #847, #839, #836, #828, #806, #797, #788, #783, #777, #774, #772, #771, #765, #764, #760, #758, #757, #756 and #749.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by ifcologne** [comment]
Just a stupid idea to reduce spam... couldn't you leave one ticket open and add a note about the missing `Exposure Notification API` support in iOS 14 beta 2?

> [Release Notes iOS 14](https://developer.apple.com/documentation/ios-ipados-release-notes/ios-ipados-14-beta-release-notes):
> ExposureNotification isn’t currently available in iOS 14 beta. (64433241)
