### ISSUE TITLE
Incomplete checks, 7 days missing

### ISSUE THREAD

**Issue by jwildeboer** [corona-warn-app/cwa-app-ios#891]
Today, 2020-07-11, the number of checks performed by the app was halved for no apparent reason. It seems that 7 days of keys were removed. 

## Avoid duplicates

* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is not already reported in another issue

See #880 for same issue but as question. I think it's a (severe) bug that should be checked ASAP.

## Describe the bug

Number of checks should be 14 but is only 7. 

## Expected behaviour

14 checks. 

## Steps to reproduce the issue

Use app. Notice 14 checks yesterday, only 7 today.

![image](https://user-images.githubusercontent.com/873028/87223548-3c1c3a80-c37e-11ea-9d86-8622463bcef5.png)

## Technical details

- iOS Version: 13.5.1
- Device: iPhone 11 and iPhone SE (2016)
- App Version: 1.0.6 (0)

## Possible Fix

Check backend key generation. I suspect something is wrong there that causes the iOS app to discard 7 days worth of keys. 

## Additional context

See question at #880

**Comment by SebastianWolf-SAP** [comment]
Please don't open duplicate issues. We will address this in #880 

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
