### ISSUE TITLE
Blank screen only on iOS 14 beta 2 

### ISSUE THREAD

**Issue by Applaus-Klaus** [corona-warn-app/cwa-app-ios#894]
![0C9E66C7-16F1-4DDC-A6E0-78AF3416468B](https://user-images.githubusercontent.com/10243446/87230797-5c65ec80-c3b2-11ea-9779-e1b6c50213f9.png)
![0D665FB8-3C2C-40C7-9943-F0AFF4327FC8](https://user-images.githubusercontent.com/10243446/87230799-5e2fb000-c3b2-11ea-8fcb-65d14fa27b24.png)

## Technical details

- iOS Version: 14.0 (18A5319i)
- Device: iPhone XR (iPhone 11,8)

**Comment by ifcologne** [comment]
Reproduced using iPhone SE (2020) and iOS14 beta 2.

**Comment by Julian-B90** [comment]
I have the same issue on Iphone 7 and iOS14 beta 2.

**Comment by tens0rfl0w** [comment]
Guys come on, take a look at the [FAQ](https://www.coronawarn.app/de/faq/#ios_14_beta) or the closed issues on this repository before posting a new issue, there is a good reason the issue template has a checklist point where it asks you to check for duplicates.😐

This issue got posted several times in the last days and for the dev team it can get slightly annoying to read the same issue again and again without being able to fix it or give any further info than the information that is available on the [FAQ](https://www.coronawarn.app/de/faq/#ios_14_beta).

You can close this issue now!🙂

**Comment by Tt2015019881988** [comment]
gooood
