### ISSUE TITLE
Endless loop after phone migration 

### ISSUE THREAD

**Issue by Torell0** [corona-warn-app/cwa-app-ios#896]
I migrated from I’m iPhone 6s to iPhone 11  iOS 13.5.1
When I start the corona warn app it stucks in a endless loop of the start/intro screens (in german):

1. Gemeinsam Corona bekämpfen -> weiter
2. Datenschutz -> weiter 
...
6. Warnung erhalten... -> weiter 
7. back to 1.

Expected behavior:
a) Continue with the already collected data from old phone
b) notification about issue

**Comment by SebastianWolf-SAP** [comment]
Problems with backup/restore are already known, please follow-up in #754. 

Mit freundlichen Grüßen/Best regards,
SW
Corona Warn-App Open Source Team
