### ISSUE TITLE
IOS14 | App Screen black

### ISSUE THREAD

**Issue by Nollknolle** [corona-warn-app/cwa-app-ios#897]
Hey,
Seit dem iOS 14 Update sehe ich in der App nur noch einen schwarzen Bildschirm.

**Comment by SebastianWolf-SAP** [comment]
Please see our FAQ https://www.coronawarn.app/de/faq/#ios_14_beta and and previous issues #889, #887, #886, #885, #854, #852, #847, #839, #836, #828, #806, #797, #788, #783, #777, #774, #772, #771, #765, #764, #760, #758, #757, #756 and #749.

Mit freundlichen Grüßen/Best regards,
SW
Corona Warn-App Open Source Team
