### ISSUE TITLE
No COVID-19 region acceptance in iOS 14 Public Beta 2 

### ISSUE THREAD

**Issue by thomasgrota** [corona-warn-app/cwa-app-ios#898]
## Avoid duplicates

* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is not already reported in another issue

## Describe the bug
After installing apple IOS 14 Public Beta 2 on iPhone 8+ Germany is not recognised as region for COVID-19 region. It says „your region is not available“. 
Obviously it is a bug Apple has to take care of however it might be useful to adapt CoronaWarnApp documentation to avoid using iOS 14 Beta versions until this has been fixed by Apple. Currently users will find out after installing iOS 14 beta not being aware of this crucial issue. 

## Expected behaviour
COVID-19 exposure notification and protocol should be available in those regions it is available in iOS 13.5. 

## Steps to reproduce the issue
Install iOS 14 Public Beta 2 and look into iOS settings for COVID-19 exposure notifications and protocol. 
Start corona warn app and you will receive a blank screen inside the app. 

## Technical details

- iOS Version: 14 Public Beta 2
- Device: iPhone 8 Plus 

## Possible Fix
Add Documentation and description in AppStore for corona warn app that it will not work on iOS 14 at this point in time 
None. Waiting for fox by Apple in next Public Beta Version

**Comment by SebastianWolf-SAP** [comment]
Dear @thomasgrota,

thanks for your input. However, the relevant details around iOS 14 have already been documented in our FAQ and have been answered almost countless times. Please see https://www.coronawarn.app/de/faq/#ios_14_beta and and previous issues #889, #887, #886, #885, #854, #852, #847, #839, #836, #828, #806, #797, #788, #783, #777, #774, #772, #771, #765, #764, #760, #758, #757, #756 and #749.

Mit freundlichen Grüßen/Best regards,
SW
Corona Warn-App Open Source Team

**Comment by Tho-Mat** [comment]
@SebastianWolf-SAP 
May be this issue should also be pinned. It seams nobody looks at the closed issues.

**Comment by SebastianWolf-SAP** [comment]
@Tho-Mat Yes, that‘s really sad. Maybe that needs to be done... We‘ll see which one we can unpin instead. However, people often even ignore pinned issues or other hints/remarks - see here: It was explicitly confirmed that they haven’t found it in the FAQ or in other issues...
