### ISSUE TITLE
Won’t work with iOS 14

### ISSUE THREAD

**Issue by MCTzOCK** [corona-warn-app/cwa-app-ios#899]
## Avoid duplicates

* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is not already reported in another issue

## Describe the bug

The app won't work with iOS 14.0 (18A5319i). When I launch the app it only shows a white screen. 

## Expected behaviour

I expect that the app works with this iOS version

## Steps to reproduce the issue
![image](https://user-images.githubusercontent.com/53553315/87250401-c9d25580-c464-11ea-97ef-d1aaec913551.png)

## Technical details

- iOS Version: 14.0 (18A5319i)
- Device: iPhone XR 

## Additional context

**Comment by SebastianWolf-SAP** [comment]
Please see our FAQ https://www.coronawarn.app/de/faq/#ios_14_beta

Mit freundlichen Grüßen/Best regards,
SW
Corona Warn-App Open Source Team
