### ISSUE TITLE
Risiko Ermittlung inaktiv, sobald keine Netzverbindung besteht.

### ISSUE THREAD

**Issue by MBurchard** [corona-warn-app/cwa-app-ios#900]
## Fehlerbeschreibung

Bei einer Wanderung in einem Gebiet mit schlechter Netzabdeckung, zeigt die Anwendung an, dass die Risikoermittlung inaktiv wäre. Dies führt zum Nutzer doch zu einiger Verwunderung.

## Erwartetes Verhalten

Wenn man in den Alpen an einer Hütte sitzt ist die Erwartung, dass die App per Bluetooth weiterhin andere Kontakte anonym aufzeichnet.
Das gerade in diesem Moment keine Netzverbindung besteht sollte kein Problem sein, da die App ja nicht dauerhaft eine Netzverbindung braucht, sondern Warnmeldungen nach bisherigen Informationen nur einmal am Tag herunterladen muss.
Die Anwendung sollte erst dann den Benutzer warnen, wenn sie nach einem definierten Zeitraum keine Warnmeldungen mehr laden konnte.

## Steps to reproduce the issue

Gehen Sie wandern ;)

## Technical details

- iOS Version: 13.5.1
- Device: iPhone 8 (MQ6G2ZD/A)

**Comment by SebastianWolf-SAP** [comment]
Das Problem ist bekannt und eine Lösung befindet sich auch bereits im Backlog, alle Details finden sich im Issue https://github.com/corona-warn-app/cwa-backlog/issues/1

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
