### ISSUE TITLE
Error displaying infection risk after reset and restore of iOS device 

### ISSUE THREAD

**Issue by Anzugmensch** [corona-warn-app/cwa-app-ios#901]
## Avoid duplicates

* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is not already reported in another issue

## Describe the bug

Even though the app has been installed before the reset and re-installed via the iCloud-backup, the app was displaying that the risk assessment is deactivated. After clicking on that banner, the app forwards to the screen where the risk assessment can be activated and deactivated. However, it was activated by default (probably this state has been backed up as well). 

Turning if off and on again did not help. 

Even after re-collecting data for fourteen days after the reset the screen did not change. 

I have uninstalled and re-installed the app now but now the counter starts from zero again, meaning the app does not seem to use the data it has collected in the prior fourteen days, even though this data seems to still be stored on the device. 

I did do a COVID-Test today and I am expecting the result this evening. I am afraid that because the app does not use the data of the prior fourteen days, the app will not be able to take my possibly positive test result into account for the risk assessment of the people I have been in contact with. 

## Expected behaviour

App should correctly display risk and use data collected prior of fresh install. 

## Steps to reproduce the issue

1st Install app and use risk assessment feature. 
2nd after at least fourteen days of data collection, reset the device (full reset with full data deletion) and restore via iCloud-backup. 
3rd app should re-install via the backup and risk assessment should be activated by default but the screen should appear as noted above.
4th after fourteen more days the app should still display the wrong screen - at this point, only a re-install (only of the app, no full device reset) will fix it. However, with the re-install the app will not use the data collected in the fourteen days before, making the fourteen days of data collection redundant. 

## Technical details

- iOS Version: iOS 13.5.1
- Device: iPhone 11 Pro

**Comment by fredrb** [comment]
Thanks for raising the issue. First of all, I hope you're doing ok. 

Unfortunately, the [collected random ids are not backed up](https://www.coronawarn.app/en/faq/#backup). I can't say for sure if your diagnosis keys from the first 14 days are backed-up, but I suppose they are not. 

Nevertheless, if I understood your scenario correctly, you are using the app for at least 14 days on this new device/installation, correct? This means that in the unfortunate event that the result comes back positive, the app should publish all keys generated [in the last 14 days](https://www.coronawarn.app/en/faq/#data_access) for checking. Therefore, even if you still had the old keys, they were not going to be submitted to the server.

**Comment by Anzugmensch** [comment]
Yes, that’s right. The app has been in use for more than 14 days. However, since the app was showing all the time that I need to turn on risk assessment even though it was activated, and the app failed to show me my current risk, I decided to reinstall it. After re-installation the app displayed that a risk assessment is not possible, because it has not been in use for 14 days. That means that it appears like it does not use the previous data it has generated over the past 14 days but rather starts from new.

Am 13.07.2020 um 18:01 schrieb Frederico <notifications@github.com>:

﻿

Thanks for raising the issue. First of all, I hope you're doing ok.

Unfortunately, the collected random ids are not backed up<https://www.coronawarn.app/en/faq/#backup>. I can't say for sure if your diagnosis keys from the first 14 days are backed-up, but I suppose they are not.

Nevertheless, if I understood your scenario correctly, you are using the app for at least 14 days on this new device/installation, correct? This means that in the unfortunate event that the result comes back positive, the app should publish all keys generated in the last 14 days<https://www.coronawarn.app/en/faq/#data_access> for checking. Therefore, even if you still had the old keys, they were not going to be submitted to the server.

**Comment by SebastianWolf-SAP** [comment]
This could also be a simply display error - the app probably simply doesn't notice that there are still existing keys stored in the framework. No matter what's the case: In case the test returns positive (we of course hope that it will not!), please simply follow the usual steps to share the exposure keys via the given QR-Code or the given teleTAN. 

We will tackle the backup/restore issue in #754 and will close this issue accordingly. Keeping all fingers crossed for you! 

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
