### ISSUE TITLE
Version 1.0.6 Confused about Exposure setting

### ISSUE THREAD

**Issue by melancholyaeon** [corona-warn-app/cwa-app-ios#902]
Hi!

iPhone XS, iOS 13.5.1
Warn app 1.0.6

Updated my app the other day & now it thinks my exposure logging is off, even tho'  it's on everywhere in the app & in the iOS Settings. 

It tells me to activate what's already activated! See screenshot in comment.  I downloaded this app on launch date & it worked great until the latest update. 

As a result, I'm uploading any info to you nor receiving any from you. Please fix.

Ty!

**Comment by SebastianWolf-SAP** [comment]
Thank you very much, @daimpi for the links. We just moved it to the iOS repository but will close it as we already have #872 which collects all reports and workarounds for this issue.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
