### ISSUE TITLE
Daten Reset bei nach Flugmodus 

### ISSUE THREAD

**Issue by ItchyWriggler** [corona-warn-app/cwa-app-ios#903]
Nach kurzem Versetzen des Handys in den Flugmodus waren alle Daten zur Bewegungs-Aufzeichnung verloren. Ich hatte die App direkt davor und danach geöffnet und konnte es so explizit darauf beziehen. In der Nacht zuvor war das Handy auch im Flugmodus, das Problem trat aber nicht auf. 
Bei der technischen Hotline sagte man mir, dass die Daten wohl nicht weg seien und durch ein Update wieder sichtbar gemacht werden könnten. Aber auch nach dem Update zeigt mir die App wieder an, dass keine Risikoermittlung möglich ist. 

Ich benutze ein iPhone 7 mit iOS 13.5.1
Die App Version bei auftreten des Bugs war eine der ersten, jetzt ist es die 1.0.6 

Die Screenshots sind von gerade eben, der Reset fand gestern Mittag statt und das Update auf die neue Version gestern Abend. 

![735ED7EC-7898-4F92-AD62-F41A85110A3E](https://user-images.githubusercontent.com/68268396/87393615-be8b4100-c5ae-11ea-8598-2f3c07e433b7.png)
![EDBB95C4-9487-4FBE-9B78-CC625CC3A5D5](https://user-images.githubusercontent.com/68268396/87393620-c1863180-c5ae-11ea-9ccb-7b6a68b9acec.png)

---
Internal Tracking ID: EXPOSUREAPP-1934

**Comment by SebastianWolf-SAP** [comment]
Danke für die Rückmeldung! Auch wir gehen im Moment davon aus, dass es sich hierbei "nur" um ein Anzeigeproblem handelt und die Kontaktprotokolle nach wie vor auf dem Gerät verfügbar sind. Wir werden das allerdings abklären.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by schuderer** [comment]
@ItchyWriggler Ich hatte auch schon einmal ein sehr ähnliches Phänomen. Die Anzeige hat sich bei mir nach einem Neustart des iPhones selbst normalisiert.

**Comment by heinezen** [comment]
We cannot reproduce this error anymore, so I assume this is fixed. If not, please make a comment and we will check again.

----
Corona-Warn-App Open Source Team
