### ISSUE TITLE
Wie meldet sich ein Nutzer wieder Gesund?

### ISSUE THREAD

**Issue by theMoe** [corona-warn-app/cwa-app-ios#906]
Wenn man die Corona Erkrankung überstanden hat, wie kann sich der Nutzer dann wieder gesund melden über die App? Oder werden weiterhin dann neue App Begegnungen automatisch über eine Gefährdung informiert?

**Comment by ferdinand** [comment]
Wenn sich ein Nutzer positiv meldet werden nur **einmalig** die Schlüssel der letzten 14 Tage bereitgestellt. Nach einem positiven Testergebnis sollte man sich, bis man gesund ist, in Quarantäne begeben und entsprechend keine Kontakte mehr haben die benachrichtigt werden könnten.

**Comment by SebastianWolf-SAP** [comment]
Vielen Dank für die Frage. Wir haben hierzu einen kleinen Eintrag in den FAQ unter https://www.coronawarn.app/de/faq/#recovered veröffentlicht.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by markusbrand** [comment]
Die Lösung, die in den FAQ beschrieben wird, die App über die Einstellungen zurücksetzen ist doch etwas tollpatschig und für low-level user schon ärgerlich (brauche da nur an meine Mutter zu denken). Dieses Feature sollte meiner Meinung nach schon implementiert werden, dass so etwas über die App selbst geht.

**Comment by Ein-Tim** [comment]
@markusbrand 
This Issue is now tracked here: https://github.com/corona-warn-app/cwa-wishlist/issues/115
Feel free to upvote there 👍
