### ISSUE TITLE
Checks are never made within the promised 24 hours. It is always (sometimes far) longer.

### ISSUE THREAD

**Issue by jwildeboer** [corona-warn-app/cwa-app-ios#918]
## Avoid duplicates

* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is not already reported in another issue

## Describe the bug

The app promises that a check is done every 24 hours. In reality it is always more, sometimes even far more.

## Expected behaviour

Checks happen every 24 hours with a maximum tolerance of +/- 1 hour

## Steps to reproduce the issue

Install app, wait :)

## Technical details

- iOS Version: 13.6, before 13.5.2
- Device: iPhone 11 and SE 1st Gen
- CWA version: Always updated, currently on 1.0.7

## Possible Fix

Possible workaround (not solution): Allow manual check when last check is more than 24 hours ago. ATM the app will only show the manual check button when background check is disabled or last check has failed for other (connectivity) reasons.

## Additional context

The iPhone 11 is my "daily driver" and I frequently start the app to check. At least 2-3 times per day. The SE 1st Gen is my corporate phone where especially on the weekend i might not open the app for several days.

## iPhone SE 1st Gen

Date | Time | Time between updates (h:mm)
-----|----|---
2020-07-17 | 14:39 | 28:12
2020-07-16 | 10:27 | 37:42
2020-07-15 | - | No Check performed
2020-07-14 | 21:45 | 32:40
2020-07-13 | 13:05 | 39:55
2020-07-12 | - | No Check performed
2020-07-11 | 21:10 | 24:21
2020-07-10 | 20:49 | 24:30
2020-07-09 | 20:19 | 24:53
2020-07-08 | 19:26 | 24:39
2020-07-07 | 18:47 | -

## iPhone 11

Date | Time | Time between updates (hh:mm)
-----|----|---
2020-07-17 | 10:52| 24:26
2020-07-16 | 10:26 | 24:05
2020-07-15 |10:21 | 24:16
2020-07-14 | 10:05 | 24:12
2020-07-13 | 09:53 | 24:00
2020-07-12 | 09:53 | 24:20
2020-07-11 | 09:33 | 28:40
2020-07-10 | 05:53 | 24:49
2020-07-09 | 05:04 | -

**Comment by jwildeboer** [comment]
This behaviour is mentioned in several bugs and questions, but I thought it would be good to have one with a clear definition to collect more data from other users. I went through the information in my settings manually to create the tables. So if I made mistakes with calculating the difference, sorry :)

**Comment by SebastianWolf-SAP** [comment]
Well, it is probably easier to change the titles of already existing issues - which I just did with #916. Please follow-up and collect the data there. Thank you very much!

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
