### ISSUE TITLE
[IOS 13.6, iPhone xr] CWA interferes with bluetooth tethering

### ISSUE THREAD

**Issue by MarieCurie13** [corona-warn-app/cwa-app-ios#932]
Since I've installed the CWA on my iPhone xr bluetooth tethering is not working anymore. I need bluetooth tethering to get online traffic information for my car's navigation system. In order to get online traffic information during driving I would have either to switch off (or uninstall) the CWA or use a second smartphone. I think, both is not an option. Other bluetooth functionalities seem to work. It would be great if this could be solved.

Thanks.

## Avoid duplicates

* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is not already reported in another issue

## Technical details

- iOS Version: 13.6
- Device: iPhone Xr

**Comment by SebastianWolf-SAP** [comment]
Please report this issue back to Apple as also mentioned in our FAQ: https://www.coronawarn.app/en/faq/#various_device_problems We've seen several issues like that in the past, but we as app developers can't do anything about it. The issues need to be know and fixed by the device/OS vendors.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by MarieCurie13** [comment]
Guten Tag,

danke für das Feedback.


Leider ist das Apple Support System so abgeschottet, wenn man kein Apple Care(+) hat, dass man gar nicht ein Problem melden kann. Es wäre viel sinnvoller, wenn das von der Corona Warn App Seite an Apple herangetragen werden kann, da ja die Systemaenderungen im ISO ja extra fuer diesen Zweck implementiert wurden.

Mit freundlichen Grüßen 

Karin Daum

**Comment by pizuz** [comment]
> Guten Tag, danke für das Feedback. Leider ist das Apple Support System so abgeschottet, wenn man kein Apple Care(+) hat, dass man gar nicht ein Problem melden kann. Es wäre viel sinnvoller, wenn das von der Corona Warn App Seite an Apple herangetragen werden kann, da ja die Systemaenderungen im ISO ja extra fuer diesen Zweck implementiert wurden. Mit freundlichen Grüßen Karin Daum
> […](#)

Hallo Karin,

Schon mal die Apple-Feedback-Seite probiert?

https://www.apple.com/feedback/

Grüße
Florian
