### ISSUE TITLE
Error 13: Unable to recover 

### ISSUE THREAD

**Issue by Amin-Rehman** [corona-warn-app/cwa-app-ios#941]
Dear Team
I have encountered this issue where I am unable to essentially use the app. I have somehow managed to enter this Error 13 unrecoverable state over the past couple of days 
![4F79D53A-CD57-4C9E-B986-F79A1CBDFDF4](https://user-images.githubusercontent.com/22418475/88341574-190a6700-cd3e-11ea-8d91-aff0c59cc732.png)

I don’t want to reinstall the app as I don’t wish to lose my persisted data also was wondering if my broken state could provide any useful telemetry or debug info at all.

**Comment by inf2381** [comment]
Thanks for bringing this up. We would need a bit more information:
* What iOS version did you install?
* What version of the app are you currently running?
* If you upgraded to iOS 13.6, did you reboot your device after the upgrade?

Thanks in advance

**Comment by gigiCom** [comment]
same here, iOS 13.6, error since App version 1.1.1 (3)

**Comment by tkowark** [comment]
Unfortunately, without further information, we cannot further investigate this issue since we are unable to reproduce it. In case this happens again, please kindly provide the required information.
