### ISSUE TITLE
App shows sometimes "no internet connection"

### ISSUE THREAD

**Issue by HeiDasGri** [corona-warn-app/cwa-app-ios#942]
## Describe the bug

Sometimes when I open the App, it shows no Internet connection. I have used other Apps before and afterwards, which did not have any problem with connectivity.  The only way to fix it is to swipe the app and start it again. 

I didn't find any pattern, when it appears. 

## Technical details

- iOS Version: 13.6
- Device: iPhone 8
- App Release 1.1.1 (not observed in other releases befor)
## Possible Fix

![A](https://user-images.githubusercontent.com/67737547/88370326-20f3f680-cd92-11ea-90c5-b87219736db1.png)
![B](https://user-images.githubusercontent.com/67737547/88370338-25b8aa80-cd92-11ea-8e05-0855c9439f8c.png)
Recommend way to go to setting is useless, because Internet was already there:
![D](https://user-images.githubusercontent.com/67737547/88370452-5993d000-cd92-11ea-92e3-a9ecbb8c1e88.png)

![c](https://user-images.githubusercontent.com/67737547/88370343-294c3180-cd92-11ea-9fbf-cf6e0c035b40.png)

---
Internal Tracking Id: EXPOSUREAPP-1572

**Comment by inf2381** [comment]
We will remove the connectivity feature completely in 1.3.0. The PR for that feature should come next week.

**Comment by JonasHeidelberg** [comment]
@inf2381 , could you elaborate a bit more? Are you removing the feature where the app attempts to judge if there is an internet connection? If, is this because there are too many false positives? I can only second @HeiDasGri in that this sometimes happens, both on my phone and on my partner's phone (both iOS).

**Comment by inf2381** [comment]
@JonasHeidelberg checking the internet connection constantly is a bad practice for mobile applications that don't require a constant connection. So whenever internet connection is required (e.g. when submitting yourself as infected), we'll attempt to connect and if that fails, we'll prompt that to the user. If you don't need internet connection, the app will not check it anymore. So you can be "offline", but still have active tracing.

**Comment by JonasHeidelberg** [comment]
@inf2381 that makes sense. The data download of the keys is done by iOS, correct? So as long as I am not being tested, both collecting keys through Bluetooth, and matching them with the keys on the central server, happens without the cwa needing internet connectivity itself?

**Comment by ferdinand** [comment]
@JonasHeidelberg No, the app downloads the keys. Accordingly, it requires an Internet connection.

**Comment by fredrb** [comment]
> No, the app downloads the keys. Accordingly, it requires an Internet connection.

That's correct. 

@JonasHeidelberg: As @ferdinand pointed out, the application needs internet connectivity to download the diagnosis keys from positive COVID tests. These keys are checked on your phone against any exposure keys collected via bluetooth.

**Comment by ouboub** [comment]
> We will remove the connectivity feature completely in 1.3.0. The PR for that feature should come next week.

Good, I can confirm this (annoying) behaviour. The only fix is to close and reopen the app.
This warning message does not prevent the app from working correctly, fortunately

**Comment by mitchvdl** [comment]
When this behaviour happens the phone starts draining the battery. This is in the last 24h. It's the top application using the battery during this time.

![0D3B2DA6-8D6A-418F-8547-927E069E5D86](https://user-images.githubusercontent.com/1120324/89099127-6bf2b700-d3ed-11ea-9b6d-e535bdde6b6f.png)

**Comment by daimpi** [comment]
Related to: https://github.com/corona-warn-app/cwa-backlog/issues/1

**Comment by UGatgithub** [comment]
Just opened the App and it was connected as it immediately refreshed at 00:01 but it showed this.

![0846A439-01DE-44AA-9250-240065802FBB](https://user-images.githubusercontent.com/30733304/89587333-bc30a580-d841-11ea-9ebb-d7b6510b4013.png)

**Comment by kereng5** [comment]
It happens with Android too. Sometimes the app shows "keine Internetverbindung" while the diagnosis keys are downloaded from the server. I write this comment mainly to make it possible to find this issue by searching for the German text "keine Internetverbindung".
