### ISSUE TITLE
Remove ambiguity of UI when background refresh is deactivated

### ISSUE THREAD

**Issue by alanrick** [corona-warn-app/cwa-app-ios#947]
## Current Implementation
When _Background App Refresh_ is disabled in the iPhone settings then the CoronaWarn app does not refresh, but instead displays an update button. 

Because of the repeated assurances from podcasts, press-releases.... that once you install and activate the app you no longer have to do anything, I assumed, **wrongly**, that even though my risk and data display in the UI did not change, the IDs would be periodically exchanged and I'd be notified when I was at risk. I had assumed that the update button was simply to update the screen UI, not the ID exchange or risk-assessment.

Background: I have _Background App Refresh_ disabled so that my iPhone does not need charging until I go to bed. Other apps performed well in the background (blue-tooth key-finder, blue-tooth lock, Ring, WhatsApp...) so I had assumed the same for the CoronaWarn app. This is not the case.
 

## Suggested Enhancement
If _Background Refresh App_ is disabled in the iPhone settings, then a warning should be displayed above the risk assessment  similar to the _No Internet Connection_ warning. E.g. _Background data-exchange deactivated._
Or the _Update_ button could include the text (_because Background Refresh deactivated_)

## Expected Benefits
Users who have disabled background refresh wouldn't be misled by the podcasts and press coverage of the app to believe that it nevertheless works without manual intervention. This is particularly important for the iOS app because iPhones have a reputation for losing power before the end of the day and disabling app refresh is a common remedy.

![CoronaWarnAppMisleading](https://user-images.githubusercontent.com/7034358/88393921-ce7cff00-cdbe-11ea-82eb-b2116cbbe16b.jpg)

---
Internal Tracking ID: EXPOSUREAPP-1735

**Comment by melloskitten** [comment]
Hi there! Thanks for submitting this issue. 
Some time ago, we have added an error alert that gets triggered. This alert informs the user that they will have to manually refresh if they have their background fetch turned off in the settings.
You can find the PR here: https://github.com/corona-warn-app/cwa-app-ios/pull/883

**Comment by alanrick** [comment]
Thanks. Is the alert still sent when the app is running in the background, despite background refresh being switched off?

**Comment by melloskitten** [comment]
This is sent if you enter the home screen and you have not switched on background fetch. But this alert is only shown once. (and i believe it will be part of the next release, so thats why you havent seen it yet probably). If you are not content that this is enough, i suggest posting into our cwa wishlist repo.
