### ISSUE TITLE
Share the app

### ISSUE THREAD

**Issue by stritti** [corona-warn-app/cwa-app-ios#950]
Would be could if there would be a share button to distribute the app via iMessage, Mail, ...

**Comment by Ein-Tim** [comment]
![image](https://user-images.githubusercontent.com/67682506/88453444-28390400-ce67-11ea-8f84-af782b4aba9a.jpeg)

**Comment by fredrb** [comment]
As @Ein-Tim pointed out, you should have a button on the main screen to share the app. In English the button is called `Share the Corona-Warn-App`. 

@stritti can you confirm that you have the button?

**Comment by jwildeboer** [comment]
Yes. It's there. And offers sharing via all mentioned methods. 

![image](https://user-images.githubusercontent.com/873028/88455640-3db62a00-ce77-11ea-8393-e50ae038313b.png)

![image](https://user-images.githubusercontent.com/873028/88455644-43ac0b00-ce77-11ea-91c8-7a28089289b8.png)

**Comment by stritti** [comment]
Oh sorry, yes there it is! The tree in forrest. I looked for the typical share icon.
