### ISSUE TITLE
Zeitstempel der Bewegungsüberprüfungen geraten beim Tagesübergang durcheinander

### ISSUE THREAD

**Issue by apuehl** [corona-warn-app/cwa-app-ios#956]
## Avoid duplicates

* [x ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x ] Bug is not already reported in another issue

## Describe the bug
CWA 1.1.1 (3)

Da die Probleme aus #916 und #921 auch auf meinem iphone aufgetreten sind, habe ich in den letzten 3-4 Tagen die Begegnungsüberprüfungen genauer verfolgt und dabei festgestellt, dass beim Übergang von einem auf den anderen Tag 
(in meinem Fall vom 24.07. auf den 25.07.) eine fehlerhafte Konstellation entstanden ist. 

1.) Heute (25.7.2020 00:13) ist noch korrekt
2.) Gesstern (24.7.2020  **23:52**) wird nicht angezeigt bzw. fehlt
3.) Dafür Vorgestern (23.7.2020 **23:52**) statt 23.7.2020 **23:47**
4.) Dafür (22.7.2020 **23:47**) statt 22.7.2020 23:43

Für mich sieht das so aus als hätten sich die Zeitstempel verschoben. 

Die Bewegungsüberprüfungen habe ich jeweils händisch durch Öffen der App angestossen, da ich die Hintergrundverarbeitung überprüfen wollte, die nicht stattgefunden hat. Deshalb bin ich mir auch recht sicher, dass hier ein Tag fehlt und die anderen verschoben sind. 

Ob bzw. wie sich das im System auswirkt kann ich nicht sagen und ob das ein Problem der App oder der Software auf dem Server ist auch nicht, aber ich denke sie sollten sich das genauer anschauen. 

## Technical details

- iOS Version: 13.6
- Device: iphone 6s

## Additional context

]
![1Unbenannt](https://user-images.githubusercontent.com/68196752/88461224-00b35d00-cea2-11ea-965e-35511babde7a.PNG)
![IMG_0272](https://user-images.githubusercontent.com/68196752/88461294-98b14680-cea2-11ea-9f5b-ade83e67383d.PNG)
![IMG_0273](https://user-images.githubusercontent.com/68196752/88461299-9ea72780-cea2-11ea-8e5a-813e2ae2cc46.PNG)

**Comment by GPclips** [comment]
@apuehl thanks for pointing that out. We will take care of this issue and discuss it with the development team.

**Comment by thomasaugsten** [comment]
Hi könntest du bitte das Verhalten mit der Version 1.1.2 überprüfen ob sie immer noch auftritt.

**Comment by apuehl** [comment]
Hallo Thomas.

Wie meinst du das? Soll ich den Übergang von einem auf den anderen Tag noch mal mit der Version 1.1.2 durchführen und protokollieren?

mfg
Armin Pühl

Von: Thomas Augsten
Gesendet: Sonntag, 26. Juli 2020 21:09
An: corona-warn-app/cwa-app-ios
Cc: apuehl; Mention
Betreff: Re: [corona-warn-app/cwa-app-ios] Zeitstempel der Bewegungsüberprüfungen geraten beim Tagesübergang durcheinander (#956)

Hi könntest du bitte das Verhalten mit der Version 1.1.2 überprüfen ob sie immer noch auftritt.

**Comment by thomasaugsten** [comment]
Ich meine du solltest auf die aktuelle Version 1.1.2 Updates die App einmal starten und die tagsübergänge im Auge behalten ob sie sich nochmal so verhalten wie du sie beschrieben hast oder das von dir beschriebene Verhalten weg ist.

**Comment by apuehl** [comment]
Werde ich machen. Melde mich in 2Tagen wieder.

**Comment by apuehl** [comment]
Hallo Thomas.
Ich muss mich korrigieren.  Ich habe die Datenkonstellation nicht richtig interpretiert. Ich bin davon ausgegangen dass ich für jeden zurückliegenden Tag (lückenlos) ein Protokoll sehen sollte. Da aber eine Aktualisierung nach mehr als 24 Std. stattfindet, kommt es beim Tagesübergang dazu, dass für einen Tag (für ein Datum) kein Protokoll erstellt wird. Das ist etwas verwirrend aber grundsätzlich nicht falsch. Es handelt sich hier wohl um keinen bug sondern eher um ein Verständnis- bzw. Darstellungsproblem. Tut mir leid, wenn ich euch unnötige Arbeit gemacht haben sollte. Aus meiner Sicht könnt ihr den Vorgang schliessen.

**Comment by tkowark** [comment]
Hallo @apuehl ,

vielen Dank trotzdem für das melden der Auffälligkeit. Wir schauen lieber einmal zu viel drauf, als das ein tieferliegender Fehler durchrutscht.
