### ISSUE TITLE
Bleibt bei Installation auf IOS14 am Punkt Benachrichtigen hängen.

### ISSUE THREAD

**Issue by ricosn** [corona-warn-app/cwa-app-ios#957]
## Avoid duplicates

* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is not already reported in another issue

## Technical details

- iOS Version:
- Device:

**Comment by tkowark** [comment]
https://www.coronawarn.app/en/faq/#ios14
