### ISSUE TITLE
verwirrende Batterieanzeige

### ISSUE THREAD

**Issue by STW65** [corona-warn-app/cwa-app-ios#958]
## Avoid duplicates

* [ x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ x] Bug is not already reported in another issue

## Describe the bug
CWA 1.1.2

In den Einstellungen/Batterie wird fälschlicherweise eine andere APP (Tile) mit hoher Hintergrundaktivität angezeigt. Ich hätte die CWA App erwartet. Die angezeigte Tile APP verwendet auch BLE im Hintergrund (war zu diesem Zeitpunkt nicht aktiv).
Das Ganze lässt sich auf einem 2ten iPhone (XS) nachvollziehen.

## Steps to reproduce the issue

![Corona_112](https://user-images.githubusercontent.com/65548131/88509439-60645200-cfe1-11ea-95df-c350d93fbafb.png)

## Technical details

- iOS Version: 13.6
- Device: iPhone 11    @##pro

**Comment by SebastianWolf-SAP** [comment]
Die Anzeige und Überprüfung des Batterieverbrauchs wird vom iOS-Betriebssystem verantwortet. Es ist nicht ersichtlich, weswegen diese Anzeige hier falsche Informationen darstellt. Offensichtlich ist in diesem Fall wirklich die App 'Tile' für einen erhöhten Energieverbrauch - wahrscheinlich im Hintergrund - verantwortlich. Bitte wenden Sie sich diesbezüglich an den Hersteller der App Tile.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
