### ISSUE TITLE
ENErrorDomain Error 11

### ISSUE THREAD

**Issue by markus597** [corona-warn-app/cwa-app-ios#972]
## Avoid duplicates

* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is not already reported in another issue

## Describe the bug

Error still persists with iOS 13.6

## Technical details

- iOS Version: iOS 13.6
- Device: iPhone Xr

## Additional context

---
Internal Tracking ID: EXPOSUREAPP-1911

**Comment by GPclips** [comment]
@markus597 thanks for reaching out. This issue has been handeled in thread https://github.com/corona-warn-app/cwa-app-ios/issues/759 already.

Best regards,
LMM
Corona-Warn-App Open Source Team

**Comment by tkowark** [comment]
Sorry for the confusion. If you experience Error 11 on iOS 13.6., we need to further investigate with Apple under which circumstances this occurs.

**Comment by CarlosTheKin** [comment]
Nicht gut

**Comment by tkowark** [comment]
@CarlosTheKin are you experiencing the issue yourself? If so, please provide the details mentioned above. Otherwise, it would be great if we can focus on the technical details.

**Comment by FroWi** [comment]
Iphone 8, Ios 13.5.1, error occured always after starting corona app since today. Last update was longer ago thn 24 hours. Until last update i regurlary had the error, thats not sure, if in this country is an app support. This errors is gone

**Comment by tkowark** [comment]
As stated in the [FAQ](https://www.coronawarn.app/de/faq/#ENError11) iOS **13.6** should reliably fix this issue. If you are still experiencing it, please update and comment if the error **still** occurs in iOS 13.**6**.

**Comment by Hefeprinz** [comment]
IOS14 Public Beta 4
iPhone 11
Fehler 11

**Comment by Ein-Tim** [comment]
> IOS14 Public Beta 4
> 
> iPhone 11
> 
> Fehler 11

CWA doesn't support iOS 14 Betas at the moment. Take a look at the [FAQ](https://www.coronawarn.app/de/faq/?search=Ios+14#ios_14_beta)

**Comment by Hefeprinz** [comment]
> > IOS14 Public Beta 4
> > iPhone 11
> > Fehler 11
> 
> @Hefeprinz CWA doesn't support iOS 14 Beta at the moment. Take a look at the [FAQ](https://www.coronawarn.app/de/faq/?search=Ios+14#ios_14_beta)

Zeit dem Publicity Beta 4 sollte es wieder funktionieren

**Comment by Ein-Tim** [comment]
> > > IOS14 Public Beta 4
> 
> > > iPhone 11
> 
> > > Fehler 11
> 
> > 
> 
> > @Hefeprinz CWA doesn't support iOS 14 Beta at the moment. Take a look at the [FAQ](https://www.coronawarn.app/de/faq/?search=Ios+14#ios_14_beta)
> 
> 
> 
> Zeit dem Publicity Beta 4 sollte es wieder funktionieren 

![image](https://user-images.githubusercontent.com/67682506/89708366-ca341280-d976-11ea-82c9-1a5e6199e531.jpeg)

**Comment by tkowark** [comment]
This issue is (was) indeed dedicated to iOS 13.6. Since we did not receive any further reports of error 11 occurring there, we'll close this issue accrodingly. If it re-occurs on other, supported operating systems, please open another dedicated issue.

Thank you all for your input!

**Comment by svengabr** [comment]
We got two additional reports of this error in the past days so I have re-opened this issue.

So far we got:

* [iPhone 11 with 14.0.1](https://github.com/corona-warn-app/cwa-app-ios/issues/1296)
* [iPhone 11 with iOS 14.2 Beta (has worked prior 14.0, error appeared since 14.0 update)](https://github.com/corona-warn-app/cwa-app-ios/issues/1284)

**Comment by Ein-Tim** [comment]
@svengabr Could we delete the iOS 13.6 from the Issue title? Thanks

**Comment by svengabr** [comment]
Could you please update to iOS 14.2 and the latest CWA version and report if the error is now resolved for you?

Thank you very much!

**Comment by dsarkar** [comment]
@franzi1802, and community, can you confirm that this issue is resolved for you?

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
Dear community, 

Thanks for contributing. This seems resolved. We will close this issue now. If necessary, please, don't hesitate to re-opening this issue.

Best wishes,
DS

---
Corona-Warn-App Open Source Team
