### ISSUE TITLE
iOS: Notification of a dangerous encouter, but the app does not mention anything. State missmatch

### ISSUE THREAD

**Issue by Wandang** [corona-warn-app/cwa-app-ios#973]
## Avoid duplicates

* [ x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ x] Bug is not already reported in another issue

## Describe the bug
A red notification poped up 2 days ago warning of risk encounters. After opening the notification to read more detail the app showed the usual zero risk encouters, everything is fine screens (everything is green).

## Expected behaviour
App shows information about the amount of risc encounters(maybe even time of encounter) and what to do next.
Colors change according to thread level/notification color.

## Steps to reproduce the issue

Since iOS does not have a notification history (I did not find any, android does have that) I was lost.
Unfortunately therefore there is no proof/reconstruction possible.

## Technical details

- iOS Version: 13.6
- Device: iPhone 8

## Possible Fix

Possible related is the iOS updater issue. Maybe my notification is actually over 2 weeks old and just got pushed?
But I checked/opened the app at least every 2nd day. So this might be a dead end.

**Comment by sin-azucar** [comment]
The push notification was probably this one:
https://twitter.com/The_Shadowghost/status/1286588016392310784

This seems to be a new feature in iOS 13.6.

Are you sure it said something about >0 risk encounters or was it like in the screenshot on Twitter? The red icon looks alarming, but doesn't necessarily mean anything (apparently even Apple has a hard time finding good UX people... 😢).

**Comment by Wandang** [comment]
The problem is the user(aka me) in this case. I only read the color red + "encounter" and immediately opened the notification. So I cannot tell you what number value was actually in the message. (Additionally I am not accustomed to iOS and assumed every notification has an in-app reaction/counterpart that get's executed like I am used to in Android)
**Hopefully** this was it and this ticket can be closed. Until more user have the same (initial) issue (with >0 encounters) this should be handled as if it was a mistake by the user.

Thanks for linking that tweet.
Nevertheless I went to get tested today.
