### ISSUE TITLE
Make app refresh work in Low power mode

### ISSUE THREAD

**Issue by ouboub** [corona-warn-app/cwa-app-ios#974]
## Avoid duplicates

* [x] This issue has not already been raised before
* [ ] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation

When Low Power mode is enabled, background app refresh is disabled.

## Suggested Enhancement

Since this app is of vital interest this feature should work if low power mode is activated.

## Expected Benefits

Low power mode is very useful especially in older phones with limited battery capacity. 
Running background app refresh is an essential feature, so it should be enabled **always**
Regards
Uwe Brauer

**Comment by GPclips** [comment]
Hi @ouboub, this relates to https://github.com/corona-warn-app/cwa-app-ios/issues/650 and therefore has been labeled as duplicate.

**Comment by ouboub** [comment]
Hi
I read this request. The author only asked to **clarify** the implication of the low power mode.
 I ask to **change** the behaviour and run always
 Why is this the same issue?
Is it possible for the app, to run even in low power mode?

**Comment by SebastianWolf-SAP** [comment]
Yes, there was obviously a misunderstanding. Sorry for that! However, low power mode and background task was just recently a topic in https://github.com/corona-warn-app/cwa-app-ios/issues/916#issuecomment-665750860. We have reports that it works smoothly with the most recent version. However, please check it out yourself and please report back in #916 if it doesn't. We need to consolidate the reports there.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by ouboub** [comment]
ok, thanks for the clarification (BTW german or english? this is github, aber vielleicht ist es ein bißchen lächerlich wenn Deutsche auf Englisch schreiben, für eine App die sowieso nur in Deutschland läuft....

**Comment by tkowark** [comment]
English is the preferred language. Some of our developers primarily speak english and there's also a lot of international interest in the app (see also here: https://github.com/corona-warn-app/cwa-documentation#working-language)

**Comment by ouboub** [comment]
Ok, thanks for the clarification, makes sense. Just the mit freundlichen Grüßen confused me.
 BTW a pity that this app is not used in other EU countries, Spain comes into my mind, which is still struggleing to get its own app working, but this is a entirely different subject.
