### ISSUE TITLE
Invert order of presenting diagnosis keys to the EN framework

### ISSUE THREAD

**Issue by ndegendogo** [corona-warn-app/cwa-app-ios#982]
## Avoid duplicates

* [x] This issue has not already been raised before
* [x] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation

The diagnosis keys are downloaded from the server, and then presented to the EN framework in order of time (oldest first). But sometimes it happens that the presenting process is aborted prematurely. We have seen this e.g. with EN error 13 (too many keys). In such a case the newest keys are not taken into account at all for the risk calculation.

## Suggested Enhancement

If you invert the order of keys and present the newest keys first to the EN framework, then even in case of abort every key is at least involved once in the risk calculation, because the older keys were already presented yesterday (although with possibly different risk configuration).

## Expected Benefits

Improved coverage of the diagnosis keys in the risk assessment, even in exceptional scenarios (abort of the procedure).

---
Internal Tracking ID: EXPOSUREAPP-3000

**Comment by GPclips** [comment]
Hello @ndegendogo ,

thank you for sharing your Idea with us. It has been noted and will be discussed with the development team as soon as possible.

Keep up the good work and let us know if you have additional ideas!

Thanks,
LMM

Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@ndegendogo If I don't miss anything I think this has been changed, or?

**Comment by ndegendogo** [comment]
@Ein-Tim Yes, you are right. They feed the hourly files of today first, before the daily files of the past days. So in case of prematurely abort / exception of the loop, there is hopefully still a partial result, and if yes, it has performed the most interesting checks on the youngest files first.

I am closing this ticket.

**Comment by dsarkar** [comment]
Dear @ndegendogo, @Ein-Tim, Thanks for cross-checking! 

Best wishes,
DS

---
Corona-Warn-App Open Source Team
