### ISSUE TITLE
App startet nicht nach Installation über Apples Schnellstart-Feature

### ISSUE THREAD

**Issue by aketo-gmbh** [corona-warn-app/cwa-app-ios#984]
Ich habe ein neues iPhone eingerichtet und dafür Apples Schnellstart-Funktion benutzt, also alle Daten von einem alten Gerät übertragen. Die App lässt danach nicht mehr starten sondern man läuft nur endlos durch den Loop der Startbildschirme. Habe die App dann gelöscht und neu installiert, daraufhin kommen die im Startprozess üblichen zusätzlichen Abfragen zu Mitteilungen und Bluetooth und die Anwendung arbeitet.

Ich halte das sofern das Verhalten bestätigt wird für dringend. Man erhält zu keinem Zeitpunkt einen Hinweis darauf, dass die App nach der Übertragung nicht mehr arbeitet.

**Comment by ferdinand** [comment]
Ist ein bekanntes Problem. Siehe https://www.coronawarn.app/de/faq/#migration_Apple und #754.

**Comment by SebastianWolf-SAP** [comment]
Vielen Dank, @ferdinand für die Hinweise auf die bestehende Dokumentation und das existierende Issue. Wir schließen dieses Issue und würden bitten, die Diskussion in #754 fortzusetzen.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
