### ISSUE TITLE
App not useable when recreating iPhone from backup

### ISSUE THREAD

**Issue by Cedric97** [corona-warn-app/cwa-app-ios#986]
## Avoid duplicates

* [ x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x ] Bug is not already reported in another issue

## Describe the bug

The configuration process of the first app start goes into a loop, when the iPhone have been recreated from an backup. The app needs to be deleted and reloaded from the App Store. 

## Expected behaviour

Normal start I think? 

## Steps to reproduce the issue

- Create iPhone backup via iCloud
- delete iPhone completely 
- recreate iPhone via iCloud Backup
- Open App
- configuration goes into loop

## Technical details

- iOS Version: iOS 13.6
- Device: iPhone 11 128GB

## Possible Fix

Work around:
- delete app
- reload app from App Store
- done.

**Comment by Cedric97** [comment]
Had this problem when switching from iPhone 11 to iPhone 7+ and again when switching back.

**Comment by sin-azucar** [comment]
This is clearly already in the FAQ (https://www.coronawarn.app/en/faq/#migration_Apple) and there is an open issue for it (https://github.com/corona-warn-app/cwa-app-ios/issues/754)

**Comment by Cedric97** [comment]
Oh crap, haven't seen it. :/ My fault, sry

**Comment by GPclips** [comment]
Hello @Cedric97 and @sin-azucar ,

I will close the issue due to the fact that it is a duplicate, as @sin-azucar already mentioned.

Thanks,
LMM

Corona-Warn-App Open Source Team
