### ISSUE TITLE
IOS14.0 App is Not Running Black Screen

### ISSUE THREAD

**Issue by SmonSE** [corona-warn-app/cwa-app-ios#987]
## Avoid duplicates

* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is not already reported in another issue

## Describe the bug

After update iPhone SE2 to IOS14.0 (Beta3) Corona Warn-App was not more running (black screen).
After uninstall and reinstall the app stuck in config mode. Buttons "next" and "not allow" are without any interaction. After close Corona Warn-App and reopen black screen is shown!

## Expected behaviour

Corona Warn-App should work with IOS14. 

## Steps to reproduce the issue

Update iPhone to IOS14.0

![image](https://user-images.githubusercontent.com/68323384/89067040-c8fb5800-d36e-11ea-9fb3-ece9efc22feb.png)

## Technical details

- iOS Version: 14.0 Beta3 
- Device: iPhone SE2 

## Possible Fix

Build Corona Warn-App against latest IOS. 

## Additional context

**Comment by tkowark** [comment]
[FAQ](https://www.coronawarn.app/de/faq/#ios_14_beta)
[Pinned Issue](https://github.com/corona-warn-app/cwa-app-ios/issues/749)

And from the release notes of iOS 14 BETA:
<img width="752" alt="Screen Shot 2020-07-31 at 21 13 58" src="https://user-images.githubusercontent.com/164467/89069156-e9c5ac80-d372-11ea-8025-bbf6c24d29bb.png">
