### ISSUE TITLE
Code Coverage Badge & Changes

### ISSUE THREAD

**Issue by Jeehut** [corona-warn-app/cwa-app-ios#99]
## Current Implementation

There's no code coverage badge for the main branch and also no way to see the difference on pull requests.

## Suggested Enhancement

Add a coverage badge to the README and setup a service to automatically post coverage changes to PRs.

## Expected Benefits

Long term improved code coverage and therefore also increased trust from our users (which is important for this app to become a success).

**Comment by Jeehut** [comment]
I could fix this myself if I had access to the [organization](https://github.com/orgs/corona-warn-app) (currently I can't add any GitHub Apps like Codacy, CodeCov or CodeClimate).

**Comment by tkowark** [comment]
Hi @Jeehut , thanks for the pointer. We'll find a solution for that to add code coverage information to the repo.

**Comment by Jeehut** [comment]
@ChristianKienle I don't know what happened, but I just checked the `README.md` on the `development` branch and there's still no code coverage badge anywhere to be seen. Could you please reopen this and check what happened?

**Comment by tkowark** [comment]
Hi @Jeehut , yes there was a problem with the PR and we had to revert. I'll reopen the ticket until the badge appears.
