### ISSUE TITLE
Misguiding alert message text concerning # of possible risk-contacts in a week

### ISSUE THREAD

**Issue by bfassbender** [corona-warn-app/cwa-app-ios#992]
## Current Implementation
On iOS with CWA I got the following message yesterday. At first I immediately wondered, how 0 (zero) possible contacts could be true, with me having stayed at several locations well within reach of other peoples' phones in the past 10 days.

![IMG_1511](https://user-images.githubusercontent.com/1222080/89122796-a3836100-d4ca-11ea-9788-1b09220b7b13.jpeg)

## Suggested Enhancement
I'd say the text should read "... 0 mögliche *Risiko*begegnungen ..." as this is more fitting to what the alert is about.
I hope you can put this forward to Apple in case you should agree to the enhancement and this message comes from iOS level and not from CWA.

## Expected Benefits
iOS users do not get confused if their app is working correctly, when reading "0 mögliche Begegnungen ", but "0 mögliche Risikobegegnungen in dieser Woche"

**Comment by Ein-Tim** [comment]
I don't think that the developers from SAP/Telekom can do anything about that, this is a message from iOS...

**Comment by databus23** [comment]
I think this notification is not managed by the Corona-Warn-App. I think, although I have found no official confirmation, it was introduced by Apple with iOS 13.6. So it might be that the CWA Team has no means to change wording (or even influence if and how the notification is shown).

**Comment by SebastianWolf-SAP** [comment]
Dear @bfassbender,

thanks for reporting this issue.  @databus23 is completely right. This message is issues by Apple's exposure notification framework itself. We are also mentioning that in our FAQ: https://www.coronawarn.app/en/faq/#notif_weekly_update

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by bfassbender** [comment]
Hmm okay. I really hoped you have some way to put this forward to Apple as I assumed you are in connection with them on the notification framework anyways. Placing such things in a FAQ is a workaround.

**Comment by SebastianWolf-SAP** [comment]
Forgot to mention that. Of course, this one is one aspect of our regular calls with Apple. But in the end, they decide what they change and when...

Mit freundlichen Grüßen/Best regards,
SW
Corona Warn-App Open Source Team

**Comment by bfassbender** [comment]
Thanks, I too believe this is all you can do in this case. If it helps to file a report directly with Apple, just point me to the right URL and I'll do that.

**Comment by pdehaye** [comment]
This issue has also been flagged in [Switzerland](https://github.com/corona-warn-app/cwa-app-ios/issues/992).

**Comment by Ein-Tim** [comment]
@SebastianWolf-SAP wouldn't it be possible to show a notification to iOS 13.6 App user that makes it clearer that this is expected behaviour? For example like the Swiss did it [here](https://github.com/DP-3T/dp3t-config-backend-ch/pull/58).


By the way, I'm for communicating more directly via the app, few users will read the FAQ. 
But if there is a notification on the start page (like mentioned above) which provides important information, these informations would reach a larger group of users.

**Comment by pdehaye** [comment]
The Swiss correction is not sufficient. It doesn't explain to users situations where they are told "x mögliche begegnungen" (with x > 0) and the app decides not to notify. I presume this is also applicable to CoronaWarnApp.

**Comment by Ein-Tim** [comment]
Yeah that's right, although I think the intention from the Swiss developers wasn't to explain which contacts are displayed and which not, they only wanted to clarify that the App works.

**Comment by pdehaye** [comment]
Any clarification that doesn't address all the anticipated confusion points is likely to create more confusion.

**Comment by SebastianWolf-SAP** [comment]
> @SebastianWolf-SAP wouldn't it be possible to show a notification to iOS 13.6 App user that makes it clearer that this is expected behaviour? For example like the Swiss did it [here](https://github.com/DP-3T/dp3t-config-backend-ch/pull/58).
> 
> By the way, I'm for communicating more directly via the app, few users will read the FAQ.
> But if there is a notification on the start page (like mentioned above) which provides important information, these informations would reach a larger group of users.

Yes, also from my perspective the colleagues developing SwissCOVID go into the right direction, but we probably need to go beyond that. It's always a complicated assessment and balancing which elements reach the app and which ones not. As UX, accessibility etc. needs to be taken into account it also takes a little longer than just updating the FAQ. ;) 

Bringing more information, FAQ etc. into the app has been on our list for quite a while, but as you know we need to fix some important bugs first. As of now, I don't have detailed and confirmed information when and what will be in the app with respect to that. But please continue giving us feedback and such good hints. :)

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
