### ISSUE TITLE
Corona Warn App

### ISSUE THREAD

**Issue by Esraakguen** [corona-warn-app/cwa-app-ios#995]
Iphone 8, IOS 13.5.1  Fehler Corona Warn App

**Comment by Ein-Tim** [comment]
Welchen Fehler haben Sie?

**Comment by Esraakguen** [comment]
Fehler 11 wird angezeigt.

Ein_Tim <notifications@github.com> schrieb am Di. 4. Aug. 2020 um 07:41:

**Comment by Ein-Tim** [comment]
ENErrorDomain Error 11, oder Fehler 11?

**Comment by Esraakguen** [comment]
Ein_Tim <notifications@github.com> schrieb am Di. 4. Aug. 2020 um 07:44:

**Comment by Ein-Tim** [comment]
Also ENErrorDomain Error 11 wurde mit iOS 13.6 behoben (siehe #759)

**Comment by Ein-Tim** [comment]
Sollten Sie den Fehler nach dem Update weiterhin haben, schreiben Sie das bitte bei #972.

**Comment by GPclips** [comment]
Hello @Esraakguen ,

thanks for reaching out. I kindly would like to ask you if you please could provide more information. 
Please also check the issues mentioned by @Ein-Tim (https://github.com/corona-warn-app/cwa-app-ios/issues/759 and https://github.com/corona-warn-app/cwa-app-ios/issues/972) and if your error fits either of these descriptions, I invite you to comment there.

Thanks,
LMM

Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@GPclips I think we can close this now 🤷‍♂️
