### ISSUE TITLE
Configuration not working

### ISSUE THREAD

**Issue by xander1401** [corona-warn-app/cwa-app-ios#996]
## Avoid duplicates

* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is not already reported in another issue

## Describe the bug
I can’t finish the setup because I can’t turn the notification on.

## Expected behaviour

Normal first start of the app

## Steps to reproduce the issue

1. Reinstall the app
2. Follow the configuration
3. I can’t turn notification on or off

- See the video for further information

## Technical details

- iOS Version: iOS 14 public beta 3
- Device: iPhone 7+

**Comment by Ein-Tim** [comment]
Duplicate of #886

**Comment by xander1401** [comment]
https://drive.google.com/file/d/18WxD2lO7BKIgZccwgGdk1JpIQBo7Ezqb/view?usp=drivesdk
It is not a duplicate

**Comment by Ein-Tim** [comment]
You are using iOS 14 Beta.
Look at [Apples Beta Release Notes Page](https://developer.apple.com/documentation/ios-ipados-release-notes/ios-ipados-14-beta-release-notes) and find that Exposure Notification isn't available at iOS 14 Beta.
![image](https://user-images.githubusercontent.com/67682506/89261125-d8f48f80-d62d-11ea-90d2-2d9ea340ae1f.jpeg)

**Comment by xander1401** [comment]
Ok, I thought it might be another issue because I couldn’t turn the normal notification on

**Comment by Ein-Tim** [comment]
Maybe you've turned on notifications but than the App couldn't load the next screen (because of the missing  ExposureNotification framework) and for you it looked like you couldn't turn notifications on. 
So or so I'm sure the App will work when iOS 14 is released.

**Comment by Ein-Tim** [comment]
I've got an update for you:
According to @tens0rfl0w in #749 the App now works under iOS 14 **Developer** Beta 4.
