### ISSUE TITLE
Compatibility with other European apps installed on the same iPhone (Spain)

### ISSUE THREAD

**Issue by ouboub** [corona-warn-app/cwa-app-ios#997]
## Avoid duplicates
* [x] Question is not already answered in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Question has not already been asked in another issue

## Your Question

I will travel to Spain, which has its own similar app. I know it is not compatible with the Coronavirus Warn app in the sense, that both apps, yet, do not communicate.
Is it save to have both apps installed?
Or will that cause problems?
thanks

**Comment by Ein-Tim** [comment]
Yes, it should be safe to install another App. 
You can change between the Apps in Settings.

**Comment by ouboub** [comment]
> Yes, it should be safe to install another App.
> You can change between the Apps in Settings.
Thanks but what do you mean: change between the apps in settings?

**Comment by Ein-Tim** [comment]
You can only use one App with the ExposureNotification Framework active. 
If you install the Spain App, and allow it to use the Framework, the 
German App can't use the Framework at the same time. 
Change between Apps in Settings (Privacy->Health->COVID-19 Exposure Logging->Active App)

**Comment by ouboub** [comment]
Ok, 
this was precisely, what I was not sure about. 

thanks for you clarification!!
So this restriction on the ExposureNotification is due to Apple (or to Android)?

**Comment by Ein-Tim** [comment]
> So this restriction on the ExposureNotification is due to Apple (or to Android)?

Yes

**Comment by ouboub** [comment]
thanks to Ein-Tim for his clarifications
