### ISSUE TITLE
European corona gateway: beta testers

### ISSUE THREAD

**Issue by ouboub** [corona-warn-app/cwa-app-ios#999]
## Avoid duplicates
* [x] Question is not already answered in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Question has not already been asked in another issue

## Your Question

According to 
https://www.reuters.com/article/us-health-coronavirus-europe-tech/sap-deutsche-telekom-to-build-corona-app-gateway-for-european-commission-idUSKCN24W277
there will be a gateway which allows some corona warn apps (which most likely share the same model) to communicate.
I would be **extremly** interesting in testing any beta version, since I live in Germany and in Spain.

**Comment by RalphRichter** [comment]
I would volunteer to test with the SwissCovid App

**Comment by GPclips** [comment]
Hello @ouboub and @RalphRichter,

I will discuss this internally with the responsible people.

Thanks,
LMM

Corona-Warn-App Open Source Team

**Comment by ouboub** [comment]
Hello LMM

thanks, I appreciate that.

**Comment by GPclips** [comment]
Hello @ouboub,

just addressed this internally and we will get back to you as soon as possible. We need to clarify if and how we can make this work.

Thanks,
LMM

Corona-Warn-App Open Source Team

**Comment by ouboub** [comment]
> Hello @ouboub,
> 
> just addressed this internally and we will get back to you as soon as possible. We need to clarify if and how we can make this work.
> 
> Thanks,
> LMM
> 
> Corona-Warn-App Open Source Team

thanks I will be in Spain, in the middle of September, but already installed the spanish Corona Virus App. 
Spain was plagued by its federal structure and that is why the app is officially working in the whole of Spain only since a couple of days.
regards
Uwe Brauer

**Comment by Marco2907** [comment]
Hello @ouboub and @RalphRichter, we discussed this point internally and I want to give you the following information about the beta testing... The test of the EFGS and the interaction with the individual systems are tested in special test environments. A public available beta version is not planned. If the system is running productively, 2 apps from 2 different countries on one mobile phone are no longer necessary as long as both countries are connected to the EFGS.

Thanks,
MP

Corona-Warn-App Open Source Team

**Comment by ouboub** [comment]
> Hello @ouboub and @RalphRichter, we discussed this point internally and I want to give you the following information about the beta testing... The test of the EFGS and the interaction with the individual systems are tested in special test environments. A public available beta version is not planned. If the system is running productively, 2 apps from 2 different countries on one mobile phone are no longer necessary as long as both countries are connected to the EFGS.
> 
> Thanks,
> MP
> 
> Corona-Warn-App Open Source Team

HI 

thanks for letting us know. It is a bit of a pity, because I think a **real** beta test could reveal bugs that an artificial test environment cannot. 
In any case, any idea about the timeline? When would this EFGS gateway be available?
truth being told, the situation in Spain is a bit of a disaster.
The official app is still not running due to Rivalries between the different autonomic states.   
Anyhow

**Comment by r-r-liu** [comment]
Hi,

I'm very interested in this possibility, because I live in Basel but am often Germany.  I've been told that, for Switzerland, this might be problem, as Switzerland does not belong to the EU.  Of course, if there is no exchange of exposure keys with Switzerland, Germans who work in Switzerland have a problem, too.  Do you have any idea what the status is?

**Comment by Marco2907** [comment]
Hi @r-r-liu , thanks for sharing your content. Actually it is not planned there will be no solution which covers Germany and Switzerland. New updates will be communicated publicly.

Thanks,
MP

Corona-Warn-App Open Source Team
